import {createHash,randomUUID} from 'node:crypto';
import sourceDocument from '../../../../config/pricing/zao-2026-27-v1.draft.json';
import type {Pool,PoolClient} from 'pg';
import {loadStaff,type Permission,type StaffPrincipal} from '../../../auth/src/staff-auth';
import {HoldError,canonical,newIntakeWindow,utcDate,type HoldConditions} from '../../../contracts/src/hold';
import {PricingError,parseQuote,parseCoupon,validateTable,INITIAL_TABLE,PRICE_PRODUCTS,DURATIONS,PRIVATE_QUOTE_TTL_SECONDS,calculate,id,exact,money,timestamp,type PriceTable,type CouponTerms,type QuoteInput} from '../../../contracts/src/pricing';
type Conn=Pick<PoolClient,'query'>;
type Book={id:string;created_by:string;source_book_id:string|null;source_sha256:string;table_jpy:PriceTable;state:string;rental_from:string;rental_until:string;revision:number};
type QuoteRow={id:string;actor:string;request_fingerprint:string;book_id:string;activation_id:string;coupon_id:string|null;hold_id:string|null;conditions:HoldConditions;snapshot:Record<string,unknown>;snapshot_sha256:string;expires_at:Date};
const hash=(v:unknown)=>createHash('sha256').update(canonical(v)).digest('hex');
const sourceHash=hash(sourceDocument);
export class QuoteService {
 constructor(private pool:Pool,private principal:StaffPrincipal,private clock?:()=>Date){}
 private async auth(c:Conn,permission:Permission='QUOTE_VIEW',stores:string[]=[]){const p=await loadStaff(c as Pick<Pool,'query'>,this.principal.subject);if(!p||p.revision!==this.principal.revision||!p.permissions.includes('QUOTE_VIEW')||!p.permissions.includes(permission)||stores.some(s=>!p.storeIds.includes(s as never))||permission==='PRICE_EDIT'&&(p.role!=='ADMIN'||p.scope!=='ALL'))throw new PricingError('FORBIDDEN',403);return p;}
 private async time(c:Conn){return this.clock?.()??(await c.query<{now:Date}>('SELECT inventory_clock() AS now')).rows[0]!.now;}
 private async tx<T>(permission:Permission,preflight:(c:Conn)=>Promise<void>,work:(c:PoolClient,now:Date)=>Promise<T>,inventory=false){await this.auth(this.pool,permission);await preflight(this.pool);let c:PoolClient|undefined;try{c=await this.pool.connect();await c.query('BEGIN');await c.query("SET LOCAL lock_timeout='1500ms';SET LOCAL statement_timeout='5000ms';SET LOCAL idle_in_transaction_session_timeout='10000ms'");await this.auth(c,permission);await preflight(c);if(inventory)await c.query('SELECT pg_advisory_xact_lock(71820600)');await c.query('SELECT pg_advisory_xact_lock(71820800)');await this.auth(c,permission);await preflight(c);await c.query("SELECT set_config('zao.actor',$1,true)",[this.principal.subject]);const result=await work(c,await this.time(c));await c.query('COMMIT');return result;}catch(e){await c?.query('ROLLBACK').catch(()=>{});if(e instanceof HoldError)throw e;const code=(e as {code?:string}).code;if(['23505','23514','23503'].includes(code??''))throw new PricingError('PRICE_CONFLICT',409);if(['55P03','57014','40001','40P01'].includes(code??''))throw new PricingError('INDETERMINATE',503);throw new PricingError('QUOTE_OPERATION_FAILED',500);}finally{c?.release();}}
 private async read<T>(work:(c:PoolClient,now:Date)=>Promise<T>){let c:PoolClient|undefined;try{c=await this.pool.connect();await c.query('BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY');await c.query("SET LOCAL statement_timeout='5000ms'");await this.auth(c);const result=await work(c,await this.time(c));await c.query('COMMIT');return result;}catch(e){await c?.query('ROLLBACK').catch(()=>{});if(e instanceof HoldError)throw e;throw new PricingError('INDETERMINATE',503);}finally{c?.release();}}
 private async book(c:Conn,bookId:string){id(bookId);const b=(await c.query<Book>('SELECT *,rental_from::text,rental_until::text FROM price_books WHERE id=$1',[bookId])).rows[0];if(!b)throw new PricingError('BOOK_NOT_FOUND',404);return b;}
 private range(from:string,until:string){if(utcDate(until)<utcDate(from)||utcDate(until)-utcDate(from)>3660*86400000)throw new PricingError('INVALID_RENTAL_RANGE');}
 async createDraft(bookId:string,sourceId:string|null,from:string,until:string){id(bookId);if(sourceId)id(sourceId);this.range(from,until);return this.tx('PRICE_EDIT',async()=>{},async c=>{const source=sourceId?await this.book(c,sourceId):null;await c.query('INSERT INTO price_books(id,created_by,source_book_id,source_sha256,table_jpy,rental_from,rental_until) VALUES($1,$2,$3,$4,$5,$6,$7)',[bookId,this.principal.subject,sourceId,source?.source_sha256??sourceHash,JSON.stringify(source?.table_jpy??INITIAL_TABLE),from,until]);return this.book(c,bookId);});}
 async editDraft(bookId:string,revision:number,product:string,d:string,amount:number){id(bookId);money(amount);if(!Number.isInteger(revision)||revision<1||!PRICE_PRODUCTS.some(p=>p.key===product)||!DURATIONS.includes(d))throw new PricingError('INVALID_PRICE_ENTRY');return this.tx('PRICE_EDIT',async()=>{},async c=>{const b=await this.book(c,bookId);if(b.state!=='DRAFT'||b.revision!==revision)throw new PricingError('STALE_PRICE_DRAFT',409);const table=structuredClone(b.table_jpy);table[product]![d]=amount;validateTable(table);await c.query('UPDATE price_books SET table_jpy=$2,revision=revision+1 WHERE id=$1',[bookId,JSON.stringify(table)]);return this.book(c,bookId);});}
 async activate(bookId:string,revision:number,effectiveAt:string,predecessorId:string|null){id(bookId);if(predecessorId)id(predecessorId);effectiveAt=timestamp(effectiveAt);if(!Number.isInteger(revision)||revision<1)throw new PricingError('INVALID_VERSION');return this.tx('PRICE_EDIT',async()=>{},async(c,now)=>{const b=await this.book(c,bookId);if(b.state!=='DRAFT'||b.revision!==revision)throw new PricingError('STALE_PRICE_DRAFT',409);if(new Date(effectiveAt)<now)throw new PricingError('BACKDATED_ACTIVATION',409);validateTable(b.table_jpy);await c.query("UPDATE price_books SET state='PRIVATE_AVAILABLE',revision=revision+1 WHERE id=$1",[bookId]);const activationId=randomUUID();await c.query('INSERT INTO price_activations(id,book_id,effective_at,predecessor_id) VALUES($1,$2,$3,$4)',[activationId,bookId,effectiveAt,predecessorId]);return {book:await this.book(c,bookId),activationId};});}
 async initializePrivate(key:string,from:string,until:string){id(key);this.range(from,until);return this.tx('PRICE_EDIT',async()=>{},async(c,now)=>{const prior=(await c.query('SELECT * FROM price_books WHERE id=$1',[key])).rows[0];if(prior){const b=await this.book(c,key);if(b.created_by!==this.principal.subject||b.rental_from!==from||b.rental_until!==until||b.source_book_id!==null)throw new PricingError('IDEMPOTENCY_MISMATCH',409);return b;}if((await c.query('SELECT 1 FROM price_books LIMIT 1')).rowCount)throw new PricingError('PRIVATE_PRICE_ALREADY_INITIALIZED',409);await c.query('INSERT INTO price_books(id,created_by,source_sha256,table_jpy,rental_from,rental_until) VALUES($1,$2,$3,$4,$5,$6)',[key,this.principal.subject,sourceHash,JSON.stringify(INITIAL_TABLE),from,until]);await c.query("UPDATE price_books SET state='PRIVATE_AVAILABLE',revision=revision+1 WHERE id=$1",[key]);await c.query('INSERT INTO price_activations(id,book_id,effective_at) VALUES($1,$2,$3)',[randomUUID(),key,now]);return this.book(c,key);});}
 async createCoupon(couponId:string,input:unknown){id(couponId);const terms=parseCoupon(input);return this.tx('PRICE_EDIT',async()=>{},async c=>{await c.query('INSERT INTO coupon_versions(id,code,terms) VALUES($1,$2,$3)',[couponId,terms.code,JSON.stringify(terms)]);return {id:couponId,terms};});}
 private async activeBook(c:Conn,now:Date){const a=(await c.query<{id:string;book_id:string}>('SELECT id,book_id FROM price_activations WHERE effective_at<=$1 ORDER BY effective_at DESC LIMIT 1',[now])).rows[0];if(!a)throw new PricingError('NO_PRIVATE_PRICE_BOOK',409);return {activation:a,book:await this.book(c,a.book_id)};}
 async catalog(){return this.read(async(c,now)=>{const books=(await c.query('SELECT id,state,revision,rental_from::text,rental_until::text FROM price_books ORDER BY created_at,id')).rows;const active=(await c.query('SELECT id,book_id,effective_at FROM price_activations WHERE effective_at<=$1 ORDER BY effective_at DESC LIMIT 1',[now])).rows[0]??null;return {products:PRICE_PRODUCTS,books,active,sourceState:'DRAFT_SOURCE_PRIVATE_COPY_ONLY',productionAvailable:false,taxDisplayBasis:'PENDING_OWNER_CONFIRMATION',quoteTtlSeconds:PRIVATE_QUOTE_TTL_SECONDS};});}
 // Preserve the existing pricing error contract for past/ended rentals; newly open
 // same-day periods now pass the shared admission check instead of comparing startsAt.
 private intake(conditions:HoldConditions,now:Date){try{return newIntakeWindow(conditions.period,now);}catch(e){if(e instanceof HoldError&&['PERIOD_ENDED','START_DATE_PAST'].includes(e.code))throw new PricingError('RENTAL_ALREADY_STARTED',409);throw e;}}
 async preview(value:unknown){const input=parseQuote(value);if(input.holdId!==null||input.couponCode!==null)throw new PricingError('INVALID_PREVIEW');return this.read(async(c,now)=>{await this.auth(c,'QUOTE_VIEW',[input.conditions.pickupStore,input.conditions.returnStore]);await this.validateVariants(c,input.conditions);this.intake(input.conditions,now);const {book,activation}=await this.activeBook(c,now);if(input.conditions.period.startDate<book.rental_from||input.conditions.period.endDate>book.rental_until)throw new PricingError('PRICE_PERIOD_NOT_COVERED',409);return {...calculate(book.table_jpy,input,now,null),priceBookId:book.id,activationId:activation.id,advisory:true};});}
 async options(){return this.read(async c=>({variants:(await c.query('SELECT v.id,v.family,v.age,v.tier,v.size,m.name FROM ledger_variants v JOIN ledger_models m ON m.id=v.model_id ORDER BY v.family,v.size,v.id')).rows,holds:(await c.query("SELECT id,conditions,expires_at FROM inventory_holds WHERE owner_id=$1 AND state='ACTIVE' AND pickup_store=ANY($2::text[]) AND return_store=ANY($2::text[]) ORDER BY created_at DESC LIMIT 100",[this.principal.subject,(await this.auth(c)).storeIds])).rows}));}
 private async attention(c:Conn,holdId:string,now:Date){return Boolean((await c.query(`SELECT 1 FROM inventory_claims cl JOIN transfer_pieces p ON p.id=cl.transfer_piece_id JOIN transfer_batches b ON b.id=p.batch_id WHERE cl.active AND cl.hold_id=$1 AND (b.issue IS NOT NULL OR (b.planned_ready_at<$2 AND p.state NOT IN ('READY','CLOSED'))) LIMIT 1`,[holdId,now])).rowCount);}
 private async hold(c:Conn,input:QuoteInput,now?:Date){await this.auth(c,'QUOTE_CREATE',[input.conditions.pickupStore,input.conditions.returnStore]);if(!input.holdId)return null;const h=(await c.query('SELECT * FROM inventory_holds WHERE id=$1',[input.holdId])).rows[0];if(!h||h.owner_id!==this.principal.subject)throw new PricingError('FORBIDDEN',403);await this.auth(c,'QUOTE_CREATE',[h.pickup_store,h.return_store]);if(hash(h.conditions)!==hash(input.conditions))throw new PricingError('HOLD_CONDITIONS_MISMATCH',409);if(now&&(h.state!=='ACTIVE'||h.expires_at<=now))throw new PricingError('HOLD_EXPIRED_OR_RELEASED',409);if(h.transfer_attention||now&&await this.attention(c,h.id,now)||!['NONE','FAILURE'].includes(h.payment_state))throw new PricingError('HOLD_RECONCILIATION_REQUIRED',409);return h;}
 private async validateVariants(c:Conn,conditions:HoldConditions){for(const m of conditions.members)for(const item of m.items){const rows=(await c.query('SELECT id,family,age,tier FROM ledger_variants WHERE id=ANY($1::uuid[])',[item.variantIds])).rows;if(rows.length!==item.variantIds.length||rows.some(v=>v.family!==item.family||v.age!==m.age||v.tier!==m.tier))throw new PricingError('VARIANT_CONDITIONS_MISMATCH',422);}}
 async create(key:string,value:unknown){id(key);const input=parseQuote(value),fingerprint=hash(input);return this.tx('QUOTE_CREATE',async c=>{await this.auth(c,'QUOTE_CREATE',[input.conditions.pickupStore,input.conditions.returnStore]);if(input.holdId){const h=(await c.query('SELECT owner_id,pickup_store,return_store FROM inventory_holds WHERE id=$1',[input.holdId])).rows[0];if(!h||h.owner_id!==this.principal.subject)throw new PricingError('FORBIDDEN',403);await this.auth(c,'QUOTE_CREATE',[h.pickup_store,h.return_store]);}},async(c,now)=>{
 const prior=(await c.query<QuoteRow>('SELECT * FROM price_quotes WHERE actor=$1 AND request_key=$2',[this.principal.subject,key])).rows[0];if(prior){if(prior.request_fingerprint!==fingerprint)throw new PricingError('IDEMPOTENCY_MISMATCH',409);return {quote:await this.view(c,prior,now),replayed:true};}
 const h=await this.hold(c,input,now);await this.validateVariants(c,input.conditions);const intake=this.intake(input.conditions,now);const {book,activation}=await this.activeBook(c,now);if(input.conditions.period.startDate<book.rental_from||input.conditions.period.endDate>book.rental_until)throw new PricingError('PRICE_PERIOD_NOT_COVERED',409);
 const coupon=input.couponCode?(await c.query<{id:string;terms:CouponTerms}>('SELECT id,terms FROM coupon_versions WHERE code=$1',[input.couponCode])).rows[0]:null;
 const calculated=calculate(book.table_jpy,input,now,coupon?.terms??null);if(coupon?.terms.maxActiveReservations!==null&&coupon?.terms.maxActiveReservations!==undefined&&Number((await c.query('SELECT count(*) AS n FROM coupon_reservations WHERE coupon_id=$1 AND expires_at>$2',[coupon.id,now])).rows[0].n)>=coupon.terms.maxActiveReservations)throw new PricingError('COUPON_LIMIT_REACHED',409);
 const limits=[now.getTime()+PRIVATE_QUOTE_TTL_SECONDS*1000,Date.parse(intake.quoteBoundaryAt)];if(h)limits.push(h.expires_at.getTime());if(coupon)limits.push(Date.parse(coupon.terms.validUntil));if(calculated.advance.status==='ESTIMATED_PAYMENT_NOT_VERIFIED')limits.push(Date.parse(calculated.advance.cutoff));const expires=new Date(Math.min(...limits));if(expires<=now)throw new PricingError('DISCOUNT_WINDOW_CLOSED',409);
 const quoteId=randomUUID(),snapshot={...calculated,priceBookId:book.id,activationId:activation.id,conditions:input.conditions,expiresAt:expires.toISOString(),fingerprint,couponVersionId:coupon?.id??null,productionGates:['TAX_UNCONFIRMED','PAYMENT_UNCONNECTED','COUPON_REDEMPTION_UNCONNECTED','PRIVATE_DEVELOPMENT_ONLY'],zeroTotalPath:calculated.totalJpy===0?'MANUAL_NO_PAYMENT_CONFIRMATION_REQUIRED':'NOT_ZERO'};
 await c.query('INSERT INTO price_quotes(id,actor,request_key,request_fingerprint,book_id,activation_id,coupon_id,hold_id,hold_version,conditions,snapshot,snapshot_sha256,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)',[quoteId,this.principal.subject,key,fingerprint,book.id,activation.id,coupon?.id??null,input.holdId,h?.version??null,JSON.stringify(input.conditions),JSON.stringify(snapshot),hash(snapshot),expires]);return {quote:await this.view(c,(await c.query<QuoteRow>('SELECT * FROM price_quotes WHERE id=$1',[quoteId])).rows[0]!,now),replayed:false};},true);}
 private async view(c:Conn,q:QuoteRow,now:Date){await this.auth(c,'QUOTE_VIEW',[q.conditions.pickupStore,q.conditions.returnStore]);if(q.actor!==this.principal.subject)throw new PricingError('FORBIDDEN',403);if(hash(q.snapshot)!==q.snapshot_sha256)throw new PricingError('SNAPSHOT_INTEGRITY_ERROR',409);let validity=now>=q.expires_at?'EXPIRED':'VALID_PRIVATE_ESTIMATE';if(validity==='VALID_PRIVATE_ESTIMATE'&&q.hold_id){const h=(await c.query('SELECT * FROM inventory_holds WHERE id=$1',[q.hold_id])).rows[0];if(!h||h.state!=='ACTIVE'||h.expires_at<=now)validity='HOLD_EXPIRED_OR_RELEASED';else if(hash(h.conditions)!==hash(q.conditions))validity='HOLD_CONDITIONS_MISMATCH';else if(h.transfer_attention||now&&await this.attention(c,h.id,now)||!['NONE','FAILURE'].includes(h.payment_state))validity='HOLD_RECONCILIATION_REQUIRED';}return {id:q.id,snapshot:q.snapshot,snapshotSha256:q.snapshot_sha256,holdId:q.hold_id,validity,chargeReady:false};}
 async get(quoteId:string){id(quoteId);return this.read(async(c,now)=>{const q=(await c.query<QuoteRow>('SELECT * FROM price_quotes WHERE id=$1',[quoteId])).rows[0];if(!q)throw new PricingError('QUOTE_NOT_FOUND',404);return this.view(c,q,now);});}
 async list(){return this.read(async(c,now)=>{const p=await this.auth(c);const qs=(await c.query<QuoteRow>(`SELECT * FROM price_quotes WHERE actor=$1 AND conditions->>'pickupStore'=ANY($2::text[]) AND conditions->>'returnStore'=ANY($2::text[]) ORDER BY created_at DESC,id LIMIT 100`,[this.principal.subject,p.storeIds])).rows;const result=[];for(const q of qs)result.push(await this.view(c,q,now));return result;});}
 // Future booking adapter boundary ONLY; deliberately absent from all HTTP routes. Quotes alone never consume capacity.
 async reserveCoupon(quoteId:string,operationKey:string){id(quoteId);id(operationKey);return this.tx('QUOTE_CREATE',async c=>{const q=(await c.query<QuoteRow>('SELECT * FROM price_quotes WHERE id=$1',[quoteId])).rows[0];if(!q||q.actor!==this.principal.subject)throw new PricingError('FORBIDDEN',403);await this.auth(c,'QUOTE_CREATE',[q.conditions.pickupStore,q.conditions.returnStore]);},async(c,now)=>{const q=(await c.query<QuoteRow>('SELECT * FROM price_quotes WHERE id=$1',[quoteId])).rows[0]!;const view=await this.view(c,q,now);if(view.validity!=='VALID_PRIVATE_ESTIMATE'||!q.coupon_id)throw new PricingError('QUOTE_NOT_RESERVABLE',409);const old=(await c.query('SELECT * FROM coupon_reservations WHERE (actor=$1 AND operation_key=$2) OR quote_id=$3',[this.principal.subject,operationKey,quoteId])).rows[0];if(old){if(old.quote_id!==quoteId||old.operation_key!==operationKey)throw new PricingError('IDEMPOTENCY_MISMATCH',409);return {id:old.id,status:'RESERVED_NOT_REDEEMED',replayed:true};}const coupon=(await c.query<{terms:CouponTerms}>('SELECT terms FROM coupon_versions WHERE id=$1',[q.coupon_id])).rows[0]!.terms;const count=Number((await c.query('SELECT count(*) AS n FROM coupon_reservations WHERE coupon_id=$1 AND expires_at>$2',[q.coupon_id,now])).rows[0].n);if(coupon.maxActiveReservations!==null&&count>=coupon.maxActiveReservations)throw new PricingError('COUPON_LIMIT_REACHED',409);const rid=randomUUID();await c.query('INSERT INTO coupon_reservations(id,coupon_id,quote_id,actor,operation_key,expires_at) VALUES($1,$2,$3,$4,$5,$6)',[rid,q.coupon_id,quoteId,this.principal.subject,operationKey,q.expires_at]);return {id:rid,status:'RESERVED_NOT_REDEEMED',replayed:false};},true);}
 async manage(value:unknown){const v=exact(value,['operation','input']);if(v.operation==='initializePrivate'){const x=exact(v.input,['requestKey','rentalFrom','rentalUntil']);if(typeof x.rentalFrom!=='string'||typeof x.rentalUntil!=='string')throw new PricingError('INVALID_INPUT');id(x.requestKey);return this.initializePrivate(x.requestKey,x.rentalFrom,x.rentalUntil);}throw new PricingError('UNSUPPORTED_PRIVATE_OPERATION',422);}
}
