import {reconcileLedgerProtection} from '../../packages/core/src/catalog/reconcile-protection';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {flowFixture} from '../flow/fixture';
import {WearService} from '../../packages/core/src/wear/service';
import {LedgerService} from '../../packages/core/src/catalog/ledger-service';
import {ledgerPrincipal} from '../../packages/auth/src/staff-auth';
import {verifyLedgerWrite} from '../../packages/auth/src/ledger-write-authority';
import {parseConditions,canonical} from '../../packages/contracts/src/hold';
import {GROUP_JSON_BYTES,DEFAULT_JSON_BYTES} from '../../packages/contracts/src/http-body-limits';
import {readJson} from '../../apps/web/src/lib/ledger-http';
import {parseRecommendation} from '../../packages/contracts/src/recommendation';
import {registerWear} from './fixture';
let failed=false,stage='setup';const x=await flowFixture();
try{const ledger=new LedgerService(x.roles.ledgerPool,ledgerPrincipal(x.principal),(c,stores,global)=>verifyLedgerWrite(c,x.roles.authPool,x.signed.identity,stores,global),(resource,id,version)=>reconcileLedgerProtection(x.roles.transferPool,x.roles.authPool,x.signed.identity,resource,id,version)),wear=new WearService(x.flow.flowPool,x.roles.authPool,x.signed.identity),f=await registerWear(ledger,wear);
 for(const pool of (await wear.overview('MOUNTAIN_BASE')).pools)await wear.adjust(randomUUID(),{poolId:pool.id,expectedRevision:pool.revision,ready:20,reason:'SYNTHETIC load quantities, not real200 garments'});
 const poles=(await x.db.pool.query('SELECT id,version FROM ledger_poles WHERE variant_id=$1',[f.variants['POLE-110 cm']])).rows[0];await ledger.update('poles',poles.id,{version:poles.version,quantity:20,reason:'SYNTHETIC twenty-person boundary'});
 for(const family of ['SKI','SKI_BOOT'] as const){const variant=f.variants[family==='SKI'?'SKI-150 cm':'SKI_BOOT-26.5 CM']!;for(let n=2;n<20;n++)await ledger.create('assets',{family,variantId:variant,storeId:'MOUNTAIN_BASE',status:'AVAILABLE',bslStatus:family==='SKI_BOOT'?'UNVERIFIED':'NOT_APPLICABLE',bslMm:null,bslEvidence:'',notes:'SYNTHETIC load',sourceKind:'SYNTHETIC',sourceDocument:'tests/wear/group-capacity.ts',sourceLocator:family+'-'+n});}
 const members=Array.from({length:20},(_,n)=>({key:'m'+String(n).padStart(23,'x'),product:'SKI_SET',age:'ADULT',tier:'PREMIUM',wear:true,items:[{family:'SKI',variantIds:[f.variants['SKI-150 cm']],modelPromise:{modelId:f.models.SKI,season:'2026/27',variantId:f.variants['SKI-150 cm']}},{family:'SKI_BOOT',variantIds:[f.variants['SKI_BOOT-26.5 CM']]},{family:'POLE',variantIds:[f.variants['POLE-110 cm']]},{family:'WEAR_JACKET',variantIds:[f.selection.jacketVariantId]},{family:'WEAR_PANTS',variantIds:[f.selection.pantsVariantId]}]}));
 const c=parseConditions({contractVersion:'INTEGRATED_V1_2',reservationId:randomUUID(),pickupStore:'MOUNTAIN_BASE',returnStore:'MOUNTAIN_BASE',period:{startDate:'2035-03-01',endDate:'2035-03-10',slot:'MULTIDAY'},members});
 stage='maximum-schema-http';const max=structuredClone(c);for(const m of max.members){m.tier='REGULAR';for(const i of m.items){delete i.modelPromise;if(!i.family.startsWith('WEAR_'))i.variantIds=Array.from({length:6},()=>randomUUID());}}parseConditions(max);const body={requestKey:randomUUID(),conditions:max,holdId:randomUUID(),couponCode:'X'.repeat(32),wantAdvance:true};const bytes=Buffer.byteLength(JSON.stringify(body));assert.ok(bytes<=GROUP_JSON_BYTES);assert.equal(canonical(await readJson(new Request('http://local.test',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),GROUP_JSON_BYTES)),canonical(body));
 const profiles={contractVersion:'INTEGRATED_V1_2',pickupStore:'MOUNTAIN_BASE',returnStore:'MOUNTAIN_BASE',period:c.period,members:members.map(m=>({key:m.key,sport:'SKI',heightCm:170,footCm:25.5,adultAtStart:true,tier:'PREMIUM',ski:{weightKg:60,ageAtStart:30,level:'BEGINNER'},poleVariantId:f.variants['POLE-110 cm'],wearSelection:f.selection,modelSelection:{modelId:f.models.SKI,season:'2026/27'}}))};parseRecommendation(profiles);const previewBytes=Buffer.byteLength(JSON.stringify({requestKey:randomUUID(),input:profiles,replaceHoldId:null}));assert.ok(previewBytes<=DEFAULT_JSON_BYTES);console.log('PASS maximum20x5 holds body '+bytes+' bytes / limit '+GROUP_JSON_BYTES+'; recommendation20 body '+previewBytes+' / '+DEFAULT_JSON_BYTES);
 // LOWER-LEVEL MECHANICS: this deliberately sets capacity (20 units) to exactly match demand
 // (20 members) to prove the allocator handles a maximal group HOLD correctly and efficiently at
 // scale — not a test of the 95% public-capacity policy, which would otherwise cap any 20-unit
 // pool's public usage at floor(20*0.95)=19, one short of this exact-boundary scenario.
 const groupReason={reason:'SYNTHETIC twenty-person maximum-group mechanics test'};
 stage='twenty-person-allocation';const started=performance.now(),h=await x.holds.command('create',randomUUID(),c,undefined,undefined,groupReason);assert.equal(h.result,'CREATED');const elapsed=Math.round(performance.now()-started);assert.equal((await x.db.pool.query('SELECT count(*)::int n FROM inventory_claims WHERE hold_id=$1 AND active',[h.holdId])).rows[0].n,600);assert.equal((await x.db.pool.query('SELECT count(*)::int n FROM wear_claims WHERE hold_id=$1 AND active',[h.holdId])).rows[0].n,400);const quote=(await x.quotes.create(randomUUID(),{conditions:c,holdId:h.holdId,couponCode:null,wantAdvance:false})).quote;assert.equal((quote.snapshot.items as unknown[]).length,40);const ttl=(await x.holds.get(h.holdId!)).expiresAt;await x.clock('2035-01-01T10:01:00+09:00');const changed={...c,members:c.members.map(m=>({...m,items:m.items.map(i=>i.family==='WEAR_JACKET'?{...i,variantIds:[f.variants['WEAR_JACKET-L']!]}:i)}))};const prior=await x.holds.get(h.holdId!);const amended=await x.holds.command('amend',randomUUID(),changed,h.holdId!,prior.version,groupReason);assert.equal(amended.result,'AMENDED');assert.equal((await x.holds.get(h.holdId!)).expiresAt,ttl);assert.equal((await x.quotes.get(quote.id)).snapshotSha256,quote.snapshotSha256);console.log('PASS actual20 members x5 components x10days: gear600 claims / wear400 quantity claims,40 commercial lines, atomic amendTTL unchanged; HOLD operation '+elapsed+'ms (not preview HTTP p95)');
 stage='split-cross-store-group-receipts';await x.clock('2035-01-01T10:20:00+09:00');
 const wearOnly=(date:string)=>parseConditions({...c,reservationId:randomUUID(),period:{startDate:date,endDate:date,slot:'DAY'},members:[0,1].map(n=>({key:'wear-'+n,product:'WEAR_SET',age:'ADULT',tier:'STANDARD',wearSport:'SKI',items:[{family:'WEAR_JACKET',variantIds:[f.selection.jacketVariantId]},{family:'WEAR_PANTS',variantIds:[f.selection.pantsVariantId]}]}))});
 // LOWER-LEVEL MECHANICS: the pools below are deliberately narrowed to ready:2 to match exactly
 // two 2-member wear-only bookings (4 units total demand against a 2-unit pool per variant),
 // proving split cross-store receipt/conservation mechanics — not the 95% public-capacity policy.
 const first=await x.draft(undefined,wearOnly('2035-03-12'),groupReason);const paid=await x.service.startPayment(first.booking.id,randomUUID());assert.equal(paid.state,'CONFIRMED_DEV');const next=await x.draft(undefined,wearOnly('2035-03-13'),groupReason);assert.equal((await x.service.startPayment(next.booking.id,randomUUID())).state,'CONFIRMED_DEV');
 for(const v of [f.selection.jacketVariantId,f.selection.pantsVariantId]){const pool=(await wear.overview('MOUNTAIN_BASE')).pools.find(p=>p.variant_id===v)!;await wear.adjust(randomUUID(),{poolId:pool.id,expectedRevision:pool.revision,ready:2,reason:'SYNTHETIC independent conservation baseline'});}
 const total=(await x.db.pool.query('SELECT sum(total)::int n FROM wear_pools')).rows[0].n;await x.clock('2035-03-12T10:00:00+09:00');const out=await wear.checkout(randomUUID(),{bookingId:paid.id,expectedBookingVersion:paid.version,store:'MOUNTAIN_BASE',reason:'SYNTHETIC group quantity loan'});assert.equal(out.loans.length,4);
 const jackets=out.loans.filter(l=>l.requirement_key.endsWith('WEAR_JACKET'));for(const [n,l] of jackets.entries())await wear.receive(randomUUID(),{loanId:l.id,expectedRevision:l.revision,store:n===0?'MOUNTAIN_BASE':'ONSEN_BASE',quantity:1,unresolvedId:null,reason:'SYNTHETIC split actual receipt'});
 const receipts=await wear.receipts(paid.id,'ONSEN_BASE');assert.deepEqual(receipts.map(r=>r.actual_store).sort(),['MOUNTAIN_BASE','ONSEN_BASE']);const loans=await wear.loans(paid.id,'ONSEN_BASE');assert.equal(loans.reduce((n,l)=>n+l.quantity-l.returned,0),2);assert.ok(loans.every(l=>l.planned_return_store==='MOUNTAIN_BASE'));assert.equal((await x.db.pool.query('SELECT sum(total)::int n FROM wear_pools')).rows[0].n,total);assert.equal((await x.holds.get(next.holdId)).state,'ACTIVE');const pending=(await wear.overview('MOUNTAIN_BASE')).pools.find(p=>p.variant_id===f.selection.jacketVariantId)!;assert.equal(pending.reserved_peak,2);assert.equal(pending.ready,0);console.log('PASS same booking Mx2 split Mountain1/Onsen1; pants2 remain on loan; total conserved; future promise retained with actual-ready attention');

 stage='saved batch exact cycles, stale candidate and per-item confirmation';
 const pants=loans.filter(l=>l.requirement_key.endsWith('WEAR_PANTS'));const common={store:'ONSEN_BASE',quantity:1,reason:'SYNTHETIC batch actual quantity'};
 const saved=await wear.saveReturnCandidate(randomUUID(),{...common,batchId:null,expectedRevision:null,loanId:pants[0]!.id,expectedLoanRevision:pants[0]!.revision});
 const batch=await wear.saveReturnCandidate(randomUUID(),{...common,batchId:saved.id,expectedRevision:saved.revision,loanId:pants[1]!.id,expectedLoanRevision:pants[1]!.revision});assert.equal(batch.items.length,2);assert.equal((await wear.returnBatch(batch.id,'ONSEN_BASE')).items.length,2);
 await assert.rejects(wear.saveReturnCandidate(randomUUID(),{...common,batchId:batch.id,expectedRevision:batch.revision,loanId:pants[1]!.id,expectedLoanRevision:pants[1]!.revision}),{code:'DUPLICATE_CANDIDATE'});
 await wear.receive(randomUUID(),{...common,loanId:pants[0]!.id,expectedRevision:pants[0]!.revision,unresolvedId:null});const originalReceipts=(await x.db.pool.query('SELECT count(*)::int n FROM wear_receipts')).rows[0].n;
 const bk=randomUUID(),confirm={batchId:batch.id,expectedRevision:batch.revision,store:'ONSEN_BASE',reason:'SYNTHETIC batch confirm'};const results=await Promise.allSettled([wear.confirmReturnBatch(bk,confirm),wear.confirmReturnBatch(randomUUID(),confirm)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);const completed=await wear.returnBatch(batch.id,'ONSEN_BASE');assert.deepEqual(completed.items.map(i=>i.state).sort(),['NEEDS_ATTENTION','RECEIVED']);assert.equal(completed.items.find(i=>i.state==='NEEDS_ATTENTION')!.error,'STALE_LOAN_CANDIDATE');
 const firstResult=results[0]!;if(firstResult.status==='fulfilled')assert.deepEqual(await wear.confirmReturnBatch(bk,confirm),JSON.parse(JSON.stringify(firstResult.value)));
 assert.equal((await x.db.pool.query('SELECT count(*)::int n FROM wear_receipts')).rows[0].n,originalReceipts+1);await wear.confirmReturnBatch(randomUUID(),{...confirm,expectedRevision:completed.revision});assert.equal((await x.db.pool.query('SELECT count(*)::int n FROM wear_receipts')).rows[0].n,originalReceipts+1);assert.equal((await x.db.pool.query('SELECT sum(total)::int n FROM wear_pools')).rows[0].n,total);console.log('PASS durable batch exact cycles, duplicate candidate refusal, stale item attention, independent valid receipt, two-terminal confirm and no repeated completed item');

}catch(e){failed=true;console.error('WEAR_MAX_FAILED '+stage+' '+((e as {code?:string}).code??(e as Error).name));if(e instanceof assert.AssertionError)console.error(JSON.stringify({actual:e.actual,expected:e.expected}));console.error((e as Error).stack?.split('\n').filter(l=>l.includes('/tests/wear/')).join('\n'));}finally{await x.close();console.log('Owned wear maximum-group PostgreSQL stopped.');}if(failed)process.exit(1);
