import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
import {performance} from 'node:perf_hooks';
import {mkdir,writeFile} from 'node:fs/promises';
import os from 'node:os';
import {chromium} from '@playwright/test';
import {safeTestTransportFailure} from '../flow/web-diagnostics';
import {startFlowApp} from '../flow/launcher';
import {bootstrapDevelopmentAdmin} from '../../scripts/bootstrap-staff';
import {seedRecommendation,inputFor} from '../recommendation/fixture';
import {skiSet} from '../inventory/fixture';
import type {HoldConditions} from '../../packages/contracts/src/hold';
let failed=false,stage='setup';const reports:unknown[]=[];
for(const totalWear of [200,400]){
 const browser=await chromium.launch(),password=randomBytes(24).toString('base64url');let app:Awaited<ReturnType<typeof startFlowApp>>|undefined;
 try{app=await startFlowApp();await seedRecommendation(app.db.pool,true);await bootstrapDevelopmentAdmin(app.db.pool,{email:'wear-mixed-root@example.invalid',displayName:'SYNTHETIC mixed root',password});const {origin}=app,db=app.db.pool;
 const clock=async(t:string)=>{assert.match(t,/^20[0-9-]+T[0-9:]+Z$/);await db.query(`CREATE OR REPLACE FUNCTION inventory_clock() RETURNS timestamptz LANGUAGE sql VOLATILE AS $$SELECT '${t}'::timestamptz$$`);};await clock('2035-01-01T01:00:00Z');
 for(let i=0;i<100;i++){try{if((await fetch(origin+'/api/health')).ok)break;}catch{}if(i===99)throw new Error('APP_START_TIMEOUT');await new Promise(r=>setTimeout(r,100));}
 async function login(email:string){const context=await browser.newContext({baseURL:origin});const p=await context.newPage();await p.goto('/staff/login');await p.getByLabel('メールアドレス',{exact:true}).fill(email);await p.getByLabel('パスワード',{exact:true}).fill(password);await p.getByRole('button',{name:'ログイン',exact:true}).click();await p.waitForURL(origin+'/staff/ledger');await p.close();return context;}
 const root=await login('wear-mixed-root@example.invalid');const created=await root.request.post('/api/staff-users',{headers:{origin},data:{email:'wear-mixed-actor@example.invalid',password,displayName:'SYNTHETIC mixed actor',active:true,role:'ADMIN',scope:'ALL',storeIds:[],permissions:{BOOKING_VIEW:true,BOOKING_CREATE:true,RENTAL_CHECKOUT:true,RENTAL_RETURN:true,INVENTORY_VIEW:true,INVENTORY_EDIT:true,HOLD_VIEW:true,HOLD_EDIT:true,QUOTE_VIEW:true,QUOTE_CREATE:true,PRICE_EDIT:true,TRANSFER_VIEW:true,TRANSFER_PLAN:true,TRANSFER_DISPATCH:true,TRANSFER_RECEIVE:true}}});assert.equal(created.status(),201);const c=await login('wear-mixed-actor@example.invalid');
 const post=async(path:string,data:unknown,status=200)=>{const response=await c.request.post(path,{headers:{origin},data});assert.equal(response.status(),status,path);return response.json();};const get=async(path:string)=>{const response=await c.request.get(path);assert.equal(response.status(),200,path);return response.json();};
 await post('/api/quotes/private-initialize',{operation:'initializePrivate',input:{requestKey:randomUUID(),rentalFrom:'2035-01-01',rentalUntil:'2035-12-31'}},201);
 const source={notes:'SYNTHETIC '+totalWear+' physical garment parts, no real200 assumption',sourceKind:'SYNTHETIC',sourceDocument:'tests/wear/mixed.ts',sourceLocator:'synthetic'};const wearIds:Record<string,string>={};
 for(const family of ['WEAR_JACKET','WEAR_PANTS']){const m=await post('/api/ledger/models',{...source,sourceLocator:family+'-model',code:'MIX-'+family,name:'SYNTHETIC '+family,brand:'SYNTHETIC',family,catalogSeason:'2026/27'},201);const v=await post('/api/ledger/variants',{...source,sourceLocator:family+'-M',modelId:m.id,family,age:'ADULT',tier:'STANDARD',size:'M',compatibleSports:['SKI','SNOWBOARD']},201);wearIds[family]=v.id;await post('/api/wear/register',{requestKey:randomUUID(),input:{variantId:v.id,store:'MOUNTAIN_BASE',quantity:totalWear/2,reason:source.notes}});}
 const wearItems=()=>[{family:'WEAR_JACKET' as const,variantIds:[wearIds.WEAR_JACKET!]},{family:'WEAR_PANTS' as const,variantIds:[wearIds.WEAR_PANTS!]}];
 const date=(n:number)=>new Date(Date.UTC(2035,1,1+n)).toISOString().slice(0,10);
 const conditions=(n:number,people=2):HoldConditions=>{const base=skiSet(date(n));return {...base,contractVersion:'INTEGRATED_V1_2',members:Array.from({length:people},(_,i)=>({...base.members[0]!,key:'person-'+i,wear:true,items:[...base.members[0]!.items,...wearItems()]}))};};
 const hold=async(n:number,people=2)=>{const conditionsNow=conditions(n,people),h=await post('/api/holds',{requestKey:randomUUID(),conditions:conditionsNow},201);assert.equal(h.result,'CREATED');return h;};
 stage='seed90holds100quotes';const held=[];for(let i=0;i<90;i++)held.push(await hold(i));for(let i=0;i<100;i++){const h=held[i%90]!;await post('/api/quotes',{requestKey:randomUUID(),input:{conditions:h.hold.conditions,holdId:h.holdId,couponCode:null,wantAdvance:false}},201);}
 // A wear-only confirmed synthetic booking supplies real quantity-return/care work.
 const wc:HoldConditions={...conditions(100),reservationId:randomUUID(),period:{startDate:'2035-01-01',endDate:'2035-01-01',slot:'DAY'},members:[{key:'wear-loan',product:'WEAR_SET',age:'ADULT',tier:'STANDARD',wearSport:'SKI',items:wearItems()}]};
 const wh=await post('/api/holds',{requestKey:randomUUID(),conditions:wc},201),wq=await post('/api/quotes',{requestKey:randomUUID(),input:{conditions:wc,holdId:wh.holdId,couponCode:null,wantAdvance:false}},201);
 const b=await post('/api/bookings',{requestKey:randomUUID(),quoteId:wq.quote.id,contact:{displayName:'SYNTHETIC Wear Mixed',email:'synthetic-wear-mixed@example.invalid',termsAccepted:true}},201);const paid=await post('/api/bookings/'+b.id+'/payment',{requestKey:randomUUID()});assert.equal(paid.state,'CONFIRMED_DEV');
 const out=await post('/api/wear/checkout',{requestKey:randomUUID(),input:{bookingId:paid.id,expectedBookingVersion:paid.version,store:'MOUNTAIN_BASE',reason:'SYNTHETIC mixed loan'}});const loan=out.loans[0];
 const boards=(await db.query("SELECT count(*)::int n FROM ledger_assets WHERE family IN ('SKI','SNOWBOARD')")).rows[0].n;assert.equal(boards,300);assert.equal((await db.query('SELECT sum(total)::int n FROM wear_pools')).rows[0].n,totalWear);
 type Timing={operation:string;concurrency:number;people:number;ms:number};const times:Timing[]=[];let serial=110,receipt:undefined|{id:string;revision:number};
 async function measured(operation:string,concurrency:number,people:number,fn:()=>Promise<unknown>){const start=performance.now();await fn();times.push({operation,concurrency,people,ms:performance.now()-start});}
 for(const concurrency of [1,4,10])for(const people of [2,20]){stage='mixed'+totalWear+'-'+concurrency+'-'+people;
  const run=async(i:number)=>{const n=serial++;const op=i%4;
   if(op===0)await measured('group HOLD plus quote HTTP',concurrency,people,async()=>{const h=await hold(n,people);const q=await post('/api/quotes',{requestKey:randomUUID(),input:{conditions:h.hold.conditions,holdId:h.holdId,couponCode:null,wantAdvance:false}},201);assert.equal(q.quote.snapshot.items.length,people*2);});
   else if(op===1)await measured('recommendation preview HTTP',concurrency,people,async()=>{const input=inputFor(date(n));input.contractVersion='INTEGRATED_V1_2';input.members=Array.from({length:people},(_,j)=>({...input.members[0]!,key:'candidate-'+j,wearSelection:{jacketVariantId:wearIds.WEAR_JACKET!,pantsVariantId:wearIds.WEAR_PANTS!}}));const v=await post('/api/recommendations',{requestKey:randomUUID(),input,replaceHoldId:null},201);assert.ok(v.preview.offered.every((o:{candidates:{RECOMMENDED:unknown}})=>o.candidates.RECOMMENDED));});
   else if(op===2)await measured('quote list100 HTTP',concurrency,people,async()=>{assert.equal((await get('/api/quotes')).length,100);});
   else await measured('quantity pool and return workspace HTTP',concurrency,people,async()=>{await get('/api/wear/pools?store=MOUNTAIN_BASE');await get('/api/wear/return-workspace?store=ONSEN_BASE');});
  };
  for(let block=0;block<2;block++)await Promise.all(Array.from({length:concurrency},(_,i)=>run(i+block)));
 }
 // Quantity mutations are individually measured while other read requests are active.
 stage='mutation-mix';await Promise.all([measured('actual cross-store quantity receipt HTTP',4,1,async()=>{const r=await post('/api/wear/receive',{requestKey:randomUUID(),input:{loanId:loan.id,expectedRevision:loan.revision,store:'ONSEN_BASE',quantity:1,unresolvedId:null,reason:'SYNTHETIC mixed receipt'}});receipt=r.receipt;}),measured('quote list100 during return HTTP',4,2,()=>get('/api/quotes')),measured('quantity source during return HTTP',4,2,()=>get('/api/wear/pools?store=MOUNTAIN_BASE')),measured('quantity destination during return HTTP',4,2,()=>get('/api/wear/pools?store=ONSEN_BASE'))]);
 for(const operation of ['START','COMPLETE'])await Promise.all([measured('quantity care '+operation+' HTTP',2,1,async()=>{receipt=await post('/api/wear/cleaning',{requestKey:randomUUID(),input:{receiptId:receipt!.id,expectedRevision:receipt!.revision,operation,confirmedReady:operation==='COMPLETE',reason:'SYNTHETIC actual washing and drying'}});}),measured('quote list during care HTTP',2,2,()=>get('/api/quotes'))]);
 assert.equal((await db.query('SELECT sum(total)::int n FROM wear_pools')).rows[0].n,totalWear);assert.equal((await db.query('SELECT sum(today_blocked)::int n FROM wear_pools')).rows[0].n,1);assert.equal((await db.query('SELECT count(*)::int n FROM rental_payment_attempts')).rows[0].n,1);
 stage='mixed-transfer';const pool=(await get('/api/wear/pools?store=MOUNTAIN_BASE')).pools.find((p:{variant_id:string})=>p.variant_id===wearIds.WEAR_JACKET);let transfer:Record<string,unknown>={};
 await Promise.all([measured('quantity transfer plan HTTP',2,1,async()=>{transfer=await post('/api/wear/transfer-plan',{requestKey:randomUUID(),input:{poolId:pool.id,expectedRevision:pool.revision,destinationStore:'ONSEN_BASE',quantity:1,scheduledDate:'2035-01-01',reason:'SYNTHETIC mixed transfer'}});}),measured('quote list during transfer plan HTTP',2,2,()=>get('/api/quotes'))]);
 await clock('2035-01-01T08:00:00Z');await Promise.all([measured('quantity dispatch HTTP',2,1,async()=>{const t=await post('/api/wear/transfer',{requestKey:randomUUID(),input:{transferId:transfer.id,expectedRevision:transfer.revision,operation:'DISPATCH',quantity:null,reason:'SYNTHETIC actual departure'}});transfer=t.transfer;}),measured('quote list after clock expiry HTTP',2,2,()=>get('/api/quotes'))]);
 await clock('2035-01-01T08:10:00Z');assert.equal((await get('/api/wear/transfers?store=ONSEN_BASE')).find((t:{id:string})=>t.id===transfer.id).state,'IN_TRANSIT');let transferReceipt:{id:string;revision:number}|undefined;
 await Promise.all([measured('quantity actual arrival HTTP',2,1,async()=>{const t=await post('/api/wear/transfer',{requestKey:randomUUID(),input:{transferId:transfer.id,expectedRevision:transfer.revision,operation:'RECEIVE',quantity:1,reason:'SYNTHETIC actual arrival'}});transferReceipt=t.receipts[0];}),measured('quote list during arrival HTTP',2,2,()=>get('/api/quotes'))]);
 await measured('quantity actual ready HTTP',1,1,()=>post('/api/wear/transfer-ready',{requestKey:randomUUID(),input:{receiptId:transferReceipt!.id,expectedRevision:transferReceipt!.revision,confirmedReady:true,reason:'SYNTHETIC actual readiness'}}));assert.equal((await db.query('SELECT sum(total)::int n FROM wear_pools')).rows[0].n,totalWear);assert.equal((await db.query('SELECT count(*)::int n FROM rental_payment_attempts')).rows[0].n,1);
 const groups=[...new Set(times.map(t=>t.operation+'|'+t.concurrency+'|'+t.people))].map(key=>{const rows=times.filter(t=>t.operation+'|'+t.concurrency+'|'+t.people===key),ms=rows.map(t=>t.ms).sort((a,b)=>a-b);return {operation:rows[0]!.operation,concurrency:rows[0]!.concurrency,people:rows[0]!.people,samples:rows.length,p50Ms:ms[Math.ceil(ms.length*.5)-1],p95Ms:ms[Math.ceil(ms.length*.95)-1]};});
 const report={synthetic:true,physicalGarmentParts:totalWear,boardAssets:boards,initialLiveHolds:90,initialPeoplePerHold:2,initialComponentsPerHold:10,initialWearComponents:360,initialEquipmentComponents:540,initialQuotes:100,additionalConfirmedWearBooking:1,period:'independent DAY dates2035-02-01 onward; return/care clock2035-01-01',concurrencies:[1,4,10],peoplePerRequest:[2,20],candidateVariantsPerPerson:'same explicit recommendation fixture; SKI5; wear one exact upper and one exact lower',environment:{platform:process.platform,node:process.version,cpu:os.cpus()[0]?.model,transport:'ordinary password -> Next development loopback HTTP -> isolated PostgreSQL18.4',firstRouteCompilationIncluded:true},operations:groups,raw:times,observedErrors:0,productionPerformanceGuarantee:false,smallSampleWarning:'p95 descriptive only; not a sustained throughput/SLA test'};reports.push(report);console.log('WEAR_MIXED '+JSON.stringify({...report,raw:undefined}));
 }catch(e){failed=true;console.error('WEAR_MIXED_FAILED '+stage+' '+(e as Error).name);console.error(JSON.stringify(safeTestTransportFailure(e)));if(e instanceof assert.AssertionError)console.error(JSON.stringify({actual:e.actual,expected:e.expected,operation:e.message.split('\n')[0]}));console.error((e as Error).stack?.split('\n').filter(l=>l.includes('/tests/wear/mixed.ts:')).join('\n'));}finally{await browser.close();await app?.stop();console.log('Owned wear mixed'+totalWear+' Web/browser/PostgreSQL stopped.');}if(failed)break;
}
await mkdir('.local/benchmarks',{recursive:true});await writeFile('.local/benchmarks/wear-mixed.json',JSON.stringify({reports,complete:!failed},null,2));if(failed)process.exit(1);
