import {reconcileLedgerProtection} from '../../packages/core/src/catalog/reconcile-protection';
import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
import {mkdir} from 'node:fs/promises';
import {chromium,expect,type Page} from '@playwright/test';
import {startFlowApp} from '../flow/launcher';
import {bootstrapDevelopmentAdmin} from '../../scripts/bootstrap-staff';
import {seedRecommendation} from '../recommendation/fixture';
import {LedgerService} from '../../packages/core/src/catalog/ledger-service';
import {loadStaff,ledgerPrincipal} from '../../packages/auth/src/staff-auth';
import {verifyLedgerWrite} from '../../packages/auth/src/ledger-write-authority';
import {WearService} from '../../packages/core/src/wear/service';
import {registerWear} from './fixture';
let stage='startup',count=0,failed=false;const browser=await chromium.launch(),password=randomBytes(24).toString('base64url');let app:Awaited<ReturnType<typeof startFlowApp>>|undefined,page:Page|undefined;
async function check(name:string,fn:()=>Promise<void>){stage=name;await fn();count++;console.log('PASS '+name);}
try{app=await startFlowApp();await seedRecommendation(app.db.pool);await bootstrapDevelopmentAdmin(app.db.pool,{email:'wear-ui-root@example.invalid',displayName:'SYNTHETIC Root',password});const {origin}=app;async function clock(time:string){await app!.db.pool.query(`CREATE OR REPLACE FUNCTION inventory_clock() RETURNS timestamptz LANGUAGE sql VOLATILE AS $$SELECT '${time}'::timestamptz$$`);}await clock('2035-01-01T01:00:00Z');
 for(let n=0;n<100;n++){try{if((await fetch(origin+'/api/health')).ok)break;}catch{}if(n===99)throw new Error('APP_START_TIMEOUT');await new Promise(r=>setTimeout(r,100));}
 const context=await browser.newContext({baseURL:origin,viewport:{width:1280,height:960}});context.setDefaultTimeout(15000);page=await context.newPage();const p=page;
 async function login(email:string){await p.goto('/staff/login');await p.getByLabel('メールアドレス',{exact:true}).fill(email);await p.getByLabel('パスワード',{exact:true}).fill(password);await p.getByRole('button',{name:'ログイン',exact:true}).click();await p.waitForURL(origin+'/staff/ledger');}
 await login('wear-ui-root@example.invalid');const perms={BOOKING_VIEW:true,BOOKING_CREATE:true,RENTAL_CHECKOUT:true,RENTAL_RETURN:true,INVENTORY_VIEW:true,INVENTORY_EDIT:true,HOLD_VIEW:true,HOLD_EDIT:true,QUOTE_VIEW:true,QUOTE_CREATE:true,PRICE_EDIT:true,TRANSFER_VIEW:true,TRANSFER_PLAN:true,TRANSFER_DISPATCH:true,TRANSFER_RECEIVE:true};const created=await context.request.post('/api/staff-users',{headers:{origin},data:{email:'wear-ui-actor@example.invalid',password,displayName:'SYNTHETIC Wear Staff',active:true,role:'ADMIN',scope:'ALL',storeIds:[],permissions:perms}});assert.equal(created.status(),201);
 await p.goto('/staff/logout');await p.getByRole('button',{name:'ログアウトする',exact:true}).click();await p.waitForURL(origin+'/staff/login');await login('wear-ui-actor@example.invalid');const subject=(await app.db.pool.query("SELECT id FROM staff_users WHERE email='wear-ui-actor@example.invalid'")).rows[0].id,sessionId=(await app.db.pool.query('SELECT id FROM auth_session WHERE "userId"=$1 ORDER BY "createdAt" DESC LIMIT 1',[subject])).rows[0].id,identity={subject,sessionId},principal=(await loadStaff(app.db.pool,subject))!;
 const ledger=new LedgerService(app.roles.ledgerPool,ledgerPrincipal(principal),(c,stores,global)=>verifyLedgerWrite(c,app!.roles.authPool,identity,stores,global),(resource,id,version)=>reconcileLedgerProtection(app!.roles.transferPool,app!.roles.authPool,identity,resource,id,version));const fixtures=await registerWear(ledger,new WearService(app.flow.flowPool,app.roles.authPool,identity));
 await p.goto('/staff/quotes');await p.getByLabel('料金の対象開始日').fill('2035-01-01');await p.getByLabel('料金の対象終了日').fill('2035-12-31');await p.getByRole('button',{name:'開発用の初期料金を設定'}).click();await expect(p.getByRole('region',{name:'料金版',exact:true})).toContainText('PRIVATE_AVAILABLE');
 let bookingId='',bookingVersion=0,holdId='',ttl='';
 await check('ordinary password UI wear-only -> independent upper/lower -> HOLD/quote -> synthetic booking and isolated payment snapshot',async()=>{
  await p.goto('/preview/integrated');await p.getByLabel('利用開始日',{exact:true}).fill('2035-01-05');await p.getByLabel('利用終了日',{exact:true}).fill('2035-01-05');await p.getByLabel('競技 1',{exact:true}).selectOption('WEAR');await p.getByLabel('利用開始時の年齢区分 1',{exact:true}).selectOption('ADULT');await p.getByLabel('上サイズ 1',{exact:true}).selectOption(fixtures.selection.jacketVariantId);await p.getByLabel('下サイズ 1',{exact:true}).selectOption(fixtures.selection.pantsVariantId);assert.equal(await p.getByLabel('身長cm 1',{exact:true}).count(),0);
  await p.getByRole('button',{name:'推薦候補を確認',exact:true}).click();await p.getByRole('button',{name:'おすすめを選ぶ 1',exact:true}).click();await p.getByRole('checkbox',{name:'表示したモデル契約・サイズ・ウェア構成を選択条件とすることを確認'}).check();await p.getByRole('button',{name:'全員分をHOLDして見積を保存',exact:true}).click();await expect(p.getByRole('region',{name:'見積詳細',exact:true})).toBeVisible();await mkdir('.local/screenshots',{recursive:true});await p.setViewportSize({width:390,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:'.local/screenshots/wear-selection-mobile-width.png',fullPage:true});
  await p.getByRole('link',{name:'非公開の合成予約プレビューへ'}).click();await p.getByLabel('合成氏名').fill('SYNTHETIC Wear Only');await p.getByLabel('架空メール宛先').fill('synthetic-wear-only@example.invalid');await p.getByLabel('開発用の合成予約であり、営業規約・請求の確定ではないことを確認').check();await p.getByRole('button',{name:'合成予約情報を保存',exact:true}).click();await expect(p.getByRole('region',{name:'開発予約詳細'})).toContainText('DRAFT');await p.getByRole('button',{name:'テストアダプタへ照合要求'}).click();await expect(p.getByRole('region',{name:'開発予約詳細'})).toContainText('CONFIRMED_DEV');await expect(p.getByLabel('開発予約QR')).toBeVisible();
  const b=(await app!.db.pool.query('SELECT b.*,h.expires_at FROM rental_bookings b JOIN inventory_holds h ON h.id=b.hold_id')).rows[0];bookingId=b.id;bookingVersion=b.version;holdId=b.hold_id;ttl=b.expires_at.toISOString();assert.equal(b.price_snapshot.totalJpy,5000);assert.equal(b.conditions.members[0].product,'WEAR_SET');assert.equal(b.price_snapshot.chargeReady,false);assert.equal((await app!.db.pool.query('SELECT count(*)::int n FROM inventory_claims WHERE hold_id=$1',[holdId])).rows[0].n,0);
 });
 await check('booking lookup -> real quantity checkout -> partial cross-store return with lost response/reload/same key',async()=>{
  await clock('2035-01-05T01:00:00Z');await p.goto('/staff/wear');await p.getByLabel('予約番号',{exact:true}).fill(bookingId);await p.getByLabel('確認済み開発予約の版').fill(String(bookingVersion));await p.getByRole('button',{name:'ウェア数量を貸出記録',exact:true}).click();await expect(p.getByRole('button',{name:'1着を受領：person-1:WEAR_JACKET',exact:true})).toBeVisible();await p.getByLabel('実際の受領・表示店舗').selectOption('ONSEN_BASE');await p.getByRole('button',{name:'貸出を読込',exact:true}).click();await expect(p.getByRole('button',{name:'1着を受領：person-1:WEAR_JACKET',exact:true})).toBeVisible();
  await p.route('**/api/wear/receive',async route=>{const response=await route.fetch();assert.equal(response.status(),200);await route.abort('failed');});await p.getByRole('button',{name:'1着を受領：person-1:WEAR_JACKET',exact:true}).click();await expect(p.getByRole('button',{name:'同じ保存要求を照合',exact:true})).toBeVisible();await p.unroute('**/api/wear/receive');await p.reload();await p.getByRole('button',{name:'同じ保存要求を照合',exact:true}).click();await expect(p.getByRole('status')).toContainText('保存済み');await p.getByLabel('実際の受領・表示店舗').selectOption('ONSEN_BASE');await p.getByLabel('予約番号',{exact:true}).fill(bookingId);await p.getByRole('button',{name:'貸出を読込',exact:true}).click();await expect(p.getByRole('article',{name:'ウェア貸出 person-1:WEAR_JACKET',exact:true})).toContainText('返却済み 1');await expect(p.getByRole('article',{name:'ウェア貸出 person-1:WEAR_PANTS',exact:true})).toContainText('未返却 1');
  const rows=(await app!.db.pool.query('SELECT l.planned_return_store,r.actual_store,r.quantity FROM wear_receipts r JOIN wear_loans l ON l.id=r.loan_id')).rows;assert.deepEqual(rows,[{planned_return_store:'MOUNTAIN_BASE',actual_store:'ONSEN_BASE',quantity:1}]);assert.equal((await app!.db.pool.query('SELECT expires_at FROM inventory_holds WHERE id=$1',[holdId])).rows[0].expires_at.toISOString(),ttl);assert.equal((await app!.db.pool.query('SELECT count(*)::int n FROM rental_payment_attempts')).rows[0].n,1);
 });
 await check('actual wash/dry confirmation remains same-day blocked; ordinary UI displays physical counts without double HOLD',async()=>{
  await p.getByRole('button',{name:/^洗浄開始：/}).click();await p.getByRole('button',{name:/^実際の乾燥・検品完了を記録：/}).click();await expect(p.getByText(/ONSEN_BASE \/ 1着 \/ TODAY_BLOCKED/)).toBeVisible();await expect(p.getByText(/同日保護の解除日 2035-01-06/)).toBeVisible();await p.getByRole('button',{name:/^翌日以降のREADY反映：/}).click();await expect(p.getByRole('status')).toContainText('SAME_DAY_REHIRE_BLOCKED');await p.setViewportSize({width:1280,height:960});await p.screenshot({path:'.local/screenshots/wear-return-desktop.png',fullPage:true});await p.setViewportSize({width:390,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:'.local/screenshots/wear-return-mobile-width.png',fullPage:true});
 });
 await check('saved quantity batch survives reload; response loss replays same batch without second receipt',async()=>{
  await p.getByRole('button',{name:'返却候補へ追加：person-1:WEAR_PANTS',exact:true}).click();await expect(p.getByRole('region',{name:'保存した返却候補'})).toContainText('CANDIDATE');const batchId=await p.getByLabel('返却バッチ番号').inputValue();assert.ok(batchId);await p.reload();await p.getByLabel('実際の受領・表示店舗').selectOption('ONSEN_BASE');await p.getByRole('button',{name:'前回のバッチ番号を復元',exact:true}).click();await p.getByRole('button',{name:'保存した候補を再読込',exact:true}).click();await expect(p.getByRole('region',{name:'保存した返却候補'})).toContainText('CANDIDATE');
  await p.route('**/api/wear/return-batch-confirm',async route=>{const response=await route.fetch();assert.equal(response.status(),200);await route.abort('failed');});await p.getByRole('button',{name:'候補の数量をまとめて返却確定',exact:true}).click();await expect(p.getByRole('button',{name:'同じ保存要求を照合',exact:true})).toBeVisible();await p.unroute('**/api/wear/return-batch-confirm');await p.reload();await p.getByRole('button',{name:'同じ保存要求を照合',exact:true}).click();await expect(p.getByRole('region',{name:'保存した返却候補'})).toContainText('RECEIVED');assert.equal((await app!.db.pool.query('SELECT count(*)::int n FROM wear_receipts')).rows[0].n,2);assert.equal((await app!.db.pool.query('SELECT count(*)::int n FROM rental_payment_attempts')).rows[0].n,1);
 });
 await check('ordinary quantity transfer UI separates planning, dispatch, actual receipt and ready',async()=>{
  await clock('2035-01-06T01:00:00Z');await p.getByLabel('実際の受領・表示店舗').selectOption('ONSEN_BASE');await p.getByLabel('予約番号',{exact:true}).fill(bookingId);await p.getByRole('button',{name:'貸出を読込',exact:true}).click();await p.getByRole('button',{name:/^翌日以降のREADY反映：/}).click();await expect(p.getByRole('status')).toContainText('保存済み');const source=(await app!.db.pool.query('SELECT * FROM wear_pools WHERE variant_id=$1 AND store_id=$2',[fixtures.selection.jacketVariantId,'ONSEN_BASE'])).rows[0];await p.getByLabel('対象サイズの数量プール').selectOption(source.id);await p.getByLabel('数量操作の理由').fill('SYNTHETIC UI relocation');await p.getByLabel('17時便の予定日').fill('2035-01-06');await p.getByRole('button',{name:'もう一方の店舗への移動を計画',exact:true}).click();await expect(p.getByRole('status')).toContainText('保存済み');await p.getByRole('button',{name:'この店舗の数量移動を再読込',exact:true}).click();await expect(p.getByRole('button',{name:/^実際に発送：/})).toBeVisible();await p.getByRole('button',{name:/^実際に発送：/}).click();await expect(p.getByRole('status')).toContainText('DEPARTURE_NOT_READY');await clock('2035-01-06T08:00:00Z');await p.getByRole('button',{name:/^実際に発送：/}).click();await expect(p.getByRole('article',{name:/^数量移動 /})).toContainText('IN_TRANSIT');await clock('2035-01-06T08:10:00Z');await p.getByLabel('実際の受領・表示店舗').selectOption('MOUNTAIN_BASE');await p.getByRole('button',{name:'この店舗の数量移動を再読込',exact:true}).click();await expect(p.getByRole('article',{name:/^数量移動 /})).toContainText('IN_TRANSIT');await p.getByRole('button',{name:/^実際に受領：/}).click();const readyReply=p.waitForResponse(r=>new URL(r.url()).pathname==='/api/wear/transfer-ready'&&r.request().method()==='POST');await p.getByRole('button',{name:'受領分の実READY確認：1着',exact:true}).click();assert.equal((await readyReply).status(),200);const dest=(await app!.db.pool.query('SELECT ready,returned_pending FROM wear_pools WHERE variant_id=$1 AND store_id=$2',[fixtures.selection.jacketVariantId,'MOUNTAIN_BASE'])).rows[0];assert.equal(dest.ready,2);assert.equal(dest.returned_pending,0);
 });
 await check('unauthenticated, CSRF, actor spoof and revoked permission cannot change quantities',async()=>{
  const anon=await browser.newContext({baseURL:origin});assert.equal((await anon.request.get('/api/wear/pools?store=MOUNTAIN_BASE')).status(),401);const payload={requestKey:randomUUID(),input:{variantId:fixtures.selection.jacketVariantId,store:'ONSEN_BASE',quantity:1,reason:'SYNTHETIC security'}};assert.equal((await context.request.post('/api/wear/unresolved',{data:payload})).status(),403);assert.equal((await context.request.post('/api/wear/unresolved',{headers:{origin},data:{...payload,actor:'fake'}})).status(),422);await app!.db.pool.query("UPDATE staff_permission_overrides SET allowed=false WHERE staff_id=$1 AND permission='RENTAL_RETURN'",[subject]);assert.equal((await context.request.post('/api/wear/unresolved',{headers:{origin},data:payload})).status(),403);assert.equal((await app!.db.pool.query('SELECT count(*)::int n FROM wear_unresolved_returns')).rows[0].n,0);await anon.close();
 });
 console.log(`WEAR ordinary UI/API/PostgreSQL ${count} passed; synthetic staff/password, isolated fake payment; no garment QR, real phone, production or equipment custody.`);
}catch(e){failed=true;console.error('WEAR_UI_FAILED '+stage+' '+(e as Error).name);if(e instanceof assert.AssertionError)console.error(JSON.stringify({actual:e.actual,expected:e.expected}));console.error((e as Error).stack?.split('\n').filter(l=>l.includes('/tests/wear/')).join('\n'));if(page){console.error('PATH '+new URL(page.url()).pathname);console.error('STATUS '+await page.getByRole('status').textContent().catch(()=>''));}}finally{await browser.close();await app?.stop();console.log('Owned wear UI Web/browser/PostgreSQL stopped.');}if(failed)process.exit(1);
