import {WearService} from '../../packages/core/src/wear/service';
import type {RecommendationInput} from '../../packages/contracts/src/recommendation';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {flowFixture} from '../flow/fixture';
import {LedgerService} from '../../packages/core/src/catalog/ledger-service';
import {ledgerPrincipal} from '../../packages/auth/src/staff-auth';
import {verifyLedgerWrite} from '../../packages/auth/src/ledger-write-authority';
import {reconcileLedgerProtection} from '../../packages/core/src/catalog/reconcile-protection';
import {RecommendationService} from '../../packages/core/src/recommendation/recommendation-service';
import {canonical,parseConditions,type HoldConditions} from '../../packages/contracts/src/hold';
import {inputFor,selection} from '../recommendation/fixture';
import {registerWear} from './fixture';
let stage='start',count=0,failed=false;const x=await flowFixture();
async function check(name:string,fn:()=>Promise<void>){stage=name;await fn();count++;console.log('PASS '+name);}
try{
 const ledger=new LedgerService(x.roles.ledgerPool,ledgerPrincipal(x.principal),(c,stores,global)=>verifyLedgerWrite(c,x.roles.authPool,x.signed.identity,stores,global),(resource,id,version)=>reconcileLedgerProtection(x.roles.transferPool,x.roles.authPool,x.signed.identity,resource,id,version));
 const wearService=new WearService(x.flow.flowPool,x.roles.authPool,x.signed.identity),fixtures=await registerWear(ledger,wearService),recs=new RecommendationService(x.roles.recommendationPool,x.principal,x.holds,x.quotes);
 const wear=(key:string)=>({key,sport:'WEAR' as const,heightCm:null,footCm:null,adultAtStart:true,tier:'STANDARD' as const,ski:null,poleVariantId:null,wearSport:'SKI' as const,wearSelection:fixtures.selection});
 const integrated=(date:string):RecommendationInput=>({...inputFor(date),contractVersion:'INTEGRATED_V1_2' as const,members:[{...inputFor(date).members[0]!,wearSelection:fixtures.selection},wear('wear-b')]});
 await check('quantity pools contain no garment Assets, preserve source audit and model edition identity',async()=>{
  const pools=(await wearService.overview('MOUNTAIN_BASE')).pools;assert.equal(pools.length,4);assert.equal(pools.reduce((n,p)=>n+p.total,0),8);assert.equal((await x.db.pool.query("SELECT count(*)::int n FROM ledger_assets WHERE family LIKE 'WEAR_%'")).rows[0].n,0);
  await assert.rejects(ledger.update('models',fixtures.models.SKI!,{version:1,reason:'attempt',catalogSeason:'2025/26'}),{code:'INVALID_INPUT'});await assert.rejects(registerWear(ledger,wearService),{code:'DUPLICATE_RECORD'});
 });
 let premiumBookingId='',premiumBookingVersion=0;let first:Awaited<ReturnType<typeof recs.get>>;
 await check('mixed equipment+wear and wear-only preview -> explicit selection -> atomic7 claims -> immutable quote',async()=>{
  const p=await recs.preview(randomUUID(),integrated('2035-02-10'),null);assert.equal(p.preview.offered.length,2);assert.equal(p.preview.offered[1]!.price?.totalJpy,5000);assert.equal(p.preview.offered[0]!.price?.totalJpy,11500);
  assert.equal((await x.db.pool.query('SELECT count(*)::int n FROM inventory_holds')).rows[0].n,0);
  first=await recs.select(p.preview.id,randomUUID(),{...selection(),directions:{'ski-a':'RECOMMENDED','wear-b':'RECOMMENDED'}});assert.equal(first.selection?.stage,'COMPLETE');assert.equal(first.quote?.snapshot.totalJpy,16500);assert.equal(first.quote?.snapshot.chargeReady,false);
  const claims=(await x.db.pool.query('SELECT asset_id,requirement_key FROM inventory_claims WHERE hold_id=$1 AND active UNION ALL SELECT NULL AS asset_id,requirement_key FROM wear_claims WHERE hold_id=$1 AND active',[first.hold!.id])).rows;assert.equal(claims.length,7);assert.equal(new Set(claims.filter(r=>r.asset_id).map(r=>r.asset_id)).size,2);
  assert.equal((first.quote?.snapshot.items as unknown[]).length,3);assert.equal(first.quote?.snapshot.wearPriceVersion,'ZAO-WEAR-CATALOG-UX-20260913-V1_2');
 });
 await check('same shared garments consumed across ski/board; shortage leaves no partial group',async()=>{
  const input=integrated('2035-02-10');input.members=[{...wear('other'),wearSport:'SNOWBOARD'}];const p=await recs.preview(randomUUID(),input,null);assert.equal(p.preview.offered[0]!.reason,'INSUFFICIENT');
  const c=parseConditions({...first!.hold!.conditions,reservationId:randomUUID(),members:[first!.hold!.conditions.members[1]!]});assert.equal((await x.holds.command('create',randomUUID(),c)).result,'INSUFFICIENT');assert.equal((await x.db.pool.query('SELECT count(*)::int n FROM inventory_holds')).rows[0].n,1);
 });
 await check('model and season promise survive recommendation/HOLD/quote/payment snapshot; wrong model or class rejected',async()=>{
  const input=integrated('2035-02-11');input.members=[{...inputFor().members[0]!,tier:'PREMIUM',poleVariantId:fixtures.variants['POLE-110 cm']!,wearSelection:fixtures.selection,modelSelection:{modelId:fixtures.models.SKI!,season:'2026/27'}}];
  const p=await recs.preview(randomUUID(),input,null),saved=await recs.select(p.preview.id,randomUUID(),{...selection(),directions:{'ski-a':'RECOMMENDED'}});assert.equal(saved.selection?.stage,'COMPLETE');assert.equal(saved.hold!.conditions.members[0]!.items[0]!.modelPromise!.modelId,fixtures.models.SKI);assert.equal(saved.quote!.snapshot.totalJpy,13000);
  const contact={displayName:'SYNTHETIC Wear Premium',email:'synthetic-wear@example.invalid',termsAccepted:true};const booking=await x.service.create(randomUUID(),saved.quote!.id,contact);const paid=await x.service.startPayment(booking.id,randomUUID());assert.equal(paid.state,'CONFIRMED_DEV');premiumBookingId=paid.id;premiumBookingVersion=paid.version;
  const b=(await x.db.pool.query('SELECT * FROM rental_bookings WHERE id=$1',[booking.id])).rows[0];assert.equal(canonical(b.conditions),canonical(saved.hold!.conditions));assert.equal(b.price_snapshot.wearPriceVersion,'ZAO-WEAR-CATALOG-UX-20260913-V1_2');
  const bad=structuredClone(saved.hold!.conditions) as HoldConditions;bad.reservationId=randomUUID();bad.members[0]!.items[0]!.modelPromise!.modelId=fixtures.models.WEAR_JACKET!;await assert.rejects(x.holds.availability(bad),{code:'VARIANT_MISMATCH'});
 });
 await check('same saved request replay preserves original lease and immutable price snapshot',async()=>{
  const before=await recs.get(first!.preview.id);const snapshot=canonical(before.quote!.snapshot),ttl=before.hold!.expiresAt;await recs.resume(first!.preview.id);const after=await recs.get(first!.preview.id);assert.equal(canonical(after.quote!.snapshot),snapshot);assert.equal(after.hold!.expiresAt,ttl);
 });
 await check('two parallel last-pool HOLDs succeed once; no cross-store pool mixing or partial claims',async()=>{
  await x.clock('2035-01-01T10:20:00+09:00');const pools=(await wearService.overview('MOUNTAIN_BASE')).pools;for(const pool of pools)await wearService.adjust(randomUUID(),{poolId:pool.id,expectedRevision:pool.revision,ready:1,reason:'SYNTHETIC capacity test'});
  const c=parseConditions({...first!.hold!.conditions,reservationId:randomUUID(),period:{startDate:'2035-02-15',endDate:'2035-02-15',slot:'DAY'},members:[first!.hold!.conditions.members[1]!]});const result=await Promise.all([x.holds.command('create',randomUUID(),c),x.holds.command('create',randomUUID(),{...c,reservationId:randomUUID()})]);assert.deepEqual(result.map(r=>r.result).sort(),['CREATED','INSUFFICIENT']);
  const before=(await wearService.overview('MOUNTAIN_BASE')).pools;await assert.rejects(wearService.adjust(randomUUID(),{poolId:before.find(p=>p.variant_id===fixtures.selection.jacketVariantId)!.id,expectedRevision:before.find(p=>p.variant_id===fixtures.selection.jacketVariantId)!.revision,ready:0,reason:'must preserve HOLD'}),{code:'WEAR_CONFLICT'});
  assert.equal((await x.holds.availability({...c,pickupStore:'ONSEN_BASE',returnStore:'ONSEN_BASE'})).result,'INSUFFICIENT');
 });
 await check('real quantity checkout/foreign return retains planned store and quantity, leaves no same-day ready',async()=>{
  await x.clock('2035-02-11T10:00:00+09:00');const checkOut=await wearService.checkout(randomUUID(),{bookingId:premiumBookingId,expectedBookingVersion:premiumBookingVersion,store:'MOUNTAIN_BASE',reason:'SYNTHETIC checkout'});assert.equal(checkOut.loans.length,2);
  const jacket=checkOut.loans.find(l=>l.requirement_key.endsWith('WEAR_JACKET'))!,key=randomUUID(),input={loanId:jacket.id,expectedRevision:jacket.revision,store:'ONSEN_BASE',quantity:1,reason:'SYNTHETIC early cross-store return',unresolvedId:null};const receipt=await wearService.receive(key,input);assert.equal(receipt.remaining,0);assert.equal(receipt.automaticRefund,false);assert.deepEqual(await wearService.receive(key,input),JSON.parse(JSON.stringify(receipt)));
  const after=(await wearService.loans(premiumBookingId,'ONSEN_BASE')).find(l=>l.id===jacket.id)!;assert.equal(after.planned_return_store,'MOUNTAIN_BASE');assert.equal(receipt.receipt!.actual_store,'ONSEN_BASE');assert.equal((await wearService.overview('ONSEN_BASE')).pools.find(p=>p.variant_id===jacket.variant_id)!.ready,0);
  const started=await wearService.cleaning(randomUUID(),{receiptId:receipt.receipt!.id,expectedRevision:receipt.receipt!.revision,operation:'START',confirmedReady:false,reason:'SYNTHETIC washing'});const completed=await wearService.cleaning(randomUUID(),{receiptId:started.id,expectedRevision:started.revision,operation:'COMPLETE',confirmedReady:true,reason:'Actual synthetic dry/ready confirmation'});assert.equal(completed.state,'TODAY_BLOCKED');await assert.rejects(wearService.cleaning(randomUUID(),{receiptId:completed.id,expectedRevision:completed.revision,operation:'RELEASE_NEXT_DAY',confirmedReady:true,reason:'same day forbidden'}),{code:'SAME_DAY_REHIRE_BLOCKED'});
  const pants=checkOut.loans.find(l=>l.id!==jacket.id)!;const u=await wearService.unresolved(randomUUID(),{variantId:pants.variant_id,store:'ONSEN_BASE',quantity:1,reason:'SYNTHETIC unidentified return'});assert.equal(u.addedToSellable,0);const pkey=randomUUID(),pin={loanId:pants.id,expectedRevision:pants.revision,store:'ONSEN_BASE',quantity:1,reason:'SYNTHETIC resolved to same loan',unresolvedId:u.id};const concurrent=await Promise.allSettled([wearService.receive(pkey,pin),wearService.receive(randomUUID(),pin)]);assert.equal(concurrent.filter(r=>r.status==='fulfilled').length,1);assert.equal((await wearService.overview('ONSEN_BASE')).pools.find(p=>p.variant_id===pants.variant_id)!.returned_pending,1);
  await x.clock('2035-02-12T09:00:00+09:00');const ready=await wearService.cleaning(randomUUID(),{receiptId:completed.id,expectedRevision:completed.revision,operation:'RELEASE_NEXT_DAY',confirmedReady:true,reason:'Next day actual ready'});assert.equal(ready.state,'READY');const dest=(await wearService.overview('ONSEN_BASE')).pools;assert.equal(dest.find(p=>p.variant_id===jacket.variant_id)!.ready,1);assert.equal(dest.find(p=>p.variant_id===pants.variant_id)!.ready,0);
  const total=(await x.db.pool.query('SELECT sum(total)::int n FROM wear_pools')).rows[0].n;assert.equal(total,4);assert.equal((await x.db.pool.query('SELECT count(*)::int n FROM wear_receipts')).rows[0].n,2);assert.equal((await x.db.pool.query('SELECT count(*)::int n FROM rental_payment_attempts')).rows[0].n,1);
 });
 await check('quantity plan protects source; dispatch has no arrival; actual receipts need separate ready confirmation',async()=>{
  const source=(await wearService.overview('ONSEN_BASE')).pools.find(p=>p.variant_id===fixtures.selection.jacketVariantId)!;const beforeTotal=(await x.db.pool.query('SELECT sum(total)::int n FROM wear_pools')).rows[0].n;
  const planned=await wearService.planTransfer(randomUUID(),{poolId:source.id,expectedRevision:source.revision,destinationStore:'MOUNTAIN_BASE',quantity:1,scheduledDate:'2035-02-12',reason:'SYNTHETIC actual cross-store quantity relocation'});assert.equal(planned.state,'PLANNED');
  const nowSource=(await wearService.overview('ONSEN_BASE')).pools.find(p=>p.id===source.id)!;assert.equal(nowSource.ready,1);await assert.rejects(wearService.adjust(randomUUID(),{poolId:source.id,expectedRevision:nowSource.revision,ready:0,reason:'cannot remove planned stock'}),{code:'WEAR_CONFLICT'});
  const input={transferId:planned.id,expectedRevision:planned.revision,operation:'DISPATCH',quantity:null,reason:'SYNTHETIC dispatch'};await assert.rejects(wearService.transfer(randomUUID(),input),{code:'DEPARTURE_NOT_READY'});await x.clock('2035-02-12T17:00:00+09:00');const dispatched=await wearService.transfer(randomUUID(),input);assert.equal(dispatched.transfer.state,'IN_TRANSIT');assert.equal((await wearService.overview('ONSEN_BASE')).pools.find(p=>p.id===source.id)!.in_transit,1);
  await x.clock('2035-02-12T17:10:00+09:00');assert.equal((await wearService.transfers('MOUNTAIN_BASE')).find(t=>t.id===planned.id)!.state,'IN_TRANSIT');await assert.rejects(wearService.transfer(randomUUID(),{...input,expectedRevision:dispatched.transfer.revision,operation:'CANCEL'}),{code:'PHYSICAL_TRANSFER_CANNOT_CANCEL'});
  const rk=randomUUID(),receive={...input,expectedRevision:dispatched.transfer.revision,operation:'RECEIVE',quantity:1};const received=await wearService.transfer(rk,receive);assert.equal(received.transfer.state,'RECEIVED');assert.deepEqual(await wearService.transfer(rk,receive),JSON.parse(JSON.stringify(received)));const dest=(await wearService.overview('MOUNTAIN_BASE')).pools.find(p=>p.variant_id===source.variant_id)!;assert.equal(dest.ready,0);assert.equal(dest.returned_pending,1);
  const receipt=received.receipts[0];const ready=await wearService.transferReady(randomUUID(),{receiptId:receipt.id,expectedRevision:receipt.revision,confirmedReady:true,reason:'SYNTHETIC received stock actually ready'});assert.equal(ready.state,'READY');assert.equal((await x.db.pool.query('SELECT sum(total)::int n FROM wear_pools')).rows[0].n,beforeTotal);await assert.rejects(wearService.planTransfer(randomUUID(),{poolId:dest.id,expectedRevision:dest.revision,destinationStore:'ONSEN_BASE',quantity:1,scheduledDate:'2035-02-12',reason:'cannot append after departure'}));
 });
 await check('quantity transfer partial receipts and two terminals conserve in-transit and destination totals',async()=>{
  const source=(await wearService.overview('MOUNTAIN_BASE')).pools.find(p=>p.variant_id===fixtures.variants['WEAR_JACKET-L'])!;const raised=await wearService.adjust(randomUUID(),{poolId:source.id,expectedRevision:source.revision,ready:2,reason:'SYNTHETIC two-quantity partial transfer'});const total=(await x.db.pool.query('SELECT sum(total)::int n FROM wear_pools')).rows[0].n;
  const t=await wearService.planTransfer(randomUUID(),{poolId:source.id,expectedRevision:raised.revision,destinationStore:'ONSEN_BASE',quantity:2,scheduledDate:'2035-02-13',reason:'SYNTHETIC partial transport'});await x.clock('2035-02-13T17:00:00+09:00');const dispatched=await wearService.transfer(randomUUID(),{transferId:t.id,expectedRevision:t.revision,operation:'DISPATCH',quantity:null,reason:'SYNTHETIC departure'});
  const input={transferId:t.id,expectedRevision:dispatched.transfer.revision,operation:'RECEIVE',quantity:1,reason:'SYNTHETIC partial arrival'};const outcomes=await Promise.allSettled([wearService.transfer(randomUUID(),input),wearService.transfer(randomUUID(),input)]);assert.equal(outcomes.filter(r=>r.status==='fulfilled').length,1);const partial=outcomes.find(r=>r.status==='fulfilled')!;assert.equal(partial.status,'fulfilled');if(partial.status!=='fulfilled')throw new Error('No partial receipt');assert.equal(partial.value.transfer.state,'IN_TRANSIT');assert.equal(partial.value.transfer.received,1);assert.equal((await wearService.overview('MOUNTAIN_BASE')).pools.find(p=>p.id===source.id)!.in_transit,1);assert.equal((await wearService.overview('ONSEN_BASE')).pools.find(p=>p.variant_id===source.variant_id)!.returned_pending,1);
  const completed=await wearService.transfer(randomUUID(),{...input,expectedRevision:partial.value.transfer.revision});assert.equal(completed.transfer.state,'RECEIVED');assert.equal(completed.receipts.length,2);assert.equal((await x.db.pool.query('SELECT sum(total)::int n FROM wear_pools')).rows[0].n,total);assert.equal((await wearService.overview('ONSEN_BASE')).pools.find(p=>p.variant_id===source.variant_id)!.ready,0);
 });
 await check('wear quantity requirement cannot be reassigned to an individual Asset',async()=>{await assert.rejects(x.holds.command('reassign',randomUUID(),{requirementKey:'wear-b:WEAR_JACKET',assetId:randomUUID()},first!.hold!.id,first!.hold!.version),{code:'INVALID_REQUIREMENT'});});
 console.log(`WEAR real PostgreSQL ${count} passed; normal library session and real roles; synthetic quantity checkout/return executed; no real stock, Square, equipment custody or phone.`);
}catch(e){failed=true;console.error('WEAR_DB_FAILED '+stage+' '+((e as {code?:string}).code??(e as Error).name));console.error((e as Error).stack?.split('\n').filter(l=>l.includes('/tests/wear/')).join('\n'));if(e instanceof assert.AssertionError)console.error(JSON.stringify({actual:e.actual,expected:e.expected}));}finally{await x.close();console.log('Owned wear PostgreSQL and pools stopped.');}if(failed)process.exit(1);
