import {createHash,randomUUID} from 'node:crypto';
import type {Pool,PoolClient} from 'pg';
import {authorizeBookingActor,type BookingActor} from '../../../auth/src/booking-actor';
import {canonical,HoldError,type HoldConditions} from '../../../contracts/src/hold';
import {holdScope,type CandidateContext} from '../../../contracts/src/hold-intake';
import {exact,id,code} from '../../../contracts/src/pricing';
import {parseRecommendation,buildMembers,sizing,rankCandidates,RECOMMENDATION_RULE,MODEL_POLICY,DIRECTIONS,RecommendationError,type RecommendationInput,type MemberRecommendation,type Direction,type Variant} from '../../../contracts/src/recommendation';
import {HoldService} from '../inventory/hold-service';
import {QuoteService} from '../pricing/quote-service';
type Conn=Pick<PoolClient,'query'>;
type Preview={id:string;owner_id:string;request_key:string;fingerprint:string;rule_version:string;model_policy:string;input:RecommendationInput;offered:MemberRecommendation[];reservation_id:string;replacement_hold_id:string|null;replacement_version:number|null;created_at:Date};
type Selection={preview_id:string;owner_id:string;request_key:string;fingerprint:string;selection:{directions:Record<string,Direction>;wantAdvance:boolean;couponCode:string|null;acceptedModelPolicy:true};conditions:HoldConditions;hold_key:string;quote_key:string;hold_id:string|null;quote_id:string|null;stage:'INTENT'|'HOLD_FAILED'|'HOLD_SAVED'|'COMPLETE';outcome:string|null};
const hash=(x:unknown)=>createHash('sha256').update(canonical(x)).digest('hex');
export class RecommendationService {
 constructor(private pool:Pool,private principal:BookingActor,private holds:HoldService,private quotes:QuoteService,private variantFilter?:(variants:Variant[])=>Promise<Variant[]>){}
 private async auth(c:Conn,edit=false,stores:string[]=[]){return authorizeBookingActor(c,this.principal,['HOLD_VIEW','QUOTE_VIEW',...(edit?['HOLD_EDIT','QUOTE_CREATE']:[])],stores);}
 private async owned(c:Conn,previewId:string,edit=false){id(previewId);await this.auth(c,edit);const p=(await c.query<Preview>('SELECT * FROM recommendation_previews WHERE id=$1 AND owner_id=$2',[previewId,this.principal.subject])).rows[0];if(!p)throw new RecommendationError('FORBIDDEN',403);await this.auth(c,edit,[p.input.pickupStore,p.input.returnStore]);return p;}
 private normalize(e:unknown):never{if(e instanceof HoldError)throw e;const code=(e as {code?:string})?.code;if(['55P03','57014','40001','40P01'].includes(code??'')||e instanceof Error&&/timeout|timed out/i.test(e.message))throw new RecommendationError('INDETERMINATE',503);throw new RecommendationError('RECOMMENDATION_FAILED',500);}
 private async tx<T>(lock:string,edit:boolean,preflight:(c:Conn)=>Promise<unknown>,fn:(c:PoolClient)=>Promise<T>){let c:PoolClient|undefined;try{await this.auth(this.pool,edit);await preflight(this.pool);c=await this.pool.connect();await c.query('BEGIN');await c.query("SET LOCAL statement_timeout='5000ms';SET LOCAL idle_in_transaction_session_timeout='15000ms';SET LOCAL lock_timeout='1500ms'");await this.auth(c,edit);await preflight(c);if(!(await c.query<{ok:boolean}>('SELECT pg_try_advisory_xact_lock(71820900,hashtext($1)) AS ok',[lock])).rows[0]!.ok)throw new RecommendationError('OPERATION_IN_PROGRESS',409);await this.auth(c,edit);await preflight(c);await c.query("SELECT set_config('zao.actor',$1,true)",[this.principal.subject]);const value=await fn(c);await c.query('COMMIT');return value;}catch(e){await c?.query('ROLLBACK').catch(()=>{});return this.normalize(e);}finally{c?.release();}}
 private async variants(){await this.auth(this.pool);const variants=await this.holds.recommendationCatalog();return this.variantFilter?this.variantFilter(variants):variants;}
 async options(){return {variants:await this.variants(),ruleVersion:RECOMMENDATION_RULE,modelPolicy:MODEL_POLICY,productionAvailable:false};}
 async list(){const p=await this.auth(this.pool);return (await this.pool.query('SELECT id,input,created_at FROM recommendation_previews WHERE owner_id=$1 AND input->>\'pickupStore\'=ANY($2::text[]) AND input->>\'returnStore\'=ANY($2::text[]) ORDER BY created_at DESC,id LIMIT 50',[p.subject,p.storeIds])).rows;}
 async get(previewId:string){const p=await this.owned(this.pool,previewId);const s=(await this.pool.query<Selection>('SELECT * FROM recommendation_selections WHERE preview_id=$1',[p.id])).rows[0]??null;const hold=s?.hold_id?await this.holds.get(s.hold_id):null;const quote=s?.quote_id?await this.quotes.get(s.quote_id):null;await this.auth(this.pool,false,[p.input.pickupStore,p.input.returnStore]);const matches=Boolean(s&&hold&&hash(hold.conditions)===hash(s.conditions));return {preview:p,selection:s,hold,quote,selectionMatchesHold:matches,meaning:'PRIVATE_PREVIEW_NOT_BOOKING_OR_PAYMENT'};}
 async preview(requestKey:string,input:unknown,replaceHoldId:string|null){
  id(requestKey);if(replaceHoldId!==null)id(replaceHoldId);const parsed=parseRecommendation(input),fingerprint=hash({input:parsed,replaceHoldId,rule:RECOMMENDATION_RULE,model:MODEL_POLICY});await this.auth(this.pool,false,[parsed.pickupStore,parsed.returnStore]);
  const prior=(await this.pool.query<Preview>('SELECT * FROM recommendation_previews WHERE owner_id=$1 AND request_key=$2',[this.principal.subject,requestKey])).rows[0];if(prior){if(prior.fingerprint!==fingerprint)throw new RecommendationError('IDEMPOTENCY_MISMATCH',409);return this.get(prior.id);}
  const replacement=replaceHoldId?await this.holds.get(replaceHoldId):null;
  if(replacement&&(replacement.state!=='ACTIVE'||replacement.allocationStage!=='PROVISIONAL'||!['NONE','FAILURE'].includes(replacement.paymentState)))throw new RecommendationError('HOLD_NOT_CHANGEABLE',409);
  const reservationId=replacement?.reservationId??randomUUID(),variants=await this.variants(),offered:MemberRecommendation[]=[];
  // Full input scope is constructed server-side, separate from the single-person candidate.
  const scope=holdScope({...(parsed.contractVersion?{contractVersion:parsed.contractVersion}:{}),reservationId,pickupStore:parsed.pickupStore,returnStore:parsed.returnStore,period:parsed.period,members:parsed.members.map(m=>({key:m.key,product:m.sport==='WEAR'?'WEAR_SET':m.sport==='SKI'?'SKI_SET':'SNOWBOARD_SET',age:m.adultAtStart?'ADULT':'KIDS',tier:m.tier,...(m.sport==='WEAR'?{wearSport:m.wearSport!}:m.wearSelection?{wear:true}:{}),items:[...(m.sport==='WEAR'?[]:m.sport==='SKI'?['SKI','SKI_BOOT','POLE'] as const:['SNOWBOARD','SNOWBOARD_BOOT'] as const).map(family=>({family,variantIds:[],...(m.modelSelection&&family===m.sport?{modelPromise:{...m.modelSelection,variantId:''}}:{})})),...(m.wearSelection?[{family:'WEAR_JACKET' as const,variantIds:[]},{family:'WEAR_PANTS' as const,variantIds:[]}]:[])]}))});
  let candidateChecks=0;
  for(const member of parsed.members){const context:CandidateContext|undefined=replacement?{scope,memberKey:member.key,expectedVersion:replacement.version}:undefined;const built=buildMembers(member,variants),size=member.sport==='WEAR'?{targetCm:0,minCm:0,maxCm:0,bootCm:0}:sizing(member),checks:MemberRecommendation['checks']=[],feasible=[];
   for(const candidate of built.candidates){if(++candidateChecks>120)throw new RecommendationError('INDETERMINATE_CANDIDATE_LIMIT',503);const c:HoldConditions={...(parsed.contractVersion?{contractVersion:parsed.contractVersion}:{}),reservationId,pickupStore:parsed.pickupStore,returnStore:parsed.returnStore,period:parsed.period,members:[candidate.member]};const a=await this.holds.availability(c,replaceHoldId??undefined,context);checks.push({lengthCm:candidate.lengthCm,result:a.result});if(a.result==='FEASIBLE')feasible.push(candidate);}
   const candidates=rankCandidates(feasible,size.targetCm);let price:Record<string,unknown>|null=null,priceError:string|null=null;
   if(candidates.RECOMMENDED){try{price=await this.quotes.preview({conditions:{...(parsed.contractVersion?{contractVersion:parsed.contractVersion}:{}),reservationId,pickupStore:parsed.pickupStore,returnStore:parsed.returnStore,period:parsed.period,members:[candidates.RECOMMENDED.member]},holdId:null,couponCode:null,wantAdvance:false},context&&replaceHoldId?{...context,holdId:replaceHoldId}:undefined);}catch(e){if(!(e instanceof HoldError)||e.status===403)throw e;priceError=e.code;}}
   const reason=built.reason??(feasible.length?checks.some(x=>x.result==='INDETERMINATE')?'INDETERMINATE_SOME_CANDIDATES':null:checks.some(x=>x.result==='INDETERMINATE')?'INDETERMINATE':checks.some(x=>x.result==='TRANSFER_PLAN_REQUIRED')?'TRANSFER_PLAN_REQUIRED':'INSUFFICIENT');
   offered.push({key:member.key,...size,initialLengthCm:candidates.RECOMMENDED?.lengthCm??null,candidates,checks,reason,price,priceError});
  }
  const pid=await this.tx('preview:'+this.principal.subject+':'+requestKey,false,c=>this.auth(c,false,[parsed.pickupStore,parsed.returnStore]),async c=>{
   const old=(await c.query<Preview>('SELECT * FROM recommendation_previews WHERE owner_id=$1 AND request_key=$2',[this.principal.subject,requestKey])).rows[0];if(old){if(old.fingerprint!==fingerprint)throw new RecommendationError('IDEMPOTENCY_MISMATCH',409);return old.id;}
   const pid=randomUUID();await c.query('INSERT INTO recommendation_previews(id,owner_id,request_key,fingerprint,rule_version,model_policy,input,offered,reservation_id,replacement_hold_id,replacement_version) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)',[pid,this.principal.subject,requestKey,fingerprint,RECOMMENDATION_RULE,MODEL_POLICY,JSON.stringify(parsed),JSON.stringify(offered),reservationId,replaceHoldId,replacement?.version??null]);return pid;
  });return this.get(pid);
 }
 async advisory(previewId:string,value:unknown){const p=await this.owned(this.pool,previewId);const x=exact(value,['directions','wantAdvance','couponCode','acceptedModelPolicy']);
  if(x.acceptedModelPolicy!==true||typeof x.wantAdvance!=='boolean'||x.couponCode!==null||!x.directions||typeof x.directions!=='object'||Array.isArray(x.directions))throw new RecommendationError('INVALID_SELECTION');
  const directions=x.directions as Record<string,Direction>;if(Object.keys(directions).sort().join()!==p.input.members.map(m=>m.key).sort().join())throw new RecommendationError('INVALID_SELECTION');
  const members=p.input.members.map(m=>{const d=directions[m.key]!;if(!DIRECTIONS.includes(d))throw new RecommendationError('INVALID_SELECTION');const c=p.offered.find(o=>o.key===m.key)?.candidates[d];if(!c)throw new RecommendationError('CANDIDATE_NOT_OFFERED');return c.member;});
  return this.quotes.preview({conditions:{...(p.input.contractVersion?{contractVersion:p.input.contractVersion}:{}),reservationId:p.reservation_id,pickupStore:p.input.pickupStore,returnStore:p.input.returnStore,period:p.input.period,members},holdId:null,couponCode:null,wantAdvance:x.wantAdvance});
 }
 async select(previewId:string,requestKey:string,value:unknown){id(requestKey);const p=await this.owned(this.pool,previewId,true);const x=exact(value,['directions','wantAdvance','couponCode','acceptedModelPolicy']);if(x.acceptedModelPolicy!==true||typeof x.wantAdvance!=='boolean'||!x.directions||typeof x.directions!=='object'||Array.isArray(x.directions))throw new RecommendationError('INVALID_SELECTION');const directions=x.directions as Record<string,Direction>;
  if(Object.keys(directions).sort().join()!==p.input.members.map(m=>m.key).sort().join()||Object.values(directions).some(v=>!DIRECTIONS.includes(v)))throw new RecommendationError('INVALID_SELECTION');
  if(p.rule_version!==RECOMMENDATION_RULE||p.model_policy!==MODEL_POLICY)throw new RecommendationError('RULE_VERSION_UNSUPPORTED',409);
  const members=p.input.members.map(m=>{const choice=p.offered.find(o=>o.key===m.key)?.candidates[directions[m.key]!];if(!choice)throw new RecommendationError('CANDIDATE_NOT_OFFERED');return choice.member;});
  const selection={directions,wantAdvance:x.wantAdvance,couponCode:x.couponCode===null?null:code(x.couponCode),acceptedModelPolicy:true as const},fingerprint=hash(selection),conditions:HoldConditions={...(p.input.contractVersion?{contractVersion:p.input.contractVersion}:{}),reservationId:p.reservation_id,pickupStore:p.input.pickupStore,returnStore:p.input.returnStore,period:p.input.period,members};
  // Durable intent commits BEFORE either domain command. Retries use the same saved keys after any interruption.
  await this.tx(previewId,true,c=>this.owned(c,previewId,true),async c=>{const old=(await c.query<Selection>('SELECT * FROM recommendation_selections WHERE preview_id=$1 OR (owner_id=$2 AND request_key=$3)',[previewId,this.principal.subject,requestKey])).rows[0];if(old){if(old.preview_id!==previewId||old.request_key!==requestKey||old.fingerprint!==fingerprint)throw new RecommendationError('SELECTION_ALREADY_FIXED',409);return;}
   await c.query('INSERT INTO recommendation_selections(preview_id,owner_id,request_key,fingerprint,selection,conditions,hold_key,quote_key,hold_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[previewId,this.principal.subject,requestKey,fingerprint,JSON.stringify(selection),JSON.stringify(conditions),randomUUID(),randomUUID(),p.replacement_hold_id]);
  });return this.resume(previewId);
 }
 async resume(previewId:string){await this.tx(previewId,true,c=>this.owned(c,previewId,true),async c=>{
  const p=await this.owned(c,previewId,true),s=(await c.query<Selection>('SELECT * FROM recommendation_selections WHERE preview_id=$1',[previewId])).rows[0];if(!s)throw new RecommendationError('NO_SAVED_SELECTION',409);if(s.stage==='COMPLETE'||s.stage==='HOLD_FAILED')return;
  if(s.stage==='INTENT'){
   try{const h=await this.holds.command(p.replacement_hold_id?'amend':'create',s.hold_key,s.conditions,p.replacement_hold_id??undefined,p.replacement_version??undefined);
    if(!['CREATED','AMENDED'].includes(h.result)){await c.query("UPDATE recommendation_selections SET stage='HOLD_FAILED',hold_id=$2,outcome=$3,updated_at=clock_timestamp() WHERE preview_id=$1",[p.id,h.holdId??null,h.result]);return;}
    if(!h.hold||hash(h.hold.conditions)!==hash(s.conditions)){await c.query("UPDATE recommendation_selections SET stage='HOLD_FAILED',hold_id=$2,outcome='HOLD_CONDITIONS_CHANGED',updated_at=clock_timestamp() WHERE preview_id=$1",[p.id,h.holdId??null]);return;}
    s.hold_id=h.hold.id;s.stage='HOLD_SAVED';await c.query("UPDATE recommendation_selections SET stage='HOLD_SAVED',hold_id=$2,outcome=NULL,updated_at=clock_timestamp() WHERE preview_id=$1",[p.id,s.hold_id]);
   }catch(e){if(!(e instanceof HoldError))throw e;const uncertain=e.status>=500||e.code==='OPERATION_IN_PROGRESS';await c.query('UPDATE recommendation_selections SET stage=$2,outcome=$3,updated_at=clock_timestamp() WHERE preview_id=$1',[p.id,uncertain?'INTENT':'HOLD_FAILED',e.code]);return;}
  }
  try{
   const held=await this.holds.get(s.hold_id!);if(hash(held.conditions)!==hash(s.conditions))throw new RecommendationError('HOLD_CONDITIONS_CHANGED',409);
   // Price from the server-read committed HOLD, never from browser amounts or an obsolete selection.
   const q=await this.quotes.create(s.quote_key,{conditions:held.conditions,holdId:held.id,couponCode:s.selection.couponCode,wantAdvance:s.selection.wantAdvance});
   await this.auth(c,true,[p.input.pickupStore,p.input.returnStore]);await c.query("UPDATE recommendation_selections SET stage='COMPLETE',quote_id=$2,outcome=NULL,updated_at=clock_timestamp() WHERE preview_id=$1",[p.id,q.quote.id]);
  }catch(e){if(!(e instanceof HoldError))throw e;await c.query("UPDATE recommendation_selections SET stage='HOLD_SAVED',outcome=$2,updated_at=clock_timestamp() WHERE preview_id=$1",[p.id,e.code]);}
 });return this.get(previewId);}
}
