 'use client';
import Image from 'next/image';
import {useEffect,useState,useRef} from 'react';
import type {PhotoJob,PhotoSelection} from '../../packages/core/src/content/photo-job';
import {invalidateStaffView} from '../../apps/web/src/components/StaffSessionBoundary';
const storage='zao-private-photo-job';
export function PhotoWorkspace({stamp}:{stamp:string}){
 const alive=useRef(true),controller=useRef<AbortController|null>(null);useEffect(()=>{alive.current=true;return()=>{alive.current=false;controller.current?.abort();};},[stamp]);
 const [files,setFiles]=useState<File[]>([]),[job,setJob]=useState<PhotoJob|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function call(path:string,body?:unknown){const r=await fetch('/api/photo-fixture'+path,{method:body?'POST':'GET',cache:'no-store',signal:controller.current?.signal??null,headers:{'content-type':'application/json','x-zao-session':stamp},...(body?{body:JSON.stringify(body)}:{})});if([401,403].includes(r.status)){invalidateStaffView();throw new Error('SESSION_CHANGED');}const d=await r.json();if(!r.ok){if(d.error==='SESSION_CHANGED')invalidateStaffView();throw new Error(d.error);}return d;}
 function choose(list:File[]){if(busy)return;if(!list.length||list.length>200||list.some(f=>f.size>10*1024*1024||!/[.](jpe?g|png|webp)$/i.test(f.name))||list.reduce((n,f)=>n+f.size,0)>500*1024*1024){setMessage('JPEG/PNG/WebP、各10MiB、200枚・合計500MiBまで。HEICは未対応です。');return;}setFiles(list);setMessage('選択済み。送信・変換はまだ行っていません。');}
 async function start(){if(busy||!files.length)return;controller.current=new AbortController();setBusy(true);setMessage('処理中…');try{
  const selections:PhotoSelection[]=[];for(const f of files){if(!alive.current||controller.current.signal.aborted)throw new Error('PAUSED');const hash=await crypto.subtle.digest('SHA-256',await f.arrayBuffer());selections.push({filename:f.name,bytes:f.size,sha256:[...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('')});}
  const prior=JSON.parse(sessionStorage.getItem(storage)??'null'),jobId=prior?.stamp===stamp?prior.jobId:crypto.randomUUID();sessionStorage.setItem(storage,JSON.stringify({stamp,jobId}));let saved:PhotoJob=await call('/prepare',{jobId,files:selections});setJob(saved);
  for(let index=0;index<saved.items.length;index++){if(!alive.current||controller.current.signal.aborted)throw new Error('PAUSED');if(saved.items[index]!.state!=='PENDING')continue;const bytes=new Uint8Array(await files[index]!.arrayBuffer());let binary='';for(let n=0;n<bytes.length;n+=32768)binary+=String.fromCharCode(...bytes.subarray(n,n+32768));await call('/upload',{jobId,index,base64:btoa(binary)});saved=await call('?jobId='+jobId);setJob(saved);}
  if(alive.current)setMessage('処理結果を保存しました。商品への正式紐付け・権利承認・公開はしていません。');
 }catch{if(alive.current)setMessage('未確認または拒否。同じファイルを再選択し、保存済みjobを照合してください。');}finally{if(alive.current)setBusy(false);}}
 async function recover(){controller.current=new AbortController();try{const prior=JSON.parse(sessionStorage.getItem(storage)??'null');if(prior?.stamp!==stamp)throw new Error('NO_JOB');setJob(await call('?jobId='+prior.jobId));setMessage('保存済み。未送信分は同じファイルの再選択で再開できます。');}catch{setMessage('保存済みjobを確認できません。');}}
 return <section aria-label="写真一括fixture"><h2>写真の一括取込</h2><p>スキー・ボード両対応。元画像は非公開保存、表示画像はEXIFを除去。名前の完全一致は候補であり、モデル・権利の確認を代行しません。</p><fieldset disabled={busy}><label>写真ファイル<input type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={e=>choose(Array.from(e.target.files??[]))}/></label><div onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();choose(Array.from(e.dataTransfer.files));}} style={{border:'1px dashed',padding:16}}>ここへ写真をまとめてドロップできます</div><p>{files.length}枚選択</p><button disabled={!files.length} onClick={()=>void start()}>選択した写真を送信・再開</button><button onClick={()=>void recover()}>保存済み写真jobを照合</button><button onClick={()=>{sessionStorage.removeItem(storage);setJob(null);setFiles([]);setMessage('別jobの準備。過去の保存画像は削除していません。');}}>別の写真jobを開始</button></fieldset><button disabled={!busy} onClick={()=>controller.current?.abort()}>写真処理を中断</button><p role="status" aria-label="写真処理状態">{message}</p>{job&&<><p>{job.state} / 変換済み {job.items.filter(i=>i.state==='READY').length} / 全{job.items.length}枚</p><p>初期表示は先頭20件。全件の結果・再開状態はサーバーjobに保存します。</p>{job.items.slice(0,20).map((i,index)=><article key={index}><h3>{i.selection.filename}</h3><p>{i.state} / {i.candidate?i.candidate.offerCode+' '+i.candidate.role+' 候補':'紐付け要確認'} / {i.issues.join(' / ')} {i.error}</p>{i.metadata&&<Thumb stamp={stamp} jobId={job.id} index={index} filename={i.selection.filename}/>}</article>)}</>}</section>;
}
function Thumb({stamp,jobId,index,filename}:{stamp:string;jobId:string;index:number;filename:string}){const [url,setUrl]=useState<string|null>(null);useEffect(()=>{let active=true,owned:string|undefined;const abort=new AbortController();fetch('/api/photo-fixture/derivative?jobId='+jobId+'&index='+index,{headers:{'x-zao-session':stamp},cache:'no-store',signal:abort.signal}).then(async r=>{if(!r.ok)throw new Error('PHOTO_NOT_AVAILABLE');const blob=await r.blob();if(active){owned=URL.createObjectURL(blob);setUrl(owned);}}).catch(()=>{});return()=>{active=false;abort.abort();if(owned)URL.revokeObjectURL(owned);};},[stamp,jobId,index]);return url?<Image unoptimized src={url} alt={'合成fixture確認用 '+filename} width={240} height={180} style={{maxWidth:'100%',objectFit:'contain'}}/>:<p>画像未確認</p>;}
