import {staffState,getRuntime,publicStamp} from '../../apps/web/src/lib/staff-runtime';
import {decodePhotoBase64} from '../../packages/core/src/content/photo-input';
import {PrivatePhotoJobs} from '../../packages/core/src/content/photo-job';
import {ContentInputError} from '../../packages/core/src/content/bulk-plan';
import {PhotoFileFixture} from './photo-fixture';
const headers={'Cache-Control':'private, no-store','Vary':'Cookie','X-Content-Type-Options':'nosniff'};
export async function photoFixtureHandler(request:Request){try{
 if(process.env.NODE_ENV!=='development'||!process.env.ZAO_TEST_FLOW_RUNTIME||!process.env.ZAO_TEST_CONTENT_FIXTURE_ROOT)return Response.json({error:'UNCONNECTED'},{status:503,headers});const runtime=getRuntime();if(!runtime)throw new Error('UNCONNECTED');
 const state=await staffState(request.headers);if(state.status!=='authorized')return Response.json({error:'UNAUTHENTICATED'},{status:401,headers});const stamp=publicStamp(state.stamp),subject=state.principal.subject;if(request.headers.get('x-zao-session')!==stamp)return Response.json({error:'SESSION_CHANGED'},{status:409,headers});
 const store=new PhotoFileFixture(runtime.config.namespace),authority={async assert(s:string){const live=await staffState(request.headers);if(live.status!=='authorized'||live.principal.subject!==s||publicStamp(live.stamp)!==stamp||!(await store.file.read()).grants[s]?.includes('CONTENT_EDIT'))throw new ContentInputError('CONTENT_FORBIDDEN');}};
 await authority.assert(subject);const service=new PrivatePhotoJobs(store,authority),url=new URL(request.url),action=url.pathname.slice('/api/photo-fixture'.length);
 if(request.method==='GET'&&action===''){if([...url.searchParams.keys()].join()!=='jobId')throw new ContentInputError('PHOTO_QUERY');return Response.json(await service.read(subject,url.searchParams.get('jobId')!),{headers});}
 if(request.method==='GET'&&action==='/derivative'){if([...url.searchParams.keys()].sort().join()!=='index,jobId')throw new ContentInputError('PHOTO_QUERY');const job=await service.read(subject,url.searchParams.get('jobId')!),index=Number(url.searchParams.get('index')),item=Number.isInteger(index)?job.items[index]:undefined;const derivative=item?.metadata?.derivatives.find(d=>d.requestedWidth===320&&d.format==='webp');if(!derivative)throw new ContentInputError('PHOTO_NOT_READY');const b=await store.readDerivative(derivative.sha256);await authority.assert(subject);return new Response(new Uint8Array(b),{headers:{...headers,'Content-Type':'image/webp'}});}
 if(request.method!=='POST'||request.headers.get('origin')!==runtime.config.origin)return Response.json({error:'ORIGIN_REJECTED'},{status:403,headers});if(url.search||request.headers.get('content-type')?.split(';')[0]!=='application/json')throw new ContentInputError('PHOTO_REQUEST');
 const reader=request.body?.getReader();if(!reader)throw new ContentInputError('PHOTO_BODY');const chunks:Uint8Array[]=[];let size=0;try{for(;;){const part=await reader.read();if(part.done)break;size+=part.value.length;if(size>14*1024*1024){await reader.cancel();return Response.json({error:'BODY_TOO_LARGE'},{status:413,headers});}chunks.push(part.value);}}finally{reader.releaseLock();}
 const raw=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(Buffer.concat(chunks)));let result:unknown;
 if(action==='/prepare'){if(!raw||Object.keys(raw).sort().join()!=='files,jobId'||!Array.isArray(raw.files))throw new ContentInputError('PHOTO_REQUEST');const offers=Object.keys((await store.file.read()).state.catalog.commercialRevisions);result=await service.prepare(subject,raw.jobId,raw.files,offers);}
 else if(action==='/upload'){if(!raw||Object.keys(raw).sort().join()!=='base64,index,jobId')throw new ContentInputError('PHOTO_REQUEST');const bytes=decodePhotoBase64(raw.base64);result=await service.upload(subject,raw.jobId,raw.index,bytes);}
 else throw new ContentInputError('PHOTO_REQUEST');return Response.json(result,{headers});
 }catch(e){const code=e instanceof ContentInputError?e.code:'PHOTO_FIXTURE_FAILED';return Response.json({error:code},{status:code==='CONTENT_FORBIDDEN'?403:e instanceof ContentInputError?409:500,headers});}}
