 'use client';
import {PhotoWorkspace} from './PhotoWorkspace';
import {useEffect,useRef,useState} from 'react';
import {StaffSessionBoundary,invalidateStaffView} from '../../apps/web/src/components/StaffSessionBoundary';
import '../../apps/web/src/components/holds.css';
type Plan={planId:string;kind:'BULK'|'RELEASE';hash:string;issues:{code:string}[];completed:boolean};
type Snapshot={catalogSources:{sourceHash:string;source:{sourceDocument:string;sourceLocator:string;modelName:string;sport:string;season:string|null};issues:string[];candidateModelIds:string[]}[];drafts:{id:string;offerCode:string;locale:string;revision:number;content:{title:string;summary:string}}[];plans:Plan[];current:string|null;releases:{id:string}[]};
type Pending={action:string;body:{requestKey:string;input:unknown}};
const storage='zao-content-fixture-pending';
export function ContentFixtureWorkspace({stamp}:{stamp:string}){return <StaffSessionBoundary stamp={stamp}><Workspace stamp={stamp}/></StaffSessionBoundary>;}
function Workspace({stamp}:{stamp:string}){
 const [sourceRows,setSourceRows]=useState<unknown[]|null>(null);
 const [initial]=useState(()=>{try{const s=JSON.parse(sessionStorage.getItem(storage)??'null');return {pending:s?.stamp===stamp?s.pending:null,blocked:false};}catch{return {pending:null,blocked:true};}});
 const [data,setData]=useState<Snapshot|null>(null),[csv,setCsv]=useState('schema_version,offer_code,locale,expected_revision,field,operation,value\n'),[busy,setBusy]=useState(false),[message,setMessage]=useState(initial.blocked?'保存領域未確認。処理を開始しません。':''),[pending,setPending]=useState<Pending|null>(initial.pending);const alive=useRef(true),generation=useRef(0);
 async function api(action:string,body?:unknown){const r=await fetch('/api/content-fixture'+action,{method:body?'POST':'GET',headers:{'content-type':'application/json','x-zao-session':stamp},cache:'no-store',...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if([401,403].includes(r.status)||d.error==='SESSION_CHANGED'){invalidateStaffView();throw new Error('SESSION_CHANGED');}if(!r.ok)throw Object.assign(new Error(d.error),{definite:r.status<500});return d;}
 async function refresh(token:number){const d=await api('');if(alive.current&&generation.current===token)setData(d);}
 useEffect(()=>{alive.current=true;const token=++generation.current;void refresh(token).catch(()=>{if(alive.current&&generation.current===token)setMessage('下書きを取得できません。');});return()=>{alive.current=false;};},[stamp]); // eslint-disable-line react-hooks/exhaustive-deps
 async function send(p:Pending){if(busy)return;try{sessionStorage.setItem(storage,JSON.stringify({stamp,pending:p}));}catch{setMessage('保存領域未確認。処理を開始しません。');return;}setBusy(true);setMessage('処理中…');setPending(p);const token=++generation.current;try{const result=await api(p.action,p.body);if(!alive.current||generation.current!==token)return;sessionStorage.removeItem(storage);setPending(null);setMessage(result.state==='PARTIAL'?'一部の下書きを保存済み。失敗行は反映していません。':'保存済み。本番へは公開していません。');try{await refresh(token);}catch{setMessage('保存応答は受信済み。一覧を再読込してください。');}}catch(e){if(alive.current&&generation.current===token){if((e as {definite?:boolean}).definite){sessionStorage.removeItem(storage);setPending(null);}setMessage((e as {definite?:boolean}).definite?'拒否：'+(e as Error).message:'結果未確認。同じ保存要求を照合してください。');}}finally{if(alive.current&&generation.current===token)setBusy(false);}}
 const act=(action:string,input:unknown)=>void send({action,body:{requestKey:crypto.randomUUID(),input}});
 return <main className="holds"><h1>商品説明の非公開fixture</h1><p>合成データの操作確認です。価格・在庫・本番の公開内容は変えません。画像権利は合成設定であり、実写真の許可ではありません。</p><a href="/staff/logout">ログアウト</a><fieldset disabled={busy||!!pending||initial.blocked}><legend>一括下書き</legend><label>CSV本文<textarea value={csv} rows={7} onChange={e=>setCsv(e.target.value)}/></label><label>CSVファイル<input type="file" accept=".csv,text/csv" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>5*1024*1024){setMessage('CSVは5MiBまでです。');return;}const token=++generation.current;void file.text().then(text=>{if(alive.current&&generation.current===token)setCsv(text);}).catch(()=>setMessage('ファイルを読めません。'));}}/></label><button onClick={()=>act('/bulk-prepare',{csv})}>差分を検証して保存</button></fieldset>
 <section aria-label="現在の下書き"><h2>現在の下書き</h2>{data?.drafts.map(d=><article key={d.id}><h3>{d.offerCode} / {d.locale} / 版{d.revision}</h3><p>{d.content.title}</p><p>{d.content.summary}</p></article>)}</section><fieldset disabled={busy||!!pending||initial.blocked}><legend>保存した処理・非公開release</legend>{data?.plans.map(p=><article key={p.planId}><p>{p.kind} / {p.completed?'反映済み':'検証済み未反映'} / {p.planId}</p>{p.issues.map((i,n)=><p key={n}>{i.code}</p>)}{!p.completed&&<button disabled={p.kind==='RELEASE'&&p.issues.length>0} onClick={()=>act(p.kind==='BULK'?'/bulk-commit':'/release-commit',{planId:p.planId,hash:p.hash})}>{p.kind==='BULK'?'有効な下書きを反映':'非公開releaseへ反映'}：{p.planId}</button>}</article>)}<button disabled={!data} onClick={()=>act('/release-prepare',{entries:data!.drafts.map(d=>d.id),expectedCurrent:data!.current,restoreOf:null})}>下書き全体のreleaseを検証</button><p>現在の非公開release {data?.current??'なし'}</p>{data?.releases.map(r=><button key={r.id} onClick={()=>act('/release-prepare',{entries:[],expectedCurrent:data.current,restoreOf:r.id})}>このreleaseから復元案を検証：{r.id}</button>)}</fieldset>{pending&&!busy&&<button onClick={()=>void send(pending)}>同じ保存要求を照合</button>}<button disabled={busy} onClick={()=>{const token=++generation.current;void refresh(token).catch(()=>setMessage('取得できません。'));}}>下書きを再読込</button><p role="status" aria-label="説明処理状態">{message}</p><section aria-label="メーカー資料fixture"><h2>メーカー資料の照合stage</h2><p>合成のJSON行を照合するだけで、実在庫・モデル・価格を登録しません。過去2季＋新季の全SKUは未着です。</p><fieldset disabled={busy||!!pending||initial.blocked}><label>資料のJSONファイル<input type="file" accept="application/json,.json" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>2*1024*1024){setMessage('資料は2MiBまでです。');return;}const token=++generation.current;void file.text().then(text=>{const rows=JSON.parse(text);if(!Array.isArray(rows))throw new Error('ROWS');if(alive.current&&generation.current===token)setSourceRows(rows);}).catch(()=>setMessage('資料を読み込めません。'));}}/></label><button disabled={!sourceRows} onClick={()=>act('/catalog-prepare',{rows:sourceRows})}>資料の行を照合して保存</button></fieldset><p>保存済み照合行 {data?.catalogSources.length??0}件</p>{data?.catalogSources.slice(0,50).map(r=><article key={r.sourceHash}><p>{r.source.modelName} / {r.source.sport} / {r.source.season??'年度未確認'}</p><p>{r.source.sourceDocument} / {r.source.sourceLocator}</p><p>{r.issues.join(' / ')} / 候補数 {r.candidateModelIds.length}</p></article>)}</section><PhotoWorkspace stamp={stamp}/><p>ローカルfile fixtureの操作です。PostgreSQLのCMS transaction、実CMS権限、外部storage、顧客公開は未接続です。</p></main>;
}
