import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
import {mkdir} from 'node:fs/promises';
import {chromium,expect,type BrowserContext,type Page} from '@playwright/test';
import {startDevelopmentApp} from '../../scripts/development-app';
import {bootstrapDevelopmentAdmin} from '../../scripts/bootstrap-staff';
import {seedInventory,variants,skiSet} from '../inventory/fixture';
let app:Awaited<ReturnType<typeof startDevelopmentApp>>|undefined,lastPage:Page|undefined;let stage='startup',count=0,failed=false;const browser=await chromium.launch(),password=randomBytes(24).toString('base64url');
async function check(name:string,fn:()=>Promise<void>){stage=name;await fn();count++;console.log('PASS '+name);}
try{
 app=await startDevelopmentApp({built:true});await seedInventory(app.db.pool);await bootstrapDevelopmentAdmin(app.db.pool,{email:'e08-ui-bootstrap@example.invalid',displayName:'合成初期ADMIN',password});const {origin}=app;
 await app.db.pool.query("CREATE OR REPLACE FUNCTION inventory_clock() RETURNS timestamptz LANGUAGE sql VOLATILE AS $$SELECT '2035-01-01T00:00:00Z'::timestamptz$$");
 for(let i=0;i<100;i++){try{if((await fetch(origin+'/api/health')).ok)break;}catch{}if(i===99)throw new Error('APP_START_TIMEOUT');await new Promise(r=>setTimeout(r,100));}
 async function context(){const c=await browser.newContext({baseURL:origin,viewport:{width:1280,height:960}});c.setDefaultTimeout(10000);return c;}
 async function login(c:BrowserContext,email:string){const p=await c.newPage();await p.goto('/staff/login');await p.getByLabel('メールアドレス',{exact:true}).fill(email);await p.getByLabel('パスワード',{exact:true}).fill(password);await p.getByRole('button',{name:'ログイン',exact:true}).click();await p.waitForURL(origin+'/staff/ledger');return p;}
 const bootstrap=await context(),admin=await context(),staff=await context(),anon=await context();const bp=await login(bootstrap,'e08-ui-bootstrap@example.invalid');
 await check('normal ADMIN creates explicit price administrator and scoped quote staff; anonymous/default roles denied',async()=>{
  assert.equal((await anon.request.get('/api/quotes/catalog')).status(),401);assert.equal((await bootstrap.request.get('/api/quotes')).status(),403);await bp.goto('/staff/users');lastPage=bp;
  for(const [email,name,isAdmin]of [['e08-ui-price@example.invalid','合成料金管理',true],['e08-ui-staff@example.invalid','合成見積担当',false]] as const){stage='open staff create '+name;await bp.getByRole('button',{name:'スタッフを作成',exact:true}).click();const f=bp.getByRole('form',{name:'スタッフ作成'});await f.getByLabel('表示名',{exact:true}).fill(name);await f.getByLabel('メールアドレス',{exact:true}).fill(email);await f.getByLabel('初期パスワード（15〜128文字）').fill(password);stage='set role '+name;await f.getByLabel('Role',{exact:true}).selectOption(isAdmin?'ADMIN':'STAFF');await f.getByLabel('店舗範囲',{exact:true}).selectOption(isAdmin?'ALL':'ASSIGNED');if(!isAdmin)await f.getByLabel('MOUNTAIN_BASE',{exact:true}).check();for(const label of ['自分の非公開見積閲覧','自分の非公開見積作成','期間在庫・自分のHOLD閲覧','自分のHOLD取得・変更',...(isAdmin?['開発用料金版の設定（全店ADMINのみ）']:[])])await f.getByLabel(label,{exact:true}).selectOption('allow');stage='save account '+name;await f.getByRole('button',{name:'スタッフ設定を保存'}).click();await expect(bp.getByRole('heading',{name,exact:true})).toBeVisible();}
 });
 const ap=await login(admin,'e08-ui-price@example.invalid'),page=await login(staff,'e08-ui-staff@example.invalid');lastPage=page;
 await check('ordinary private UI initializes explicit source table using restricted pricing role',async()=>{await ap.goto('/staff/quotes');await ap.getByLabel('料金の対象開始日').fill('2035-01-01');await ap.getByLabel('料金の対象終了日').fill('2035-12-31');await ap.getByRole('button',{name:'開発用の初期料金を設定'}).click();await expect(ap.getByRole('region',{name:'料金版',exact:true})).toContainText('PRIVATE_AVAILABLE');assert.equal((await app!.db.pool.query('SELECT count(*)::int AS n FROM price_books')).rows[0].n,1);});
 let quoteId='',key='';
 await check('normal product/duration form -> protected API -> actual DB; response loss reconciles once after reload',async()=>{
  await page.goto('/staff/quotes');await expect(page.getByRole('heading',{name:'非公開の料金・見積',exact:true})).toBeVisible();await page.getByLabel('利用開始日',{exact:true}).fill('2035-01-05');await page.getByLabel('利用終了日',{exact:true}).fill('2035-01-05');await page.getByLabel('利用区分',{exact:true}).selectOption('AM');await page.getByLabel('スキーのサイズ 1',{exact:true}).selectOption(variants.ski);await page.getByLabel('スキーブーツのサイズ 1',{exact:true}).selectOption(variants.boot);await page.getByLabel('ポールのサイズ 1',{exact:true}).selectOption(variants.pole);await page.getByLabel('早割5％の適用見込みを確認').check();
  await page.route(origin+'/api/quotes',async route=>{if(route.request().method()!=='POST'){await route.continue();return;}const result=await route.fetch();assert.equal(result.status(),201);const v=await result.json();quoteId=v.quote.id;key=route.request().postDataJSON().requestKey;await route.abort('failed');});
  await page.getByRole('button',{name:'見積を作成して保存',exact:true}).click();await expect(page.getByRole('button',{name:'同じ要求を照合・再送'})).toBeVisible();await page.unroute(origin+'/api/quotes');await page.reload();await page.getByRole('button',{name:'同じ要求を照合・再送'}).click();await expect(page.getByRole('region',{name:'見積詳細'})).toContainText('5,320 円');await expect(page.getByRole('region',{name:'見積詳細'})).toContainText(quoteId);assert.equal((await app!.db.pool.query('SELECT count(*)::int AS n FROM price_quotes WHERE request_key=$1',[key])).rows[0].n,1);assert.equal((await app!.db.pool.query('SELECT snapshot FROM price_quotes WHERE id=$1',[quoteId])).rows[0].snapshot.totalJpy,5320);
  await mkdir('.local/screenshots',{recursive:true});await page.screenshot({path:'.local/screenshots/e08-quote-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'.local/screenshots/e08-quote-mobile-width.png',fullPage:true});
 });
 await check('multiple members and changed dates create a new saved quote; previous version remains readable',async()=>{
  await page.getByLabel('利用開始日',{exact:true}).fill('2035-01-05');await page.getByLabel('利用終了日',{exact:true}).fill('2035-01-06');await page.getByLabel('利用区分',{exact:true}).selectOption('MULTIDAY');await page.getByLabel('スキーのサイズ 1',{exact:true}).selectOption(variants.ski);await page.getByLabel('スキーブーツのサイズ 1',{exact:true}).selectOption(variants.boot);await page.getByLabel('ポールのサイズ 1',{exact:true}).selectOption(variants.pole);await page.getByRole('button',{name:'利用者を追加'}).click();await page.getByLabel('商品 2',{exact:true}).selectOption('SKI_EQUIPMENT_ONLY_ADULT_REGULAR');await page.getByLabel('スキーのサイズ 2',{exact:true}).selectOption(variants.skiAlt);await page.getByRole('button',{name:'見積を作成して保存',exact:true}).click();await expect(page.getByRole('region',{name:'見積詳細'})).toContainText('24,800 円'); // 13,800 +11,000, no advance checkbox after reload
  await page.getByRole('button',{name:new RegExp(quoteId.slice(0,8))}).click();await expect(page.getByRole('region',{name:'見積詳細'})).toContainText('5,320 円');
 });
 await check('ordinary HOLD conditions import and quote do not change expiry; altered UI conditions are refused',async()=>{
  const conditions=skiSet('2035-01-08');const hr=await staff.request.post('/api/holds',{headers:{origin},data:{requestKey:randomUUID(),conditions}});assert.equal(hr.status(),201);const h=(await hr.json()).hold;await page.reload();await page.getByRole('button',{name:'HOLD '+h.id,exact:true}).click();await page.getByRole('button',{name:'見積を作成して保存',exact:true}).click();await expect(page.getByRole('region',{name:'見積詳細'})).toContainText('7,500 円');const after=await staff.request.get('/api/holds/'+h.id);assert.equal((await after.json()).expiresAt,h.expiresAt);await page.getByLabel('利用開始日',{exact:true}).fill('2035-01-09');await page.getByLabel('利用終了日',{exact:true}).fill('2035-01-09');await page.getByRole('button',{name:'見積を作成して保存',exact:true}).click();await expect(page.getByRole('status')).toContainText('HOLD_CONDITIONS_MISMATCH');
 });
 await check('protected APIs reject forgery, missing CSRF origin, cross-user read and role/scope overreach',async()=>{
  const input={conditions:skiSet('2035-01-05'),holdId:null,couponCode:null,wantAdvance:false};assert.equal((await staff.request.post('/api/quotes',{data:{requestKey:randomUUID(),input}})).status(),403);assert.equal((await staff.request.post('/api/quotes',{headers:{origin},data:{requestKey:randomUUID(),input,totalJpy:1}})).status(),422);input.conditions.pickupStore='ONSEN_BASE';assert.equal((await staff.request.post('/api/quotes',{headers:{origin},data:{requestKey:randomUUID(),input}})).status(),403);assert.equal((await admin.request.get('/api/quotes/'+quoteId)).status(),403);
 });
 await check('logout/relogin preserves DB quotes; another session never receives old-user quote cache',async()=>{
  await page.getByRole('link',{name:'ログアウト',exact:true}).click();await page.getByRole('button',{name:'ログアウトする',exact:true}).click();await page.waitForURL(origin+'/staff/login');assert.equal((await staff.request.get('/api/quotes')).status(),401);const next=await login(staff,'e08-ui-staff@example.invalid');lastPage=next;await next.goto('/staff/quotes');await next.getByRole('button',{name:new RegExp(quoteId.slice(0,8))}).click();await expect(next.getByRole('region',{name:'見積詳細'})).toContainText('5,320 円');assert.equal((await admin.request.get('/api/quotes')).status(),200);assert.equal((await (await admin.request.get('/api/quotes')).json()).length,0);
  await bp.getByRole('button',{name:'スタッフを編集：合成見積担当'}).click();const form=bp.getByRole('form',{name:'スタッフ更新'});await form.getByLabel('自分の非公開見積閲覧',{exact:true}).selectOption('deny');await form.getByRole('button',{name:'スタッフ設定を保存'}).click();await expect(form).toHaveCount(0);await next.reload();await expect(next.getByRole('heading',{name:'見積の利用権限が必要です'})).toBeVisible();assert.equal((await staff.request.get('/api/quotes')).status(),403);
 });
 console.log(`E08 ordinary UI/API/PostgreSQL: ${count} passed; 0 skipped. Real synthetic email/password sessions; owner-controlled development clock. API/DB data not mocked. Only response-loss test aborts delivery AFTER real commit. Viewport is not a physical phone.`);
}catch(e){console.error('E08_UI_FAILED '+stage+' '+(e as Error).name);console.error((e as Error).stack?.split('\n').filter(l=>l.includes('/tests/pricing/normal-ui.ts:')).join('\n'));if(lastPage&&['/staff/quotes','/staff/users'].includes(new URL(lastPage.url()).pathname)){console.error('UI_STATUS '+await lastPage.getByRole('status').textContent().catch(()=>''));await mkdir('.local/screenshots',{recursive:true});await lastPage.screenshot({path:'.local/screenshots/e08-failure.png',fullPage:true});}failed=true;}finally{await browser.close();if(app)await app.stop();console.log('Owned E08 Web, browser and PostgreSQL stopped.');}if(failed)process.exit(1);
