import assert from 'node:assert/strict';
import {randomBytes,randomUUID,createHash} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {migrate,migrationPlan,migrationsDirectory} from '@rental/db';
import {startIsolatedPostgres} from '../../scripts/postgres';
import {provisionApplicationRoles} from '../../scripts/application-roles';
import {bootstrapDevelopmentAdmin} from '../../scripts/bootstrap-staff';
import {createStaffAuth,loadStaff,resolveStaff,type StaffPrincipal} from '../../packages/auth/src/staff-auth';
import {writeAccount,type AccountSettings} from '../../packages/auth/src/accounts';
import {authHandler} from '../../apps/web/src/lib/auth-http';
import {quoteHandler} from '../../apps/web/src/lib/quote-http';
import {QuoteService} from '../../packages/core/src/pricing/quote-service';
import {HoldService} from '../../packages/core/src/inventory/hold-service';
import {legacyHold,legacyTransfer} from '../fixtures/legacy-prefix';
import {seedInventory,requestFor,skiSet,variants,fid} from '../inventory/fixture';
import type {CouponTerms} from '../../packages/contracts/src/pricing';
let count=0,stage='startup',failed=false;const db=await startIsolatedPostgres();let roles:Awaited<ReturnType<typeof provisionApplicationRoles>>|undefined;
let now=new Date('2035-01-01T00:00:00Z');const origin='http://127.0.0.1:34567',password=randomBytes(24).toString('base64url'),secret=randomBytes(32).toString('hex');
async function check(name:string,fn:()=>Promise<void>){stage=name;await fn();count++;console.log('PASS '+name);}
try{
 for(const m of migrationPlan.slice(0,5)){const sql=await readFile(migrationsDirectory+'/'+m.file,'utf8');await db.pool.query(sql);await db.pool.query('CREATE TABLE IF NOT EXISTS foundation_migrations(id text PRIMARY KEY,checksum text NOT NULL)');await db.pool.query('INSERT INTO foundation_migrations VALUES($1,$2)',[m.id,createHash('sha256').update(sql).digest('hex')]);}
 await seedInventory(db.pool);const bootstrap=await bootstrapDevelopmentAdmin(db.pool,{email:'e08-bootstrap@example.invalid',displayName:'合成ADMIN',password}),bp=(await loadStaff(db.pool,bootstrap))!;
 const previous=(await writeAccount(db.pool,bp,undefined,{email:'e08-old@example.invalid',password,displayName:'合成旧担当',active:true,role:'STAFF',scope:'ASSIGNED',storeIds:['MOUNTAIN_BASE','ONSEN_BASE'],permissions:{TRANSFER_VIEW:true,TRANSFER_PLAN:true,HOLD_VIEW:true,HOLD_EDIT:true}})).id!;
 const oldHold=await legacyHold(db.pool,previous,requestFor('2035-01-02'),now);
 const batch=await legacyTransfer(db.pool,previous,fid(1204));
 const auth=createStaffAuth(db.pool,{origin,secret}),httpAuth=authHandler(auth,db.pool,origin,db.pool);
 async function login(email:string){const r=await httpAuth(new Request(origin+'/api/auth/sign-in/email',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify({email,password})}));assert.equal(r.status,200);return r.headers.getSetCookie().map(x=>x.split(';')[0]).join('; ');}
 const oldCookie=await login('e08-old@example.invalid');
 await check('populated exact PR7 prefix -> latest additive migrations concurrent migration preserves staff session, HOLD and transfer',async()=>{await Promise.all([migrate(db.pool),migrate(db.pool)]);assert.equal((await resolveStaff(auth,db.pool,new Headers({cookie:oldCookie}))).status,'authorized');assert.equal((await db.pool.query('SELECT count(*)::int AS n FROM foundation_migrations')).rows[0].n,migrationPlan.length);assert.equal((await db.pool.query('SELECT state FROM inventory_holds WHERE id=$1',[oldHold.holdId])).rows[0].state,'ACTIVE');assert.equal((await db.pool.query('SELECT state FROM transfer_batches WHERE id=$1',[batch.id])).rows[0].state,'PLANNED');});
 roles=await provisionApplicationRoles(db.pool,db.identity);
 const all:AccountSettings={displayName:'合成価格管理',active:true,role:'ADMIN',scope:'ALL',storeIds:[],permissions:{QUOTE_VIEW:true,QUOTE_CREATE:true,PRICE_EDIT:true,HOLD_VIEW:true,HOLD_EDIT:true}};
 const editorId=(await writeAccount(roles.authPool,bp,undefined,{...all,email:'e08-price@example.invalid',password})).id!,editor=(await loadStaff(db.pool,editorId))!;
 const settings:AccountSettings={displayName:'合成見積担当',active:true,role:'STAFF',scope:'ASSIGNED',storeIds:['MOUNTAIN_BASE'],permissions:{QUOTE_VIEW:true,QUOTE_CREATE:true,HOLD_VIEW:true,HOLD_EDIT:true}};
 const actor=(await writeAccount(roles.authPool,bp,undefined,{...settings,email:'e08-actor@example.invalid',password})).id!,principal=(await loadStaff(db.pool,actor))!;
 const svc=(p:StaffPrincipal=principal)=>new QuoteService(roles!.pricingPool,p,()=>now),prices=()=>svc(editor),holds=()=>new HoldService(roles!.holdPool,principal,()=>now);
 const input=()=>({conditions:skiSet('2035-01-05'),holdId:null as string|null,couponCode:null as string|null,wantAdvance:false});
 await check('PRICE_EDIT alone cannot turn STAFF or assigned-store ADMIN into a price administrator',async()=>{for(const [role,scope]of [['STAFF','ALL'],['ADMIN','ASSIGNED']] as const){const a=(await writeAccount(roles!.authPool,bp,undefined,{...settings,role,scope,permissions:{QUOTE_VIEW:true,QUOTE_CREATE:true,PRICE_EDIT:true},email:'e08-denied-'+role.toLowerCase()+'@example.invalid',password})).id!;const p=(await loadStaff(db.pool,a))!;await assert.rejects(svc(p).initializePrivate(randomUUID(),'2035-01-01','2035-12-31'),{code:'FORBIDDEN'});}});
 const firstBook=randomUUID();let firstQuote:Awaited<ReturnType<QuoteService['create']>>;let activation='';
 await check('no auto grants, draft invisible, explicit private source initialization, idempotent authorized setup',async()=>{
  await assert.rejects(svc(bp).catalog(),{code:'FORBIDDEN'});await assert.rejects(svc().create(randomUUID(),input()),{code:'NO_PRIVATE_PRICE_BOOK'});await assert.rejects(svc().initializePrivate(firstBook,'2035-01-01','2035-12-31'),{code:'FORBIDDEN'});
  const b=await prices().initializePrivate(firstBook,'2035-01-01','2035-12-31');assert.equal(b.state,'PRIVATE_AVAILABLE');assert.deepEqual((await prices().initializePrivate(firstBook,'2035-01-01','2035-12-31')).table_jpy,b.table_jpy);assert.equal((await db.pool.query('SELECT count(*)::int AS n FROM price_books')).rows[0].n,1);activation=(await prices().catalog()).active!.id;
  await assert.rejects(prices().initializePrivate(firstBook,'2035-02-01','2035-12-31'),{code:'IDEMPOTENCY_MISMATCH'});
 });
 await check('whole group explicit table -> quote DB snapshot; re-read immutable and replay does not duplicate',async()=>{
  const x=input();x.wantAdvance=true;const key=randomUUID();firstQuote=await svc().create(key,x);const q=firstQuote.quote;assert.equal(q.snapshot.totalJpy,7125);assert.equal(q.snapshot.subtotalJpy,7500);assert.equal(q.chargeReady,false);assert.equal(q.snapshot.taxDisplayBasis,'PENDING_OWNER_CONFIRMATION');assert.equal(q.validity,'VALID_PRIVATE_ESTIMATE');assert.deepEqual(await svc().get(q.id),q);const repeat=await svc().create(key,x);assert.equal(repeat.replayed,true);assert.equal(repeat.quote.id,q.id);assert.equal((await db.pool.query('SELECT count(*)::int AS n FROM price_quotes WHERE request_key=$1',[key])).rows[0].n,1);x.wantAdvance=false;await assert.rejects(svc().create(key,x),{code:'IDEMPOTENCY_MISMATCH'});
 });
 await check('all occupied dates one price book, future rental and actual variant constraints; no client prices',async()=>{
  const x=input();x.conditions.period={startDate:'2035-12-30',endDate:'2036-01-02',slot:'MULTIDAY'};await assert.rejects(svc().create(randomUUID(),x),{code:'PRICE_PERIOD_NOT_COVERED'});
  x.conditions=requestFor('2034-12-31');await assert.rejects(svc().create(randomUUID(),x),{code:'RENTAL_ALREADY_STARTED'});x.conditions=requestFor('2035-01-05',[variants.boot]);await assert.rejects(svc().create(randomUUID(),x),{code:'VARIANT_CONDITIONS_MISMATCH'});await assert.rejects(svc().create(randomUUID(),{...input(),totalJpy:1}),{code:'INVALID_INPUT'});
 });
 const nextBook=randomUUID();let nextActivation='';
 await check('draft edits are optimistic and isolated; activation predecessor and backdating are guarded',async()=>{
  await prices().createDraft(nextBook,firstBook,'2035-01-01','2035-12-31');await prices().editDraft(nextBook,1,'SKI_EQUIPMENT_ONLY_ADULT_REGULAR','DAY_1',6200);await assert.rejects(prices().editDraft(nextBook,1,'SKI_EQUIPMENT_ONLY_ADULT_REGULAR','DAY_1',99),{code:'STALE_PRICE_DRAFT'});await prices().editDraft(nextBook,2,'SKI_BOOTS_ONLY_ADULT_STANDARD','DAY_1',3300);assert.equal((await svc().create(randomUUID(),{...input(),conditions:requestFor('2035-01-05')})).quote.snapshot.totalJpy,6000);
  await assert.rejects(prices().activate(nextBook,3,'2034-12-31T23:59:59Z',activation),{code:'BACKDATED_ACTIVATION'});await assert.rejects(prices().activate(nextBook,3,'2035-01-01T00:00:01Z',null),{code:'PRICE_CONFLICT'});assert.equal((await db.pool.query('SELECT state FROM price_books WHERE id=$1',[nextBook])).rows[0].state,'DRAFT');
 });
 await check('concurrent activation and quote never mix two versions; previous quote amount/hash remain unchanged',async()=>{
  now=new Date('2035-01-01T00:00:01Z');const x=input();x.conditions=requestFor('2035-01-05');const boot=structuredClone(x.conditions.members[0]!);boot.key='boot';boot.items=[{family:'SKI_BOOT',variantIds:[variants.boot]}];x.conditions.members.push(boot);
  const [a,q]=await Promise.all([prices().activate(nextBook,3,now.toISOString(),activation),svc().create(randomUUID(),x)]);nextActivation=a.activationId;assert.ok([9000,9500].includes(Number(q.quote.snapshot.totalJpy)));const newQ=(await svc().create(randomUUID(),x)).quote;assert.equal(newQ.snapshot.totalJpy,9500);assert.equal(newQ.snapshot.priceBookId,nextBook);assert.deepEqual((await svc().get(firstQuote.quote.id)).snapshot,firstQuote.quote.snapshot);assert.equal((await svc().get(firstQuote.quote.id)).snapshotSha256,firstQuote.quote.snapshotSha256);await assert.rejects(prices().editDraft(nextBook,4,'SKI_SET_ADULT_REGULAR','DAY_1',1),{code:'STALE_PRICE_DRAFT'});
 });
 await check('scheduled immutable version activates by DB time; no previous-book date fallback or ambiguous successor',async()=>{
  const future=randomUUID();await prices().createDraft(future,nextBook,'2035-02-01','2035-12-31');const a=await prices().activate(future,1,'2035-01-02T00:00:00Z',nextActivation);assert.equal((await prices().catalog()).active!.book_id,nextBook);const fork=randomUUID();await prices().createDraft(fork,nextBook,'2035-01-01','2035-12-31');await assert.rejects(prices().activate(fork,1,'2035-01-03T00:00:00Z',nextActivation),{code:'PRICE_CONFLICT'});const keep=now;now=new Date('2035-01-02T00:00:00Z');assert.equal((await prices().catalog()).active!.id,a.activationId);await assert.rejects(svc().create(randomUUID(),input()),{code:'PRICE_PERIOD_NOT_COVERED'});now=keep;
 });
 let linked:string,linkedQuote:string;
 await check('HOLD owner/content/expiry coupling; quote does not extend 10 minutes or mutate claims',async()=>{
  const x=input();const h=await holds().command('create',randomUUID(),x.conditions);assert.equal(h.result,'CREATED');linked=h.holdId!;x.holdId=linked;const before=await holds().get(linked);const q=(await svc().create(randomUUID(),x)).quote;linkedQuote=q.id;assert.equal(q.snapshot.expiresAt,before.expiresAt);assert.equal((await holds().get(linked)).expiresAt,before.expiresAt);assert.deepEqual((await holds().get(linked)).conditions,before.conditions);
  x.conditions.period.startDate=x.conditions.period.endDate='2035-01-06';await assert.rejects(svc().create(randomUUID(),x),{code:'HOLD_CONDITIONS_MISMATCH'});await holds().command('amend',randomUUID(),x.conditions,linked);assert.equal((await svc().get(linkedQuote)).validity,'HOLD_CONDITIONS_MISMATCH');assert.equal((await holds().get(linked)).expiresAt,before.expiresAt);await holds().command('cancel',randomUUID(),undefined,linked);assert.equal((await svc().get(linkedQuote)).validity,'HOLD_EXPIRED_OR_RELEASED');
 });
 await check('late transfer attention is derived while HOLD remains live; no persisted issue flag is needed',async()=>{
  const old=now;now=new Date('2035-01-03T09:55:00Z');await writeAccount(roles!.authPool,bp,previous,{...settings,expectedRevision:(await loadStaff(db.pool,previous))!.revision,storeIds:['MOUNTAIN_BASE','ONSEN_BASE']});const p=(await loadStaff(db.pool,previous))!,hsvc=new HoldService(roles!.holdPool,p,()=>now),qsvc=svc(p);
  const conditions=requestFor('2035-02-05',[variants.board]);conditions.pickupStore=conditions.returnStore='ONSEN_BASE';conditions.members[0]!.items[0]!.family='SNOWBOARD';const h=await hsvc.command('create',randomUUID(),conditions);assert.equal(h.result,'CREATED');const x={conditions,holdId:h.holdId!,couponCode:null,wantAdvance:false};const q=(await qsvc.create(randomUUID(),x)).quote;assert.equal(q.validity,'VALID_PRIVATE_ESTIMATE');
  now=new Date('2035-01-03T10:01:00Z');assert.equal((await hsvc.get(h.holdId!)).state,'ACTIVE');assert.equal((await db.pool.query('SELECT transfer_attention FROM inventory_holds WHERE id=$1',[h.holdId])).rows[0].transfer_attention,null);assert.equal((await qsvc.get(q.id)).validity,'HOLD_RECONCILIATION_REQUIRED');await assert.rejects(qsvc.create(randomUUID(),x),{code:'HOLD_RECONCILIATION_REQUIRED'});await hsvc.command('cancel',randomUUID(),undefined,h.holdId);now=old;
 });
 const terms:CouponTerms={code:'SYNTHETIC-ONE',validFrom:'2035-01-01T00:00:00.000Z',validUntil:'2035-01-02T00:00:00.000Z',storeBasis:'PICKUP_STORE',stores:['MOUNTAIN_BASE'],products:['SKI_SET_ADULT_REGULAR'],kind:'FIXED_JPY',value:700,minimumJpy:7500,minimumBasis:'ELIGIBLE_SUBTOTAL',maximumDiscountJpy:700,advanceCombination:'ALLOW',maxActiveReservations:1};let couponId='';
 await check('coupon quotes never consume capacity; explicit combination computes integer total and records terms version',async()=>{
  couponId=randomUUID();await prices().createCoupon(couponId,terms);const x=input();x.couponCode=terms.code;x.wantAdvance=true;const q=(await svc().create(randomUUID(),x)).quote;assert.equal(q.snapshot.totalJpy,6460);assert.equal(q.snapshot.couponDiscountJpy,700);assert.equal(q.snapshot.advanceDiscountJpy,340);assert.equal(q.snapshot.couponVersionId,couponId);await svc().get(q.id);assert.equal((await db.pool.query('SELECT count(*)::int AS n FROM coupon_reservations')).rows[0].n,0);
  const invalid=input();invalid.couponCode='MISSING';await assert.rejects(svc().create(randomUUID(),invalid),{code:'COUPON_NOT_FOUND'});
 });
 await check('future reservation adapter capacity is atomic across connections and idempotent; redemption still absent',async()=>{
  const x=input();x.couponCode=terms.code;const q1=(await svc().create(randomUUID(),x)).quote,q2=(await svc().create(randomUUID(),x)).quote,k1=randomUUID(),k2=randomUUID();const out=await Promise.allSettled([svc().reserveCoupon(q1.id,k1),svc().reserveCoupon(q2.id,k2)]);assert.equal(out.filter(x=>x.status==='fulfilled').length,1);assert.equal(out.filter(x=>x.status==='rejected'&&(x.reason as {code:string}).code==='COUPON_LIMIT_REACHED').length,1);const win=out[0]!.status==='fulfilled';assert.equal((await svc().reserveCoupon(win?q1.id:q2.id,win?k1:k2)).replayed,true);assert.equal((await db.pool.query('SELECT count(*)::int AS n FROM coupon_reservations')).rows[0].n,1);await assert.rejects(svc().create(randomUUID(),x),{code:'COUPON_LIMIT_REACHED'});
 });
 await check('expiry invalidates current use without rewriting snapshot and releases reservation capacity only',async()=>{now=new Date('2035-01-01T00:11:02Z');const old=await svc().get(firstQuote.quote.id);assert.equal(old.validity,'EXPIRED');assert.deepEqual(old.snapshot,firstQuote.quote.snapshot);const x=input();x.couponCode=terms.code;assert.equal((await svc().create(randomUUID(),x)).quote.snapshot.totalJpy,6800);});
 await check('E08-01: expired quote keeps expiry as primary status even when linked HOLD is released',async()=>{assert.equal((await svc().get(linkedQuote)).validity,'EXPIRED');});
 await check('cutoff is inclusive for payment qualification but a zero-lifetime preview is refused; no locked-in early discount',async()=>{const old=now;now=new Date('2035-01-01T06:00:00Z');const x=input();x.conditions=skiSet('2035-01-02');x.wantAdvance=true;await assert.rejects(svc().create(randomUUID(),x),{code:'DISCOUNT_WINDOW_CLOSED'});now=new Date('2035-01-01T06:00:00.001Z');assert.equal((await svc().create(randomUUID(),x)).quote.snapshot.advanceDiscountJpy,0);now=old;});
 await check('concurrent HOLD amendment serializes quote check; pending/unknown payment blocks further use',async()=>{
  const x=input();x.conditions=skiSet('2035-01-10');const h=await holds().command('create',randomUUID(),x.conditions);assert.equal(h.result,'CREATED');x.holdId=h.holdId!;const changed=structuredClone(x.conditions);changed.period.startDate=changed.period.endDate='2035-01-11';const result=await Promise.allSettled([svc().create(randomUUID(),x),holds().command('amend',randomUUID(),changed,h.holdId)]);assert.equal(result[1]!.status,'fulfilled');if(result[0]!.status==='fulfilled')assert.equal((await svc().get(result[0].value.quote.id)).validity,'HOLD_CONDITIONS_MISMATCH');else assert.equal(result[0]!.reason.code,'HOLD_CONDITIONS_MISMATCH');
  x.conditions=changed;const q=(await svc().create(randomUUID(),x)).quote;const c=await db.pool.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('zao.actor',$1,true)",[actor]);await c.query("UPDATE inventory_holds SET payment_state='PENDING' WHERE id=$1",[h.holdId]);await c.query('COMMIT');}finally{c.release();}assert.equal((await svc().get(q.id)).validity,'HOLD_RECONCILIATION_REQUIRED');await assert.rejects(svc().create(randomUUID(),x),{code:'HOLD_RECONCILIATION_REQUIRED'});
 });
 await check('zero-total coupon remains a private unconfirmed no-payment gate, never a charge',async()=>{await prices().createCoupon(randomUUID(),{...terms,code:'SYNTHETIC-ZERO',value:100000,maximumDiscountJpy:100000,maxActiveReservations:null});const x=input();x.couponCode='SYNTHETIC-ZERO';const q=(await svc().create(randomUUID(),x)).quote;assert.equal(q.snapshot.totalJpy,0);assert.equal(q.snapshot.zeroTotalPath,'MANUAL_NO_PAYMENT_CONFIRMATION_REQUIRED');assert.equal(q.chargeReady,false);});
 await check('password/session/ordinary handler rejects anonymous, CSRF, spoof, other actor, scope and noneditor',async()=>{
  const cookie=await login('e08-actor@example.invalid'),handler=quoteHandler(h=>resolveStaff(auth,db.pool,h),p=>svc(p),origin),post=(body:unknown,headers:Record<string,string>={cookie,origin})=>handler(new Request(origin+'/api/quotes',{method:'POST',headers:{'content-type':'application/json',...headers},body:JSON.stringify(body)}));
  assert.equal((await handler(new Request(origin+'/api/quotes'))).status,401);const body={requestKey:randomUUID(),input:input()};assert.equal((await post(body,{cookie})).status,403);assert.equal((await post({...body,role:'ADMIN'})).status,422);assert.equal((await post({...body,actor:editorId})).status,422);const success=await post(body);assert.equal(success.status,201);assert.equal((await success.json()).quote.chargeReady,false);assert.equal((await handler(new Request(origin+'/api/quotes/'+firstQuote.quote.id,{headers:{cookie}}))).status,200);await assert.rejects(prices().get(firstQuote.quote.id),{code:'FORBIDDEN'});
  const block=await db.pool.connect();try{await block.query('BEGIN');await block.query('SELECT pg_advisory_xact_lock(71820800)');const other=input();other.conditions.pickupStore='ONSEN_BASE';const started=Date.now();assert.equal((await post({requestKey:randomUUID(),input:other})).status,403);assert.ok(Date.now()-started<1000);assert.equal((await handler(new Request(origin+'/api/quotes/private-initialize',{method:'POST',headers:{cookie,origin,'content-type':'application/json'},body:JSON.stringify({operation:'initializePrivate',input:{requestKey:randomUUID(),rentalFrom:'2035-01-01',rentalUntil:'2035-12-31'}})}))).status,403);}finally{await block.query('ROLLBACK');block.release();}
  assert.equal((await handler(new Request(origin+'/api/quotes/'+firstQuote.quote.id+'/reserve',{method:'POST',headers:{cookie,origin,'content-type':'application/json'},body:'{}'}))).status,404);
  await writeAccount(roles!.authPool,bp,actor,{...settings,expectedRevision:(await loadStaff(db.pool,actor))!.revision,permissions:{QUOTE_VIEW:true,QUOTE_CREATE:false}});assert.equal((await post(body)).status,403);await writeAccount(roles!.authPool,bp,actor,{...settings,expectedRevision:(await loadStaff(db.pool,actor))!.revision,active:false});assert.equal((await handler(new Request(origin+'/api/quotes',{headers:{cookie}}))).status,401);
 });
 await check('app DB cannot DDL, access passwords, alter HOLD, change audit/quotes/books; audit actor is verified caller',async()=>{
  for(const sql of ['CREATE TABLE forbidden_price(id int)','SELECT password FROM auth_account',"UPDATE inventory_holds SET state='RELEASED'",'UPDATE pricing_history SET event=event','UPDATE price_quotes SET snapshot=snapshot','DELETE FROM price_quotes'])await assert.rejects(roles!.pricingPool.query(sql),{code:'42501'});
  const c=await roles!.pricingPool.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('zao.actor',$1,true)",[editorId]);await assert.rejects(c.query('UPDATE price_books SET revision=revision+1 WHERE id=$1',[firstBook]),{code:'23514'});await c.query('ROLLBACK');}finally{c.release();}
  const history=(await db.pool.query("SELECT actor FROM pricing_history WHERE event='price_quotes_INSERT'")).rows;assert.ok(history.length>0&&history.every(h=>[actor,previous].includes(h.actor)));assert.ok((await db.pool.query('SELECT count(*)::int AS n FROM pricing_history WHERE entity_id=$1',[firstBook])).rows[0].n>=2);
 });
 console.log(`E08 real PostgreSQL: ${count} passed; 0 skipped. Synthetic accounts; injected service clock. Coupon reservation is not redemption. No payment/production operation.`);
}catch(e){console.error('E08_DB_FAILED '+stage+' '+((e as {code?:string}).code??(e as Error).name));if(e instanceof assert.AssertionError)console.error(JSON.stringify({actual:e.actual,expected:e.expected}));failed=true;}finally{if(roles)await roles.close();await db.stop();console.log('Owned E08 PostgreSQL stopped.');}if(failed)process.exit(1);
