import {createHash} from 'node:crypto';
import {canonical} from '../../../contracts/src/hold';
import type {ContentWorkflowState} from './workflow';
import type {Pool} from 'pg';
import type {GuestCatalog} from '../guest/service';
import type {Variant} from '../../../contracts/src/recommendation';
export type PublicMedia={alt:string;width:number;height:number;variants:{src:string;width:number;type:'image/webp'|'image/jpeg'}[]};
export type PublishedModel={slug:string;name:string;modelId:string;season:string;sport:'SKI'|'SNOWBOARD';lengths:string[];variantIds:string[];content:{ja:{title:string;summary:string};en:{title:string;summary:string}};media:PublicMedia};
export function validPublicMedia(value:unknown):value is PublicMedia{if(!value||typeof value!=='object')return false;const m=value as PublicMedia;return typeof m.alt==='string'&&m.alt.trim().length>0&&Number.isInteger(m.width)&&Number.isInteger(m.height)&&m.width>0&&m.height>0&&Array.isArray(m.variants)&&m.variants.length>0&&m.variants.every(v=>/^\/media\/[a-f0-9]{64}\/(?:[0-9]+)\.(?:webp|jpg)$/.test(v.src)&&['image/webp','image/jpeg'].includes(v.type)&&Number.isInteger(v.width)&&v.width>0);}
export async function releasedModels(pool:Pool):Promise<PublishedModel[]>{const state=(await pool.query('SELECT value FROM content_workspace WHERE id=true')).rows[0]?.value as ContentWorkflowState|undefined;const release=state?.catalog.releases.find(r=>r.id===state.catalog.current);if(!state||!release)return [];const rows=(await pool.query(`SELECT p.*,m.name,m.family,m.catalog_season FROM content_model_previews p JOIN ledger_models m ON m.id=p.model_id WHERE p.state='PREVIEW_APPROVED' AND p.shop_verified AND p.rights_verified AND p.translation_approved AND (p.rights_until IS NULL OR p.rights_until>clock_timestamp()) ORDER BY p.slug`)).rows;const out:PublishedModel[]=[];
 for(const p of rows){const revisions=release.entries.map(id=>state.catalog.revisions.find(r=>r.id===id)).filter(r=>r?.offerCode===p.slug);const ja=revisions.find(r=>r?.locale==='ja'),en=revisions.find(r=>r?.locale==='en');if(!ja||!en||!en.translationApproved||en.sourceRevision!==ja.id||canonical(p.content)!==canonical({ja:ja.content,en:en.content}))continue;if(!['SKI','SNOWBOARD'].includes(p.family)||p.catalog_season!==p.season||!validPublicMedia(p.media)||!p.content?.ja?.title||!p.content?.en?.title)continue;
  const variants=(await pool.query(`SELECT v.id,v.size FROM ledger_variants v WHERE v.id=ANY($1::uuid[]) AND v.model_id=$2 AND v.tier='PREMIUM' AND v.family=$3 AND EXISTS(SELECT 1 FROM ledger_assets a WHERE a.variant_id=v.id AND a.status<>'RETIRED') ORDER BY v.size`,[p.variant_ids,p.model_id,p.family])).rows;if(variants.length!==p.variant_ids.length)continue;
  let mediaReady=true;for(const v of p.media.variants){const digest=v.src.split('/')[2],bytes=(await pool.query('SELECT bytes FROM content_media_objects WHERE sha256=$1',[digest])).rows[0]?.bytes as Buffer|undefined;if(!bytes||createHash('sha256').update(bytes).digest('hex')!==digest){mediaReady=false;break;}}if(!mediaReady)continue;
  const mediaRefs=[...ja.mediaIds,...en.mediaIds].map(id=>state.catalog.media.find(m=>m.id===id));if(!mediaRefs.length||mediaRefs.some(m=>!m?.processed||m.internalOnly||!m.rightsConfirmed||m.rightsUntil!==null&&Date.parse(m.rightsUntil)<=Date.now()||!p.media.variants.some((v:{src:string})=>v.src.includes(m.immutableSha256))))continue;
  out.push({slug:p.slug,name:p.name,modelId:p.model_id,season:p.season,sport:p.family,lengths:variants.map(v=>v.size),variantIds:variants.map(v=>v.id),content:p.content,media:p.media});
 }return out;
}
export async function guestCatalog(pool:Pool,variants:Variant[]):Promise<GuestCatalog>{const models=await releasedModels(pool);return {revision:'public-p0-preview-v1',models:models.map(m=>({key:m.slug,name:m.name,modelId:m.modelId,season:m.season,sport:m.sport,lengths:m.lengths,variantIds:m.variantIds})),sizes:variants.filter(v=>['POLE','WEAR_JACKET','WEAR_PANTS'].includes(v.family)).map(v=>({key:v.family.toLowerCase()+'-'+v.id,label:v.size,variant:v}))};}

export async function guestVariants(catalog:GuestCatalog,variants:Variant[]){const allowed=new Set(catalog.models.flatMap(m=>m.variantIds));return variants.filter(v=>!(['SKI','SNOWBOARD'].includes(v.family)&&v.tier==='PREMIUM')||allowed.has(v.id));}
