'use client';
import {useState} from 'react';
import type {HoldConditions,HoldMember,EquipmentFamily} from '../../../../packages/contracts/src/hold';
import type {AmendmentService} from '../../../../packages/core/src/operations/amendment-service';
import type {FinancialOperations} from '../../../../packages/core/src/operations/financial';
import {StaffSessionBoundary} from './StaffSessionBoundary';
import {useOperationsRequest} from './useOperationsRequest';
import './holds.css';
import './operations.css';
type View=Awaited<ReturnType<AmendmentService['view']>>;type Quote=Awaited<ReturnType<AmendmentService['quote']>>;type Options=Awaited<ReturnType<AmendmentService['options']>>;type Money=Awaited<ReturnType<FinancialOperations['summary']>>;
export function AmendmentWorkspace(p:{stamp:string;stores:string[];canAmend:boolean;canRefund:boolean}){return <StaffSessionBoundary stamp={p.stamp}><Workspace {...p}/></StaffSessionBoundary>;}
function Workspace({stamp,stores,canAmend,canRefund}:{stamp:string;stores:string[];canAmend:boolean;canRefund:boolean}){
 const op=useOperationsRequest(stamp,'amendment'),[booking,setBooking]=useState(''),[view,setView]=useState<View|null>(null),[conditions,setConditions]=useState<HoldConditions|null>(null),[quote,setQuote]=useState<Quote|null>(null),[variants,setVariants]=useState<Options>([]),[reason,setReason]=useState(''),[fit,setFit]=useState(''),[financial,setFinancial]=useState<Money|null>(null),[store,setStore]=useState(stores[0]??''),[payment,setPayment]=useState(''),[amount,setAmount]=useState(''),[category,setCategory]=useState('CUSTOMER_EXCEPTION');
 function open(v:View){setView(v);setConditions(structuredClone(v.conditions));setQuote(null);}
 function member(index:number,update:(m:HoldMember)=>void){setConditions(c=>{const next=structuredClone(c!);update(next.members[index]!);return next;});setQuote(null);}
 const load=()=>void op.load<View>('/api/operations/amendment?id='+booking,open);
 return <main className="holds operations"><header><h1>予約変更・例外返金依頼</h1><nav><a href="/staff/rentals">貸出・返却</a> · <a href="/admin/assets">用品台帳</a></nav></header><p>元の予約・決済明細を保持します。早期返却だけでは返金しません。追加請求・返金のprovider送信は未接続です。</p><p role="status">{op.message}</p>
 {op.pending&&<button disabled={op.busy} onClick={()=>void op.send(op.pending!.path,null,()=>{setView(null);setFinancial(null);setQuote(null);},true)}>保存済みの同じ要求を照合</button>}
 <fieldset disabled={op.disabled}><legend>予約照合</legend><label>予約ID<input value={booking} maxLength={36} onChange={e=>{setBooking(e.target.value);setView(null);setFinancial(null);setQuote(null);}}/></label><button disabled={!canAmend} onClick={load}>変更対象を読み込む</button><button disabled={!canAmend} onClick={()=>void op.load<Options>('/api/operations/amendment-options',setVariants)}>商品候補を読み込む</button><label>操作店舗<select value={store} onChange={e=>{setStore(e.target.value);setFinancial(null);}}>{stores.map(s=><option key={s}>{s}</option>)}</select></label><button onClick={()=>void op.load<Money>('/api/operations/financial?id='+booking+'&store='+store,setFinancial)}>入金・返金残額を照合</button></fieldset>
 <label>操作理由（詳細な個人情報は記入しない）<input value={reason} maxLength={160} onChange={e=>setReason(e.target.value)}/></label>
 {view&&conditions&&<section><h2>変更内容</h2><p>元の支払対象額: {Number(view.originalPrice.totalJpy).toLocaleString()}円 · {view.conditions.pickupStore} → {view.conditions.returnStore}</p><fieldset disabled={op.disabled||!canAmend}><label>返却日<input type="date" value={conditions.period.endDate} min={conditions.period.startDate} onChange={e=>{setConditions({...conditions,period:{...conditions.period,endDate:e.target.value,slot:e.target.value===conditions.period.startDate?'DAY':'MULTIDAY'}});setQuote(null);}}/></label>
 {conditions.members.map((m,n)=><fieldset key={m.key}><legend>利用者 {m.key}</legend><label>商品<select value={m.product} onChange={e=>member(n,next=>{next.product=e.target.value as HoldMember['product'];const families:EquipmentFamily[]=next.product==='SKI_SET'?['SKI','SKI_BOOT','POLE']:next.product==='SNOWBOARD_SET'?['SNOWBOARD','SNOWBOARD_BOOT']:next.items.filter(i=>!i.family.startsWith('WEAR_')).map(i=>i.family);next.items=[...families.map(family=>next.items.find(i=>i.family===family)??{family,variantIds:[]}),...next.items.filter(i=>i.family.startsWith('WEAR_'))];})}>{['SKI_SET','SNOWBOARD_SET'].includes(m.product)?<><option value="SKI_SET">スキーセット</option><option value="SNOWBOARD_SET">ボードセット</option></>:<option value={m.product}>{m.product}</option>}</select></label>
 {m.items.map(item=><label key={item.family}>{item.family}<select value={item.variantIds.length===1?item.variantIds[0]:''} onChange={e=>member(n,next=>{const i=next.items.find(x=>x.family===item.family)!,v=variants.find(v=>v.id===e.target.value);i.variantIds=v?[v.id]:[];delete i.modelPromise;if(v&&conditions.contractVersion==='INTEGRATED_V1_2'&&next.tier==='PREMIUM'&&['SKI','SNOWBOARD'].includes(i.family)&&v.catalog_season)i.modelPromise={modelId:v.model_id,season:v.catalog_season,variantId:v.id};})}><option value="">現在の候補群を維持／交換先を選択</option>{variants.filter(v=>v.family===item.family&&v.age===m.age&&v.tier===(item.family.startsWith('WEAR_')?'STANDARD':m.tier)).map(v=><option key={v.id} value={v.id}>{v.name} · {v.size}</option>)}</select></label>)}</fieldset>)}
 <button disabled={!reason.trim()} onClick={()=>void op.send<Quote>('/api/operations/amendment-quote',{bookingId:view.bookingId,expectedHoldVersion:view.holdVersion,conditions,reason},setQuote)}>変更見積を固定</button></fieldset>
 {quote&&<section><h3>変更見積</h3><p>変更後 {quote.quote.target.totalJpy.toLocaleString()}円 / 差額 {quote.quote.differenceJpy.toLocaleString()}円 / 追加請求依頼 {quote.quote.additionalChargeJpy.toLocaleString()}円 / 自動返金 0円</p><p>有効期限: {quote.expiresAt}。適用時にも在庫・貸出状態を再確認します。</p><label>交換時のフィット・現品確認<input value={fit} maxLength={160} onChange={e=>setFit(e.target.value)}/></label><button disabled={op.disabled||!reason.trim()} onClick={()=>void op.send('/api/operations/amendment-accept',{quoteId:quote.id,fitEvidence:fit,reason},()=>{setQuote(null);setView(null);setFinancial(null);})}>この見積で変更を確定</button></section>}</section>}
 {financial&&<section><h2>入金と返金残額</h2><ul>{financial.payments.map(p=><li key={p.id}>入金 {p.collected_jpy}円 / 返金済 {p.refunded_jpy}円 / 処理中 {p.reserved_jpy}円 / 残額 {p.remainingJpy}円</li>)}</ul><ul>{financial.charges.map(c=><li key={c.id}>追加請求 {c.amountJpy}円 · {c.state}</li>)}{financial.refunds.map(r=><li key={r.id}>返金依頼 {r.amountJpy}円 · {r.state}</li>)}</ul>
 {financial.alerts.map((a,n)=><p role="alert" key={n}>要照合: {a.code}。新しい返金依頼を止めています。</p>)}<fieldset disabled={op.disabled||!canRefund||financial.alerts.length>0}><legend>明示権限による例外返金</legend><label>元の入金<select value={payment} onChange={e=>setPayment(e.target.value)}><option value="">選択</option>{financial.payments.map(p=><option key={p.id} value={p.id}>{p.id} · 残額 {p.remainingJpy}円</option>)}</select></label><label>理由区分<select value={category} onChange={e=>setCategory(e.target.value)}><option value="CUSTOMER_EXCEPTION">個別例外</option><option value="SERVICE_ISSUE">サービス上の事情</option><option value="DUPLICATE_COLLECTION">重複入金</option><option value="OTHER_APPROVED">その他の承認済み例外</option></select></label><label>返金依頼額（円）<input type="number" min="1" max="100000000" value={amount} onChange={e=>setAmount(e.target.value)}/></label><button disabled={!payment||!reason.trim()||!amount} onClick={()=>void op.send('/api/operations/refund',{bookingId:booking,paymentId:payment,actingStore:store,category,reason,amountJpy:Number(amount)},()=>setFinancial(null))}>例外返金を依頼する</button></fieldset></section>}
 </main>;
}
