 'use client';
import {useEffect,useRef,useState} from 'react';
import QRCode from 'qrcode';
import type {BookingService} from '../../../../packages/core/src/payment/booking-service';
import {StaffSessionBoundary,invalidateStaffView} from './StaffSessionBoundary';
import './holds.css';
type View=Awaited<ReturnType<BookingService['get']>>;
type Pending={path:string;body:unknown};
const storage='zao-flow-preview-pending-v1';
function recover(stamp:string):{pending:Pending|null;failed:boolean}{try{const raw=sessionStorage.getItem(storage);if(!raw)return {pending:null,failed:false};const p=JSON.parse(raw);if(p.stamp!==stamp){sessionStorage.removeItem(storage);return {pending:null,failed:false};}if(typeof p.path!=='string'||!/^$|^\/[a-f0-9-]{36}\/(payment|reconcile)$/.test(p.path)||!p.body)throw new Error();return {pending:{path:p.path,body:p.body},failed:false};}catch{return {pending:null,failed:true};}}
function Qr({value}:{value:string}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{let live=true;if(ref.current)void QRCode.toCanvas(ref.current,value,{width:220,margin:4,errorCorrectionLevel:'M'}).catch(()=>{if(live&&ref.current)ref.current.width=0;});return()=>{live=false;};},[value]);return <figure><canvas ref={ref} aria-label="開発予約QR"/><figcaption>開発予約の照合用QR。スタッフ認証と操作権限が必要です。</figcaption></figure>;}
export function BookingWorkspace(p:{stamp:string;quoteId:string|null;canCreate:boolean}){return <StaffSessionBoundary stamp={p.stamp}><Workspace {...p}/></StaffSessionBoundary>;}
function Workspace({stamp,quoteId,canCreate}:{stamp:string;quoteId:string|null;canCreate:boolean}){
 const [initial]=useState(()=>recover(stamp));
 const [quote,setQuote]=useState(quoteId??''),[name,setName]=useState(''),[email,setEmail]=useState(''),[accept,setAccept]=useState(false),[view,setView]=useState<View|null>(null),[list,setList]=useState<{id:string;state:string;display_name:string;period:{startDate:string}}[]>([]),[mode,setMode]=useState('CHECKING'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[pending,setPending]=useState<Pending|null>(initial.pending),[storageFailed,setStorageFailed]=useState(initial.failed);
 const alive=useRef(true),serial=useRef(0);useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 async function call(path:string,body?:unknown){const r=await fetch('/api/bookings'+path,{method:body===undefined?'GET':'POST',cache:'no-store',headers:{'content-type':'application/json','x-zao-session':stamp},...(body===undefined?{}:{body:JSON.stringify(body)})});const data=await r.json();if([401,403].includes(r.status)||data.error==='SESSION_CHANGED'){invalidateStaffView();throw new Error('SESSION_CHANGED');}if(!r.ok)throw Object.assign(new Error(data.error),{definite:r.status<500});return data;}
 useEffect(()=>{let active=true;void call('/capabilities').then(async c=>{if(!active)return;setMode(c.mode);if(c.simulated||c.mode==='LOCAL_OPERATIONS'){const rows=await call('');if(active)setList(rows);}}).catch(()=>{if(active)setMessage('利用状態を確認できませんでした。');});return()=>{active=false;};},[stamp]); // eslint-disable-line react-hooks/exhaustive-deps
 async function open(id:string){const n=++serial.current;setBusy(true);try{const v=await call('/'+id);if(alive.current&&n===serial.current)setView(v);}catch{if(alive.current&&n===serial.current)setMessage('読込できませんでした。');}finally{if(alive.current&&n===serial.current)setBusy(false);}}
 async function send(p:Pending){try{sessionStorage.setItem(storage,JSON.stringify({stamp,...p}));}catch{setStorageFailed(true);return;}setPending(p);setBusy(true);const n=++serial.current;try{const v:View=await call(p.path,p.body);if(!alive.current||n!==serial.current)return;setView(v);sessionStorage.removeItem(storage);setPending(null);setMessage(v.state==='CONFIRMED_DEV'?'開発用の照合が完了しました。実予約・実決済ではありません。':'状態を保存しました。');const rows=await call('');if(alive.current&&n===serial.current)setList(rows);}catch(e){if(alive.current&&n===serial.current){if((e as {definite?:boolean}).definite){sessionStorage.removeItem(storage);setPending(null);}setMessage((e as {definite?:boolean}).definite?'拒否：'+(e as Error).message:'応答未確認です。同じ保存済み要求を照合してください。');}}finally{if(alive.current&&n===serial.current)setBusy(false);}}
 const disabled=busy||Boolean(pending)||storageFailed||mode!=='ISOLATED_TEST'||!canCreate;
 return <main className="holds"><header><p>ZAO Rental · 非公開の開発プレビュー</p><h1>予約情報と決済照合</h1><nav><a href="/staff/recommendations">推薦・HOLD・見積</a> · <a href="/staff/ledger">台帳</a> · <a href="/staff/logout">ログアウト</a></nav></header><p>合成データ専用です。税区分は未確認、請求確定はできません。実Square・メール送信には接続していません。</p>
 {mode==='UNCONNECTED'&&<p role="status">通常アプリの決済は未接続です。模擬決済は隔離したテスト構成だけで利用できます。</p>}
 <fieldset disabled={disabled}><legend>合成予約情報</legend><label>保存済み見積ID<input value={quote} onChange={e=>setQuote(e.target.value)} maxLength={36}/></label><label>合成氏名<input value={name} onChange={e=>setName(e.target.value)} placeholder="SYNTHETIC Guest" maxLength={70}/></label><label>架空メール宛先<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="synthetic-guest@example.invalid" maxLength={100}/></label><label><input type="checkbox" checked={accept} onChange={e=>setAccept(e.target.checked)}/>開発用の合成予約であり、営業規約・請求の確定ではないことを確認</label><button disabled={!accept} onClick={()=>void send({path:'',body:{requestKey:crypto.randomUUID(),quoteId:quote,contact:{displayName:name,email,termsAccepted:accept}}})}>合成予約情報を保存</button></fieldset>
 {view&&<section aria-label="開発予約詳細"><h2>{view.contact.displayName}</h2><p>開発予約ID {view.id}</p><p>状態 <strong>{view.state}</strong></p><p>{view.conditions.period.startDate}〜{view.conditions.period.endDate} / {view.conditions.period.slot} / {view.conditions.pickupStore} → {view.conditions.returnStore}</p><p>見積合計 {Number(view.priceSnapshot.totalJpy).toLocaleString()} 円 · 保存した料金版 {String(view.priceSnapshot.priceBookId)}</p><p>見積期限 {String(view.priceSnapshot.expiresAt)} / 早割は検証された決済完了時刻で照合</p><p>価格snapshot {view.priceSha256}</p>{view.payments.map(p=><p key={p.id}>模擬決済 {p.state} / {p.provider_state??'結果不明'}</p>)}
 {view.state==='DRAFT'&&<button disabled={disabled} onClick={()=>void send({path:'/'+view.id+'/payment',body:{requestKey:crypto.randomUUID()}})}>テストアダプタへ照合要求</button>}{view.payments.length>0&&!['CONFIRMED_DEV','COMPLETED_DEV','CONFIRMED','COMPLETED','CANCELLED'].includes(view.state)&&<button disabled={disabled} onClick={()=>void send({path:'/'+view.id+'/reconcile',body:{}})}>既存の決済結果を照合</button>}<button disabled={busy||Boolean(pending)} onClick={()=>void open(view.id)}>予約結果を再読込</button>{view.qr&&<Qr value={view.qr}/>}<p>{mode==='ISOLATED_TEST'?<a href="/staff/rental">権限を確認して道具の受付・貸出・返却へ</a>:'通常アプリの貸出返却は未接続です。'}</p></section>}
 {pending&&!busy&&<button disabled={storageFailed} onClick={()=>void send(pending)}>同じ保存済み要求を照合</button>}<p role="status">{storageFailed?'要求の保存領域を確認できないため更新停止。':message}</p><section><h2>保存済み開発予約</h2>{list.map(b=><button key={b.id} disabled={busy||Boolean(pending)} onClick={()=>void open(b.id)}>{b.display_name} · {b.period.startDate} · {b.state}</button>)}</section></main>;
}
