'use client';
import {useEffect,useRef,useState} from 'react';
import {StaffSessionBoundary,invalidateStaffView} from './StaffSessionBoundary';
import {AssetQrInput} from './AssetQrInput';
import type {StoreId} from '../../../../packages/contracts/src/ledger';
import './holds.css';
type Item={requirement_key:string;asset_id:string|null;pole_id:string|null;family:string;size:string;name:string;bsl_status:string|null};
type Loan={id:string;family:string;requirement_key:string;state:string;version:number;asset_id:string|null;pole_id:string|null};
type View={bookingId:string;bookingVersion:number;holdVersion:number;items:Item[];preparation:{version:number}|null;loans:Loan[]};
type Batch={id:string;store_id:string;version:number;candidates:{id:string;state:string;outcome:string;family:string|null;booking_id:string|null;requirement_key:string|null;loan_item_id:string|null}[]};
type Work={batches:{id:string}[];received:{loan_item_id:string;family:string;requirement_key:string;version:number;inspection_id:string|null}[]};
type Pending={path:string;body:{requestKey:string;input:unknown}};
const storage='zao-custody-pending-v1';
function recover(stamp:string){try{const data=JSON.parse(sessionStorage.getItem(storage)??'null');if(data?.stamp===stamp&&data.pending)return {pending:data.pending as Pending,blocked:false};sessionStorage.removeItem(storage);return {pending:null,blocked:false};}catch{return {pending:null,blocked:true};}}
export function CustodyWorkspace(p:{stamp:string;stores:StoreId[];canCheckout:boolean;canReturn:boolean}){return <StaffSessionBoundary stamp={p.stamp}><Workspace {...p}/></StaffSessionBoundary>;}
function Workspace({stamp,stores,canCheckout,canReturn}:{stamp:string;stores:StoreId[];canCheckout:boolean;canReturn:boolean}){
 const [initial]=useState(()=>recover(stamp)),[pending,setPending]=useState<Pending|null>(initial.pending),[blocked,setBlocked]=useState(initial.blocked),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[booking,setBooking]=useState(''),[view,setView]=useState<View|null>(null),[fit,setFit]=useState(''),[verified,setVerified]=useState(false),[store,setStore]=useState(stores[0]!),[batch,setBatch]=useState<Batch|null>(null),[batchId,setBatchId]=useState(''),[work,setWork]=useState<Work|null>(null),[poleLoan,setPoleLoan]=useState(''),[inspection,setInspection]=useState('');
 const alive=useRef(true),generation=useRef(0),busyRef=useRef(false);useEffect(()=>{alive.current=true;const tickets=generation;return()=>{alive.current=false;tickets.current++;};},[]);
 async function call(path:string,body?:unknown){const r=await fetch('/api/custody'+path,{method:body===undefined?'GET':'POST',cache:'no-store',headers:{'content-type':'application/json','x-zao-session':stamp},...(body===undefined?{}:{body:JSON.stringify(body)})});const data=await r.json();if([401,403].includes(r.status)||data.error==='SESSION_CHANGED'){invalidateStaffView();throw Object.assign(new Error('SESSION_CHANGED'),{definite:true});}if(!r.ok)throw Object.assign(new Error(data.error),{definite:r.status<500});return data;}
 function openBatch(data:Batch){setBatch(data);setBatchId(data.id);setStore(data.store_id as StoreId);setWork(null);}
 async function load(path:string,apply:(data:never)=>void){if(busyRef.current||pending)return;const g=++generation.current;busyRef.current=true;setBusy(true);try{const data=await call(path);if(alive.current&&g===generation.current)apply(data as never);}catch(e){if(alive.current&&g===generation.current)setMessage((e as Error).message);}finally{busyRef.current=false;if(alive.current)setBusy(false);}}
 async function send(p:Pending){if(busyRef.current)throw new Error('REQUEST_IN_FLIGHT');try{sessionStorage.setItem(storage,JSON.stringify({stamp,pending:p}));}catch{setBlocked(true);throw new Error('STORAGE_NOT_CONFIRMED');}setPending(p);setBusy(true);busyRef.current=true;const g=++generation.current;
  try{const data=await call(p.path,p.body);if(!alive.current||g!==generation.current)return;
   if(['/prepare','/checkout'].includes(p.path))setView(data);else if(['/batch','/scan','/confirm'].includes(p.path)){openBatch(data);}sessionStorage.removeItem(storage);setPending(null);setMessage(p.path==='/scan'?'返却候補をサーバーに保存しました。受領は未確定です。':p.path==='/confirm'?'正常な明細を受領しました。要確認の明細と検品待ちは残っています。':'処理結果を保存しました。');
   if(canReturn){const w=await call('/returns?store='+(data.store_id??store));if(alive.current&&g===generation.current)setWork(w);}
  }catch(e){if(alive.current&&g===generation.current){if((e as {definite?:boolean}).definite){sessionStorage.removeItem(storage);setPending(null);}setMessage((e as {definite?:boolean}).definite?'拒否：'+(e as Error).message:'応答未確認です。同じ保存済み要求を照合してください。');}throw e;
  }finally{busyRef.current=false;if(alive.current&&g===generation.current)setBusy(false);}
 }
 const mutate=(path:string,input:unknown)=>send({path,body:{requestKey:crypto.randomUUID(),input}});
 const disabled=busy||!!pending||blocked;
 return <main className="holds"><header><p>ZAO Rental · 合成データ専用</p><h1>道具の受付・貸出・返却</h1><nav><a href="/preview/rental">開発予約</a> · <a href="/staff/wear">ウェアの数量貸出・返却</a> · <a href="/staff/logout">ログアウト</a></nav></header><p>実予約・実決済ではありません。返却受領、検品、同日再貸出の制限は別です。早期返却で自動返金はしません。</p>
 {canCheckout&&<fieldset disabled={disabled}><legend>予約を照合して道具を貸出</legend><label>開発予約IDまたは予約QR<input value={booking} onChange={e=>setBooking(e.target.value)} maxLength={80}/></label><button onClick={()=>{try{const id=booking.startsWith('zao-rental:reservation:')?booking.slice('zao-rental:reservation:'.length):booking;void load('/booking/'+id,setView);}catch{setMessage('予約IDを確認してください。');}}}>予約と仮割当を照合</button>
 {view&&<section aria-label="貸出用品"><p>予約 {view.bookingId}</p><p>ウェアは別の数量画面で同じ予約IDを指定します。用品IDをウェアへ発行しません。</p>{view.items.map(i=><article key={i.requirement_key}><strong>{i.requirement_key} · {i.name} · {i.size}</strong><p>{i.asset_id?'個体ID '+i.asset_id:'ポール数量プール '+i.pole_id+' / 1ペア'}</p>{i.bsl_status==='UNVERIFIED'&&<p>BSL未確認。自動推測・DIN確定は行っていません。</p>}</article>)}
 {!view.preparation&&<><label>準備・最終適合の作業記録<input value={fit} onChange={e=>setFit(e.target.value)} maxLength={160}/></label><label><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/>表示された個体と数量を照合した（合成検証）</label><button disabled={!verified||!fit.trim()} onClick={()=>void mutate('/prepare',{bookingId:view.bookingId,expectedBookingVersion:view.bookingVersion,expectedHoldVersion:view.holdVersion,selections:view.items.map(i=>({requirementKey:i.requirement_key,assetId:i.asset_id,poleId:i.pole_id})),fitEvidence:fit}).catch(()=>{})}>照合した用品を準備固定</button></>}
 {view.preparation&&!view.loans.length&&<button onClick={()=>void mutate('/checkout',{bookingId:view.bookingId,expectedPreparationVersion:view.preparation!.version}).catch(()=>{})}>道具の貸出を記録</button>}
 {view.loans.map(l=><p key={l.id}>{l.requirement_key} · {l.state} · 貸出明細 {l.id}</p>)}<button onClick={()=>void load('/booking/'+view.bookingId,setView)}>貸出結果を再読込</button></section>}
 </fieldset>}
 {canReturn&&<><fieldset disabled={disabled}><legend>実際の返却受領店舗</legend><label>受領店舗<select aria-label="受領店舗" value={store} onChange={e=>{generation.current++;setStore(e.target.value as StoreId);setBatch(null);setWork(null);setBatchId('');}}>{stores.map(s=><option value={s} key={s}>{s}</option>)}</select></label><button onClick={()=>void mutate('/batch',{store}).catch(()=>{})}>この店舗で返却バッチを開始</button><button onClick={()=>void load('/returns?store='+store,setWork)}>保存済み返却作業を読込</button><label>保存済み返却バッチID<input value={batchId} onChange={e=>setBatchId(e.target.value)} maxLength={36}/></label><button onClick={()=>void load('/batch/'+batchId,openBatch)}>返却バッチを再開</button>{work?.batches.map(b=><button key={b.id} onClick={()=>void load('/batch/'+b.id,openBatch)}>バッチを開く {b.id}</button>)}</fieldset>
 {batch&&<section aria-label="連続返却バッチ"><h2>返却候補と受領結果</h2><p>{batch.store_id} / {batch.id}</p><AssetQrInput disabled={blocked||!!pending&&!busy} onAsset={id=>mutate('/scan',{batchId:batch.id,expectedVersion:batch.version,assetId:id,poleLoanId:null})}/>
 <fieldset disabled={disabled}><legend>ポールは貸出明細に対応するペア数量</legend><label>ポールの貸出明細ID<input value={poleLoan} onChange={e=>setPoleLoan(e.target.value)} maxLength={36}/></label><button disabled={!poleLoan} onClick={()=>void mutate('/scan',{batchId:batch.id,expectedVersion:batch.version,assetId:null,poleLoanId:poleLoan}).catch(()=>{})}>この貸出のポール1ペアを候補に追加</button></fieldset><p>帰属不明の混在数量を、特定予約の返却完了へ自動で割り当てません。</p>
 {batch.candidates.map(c=><article key={c.id}><strong>{c.requirement_key??'照合要確認'} / {c.state}</strong><p>{c.outcome} / 予約 {c.booking_id??'未照合'} / 貸出明細 {c.loan_item_id??'未照合'}</p></article>)}<button disabled={disabled||!batch.candidates.some(c=>c.state==='CANDIDATE')} onClick={()=>void mutate('/confirm',{batchId:batch.id,expectedVersion:batch.version}).catch(()=>{})}>正常な候補をまとめて受領確定</button></section>}
 <fieldset disabled={disabled}><legend>受領後の検品</legend><label>実際に行った検品記録<input value={inspection} onChange={e=>setInspection(e.target.value)} maxLength={160}/></label>{work?.received.map(r=><article key={r.loan_item_id}><p>{r.requirement_key} / {r.inspection_id?'検品済み（契約日・当日ブロックは維持）':'受領済み・検品待ち'}</p>{!r.inspection_id&&<button disabled={!inspection.trim()} onClick={()=>void mutate('/inspection',{loanItemId:r.loan_item_id,expectedVersion:r.version,store,evidence:inspection}).catch(()=>{})}>検品完了 {r.loan_item_id}</button>}</article>)}</fieldset></>}
 {pending&&!busy&&<button disabled={blocked} onClick={()=>void send(pending).catch(()=>{})}>同じ保存済み要求を照合</button>}<p role="status">{blocked?'保存領域未確認のため操作停止':message}</p></main>;
}
