 'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {SaveBookingAccess} from './BookingAccess';
import {GuestAvatarPreview} from './GuestAvatarPreview';
import type {Direction} from '../../../../packages/contracts/src/recommendation';
import type {Locale} from '../../../../packages/core/src/content/public-pages';
import './public.css';
import './guest.css';
type Member={key:string;sport:string;heightCm:number|null;footCm:number|null;adultAtStart:boolean;tier:string;ski:{weightKg:number;ageAtStart:number;level:string}|null;poleSize:string|null;premiumModel:string|null;jacketSize:string|null;pantsSize:string|null;wearSport:string|null};
type Input={pickupStore:string;returnStore:string;period:{startDate:string;endDate:string;slot:string};members:Member[]};
type Options={models:{key:string;name:string;season:string;sport:string;lengths:string[]}[];sizes:{key:string;label:string;family:string;age:string;tier:string}[]};
type Contact={displayName:string;email:string;termsAccepted:boolean};
type Draft={id:string;revision:number;input:Input|null;locked:boolean;priceReviewRequired:boolean;selection:{directions:Record<string,string>;wantAdvance:boolean;contact?:Contact}|null;preview:{members:{key:string;reason:string|null;price:Record<string,unknown>|null;priceError:string|null;candidates:Record<string,{lengthCm:number}|null>}[]}|null;hold:{state:string;expiresAt:string}|null;estimate:{subtotalJpy:number;bundleDiscountJpy?:number;advanceDiscountJpy:number;totalJpy:number}|null;reviewHash:string|null;quote:{snapshot:{totalJpy:number};snapshotSha256:string;validity:string}|null;booking:{id:string;state:string;qr:string|null;qrImage:string|null;payments:{state:string}[];priceSnapshot:{totalJpy:number}}|null;simulation?:boolean};
let starting:Promise<unknown>|null=null;
async function request(path:string,body?:unknown){const r=await fetch('/api/guest'+path,{cache:'no-store',method:body===undefined?'GET':'POST',headers:{'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});const data=await r.json();if(!r.ok)throw Object.assign(new Error(data.error),{status:r.status});return data;}
function blank(n:number):Member{return {key:'person-'+n,sport:'SKI',heightCm:170,footCm:25.5,adultAtStart:true,tier:'REGULAR',ski:{weightKg:60,ageAtStart:30,level:'BEGINNER'},poleSize:null,premiumModel:null,jacketSize:null,pantsSize:null,wearSport:null};}
export function GuestBooking({locale}:{locale:Locale}){const ja=locale==='ja',t=(j:string,e:string)=>ja?j:e;
 const [draft,setDraft]=useState<Draft|null>(null),[options,setOptions]=useState<Options>({models:[],sizes:[]}),[input,setInput]=useState<Input>({pickupStore:'MOUNTAIN_BASE',returnStore:'MOUNTAIN_BASE',period:{startDate:'',endDate:'',slot:'DAY'},members:[blank(1)]}),[step,setStep]=useState(0),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[directions,setDirections]=useState<Record<string,string>>({}),[accepted,setAccepted]=useState(false),[advance,setAdvance]=useState(false),[contact,setContact]=useState<Contact>({displayName:'SYNTHETIC Guest',email:'synthetic-guest@example.invalid',termsAccepted:false}),[simulation,setSimulation]=useState(false);
 const alive=useRef(true),ticket=useRef(0),inFlight=useRef(false);
 const open=useCallback((d:Draft)=>{setDraft(d);if(d.input)setInput(d.input);if(d.selection){setDirections(d.selection.directions);setAdvance(d.selection.wantAdvance);if(d.selection.contact)setContact(d.selection.contact);}if(d.selection||d.booking||d.hold)setStep(3);else if(d.preview)setStep(2);if(d.simulation!==undefined)setSimulation(d.simulation);},[]);
 useEffect(()=>{alive.current=true;const n=++ticket.current;if(!starting)starting=request('/context',{}).finally(()=>{starting=null;});starting.then(async()=>{const [d,o]=await Promise.all([request('/draft'),request('/options')]);if(alive.current&&n===ticket.current){open(d);setOptions(o);}}).catch(e=>{if(alive.current&&n===ticket.current)setMessage(e.message);});return()=>{alive.current=false;};},[open]);
 async function run(fn:()=>Promise<Draft>){if(inFlight.current)return;inFlight.current=true;setBusy(true);const n=++ticket.current;try{const d=await fn();if(alive.current&&n===ticket.current){open(d);setMessage('');}}catch(e){if(alive.current&&n===ticket.current){if((e as {status?:number}).status===401){setDraft(null);setInput({pickupStore:'MOUNTAIN_BASE',returnStore:'MOUNTAIN_BASE',period:{startDate:'',endDate:'',slot:'DAY'},members:[blank(1)]});setDirections({});}setMessage((e as Error).message);}}finally{inFlight.current=false;if(alive.current)setBusy(false);}}
 function member(n:number,patch:Partial<Member>){setInput(i=>({...i,members:i.members.map((m,j)=>j===n?{...m,...patch}:m)}));}
 function sport(n:number,s:string){member(n,{sport:s,tier:s==='WEAR'?'STANDARD':'REGULAR',ski:s==='SKI'?{weightKg:60,ageAtStart:30,level:'BEGINNER'}:null,heightCm:s==='WEAR'?null:170,footCm:s==='WEAR'?null:25.5,poleSize:null,premiumModel:null,jacketSize:null,pantsSize:null,wearSport:s==='WEAR'?'SKI':null});}
 const sizes=(m:Member,f:string)=>options.sizes.filter(v=>v.family===f&&v.age===(m.adultAtStart?'ADULT':'KIDS')&&v.tier===(f.startsWith('WEAR_')?'STANDARD':m.tier));
 const money=(n:unknown)=>typeof n==='number'?new Intl.NumberFormat(locale==='ja'?'ja-JP':'en-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(n):'—';
 return <div className="public-shell" lang={locale}><header className="public-header"><Link className="wordmark" href={'/'+locale}>ZAO<span>RENTAL</span></Link><Link href={'/'+locale+'/rental'}>{t('プランを見る','View plans')}</Link></header><main className="guest-main"><p className="public-kicker">YOUR SNOW DAY</p><h1>{t('みんなのレンタルを選ぶ','Plan the group’s rental')}</h1><p>{t('開発プレビューです。架空の情報だけを使用してください。実決済・本番予約は行いません。','Development preview: use synthetic details only. No real payment or production booking.')}</p><ol className="guest-steps" aria-label={t('予約の流れ','Booking steps')}>{[t('日程','Dates'),t('用品とサイズ','Equipment'),t('候補を選ぶ','Choose sizes'),t('全員分を確認','Review group')].map((s,n)=><li key={s} aria-current={step===n?'step':undefined}>{n+1}. {s}</li>)}</ol>
 {!draft&&<p role="status">{message||t('予約用の画面を開いています…','Opening your booking workspace…')}</p>}
 {draft&&<><fieldset disabled={busy||draft.locked}><legend>{step===0?t('日程・店舗','Dates & stores'):step===1?t('一人ずつ選択','Choose for each person'):t('保存済みの条件','Saved conditions')}</legend>
 {step===0&&<><div className="guest-grid"><label>{t('利用開始日','Start date')}<input type="date" value={input.period.startDate} onChange={e=>setInput(i=>({...i,period:{...i.period,startDate:e.target.value,endDate:i.period.endDate||e.target.value}}))}/></label><label>{t('利用終了日','End date')}<input type="date" value={input.period.endDate} onChange={e=>setInput(i=>({...i,period:{...i.period,endDate:e.target.value}}))}/></label><label>{t('利用枠','Rental slot')}<select aria-label={t('利用枠','Rental slot')} value={input.period.slot} onChange={e=>setInput(i=>({...i,period:{...i.period,slot:e.target.value}}))}>{[['DAY','1日 / Day'],['AM','午前 / Morning'],['PM','午後 / Afternoon'],['MULTIDAY','2日以上 / Multi-day']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{(['pickupStore','returnStore'] as const).map(f=><label key={f}>{f==='pickupStore'?t('受取店舗','Pickup store'):t('返却店舗','Return store')}<select aria-label={f==='pickupStore'?t('受取店舗','Pickup store'):t('返却店舗','Return store')} value={input[f]} onChange={e=>setInput(i=>({...i,[f]:e.target.value}))}><option value="MOUNTAIN_BASE">Mountain Base</option><option value="ONSEN_BASE">Onsen Base</option></select></label>)}</div><button disabled={!input.period.startDate||!input.period.endDate} onClick={()=>setStep(1)}>{t('用品を選ぶ','Choose equipment')}</button></>}
 {step===1&&<><div className="guest-compare"><article><h2>Regular</h2><p>{t('サイズ・年齢区分・クラスを選びます。モデルは確約しません。','Choose size, age category and class. No specific model promise.')}</p></article><article><h2>Premium</h2><p>{t('モデル・シーズン・長さを選択条件として保存します。','Your selected model, season and length become the promise.')}</p></article></div><label>{t('利用人数','Group size')}<input type="number" min={1} max={20} value={input.members.length} onChange={e=>{const n=Number(e.target.value);if(Number.isInteger(n)&&n>0&&n<=20)setInput(i=>({...i,members:Array.from({length:n},(_,j)=>i.members[j]??blank(j+1))}));}}/></label>
 {input.members.map((m,n)=><article className="guest-person" key={m.key}><h2>{t('利用者','Person')} {n+1}</h2><div className="guest-grid"><label>{t('用品','Equipment')} {n+1}<select aria-label={t('用品','Equipment')+' '+(n+1)} value={m.sport} onChange={e=>sport(n,e.target.value)}><option value="SKI">{t('スキーセット','Ski set')}</option><option value="SNOWBOARD">{t('スノーボードセット','Snowboard set')}</option><option value="WEAR">{t('ウェアのみ','Wear only')}</option></select></label><label>{t('年齢区分','Age category')} {n+1}<select aria-label={t('年齢区分','Age category')+' '+(n+1)} value={m.adultAtStart?'ADULT':'KIDS'} onChange={e=>member(n,{adultAtStart:e.target.value==='ADULT',tier:m.sport==='WEAR'?'STANDARD':'REGULAR',poleSize:null,premiumModel:null,jacketSize:null,pantsSize:null,...(m.ski?{ski:{...m.ski,ageAtStart:e.target.value==='ADULT'?30:10}}:{})})}><option value="ADULT">{t('大人','Adult')}</option><option value="KIDS">{t('子供','Child')}</option></select></label>
 {m.sport!=='WEAR'&&<><label>{t('プラン','Plan')} {n+1}<select aria-label={t('プラン','Plan')+' '+(n+1)} value={m.tier} onChange={e=>member(n,{tier:e.target.value,premiumModel:null,poleSize:null})}><option value="REGULAR">Regular</option>{m.adultAtStart&&<option value="PREMIUM">Premium</option>}</select></label><label>{t('身長cm','Height cm')} {n+1}<input type="number" value={m.heightCm??''} onChange={e=>member(n,{heightCm:Number(e.target.value)})}/></label><label>{t('足サイズcm','Foot size cm')} {n+1}<input type="number" step="0.5" value={m.footCm??''} onChange={e=>member(n,{footCm:Number(e.target.value)})}/></label></>}
 {m.ski&&<><label>{t('体重kg','Weight kg')} {n+1}<input type="number" value={m.ski.weightKg} onChange={e=>member(n,{ski:{...m.ski!,weightKg:Number(e.target.value)}})}/></label><label>{t('開始日の年齢','Age at start')} {n+1}<input type="number" value={m.ski.ageAtStart} onChange={e=>member(n,{ski:{...m.ski!,ageAtStart:Number(e.target.value)}})}/></label><label>{t('スキーレベル','Ski level')} {n+1}<select aria-label={t('スキーレベル','Ski level')+' '+(n+1)} value={m.ski.level} onChange={e=>member(n,{ski:{...m.ski!,level:e.target.value}})}><option value="BEGINNER">{t('初級','Beginner')}</option><option value="INTERMEDIATE">{t('中級','Intermediate')}</option><option value="ADVANCED">{t('上級','Advanced')}</option></select></label><label>{t('ポールのサイズ','Pole size')} {n+1}<select aria-label={t('ポールのサイズ','Pole size')+' '+(n+1)} value={m.poleSize??''} onChange={e=>member(n,{poleSize:e.target.value||null})}><option value="">{t('選択してください','Choose a size')}</option>{sizes(m,'POLE').map(v=><option key={v.key} value={v.key}>{v.label}</option>)}</select></label></>}
 {m.tier==='PREMIUM'&&<label>{t('モデルとシーズン','Model and season')} {n+1}<select aria-label={t('モデルとシーズン','Model and season')+' '+(n+1)} value={m.premiumModel??''} onChange={e=>member(n,{premiumModel:e.target.value||null})}><option value="">{t('確認済みモデルから選択','Choose a verified model')}</option>{options.models.filter(p=>p.sport===m.sport).map(p=><option value={p.key} key={p.key}>{p.name} · {p.season} · {p.lengths.join(', ')}</option>)}</select>{!options.models.some(p=>p.sport===m.sport)&&<small>{t('公開確認済みモデルはまだありません。','No models are approved for this preview yet.')}</small>}</label>}
 {m.sport==='WEAR'&&<label>{t('ウェアの用途','Wear sport')} {n+1}<select aria-label={t('ウェアの用途','Wear sport')+' '+(n+1)} value={m.wearSport??'SKI'} onChange={e=>member(n,{wearSport:e.target.value})}><option value="SKI">Ski</option><option value="SNOWBOARD">Snowboard</option></select></label>}
 {(['jacketSize','pantsSize'] as const).map((f,i)=><label key={f}>{i===0?t('ジャケットサイズ','Jacket size'):t('パンツサイズ','Pants size')} {n+1}<select aria-label={(i===0?t('ジャケットサイズ','Jacket size'):t('パンツサイズ','Pants size'))+' '+(n+1)} value={m[f]??''} onChange={e=>member(n,{[f]:e.target.value||null})}><option value="">{t('選択なし','Not selected')}</option>{sizes(m,i===0?'WEAR_JACKET':'WEAR_PANTS').map(v=><option value={v.key} key={v.key}>{v.label}</option>)}</select></label>)}</div></article>)}
 <p>{t('候補確認ではまだ在庫を確保しません。','Reviewing candidates does not hold stock yet.')}</p><button onClick={()=>setStep(0)}>{t('日程に戻る','Back to dates')}</button><button onClick={()=>void run(async()=>{const saved=await request('/draft',{draftId:draft.id,expectedRevision:draft.revision,input});return request('/preview',{draftId:saved.id,expectedRevision:saved.revision});})}>{t('候補と参考料金を確認','Review sizes and estimates')}</button></>}
 {step===2&&draft.preview&&<><p>{t('候補は目安です。長さを明示的に選択してください。','Suggestions are a guide. Choose a length explicitly.')}</p>{draft.preview.members.map((m,n)=><article className="guest-person" key={m.key}><h2>{t('利用者','Person')} {n+1}</h2><p>{t('参考料金','Estimate')}: {money(m.price?.totalJpy)}</p>{Object.entries(m.candidates).map(([d,c])=>c&&<label className="guest-choice" key={d}><input type="radio" name={m.key} checked={directions[m.key]===d} onChange={()=>setDirections(x=>({...x,[m.key]:d}))}/>{t(d==='RECOMMENDED'?'おすすめ':d==='SHORTER'?'短め':'長め',d)} {c.lengthCm||t('上下サイズ確認','Wear sizes confirmed')}{c.lengthCm?' cm':''}</label>)}{m.reason&&<p>{m.reason}</p>}<GuestAvatarPreview key={draft.id+':'+draft.revision+':'+m.key} scope={{draftId:draft.id,revision:draft.revision,memberKey:m.key}} direction={(directions[m.key]??'RECOMMENDED') as Direction} locale={locale}/></article>)}<label className="guest-choice"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/>{t('全員のサイズ・モデル条件・ウェア構成を確認した','I confirm each person’s size, model promise and wear selections')}</label><label className="guest-choice"><input type="checkbox" checked={advance} onChange={e=>setAdvance(e.target.checked)}/>{t('事前決済5％調整の見込みを確認する','Evaluate potential 5% advance-payment eligibility')}</label><button disabled={!accepted||draft.preview.members.some(m=>!directions[m.key])} onClick={()=>void run(()=>request('/selection',{draftId:draft.id,expectedRevision:draft.revision,directions,wantAdvance:advance,couponCode:null,acceptedModelPolicy:true}))}>{t('全員分の最終確認へ','Review the whole group')}</button></>}
 </fieldset>
 {step===3&&<section className="guest-review" aria-label={t('全員分の確認','Group review')}><h2>{t('最終確認','Final review')}</h2>{!draft.locked&&<button disabled={busy} onClick={()=>setStep(1)}>{t('条件を編集して再計算','Edit and recalculate')}</button>}<p>{input.period.startDate} → {input.period.endDate} · {input.period.slot}</p><p>{input.pickupStore} → {input.returnStore}</p>{input.members.map((m,n)=><article key={m.key}><h3>{t('利用者','Person')} {n+1} · {m.sport} · {m.tier}</h3><p>{draft.preview?.members[n]?.candidates[directions[m.key]??'']?.lengthCm||'—'} cm · {options.models.find(p=>p.key===m.premiumModel)?.name??t('モデル非指定','No specific model')} · {options.sizes.find(v=>v.key===m.jacketSize)?.label??'—'} / {options.sizes.find(v=>v.key===m.pantsSize)?.label??'—'}</p></article>)}<p>{t('税区分・営業規約は公開前確認中。見積は請求確定ではありません。','Tax display and public terms remain under review. Estimates are not final charges.')}</p>
 {draft.estimate&&<dl><dt>{t('小計','Subtotal')}</dt><dd>{money(draft.estimate.subtotalJpy)}</dd><dt>{t('ウェア調整','Wear adjustment')}</dt><dd>{money(draft.estimate.bundleDiscountJpy??0)}</dd><dt>{t('事前決済調整（見込み）','Estimated advance adjustment')}</dt><dd>{money(draft.estimate.advanceDiscountJpy)}</dd><dt>{t('全員分の参考総額','Group estimate')}</dt><dd><strong>{money(draft.estimate.totalJpy)}</strong></dd></dl>}
 <label>{t('お名前（架空）','Name (synthetic)')}<input value={contact.displayName} disabled={busy||draft.locked} onChange={e=>setContact(c=>({...c,displayName:e.target.value}))}/></label><label>{t('メール（架空）','Email (synthetic)')}<input value={contact.email} disabled={busy||draft.locked} onChange={e=>setContact(c=>({...c,email:e.target.value}))}/></label><label className="guest-choice"><input type="checkbox" checked={contact.termsAccepted} disabled={busy||draft.locked} onChange={e=>setContact(c=>({...c,termsAccepted:e.target.checked}))}/>{t('合成データによる開発確認であることを確認','I understand this is a synthetic development preview')}</label>
 {!draft.booking&&<button disabled={busy||!contact.termsAccepted||!simulation} onClick={()=>void run(()=>request('/checkout',{locale,draftId:draft.id,expectedRevision:draft.revision,reviewHash:draft.reviewHash,contact:{displayName:contact.displayName,email:contact.email,termsAccepted:contact.termsAccepted}}))}>{draft.locked?t('同じ保存済み要求を照合','Reconcile saved request'):t('在庫をHOLDして開発用決済を照合','Hold stock and reconcile test payment')}</button>}{!simulation&&<p>{t('この環境では決済接続が未設定です。','Payment is not connected in this environment.')}</p>}
 {draft.quote&&!draft.booking&&draft.priceReviewRequired&&<button disabled={busy} onClick={()=>void run(()=>request('/accept-price',{draftId:draft.id,expectedRevision:draft.revision,snapshotSha256:draft.quote!.snapshotSha256}))}>{t('保存済みの新しい見積を確認・承認する','Review and accept the new saved estimate')}</button>}
 {draft.hold&&<p>{draft.booking?.state==='CONFIRMED_DEV'?t('確認済み予約は元の契約期間の在庫保護を維持。参考：初期HOLD期限','Confirmed booking retains contract-period protection. Initial HOLD expiry for reference'):t('在庫HOLD期限','Inventory HOLD expiry')}: <time>{draft.hold.expiresAt}</time> / {draft.hold.state}</p>}{draft.quote&&<p>{t('保存済み見積','Saved estimate')}: {money(draft.quote.snapshot.totalJpy)} / {draft.quote.validity}</p>}
 {draft.booking&&<div role="status" className="guest-result"><h3>{draft.booking.state}</h3><p>{money(draft.booking.priceSnapshot.totalJpy)}</p>{draft.booking.payments.map((p,n)=><p key={n}>{t('照合状態','Reconciliation state')}: {p.state}</p>)}{draft.booking.state==='CONFIRMED_DEV'&&<SaveBookingAccess bookingId={draft.booking.id} locale={locale}/>}{draft.booking.qrImage&&<picture><img src={draft.booking.qrImage} width={240} height={240} alt={t('開発予約QR','Development booking QR')}/></picture>}{draft.booking.qr&&<><p>{t('開発予約QRの内容','Development QR content')}</p><code>{draft.booking.qr}</code></>}{draft.booking.state!=='CONFIRMED_DEV'&&<button disabled={busy} onClick={()=>void run(()=>request('/reconcile',{}))}>{t('決済状態を再照合','Reconcile payment status')}</button>}</div>}
 </section>}
 <button disabled={busy} onClick={()=>void run(()=>request('/draft'))}>{t('保存済みの結果を再読込','Reload saved result')}</button><button disabled={busy} onClick={()=>void run(async()=>{await request('/logout',{});setDraft(null);setInput({pickupStore:'MOUNTAIN_BASE',returnStore:'MOUNTAIN_BASE',period:{startDate:'',endDate:'',slot:'DAY'},members:[blank(1)]});setDirections({});location.assign(new URL('/'+locale,location.origin).href);return draft;})}>{t('この予約画面を閉じる','Close this booking context')}</button>
 </>}{message&&<p role="alert">{message} — {t('結果が不明な場合は、保存済みの結果を再読込してください。','If the result is uncertain, reload the saved result.')}</p>}</main></div>;
}
