 'use client';
import {useState} from 'react';
const requestKey='zao-guest-recovery-request';
export function GuestRecovery({locale}:{locale:'ja'|'en'}){const ja=locale==='ja',t=(j:string,e:string)=>ja?j:e;const [code,setCode]=useState(''),[backup,setBackup]=useState(''),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function send(path:string,body?:unknown){const r=await fetch('/api/guest/'+path,{cache:'no-store',method:body?'POST':'GET',headers:{'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});if(!r.ok)throw new Error(r.status===503?'UNCONNECTED':r.status===429?'RATE':'UNAVAILABLE');return r.json();}
 async function enroll(){if(busy)return;setBusy(true);try{const m=await send('security'),enrolled=await send('recovery-code',{expectedRevision:m.revision});setBackup(enrolled.code);setMessage(t('回復コードを安全な場所へ控えてください。第三者へ渡さないでください。','Keep this recovery code in a safe place. Do not share it.'));}catch{setMessage(t('登録結果は未確認です。同じ画面で再確認してください。未接続の場合は準備完了まで利用できません。','Enrollment is unconfirmed. Retry here; an unconnected service is not ready.'));}finally{setBusy(false);}}
 async function recover(){if(busy)return;setBusy(true);try{let key=sessionStorage.getItem(requestKey);if(!key){key=crypto.randomUUID();sessionStorage.setItem(requestKey,key);}await send('recover',{code,requestId:key});sessionStorage.removeItem(requestKey);setCode('');location.reload();}catch{setMessage(t('回復結果は未確認です。同じコードで再送できます。無効・期限切れ・取消済みの場合は回復できません。','Recovery is unconfirmed. Retry the same code. Invalid, expired or revoked access cannot be recovered.'));setBusy(false);}}
 return <section aria-label={t('予約画面の回復','Recover booking access')} className="guest-main"><h2>{t('予約画面の回復','Recover booking access')}</h2><p>{t('メールアドレスや予約番号だけでは回復できません。回復しても料金・予約期限・HOLD期限は変わりません。','Email or booking number alone cannot recover access. Recovery does not change price, dates or HOLD expiry.')}</p><button disabled={busy} onClick={()=>void enroll()}>{t('回復コードを作成','Create recovery code')}</button>{backup&&<><label><input type="checkbox" checked={show} onChange={e=>setShow(e.target.checked)}/>{t('回復コードを表示','Show recovery code')}</label><label>{t('保存する回復コード','Recovery code to keep')}<input type={show?'text':'password'} readOnly value={backup} autoComplete="off" style={{maxWidth:'100%',boxSizing:'border-box'}}/></label></>}<label>{t('控えた回復コード','Your recovery code')}<input type="password" autoComplete="off" maxLength={43} value={code} onChange={e=>setCode(e.target.value)} style={{maxWidth:'100%',boxSizing:'border-box'}}/></label><button disabled={busy||code.length!==43} onClick={()=>void recover()}>{t('保存済み予約画面を回復','Recover saved booking')}</button><p role="status">{message}</p></section>;
}
