'use client';
import {StaffSessionBoundary} from './StaffSessionBoundary';
import Link from 'next/link';
import {useRef,useState} from 'react';
type Delivery={id:string;bookingId:string;eventType:string;status:string;attemptCount:number;lastSafeFailureCode:string;createdAt:string;nextAttemptAt:string|null};
export function NotificationWorkspace({stamp,stores,canResend}:{stamp:string;stores:readonly string[];canResend:boolean}){
 const [store,setStore]=useState(stores[0]??''),[rows,setRows]=useState<Delivery[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[reason,setReason]=useState('CUSTOMER_REQUEST');const active=useRef(false),requests=useRef(new Map<string,string>());
 async function load(){if(active.current)return;active.current=true;setBusy(true);setRows([]);try{const r=await fetch('/api/operations/notifications?store='+encodeURIComponent(store),{cache:'no-store',headers:{'x-zao-session':stamp}});if(!r.ok)throw Error();setRows((await r.json()).deliveries);setMessage('通知一覧を更新しました。配送事業者は未接続です。');}catch{setRows([]);setMessage('通知状態を確認できません。権限と接続を確認してください。');}finally{active.current=false;setBusy(false);}}
 async function resend(d:Delivery){if(active.current)return;active.current=true;setBusy(true);const intent=d.id+':'+store+':'+reason;let key=requests.current.get(intent);if(!key){key=crypto.randomUUID();requests.current.set(intent,key);}try{const r=await fetch('/api/operations/notification-resend',{method:'POST',cache:'no-store',headers:{'content-type':'application/json','x-zao-session':stamp},body:JSON.stringify({requestKey:key,input:{deliveryId:d.id,store,reason}})});if(!r.ok){setMessage(r.status===429?'再送の受付上限です。時間をおいて状態を確認してください。':'再送を受け付けられません。結果不明・権限・期限を確認してください。');return;}setMessage('再送要求を保存しました。送信完了は通知一覧で確認してください。');}catch{setMessage('受付結果は未確認です。もう一度操作した場合も同じ要求を照合します。');}finally{active.current=false;setBusy(false);}}
 return <StaffSessionBoundary stamp={stamp}><main><h1>予約通知</h1><nav><Link href="/staff/ledger">スタッフ台帳</Link></nav><p>予約の成立と配送の成否を分けて確認します。結果不明の通知は、配送先へ照会するまで再送できません。</p><label>店舗<select value={store} disabled={busy} onChange={e=>{setStore(e.target.value);setRows([]);}}>{stores.map(s=><option key={s}>{s}</option>)}</select></label><button disabled={busy||!store} onClick={()=>void load()}>通知状態を読み込む</button>{canResend&&<label>再送理由<select value={reason} disabled={busy} onChange={e=>setReason(e.target.value)}><option value="CUSTOMER_REQUEST">お客様からの依頼</option><option value="DELIVERY_RECOVERY">配送障害からの復旧</option></select></label>}{message&&<p role="status">{message}</p>}<section aria-label="通知一覧">{rows.map(d=><article key={d.id} style={{overflowWrap:'anywhere',borderBottom:'1px solid #bbb',padding:'1rem 0'}}><h2>{d.eventType}</h2><p>予約: {d.bookingId}</p><p>状態: {d.status} / 試行: {d.attemptCount}</p><p>最終結果: {d.lastSafeFailureCode}</p><p>受付: <time>{d.createdAt}</time>{d.nextAttemptAt&&<> / 次回以降: <time>{d.nextAttemptAt}</time></>}</p>{canResend&&<button disabled={busy||!(d.status==='SENT'||d.status==='PERMANENT_FAILURE'&&d.lastSafeFailureCode==='RETRY_EXHAUSTED')} onClick={()=>void resend(d)}>再送を依頼</button>}</article>)}</section></main></StaffSessionBoundary>;
}
