'use client';
import {useState} from 'react';
import type {QuoteService} from '../../../../packages/core/src/pricing/quote-service';
import {StaffSessionBoundary} from './StaffSessionBoundary';
import {useOperationsRequest} from './useOperationsRequest';
import './holds.css';
import './operations.css';
type Catalog=Awaited<ReturnType<QuoteService['catalog']>>;type Draft=Awaited<ReturnType<QuoteService['draftView']>>;
export function PriceAdminWorkspace({stamp}:{stamp:string}){return <StaffSessionBoundary stamp={stamp}><Workspace stamp={stamp}/></StaffSessionBoundary>;}
function Workspace({stamp}:{stamp:string}){const op=useOperationsRequest(stamp,'price'),[catalog,setCatalog]=useState<Catalog|null>(null),[draft,setDraft]=useState<Draft|null>(null),[book,setBook]=useState(''),[from,setFrom]=useState(''),[until,setUntil]=useState(''),[product,setProduct]=useState(''),[duration,setDuration]=useState('DAY_1'),[amount,setAmount]=useState(''),[reason,setReason]=useState(''),[effective,setEffective]=useState('');
 const after=()=>{setDraft(null);setCatalog(null);};
 return <main className="holds operations"><h1>料金版の管理</h1><nav><a href="/staff/quotes">予約見積</a> · <a href="/admin/assets">用品台帳</a></nav><p>適用済み料金版と過去の予約価格は変更しません。編集は新しいdraftへ複製します。この構成は非公開の検証用です。</p><p role="status">{op.message}</p>{op.pending&&<button disabled={op.busy} onClick={()=>void op.send(op.pending!.path,null,after,true)}>保存済みの同じ要求を照合</button>}
 <button disabled={op.disabled} onClick={()=>void op.load<Catalog>('/api/quotes/catalog',setCatalog)}>料金版を読み込む</button>
 <fieldset disabled={op.disabled}><legend>既存料金版</legend><label>料金版<select value={book} onChange={e=>{setBook(e.target.value);setDraft(null);}}><option value="">選択</option>{catalog?.books.map(b=><option key={b.id} value={b.id}>{b.id} · {b.state}</option>)}</select></label><button disabled={!book} onClick={()=>void op.load<Draft>('/api/quotes/draft/'+book,setDraft)}>料金表と差分を表示</button><label>理由<input value={reason} maxLength={160} onChange={e=>setReason(e.target.value)}/></label><label>対象開始日<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>対象終了日<input type="date" value={until} onChange={e=>setUntil(e.target.value)}/></label><button disabled={!book||!from||!until||!reason.trim()} onClick={()=>void op.send('/api/quotes/manage',{operation:'createDraft',input:{bookId:crypto.randomUUID(),sourceId:book,rentalFrom:from,rentalUntil:until,reason}},after)}>選択した料金版からdraftを作る</button></fieldset>
 {draft&&<section><h2>{draft.book.state} · revision {draft.book.revision}</h2><div className="table-scroll"><table><thead><tr><th>商品</th><th>期間</th><th>金額（円）</th></tr></thead><tbody>{Object.entries(draft.book.table_jpy).flatMap(([p,table])=>Object.entries(table).map(([d,n])=><tr key={p+d}><td>{p}</td><td>{d}</td><td>{n.toLocaleString()}</td></tr>))}</tbody></table></div><h3>複製元との差分</h3><ul>{draft.changes.map(c=><li key={c.product+c.duration}>{c.product} / {c.duration}: {c.before??'—'} → {c.after}円</li>)}</ul>
 <fieldset disabled={op.disabled||draft.book.state!=='DRAFT'}><legend>draftの編集</legend><label>商品<select value={product} onChange={e=>setProduct(e.target.value)}><option value="">選択</option>{Object.keys(draft.book.table_jpy).map(p=><option key={p}>{p}</option>)}</select></label><label>期間<select value={duration} onChange={e=>setDuration(e.target.value)}>{Object.keys(draft.book.table_jpy[product]??draft.book.table_jpy[Object.keys(draft.book.table_jpy)[0]!]!).map(d=><option key={d}>{d}</option>)}</select></label><label>金額（円）<input type="number" min="0" value={amount} onChange={e=>setAmount(e.target.value)}/></label><button disabled={!product||!amount||!reason.trim()} onClick={()=>void op.send('/api/quotes/manage',{operation:'editDraft',input:{bookId:book,revision:draft.book.revision,product,duration,amount:Number(amount),reason}},after)}>draftを更新する</button><label>適用日時（この端末の時間帯）<input type="datetime-local" value={effective} onChange={e=>setEffective(e.target.value)}/></label><button disabled={!effective||!reason.trim()} onClick={()=>void op.send('/api/quotes/manage',{operation:'activate',input:{bookId:book,revision:draft.book.revision,effectiveAt:new Date(effective).toISOString(),predecessorId:catalog?.active?.id??null,reason}},after)}>表示した料金版を確定・適用する</button></fieldset></section>}
 </main>;}
