 'use client';
import {useEffect,useRef,useState} from 'react';
import type {HoldConditions,Period} from '../../../../packages/contracts/src/hold';
import type {StoreId} from '../../../../packages/contracts/src/ledger';
import type {FrozenPriceSnapshot} from '../../../../packages/contracts/src/pricing';
import {StaffSessionBoundary,invalidateStaffView} from './StaffSessionBoundary';
import './holds.css';
type Product={key:string;sport:string;kind:string;age:string;tier:string};
type Variant={id:string;family:string;age:string;tier:string;size:string;name:string};
type Hold={id:string;conditions:HoldConditions;expires_at:string};
type Quote={id:string;snapshot:FrozenPriceSnapshot;snapshotSha256:string;holdId:string|null;validity:string;chargeReady:false};
type Catalog={products:Product[];books:{id:string;state:string;revision:number;rental_from:string;rental_until:string}[];active:{book_id:string}|null};
type Pending={path:string;body:unknown};
type Member=HoldConditions['members'][number];
const pendingKey='zao-rental-quote-pending-v1';
const names:Record<string,string>={SKI:'スキー',SNOWBOARD:'ボード',SKI_BOOT:'スキーブーツ',SNOWBOARD_BOOT:'ボードブーツ',POLE:'ポール',SKI_SET:'スキーセット',SNOWBOARD_SET:'ボードセット',SET:'セット',EQUIPMENT_ONLY:'板のみ',BOOTS_ONLY:'ブーツのみ',POLES_ONLY:'ポールのみ',ADULT:'大人',KIDS:'子供',REGULAR:'Regular',PREMIUM:'Premium',STANDARD:'共通料金'};
function productLabel(p:Product){return [p.sport,p.kind,p.age,p.tier].map(v=>names[v]??v).join(' / ');}
function member(key:string):Member{return {key,product:'SKI_SET',age:'ADULT',tier:'REGULAR',items:[{family:'SKI',variantIds:[]},{family:'SKI_BOOT',variantIds:[]},{family:'POLE',variantIds:[]}]};}
function recover(stamp:string):{pending:Pending|null;blocked:boolean}{try{const raw=sessionStorage.getItem(pendingKey);if(!raw)return {pending:null,blocked:false};const v=JSON.parse(raw);if(v.stamp!==stamp){sessionStorage.removeItem(pendingKey);return {pending:null,blocked:false};}if(!['','/private-initialize'].includes(v.path)||!v.body)throw 0;return {pending:{path:v.path,body:v.body},blocked:false};}catch{return {pending:null,blocked:true};}}
export function QuoteWorkspace(p:{stamp:string;stores:StoreId[];canCreate:boolean;canConfigure:boolean}){return <StaffSessionBoundary stamp={p.stamp}><Workspace {...p}/></StaffSessionBoundary>;}
function Workspace({stamp,stores,canCreate,canConfigure}:{stamp:string;stores:StoreId[];canCreate:boolean;canConfigure:boolean}){
 const [initial]=useState(()=>recover(stamp)),[pending,setPending]=useState<Pending|null>(initial.pending),[storageBlocked,setStorageBlocked]=useState(initial.blocked),[busy,setBusy]=useState(false),[message,setMessage]=useState(initial.pending?'前回の結果が未確認です。同じ要求を照合してください。':''),[catalog,setCatalog]=useState<Catalog|null>(null),[variants,setVariants]=useState<Variant[]>([]),[holds,setHolds]=useState<Hold[]>([]),[quotes,setQuotes]=useState<Quote[]>([]),[selected,setSelected]=useState<Quote|null>(null);
 const [pickup,setPickup]=useState<StoreId>(stores[0]!),[returned,setReturned]=useState<StoreId>(stores[0]!),[period,setPeriod]=useState<Period>({startDate:'',endDate:'',slot:'DAY'}),[members,setMembers]=useState<Member[]>([member('person-1')]),[holdId,setHoldId]=useState<string|null>(null),[coupon,setCoupon]=useState(''),[advance,setAdvance]=useState(false),[from,setFrom]=useState(''),[until,setUntil]=useState('');
 const reservation=useRef<string|null>(null),alive=useRef(true),generation=useRef(0);useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const blocked=busy||Boolean(pending)||storageBlocked;
 async function call(path:string,body?:unknown){const r=await fetch('/api/quotes'+path,{cache:'no-store',method:body===undefined?'GET':'POST',headers:{'content-type':'application/json','x-zao-session':stamp},...(body===undefined?{}:{body:JSON.stringify(body)})});const v=await r.json();if([401,403].includes(r.status)||v.error==='SESSION_CHANGED'){invalidateStaffView();throw new Error('SESSION_CHANGED');}if(!r.ok)throw Object.assign(new Error(v.error),{definite:r.status<500});return v;}
 async function reload(){return Promise.all([call('/catalog'),call('/options'),call('')]);}
 function apply([c,o,q]:[Catalog,{variants:Variant[];holds:Hold[]},Quote[]]){setCatalog(c);setVariants(o.variants);setHolds(o.holds);setQuotes(q);}
 useEffect(()=>{let current=true;reload().then(v=>{if(current)apply(v);}).catch(()=>{if(current)setMessage('見積を読み込めませんでした');});return()=>{current=false;};},[stamp]); // eslint-disable-line react-hooks/exhaustive-deps
 function changed(){setSelected(null);}
 function replaceMember(index:number,m:Member){setMembers(members.map((old,i)=>i===index?m:old));changed();}
 function selectProduct(index:number,key:string){const p=catalog?.products.find(p=>p.key===key);if(!p)return;const family=p.sport==='SKI'?'SKI':'SNOWBOARD';const families=p.kind==='SET'?(family==='SKI'?['SKI','SKI_BOOT','POLE']:['SNOWBOARD','SNOWBOARD_BOOT']):[p.kind==='EQUIPMENT_ONLY'?family:p.kind==='BOOTS_ONLY'?family+'_BOOT':'POLE'];replaceMember(index,{key:members[index]!.key,product:p.kind==='SET'?(family+'_SET') as Member['product']:'SINGLE',age:p.age as Member['age'],tier:p.tier==='PREMIUM'?'PREMIUM':'REGULAR',items:families.map(f=>({family:f as Member['items'][number]['family'],variantIds:[]}))});}
 function keyFor(m:Member){if(m.product!=='SINGLE')return m.product+'_'+m.age+'_'+m.tier;const family=m.items[0]!.family,sport=['SNOWBOARD','SNOWBOARD_BOOT'].includes(family)?'SNOWBOARD':'SKI',kind=['SKI','SNOWBOARD'].includes(family)?'EQUIPMENT_ONLY':family==='POLE'?'POLES_ONLY':'BOOTS_ONLY';return [sport,kind,m.age,kind==='EQUIPMENT_ONLY'?m.tier:'STANDARD'].join('_');}
 function copyHold(h:Hold){setHoldId(h.id);setPickup(h.conditions.pickupStore);setReturned(h.conditions.returnStore);setPeriod(h.conditions.period);setMembers(h.conditions.members);reservation.current=h.conditions.reservationId;changed();}
 async function choose(id:string){const n=++generation.current;setBusy(true);try{const q=await call('/'+id);if(alive.current&&n===generation.current)setSelected(q);}catch{if(alive.current)setMessage('保存済み見積を読込できませんでした');}finally{if(alive.current&&n===generation.current)setBusy(false);}}
 async function send(p:Pending){try{sessionStorage.setItem(pendingKey,JSON.stringify({stamp,...p}));}catch{setStorageBlocked(true);setMessage('要求を保存できないため変更停止');return;}setPending(p);setBusy(true);const n=++generation.current;try{const result=await call(p.path,p.body);if(!alive.current||n!==generation.current)return;sessionStorage.removeItem(pendingKey);setPending(null);setSelected(result.quote??null);setMessage(result.replayed?'元の要求を照合しました':'保存しました。請求・決済は行っていません。');try{const v=await reload();if(alive.current&&n===generation.current)apply(v);}catch{if(alive.current)setMessage('保存済みです。一覧を再読込してください。');}}catch(e){if(alive.current&&n===generation.current){if((e as {definite?:boolean}).definite){try{sessionStorage.removeItem(pendingKey);setPending(null);}catch{setStorageBlocked(true);}}setMessage((e as {definite?:boolean}).definite?'処理を拒否しました：'+(e as Error).message:'結果未確認です。同じ要求を照合してください。');}}finally{if(alive.current&&n===generation.current)setBusy(false);}}
 function create(){reservation.current??=crypto.randomUUID();void send({path:'',body:{requestKey:crypto.randomUUID(),input:{conditions:{reservationId:reservation.current,pickupStore:pickup,returnStore:returned,period,members},holdId,couponCode:coupon||null,wantAdvance:advance}}});}
 return <main className="holds"><header><p>ZAO Rental · 開発用実DB</p><h1>非公開の料金・見積</h1><nav><a href="/staff/ledger">台帳へ</a> · <a href="/staff/holds">期間在庫へ</a> · <a href="/staff/users">スタッフ管理</a> · <a href="/staff/logout">ログアウト</a></nav></header><p>税区分は未確認です。これは支払額の確定・在庫確保・請求ではありません。早割は前日15時までの決済完了が必要で、ここでは適用見込みのみ確認します。</p>
 <section aria-label="料金版"><h2>料金版</h2><p>正本の下書き価格から作成した非公開の開発用コピーです。本番利用は無効。</p>{catalog?.books.map(b=><p key={b.id}>{b.id} · {b.state} · 版 {b.revision} · {b.rental_from}〜{b.rental_until}</p>)}{!catalog?.active&&<p>利用できる開発用料金版がありません。</p>}
 {canConfigure&&!catalog?.books.length&&<fieldset disabled={blocked}><legend>初期料金を開発用に設定</legend><label>料金の対象開始日<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>料金の対象終了日<input type="date" value={until} onChange={e=>setUntil(e.target.value)}/></label><p>正本の価格をコピーします。この期間を営業日・販売期間として公開しません。</p><button onClick={()=>void send({path:'/private-initialize',body:{operation:'initializePrivate',input:{requestKey:crypto.randomUUID(),rentalFrom:from,rentalUntil:until}}})}>開発用の初期料金を設定</button></fieldset>}</section>
 <fieldset disabled={blocked||!canCreate||!catalog?.active}><legend>見積条件</legend><div className="hold-grid"><label>受取店舗<select aria-label="受取店舗" value={pickup} onChange={e=>{setPickup(e.target.value as StoreId);changed();}}>{stores.map(s=><option key={s}>{s}</option>)}</select></label><label>返却店舗<select aria-label="返却店舗" value={returned} onChange={e=>{setReturned(e.target.value as StoreId);changed();}}>{stores.map(s=><option key={s}>{s}</option>)}</select></label><label>利用開始日<input type="date" value={period.startDate} onChange={e=>{setPeriod({...period,startDate:e.target.value});changed();}}/></label><label>利用終了日<input type="date" value={period.endDate} onChange={e=>{setPeriod({...period,endDate:e.target.value});changed();}}/></label><label>利用区分<select aria-label="利用区分" value={period.slot} onChange={e=>{setPeriod({...period,slot:e.target.value as Period['slot']});changed();}}><option value="DAY">1日</option><option value="MULTIDAY">連日（1〜10日）</option><option value="AM">午前半日</option><option value="PM">午後半日</option></select></label></div>
 {members.map((m,index)=><fieldset key={m.key}><legend>利用者 {index+1}（個人情報なし）</legend><label>商品 {index+1}<select aria-label={"商品 "+(index+1)} value={keyFor(m)} onChange={e=>selectProduct(index,e.target.value)}>{catalog?.products.map(p=><option key={p.key} value={p.key}>{productLabel(p)}</option>)}</select></label>{m.items.map((item,j)=><label key={item.family}>{names[item.family]}のサイズ {index+1}<select aria-label={names[item.family]+'のサイズ '+(index+1)} value={item.variantIds[0]??''} onChange={e=>replaceMember(index,{...m,items:m.items.map((old,k)=>k===j?{...old,variantIds:[e.target.value]}:old)})}><option value="">選択</option>{variants.filter(v=>v.family===item.family&&v.age===m.age&&v.tier===m.tier).map(v=><option key={v.id} value={v.id}>{v.name} / {v.size} / {v.id.slice(0,8)}</option>)}</select></label>)}{members.length>1&&<button onClick={()=>{setMembers(members.filter((_,i)=>i!==index));changed();}}>利用者 {index+1} を除く</button>}</fieldset>)}<button disabled={members.length>=20} onClick={()=>{setMembers([...members,member('person-'+crypto.randomUUID().slice(0,16))]);changed();}}>利用者を追加</button>
 <label>クーポンコード<input maxLength={32} value={coupon} onChange={e=>{setCoupon(e.target.value);changed();}}/></label><label><input type="checkbox" checked={advance} onChange={e=>{setAdvance(e.target.checked);changed();}}/>早割5％の適用見込みを確認</label><p>未設定の割引併用は許可しません。クーポンの利用回数は見積では消費しません。</p><p>紐づけたHOLD：{holdId??'なし（在庫未確保）'}</p>{holdId&&<button onClick={()=>{setHoldId(null);reservation.current=null;changed();}}>HOLD連携を外して別見積にする</button>}<button onClick={create}>見積を作成して保存</button></fieldset>
 <section><h2>自分のHOLDから条件を読み込む</h2><p>変更後の条件がHOLDと異なる場合は拒否します。見積作成でHOLDを延長しません。</p>{holds.map(h=><button disabled={blocked} key={h.id} onClick={()=>copyHold(h)}>HOLD {h.id}</button>)}</section>
 {pending&&!busy&&<button disabled={storageBlocked} onClick={()=>void send(pending)}>同じ要求を照合・再送</button>}<p role="status">{storageBlocked?'保存領域を確認できないため変更停止。':message}</p>
 <section><h2>保存済みの自分の見積</h2>{quotes.map(q=><button disabled={blocked} key={q.id} onClick={()=>void choose(q.id)}>{q.id.slice(0,8)} · {q.snapshot.totalJpy.toLocaleString()} 円 · {q.validity}</button>)}</section>
 {selected&&<section aria-label="見積詳細"><h2>保存時点の見積</h2><p>{selected.id} / {selected.validity}</p><p>料金版 {selected.snapshot.priceBookId}</p><p>利用 {selected.snapshot.conditions.period.startDate}〜{selected.snapshot.conditions.period.endDate} / {selected.snapshot.conditions.period.slot} / {selected.snapshot.conditions.pickupStore} / {selected.snapshot.conditions.members.length}名</p><ul>{selected.snapshot.items.map(i=><li key={i.memberKey}>{i.memberKey} · {i.productKey} · {i.duration} · {i.lineJpy.toLocaleString()} 円</li>)}</ul><dl><dt>小計</dt><dd>{selected.snapshot.subtotalJpy.toLocaleString()} 円</dd><dt>クーポン（未消費）</dt><dd>−{selected.snapshot.couponDiscountJpy.toLocaleString()} 円</dd><dt>早割（決済前の見込み）</dt><dd>−{selected.snapshot.advanceDiscountJpy.toLocaleString()} 円</dd><dt>見積合計</dt><dd>{selected.snapshot.totalJpy.toLocaleString()} 円</dd></dl><p>有効期限 {new Date(selected.snapshot.expiresAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'})} JST</p><p>税区分未確認・請求確定ではありません。{selected.holdId?'HOLD '+selected.holdId:'在庫確保なし'}。有効性は再読込時に確認します。</p></section>}</main>;
}
