 'use client';
import {useEffect,useRef,useState} from 'react';
import type {StoreId} from '../../../../packages/contracts/src/ledger';
import type {RecommendationInput,Profile,Direction,Variant} from '../../../../packages/contracts/src/recommendation';
import type {RecommendationService} from '../../../../packages/core/src/recommendation/recommendation-service';
import {StaffSessionBoundary,invalidateStaffView} from './StaffSessionBoundary';
import './holds.css';
import './recommendation.css';
type View=Awaited<ReturnType<RecommendationService['get']>>;
type Member=Omit<Profile,'adultAtStart'|'ski'>&{adultAtStart:boolean|null;ski:{weightKg:number;ageAtStart:number;level:string}|null};
type Draft=Omit<RecommendationInput,'members'>&{members:Member[]};
type Pending={path:string;body:unknown};
const pendingKey='zao-rental-recommendation-pending-v1';
const labels:Record<Direction,string>={RECOMMENDED:'おすすめ',SHORTER:'短め',LONGER:'長め'};
function member(key:string):Member{return {key,sport:'SKI',heightCm:0,footCm:0,adultAtStart:null,tier:'REGULAR',ski:{weightKg:0,ageAtStart:0,level:''},poleVariantId:null};}
function recover(stamp:string):{pending:Pending|null;blocked:boolean}{try{const raw=sessionStorage.getItem(pendingKey);if(!raw)return {pending:null,blocked:false};const v=JSON.parse(raw);if(v.stamp!==stamp){sessionStorage.removeItem(pendingKey);return {pending:null,blocked:false};}if(typeof v.path!=='string'||!/^$|^\/[a-f0-9-]{36}\/(select|resume)$/.test(v.path)||!v.body)throw 0;return {pending:{path:v.path,body:v.body},blocked:false};}catch{return {pending:null,blocked:true};}}
export function RecommendationWorkspace(p:{stamp:string;stores:StoreId[];canSelect:boolean;integrated?:boolean}){return <StaffSessionBoundary stamp={p.stamp}><Workspace {...p}/></StaffSessionBoundary>;}
function Workspace({stamp,stores,canSelect,integrated=false}:{stamp:string;stores:StoreId[];canSelect:boolean;integrated?:boolean}){
 const [initial]=useState(()=>recover(stamp)),[pending,setPending]=useState(initial.pending),[storageBlocked,setStorageBlocked]=useState(initial.blocked),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[variants,setVariants]=useState<Variant[]>([]),[saved,setSaved]=useState<{id:string;input:RecommendationInput}[]>([]),[view,setView]=useState<View|null>(null);
 const [input,setInput]=useState<Draft>({...(integrated?{contractVersion:'INTEGRATED_V1_2' as const}:{}),pickupStore:stores[0]!,returnStore:stores[0]!,period:{startDate:'',endDate:'',slot:'DAY'},members:[member('person-1')]}),[directions,setDirections]=useState<Record<string,Direction>>({}),[replaceHoldId,setReplaceHoldId]=useState<string|null>(null),[accept,setAccept]=useState(false),[advance,setAdvance]=useState(false),[coupon,setCoupon]=useState('');
 const alive=useRef(true),generation=useRef(0);useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const blocked=storageBlocked||Boolean(pending?.path)||busy&&pending?.path!=='';
 async function call(path:string,body?:unknown){const r=await fetch('/api/recommendations'+path,{cache:'no-store',method:body===undefined?'GET':'POST',headers:{'content-type':'application/json','x-zao-session':stamp},...(body===undefined?{}:{body:JSON.stringify(body)})});const v=await r.json();if([401,403].includes(r.status)||v.error==='SESSION_CHANGED'){invalidateStaffView();throw new Error('SESSION_CHANGED');}if(!r.ok)throw Object.assign(new Error(v.error),{definite:r.status<500&&v.error!=='OPERATION_IN_PROGRESS'});return v;}
 async function refresh(){const list=await call('');if(alive.current)setSaved(list);}
 useEffect(()=>{let current=true;Promise.all([call('/options'),call('')]).then(([o,list])=>{if(current){setVariants(o.variants);setSaved(list);}}).catch(()=>{if(current)setMessage('読込できませんでした');});return()=>{current=false;};},[stamp]); // eslint-disable-line react-hooks/exhaustive-deps
 function changed(next:Draft){generation.current++;setInput({...next,...(integrated?{contractVersion:'INTEGRATED_V1_2' as const}:{})});setView(null);setDirections({});setAccept(false);setMessage('条件を変更しました。推薦を再取得してください。');if(pending?.path===''){try{sessionStorage.removeItem(pendingKey);setPending(null);setBusy(false);}catch{setStorageBlocked(true);}}}
 function sportChange(i:number,sport:Profile['sport']){const old=input.members[i]!;const next:Member={key:old.key,sport,heightCm:sport==='WEAR'?null:old.heightCm??0,footCm:sport==='WEAR'?null:old.footCm??0,adultAtStart:old.adultAtStart,tier:sport==='WEAR'?'STANDARD':'REGULAR',ski:sport==='SKI'?{weightKg:0,ageAtStart:0,level:''}:null,poleVariantId:null,...(sport==='WEAR'?{wearSport:'SKI' as const,wearSelection:{jacketVariantId:'',pantsVariantId:''}}:{})};changed({...input,members:input.members.map((m,n)=>n===i?next:m)});}
 function setWear(i:number,enabled:boolean){const next={...input.members[i]!};if(enabled)next.wearSelection={jacketVariantId:'',pantsVariantId:''};else delete next.wearSelection;changed({...input,members:input.members.map((m,n)=>n===i?next:m)});}
 function changeMember(i:number,patch:Partial<Member>){const next={...input.members[i]!,...patch};if(patch.tier&&patch.tier!=='PREMIUM')delete next.modelSelection;changed({...input,members:input.members.map((m,n)=>n===i?next:m)});}
 function changeModel(i:number,value:string){const [modelId,season]=value.split('|'),next={...input.members[i]!};if(modelId&&season)next.modelSelection={modelId,season};else delete next.modelSelection;changed({...input,members:input.members.map((m,n)=>n===i?next:m)});}
 function apply(v:View){setView(v);setInput(v.preview.input);setDirections(v.selection?.selection.directions??{});setAccept(Boolean(v.selection));setAdvance(v.selection?.selection.wantAdvance??false);setCoupon(v.selection?.selection.couponCode??'');setReplaceHoldId(v.hold?.id??v.preview.replacement_hold_id);}
 async function open(id:string){const n=++generation.current;setBusy(true);try{const v=await call('/'+id);if(alive.current&&n===generation.current)apply(v);}catch{if(alive.current&&n===generation.current)setMessage('保存済み結果を読込できませんでした');}finally{if(alive.current&&n===generation.current)setBusy(false);}}
 async function send(p:Pending){try{sessionStorage.setItem(pendingKey,JSON.stringify({stamp,...p}));}catch{setStorageBlocked(true);return;}setPending(p);setBusy(true);setMessage('処理中…');const n=++generation.current;
  try{const v:View=await call(p.path,p.body);if(!alive.current||n!==generation.current)return;sessionStorage.removeItem(pendingKey);setPending(null);apply(v);setMessage(v.selection?.outcome??(v.selection?.stage==='COMPLETE'?'HOLDと見積を保存しました。予約・支払いは未確定です。':'推薦候補を保存しました。在庫は未確保です。'));await refresh();}
  catch(e){if(alive.current&&n===generation.current){if((e as {definite?:boolean}).definite){try{sessionStorage.removeItem(pendingKey);setPending(null);}catch{setStorageBlocked(true);}}setMessage((e as {definite?:boolean}).definite?'拒否されました：'+(e as Error).message:'結果未確認です。同じ要求を照合してください。');}}
  finally{if(alive.current&&n===generation.current)setBusy(false);}
 }
 const selectable=view&&!view.selection&&view.preview.offered.every(o=>Boolean(directions[o.key]&&o.candidates[directions[o.key]!]))&&accept;
 return <main className="holds recommendation"><header><p>ZAO Rental · スタッフ専用プレビュー</p><h1>{integrated?'道具とウェアの統合予約プレビュー':'サイズ選択からHOLD・見積へ'}</h1><nav><a href="/staff/ledger">台帳</a> · <a href="/staff/holds">期間在庫</a> · <a href="/staff/transfers">店舗間移動</a> · <a href="/staff/quotes">料金・見積</a> · <a href="/staff/logout">ログアウト</a></nav></header>
 <p>候補の照会だけでは在庫を確保しません。全員分を選んでから一括確認します。ここで予約・支払いは完了しません。</p>
 <fieldset disabled={blocked}><legend>利用条件</legend><div className="hold-grid">{(['pickupStore','returnStore'] as const).map((k,i)=><label key={k}>{i?'返却予定店舗':'受取店舗'}<select aria-label={i?'返却予定店舗':'受取店舗'} value={input[k]} onChange={e=>changed({...input,[k]:e.target.value})}>{stores.map(s=><option key={s}>{s}</option>)}</select></label>)}<label>利用開始日<input type="date" value={input.period.startDate} onChange={e=>changed({...input,period:{...input.period,startDate:e.target.value}})}/></label><label>利用終了日<input type="date" value={input.period.endDate} onChange={e=>changed({...input,period:{...input.period,endDate:e.target.value}})}/></label><label>利用区分<select aria-label="利用区分" value={input.period.slot} onChange={e=>changed({...input,period:{...input.period,slot:e.target.value as RecommendationInput['period']['slot']}})}><option value="DAY">1日</option><option value="AM">午前半日</option><option value="PM">午後半日</option><option value="MULTIDAY">連日（1〜10日）</option></select></label></div>
 {input.members.map((m,i)=><fieldset key={m.key}><legend>利用者 {i+1}</legend><div className="hold-grid"><label>競技 {i+1}<select aria-label={'競技 '+(i+1)} value={m.sport} onChange={e=>sportChange(i,e.target.value as Profile['sport'])}><option value="SKI">スキー</option><option value="SNOWBOARD">スノーボード</option>{integrated&&<option value="WEAR">ウェアのみ</option>}</select></label><label>利用開始時の年齢区分 {i+1}<select aria-label={'利用開始時の年齢区分 '+(i+1)} value={m.adultAtStart===null?'':m.adultAtStart?'ADULT':'KIDS'} onChange={e=>changeMember(i,{adultAtStart:e.target.value===''?null:e.target.value==='ADULT',poleVariantId:null})}><option value="">確認して選択</option><option value="ADULT">13歳以上（大人）</option><option value="KIDS">12歳以下（子供）</option></select></label>{m.sport!=='WEAR'&&<><label>クラス {i+1}<select aria-label={'クラス '+(i+1)} value={m.tier} onChange={e=>changeMember(i,{tier:e.target.value as Profile['tier'],poleVariantId:null})}><option value="REGULAR">Regular</option><option value="PREMIUM">Premium</option></select></label><label>身長cm {i+1}<input type="number" value={m.heightCm||''} onChange={e=>changeMember(i,{heightCm:Number(e.target.value)})}/></label><label>足サイズcm {i+1}<input type="number" step="0.1" value={m.footCm||''} onChange={e=>changeMember(i,{footCm:Number(e.target.value)})}/></label></>}
 {integrated&&<IntegratedFields m={m} i={i} variants={variants} onWear={enabled=>setWear(i,enabled)} onMember={patch=>changeMember(i,patch)} onModel={value=>changeModel(i,value)}/>}

 {m.sport==='SKI'&&m.ski&&<><label>体重kg {i+1}<input type="number" value={m.ski.weightKg||''} onChange={e=>changeMember(i,{ski:{...m.ski!,weightKg:Number(e.target.value)}})}/></label><label>利用開始時の年齢 {i+1}<input type="number" value={m.ski.ageAtStart||''} onChange={e=>changeMember(i,{ski:{...m.ski!,ageAtStart:Number(e.target.value)}})}/></label><label>レベル {i+1}<select aria-label={'レベル '+(i+1)} value={m.ski.level} onChange={e=>changeMember(i,{ski:{...m.ski!,level:e.target.value}})}><option value="">申告を選択</option><option value="BEGINNER">初級</option><option value="INTERMEDIATE">中級</option><option value="ADVANCED">上級</option></select></label><label>ポールのサイズ {i+1}<select aria-label={'ポールのサイズ '+(i+1)} value={m.poleVariantId??''} onChange={e=>changeMember(i,{poleVariantId:e.target.value||null})}><option value="">明示的に選択（自動推薦なし）</option>{variants.filter(v=>v.family==='POLE'&&v.age===(m.adultAtStart?'ADULT':'KIDS')&&v.tier===m.tier).map(v=><option key={v.id} value={v.id}>{v.size} / ペア単位 / {v.id.slice(-8)}</option>)}</select></label></>}
 </div>{input.members.length>1&&<button onClick={()=>changed({...input,members:input.members.filter((_,n)=>n!==i)})}>利用者 {i+1} を除く</button>}</fieldset>)}<button disabled={input.members.length>=20} onClick={()=>changed({...input,members:[...input.members,member('person-'+crypto.randomUUID().slice(0,12))]})}>利用者を追加</button>
 <p>変更対象HOLD：{replaceHoldId??'なし（新規）'}。変更しても10分の期限は延長しません。</p><button disabled={busy} onClick={()=>void send({path:'',body:{requestKey:crypto.randomUUID(),input,replaceHoldId}})}>推薦候補を確認</button></fieldset>
 {view&&<section aria-label="推薦候補"><h2>全期間の判定済み候補（照会時点）</h2><p>ルール {view.preview.rule_version}。{view.preview.input.contractVersion?'Premiumは選択モデル・シーズン・サイズを保存。Regularはモデル非指定。ウェアはサイズ別数量で確保し、個体QRを発行しません。':'モデル名の確約なし。同じ競技・年齢区分・クラス・選択サイズから割当します。'}</p><p>ブーツは「大きめ推奨」：足サイズ＋1cmの初期候補です。店頭で試着・最終確認が必要です。BSL・DINを推測しません。</p>
 {view.preview.offered.map((o,i)=><article key={o.key} aria-label={'利用者 '+(i+1)+' の候補'}><h3>利用者 {i+1}{view.preview.input.members[i]?.sport==='WEAR'?' · ウェア上下':` · 基準 ${o.targetCm}cm`}</h3>{view.preview.input.members[i]?.sport!=='WEAR'&&<p>固定範囲 {o.minCm}〜{o.maxCm}cm / ブーツ {o.bootCm}cm</p>}{o.reason&&<p>{o.reason==='TRANSFER_PLAN_REQUIRED'?'移動計画が必要です。店舗間移動画面で権限付き手順を確認してください。':o.reason}</p>}<div className="candidate-grid">{(['RECOMMENDED','SHORTER','LONGER'] as Direction[]).map(d=>{const candidate=o.candidates[d];return <div key={d}><strong>{labels[d]}</strong><p>{candidate?(candidate.member.product==='WEAR_SET'?'選択した上下サイズ':candidate.lengthCm+' cm'):'該当する在庫候補なし／選択不可'}</p><p>{view.preview.input.members[i]?.tier}</p>{candidate&&(o.price?(view.preview.input.contractVersion?<IntegratedPriceCard candidate={candidate} price={o.price} variants={variants} period={view.preview.input.period}/>:<p>割引前の参考額 {Number(o.price.totalJpy).toLocaleString()} 円</p>):<p>料金未確認：{o.priceError??'候補なし'}</p>)}<button disabled={blocked||busy||Boolean(view.selection)||!candidate} aria-pressed={directions[o.key]===d} onClick={()=>{setDirections({...directions,[o.key]:d});setMessage('選択しました。在庫はまだ確保していません。');}}>{labels[d]}を選ぶ {i+1}</button></div>;})}</div></article>)}
 {!view.selection&&<fieldset disabled={blocked||busy||!canSelect}><legend>全員分の選択を確保</legend><label><input type="checkbox" checked={accept} onChange={e=>setAccept(e.target.checked)}/>{view.preview.input.contractVersion?'表示したモデル契約・サイズ・ウェア構成を選択条件とすることを確認':'モデル指定なし・表示したサイズとクラスを選択条件とすることを確認'}</label><label>クーポンコード<input value={coupon} maxLength={32} onChange={e=>setCoupon(e.target.value)}/></label><label><input type="checkbox" checked={advance} onChange={e=>setAdvance(e.target.checked)}/>早割5％の適用見込みを確認</label><button disabled={!selectable} onClick={()=>void send({path:'/'+view.preview.id+'/select',body:{requestKey:crypto.randomUUID(),selection:{directions,acceptedModelPolicy:accept,couponCode:coupon||null,wantAdvance:advance}}})}>全員分をHOLDして見積を保存</button></fieldset>}
 {view.selection&&<section aria-label="保存結果"><h2>保存結果</h2><p>{view.selection.stage} / {view.selection.outcome??'保存済み'}</p><p>選択条件の保存ID {view.preview.id}</p>{view.selection.stage==='HOLD_FAILED'&&<p>グループ全体は成立しませんでした。利用者 {view.preview.input.members.map((_,i)=>i+1).join('・')} の候補を再確認してください。サイズ・クラスは変更していません。変更前の有効HOLDは保持されます。</p>}{view.hold&&<><p>HOLD {view.hold.id} / {view.hold.state} / 期限 {view.hold.expiresAt}</p><p>{view.selectionMatchesHold?'選択条件とHOLD条件は一致しています。':'表示した選択条件と現在のHOLDは一致しません。以前の金額を新しい条件へ使えません。'}</p></>}
 {['INTENT','HOLD_SAVED'].includes(view.selection.stage)&&<button disabled={blocked||busy||!canSelect} onClick={()=>void send({path:'/'+view.preview.id+'/resume',body:{}})}>保存済みHOLD・見積処理を照合する</button>}
 {view.quote&&view.selectionMatchesHold&&<section aria-label="見積詳細"><h3>保存時点の見積</h3><a href={"/preview/rental?quote="+encodeURIComponent(view.quote.id)}>非公開の合成予約プレビューへ</a><p>{view.quote.id} / {view.quote.validity}</p><p>見積合計 {Number(view.quote.snapshot.totalJpy).toLocaleString()} 円</p><p>小計 {Number(view.quote.snapshot.subtotalJpy).toLocaleString()} 円 / ウェア調整 {Number(view.quote.snapshot.bundleDiscountJpy??0).toLocaleString()} 円 / クーポン {Number(view.quote.snapshot.couponDiscountJpy).toLocaleString()} 円 / 早割見込み {Number(view.quote.snapshot.advanceDiscountJpy).toLocaleString()} 円</p><p>料金版 {String(view.quote.snapshot.priceBookId)} / 期限 {String(view.quote.snapshot.expiresAt)}</p></section>}
 <p>税区分未確認・早割は決済完了前の見込み・請求確定不可。HOLD、見積、予約、支払いは別の状態です。</p><button disabled={blocked||busy} onClick={()=>void open(view.preview.id)}>保存結果を再読込</button></section>}
 </section>}
 {pending&&!busy&&<button disabled={storageBlocked} onClick={()=>void send(pending)}>同じ要求を照合・再送</button>}<p role="status">{storageBlocked?'保存領域が確認できないため変更停止。':message}</p><section><h2>保存済みの自分の推薦</h2>{saved.map(p=><button disabled={blocked||busy} key={p.id} onClick={()=>void open(p.id)}>推薦 {p.id.slice(0,8)} · {p.input.period.startDate}</button>)}</section></main>;
}

function IntegratedFields({m,i,variants,onWear,onMember,onModel}:{m:Member;i:number;variants:Variant[];onWear:(enabled:boolean)=>void;onMember:(patch:Partial<Member>)=>void;onModel:(value:string)=>void}){
 const sport=m.sport==='WEAR'?m.wearSport??'SKI':m.sport,age=m.adultAtStart?'ADULT':'KIDS';
 const models=variants.filter(v=>v.family===m.sport&&v.age===age&&v.tier==='PREMIUM'&&v.catalog_season&&v.model_id).filter((v,n,all)=>all.findIndex(x=>x.model_id===v.model_id&&x.catalog_season===v.catalog_season)===n);
 return <>{m.sport!=='WEAR'&&<label><input type="checkbox" aria-label={'ウェア上下セットを追加 '+(i+1)} checked={!!m.wearSelection} onChange={e=>onWear(e.target.checked)}/>ウェア上下セットを追加（道具セットと同じ利用者のウェア部分20％調整）</label>}
 {m.sport==='WEAR'&&<label>ウェア用途 {i+1}<select value={m.wearSport??'SKI'} onChange={e=>onMember({wearSport:e.target.value as 'SKI'|'SNOWBOARD'})}><option value="SKI">スキー</option><option value="SNOWBOARD">スノーボード</option></select></label>}
 {m.wearSelection&&(['WEAR_JACKET','WEAR_PANTS'] as const).map((family,n)=>{const key=n?'pantsVariantId':'jacketVariantId';return <label key={family}>{n?'下サイズ':'上サイズ'} {i+1}<select aria-label={(n?'下サイズ':'上サイズ')+' '+(i+1)} value={m.wearSelection![key]} onChange={e=>onMember({wearSelection:{...m.wearSelection!,[key]:e.target.value}})}><option value="">サイズを選択</option>{variants.filter(v=>v.family===family&&v.age===age&&v.tier==='STANDARD'&&v.compatible_sports?.includes(sport)).map(v=><option value={v.id} key={v.id}>{v.size}</option>)}</select></label>;})}
 {m.tier==='PREMIUM'&&m.sport!=='WEAR'&&<label>指定モデル・シーズン {i+1}<select aria-label={'指定モデル・シーズン '+(i+1)} value={m.modelSelection?m.modelSelection.modelId+'|'+m.modelSelection.season:''} onChange={e=>onModel(e.target.value)}><option value="">モデルを選択</option>{models.map(v=><option key={v.model_id+'|'+v.catalog_season} value={v.model_id+'|'+v.catalog_season}>{v.model_name} / {v.catalog_season}</option>)}</select></label>}</>;
}

function IntegratedPriceCard({candidate,price,variants,period}:{candidate:NonNullable<View['preview']['offered'][number]['candidates']['RECOMMENDED']>;price:Record<string,unknown>;variants:Variant[];period:RecommendationInput['period']}){
 const board=candidate.member.items.find(i=>i.family==='SKI'||i.family==='SNOWBOARD'),promise=board?.modelPromise,model=promise?variants.find(v=>v.id===promise.variantId&&v.model_id===promise.modelId&&v.catalog_season===promise.season):null;
 const lines=(Array.isArray(price.items)?price.items:[]) as {productKey:string;lineJpy:number;bundleDiscountJpy?:number}[],wear=lines.find(i=>i.productKey.startsWith('WEAR_SET_'));
 return <div className="integrated-price"><p>{period.startDate}〜{period.endDate} / {period.slot}</p>{promise?<><p><strong>指定モデル {model?.model_name??'保存されたモデルIDを確認'} / {promise.season}</strong></p><p className="photo-pending">モデル写真は準備中。別モデルの写真では補いません。</p></>:candidate.member.product!=='WEAR_SET'?<p>Regular：モデル指定なし、選択サイズ・クラスで確保</p>:null}<p>選択期間の参考総額 <strong>{Number(price.totalJpy).toLocaleString()} 円</strong></p>{wear&&<p>ウェア上下 {wear.lineJpy.toLocaleString()} 円 − 同じ利用者のセット調整 {(wear.bundleDiscountJpy??0).toLocaleString()} 円 = { (wear.lineJpy-(wear.bundleDiscountJpy??0)).toLocaleString()} 円{candidate.member.product==='WEAR_SET'?'':'の追加'}</p>}<p>ウェアは上着・パンツの上下セットです。小物は含みません。早割5％は見積で適用見込みを確認し、前日15時までの決済完了が必要です。</p><p>非公開の参考額・税区分未確認。候補表示だけでは在庫未確保です。</p></div>;
}
