 'use client';
import {useEffect,useState} from 'react';
import type {StaffRole,Permission} from '../../../../packages/auth/src/staff-auth';
type StaffRow={id:string;email:string;displayName:string;active:boolean;role:StaffRole;scope:'ALL'|'ASSIGNED';storeIds:string[];permissions:Partial<Record<Permission,boolean>>};
export function StaffManagement({stamp}:{stamp:string}){const [items,setItems]=useState<StaffRow[]>([]),[editing,setEditing]=useState<StaffRow|null|undefined>(),[error,setError]=useState('');
 async function load(){const r=await fetch('/api/staff-users',{cache:'no-store'});if(!r.ok){setItems([]);setEditing(undefined);throw new Error();}setItems((await r.json()).items);}
 useEffect(()=>{let active=true;fetch('/api/staff-users',{cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error();const data=await r.json();if(active)setItems(data.items);}).catch(()=>{if(active)setError('スタッフ一覧を取得できませんでした。');});return()=>{active=false;};},[]);
 async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setError('');const form=event.currentTarget;const d=new FormData(form);const permissionEntries=(['INVENTORY_VIEW','INVENTORY_EDIT','STAFF_MANAGE'] as const).filter(p=>d.get(p)!=='default').map(p=>[p,d.get(p)==='allow']);
 const body={displayName:d.get('displayName'),active:d.get('active')==='on',role:d.get('role'),scope:d.get('scope'),storeIds:d.getAll('store'),permissions:Object.fromEntries(permissionEntries),...(!editing?{email:d.get('email'),password:d.get('password')}:{})};
 try{const r=await fetch('/api/staff-users'+(editing?'/'+editing.id:''),{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json','x-zao-session':stamp},body:JSON.stringify(body)});if(!r.ok)throw new Error();form.reset();setEditing(undefined);await load();}catch{setError('保存できませんでした。権限・店舗・入力内容・重複メールを確認してください。自分自身の権限はここでは変更できません。');}}
 return <main className="staff-management"><div className="staff-page-head"><div><h1>スタッフ管理</h1><p>Role・個別Permission・店舗アクセスを分けて管理します。</p></div><a href="/staff/ledger">台帳へ</a></div><button onClick={()=>setEditing(null)}>スタッフを作成</button>{error&&<p role="alert">{error}</p>}
 {editing!==undefined&&<form className="staff-management-form" key={editing?.id??'new'} onSubmit={e=>void save(e)} aria-label={editing?'スタッフ更新':'スタッフ作成'}><h2>{editing?'スタッフ更新':'スタッフ作成'}</h2><label>表示名<input name="displayName" required maxLength={80} defaultValue={editing?.displayName??''}/></label>{!editing&&<><label>メールアドレス<input name="email" type="email" required maxLength={254} autoComplete="off"/></label><label>初期パスワード（15〜128文字）<input name="password" type="password" required minLength={15} maxLength={128} autoComplete="new-password"/></label><p>初期パスワードは本人へ安全な方法で伝え、本人が変更してください。画面やログへ再表示しません。</p></>}
 <label>Role<select name="role" defaultValue={editing?.role??'STAFF'}>{['ADMIN','MANAGER','STAFF','VIEWER'].map(r=><option key={r}>{r}</option>)}</select></label><label><input type="checkbox" name="active" defaultChecked={editing?.active??true}/>有効</label>
 <label>店舗範囲<select name="scope" defaultValue={editing?.scope??'ASSIGNED'}><option value="ASSIGNED">選択した店舗のみ</option><option value="ALL">全店舗（明示的な付与）</option></select></label><fieldset><legend>店舗アクセス</legend>{['MOUNTAIN_BASE','ONSEN_BASE'].map(s=><label key={s}><input type="checkbox" name="store" value={s} defaultChecked={editing?.storeIds.includes(s)??false}/>{s}</label>)}</fieldset>
 <fieldset><legend>個別Permission</legend>{(['INVENTORY_VIEW','INVENTORY_EDIT','STAFF_MANAGE'] as const).map(p=><label key={p}>{{INVENTORY_VIEW:'台帳の閲覧',INVENTORY_EDIT:'台帳の登録・更新',STAFF_MANAGE:'スタッフ管理'}[p]}<select aria-label={{INVENTORY_VIEW:'台帳の閲覧',INVENTORY_EDIT:'台帳の登録・更新',STAFF_MANAGE:'スタッフ管理'}[p]} name={p} defaultValue={editing?.permissions[p]===undefined?'default':editing.permissions[p]?'allow':'deny'}><option value="default">Roleの標準</option><option value="allow">付与</option><option value="deny">剥奪</option></select></label>)}</fieldset><p>STAFF / VIEWERの標準は台帳閲覧のみ。返金・価格変更の権限は実装していません。</p><button type="submit">スタッフ設定を保存</button><button type="button" onClick={()=>setEditing(undefined)}>閉じる</button></form>}
 <ul className="staff-cards">{items.map(s=><li key={s.id}><h2>{s.displayName}</h2><p>{s.email}</p><p>{s.active?'有効':'無効'} · {s.role} · {s.scope==='ALL'?'全店舗':s.storeIds.join(' / ')}</p><button onClick={()=>setEditing(s)} aria-label={`スタッフを編集：${s.displayName}`}>設定を編集</button></li>)}</ul></main>;
}
