 'use client';
import {useEffect,useState} from 'react';
import type {StaffRole,Permission} from '../../../../packages/auth/src/staff-auth';
type StaffRow={revision:number;id:string;email:string;displayName:string;active:boolean;role:StaffRole;scope:'ALL'|'ASSIGNED';storeIds:string[];permissions:Partial<Record<Permission,boolean>>};
export function StaffManagement({stamp}:{stamp:string}){const [items,setItems]=useState<StaffRow[]>([]),[editing,setEditing]=useState<StaffRow|null|undefined>(),[error,setError]=useState(''),[conflict,setConflict]=useState(false),[saving,setSaving]=useState(false);
 async function load(){const r=await fetch('/api/staff-users',{cache:'no-store'});if(!r.ok){setItems([]);setEditing(undefined);throw new Error();}const rows:StaffRow[]=(await r.json()).items;setItems(rows);return rows;}
 async function reloadConflict(){try{const rows=await load();setEditing(rows.find(r=>r.id===editing?.id));setConflict(false);setError('');}catch{setError('最新設定を取得できませんでした。');}}
 useEffect(()=>{let active=true;fetch('/api/staff-users',{cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error();const data=await r.json();if(active)setItems(data.items);}).catch(()=>{if(active)setError('スタッフ一覧を取得できませんでした。');});return()=>{active=false;};},[]);
 async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(conflict||saving)return;setSaving(true);setError('');const form=event.currentTarget;const d=new FormData(form);const permissionEntries=(['INVENTORY_VIEW','INVENTORY_EDIT','STAFF_MANAGE','HOLD_VIEW','HOLD_EDIT','TRANSFER_VIEW','TRANSFER_PLAN','TRANSFER_DISPATCH','TRANSFER_RECEIVE','QUOTE_VIEW','QUOTE_CREATE','PRICE_EDIT','BOOKING_VIEW','BOOKING_CREATE','RENTAL_CHECKOUT','RENTAL_RETURN','RENTAL_AMEND','REFUND_OVERRIDE','INVENTORY_RECONCILE'] as const).filter(p=>d.get(p)!=='default').map(p=>[p,d.get(p)==='allow']);
 const body={displayName:d.get('displayName'),active:d.get('active')==='on',role:d.get('role'),scope:d.get('scope'),storeIds:d.getAll('store'),permissions:Object.fromEntries(permissionEntries),...(!editing?{email:d.get('email'),password:d.get('password')}:{expectedRevision:editing.revision})};
 try{const r=await fetch('/api/staff-users'+(editing?'/'+editing.id:''),{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json','x-zao-session':stamp},body:JSON.stringify(body)});if(r.status===409&&(await r.clone().json()).error==='STALE_STAFF_REVISION'){setConflict(true);setError('別の管理者が更新したため再読込が必要です。最新設定から編集し直してください。');return;}if(!r.ok)throw new Error();form.reset();setEditing(undefined);await load();}catch{setError('保存できませんでした。権限・店舗・入力内容・重複メールを確認してください。自分自身の権限はここでは変更できません。');}finally{setSaving(false);}}
 return <main className="staff-management"><div className="staff-page-head"><div><h1>スタッフ管理</h1><p>Role・個別Permission・店舗アクセスを分けて管理します。</p></div><a href="/staff/ledger">台帳へ</a></div><button onClick={()=>{setEditing(null);setConflict(false);setError('');}}>スタッフを作成</button>{error&&<p role="alert">{error}</p>}{conflict&&<button onClick={()=>void reloadConflict()}>最新設定を再読込</button>}
 {editing!==undefined&&<form className="staff-management-form" key={editing?editing.id+':'+editing.revision:'new'} onSubmit={e=>void save(e)} aria-label={editing?'スタッフ更新':'スタッフ作成'}><h2>{editing?'スタッフ更新':'スタッフ作成'}</h2><label>表示名<input name="displayName" required maxLength={80} defaultValue={editing?.displayName??''}/></label>{!editing&&<><label>メールアドレス<input name="email" type="email" required maxLength={254} autoComplete="off"/></label><label>初期パスワード（15〜128文字）<input name="password" type="password" required minLength={15} maxLength={128} autoComplete="new-password"/></label><p>初期パスワードは本人へ安全な方法で伝え、本人が変更してください。画面やログへ再表示しません。</p></>}
 <label>Role<select aria-label="Role" name="role" defaultValue={editing?.role??'STAFF'}>{['ADMIN','MANAGER','STAFF','VIEWER'].map(r=><option key={r}>{r}</option>)}</select></label><label><input type="checkbox" name="active" defaultChecked={editing?.active??true}/>有効</label>
 <label>店舗範囲<select aria-label="店舗範囲" name="scope" defaultValue={editing?.scope??'ASSIGNED'}><option value="ASSIGNED">選択した店舗のみ</option><option value="ALL">全店舗（明示的な付与）</option></select></label><fieldset><legend>店舗アクセス</legend>{['MOUNTAIN_BASE','ONSEN_BASE'].map(s=><label key={s}><input type="checkbox" name="store" value={s} defaultChecked={editing?.storeIds.includes(s)??false}/>{s}</label>)}</fieldset>
 <fieldset><legend>個別Permission</legend>{(['INVENTORY_VIEW','INVENTORY_EDIT','STAFF_MANAGE','HOLD_VIEW','HOLD_EDIT','TRANSFER_VIEW','TRANSFER_PLAN','TRANSFER_DISPATCH','TRANSFER_RECEIVE','QUOTE_VIEW','QUOTE_CREATE','PRICE_EDIT','BOOKING_VIEW','BOOKING_CREATE','RENTAL_CHECKOUT','RENTAL_RETURN','RENTAL_AMEND','REFUND_OVERRIDE','INVENTORY_RECONCILE'] as const).map(p=><label key={p}>{{INVENTORY_VIEW:'台帳の閲覧',INVENTORY_EDIT:'台帳の登録・更新',STAFF_MANAGE:'スタッフ管理',HOLD_VIEW:'期間在庫・自分のHOLD閲覧',HOLD_EDIT:'自分のHOLD取得・変更',TRANSFER_VIEW:'店舗間移動の閲覧',TRANSFER_PLAN:'移動計画の確保・取消',TRANSFER_DISPATCH:'元店舗からの発送',TRANSFER_RECEIVE:'移動先での受領・準備完了',QUOTE_VIEW:'自分の非公開見積閲覧',QUOTE_CREATE:'自分の非公開見積作成',PRICE_EDIT:'開発用料金版の設定（全店ADMINのみ）',BOOKING_VIEW:'開発予約の閲覧',BOOKING_CREATE:'開発予約の作成',RENTAL_CHECKOUT:'開発用受付・貸出',RENTAL_RETURN:'開発用返却・検品',RENTAL_AMEND:'予約延長・商品交換',REFUND_OVERRIDE:'例外返金依頼（明示付与）',INVENTORY_RECONCILE:'棚卸差異の確定（明示付与）'}[p]}<select aria-label={{INVENTORY_VIEW:'台帳の閲覧',INVENTORY_EDIT:'台帳の登録・更新',STAFF_MANAGE:'スタッフ管理',HOLD_VIEW:'期間在庫・自分のHOLD閲覧',HOLD_EDIT:'自分のHOLD取得・変更',TRANSFER_VIEW:'店舗間移動の閲覧',TRANSFER_PLAN:'移動計画の確保・取消',TRANSFER_DISPATCH:'元店舗からの発送',TRANSFER_RECEIVE:'移動先での受領・準備完了',QUOTE_VIEW:'自分の非公開見積閲覧',QUOTE_CREATE:'自分の非公開見積作成',PRICE_EDIT:'開発用料金版の設定（全店ADMINのみ）',BOOKING_VIEW:'開発予約の閲覧',BOOKING_CREATE:'開発予約の作成',RENTAL_CHECKOUT:'開発用受付・貸出',RENTAL_RETURN:'開発用返却・検品',RENTAL_AMEND:'予約延長・商品交換',REFUND_OVERRIDE:'例外返金依頼（明示付与）',INVENTORY_RECONCILE:'棚卸差異の確定（明示付与）'}[p]} name={p} defaultValue={editing?.permissions[p]===undefined?'default':editing.permissions[p]?'allow':'deny'}><option value="default">Roleの標準</option><option value="allow">付与</option><option value="deny">剥奪</option></select></label>)}</fieldset><p>STAFF / VIEWERの標準は台帳閲覧のみ。返金依頼は明示付与のみ。provider送信は未接続。料金版設定は全店ADMINへの明示付与が必要で、本番価格は公開しません。</p><button type="submit" disabled={conflict||saving}>スタッフ設定を保存</button><button type="button" onClick={()=>setEditing(undefined)}>閉じる</button></form>}
 <ul className="staff-cards">{items.map(s=><li key={s.id}><h2>{s.displayName}</h2><p>{s.email}</p><p>{s.active?'有効':'無効'} · {s.role} · {s.scope==='ALL'?'全店舗':s.storeIds.join(' / ')}</p><button onClick={()=>{setEditing(s);setConflict(false);setError('');}} aria-label={`スタッフを編集：${s.displayName}`}>設定を編集</button></li>)}</ul></main>;
}
