 'use client';
import {useEffect,useRef,useState} from 'react';
import {StaffSessionBoundary,invalidateStaffView} from './StaffSessionBoundary';
import type {Permission} from '../../../../packages/auth/src/staff-auth';
import type {StoreId} from '../../../../packages/contracts/src/ledger';
import './holds.css';
type Stock={id:string;family:string;store_id:string;quantity:number;size:string;name:string};
type Piece={id:string;line_key:string;asset_id:string|null;source_pole_id:string|null;state:string;ordinal:number};
type Batch={id:string;source_store:string;destination_store:string;scheduled_date:string;state:string;version:number;issue:string|null;late?:boolean;pieces?:Piece[];affectedHolds?:{id:string;transfer_attention:string|null}[]};
type Pending={path:string;body:{requestKey:string;input:unknown}};
const pendingKey='zao-rental-transfer-pending-v1';
const errors:Record<string,string>={BATCH_CLOSED:'この便には追加できません。未発送の便と日付を確認してください。',TRANSFER_CONFLICT:'ほかの確保または移動と競合しました。最新の記録を確認してください。',SOURCE_PROMISE_CONFLICT:'元店舗の予約に必要な用品です。別の用品を選択してください。',SOURCE_NOT_RETURNED_OR_READY:'未返却または準備確認が必要な用品を含むため発送できません。',DISPATCH_NOT_ALLOWED:'発送可能な日付・17時以降・便の状態を確認してください。',STALE_SELECTION:'ほかの操作で対象が変わりました。詳細を再読込してください。',INVALID_READY_ESTIMATE:'準備完了の見込みと必要期限の前後関係を確認してください。',INVALID_INPUT:'入力項目を確認してください。',INVALID_DATE:'有効な日付を入力してください。',INVALID_TIME:'有効な日本時間の日時を入力してください。',INVALID_ID:'用品を選択してください。',STOCK_NOT_READY:'元店舗で準備済みの用品を選択してください。',STOCK_CONSTRAINED:'整備・貸出などの制約があります。現物と予定を確認してください。'};
function recover(stamp:string){try{const raw=sessionStorage.getItem(pendingKey);if(!raw)return {pending:null,blocked:false};const v=JSON.parse(raw);if(v.stamp!==stamp){sessionStorage.removeItem(pendingKey);return {pending:null,blocked:false};}if(typeof v.path!=='string'||!/^$|^\/[a-f0-9-]{36}\/(add|dispatch|receive|ready|cancel|issue)$/.test(v.path)||typeof v.body?.requestKey!=='string')throw 0;return {pending:{path:v.path,body:v.body} as Pending,blocked:false};}catch{return {pending:null,blocked:true};}}
export function TransferWorkspace(p:{stamp:string;stores:StoreId[];permissions:Permission[]}){return <StaffSessionBoundary stamp={p.stamp}><Workspace {...p}/></StaffSessionBoundary>;}
function Workspace({stamp,stores,permissions}:{stamp:string;stores:StoreId[];permissions:Permission[]}){
 const [initial]=useState(()=>recover(stamp)),[pending,setPending]=useState<Pending|null>(initial.pending),[storageBlocked,setStorageBlocked]=useState(initial.blocked),[busy,setBusy]=useState(false),[message,setMessage]=useState(initial.pending?'前回の結果が未確認です。同じ要求を照合してください。':''),[batches,setBatches]=useState<Batch[]>([]),[selected,setSelected]=useState<Batch|null>(null),[options,setOptions]=useState<Stock[]>([]),[source,setSource]=useState(stores[0]??'MOUNTAIN_BASE'),[destination,setDestination]=useState<StoreId>(source==='MOUNTAIN_BASE'?'ONSEN_BASE':'MOUNTAIN_BASE'),[date,setDate]=useState(''),[ready,setReady]=useState(''),[needed,setNeeded]=useState(''),[basis,setBasis]=useState(''),[stock,setStock]=useState(''),[quantity,setQuantity]=useState(1),[selection,setSelection]=useState<string[]>([]),[reason,setReason]=useState(''),[pairCount,setPairCount]=useState(1);
 const generation=useRef(0),alive=useRef(true);useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const blocked=busy||Boolean(pending)||storageBlocked,can=(permission:Permission)=>permissions.includes(permission);
 async function call(path:string,body?:unknown){const r=await fetch('/api/transfers'+path,{cache:'no-store',method:body?'POST':'GET',headers:{'content-type':'application/json','x-zao-session':stamp},...(body?{body:JSON.stringify(body)}:{})});const v=await r.json();if([401,403].includes(r.status)||v.error==='SESSION_CHANGED'){invalidateStaffView();throw new Error('SESSION_CHANGED');}if(!r.ok)throw Object.assign(new Error(v.error),{definite:r.status<500});return v;}
 useEffect(()=>{let current=true;Promise.all([call(''),call('/options')]).then(([b,o])=>{if(current){setBatches(b);setOptions(o);}}).catch(()=>{if(current)setMessage('読込できませんでした');});return()=>{current=false;};},[stamp]); // eslint-disable-line react-hooks/exhaustive-deps
 async function choose(id:string){const n=++generation.current;setBusy(true);try{const b=await call('/'+id);if(alive.current&&n===generation.current){setSelected(b);setSelection([]);}}catch{setMessage('詳細を読込できませんでした');}finally{if(alive.current&&n===generation.current)setBusy(false);}}
 async function send(p:Pending){try{sessionStorage.setItem(pendingKey,JSON.stringify({stamp,...p}));}catch{setStorageBlocked(true);setMessage('要求を保存できないため変更を停止しました');return;}
  setPending(p);setBusy(true);const n=++generation.current;try{const result=await call(p.path,p.body);if(!alive.current||n!==generation.current)return;sessionStorage.removeItem(pendingKey);setPending(null);setSelected(result.batch);setSelection([]);setMessage(result.replayed?'元の要求を照合しました':'移動記録を保存しました');try{const b=await call('');if(alive.current&&n===generation.current)setBatches(b);}catch{if(alive.current&&n===generation.current)setMessage('移動記録は保存済みです。一覧を再読込してください。');}
  }catch(e){if(alive.current&&n===generation.current){if((e as {definite?:boolean}).definite){try{sessionStorage.removeItem(pendingKey);setPending(null);}catch{setStorageBlocked(true);}}setMessage((e as Error).message==='SESSION_CHANGED'?'セッションを再確認してください':(e as {definite?:boolean}).definite?(errors[(e as Error).message]??'処理を拒否しました。入力と最新の記録を確認してください。'):'結果未確認です。同じ要求キーで照合してください。');}}finally{if(alive.current&&n===generation.current)setBusy(false);}
 }
 function operation(op:string,input:unknown={}){void send({path:selected?'/'+selected.id+'/'+op:'',body:{requestKey:crypto.randomUUID(),input}});}
 const chosen=options.find(x=>x.id===stock);const line=chosen?.family==='POLE'?{poleId:stock,quantity}:{assetId:stock};
 return <main className="holds"><header><p>ZAO Rental · 開発用実DB</p><h1>店舗間の移動</h1><nav><a href="/staff/ledger">台帳へ</a> · <a href="/staff/holds">期間在庫へ</a> · <a href="/staff/logout">ログアウト</a></nav></header>
 <p>17時便の移動予定と実所在地は別の記録です。10分後の自動受領はありません。受領後も準備完了の確認が必要です。左右同一IDは1組＝1 Asset、ポールはサイズ別ペア数量です。</p>
 <fieldset disabled={blocked||!can('TRANSFER_PLAN')}><legend>移動計画</legend><div className="hold-grid"><label>元店舗<select aria-label="元店舗" value={source} onChange={e=>{setSource(e.target.value as StoreId);setStock('');}}>{stores.map(s=><option key={s}>{s}</option>)}</select></label><label>移動先<select aria-label="移動先" value={destination} onChange={e=>setDestination(e.target.value as StoreId)}>{stores.map(s=><option key={s}>{s}</option>)}</select></label><label>17時便の日付<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>準備完了の見込み（日本時間）<input type="datetime-local" value={ready} onChange={e=>setReady(e.target.value)}/></label><label>必要期限（日本時間）<input type="datetime-local" value={needed} onChange={e=>setNeeded(e.target.value)}/></label><label>計画根拠・運搬と準備の確認<input maxLength={160} value={basis} onChange={e=>setBasis(e.target.value)}/></label><label>対象用品<select aria-label="対象用品" value={stock} onChange={e=>setStock(e.target.value)}><option value="">選択</option>{options.filter(x=>x.store_id===source).map(x=><option key={x.id} value={x.id}>{x.name} · {x.size} · {x.id} · 台帳 {x.quantity}</option>)}</select></label>{chosen?.family==='POLE'&&<label>ポール数量（ペア）<input type="number" min={1} max={100} value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label>}</div>
 <p>見込みは担当者が運搬・積込・準備の成立を確認して入力します。未確認の時間や臨時便を約束しないでください。</p><button onClick={()=>void send({path:'',body:{requestKey:crypto.randomUUID(),input:{sourceStore:source,destinationStore:destination,scheduledDate:date,plannedReadyAt:ready+':00+09:00',neededBy:needed+':00+09:00',basis,lines:[line]}}})}>計画を確保する</button>{selected&&<button disabled={selected.state!=='PLANNED'} onClick={()=>operation('add',{lines:[line]})}>選択した便に用品を追加</button>}</fieldset>
 {pending&&!busy&&<button disabled={storageBlocked} onClick={()=>void send(pending)}>同じ要求を照合・再送</button>}<p role="status">{storageBlocked?'保存領域を確認できないため変更停止。':message}</p>
 <section><h2>移動一覧</h2>{batches.map(b=><button disabled={blocked} key={b.id} onClick={()=>void choose(b.id)}>{b.scheduled_date} · {b.source_store} → {b.destination_store} · {b.state} · {b.id.slice(0,8)}</button>)}</section>
 {selected&&<section aria-label="移動詳細"><h2>移動記録</h2><p>{selected.id} / {selected.state} / 版 {selected.version}</p><p>{selected.source_store} → {selected.destination_store}</p>{(selected.issue||selected.late)&&<p role="alert">要対応：{selected.issue??'準備見込み時刻を超過'}</p>}<fieldset disabled={blocked}><legend>受領・準備完了の対象</legend>{selected.pieces?.filter(p=>p.asset_id).map(p=><label key={p.id}><input type="checkbox" aria-label={'移動明細 '+p.id} checked={selection.includes(p.id)} onChange={e=>setSelection(e.target.checked?[...selection,p.id]:selection.filter(i=>i!==p.id))}/>{p.asset_id?'Asset '+p.asset_id:'ポール '+p.source_pole_id+'（ペア数量の '+p.ordinal+' 番目）'} — {p.state}</label>)}
 {[...new Set(selected.pieces?.filter(p=>p.source_pole_id).map(p=>p.line_key))].map(key=>{const line=selected.pieces!.filter(p=>p.line_key===key);const transit=line.filter(p=>p.state==='IN_TRANSIT'),received=line.filter(p=>p.state==='RECEIVED');return <section key={key} aria-label="ポール数量明細"><p>ポール台帳 {line[0]!.source_pole_id} / 計画 {line.length} ペア / 運搬中 {transit.length} / 検品待ち {received.length} / 準備完了 {line.filter(p=>p.state==='READY').length}</p><label>今回のポールペア数<input type="number" min={1} max={100} value={pairCount} onChange={e=>setPairCount(Number(e.target.value))}/></label><button disabled={!can('TRANSFER_RECEIVE')||!stores.includes(selected.destination_store as StoreId)||!Number.isInteger(pairCount)||pairCount<1||pairCount>transit.length} onClick={()=>operation('receive',{pieceIds:transit.slice(0,pairCount).map(p=>p.id)})}>ポール数量を実受領</button><button disabled={!can('TRANSFER_RECEIVE')||!stores.includes(selected.destination_store as StoreId)||!Number.isInteger(pairCount)||pairCount<1||pairCount>received.length} onClick={()=>operation('ready',{pieceIds:received.slice(0,pairCount).map(p=>p.id)})}>ポール数量の準備完了</button></section>;})}
 <div className="hold-actions"><button disabled={selected.state!=='PLANNED'||Boolean(selected.issue)||!can('TRANSFER_DISPATCH')||!stores.includes(selected.source_store as StoreId)} onClick={()=>operation('dispatch')}>計画の全品を実発送</button><button disabled={!can('TRANSFER_RECEIVE')||!stores.includes(selected.destination_store as StoreId)||!selection.length} onClick={()=>operation('receive',{pieceIds:selection})}>選択分を実受領</button><button disabled={!can('TRANSFER_RECEIVE')||!stores.includes(selected.destination_store as StoreId)||!selection.length} onClick={()=>operation('ready',{pieceIds:selection})}>選択分の準備完了</button><button disabled={selected.state!=='PLANNED'||!can('TRANSFER_PLAN')} onClick={()=>operation('cancel')}>発送前計画を取り消す</button></div><label>要対応の理由<input maxLength={160} value={reason} onChange={e=>setReason(e.target.value)}/></label><button onClick={()=>operation('issue',{reason})}>要対応を記録</button></fieldset><p>受領は事実として記録します。要対応の予約を自動取消・返金しません。</p><ul>{selected.affectedHolds?.map(h=><li key={h.id}>{h.id} {h.transfer_attention??'この移動を参照するHOLD'}</li>)}</ul></section>}</main>;
}
