 'use client';
import {useEffect,useRef,useState} from 'react';
import {StaffSessionBoundary,invalidateStaffView} from './StaffSessionBoundary';
import type {StoreId} from '../../../../packages/contracts/src/ledger';
import './holds.css';
type Pool={id:string;variant_id:string;family:string;size:string;age:string;ready:number;reserved_peak:number;transfer_reserved:number;on_loan:number;returned_pending:number;cleaning:number;today_blocked:number;in_transit:number;unavailable:number;total:number;revision:number};
type Loan={family:string;size:string;age:string;id:string;booking_id:string;member_key:string;requirement_key:string;quantity:number;returned:number;planned_pickup_store:string;actual_pickup_store:string;planned_return_store:string;revision:number};
type Receipt={id:string;actual_store:string;quantity:number;state:string;eligible_on:string;revision:number};
type Transfer={id:string;source_store:string;source_pool_id:string;destination_store:string;quantity:number;received:number;scheduled_at:string;state:string;revision:number;receipts:{id:string;quantity:number;state:string;revision:number}[]};
type Batch={id:string;store_id:string;revision:number;items:{id:string;bookingId:string;requirementKey:string;quantity:number;state:string;error?:string}[]};
type Pending={action:string;body:{requestKey:string;input:unknown}};
const storage='zao-wear-quantity-pending-v1';
export function WearWorkspace(p:{stamp:string;stores:StoreId[]}){return <StaffSessionBoundary stamp={p.stamp}><Workspace {...p}/></StaffSessionBoundary>;}
function recoverWear(stamp:string):{pending:Pending|null;blocked:boolean}{try{const saved=JSON.parse(sessionStorage.getItem(storage)??'null');if(saved?.stamp===stamp&&saved.pending)return {pending:saved.pending,blocked:false};sessionStorage.removeItem(storage);return {pending:null,blocked:false};}catch{return {pending:null,blocked:true};}}
function Workspace({stamp,stores}:{stamp:string;stores:StoreId[]}){
 const [initial]=useState(()=>recoverWear(stamp));
 const [store,setStore]=useState<string>(stores[0]!),[pools,setPools]=useState<Pool[]>([]),[booking,setBooking]=useState(''),[version,setVersion]=useState(1),[loans,setLoans]=useState<Loan[]>([]),[receipts,setReceipts]=useState<Receipt[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[pending,setPending]=useState<Pending|null>(initial.pending),[storageBlocked,setStorageBlocked]=useState(initial.blocked);
 const [transfers,setTransfers]=useState<Transfer[]>([]),[selectedPool,setSelectedPool]=useState(''),[transferDate,setTransferDate]=useState(''),[transferQuantity,setTransferQuantity]=useState(1),[operationReason,setOperationReason]=useState('');
 const [batch,setBatch]=useState<Batch|null>(null),[batchId,setBatchId]=useState('');
 const alive=useRef(true),generation=useRef(0);useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 async function call(path:string,body?:unknown){const response=await fetch('/api/wear'+path,{method:body===undefined?'GET':'POST',cache:'no-store',headers:{'content-type':'application/json','x-zao-session':stamp},...(body===undefined?{}:{body:JSON.stringify(body)})});const data=await response.json();if(response.status===401||response.status===403||data.error==='SESSION_CHANGED'){invalidateStaffView();throw new Error('SESSION_CHANGED');}if(!response.ok)throw Object.assign(new Error(data.error),{definite:response.status<500});return data;}
 async function refresh(token:number){if(transfers.length){const t=await call('/transfers?store='+encodeURIComponent(store));if(alive.current&&token===generation.current)setTransfers(t);}const data=await call('/pools?store='+encodeURIComponent(store));if(alive.current&&token===generation.current)setPools(data.pools);if(booking){const q='?bookingId='+encodeURIComponent(booking)+'&store='+encodeURIComponent(store),[l,r]=await Promise.all([call('/loans'+q),call('/receipts'+q)]);if(alive.current&&token===generation.current){setLoans(l);setReceipts(r);}}}
 useEffect(()=>{let active=true;call('/pools?store='+encodeURIComponent(store)).then(r=>{if(active)setPools(r.pools);}).catch(e=>{if(active)setMessage((e as Error).message);});return()=>{active=false;};},[stamp,store]); // eslint-disable-line react-hooks/exhaustive-deps
 async function send(p:Pending){if(busy)return;try{sessionStorage.setItem(storage,JSON.stringify({stamp,pending:p}));}catch{setStorageBlocked(true);return;}setPending(p);setBusy(true);const token=++generation.current;try{const saved=await call('/'+p.action,p.body);if(!alive.current||token!==generation.current)return;if(p.action==='return-candidate'||p.action==='return-batch-confirm'){setBatch(saved);setBatchId(saved.id);sessionStorage.setItem(storage+'-batch',JSON.stringify({stamp,id:saved.id,store:saved.store_id}));}sessionStorage.removeItem(storage);setPending(null);setMessage('保存済み。返却と再貸出可能性は別の状態です。');await refresh(token);}catch(e){if(alive.current&&token===generation.current){if((e as {definite?:boolean}).definite){sessionStorage.removeItem(storage);setPending(null);}setMessage((e as {definite?:boolean}).definite?'拒否：'+(e as Error).message:'結果未確認。同じ要求を照合してください。');}}finally{if(alive.current&&token===generation.current)setBusy(false);}}
 function mutate(action:string,input:unknown){void send({action,body:{requestKey:crypto.randomUUID(),input}});}
 return <main className="holds"><header><p>ZAO RENTAL · 非公開開発用</p><h1>ウェア数量・貸出返却</h1><nav><a href="/preview/integrated">統合予約</a> · <a href="/preview/rental">決済照合・予約QR</a> · <a href="/staff/logout">ログアウト</a></nav></header><p>衣類に個体ID・QRはありません。予約番号で貸出を確認し、上・下それぞれの数量を受領します。約200着の内訳は未確認です。</p>
 <fieldset disabled={busy||!!pending}><label>実際の受領・表示店舗<select value={store} onChange={e=>{generation.current++;setStore(e.target.value);setPools([]);setLoans([]);setReceipts([]);setBatch(null);setBatchId('');setTransfers([]);setSelectedPool('');}}>{stores.map(s=><option key={s}>{s}</option>)}</select></label></fieldset>
 <section aria-label="ウェア数量"><h2>物理数量（HOLDを加算しません）</h2>{pools.map(p=><article key={p.id}><h3>{p.family==='WEAR_JACKET'?'上着':'パンツ'} {p.size} / {p.age}</h3><p>READY {p.ready} / 貸出中 {p.on_loan} / 返却受領 {p.returned_pending} / 洗浄 {p.cleaning} / 同日保護 {p.today_blocked} / 運搬中 {p.in_transit} / 利用不可 {p.unavailable} / 合計 {p.total}</p><p>論理保護（日別最大）{p.reserved_peak} / 移動計画の保護 {p.transfer_reserved}。期間別の予約可能数とは異なります。</p>{p.reserved_peak+p.transfer_reserved>p.ready&&<p role="alert">将来の約束に対する実準備・所在地の確認が必要です。確保は消していません。</p>}</article>)}</section>
 <fieldset disabled={busy||!!pending||storageBlocked}><legend>予約・貸出サイクルを確認</legend><label>予約番号<input value={booking} onChange={e=>{generation.current++;setBooking(e.target.value);setLoans([]);setReceipts([]);}}/></label><button onClick={()=>{const token=++generation.current;void refresh(token).catch(e=>{if(alive.current&&token===generation.current)setMessage((e as Error).message);});}}>貸出を読込</button><label>確認済み開発予約の版<input type="number" min="1" value={version} onChange={e=>setVersion(Number(e.target.value))}/></label><button onClick={()=>mutate('checkout',{bookingId:booking,expectedBookingVersion:version,store,reason:'SYNTHETIC development wear checkout'})}>ウェア数量を貸出記録</button>
 {loans.map(l=><article key={l.id} aria-label={'ウェア貸出 '+l.requirement_key}><h3>{l.member_key} / {l.requirement_key} / {l.size} / {l.age}</h3><p>貸出 {l.quantity} / 返却済み {l.returned} / 未返却 {l.quantity-l.returned}</p><p>予定受取 {l.planned_pickup_store} / 実受取 {l.actual_pickup_store} / 予定返却 {l.planned_return_store}</p>{l.returned<l.quantity&&<button onClick={()=>mutate('receive',{loanId:l.id,expectedRevision:l.revision,store,quantity:1,reason:'SYNTHETIC actual quantity receipt',unresolvedId:null})}>1着を受領：{l.requirement_key}</button>}{l.returned<l.quantity&&<button onClick={()=>mutate('return-candidate',{batchId:batch?.id??null,expectedRevision:batch?.revision??null,loanId:l.id,expectedLoanRevision:l.revision,quantity:1,store,reason:'SYNTHETIC saved quantity return candidate'})}>返却候補へ追加：{l.requirement_key}</button>}</article>)}
 <section aria-label="保存した返却候補"><h2>複数予約の返却候補</h2><p>候補の保存では返却を確定しません。受領数量を確認して一括確定してください。古い候補は別の貸出へ付け替えません。</p><label>返却バッチ番号<input value={batchId} onChange={e=>{setBatchId(e.target.value);setBatch(null);}}/></label><button onClick={()=>{const token=++generation.current;void call('/return-batch?batchId='+encodeURIComponent(batchId)+'&store='+encodeURIComponent(store)).then(b=>{if(alive.current&&token===generation.current)setBatch(b);}).catch(e=>setMessage((e as Error).message));}}>保存した候補を再読込</button><button onClick={()=>{try{const saved=JSON.parse(sessionStorage.getItem(storage+'-batch')??'null');if(saved?.stamp===stamp&&saved.store===store){setBatchId(saved.id);setMessage('バッチ番号を復元しました。再読込して最新状態を確認してください。');}else setMessage('この本人・店舗の保存候補はありません。');}catch{setMessage('保存候補の復元に失敗しました。');}}}>前回のバッチ番号を復元</button>{batch&&<><p>保存済み候補 {batch.id}</p>{batch.items.map(i=><p key={i.id}>{i.bookingId.slice(-6)} / {i.requirementKey} / {i.quantity}着 / {i.state}{i.error?' / '+i.error:''}</p>)}<button disabled={!batch.items.some(i=>i.state==='CANDIDATE')} onClick={()=>mutate('return-batch-confirm',{batchId:batch.id,expectedRevision:batch.revision,store,reason:'SYNTHETIC confirmed physical quantities'})}>候補の数量をまとめて返却確定</button></>}</section>
 {receipts.map(r=><article key={r.id} aria-label={'返却受領 '+r.id}><p>{r.actual_store} / {r.quantity}着 / {r.state} / 同日保護の解除日 {String(r.eligible_on).slice(0,10)}</p>{r.actual_store===store&&r.state!=='READY'&&<button onClick={()=>mutate('cleaning',{receiptId:r.id,expectedRevision:r.revision,operation:r.state==='RETURNED_PENDING'?'START':r.state==='CLEANING'?'COMPLETE':'RELEASE_NEXT_DAY',confirmedReady:r.state!=='RETURNED_PENDING',reason:'SYNTHETIC explicit care confirmation'})}>{r.state==='RETURNED_PENDING'?'洗浄開始':r.state==='CLEANING'?'実際の乾燥・検品完了を記録':'翌日以降のREADY反映'}：{r.id.slice(-6)}</button>}</article>)}
 </fieldset><fieldset disabled={busy||!!pending||storageBlocked}><legend>数量移動・予約不明の受領</legend><p>確定操作には実際の数量・受領店舗と理由が必要です。移動予定だけで到着数は増えません。</p><label>対象サイズの数量プール<select value={selectedPool} onChange={e=>setSelectedPool(e.target.value)}><option value="">選択してください</option>{pools.map(p=><option key={p.id} value={p.id}>{p.family} {p.size} {p.age}</option>)}</select></label><label>操作数量<input type="number" min="1" max="1000" value={transferQuantity} onChange={e=>setTransferQuantity(Number(e.target.value))}/></label><label>数量操作の理由<input maxLength={160} value={operationReason} onChange={e=>setOperationReason(e.target.value)}/></label><label>17時便の予定日<input type="date" value={transferDate} onChange={e=>setTransferDate(e.target.value)}/></label><button disabled={!selectedPool||!operationReason.trim()||!transferDate} onClick={()=>{const source=pools.find(p=>p.id===selectedPool);if(source)mutate('transfer-plan',{poolId:source.id,expectedRevision:source.revision,destinationStore:store==='MOUNTAIN_BASE'?'ONSEN_BASE':'MOUNTAIN_BASE',quantity:transferQuantity,scheduledDate:transferDate,reason:operationReason});}}>もう一方の店舗への移動を計画</button><button disabled={!selectedPool||!operationReason.trim()} onClick={()=>{const p=pools.find(p=>p.id===selectedPool);if(p)mutate('unresolved',{variantId:p.variant_id,store,quantity:transferQuantity,reason:operationReason});}}>予約不明として受領記録（READYへ加算しない）</button><button onClick={()=>{const token=++generation.current;void call('/transfers?store='+encodeURIComponent(store)).then(t=>{if(alive.current&&token===generation.current)setTransfers(t);}).catch(e=>{if(alive.current&&token===generation.current)setMessage((e as Error).message);});}}>この店舗の数量移動を再読込</button>{transfers.map(t=><article key={t.id} aria-label={'数量移動 '+t.id}><p>{t.source_store} → {t.destination_store} / {t.quantity}着 / 受領済 {t.received} / {t.state}</p><p>予定出発 {t.scheduled_at} / 実受領を自動入力しません。</p>{t.state==='PLANNED'&&t.source_store===store&&<button disabled={!operationReason.trim()} onClick={()=>mutate('transfer',{transferId:t.id,expectedRevision:t.revision,operation:'DISPATCH',quantity:null,reason:operationReason})}>実際に発送：{t.id.slice(-6)}</button>}{t.state==='IN_TRANSIT'&&t.destination_store===store&&<button disabled={!operationReason.trim()} onClick={()=>mutate('transfer',{transferId:t.id,expectedRevision:t.revision,operation:'RECEIVE',quantity:transferQuantity,reason:operationReason})}>実際に受領：{t.id.slice(-6)}</button>}{t.receipts.filter(r=>r.state==='RETURNED_PENDING'&&t.destination_store===store).map(r=><button key={r.id} disabled={!operationReason.trim()} onClick={()=>mutate('transfer-ready',{receiptId:r.id,expectedRevision:r.revision,confirmedReady:true,reason:operationReason})}>受領分の実READY確認：{r.quantity}着</button>)}</article>)}</fieldset>{pending&&!busy&&<button onClick={()=>void send(pending)}>同じ保存要求を照合</button>}<p role="status">{storageBlocked?'保存領域未確認のため操作停止':message}</p><p>返却で自動返金はしません。道具の個体スキャン返却との一括結合は、別途記録した権限境界が未接続です。</p></main>;
}
