import seed from '../../../config/pricing/zao-2026-27-v1.draft.json';
import {HoldError,parseConditions,normalizePeriod,utcDate,type HoldConditions} from './hold';
export class PricingError extends HoldError {}
export const PRICE_PRODUCTS=seed.products.map(p=>({key:p.product_key,sport:p.sport,kind:p.kind,age:p.age_category,tier:p.tier}));
export const DURATIONS=['HALF_DAY_AM','HALF_DAY_PM',...Array.from({length:10},(_,i)=>`DAY_${i+1}`)];
export type PriceTable=Record<string,Record<string,number>>;
export const INITIAL_TABLE:PriceTable=Object.fromEntries(seed.products.map(p=>[p.product_key,{...p.prices_jpy}]));
export const PRIVATE_QUOTE_TTL_SECONDS=600; // Development preview only; production duration remains unapproved.
export type QuoteInput={conditions:HoldConditions;holdId:string|null;couponCode:string|null;wantAdvance:boolean};
export type CouponTerms={code:string;validFrom:string;validUntil:string;storeBasis:'PICKUP_STORE';stores:string[];products:string[];kind:'PERCENT_BPS'|'FIXED_JPY';value:number;minimumJpy:number;minimumBasis:'CART_SUBTOTAL'|'ELIGIBLE_SUBTOTAL';maximumDiscountJpy:number;advanceCombination:'ALLOW'|'DENY'|'UNSET';maxActiveReservations:number|null};
export function exact(value:unknown,keys:string[]):Record<string,unknown>{if(!value||typeof value!=='object'||Array.isArray(value)||Object.keys(value).some(k=>!keys.includes(k))||keys.some(k=>!(k in value)))throw new PricingError('INVALID_INPUT');return value as Record<string,unknown>;}
export function id(value:unknown):asserts value is string{if(typeof value!=='string'||!/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/.test(value))throw new PricingError('INVALID_ID');}
export function money(value:unknown,max=100_000_000):asserts value is number{if(!Number.isSafeInteger(value)||Number(value)<0||Number(value)>max)throw new PricingError('INVALID_MONEY');}
export function timestamp(value:unknown):string{if(typeof value!=='string'||!/^20\d\d-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d{1,3})?(Z|[+-]\d\d:\d\d)$/.test(value)||!Number.isFinite(Date.parse(value)))throw new PricingError('INVALID_TIME');utcDate(value.slice(0,10));return new Date(value).toISOString();}
export function code(value:unknown):string{if(typeof value!=='string'||!/^[A-Za-z0-9-]{1,32}$/.test(value.trim()))throw new PricingError('INVALID_COUPON');return value.trim().toUpperCase();}
export function parseQuote(value:unknown):QuoteInput{const v=exact(value,['conditions','holdId','couponCode','wantAdvance']);const conditions=parseConditions(v.conditions);if(v.holdId!==null)id(v.holdId);if(typeof v.wantAdvance!=='boolean')throw new PricingError('INVALID_INPUT');return {conditions,holdId:v.holdId as string|null,couponCode:v.couponCode===null?null:code(v.couponCode),wantAdvance:v.wantAdvance};}
export function validateTable(table:PriceTable){if(!table||typeof table!=='object'||Object.keys(table).sort().join()!==PRICE_PRODUCTS.map(p=>p.key).sort().join())throw new PricingError('INVALID_PRICE_TABLE');for(const product of PRICE_PRODUCTS){const entries=table[product.key];if(!entries||Object.keys(entries).sort().join()!==[...DURATIONS].sort().join())throw new PricingError('INVALID_PRICE_TABLE');for(const d of DURATIONS)money(entries[d]);}return table;}
export function parseCoupon(value:unknown):CouponTerms{const v=exact(value,['code','validFrom','validUntil','storeBasis','stores','products','kind','value','minimumJpy','minimumBasis','maximumDiscountJpy','advanceCombination','maxActiveReservations']);if(v.storeBasis!=='PICKUP_STORE')throw new PricingError('UNRESOLVED_STORE_BASIS');v.code=code(v.code);v.validFrom=timestamp(v.validFrom);v.validUntil=timestamp(v.validUntil);if(String(v.validFrom)>=String(v.validUntil))throw new PricingError('INVALID_COUPON');for(const k of ['stores','products'] as const){const allowed=k==='stores'?['MOUNTAIN_BASE','ONSEN_BASE']:PRICE_PRODUCTS.map(p=>p.key);if(!Array.isArray(v[k])||!v[k].length||new Set(v[k]).size!==v[k].length||v[k].some(x=>typeof x!=='string'||!allowed.includes(x)))throw new PricingError('INVALID_COUPON');}if(!['PERCENT_BPS','FIXED_JPY'].includes(v.kind as string)||!['CART_SUBTOTAL','ELIGIBLE_SUBTOTAL'].includes(v.minimumBasis as string)||!['ALLOW','DENY','UNSET'].includes(v.advanceCombination as string))throw new PricingError('INVALID_COUPON');money(v.value,v.kind==='PERCENT_BPS'?10000:100_000_000);money(v.minimumJpy);money(v.maximumDiscountJpy);if(v.maxActiveReservations!==null&&(!Number.isInteger(v.maxActiveReservations)||Number(v.maxActiveReservations)<1||Number(v.maxActiveReservations)>100000))throw new PricingError('INVALID_COUPON');return v as CouponTerms;}
export function duration(c:HoldConditions){const p=normalizePeriod(c.period);return c.period.slot==='AM'?'HALF_DAY_AM':c.period.slot==='PM'?'HALF_DAY_PM':`DAY_${p.days}`;}
export function productKey(m:HoldConditions['members'][number]){if(m.age==='KIDS'&&m.tier==='PREMIUM')throw new PricingError('PRODUCT_NOT_OFFERED');if(m.product!=='SINGLE')return `${m.product}_${m.age}_${m.tier}`;const f=m.items[0]!.family;const sport=f==='SNOWBOARD'||f==='SNOWBOARD_BOOT'?'SNOWBOARD':'SKI';const kind=f==='SKI'||f==='SNOWBOARD'?'EQUIPMENT_ONLY':f==='POLE'?'POLES_ONLY':'BOOTS_ONLY';return `${sport}_${kind}_${m.age}_${kind==='EQUIPMENT_ONLY'?m.tier:'STANDARD'}`;}
export function advanceCutoff(startDate:string){return new Date(utcDate(startDate)-18*3600000);}
// A trusted future payment integration must supply verified completion evidence. Quote creation is never that evidence.
export function advanceQualification(startDate:string,verifiedCompletedAt:Date|null){return !verifiedCompletedAt?'UNVERIFIED':verifiedCompletedAt<=advanceCutoff(startDate)?'QUALIFIED':'NOT_QUALIFIED';}
export function halfUpBps(amount:number,bps:number){money(amount,2_000_000_000);money(bps,10000);return Number((BigInt(amount)*BigInt(bps)+5000n)/10000n);}
export function calculate(table:PriceTable,input:QuoteInput,now:Date,coupon:CouponTerms|null){validateTable(table);const d=duration(input.conditions);const items=input.conditions.members.map(m=>{const key=productKey(m),unit=table[key]?.[d];if(unit===undefined)throw new PricingError('PRODUCT_NOT_OFFERED');return {memberKey:m.key,productKey:key,duration:d,quantity:1,unitJpy:unit,lineJpy:unit};});const subtotal=items.reduce((n,i)=>n+i.lineJpy,0),cutoff=advanceCutoff(input.conditions.period.startDate),advanceEstimated=input.wantAdvance&&now<=cutoff;
 let couponDiscount=0;if(input.couponCode&&!coupon)throw new PricingError('COUPON_NOT_FOUND');if(coupon){if(input.couponCode!==coupon.code||now<new Date(coupon.validFrom)||now>=new Date(coupon.validUntil)||!coupon.stores.includes(input.conditions.pickupStore))throw new PricingError('COUPON_NOT_APPLICABLE');const eligible=items.filter(i=>coupon.products.includes(i.productKey)).reduce((n,i)=>n+i.lineJpy,0);if(!eligible||(coupon.minimumBasis==='CART_SUBTOTAL'?subtotal:eligible)<coupon.minimumJpy)throw new PricingError('COUPON_NOT_APPLICABLE');if(advanceEstimated&&coupon.advanceCombination!=='ALLOW')throw new PricingError(coupon.advanceCombination==='UNSET'?'PROMOTION_POLICY_UNRESOLVED':'DISCOUNTS_NOT_COMBINABLE');couponDiscount=Math.min(eligible,coupon.maximumDiscountJpy,coupon.kind==='PERCENT_BPS'?halfUpBps(eligible,coupon.value):coupon.value);}
 const afterCoupon=subtotal-couponDiscount,advanceDiscount=advanceEstimated?halfUpBps(afterCoupon,500):0;
 return {calculationPolicyVersion:'E08_PRIVATE_CALC_V1' as const,advancePromotionVersion:'ADVANCE_5_PERCENT_PREV_DAY_1500_JST_V1' as const,items,subtotalJpy:subtotal,couponDiscountJpy:couponDiscount,advanceDiscountJpy:advanceDiscount,totalJpy:afterCoupon-advanceDiscount,currency:'JPY' as const,taxDisplayBasis:'PENDING_OWNER_CONFIRMATION' as const,taxAddedJpy:0,rounding:'WHOLE_JPY_HALF_UP' as const,adjustmentOrder:'EXPLICIT_TABLE_COUPON_THEN_ADVANCE' as const,advance:{status:advanceEstimated?'ESTIMATED_PAYMENT_NOT_VERIFIED':'NOT_ESTIMATED',cutoff:cutoff.toISOString(),qualificationEvent:'PAYMENT_COMPLETED'},coupon:{status:coupon?'ESTIMATED_NOT_RESERVED':'NONE',code:coupon?.code??null},chargeReady:false as const,meaning:'PRIVATE_ESTIMATE_NOT_INVOICE_PAYMENT_OR_STOCK' as const};
}
export type FrozenPriceSnapshot=Readonly<ReturnType<typeof calculate>&{priceBookId:string;activationId:string;conditions:HoldConditions;expiresAt:string;fingerprint:string}>;
