import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
import {mkdir} from 'node:fs/promises';
import {chromium,expect,type BrowserContext} from '@playwright/test';
import {startDevelopmentApp} from '../../scripts/development-app';
import {bootstrapDevelopmentAdmin} from '../../scripts/bootstrap-staff';
import {seedInventory,fid} from '../inventory/fixture';
let lastPage:import('@playwright/test').Page|undefined;let app:Awaited<ReturnType<typeof startDevelopmentApp>>|undefined;let stage='startup',count=0,failed=false;const browser=await chromium.launch(),password=randomBytes(24).toString('base64url');
async function check(name:string,fn:()=>Promise<void>){stage=name;await fn();count++;console.log('PASS '+name);}
try{
 app=await startDevelopmentApp({built:true});await seedInventory(app.db.pool);await bootstrapDevelopmentAdmin(app.db.pool,{email:'e07-ui-admin@example.invalid',displayName:'合成ADMIN',password});const {origin}=app;
 // Only the disposable DB owner changes this clock dependency. The app roles cannot ALTER it.
 async function clock(value:string){assert.match(value,/^2033-01-0[1-9]T\d\d:\d\d:\d\dZ$/);await app!.db.pool.query(`CREATE OR REPLACE FUNCTION inventory_clock() RETURNS timestamptz LANGUAGE sql VOLATILE AS $$SELECT '${value}'::timestamptz$$`);}
 await clock('2033-01-01T07:50:00Z');for(let i=0;i<100;i++){try{if((await fetch(origin+'/api/health')).ok)break;}catch{}if(i===99)throw new Error('APP_START_TIMEOUT');await new Promise(r=>setTimeout(r,100));}
 async function context(){const c=await browser.newContext({baseURL:origin,viewport:{width:1280,height:960}});c.setDefaultTimeout(10000);return c;}
 async function login(c:BrowserContext,email:string){const p=await c.newPage();await p.goto('/staff/login');await p.getByLabel('メールアドレス',{exact:true}).fill(email);await p.getByLabel('パスワード',{exact:true}).fill(password);await p.getByRole('button',{name:'ログイン',exact:true}).click();await p.waitForURL(origin+'/staff/ledger');return p;}
 const admin=await context(),editor=await context(),anon=await context();const ap=await login(admin,'e07-ui-admin@example.invalid');
 await check('normal ADMIN UI creates scoped staff with explicit transfer permissions; anonymous and default ADMIN rejected',async()=>{
  assert.equal((await anon.request.get('/api/transfers')).status(),401);assert.equal((await admin.request.get('/api/transfers')).status(),403);
  await ap.goto('/staff/users');await ap.getByRole('button',{name:'スタッフを作成',exact:true}).click();const f=ap.getByRole('form',{name:'スタッフ作成'});await f.getByLabel('表示名',{exact:true}).fill('合成移動担当');await f.getByLabel('メールアドレス',{exact:true}).fill('e07-ui-staff@example.invalid');await f.getByLabel('初期パスワード（15〜128文字）').fill(password);for(const store of ['MOUNTAIN_BASE','ONSEN_BASE'])await f.getByLabel(store,{exact:true}).check();for(const label of ['店舗間移動の閲覧','移動計画の確保・取消','元店舗からの発送','移動先での受領・準備完了'])await f.getByLabel(label,{exact:true}).selectOption('allow');await f.getByRole('button',{name:'スタッフ設定を保存'}).click();await expect(ap.getByRole('heading',{name:'合成移動担当',exact:true})).toBeVisible();
 });
 const page=await login(editor,'e07-ui-staff@example.invalid');lastPage=page;let id='',pieceId='';
 await check('normal login -> Next UI -> protected API -> real PostgreSQL plan; failed response reconciles after reload once',async()=>{
  stage='open transfers';await page.goto('/staff/transfers');await expect(page.getByRole('heading',{name:'店舗間の移動',exact:true})).toBeVisible();stage='select source';await page.getByLabel('元店舗',{exact:true}).selectOption('MOUNTAIN_BASE');stage='select destination';await page.getByLabel('移動先',{exact:true}).selectOption('ONSEN_BASE');stage='fill scheduled date';await page.getByLabel('17時便の日付').fill('2033-01-01');await page.getByLabel('準備完了の見込み（日本時間）').fill('2033-01-01T19:00');await page.getByLabel('必要期限（日本時間）').fill('2033-01-02T08:30');await page.getByLabel('計画根拠・運搬と準備の確認').fill('SYNTHETIC test: route, loading and readiness confirmed for fixture');stage='select stock';await page.getByLabel('対象用品',{exact:true}).selectOption(fid(1201));
  let key='';await page.route(origin+'/api/transfers',async route=>{if(route.request().method()!=='POST'){await route.continue();return;}const result=await route.fetch();assert.equal(result.status(),201);const v=await result.json();id=v.batch.id;pieceId=v.batch.pieces[0].id;key=route.request().postDataJSON().requestKey;await route.abort('failed');});
  stage='submit transfer';await page.getByRole('button',{name:'計画を確保する',exact:true}).click();stage='await lost-response recovery';await expect(page.getByRole('button',{name:'同じ要求を照合・再送'})).toBeVisible();await page.unroute(origin+'/api/transfers');await page.reload();await expect(page.getByRole('button',{name:'計画を確保する',exact:true})).toBeDisabled();stage='reconcile original request';await page.getByRole('button',{name:'同じ要求を照合・再送'}).click();await expect(page.getByRole('region',{name:'移動詳細'})).toContainText(id);assert.equal((await app!.db.pool.query('SELECT count(*)::int AS n FROM transfer_requests WHERE request_key=$1',[key])).rows[0].n,1);assert.equal((await app!.db.pool.query('SELECT count(*)::int AS n FROM transfer_batches')).rows[0].n,1);assert.equal((await app!.db.pool.query('SELECT store_id FROM ledger_assets WHERE id=$1',[fid(1201)])).rows[0].store_id,'MOUNTAIN_BASE');
 });
 await check('17:00 test clock; ordinary UI dispatch -> in transit -> actual receive -> preparation -> persistent reload',async()=>{
  await clock('2033-01-01T08:00:00Z');await page.getByRole('button',{name:'計画の全品を実発送',exact:true}).click();await expect(page.getByRole('region',{name:'移動詳細'})).toContainText('IN_TRANSIT');await clock('2033-01-01T08:10:00Z');await page.reload();await page.getByRole('button',{name:new RegExp(id.slice(0,8))}).click();await expect(page.getByRole('region',{name:'移動詳細'})).toContainText('IN_TRANSIT');
  await page.getByLabel('移動明細 '+pieceId,{exact:true}).check();await page.getByRole('button',{name:'選択分を実受領',exact:true}).click();await expect(page.getByRole('region',{name:'移動詳細'})).toContainText('RECEIVED');assert.equal((await app!.db.pool.query('SELECT store_id FROM ledger_assets WHERE id=$1',[fid(1201)])).rows[0].store_id,'ONSEN_BASE');await page.getByLabel('移動明細 '+pieceId,{exact:true}).check();await page.getByRole('button',{name:'選択分の準備完了',exact:true}).click();await expect(page.getByRole('region',{name:'移動詳細'})).toContainText('CLOSED');await page.reload();await page.getByRole('button',{name:new RegExp(id.slice(0,8))}).click();await expect(page.getByRole('region',{name:'移動詳細'})).toContainText('CLOSED');
  const actor=(await app!.db.pool.query("SELECT id FROM staff_users WHERE email='e07-ui-staff@example.invalid'")).rows[0].id;assert.ok((await app!.db.pool.query('SELECT actor FROM transfer_history WHERE batch_id=$1',[id])).rows.every(r=>r.actor===actor));
  await mkdir('.local/screenshots',{recursive:true});await page.screenshot({path:'.local/screenshots/e07-transfer-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'.local/screenshots/e07-transfer-mobile-width.png',fullPage:true});
 });
 await check('normal quantity UI dispatches three PAIRs and partially receives one without individual pole identity',async()=>{
  await clock('2033-01-02T07:50:00Z');const c=await app!.db.pool.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('zao.actor','synthetic-e07-ui',true),set_config('zao.reason','SYNTHETIC pole quantity fixture',true)");await c.query('UPDATE ledger_poles SET quantity=3 WHERE id=$1',[fid(1301)]);await c.query('COMMIT');}finally{c.release();}
  await page.reload();await page.getByLabel('17時便の日付').fill('2033-01-02');await page.getByLabel('準備完了の見込み（日本時間）').fill('2033-01-02T19:00');await page.getByLabel('必要期限（日本時間）').fill('2033-01-03T08:30');await page.getByLabel('計画根拠・運搬と準備の確認').fill('SYNTHETIC pole quantity transport');await page.getByLabel('対象用品',{exact:true}).selectOption(fid(1301));await page.getByLabel('ポール数量（ペア）',{exact:true}).fill('3');await page.getByRole('button',{name:'計画を確保する',exact:true}).click();await expect(page.getByRole('region',{name:'ポール数量明細'})).toContainText('計画 3 ペア');await clock('2033-01-02T08:00:00Z');await page.getByRole('button',{name:'計画の全品を実発送',exact:true}).click();await expect(page.getByRole('region',{name:'ポール数量明細'})).toContainText('運搬中 3');await page.getByLabel('今回のポールペア数').fill('1');await page.getByRole('button',{name:'ポール数量を実受領',exact:true}).click();await expect(page.getByRole('region',{name:'ポール数量明細'})).toContainText('運搬中 2 / 検品待ち 1');await page.getByRole('button',{name:'ポール数量の準備完了',exact:true}).click();await expect(page.getByRole('region',{name:'ポール数量明細'})).toContainText('準備完了 1');assert.equal((await app!.db.pool.query('SELECT quantity FROM ledger_poles WHERE id=$1',[fid(1301)])).rows[0].quantity,0);
  await page.screenshot({path:'.local/screenshots/e07-pole-partial-mobile-width.png',fullPage:true});
 });
 await check('unavailable pending storage stops a new transfer before any network write',async()=>{
  let writes=0;const listener=(r:import('@playwright/test').Request)=>{if(r.method()==='POST'&&r.url().includes('/api/transfers'))writes++;};page.on('request',listener);await page.evaluate(()=>{Storage.prototype.setItem=()=>{throw new DOMException('Unavailable','QuotaExceededError');};});await page.getByRole('button',{name:'計画を確保する',exact:true}).click();await expect(page.getByRole('status')).toContainText('変更停止');assert.equal(writes,0);page.off('request',listener);await page.reload();
 });
 await check('real ordinary API rejects forged actors/CSRF; logout removes session and old-user view',async()=>{
  for(const headers of [{},{origin:'https://untrusted.invalid'}])assert.equal((await editor.request.post('/api/transfers/'+id+'/receive',{headers,data:{requestKey:randomUUID(),input:{pieceIds:[pieceId]}}})).status(),403);
  assert.equal((await editor.request.post('/api/transfers/'+id+'/ready',{headers:{origin},data:{requestKey:randomUUID(),input:{pieceIds:[pieceId]},role:'ADMIN'}})).status(),422);
  await page.getByRole('link',{name:'ログアウト',exact:true}).click();await page.getByRole('button',{name:'ログアウトする',exact:true}).click();await page.waitForURL(origin+'/staff/login');assert.equal((await editor.request.get('/api/transfers')).status(),401);stage='open transfers';await page.goto('/staff/transfers');await expect(page.getByRole('heading',{name:'店舗間移動の利用権限が必要です'})).toBeVisible();
 });
 console.log(`E07 normal UI/API/PostgreSQL: ${count} passed; 0 skipped. Real synthetic password authentication; owned DB operational clock fixed. No mocked UI data/API responses except deliberate loss AFTER real commit. Viewport simulation, not physical phone.`);
}catch(e){console.error('E07_UI_FAILED '+stage+' '+(e as Error).name);if(lastPage&&new URL(lastPage.url()).pathname==='/staff/transfers'){console.error('UI_STATUS '+await lastPage.getByRole('status').textContent().catch(()=>''));await mkdir('.local/screenshots',{recursive:true});await lastPage.screenshot({path:'.local/screenshots/e07-failure.png',fullPage:true});}failed=true;}finally{await browser.close();if(app)await app.stop();console.log('Owned E07 Web, browser and PostgreSQL stopped.');}if(failed)process.exit(1);
