import assert from 'node:assert/strict';
import {randomBytes,randomUUID,createHash} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {migrate,migrationPlan,migrationsDirectory} from '@rental/db';
import {startIsolatedPostgres} from '../../scripts/postgres';
import {provisionApplicationRoles} from '../../scripts/application-roles';
import {bootstrapDevelopmentAdmin} from '../../scripts/bootstrap-staff';
import {createStaffAuth,loadStaff,resolveStaff,type StaffPrincipal} from '../../packages/auth/src/staff-auth';
import {writeAccount} from '../../packages/auth/src/accounts';
import {authHandler} from '../../apps/web/src/lib/auth-http';
import {transferHandler} from '../../apps/web/src/lib/transfer-http';
import {TransferService} from '../../packages/core/src/transfer/transfer-service';
import {HoldService} from '../../packages/core/src/inventory/hold-service';
import {seedInventory,requestFor,variants,fid} from '../inventory/fixture';
import type {TransferPlan,TransferLine} from '../../packages/contracts/src/transfer';
let count=0,stage='startup',failed=false;const db=await startIsolatedPostgres();let roles:Awaited<ReturnType<typeof provisionApplicationRoles>>|undefined;
let now=new Date('2031-01-01T06:00:00Z');const origin='http://127.0.0.1:34567';const secret=randomBytes(32).toString('hex'),password=randomBytes(24).toString('base64url');
async function check(name:string,fn:()=>Promise<void>){stage=name;await fn();count++;console.log('PASS '+name);}
try{
 for(const m of migrationPlan.slice(0,4)){const sql=await readFile(migrationsDirectory+'/'+m.file,'utf8');await db.pool.query(sql);await db.pool.query('CREATE TABLE IF NOT EXISTS foundation_migrations(id text PRIMARY KEY,checksum text NOT NULL)');await db.pool.query('INSERT INTO foundation_migrations VALUES($1,$2)',[m.id,createHash('sha256').update(sql).digest('hex')]);}
 await seedInventory(db.pool);const admin=await bootstrapDevelopmentAdmin(db.pool,{email:'e07-admin@example.invalid',displayName:'合成ADMIN',password});const auth=createStaffAuth(db.pool,{origin,secret}),httpAuth=authHandler(auth,db.pool,origin,db.pool);
 const signed=await httpAuth(new Request(origin+'/api/auth/sign-in/email',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify({email:'e07-admin@example.invalid',password})}));assert.equal(signed.status,200);const cookie=signed.headers.getSetCookie().map(x=>x.split(';')[0]).join('; ');
 const oldHold=randomUUID(),oldReservation=randomUUID(),oldConditions=requestFor('2032-01-01');oldConditions.reservationId=oldReservation;
 const c=await db.pool.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('zao.actor',$1,true)",[admin]);await c.query('INSERT INTO inventory_reservations VALUES($1,$2)',[oldReservation,admin]);await c.query(`INSERT INTO inventory_holds(id,reservation_id,owner_id,pickup_store,return_store,conditions,starts_at,due_at,occupancy_start,occupancy_end,expires_at,state) VALUES($1,$2,$3,'MOUNTAIN_BASE','MOUNTAIN_BASE',$4,'2032-01-01T08:30:00+09:00','2032-01-01T17:00:00+09:00','2032-01-01','2032-01-01','2032-01-01','ACTIVE')`,[oldHold,oldReservation,admin,oldConditions]);await c.query('INSERT INTO inventory_claims(hold_id,requirement_key,asset_id,day) VALUES($1,$2,$3,$4)',[oldHold,'person-a:SKI',fid(1201),'2032-01-01']);await c.query('COMMIT');}finally{c.release();}
 await check('populated exact PR6 prefix upgrade preserves staff password session, ledger and HOLD claims',async()=>{await Promise.all([migrate(db.pool),migrate(db.pool)]);assert.equal((await resolveStaff(auth,db.pool,new Headers({cookie}))).status,'authorized');assert.equal((await db.pool.query('SELECT asset_id FROM inventory_claims WHERE hold_id=$1',[oldHold])).rows[0].asset_id,fid(1201));assert.equal((await db.pool.query('SELECT count(*)::int AS n FROM foundation_migrations')).rows[0].n,6);});
 roles=await provisionApplicationRoles(db.pool,db.identity);const adminP=(await loadStaff(db.pool,admin))!;
 const grants={TRANSFER_VIEW:true,TRANSFER_PLAN:true,TRANSFER_DISPATCH:true,TRANSFER_RECEIVE:true,HOLD_VIEW:true,HOLD_EDIT:true};
 const settings={displayName:'合成移動担当',active:true,role:'STAFF' as const,scope:'ASSIGNED' as const,storeIds:['MOUNTAIN_BASE','ONSEN_BASE'] as ('MOUNTAIN_BASE'|'ONSEN_BASE')[],permissions:grants};
 const actor=(await writeAccount(roles.authPool,adminP,undefined,{...settings,email:'e07-actor@example.invalid',password})).id!;
 const receiver=(await writeAccount(roles.authPool,adminP,undefined,{...settings,storeIds:['ONSEN_BASE'],permissions:{TRANSFER_VIEW:true,TRANSFER_RECEIVE:true},email:'e07-receiver@example.invalid',password})).id!;
 let principal=(await loadStaff(db.pool,actor))!;const svc=(p:StaffPrincipal=principal)=>new TransferService(roles!.transferPool,p,()=>now);const holds=()=>new HoldService(roles!.holdPool,principal,()=>now);
 async function stock(family:'SKI'|'POLE'='SKI',quantity=1,unique=false){const id=randomUUID(),client=await db.pool.connect();try{await client.query('BEGIN');await client.query("SELECT set_config('zao.actor',$1,true),set_config('zao.reason','Synthetic E07 test stock',true)",[actor]);let skiVariant=variants.ski;if(family==='SKI'&&unique){skiVariant=randomUUID();await client.query(`INSERT INTO ledger_variants(id,model_id,family,age,tier,size,notes,source_kind,source_document,source_locator) SELECT $1::uuid,model_id,'SKI','ADULT','REGULAR',$2,'','SYNTHETIC','tests/transfer/real-postgres.ts',$1::text FROM ledger_variants WHERE id=$3`,[skiVariant,'test-'+id.slice(0,8),variants.ski]);}if(family==='SKI')await client.query(`INSERT INTO ledger_assets(id,variant_id,family,initial_store_id,store_id,status,bsl_status,bsl_mm,bsl_evidence,notes,source_kind,source_document,source_locator) VALUES($1::uuid,$2,'SKI','MOUNTAIN_BASE','MOUNTAIN_BASE','AVAILABLE','NOT_APPLICABLE',NULL,'','','SYNTHETIC','tests/transfer/real-postgres.ts',$1::text)`,[id,skiVariant]);else{const variant=randomUUID();await client.query(`INSERT INTO ledger_variants(id,model_id,family,age,tier,size,notes,source_kind,source_document,source_locator) SELECT $1::uuid,model_id,'POLE','ADULT','REGULAR',$2,'','SYNTHETIC','tests/transfer/real-postgres.ts',$1::text FROM ledger_variants WHERE id=$3`,[variant,'test-'+id.slice(0,8),variants.pole]);await client.query(`INSERT INTO ledger_poles(id,variant_id,store_id,quantity,status,notes,source_kind,source_document,source_locator) VALUES($1::uuid,$2,'MOUNTAIN_BASE',$3,'AVAILABLE','','SYNTHETIC','tests/transfer/real-postgres.ts',$1::text)`,[id,variant,quantity]);}await client.query('COMMIT');return id;}finally{client.release();}}
 function plan(lines:TransferLine[],day='2031-01-02'):TransferPlan{return {sourceStore:'MOUNTAIN_BASE',destinationStore:'ONSEN_BASE',scheduledDate:day,plannedReadyAt:day+'T19:00:00+09:00',neededBy:new Date(Date.parse(day+'T00:00:00Z')+86400000).toISOString().slice(0,10)+'T08:30:00+09:00',basis:'SYNTHETIC ONLY: staff-confirmed loading, route and readiness estimate; no 17:10 assumption',lines};}
 async function create(lines:TransferLine[],day='2031-01-02'){return (await svc().command('create',randomUUID(),plan(lines,day))).batch;}
 async function command(id:string,op:'dispatch'|'receive'|'ready'|'cancel'|'issue',input:unknown={}){return (await svc().command(op,randomUUID(),input,id)).batch;}
 let a:string,b:Awaited<ReturnType<typeof create>>;
 await check('committed plan preserves current location and supports an exact future destination HOLD only once',async()=>{
  a=await stock();b=await create([{assetId:a}]);assert.equal((await db.pool.query('SELECT store_id FROM ledger_assets WHERE id=$1',[a])).rows[0].store_id,'MOUNTAIN_BASE');
  const h=requestFor('2031-01-03');h.pickupStore=h.returnStore='ONSEN_BASE';const r=await holds().command('create',randomUUID(),h);assert.equal(r.result,'CREATED');assert.equal((await db.pool.query('SELECT asset_id,transfer_piece_id FROM inventory_claims WHERE hold_id=$1 AND active',[r.holdId])).rows[0].asset_id,a);assert.equal((await holds().availability({...h,reservationId:randomUUID()})).result,'TRANSFER_PLAN_REQUIRED');
 });
 await check('departure requires 17:00; no automatic receipt, late additions or post-dispatch cancellation',async()=>{
  now=new Date('2031-01-02T07:59:00Z');await assert.rejects(svc().command('dispatch',randomUUID(),{},b.id),{code:'DISPATCH_NOT_ALLOWED'});now=new Date('2031-01-02T08:00:00Z');b=await command(b.id,'dispatch');assert.ok(b.pieces.every(p=>p.state==='IN_TRANSIT'));now=new Date('2031-01-02T08:10:00Z');assert.ok((await svc().get(b.id)).pieces.every(p=>p.state==='IN_TRANSIT'));await assert.rejects(svc().command('add',randomUUID(),{lines:[{assetId:await stock()}]},b.id),{code:'BATCH_CLOSED'});await assert.rejects(svc().command('cancel',randomUUID(),{},b.id),{code:'PHYSICAL_TRANSFER_CANNOT_CANCEL'});
 });
 await check('HOLD release after dispatch retains physical transfer; future allocation cannot auto-move a dispatched witness',async()=>{
  const h=requestFor('2031-01-04');h.pickupStore=h.returnStore='ONSEN_BASE';const r=await holds().command('create',randomUUID(),h);assert.equal(r.result,'CREATED');await assert.rejects(holds().command('reassign',randomUUID(),{requirementKey:'person-a:SKI',assetId:await stock()},r.holdId),{code:'TRANSFER_ALLOCATION_FIXED'});assert.equal((await holds().command('cancel',randomUUID(),undefined,r.holdId)).result,'RELEASED');assert.equal((await svc().get(b.id)).pieces[0].state,'IN_TRANSIT');
 });
 await check('receiver scope, actual receipt history, readiness separation and immutable Asset identity',async()=>{
  const receiverP=(await loadStaff(db.pool,receiver))!;await assert.rejects(svc(receiverP).command('dispatch',randomUUID(),{},b.id),{code:'FORBIDDEN'});
  const key=randomUUID(),piece=b.pieces[0].id;const r=await svc(receiverP).command('receive',key,{pieceIds:[piece]},b.id);assert.equal(r.batch.pieces[0].state,'RECEIVED');assert.equal((await db.pool.query('SELECT store_id,initial_store_id FROM ledger_assets WHERE id=$1',[a])).rows[0].store_id,'ONSEN_BASE');assert.equal((await db.pool.query('SELECT count(*)::int AS n FROM ledger_locations WHERE asset_id=$1',[a])).rows[0].n,2);assert.equal((await svc(receiverP).command('receive',key,{pieceIds:[piece]},b.id)).replayed,true);await assert.rejects(svc(receiverP).command('receive',randomUUID(),{pieceIds:[piece]},b.id),{code:'STALE_SELECTION'});
  await command(b.id,'ready',{pieceIds:[piece]});assert.equal((await svc().get(b.id)).pieces[0].state,'READY');
 });
 await check('same-day reuse forbidden at destination; another date remains possible',async()=>{const h=requestFor('2031-01-02');h.period.slot='PM';h.pickupStore=h.returnStore='ONSEN_BASE';await assert.rejects(holds().availability(h),{code:'PERIOD_ENDED'});h.period.startDate=h.period.endDate='2031-01-05';assert.equal((await holds().availability(h)).result,'FEASIBLE');});
 await check('pooled PAIR quantities: partial receipt, separate inspection, no double stock, duplicate and overreceipt refusal',async()=>{
  now=new Date('2031-01-03T06:00:00Z');const pole=await stock('POLE',3);const p=await create([{poleId:pole,quantity:3}],'2031-01-04');const variant=(await db.pool.query('SELECT variant_id FROM ledger_poles WHERE id=$1',[pole])).rows[0].variant_id;
  const h=requestFor('2031-01-05');h.pickupStore=h.returnStore='ONSEN_BASE';h.members[0]!.items=[{family:'POLE',variantIds:[variant]}];assert.equal((await holds().command('create',randomUUID(),h)).result,'CREATED');
  now=new Date('2031-01-04T08:00:00Z');await command(p.id,'dispatch');assert.equal((await db.pool.query('SELECT quantity FROM ledger_poles WHERE id=$1',[pole])).rows[0].quantity,0);
  const first=p.pieces[0].id;await command(p.id,'receive',{pieceIds:[first]});let q=await svc().get(p.id);assert.equal(q.pieces.filter(x=>x.state==='IN_TRANSIT').length,2);assert.equal(q.pieces.filter(x=>x.state==='RECEIVED').length,1);assert.equal((await db.pool.query('SELECT sum(quantity)::int AS n FROM ledger_poles WHERE variant_id=$1',[variant])).rows[0].n,1);
  await command(p.id,'ready',{pieceIds:[first]});q=await svc().get(p.id);assert.equal(q.pieces.filter(x=>x.state==='READY').length,1);await assert.rejects(svc().command('receive',randomUUID(),{pieceIds:[first,randomUUID()]},p.id),{code:'STALE_SELECTION'});await command(p.id,'receive',{pieceIds:p.pieces.slice(1).map(x=>x.id)});await command(p.id,'ready',{pieceIds:p.pieces.slice(1).map(x=>x.id)});assert.equal((await db.pool.query('SELECT sum(quantity)::int AS n FROM ledger_poles WHERE variant_id=$1',[variant])).rows[0].n,3);
  const many=structuredClone(h);many.reservationId=randomUUID();many.period.startDate=many.period.endDate='2031-01-06';many.members=Array.from({length:4},(_,i)=>({...structuredClone(h.members[0]!),key:'person-'+i}));assert.notEqual((await holds().availability(many)).result,'FEASIBLE');
 });
 await check('cancel and delay identify exact affected HOLD, preserve claims, and do not block unrelated demands',async()=>{
  now=new Date('2031-01-05T06:00:00Z');const id=await stock('SKI',1,true),variant=(await db.pool.query('SELECT variant_id FROM ledger_assets WHERE id=$1',[id])).rows[0].variant_id,p=await create([{assetId:id}],'2031-01-06');const h=requestFor('2031-01-07',[variant]);h.pickupStore=h.returnStore='ONSEN_BASE';const r=await holds().command('create',randomUUID(),h);assert.equal(r.result,'CREATED');assert.equal((await db.pool.query('SELECT transfer_piece_id FROM inventory_claims WHERE hold_id=$1 AND active',[r.holdId])).rows[0].transfer_piece_id,p.pieces[0].id);
  await command(p.id,'cancel');assert.equal((await holds().get(r.holdId!)).transferAttention,'TRANSFER_RECONCILIATION_REQUIRED');assert.equal((await holds().get(r.holdId!)).state,'ACTIVE');assert.equal((await db.pool.query('SELECT count(*)::int AS n FROM inventory_claims WHERE hold_id=$1 AND active',[r.holdId])).rows[0].n,1);assert.notEqual((await holds().availability({...h,reservationId:randomUUID()})).result,'FEASIBLE');assert.equal((await holds().availability(requestFor('2031-01-08'))).result,'FEASIBLE');
  const second=await stock('SKI',1,true),secondVariant=(await db.pool.query('SELECT variant_id FROM ledger_assets WHERE id=$1',[second])).rows[0].variant_id;const q=await create([{assetId:second}],'2031-01-06');now=new Date('2031-01-06T08:00:00Z');await command(q.id,'dispatch');now=new Date('2031-01-06T09:55:00Z');const hh=requestFor('2031-01-07',[secondVariant]);hh.pickupStore=hh.returnStore='ONSEN_BASE';const hr=await holds().command('create',randomUUID(),hh);assert.equal(hr.result,'CREATED');now=new Date('2031-01-06T10:01:00Z');assert.equal((await holds().get(hr.holdId!)).transferAttention,'TRANSFER_RECONCILIATION_REQUIRED');await command(q.id,'issue',{reason:'SYNTHETIC delayed vehicle'});assert.equal((await holds().get(hr.holdId!)).state,'ACTIVE');await command(q.id,'receive',{pieceIds:q.pieces.map(x=>x.id)});assert.equal((await svc().get(q.id)).pieces[0].state,'RECEIVED');assert.equal((await holds().availability(requestFor('2031-01-08'))).result,'FEASIBLE');
 });
 await check('source future HOLD and transfer compete on the same global transaction lock: exactly one promise wins',async()=>{
  now=new Date('2031-01-07T06:00:00Z');const id=await stock('SKI',1,true),variant=(await db.pool.query('SELECT variant_id FROM ledger_assets WHERE id=$1',[id])).rows[0].variant_id;
  const outcomes=await Promise.allSettled([create([{assetId:id}],'2031-01-08'),holds().command('create',randomUUID(),requestFor('2031-01-09',[variant]))]);
  const transfer=outcomes[0]!.status==='fulfilled',held=outcomes[1]!.status==='fulfilled'&&(outcomes[1] as PromiseFulfilledResult<{result:string}>).value.result==='CREATED';assert.notEqual(transfer,held);assert.equal(Number(transfer)+Number(held),1);
 });
 await check('same-day source HOLD does not invalidate unrelated future demands after dispatch, and fixed rental cannot be presumed returned',async()=>{
  now=new Date('2031-01-09T07:55:00Z');const id=await stock('SKI',1,true),variant=(await db.pool.query('SELECT variant_id FROM ledger_assets WHERE id=$1',[id])).rows[0].variant_id;
  const h=await holds().command('create',randomUUID(),requestFor('2031-01-09',[variant]));assert.equal(h.result,'CREATED');const p=await create([{assetId:id}],'2031-01-09');now=new Date('2031-01-09T08:00:00Z');await command(p.id,'dispatch');assert.equal((await holds().availability(requestFor('2031-01-10'))).result,'FEASIBLE');
  now=new Date('2031-01-10T07:55:00Z');const other=await stock('SKI',1,true),v=(await db.pool.query('SELECT variant_id FROM ledger_assets WHERE id=$1',[other])).rows[0].variant_id;const fixed=await holds().command('create',randomUUID(),requestFor('2031-01-10',[v]));const c=await db.pool.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('zao.actor',$1,true)",[actor]);await c.query("UPDATE inventory_holds SET allocation_stage='RENTAL_FIXED' WHERE id=$1",[fixed.holdId]);await c.query('COMMIT');}finally{c.release();}await assert.rejects(create([{assetId:other}],'2031-01-10'),{code:'SOURCE_PROMISE_CONFLICT'});
 });
 await check('concurrent transfer plans claim an individual once; concurrent partial receipts change stock once',async()=>{
  now=new Date('2031-01-11T06:00:00Z');const id=await stock();const outcomes=await Promise.allSettled([create([{assetId:id}],'2031-01-12'),create([{assetId:id}],'2031-01-12')]);assert.equal(outcomes.filter(x=>x.status==='fulfilled').length,1);const p=(outcomes.find(x=>x.status==='fulfilled') as PromiseFulfilledResult<Awaited<ReturnType<typeof create>>>).value;now=new Date('2031-01-12T08:00:00Z');await command(p.id,'dispatch');const results=await Promise.allSettled([command(p.id,'receive',{pieceIds:[p.pieces[0].id]}),command(p.id,'receive',{pieceIds:[p.pieces[0].id]})]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal((await db.pool.query('SELECT count(*)::int AS n FROM ledger_locations WHERE asset_id=$1',[id])).rows[0].n,2);
 });
 await check('pole dispatch compacts only fungible slots, preserving a fixed source promise and date after quantity reduction',async()=>{
  now=new Date('2031-01-13T06:00:00Z');const pole=await stock('POLE',3),variant=(await db.pool.query('SELECT variant_id FROM ledger_poles WHERE id=$1',[pole])).rows[0].variant_id;
  const requests=[];for(let i=0;i<3;i++){const h=requestFor('2031-01-15');h.members[0]!.items=[{family:'POLE',variantIds:[variant]}];requests.push(await holds().command('create',randomUUID(),h));}
  const last=(await db.pool.query('SELECT hold_id FROM inventory_claims WHERE pole_id=$1 AND active AND pole_slot=3',[pole])).rows[0].hold_id;
  for(const h of requests)if(h.holdId!==last)await holds().command('cancel',randomUUID(),undefined,h.holdId);
  const c=await db.pool.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('zao.actor',$1,true)",[actor]);await c.query("UPDATE inventory_holds SET allocation_stage='PREPARATION_FIXED' WHERE id=$1",[last]);await c.query('COMMIT');}finally{c.release();}
  const old=await holds().get(last),p=await create([{poleId:pole,quantity:2}],'2031-01-14');now=new Date('2031-01-14T08:00:00Z');await command(p.id,'dispatch');assert.equal((await db.pool.query('SELECT quantity FROM ledger_poles WHERE id=$1',[pole])).rows[0].quantity,1);
  const claim=(await db.pool.query('SELECT pole_slot,day::text FROM inventory_claims WHERE hold_id=$1 AND active',[last])).rows[0];assert.deepEqual(claim,{pole_slot:1,day:'2031-01-15'});assert.deepEqual((await holds().get(last)).conditions,old.conditions);
  assert.equal((await holds().get(last)).allocationStage,'PREPARATION_FIXED');assert.ok((await db.pool.query('SELECT count(*)::int AS n FROM inventory_replans')).rows[0].n>0);
 });
 await check('one direction/date batch cannot be recreated after departure; a ready item may join before actual departure after 17:00',async()=>{
  now=new Date('2031-01-16T07:00:00Z');const p=await create([{assetId:await stock()}],'2031-01-16');now=new Date('2031-01-16T08:05:00Z');await svc().command('add',randomUUID(),{lines:[{assetId:await stock()}]},p.id);assert.equal((await svc().get(p.id)).pieces.length,2);const key=randomUUID();const first=await svc().command('dispatch',key,{},p.id),again=await svc().command('dispatch',key,{},p.id);assert.equal(first.batch.id,again.batch.id);assert.equal(again.replayed,true);await assert.rejects(create([{assetId:await stock()}],'2031-01-16'),{code:'TRANSFER_CONFLICT'});
 });
 await check('dispatch rechecks a rental fixed after planning and never assumes its physical return',async()=>{
  now=new Date('2031-01-17T07:55:00Z');const id=await stock('SKI',1,true),variant=(await db.pool.query('SELECT variant_id FROM ledger_assets WHERE id=$1',[id])).rows[0].variant_id;const p=await create([{assetId:id}],'2031-01-17');const h=await holds().command('create',randomUUID(),requestFor('2031-01-17',[variant]));assert.equal(h.result,'CREATED');const c=await db.pool.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('zao.actor',$1,true)",[actor]);await c.query("UPDATE inventory_holds SET allocation_stage='RENTAL_FIXED' WHERE id=$1",[h.holdId]);await c.query('COMMIT');}finally{c.release();}now=new Date('2031-01-17T08:00:00Z');await assert.rejects(svc().command('dispatch',randomUUID(),{},p.id),{code:'SOURCE_NOT_RETURNED_OR_READY'});assert.equal((await svc().get(p.id)).state,'PLANNED');assert.equal((await db.pool.query('SELECT store_id FROM ledger_assets WHERE id=$1',[id])).rows[0].store_id,'MOUNTAIN_BASE');
 });
 // E07-01: a future maintenance interval must not block an earlier transfer date.
 let constraintCase=0;
 for(const family of ['SKI','POLE'] as const)for(const op of ['create','add'] as const){
  await check(`constraint date overlap: ${family} ${op} accepts future maintenance and rejects an inclusive departure-day block`,async()=>{
   for(const overlaps of [false,true]){
    const day='2031-02-'+String(2+constraintCase++).padStart(2,'0');now=new Date(day+'T06:00:00Z');
    const id=await stock(family,2,true),line:TransferLine=family==='SKI'?{assetId:id}:{poleId:id,quantity:1};
    const starts=overlaps?day:new Date(Date.parse(day+'T00:00:00Z')+86400000).toISOString().slice(0,10);
    const ends=new Date(Date.parse(day+'T00:00:00Z')+2*86400000).toISOString().slice(0,10);
    await db.pool.query("INSERT INTO inventory_constraints(id,asset_id,pole_id,starts_on,ends_on,kind,evidence_ref) VALUES($1,$2,$3,$4,$5,'MAINTENANCE','SYNTHETIC E07-01 interval boundary')",[randomUUID(),family==='SKI'?id:null,family==='POLE'?id:null,starts,ends]);
    const existing=op==='add'?await create([{assetId:await stock()}],day):null;
    const before=(await db.pool.query('SELECT count(*)::int AS n FROM transfer_pieces')).rows[0].n;
    const attempt=()=>op==='create'?svc().command('create',randomUUID(),plan([line],day)):svc().command('add',randomUUID(),{lines:[line]},existing!.id);
    if(overlaps){await assert.rejects(attempt(),{code:'STOCK_CONSTRAINED'});assert.equal((await db.pool.query('SELECT count(*)::int AS n FROM transfer_pieces')).rows[0].n,before);}
    else{const result=await attempt();assert.ok(result.batch.pieces.some(p=>p.asset_id===id||p.source_pole_id===id));now=new Date(day+'T08:00:00Z');await command(result.batch.id,'dispatch');assert.ok((await svc().get(result.batch.id)).pieces.every(p=>p.state==='IN_TRANSIT'));}
   }
  });
 }
 await check('ordinary password/session/API rejects anonymous, CSRF, role/actor spoof and removed permission before allocation lock',async()=>{
  const signin=await httpAuth(new Request(origin+'/api/auth/sign-in/email',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify({email:'e07-actor@example.invalid',password})}));assert.equal(signin.status,200);const actorCookie=signin.headers.getSetCookie().map(x=>x.split(';')[0]).join('; ');
  const handler=transferHandler(h=>resolveStaff(auth,db.pool,h),p=>svc(p),origin);assert.equal((await handler(new Request(origin+'/api/transfers'))).status,401);
  const payload={requestKey:randomUUID(),input:plan([{assetId:await stock()}],'2031-01-10')};
  assert.equal((await handler(new Request(origin+'/api/transfers',{method:'POST',headers:{cookie:actorCookie,'content-type':'application/json'},body:JSON.stringify(payload)}))).status,403);
  assert.equal((await handler(new Request(origin+'/api/transfers',{method:'POST',headers:{cookie:actorCookie,origin,'content-type':'application/json'},body:JSON.stringify({...payload,role:'ADMIN'})}))).status,422);
  now=new Date('2031-01-09T06:00:00Z');const result=await handler(new Request(origin+'/api/transfers',{method:'POST',headers:{cookie:actorCookie,origin,'content-type':'application/json'},body:JSON.stringify(payload)}));assert.equal(result.status,201);
  const scopeBlock=await db.pool.connect();try{await scopeBlock.query('BEGIN');await scopeBlock.query('SELECT pg_advisory_xact_lock(71820600)');const before=Date.now();const forbidden=await handler(new Request(origin+'/api/transfers',{method:'POST',headers:{cookie:actorCookie,origin,'content-type':'application/json'},body:JSON.stringify({requestKey:randomUUID(),input:plan([{assetId:a}],'2031-01-20')})}));assert.equal(forbidden.status,403);assert.ok(Date.now()-before<1000);}finally{await scopeBlock.query('ROLLBACK');scopeBlock.release();}
  await writeAccount(roles!.authPool,adminP,actor,{...settings,permissions:{...grants,TRANSFER_PLAN:false}});const blocker=await db.pool.connect();try{await blocker.query('BEGIN');await blocker.query('SELECT pg_advisory_xact_lock(71820600)');const start=Date.now();const denied=await handler(new Request(origin+'/api/transfers',{method:'POST',headers:{cookie:actorCookie,origin,'content-type':'application/json'},body:JSON.stringify(payload)}));assert.equal(denied.status,403);assert.ok(Date.now()-start<1000);}finally{await blocker.query('ROLLBACK');blocker.release();}
  principal=(await loadStaff(db.pool,actor))!;
 });
 await check('application roles cannot rewrite location through master edits, manufacture audit, or perform DDL',async()=>{
  const c=await roles!.ledgerPool.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('zao.actor',$1,true),set_config('zao.reason','Spoofed movement',true),set_config('zao.transfer_operation','controlled',true)",[actor]);await assert.rejects(c.query("UPDATE ledger_assets SET store_id='MOUNTAIN_BASE' WHERE id=$1",[a]),{code:'23514'});await c.query('ROLLBACK');}finally{c.release();}
  await assert.rejects(roles!.transferPool.query('CREATE TABLE forbidden_transfer_test(id int)'),{code:'42501'});await assert.rejects(roles!.transferPool.query("UPDATE inventory_holds SET payment_state='SUCCESS'"),{code:'42501'});await assert.rejects(roles!.transferPool.query("UPDATE inventory_holds SET conditions='{}'::jsonb"),{code:'42501'});await assert.rejects(roles!.transferPool.query("UPDATE transfer_history SET event='spoof'"),{code:'42501'});await assert.rejects(roles!.transferPool.query('SELECT password FROM auth_account'),{code:'42501'});await assert.rejects(roles!.transferPool.query("CREATE OR REPLACE FUNCTION inventory_clock() RETURNS timestamptz LANGUAGE sql AS $$SELECT now()$$"),{code:'42501'});
 });
 console.log(`E07 real PostgreSQL: ${count} passed; 0 skipped. Synthetic password sessions; operational clock injected only into service tests.`);
}catch(e){console.error('E07_DB_FAILED '+stage+' '+((e as {code?:string}).code??(e as Error).name));if(e instanceof assert.AssertionError)console.error(JSON.stringify({actual:e.actual,expected:e.expected}));failed=true;}finally{if(roles)await roles.close();await db.stop();console.log('Owned E07 PostgreSQL stopped.');}if(failed)process.exit(1);
