import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
import {mkdir} from 'node:fs/promises';
import {chromium,expect,type BrowserContext} from '@playwright/test';
import {startDevelopmentApp} from '../../scripts/development-app';
import {bootstrapDevelopmentAdmin} from '../../scripts/bootstrap-staff';
import {loadStaff} from '../../packages/auth/src/staff-auth';
import {QuoteService} from '../../packages/core/src/pricing/quote-service';
import {PRICE_PRODUCTS} from '../../packages/contracts/src/pricing';
import {seedRecommendation,inputFor,selection,lengthVariants,variants,fid} from './fixture';
import type {RecommendationService} from '../../packages/core/src/recommendation/recommendation-service';
import type {HoldConditions} from '../../packages/contracts/src/hold';
type View=Awaited<ReturnType<RecommendationService['get']>>;
const browser=await chromium.launch(),password=randomBytes(24).toString('base64url');
let app:Awaited<ReturnType<typeof startDevelopmentApp>>|undefined,passed=0,failed=0;
async function check(name:string,fn:()=>Promise<void>){try{await fn();passed++;console.log('PASS '+name);}catch(e){failed++;console.error('FAIL '+name+' '+(e as {code?:string}).code+' '+(e as Error).name);if(e instanceof assert.AssertionError)console.error(JSON.stringify({actual:e.actual,expected:e.expected}));console.error((e as Error).stack?.split('\n').filter(l=>l.includes('/tests/recommendation/continuation-ui.ts:')).join('\n'));}}
try{
 app=await startDevelopmentApp({built:true});await seedRecommendation(app.db.pool,true);await bootstrapDevelopmentAdmin(app.db.pool,{email:'continuation-bootstrap@example.invalid',displayName:'合成初期ADMIN',password});const {origin}=app;
 // Continuation changes to 145/155cm need one public slot, hence two physical units.
 const seed=await app.db.pool.connect();try{await seed.query('BEGIN');await seed.query("SELECT set_config('zao.actor','synthetic-continuation',true),set_config('zao.reason','SYNTHETIC public size continuation',true)");
  await seed.query(`INSERT INTO ledger_assets(id,variant_id,family,initial_store_id,store_id,status,bsl_status,bsl_evidence,notes,source_kind,source_document,source_locator)
   SELECT gen_random_uuid(),id,family,'MOUNTAIN_BASE','MOUNTAIN_BASE','AVAILABLE','NOT_APPLICABLE','','SYNTHETIC continuation','SYNTHETIC','tests/recommendation/continuation-ui.ts','public-size-'||id FROM ledger_variants WHERE id=ANY($1::uuid[])`,[[variants.skiAlt,lengthVariants.ski145,lengthVariants.board155]]);await seed.query('COMMIT');
 }catch(e){await seed.query('ROLLBACK');throw e;}finally{seed.release();}
 async function clock(iso:string){await app!.db.pool.query(`CREATE OR REPLACE FUNCTION inventory_clock() RETURNS timestamptz LANGUAGE sql VOLATILE AS $$ SELECT '${new Date(iso).toISOString()}'::timestamptz $$`);}
 await clock('2035-01-01T00:00:00Z');for(let i=0;i<100;i++){try{if((await fetch(origin+'/api/health')).ok)break;}catch{}if(i===99)throw new Error('APP_START_TIMEOUT');await new Promise(r=>setTimeout(r,100));}
 async function login(email:string){const c=await browser.newContext({baseURL:origin,viewport:{width:1280,height:1000}});c.setDefaultTimeout(10000);const page=await c.newPage();await page.goto('/staff/login');await page.getByLabel('メールアドレス',{exact:true}).fill(email);await page.getByLabel('パスワード',{exact:true}).fill(password);await page.getByRole('button',{name:'ログイン',exact:true}).click();await page.waitForURL(origin+'/staff/ledger');await page.close();return c;}
 const bootstrap=await login('continuation-bootstrap@example.invalid');
 for(const [name,edit]of [['owner',true],['other',true],['viewer',false]] as const){const r=await bootstrap.request.post('/api/staff-users',{headers:{origin},data:{email:`continuation-${name}@example.invalid`,password,displayName:'合成 '+name,active:true,role:edit?'ADMIN':'VIEWER',scope:edit?'ALL':'ASSIGNED',storeIds:edit?[]:['MOUNTAIN_BASE'],permissions:{HOLD_VIEW:true,HOLD_EDIT:edit,QUOTE_VIEW:true,QUOTE_CREATE:edit,PRICE_EDIT:edit}}});assert.equal(r.status(),201);}
 const staff=await login('continuation-owner@example.invalid'),other=await login('continuation-other@example.invalid'),viewer=await login('continuation-viewer@example.invalid');
 assert.equal((await staff.request.post('/api/quotes/private-initialize',{headers:{origin},data:{operation:'initializePrivate',input:{requestKey:randomUUID(),rentalFrom:'2035-01-01',rentalUntil:'2036-12-31'}}})).status(),201);
 const post=(path:string,data:unknown,c:BrowserContext=staff)=>c.request.post(path,{headers:{origin},data});
 const nextDay=(d:string)=>new Date(Date.parse(d+'T00:00:00Z')+86400000).toISOString().slice(0,10);
 async function fresh(date:string,slot:'MULTIDAY'|'DAY'|'AM'='MULTIDAY',time=slot==='AM'?'11:55':'16:55',c=staff){await clock(date+'T'+time+':00+09:00');const input=inputFor(date);input.period={startDate:date,endDate:slot==='MULTIDAY'?nextDay(date):date,slot};const r=await post('/api/recommendations',{requestKey:randomUUID(),input,replaceHoldId:null},c);assert.equal(r.status(),201);const p:View=await r.json();const s=await post('/api/recommendations/'+p.preview.id+'/select',{requestKey:randomUUID(),selection:selection()},c);assert.equal(s.status(),200);const v:View=await s.json();assert.equal(v.selection!.stage,'COMPLETE');return v;}
 const preview=(v:View,input=v.preview.input,c=staff)=>post('/api/recommendations',{requestKey:randomUUID(),input,replaceHoldId:v.hold!.id},c);
 const change=(v:View)=>{const c=structuredClone(v.hold!.conditions);c.members[0]!.items.find(i=>i.family==='SKI')!.variantIds=[lengthVariants.ski145];return c;};
 const amend=(v:View,c:HoldConditions=change(v),key=randomUUID(),who=staff)=>post('/api/holds/'+v.hold!.id+'/amend',{requestKey:key,conditions:c,expectedVersion:v.hold!.version},who);
 const quote=(v:View,c=v.hold!.conditions,key=randomUUID())=>post('/api/quotes',{requestKey:key,input:{conditions:c,holdId:v.hold!.id,couponCode:null,wantAdvance:false}});
 const reread=(v:View)=>staff.request.get('/api/holds/'+v.hold!.id).then(r=>r.json());
 async function unchanged(v:View){const h=await reread(v);assert.deepEqual(h.conditions,v.hold!.conditions);assert.equal(h.version,v.hold!.version);assert.equal(h.expiresAt,v.hold!.expiresAt);}
 async function rejected(r:Awaited<ReturnType<typeof post>>){assert.ok([403,409,422].includes(r.status()),'must reject, status '+r.status());return r.json();}

 await check('16:55 group ->17:01 one-member length/price ->UI selection/amend/quote/reread; no lease renewal',async()=>{
  const first=await fresh('2035-07-01'),oldSnapshot=structuredClone(first.quote);await clock('2035-07-01T17:01:00+09:00');const p=await staff.newPage();try{await p.goto('/staff/recommendations');await p.getByRole('button',{name:new RegExp('推薦 '+first.preview.id.slice(0,8))}).click();await expect(p.getByRole('region',{name:'保存結果',exact:true})).toBeVisible();
   const response=p.waitForResponse(r=>r.url()===origin+'/api/recommendations'&&r.request().method()==='POST');await p.getByRole('button',{name:'推薦候補を確認',exact:true}).click();const r=await response;console.log('CONTINUATION_PREVIEW '+JSON.stringify({status:r.status()}));assert.equal(r.status(),201);const candidate:View=await r.json();assert.equal(candidate.preview.offered.length,2);assert.ok(candidate.preview.offered.every(o=>o.price&&o.priceError===null));
   await expect(p.getByRole('article',{name:'利用者 1 の候補'})).toContainText('割引前の参考額');await p.getByRole('button',{name:'長めを選ぶ 1',exact:true}).click();await p.getByRole('button',{name:'おすすめを選ぶ 2',exact:true}).click();await p.getByLabel('モデル指定なし・表示したサイズとクラスを選択条件とすることを確認').check();const done=p.waitForResponse(r=>r.url().endsWith('/select'));await p.getByRole('button',{name:'全員分をHOLDして見積を保存',exact:true}).click();const v:View=await (await done).json();assert.equal(v.selection!.stage,'COMPLETE');assert.equal(v.hold!.id,first.hold!.id);assert.equal(v.hold!.version,2);assert.equal(v.hold!.expiresAt,'2035-07-01T08:05:00.000Z');assert.equal(v.quote!.snapshot.expiresAt,v.hold!.expiresAt);assert.equal(v.quote!.chargeReady,false);assert.equal(v.hold!.conditions.members[0]!.items[0]!.variantIds[0],variants.skiAlt);assert.deepEqual(v.hold!.conditions.members[1],first.hold!.conditions.members[1]);
   await p.reload();await p.getByRole('button',{name:new RegExp('推薦 '+v.preview.id.slice(0,8))}).click();await expect(p.getByRole('region',{name:'見積詳細',exact:true})).toContainText('VALID_PRIVATE_ESTIMATE');assert.deepEqual((await (await staff.request.get('/api/quotes/'+oldSnapshot!.id)).json()).snapshot,oldSnapshot!.snapshot);await mkdir('.local/screenshots',{recursive:true});await p.screenshot({path:'.local/screenshots/e09-continuation.png',fullPage:true});
  }finally{await p.close();}
 });
 await check('17:01 rejects new same-day HOLD/unlinked quote; future reservation remains allowed after hours',async()=>{const v=await fresh('2035-07-03');await clock('2035-07-03T17:01:00+09:00');const c=structuredClone(v.hold!.conditions);c.reservationId=randomUUID();await rejected(await post('/api/holds',{requestKey:randomUUID(),conditions:c}));await rejected(await post('/api/quotes',{requestKey:randomUUID(),input:{conditions:c,holdId:null,couponCode:null,wantAdvance:false}}));const future=inputFor('2035-07-05');assert.equal((await post('/api/recommendations',{requestKey:randomUUID(),input:future,replaceHoldId:null})).status(),201);await unchanged(v);});
 for(const time of ['17:05:00','17:05:01','next-day'])await check('expired HOLD cannot continue at '+time,async()=>{const v=await fresh('2035-07-07');await clock(time==='next-day'?'2035-07-08T10:00:00+09:00':'2035-07-07T'+time+'+09:00');await rejected(await preview(v));await rejected(await quote(v));await rejected(await post('/api/holds/'+v.hold!.id+'/availability',v.hold!.conditions));const r=await amend(v);if(r.ok())assert.equal((await r.json()).result,'EXPIRED');else await rejected(r);assert.equal((await reread(v)).state,'EXPIRED');assert.equal((await reread(v)).expiresAt,v.hold!.expiresAt);});
 for(const slot of ['DAY','AM'] as const)await check(slot+' due closes continuation even with lease time left',async()=>{const v=await fresh(slot==='DAY'?'2035-07-10':'2035-07-11',slot);await clock(v.preview.input.period.startDate+(slot==='DAY'?'T17:00:00+09:00':'T12:00:00+09:00'));await rejected(await preview(v));await rejected(await quote(v));await rejected(await amend(v));await unchanged(v);});
 await check('after-close full-group non-size mutations cannot borrow old HOLD; original stays intact',async()=>{const v=await fresh('2035-07-13');await clock('2035-07-13T17:01:00+09:00');const changes:{label:string;edit:(c:HoldConditions)=>void}[]=[{label:'member',edit:c=>c.members.push({...structuredClone(c.members[0]!),key:'extra'})},{label:'tier',edit:c=>{c.members[0]!.tier='PREMIUM';}},{label:'age',edit:c=>{c.members[0]!.age='KIDS';}},{label:'product',edit:c=>{c.members[0]!.product='SINGLE';c.members[0]!.items=c.members[0]!.items.slice(0,1);}},{label:'store',edit:c=>{c.returnStore='ONSEN_BASE';}},{label:'period',edit:c=>{c.period.endDate=nextDay(c.period.endDate);}},{label:'slot',edit:c=>{c.period.endDate=c.period.startDate;c.period.slot='PM';}},{label:'reservation',edit:c=>{c.reservationId=randomUUID();}}];for(const x of changes){const c=structuredClone(v.hold!.conditions);x.edit(c);const r=await amend(v,c);console.log('SCOPE_REFUSAL '+x.label+' '+r.status());await rejected(r);await unchanged(v);}const input=structuredClone(v.preview.input);input.members.push({...structuredClone(input.members[0]!),key:'extra'});await rejected(await preview(v,input));await unchanged(v);});
 await check('other owner, fixed, unknown payment, transfer attention, stale version refused before mutation',async()=>{const v=await fresh('2035-07-15');await clock('2035-07-15T17:01:00+09:00');assert.equal((await preview(v,v.preview.input,other)).status(),403);assert.equal((await amend(v,change(v),randomUUID(),other)).status(),403);for(const [column,value] of [['allocation_stage','PREPARATION_FIXED'],['payment_state','UNKNOWN'],['transfer_attention','SYNTHETIC_ATTENTION']] as const){const c=await app!.db.pool.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('zao.actor',(SELECT id FROM auth_user WHERE email='continuation-owner@example.invalid'),true)");await c.query(`UPDATE inventory_holds SET ${column}=$1 WHERE id=$2`,[value,v.hold!.id]);await c.query('COMMIT');}finally{c.release();}await rejected(await preview(v));await rejected(await quote(v));await rejected(await amend(v));const reset=await app!.db.pool.connect();try{await reset.query('BEGIN');await reset.query("SELECT set_config('zao.actor',(SELECT id FROM auth_user WHERE email='continuation-owner@example.invalid'),true)");await reset.query(`UPDATE inventory_holds SET ${column}=$1 WHERE id=$2`,[column==='allocation_stage'?'PROVISIONAL':column==='payment_state'?'NONE':null,v.hold!.id]);await reset.query('COMMIT');}finally{reset.release();}}
  const a=await preview(v),b=await preview(v);assert.equal(a.status(),201);assert.equal(b.status(),201);const [va,vb]=await Promise.all([a.json(),b.json()]) as View[];const results=await Promise.all([post('/api/recommendations/'+va!.preview.id+'/select',{requestKey:randomUUID(),selection:{...selection(),directions:{'ski-a':'SHORTER','board-b':'RECOMMENDED'}}}),post('/api/recommendations/'+vb!.preview.id+'/select',{requestKey:randomUUID(),selection:{...selection(),directions:{'ski-a':'LONGER','board-b':'RECOMMENDED'}}})]);const values:View[]=await Promise.all(results.map(r=>r.json()));assert.equal(values.filter(x=>x.selection!.stage==='COMPLETE').length,1);assert.equal(values.filter(x=>x.selection!.outcome==='STALE_HOLD_VERSION').length,1);assert.equal((await reread(v)).expiresAt,v.hold!.expiresAt);
 });
 await check('two different holds race for last145cm after close; one succeeds, loser original retained',async()=>{const a=await fresh('2035-07-17');await clock('2035-07-17T16:56:00+09:00');const input=inputFor('2035-07-17');input.period.endDate=nextDay(input.period.startDate);input.period.slot='MULTIDAY';const r=await post('/api/recommendations',{requestKey:randomUUID(),input,replaceHoldId:null});assert.equal(r.status(),201);const p:View=await r.json();const br=await post('/api/recommendations/'+p.preview.id+'/select',{requestKey:randomUUID(),selection:{...selection(),directions:{'ski-a':'LONGER','board-b':'LONGER'}}});const b:View=await br.json();assert.equal(b.selection!.stage,'COMPLETE');await clock('2035-07-17T17:01:00+09:00');const results=await Promise.all([amend(a),amend(b)]);const values=await Promise.all(results.map(r=>r.json()));assert.equal(values.filter(v=>v.result==='AMENDED').length,1);assert.equal(values.filter(v=>v.result==='INSUFFICIENT').length,1);for(const [i,v]of [a,b].entries())if(values[i].result==='INSUFFICIENT')await unchanged(v);assert.equal((await app!.db.pool.query('SELECT count(*)::int AS n FROM (SELECT asset_id,day,count(*) FROM inventory_claims WHERE active AND asset_id IS NOT NULL GROUP BY asset_id,day HAVING count(*)>1) x')).rows[0].n,0);});
 await check('lost amendment HTTP response replays saved selection keys and expires honestly at17:05',async()=>{const v=await fresh('2035-07-19');await clock('2035-07-19T17:01:00+09:00');const p=await staff.newPage();try{await p.goto('/staff/recommendations');await p.getByRole('button',{name:new RegExp('推薦 '+v.preview.id.slice(0,8))}).click();const wait=p.waitForResponse(r=>r.url()===origin+'/api/recommendations'&&r.request().method()==='POST');await p.getByRole('button',{name:'推薦候補を確認',exact:true}).click();assert.equal((await wait).status(),201);await p.getByRole('button',{name:'短めを選ぶ 1',exact:true}).click();await p.getByRole('button',{name:'おすすめを選ぶ 2',exact:true}).click();await p.getByLabel('モデル指定なし・表示したサイズとクラスを選択条件とすることを確認').check();let saved:View|undefined;await p.route('**/api/recommendations/*/select',async route=>{const r=await route.fetch();saved=await r.json();await route.abort();});await p.getByRole('button',{name:'全員分をHOLDして見積を保存',exact:true}).click();await expect(p.getByRole('button',{name:'同じ要求を照合・再送'})).toBeVisible();assert.equal(saved?.selection?.stage,'COMPLETE');await p.unroute('**/api/recommendations/*/select');await clock('2035-07-19T17:05:00+09:00');await p.reload();await p.getByRole('button',{name:'同じ要求を照合・再送'}).click();await expect(p.getByRole('region',{name:'見積詳細',exact:true})).toContainText('EXPIRED');const after:View=await (await staff.request.get('/api/recommendations/'+saved!.preview.id)).json();assert.equal(after.hold!.id,v.hold!.id);assert.equal(after.hold!.state,'EXPIRED');assert.equal(after.quote!.snapshotSha256,saved!.quote!.snapshotSha256);assert.equal(after.selection!.hold_key,saved!.selection!.hold_key);assert.equal(after.selection!.quote_key,saved!.selection!.quote_key);assert.equal(after.hold!.expiresAt,v.hold!.expiresAt);}finally{await p.close();}});
 await check('HOLD saved then missing coupon quote fails; retry exact key after development coupon configuration',async()=>{const v=await fresh('2035-07-21');await clock('2035-07-21T17:01:00+09:00');const pr=await preview(v);assert.equal(pr.status(),201);const p:View=await pr.json();const selected=await post('/api/recommendations/'+p.preview.id+'/select',{requestKey:randomUUID(),selection:{...selection(),couponCode:'NOTCONFIGURED',directions:{'ski-a':'SHORTER','board-b':'RECOMMENDED'}}});const held:View=await selected.json();assert.equal(held.selection!.stage,'HOLD_SAVED');assert.equal(held.selection!.outcome,'COUPON_NOT_FOUND');const again:View=await (await post('/api/recommendations/'+p.preview.id+'/resume',{})).json();assert.equal(again.hold!.id,v.hold!.id);assert.equal(again.hold!.version,2);assert.equal(again.hold!.expiresAt,v.hold!.expiresAt);assert.equal(again.selection!.hold_key,held.selection!.hold_key);assert.equal(again.selection!.quote_key,held.selection!.quote_key);assert.equal(again.selection!.stage,'HOLD_SAVED');
  // Fault is missing synthetic configuration, not a fake quote response. Configure via
  // the existing privileged service on the owned DB, then recover through normal HTTP.
  const actor=(await app!.db.pool.query("SELECT id FROM auth_user WHERE email='continuation-owner@example.invalid'")).rows[0].id,principal=(await loadStaff(app!.roles.authPool,actor))!;
  await new QuoteService(app!.roles.pricingPool,principal).createCoupon(randomUUID(),{code:'NOTCONFIGURED',validFrom:'2035-07-21T16:00:00+09:00',validUntil:'2035-07-21T17:04:00+09:00',storeBasis:'PICKUP_STORE',stores:['MOUNTAIN_BASE'],products:PRICE_PRODUCTS.map(p=>p.key),kind:'FIXED_JPY',value:100,minimumJpy:0,minimumBasis:'CART_SUBTOTAL',maximumDiscountJpy:100,advanceCombination:'DENY',maxActiveReservations:null});
  const recovered:View=await (await post('/api/recommendations/'+p.preview.id+'/resume',{})).json();assert.equal(recovered.selection!.stage,'COMPLETE');assert.equal(recovered.selection!.quote_key,held.selection!.quote_key);assert.equal(recovered.hold!.expiresAt,v.hold!.expiresAt);assert.equal(recovered.quote!.snapshot.expiresAt,'2035-07-21T08:04:00.000Z');assert.equal(recovered.quote!.snapshot.couponDiscountJpy,100);assert.equal((await app!.db.pool.query('SELECT count(*)::int AS n FROM coupon_reservations')).rows[0].n,0);
 });
 await check('lock wait crossing17:05 rereads server clock and refuses amendment; forbidden never waits stock lock',async()=>{const v=await fresh('2035-07-23');await clock('2035-07-23T17:04:00+09:00');const c=await app!.db.pool.connect();try{await c.query('BEGIN');await c.query('SELECT pg_advisory_xact_lock(71820600)');const start=Date.now();assert.equal((await amend(v,change(v),randomUUID(),viewer)).status(),403);assert.ok(Date.now()-start<1000);const pending=amend(v);let waiting=false;for(let n=0;n<100;n++){waiting=(await app!.db.pool.query("SELECT 1 FROM pg_stat_activity WHERE usename=$1 AND wait_event='advisory'",[app!.roles.holdDb.user])).rowCount!>0;if(waiting)break;await new Promise(r=>setTimeout(r,5));}assert.equal(waiting,true);await clock('2035-07-23T17:05:00+09:00');await c.query('COMMIT');const r=await pending;if(r.ok())assert.equal((await r.json()).result,'EXPIRED');else await rejected(r);assert.equal((await reread(v)).state,'EXPIRED');assert.deepEqual((await reread(v)).conditions,v.hold!.conditions);}finally{await c.query('ROLLBACK');c.release();}});
 await check('cancel/read remain available after intake cutoff; operational reassign shares protection/no renewal',async()=>{const v=await fresh('2035-07-25');await clock('2035-07-25T17:01:00+09:00');const re=await post('/api/holds/'+v.hold!.id+'/reassign',{requestKey:randomUUID(),requirementKey:'ski-a:SKI',assetId:fid(1201)});assert.equal(re.status(),200);assert.equal((await re.json()).hold.expiresAt,v.hold!.expiresAt);const c=await post('/api/holds/'+v.hold!.id+'/cancel',{requestKey:randomUUID()});assert.equal((await c.json()).result,'RELEASED');assert.equal((await reread(v)).state,'RELEASED');});
 await check('direct domain key replay after expiry reads original amendment/quote; no recreation',async()=>{const v=await fresh('2035-07-27');await clock('2035-07-27T17:01:00+09:00');const key=randomUUID(),conditions=change(v),r=await amend(v,conditions,key);assert.equal(r.status(),200);const a=await r.json();assert.equal(a.result,'AMENDED');const quoteKey=randomUUID(),qr=await quote(v,conditions,quoteKey);assert.equal(qr.status(),201);const q=await qr.json();await clock('2035-07-27T17:05:00+09:00');const replay=await (await amend(v,conditions,key)).json();assert.equal(replay.replayed,true);assert.equal(replay.result,'AMENDED');assert.equal(replay.hold.state,'EXPIRED');assert.equal(replay.hold.version,a.hold.version);assert.equal(replay.hold.expiresAt,v.hold!.expiresAt);const qReplay=await (await quote(v,conditions,quoteKey)).json();assert.equal(qReplay.replayed,true);assert.equal(qReplay.quote.validity,'EXPIRED');assert.deepEqual(qReplay.quote.snapshot,q.quote.snapshot);assert.equal(qReplay.quote.snapshotSha256,q.quote.snapshotSha256);assert.equal((await app!.db.pool.query('SELECT count(*)::int AS n FROM price_quotes WHERE request_key=$1',[quoteKey])).rows[0].n,1);});
 await check('no client continuation flag and no unversioned after-close amend exemption',async()=>{const v=await fresh('2035-07-29');await clock('2035-07-29T17:01:00+09:00');for(const data of [{requestKey:randomUUID(),conditions:change(v)},{requestKey:randomUUID(),conditions:change(v),expectedVersion:'1'},{requestKey:randomUUID(),conditions:change(v),expectedVersion:1,allowAfterHours:true}])await rejected(await post('/api/holds/'+v.hold!.id+'/amend',data));await rejected(await post('/api/recommendations',{requestKey:randomUUID(),input:v.preview.input,replaceHoldId:v.hold!.id,continuation:true}));await rejected(await post('/api/quotes',{requestKey:randomUUID(),input:{conditions:v.hold!.conditions,holdId:v.hold!.id,couponCode:null,wantAdvance:false,allowAfterHours:true}}));await unchanged(v);});
 await check('quote waiting for inventory lock observes expiry before any price row insert',async()=>{const v=await fresh('2035-07-31');await clock('2035-07-31T17:04:00+09:00');const c=await app!.db.pool.connect(),key=randomUUID();try{await c.query('BEGIN');await c.query('SELECT pg_advisory_xact_lock(71820600)');const pending=quote(v,v.hold!.conditions,key);let waiting=false;for(let n=0;n<100;n++){waiting=(await app!.db.pool.query("SELECT 1 FROM pg_stat_activity WHERE usename=$1 AND wait_event='advisory'",[app!.roles.pricingDb.user])).rowCount!>0;if(waiting)break;await new Promise(r=>setTimeout(r,5));}assert.equal(waiting,true);await clock('2035-07-31T17:05:00+09:00');await c.query('COMMIT');assert.equal((await rejected(await pending)).error,'HOLD_EXPIRED_OR_RELEASED');assert.equal((await app!.db.pool.query('SELECT count(*)::int AS n FROM price_quotes WHERE request_key=$1',[key])).rows[0].n,0);await unchanged(v);}finally{await c.query('ROLLBACK');c.release();}});
 console.log(`E09-02 normal UI/API/real PostgreSQL: ${passed} passed; ${failed} failed; 0 skipped. Synthetic individual password sessions. Test-owner DB clock/synchronization only; no real device or live payment.`);
}catch(e){failed++;console.error('CONTINUATION_SETUP_FAILED '+(e as Error).name);if(e instanceof assert.AssertionError)console.error(JSON.stringify({actual:e.actual,expected:e.expected}));console.error((e as Error).stack?.split('\n').filter(l=>l.includes('/tests/recommendation/continuation-ui.ts:')).join('\n'));}finally{await browser.close();if(app)await app.stop();console.log('Owned continuation Web/browser/PostgreSQL stopped.');}if(failed)process.exit(1);
