import type {Pool} from 'pg';
import type {RecommendationInput} from '../../packages/contracts/src/recommendation';
import {seedInventory,fid,variants} from '../inventory/fixture';
export {fid,variants};
export const lengthVariants={ski145:fid(7101),ski135:fid(7102),ski165:fid(7103),ski134:fid(7104),ski166:fid(7105),board145:fid(7106),board155:fid(7107)};
export function inputFor(date='2035-01-05'):RecommendationInput{return {pickupStore:'MOUNTAIN_BASE',returnStore:'MOUNTAIN_BASE',period:{startDate:date,endDate:date,slot:'DAY'},members:[{key:'ski-a',sport:'SKI',heightCm:170,footCm:25.5,adultAtStart:true,tier:'REGULAR',ski:{weightKg:60,ageAtStart:30,level:'BEGINNER'},poleVariantId:variants.pole},{key:'board-b',sport:'SNOWBOARD',heightCm:170,footCm:25.5,adultAtStart:true,tier:'REGULAR',ski:null,poleVariantId:null}]};}
export function selection(){return {directions:{'ski-a':'RECOMMENDED','board-b':'RECOMMENDED'},wantAdvance:false,couponCode:null,acceptedModelPolicy:true};}
export async function seedRecommendation(pool:Pool,load=false){await seedInventory(pool);const c=await pool.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('zao.actor','synthetic-e09-seed',true),set_config('zao.reason','SYNTHETIC E09 fixture',true)");
 for(const [i,f,size]of [[7101,'SKI',145],[7102,'SKI',135],[7103,'SKI',165],[7104,'SKI',134],[7105,'SKI',166],[7106,'SNOWBOARD',145],[7107,'SNOWBOARD',155]] as const){await c.query(`INSERT INTO ledger_variants(id,model_id,family,age,tier,size,notes,source_kind,source_document,source_locator) VALUES($1,$2,$3,'ADULT','REGULAR',$4,'','SYNTHETIC','tests/recommendation/fixture.ts',$5) ON CONFLICT DO NOTHING`,[fid(i),fid(f==='SKI'?1001:1004),f,size+' cm','variant-'+i]);await c.query(`INSERT INTO ledger_assets(id,variant_id,family,initial_store_id,store_id,status,bsl_status,bsl_evidence,notes,source_kind,source_document,source_locator) VALUES($1,$2,$3,'MOUNTAIN_BASE','MOUNTAIN_BASE','AVAILABLE','NOT_APPLICABLE','','','SYNTHETIC','tests/recommendation/fixture.ts',$4) ON CONFLICT DO NOTHING`,[fid(i+100),fid(i),f,'asset-'+(i+100)]);}
 // Three boots per sport make board scarcity (not an accidental boot shortage) observable.
 for(const [i,v,f]of [[7301,variants.boot,'SKI_BOOT'],[7302,variants.boot,'SKI_BOOT'],[7303,variants.boardBoot,'SNOWBOARD_BOOT'],[7304,variants.boardBoot,'SNOWBOARD_BOOT']] as const)await c.query(`INSERT INTO ledger_assets(id,variant_id,family,initial_store_id,store_id,status,bsl_status,bsl_evidence,notes,source_kind,source_document,source_locator) VALUES($1,$2,$3,'MOUNTAIN_BASE','MOUNTAIN_BASE','AVAILABLE',$4,'','','SYNTHETIC','tests/recommendation/fixture.ts',$5) ON CONFLICT DO NOTHING`,[fid(i),v,f,f==='SKI_BOOT'?'UNVERIFIED':'NOT_APPLICABLE','asset-'+i]);
 if(load){for(const [family,variant,count]of [['SKI',variants.ski,143],['SNOWBOARD',variants.board,147],['SKI_BOOT',variants.boot,147],['SNOWBOARD_BOOT',variants.boardBoot,147]] as const)for(let n=0;n<count;n++)await c.query(`INSERT INTO ledger_assets(id,variant_id,family,initial_store_id,store_id,status,bsl_status,bsl_evidence,notes,source_kind,source_document,source_locator) VALUES($1,$2,$3,'MOUNTAIN_BASE','MOUNTAIN_BASE','AVAILABLE',$4,'','','SYNTHETIC','tests/recommendation/fixture.ts',$5)`,[fid(10000+['SKI','SNOWBOARD','SKI_BOOT','SNOWBOARD_BOOT'].indexOf(family)*1000+n),variant,family,family==='SKI_BOOT'?'UNVERIFIED':'NOT_APPLICABLE','LOAD-'+family+'-'+n]);}
 await c.query('UPDATE ledger_poles SET quantity=$1,version=version+1 WHERE id=$2',[load?150:3,fid(1301)]);await c.query('COMMIT');
 }catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
