import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
import {mkdir,writeFile} from 'node:fs/promises';
import {chromium,expect,type BrowserContext,type Page} from '@playwright/test';
import {startDevelopmentApp} from '../../scripts/development-app';
import {bootstrapDevelopmentAdmin} from '../../scripts/bootstrap-staff';
import {seedRecommendation,variants,lengthVariants,inputFor} from './fixture';
let app:Awaited<ReturnType<typeof startDevelopmentApp>>|undefined,lastPage:Page|undefined;let stage='startup',count=0,failed=false;const browser=await chromium.launch(),password=randomBytes(24).toString('base64url');
async function check(name:string,fn:()=>Promise<void>){stage=name;await fn();count++;console.log('PASS '+name);}
try{
 app=await startDevelopmentApp({built:true});await seedRecommendation(app.db.pool,true);
 // Two units give each alternate length one public slot. Two skiers still cannot
 // both take the scarce 145cm direction under the unchanged 95% ceiling.
 const directionVariants=[variants.skiAlt,...Object.values(lengthVariants)],seed=await app.db.pool.connect();
 try{await seed.query('BEGIN');await seed.query("SELECT set_config('zao.actor','synthetic-e09-ui',true),set_config('zao.reason','SYNTHETIC directional public capacity',true)");
  await seed.query(`INSERT INTO ledger_assets(id,variant_id,family,initial_store_id,store_id,status,bsl_status,bsl_evidence,notes,source_kind,source_document,source_locator)
   SELECT gen_random_uuid(),id,family,'MOUNTAIN_BASE','MOUNTAIN_BASE','AVAILABLE','NOT_APPLICABLE','','SYNTHETIC public direction','SYNTHETIC','tests/recommendation/normal-ui.ts','public-direction-'||id FROM ledger_variants WHERE id=ANY($1::uuid[])`,[directionVariants]);
  assert.ok((await seed.query('SELECT variant_id,count(*)::int n FROM ledger_assets WHERE variant_id=ANY($1::uuid[]) GROUP BY variant_id',[directionVariants])).rows.every(r=>r.n===2));await seed.query('COMMIT');
 }catch(e){await seed.query('ROLLBACK');throw e;}finally{seed.release();}
 await bootstrapDevelopmentAdmin(app.db.pool,{email:'e09-ui-bootstrap@example.invalid',displayName:'合成初期ADMIN',password});const {origin}=app;
 await app.db.pool.query("CREATE OR REPLACE FUNCTION inventory_clock() RETURNS timestamptz LANGUAGE sql VOLATILE AS $$SELECT '2035-01-01T00:00:00Z'::timestamptz$$");
 for(let i=0;i<100;i++){try{if((await fetch(origin+'/api/health')).ok)break;}catch{}if(i===99)throw new Error('APP_START_TIMEOUT');await new Promise(r=>setTimeout(r,100));}
 async function context(){const c=await browser.newContext({baseURL:origin,viewport:{width:1280,height:960}});c.setDefaultTimeout(10000);return c;}
 async function login(c:BrowserContext,email:string){const p=await c.newPage();await p.goto('/staff/login');await p.getByLabel('メールアドレス',{exact:true}).fill(email);await p.getByLabel('パスワード',{exact:true}).fill(password);await p.getByRole('button',{name:'ログイン',exact:true}).click();await p.waitForURL(origin+'/staff/ledger');return p;}
 const bootstrap=await context(),admin=await context(),staff=await context(),anon=await context();const bp=await login(bootstrap,'e09-ui-bootstrap@example.invalid');
 await check('normal ADMIN creates explicit permissions; no authentication bypass; anonymous preview denied',async()=>{
  assert.equal((await anon.request.get('/api/recommendations/options')).status(),401);assert.equal((await bootstrap.request.get('/api/recommendations')).status(),403);await bp.goto('/staff/users');lastPage=bp;
  for(const [email,name,isAdmin]of [['e09-ui-price@example.invalid','合成料金管理',true],['e09-ui-staff@example.invalid','合成推薦担当',false]] as const){await bp.getByRole('button',{name:'スタッフを作成',exact:true}).click();const f=bp.getByRole('form',{name:'スタッフ作成'});await f.getByLabel('表示名',{exact:true}).fill(name);await f.getByLabel('メールアドレス',{exact:true}).fill(email);await f.getByLabel('初期パスワード（15〜128文字）').fill(password);await f.getByLabel('Role',{exact:true}).selectOption(isAdmin?'ADMIN':'STAFF');await f.getByLabel('店舗範囲',{exact:true}).selectOption(isAdmin?'ALL':'ASSIGNED');if(!isAdmin)await f.getByLabel('MOUNTAIN_BASE',{exact:true}).check();for(const label of ['自分の非公開見積閲覧','自分の非公開見積作成','期間在庫・自分のHOLD閲覧','自分のHOLD取得・変更',...(isAdmin?['開発用料金版の設定（全店ADMINのみ）']:[])])await f.getByLabel(label,{exact:true}).selectOption('allow');await f.getByRole('button',{name:'スタッフ設定を保存'}).click();await expect(bp.getByRole('heading',{name,exact:true})).toBeVisible();}
 });
 const ap=await login(admin,'e09-ui-price@example.invalid'),page=await login(staff,'e09-ui-staff@example.invalid');lastPage=page;
 await ap.goto('/staff/quotes');await ap.getByLabel('料金の対象開始日').fill('2035-01-01');await ap.getByLabel('料金の対象終了日').fill('2036-12-31');await ap.getByRole('button',{name:'開発用の初期料金を設定'}).click();await expect(ap.getByRole('region',{name:'料金版',exact:true})).toContainText('PRIVATE_AVAILABLE');
 async function profile(i:number,sport:'SKI'|'SNOWBOARD'){await page.getByLabel('競技 '+i,{exact:true}).selectOption(sport);await page.getByLabel('利用開始時の年齢区分 '+i,{exact:true}).selectOption('ADULT');await page.getByLabel('身長cm '+i,{exact:true}).fill('170');await page.getByLabel('足サイズcm '+i,{exact:true}).fill('25.5');if(sport==='SKI'){await page.getByLabel('体重kg '+i,{exact:true}).fill('60');await page.getByLabel('利用開始時の年齢 '+i,{exact:true}).fill('30');await page.getByLabel('レベル '+i,{exact:true}).selectOption('BEGINNER');await page.getByLabel('ポールのサイズ '+i,{exact:true}).selectOption(variants.pole);}}
 async function accept(){await page.getByLabel('モデル指定なし・表示したサイズとクラスを選択条件とすることを確認').check();}
 let previewId='',holdId='',quoteId='',holdExpiry='';
 await check('mixed ski/board inputs -> real period/stock recommendations; board discards unnecessary ski inputs',async()=>{await page.goto('/staff/recommendations');await expect(page.getByRole('heading',{name:'サイズ選択からHOLD・見積へ'})).toBeVisible();await page.getByLabel('利用開始日',{exact:true}).fill('2035-01-05');await page.getByLabel('利用終了日',{exact:true}).fill('2035-01-05');await page.getByLabel('利用区分',{exact:true}).selectOption('AM');await profile(1,'SKI');await page.getByRole('button',{name:'利用者を追加',exact:true}).click();await profile(2,'SKI');await page.getByLabel('競技 2',{exact:true}).selectOption('SNOWBOARD');await expect(page.getByLabel('体重kg 2',{exact:true})).toHaveCount(0);await expect(page.getByLabel('利用開始時の年齢 2',{exact:true})).toHaveCount(0);await expect(page.getByLabel('レベル 2',{exact:true})).toHaveCount(0);await page.getByRole('button',{name:'推薦候補を確認',exact:true}).click();await expect(page.getByRole('region',{name:'推薦候補',exact:true})).toContainText('大きめ推奨');for(const n of [1,2]){const card=page.getByRole('article',{name:'利用者 '+n+' の候補'});await expect(card).toContainText('基準 150cm');await expect(card).toContainText('145 cm');await expect(card).toContainText('155 cm');await expect(card).toContainText('ブーツ 26.5cm');}assert.equal((await app!.db.pool.query('SELECT count(*)::int AS n FROM inventory_holds')).rows[0].n,0);assert.equal((await app!.db.pool.query('SELECT count(*)::int AS n FROM price_quotes')).rows[0].n,0);});
 await check('selection -> group HOLD -> price DB commit, lost response/reload recovers exactly once',async()=>{for(const i of [1,2])await page.getByRole('button',{name:'おすすめを選ぶ '+i,exact:true}).click();await accept();await page.getByLabel('早割5％の適用見込みを確認').check();await page.route('**/api/recommendations/*/select',async route=>{const r=await route.fetch();assert.equal(r.status(),200);const v=await r.json();assert.equal(v.selection.stage,'COMPLETE');previewId=v.preview.id;holdId=v.hold.id;quoteId=v.quote.id;holdExpiry=v.hold.expiresAt;await route.abort('failed');});await page.getByRole('button',{name:'全員分をHOLDして見積を保存',exact:true}).click();await expect(page.getByRole('button',{name:'同じ要求を照合・再送'})).toBeVisible();await page.unroute('**/api/recommendations/*/select');await page.reload();await page.getByRole('button',{name:'同じ要求を照合・再送'}).click();await expect(page.getByRole('region',{name:'見積詳細',exact:true})).toContainText('10,640 円');await expect(page.getByRole('region',{name:'保存結果',exact:true})).toContainText(holdId);const row=(await app!.db.pool.query('SELECT count(*)::int AS n FROM price_quotes WHERE id=$1',[quoteId])).rows[0];assert.equal(row.n,1);assert.equal((await app!.db.pool.query('SELECT count(*)::int AS n FROM inventory_holds')).rows[0].n,1);await mkdir('.local/screenshots',{recursive:true});await page.screenshot({path:'.local/screenshots/e09-recommendation-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'.local/screenshots/e09-recommendation-mobile-width.png',fullPage:true});await page.setViewportSize({width:1280,height:960});});
 await check('changed conditions hide old quote, successful length/day amendment preserves same HOLD and TTL',async()=>{await page.getByLabel('利用開始日',{exact:true}).fill('2035-01-06');await page.getByLabel('利用終了日',{exact:true}).fill('2035-01-06');await expect(page.getByRole('region',{name:'見積詳細',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'推薦候補を確認',exact:true}).click();await expect(page.getByRole('region',{name:'推薦候補',exact:true})).toBeVisible();await page.getByRole('button',{name:'短めを選ぶ 1',exact:true}).click();await page.getByRole('button',{name:'長めを選ぶ 2',exact:true}).click();await accept();await page.getByRole('button',{name:'全員分をHOLDして見積を保存',exact:true}).click();await expect(page.getByRole('region',{name:'保存結果',exact:true})).toContainText('COMPLETE');const r=(await app!.db.pool.query('SELECT * FROM inventory_holds WHERE id=$1',[holdId])).rows[0];assert.equal(r.version,2);assert.equal(r.expires_at.toISOString(),holdExpiry);assert.equal(r.conditions.period.startDate,'2035-01-06');assert.equal((await staff.request.get('/api/quotes/'+quoteId)).status(),200);assert.equal((await (await staff.request.get('/api/quotes/'+quoteId)).json()).validity,'HOLD_CONDITIONS_MISMATCH');});
 await check('last145 candidate for two skiers cannot double-allocate; old group stays held and no old amount masquerades as new',async()=>{const before=(await app!.db.pool.query('SELECT conditions,version FROM inventory_holds WHERE id=$1',[holdId])).rows[0];await page.getByRole('button',{name:'利用者を追加',exact:true}).click();await profile(3,'SKI');await page.getByRole('button',{name:'推薦候補を確認',exact:true}).click();await expect(page.getByRole('article',{name:'利用者 3 の候補'})).toBeVisible();for(const i of [1,3])await page.getByRole('button',{name:'短めを選ぶ '+i,exact:true}).click();await page.getByRole('button',{name:'おすすめを選ぶ 2',exact:true}).click();await accept();await page.getByRole('button',{name:'全員分をHOLDして見積を保存',exact:true}).click();await expect(page.getByRole('region',{name:'保存結果',exact:true})).toContainText('HOLD_FAILED');await expect(page.getByRole('region',{name:'保存結果',exact:true})).toContainText('INSUFFICIENT');assert.deepEqual((await app!.db.pool.query('SELECT conditions,version FROM inventory_holds WHERE id=$1',[holdId])).rows[0],before);await expect(page.getByRole('region',{name:'見積詳細',exact:true})).toHaveCount(0);});
 await check('late preview response cannot restore old input or overwrite a changed/removed member',async()=>{await page.getByRole('button',{name:'利用者 3 を除く',exact:true}).click();let fetched=false;let release!:()=>void;const gate=new Promise<void>(r=>release=r);await page.route(origin+'/api/recommendations',async route=>{if(route.request().method()!=='POST'){await route.continue();return;}const response=await route.fetch();fetched=true;await gate;await route.fulfill({response});});await page.getByRole('button',{name:'推薦候補を確認',exact:true}).click();await expect.poll(()=>fetched).toBe(true);await page.getByLabel('身長cm 1',{exact:true}).fill('180');await page.getByRole('button',{name:'利用者 2 を除く',exact:true}).click();const delivered=page.waitForResponse(r=>r.url()===origin+'/api/recommendations'&&r.request().method()==='POST');release();await delivered;await page.unroute(origin+'/api/recommendations');await expect(page.getByLabel('身長cm 1',{exact:true})).toHaveValue('180');await expect(page.getByLabel('競技 2',{exact:true})).toHaveCount(0);await expect(page.getByRole('region',{name:'推薦候補',exact:true})).toHaveCount(0);});
 await check('E09-01 unavailable direction shows no price while actual recommended candidate remains priced',async()=>{for(const test of [{height:'200',target:180,length:166,direction:'長め'},{height:'149',target:129,length:134,direction:'短め'}]){await page.getByLabel('身長cm 1',{exact:true}).fill(test.height);await page.getByRole('button',{name:'推薦候補を確認',exact:true}).click();const member=page.getByRole('article',{name:'利用者 1 の候補'});await expect(member).toContainText('基準 '+test.target+'cm');const recommended=page.getByRole('button',{name:'おすすめを選ぶ 1',exact:true});await expect(recommended).toBeEnabled();await expect(recommended.locator('..')).toContainText(test.length+' cm');await expect(recommended.locator('..')).toContainText('割引前の参考額');const button=page.getByRole('button',{name:test.direction+'を選ぶ 1',exact:true}),card=button.locator('..');await expect(button).toBeDisabled();await expect(card).toContainText('該当する在庫候補なし／選択不可');console.log('E09_01 '+JSON.stringify({direction:test.direction,candidate:false,referencePriceVisible:(await card.textContent())!.includes('割引前の参考額')}));await expect(card).not.toContainText('割引前の参考額');await expect(card).not.toContainText('料金未確認');}});
 await check('308 combined equipment sets, 300 boot pairs and150 pole pairs: fresh E09 HTTP latency at concurrency1/4',async()=>{const counts=(await app!.db.pool.query('SELECT family,count(*)::int AS n FROM ledger_assets GROUP BY family')).rows;assert.equal(counts.filter(x=>['SKI','SNOWBOARD'].includes(x.family)).reduce((n,x)=>n+x.n,0),308);assert.equal(counts.filter(x=>x.family.endsWith('BOOT')).reduce((n,x)=>n+x.n,0),300);const results=[];for(const concurrency of [1,4]){const times:number[]=[];let errors=0;for(let batch=0;batch<8;batch++){await Promise.all(Array.from({length:concurrency},async()=>{const start=performance.now();const r=await staff.request.post('/api/recommendations',{headers:{origin},data:{requestKey:randomUUID(),input:inputFor('2035-05-01'),replaceHoldId:null}});const v=await r.json();times.push(performance.now()-start);if(r.status()!==201||!v.preview?.offered.every((o:{candidates:{RECOMMENDED:unknown}})=>o.candidates.RECOMMENDED))errors++;}));}times.sort((a,b)=>a-b);results.push({concurrency,requests:times.length,errors,p50Ms:times[Math.ceil(times.length*.5)-1],p95Ms:times[Math.ceil(times.length*.95)-1],rawMs:times});assert.equal(errors,0);}const report={task:'E09',source:'tests/recommendation/fixture.ts SYNTHETIC',equipmentCount:308,composition:'156 ski pairs +152 boards; 300 boot pairs;150 pole pairs',membersPerRequest:2,period:'2035-05-01 DAY',measurement:'Playwright APIRequestContext HTTP loopback start through response JSON; includes Next/session/auth, PostgreSQL feasibility, price read and saved preview; not isolated compute or DB time',warmup:'prior functional UI requests; no per-scenario excluded warmup',platform:process.platform,node:process.version,realDevice:false,results};await mkdir('.local/benchmarks',{recursive:true});await writeFile('.local/benchmarks/e09-recommendation-http.json',JSON.stringify(report,null,2));console.log('E09_BENCHMARK '+JSON.stringify(results.map(r=>({concurrency:r.concurrency,requests:r.requests,errors:r.errors,p50Ms:r.p50Ms,p95Ms:r.p95Ms}))));});
 await check('ordinary protected paths reject foreign owner, CSRF, forged amounts and outside-store access',async()=>{const body={requestKey:randomUUID(),input:inputFor('2035-05-02'),replaceHoldId:null};assert.equal((await staff.request.post('/api/recommendations',{data:body})).status(),403);assert.equal((await staff.request.post('/api/recommendations',{headers:{origin},data:{...body,totalJpy:1}})).status(),422);const outside=structuredClone(body);outside.input.pickupStore='ONSEN_BASE';assert.equal((await staff.request.post('/api/recommendations',{headers:{origin},data:outside})).status(),403);assert.equal((await admin.request.get('/api/recommendations/'+previewId)).status(),403);});
 await check('logout/login re-reads server saved results, permission removal closes preview and protected API',async()=>{await page.getByRole('link',{name:'ログアウト',exact:true}).click();await page.getByRole('button',{name:'ログアウトする',exact:true}).click();await page.waitForURL(origin+'/staff/login');assert.equal((await staff.request.get('/api/recommendations')).status(),401);const next=await login(staff,'e09-ui-staff@example.invalid');lastPage=next;await next.goto('/staff/recommendations');await next.getByRole('button',{name:new RegExp('推薦 '+previewId.slice(0,8))}).click();await expect(next.getByRole('region',{name:'保存結果',exact:true})).toContainText(holdId);await expect(next.getByRole('region',{name:'保存結果',exact:true})).toContainText('一致しません');await expect(next.getByRole('region',{name:'見積詳細',exact:true})).toHaveCount(0);await bp.getByRole('button',{name:'スタッフを編集：合成推薦担当'}).click();const f=bp.getByRole('form',{name:'スタッフ更新'});await f.getByLabel('期間在庫・自分のHOLD閲覧',{exact:true}).selectOption('deny');await f.getByRole('button',{name:'スタッフ設定を保存'}).click();await expect(f).toHaveCount(0);await next.reload();await expect(next.getByRole('heading',{name:'推薦プレビューの利用権限が必要です'})).toBeVisible();assert.equal((await staff.request.get('/api/recommendations')).status(),403);});
 console.log(`E09 ordinary UI/API/PostgreSQL: ${count} passed; 0 skipped. Actual synthetic email/password sessions. Only response delivery/delay is simulated after real server work. 1280/390 viewport is not a physical phone.`);
}catch(e){console.error('E09_UI_FAILED '+stage+' '+(e as Error).name);console.error((e as Error).stack?.split('\n').filter(l=>l.includes('/tests/recommendation/normal-ui.ts:')).join('\n'));if(lastPage&&['/staff/recommendations','/staff/users'].includes(new URL(lastPage.url()).pathname)){console.error('UI_STATUS '+await lastPage.getByRole('status').textContent().catch(()=>''));await mkdir('.local/screenshots',{recursive:true});await lastPage.screenshot({path:'.local/screenshots/e09-failure.png',fullPage:true});}failed=true;}finally{await browser.close();if(app)await app.stop();console.log('Owned E09 Web, browser and PostgreSQL stopped.');}if(failed)process.exit(1);
