import assert from 'node:assert/strict';
import {chromium,expect} from '@playwright/test';
import {randomUUID,randomBytes} from 'node:crypto';
import {mkdir} from 'node:fs/promises';
import {startFlowApp} from '../flow/launcher';
import {seedRecommendation,variants} from '../recommendation/fixture';
import {bootstrapDevelopmentAdmin} from '../../scripts/bootstrap-staff';
import {loadStaff} from '../../packages/auth/src/staff-auth';
import {QuoteService} from '../../packages/core/src/pricing/quote-service';
const browser=await chromium.launch();let app:Awaited<ReturnType<typeof startFlowApp>>|undefined,failed=false,stage='setup';
try{
 app=await startFlowApp({publicP0:true,publicP1:true,publicP4:true});await seedRecommendation(app.db.pool,true);
 const clock=async(t:string)=>{assert.match(t,/^[0-9:T+-]+$/);await app!.db.pool.query(`CREATE OR REPLACE FUNCTION inventory_clock() RETURNS timestamptz LANGUAGE sql VOLATILE AS $$SELECT '${t}'::timestamptz$$`);};await clock('2035-01-01T10:00:00+09:00');
 const root=await bootstrapDevelopmentAdmin(app.db.pool,{email:'p4-root@example.invalid',displayName:'SYNTHETIC P4',password:randomBytes(24).toString('base64url')});for(const permission of ['QUOTE_VIEW','QUOTE_CREATE','PRICE_EDIT'])await app.db.pool.query('INSERT INTO staff_permission_overrides(staff_id,permission,allowed) VALUES($1,$2,true)',[root,permission]);await new QuoteService(app.roles.pricingPool,(await loadStaff(app.db.pool,root))!).initializePrivate(randomUUID(),'2035-01-01','2035-12-31');
 const context=await browser.newContext({baseURL:app.origin,viewport:{width:390,height:844},hasTouch:true});context.setDefaultTimeout(15000);const page=await context.newPage();
 stage='ordinary guest UI confirmation';await page.goto('/ja/book');await expect(page.getByLabel('利用開始日',{exact:true})).toBeEnabled();await page.getByLabel('利用開始日',{exact:true}).fill('2035-01-05');await page.getByLabel('利用終了日',{exact:true}).fill('2035-01-05');await page.getByRole('button',{name:'用品を選ぶ',exact:true}).click();await page.getByLabel('ポールのサイズ 1',{exact:true}).selectOption('pole-'+variants.pole);await page.getByRole('button',{name:'候補と参考料金を確認',exact:true}).click();await page.getByRole('radio',{name:/おすすめ/}).check();await page.getByRole('checkbox',{name:'全員のサイズ・モデル条件・ウェア構成を確認した'}).check();await page.getByRole('button',{name:'全員分の最終確認へ'}).click();await page.getByRole('checkbox',{name:'合成データによる開発確認であることを確認'}).check();await page.getByRole('button',{name:'この内容で予約を確定する（開発用決済）'}).click();await expect(page.getByRole('heading',{name:'予約が確認されました',exact:true})).toBeVisible();
 console.log('PASS normal guest UI -> protected API -> synthetic payment -> confirmed real PostgreSQL booking');
 stage='exact refund preview and final confirmation';
 const before=(await app.db.pool.query('SELECT id,state,price_snapshot FROM rental_bookings')).rows[0];
 await page.getByRole('button',{name:'予約閲覧をこの端末へ保存'}).click();await expect(page.getByRole('link',{name:'保存した予約とQRを開く'})).toBeVisible();
 await page.getByRole('button',{name:'予約をキャンセル',exact:true}).click();const preview=page.getByRole('region',{name:'予約のキャンセル',exact:true});await expect(preview).toContainText(new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(before.price_snapshot.totalJpy));
 assert.equal((await app.db.pool.query('SELECT state FROM rental_bookings WHERE id=$1',[before.id])).rows[0].state,'CONFIRMED_DEV');await page.getByRole('button',{name:'予約を維持する'}).click();await expect(page.getByRole('button',{name:'この返金額でキャンセルを確定'})).toHaveCount(0);
 await page.getByRole('button',{name:'予約をキャンセル',exact:true}).click();await expect(page.getByRole('button',{name:'この返金額でキャンセルを確定'})).toBeVisible();
 let lost!:()=>void;const committed=new Promise<void>(r=>lost=r);await page.route('**/api/guest/cancel',async route=>{const response=await route.fetch();assert.equal(response.status(),200);await route.abort('failed');lost();});await page.getByRole('button',{name:'この返金額でキャンセルを確定'}).click();await committed;await page.unroute('**/api/guest/cancel');await page.reload();
 await expect(page.getByRole('heading',{name:'予約をキャンセルしました'})).toBeVisible();await expect(page.getByRole('region',{name:'キャンセル状況'})).toContainText('返金処理待ち');assert.equal((await app.db.pool.query('SELECT count(*)::int n FROM booking_cancellations WHERE booking_id=$1',[before.id])).rows[0].n,1);assert.equal((await app.db.pool.query('SELECT count(*)::int n FROM booking_cancellation_refunds WHERE booking_id=$1',[before.id])).rows[0].n,1);
 await page.goto('/en/book');await expect(page.getByRole('region',{name:'Cancellation status'})).toContainText('Refund pending');await expect(page.getByRole('img')).toHaveCount(0);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mkdir('.local/screenshots',{recursive:true});await page.screenshot({path:'.local/screenshots/cancellation-en-mobile.png',fullPage:true});
 await page.goto('/en/reservation');await expect(page.getByRole('region',{name:'Saved booking'})).toContainText('Booking cancelled');await expect(page.getByRole('img',{name:'Saved booking QR'})).toHaveCount(0);
 console.log('PASS JA refund preview before final action, keep booking, committed cancellation response loss/reload, one cancellation/refund, EN pending status, cancelled read-only access has no QR. Synthetic real PostgreSQL; actual refund/mail requests 0.');
}catch(e){failed=true;console.error('CANCELLATION_UI_FAILED '+stage+' '+(e as Error).name);console.error((e as Error).stack?.split('\n').filter(s=>s.includes('/tests/readiness/')).join('\n'));}finally{await browser.close();await app?.stop();}if(failed)process.exit(1);
