import assert from 'node:assert/strict';
import {createHmac,randomUUID,randomBytes} from 'node:crypto';
import {writeFileSync} from 'node:fs';
import type {Pool,PoolClient} from 'pg';
import {provisionPaymentActivationRoles} from '../../scripts/payment-activation-roles';
import {PgSquareWebhookInbox,type InboxPool,type InboxConnection} from '../../packages/db/src/square-webhook-inbox';
import {PgPaymentReconciliation} from '../../packages/db/src/payment-reconciliation';
import {PgPaymentProjection} from '../../packages/db/src/payment-projection';
import {TransactionalPaymentProjection,type ProjectionReference,type ProjectionSource} from '../../packages/core/src/payment/payment-projection';
import {type JobOutcome} from '../../packages/core/src/payment/payment-reconciliation';
import {decidePaymentTruth} from '../../packages/core/src/payment/payment-truth';
import {squareWebhookReceiver} from '../../packages/core/src/payment/square-webhook-receiver';
import {additional} from './r14-additional';
import {captureDbEvidence} from './r14-evidence';
import {fork} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {flowHash} from '../../packages/contracts/src/rental-flow';
import {normalizePeriod} from '../../packages/contracts/src/hold';
import {id,stateFixture,observation} from '../fixtures/payment-projection';
export type DB={pool:Pool;identity:{namespace:string;database:string;dbPort:number};r14?:{roles:Awaited<ReturnType<typeof provisionPaymentActivationRoles>>;completed:Set<string>}};
const event=()=>({environment:'SANDBOX' as const,eventId:'r14_'+randomUUID(),type:'payment.updated' as const,merchantId:'fixture-merchant',paymentId:'fixture-payment',bodySha256:flowHash(randomUUID())});
export function scoped(c:PoolClient,role:string):InboxPool{
 assert.match(role,/^zr_[a-f0-9]{12}_pay_[a-z]+$/);
 return {async connect(){await c.query('SET LOCAL ROLE '+role);return {query:async(sql:string,args?:unknown[])=>{
  if(sql==='BEGIN')return c.query('SAVEPOINT r14_boundary');
  if(sql==='COMMIT'){const v=await c.query('RELEASE SAVEPOINT r14_boundary');await c.query('RESET ROLE');return v;}
  if(sql==='ROLLBACK'){await c.query('ROLLBACK TO SAVEPOINT r14_boundary');const v=await c.query('RELEASE SAVEPOINT r14_boundary');await c.query('RESET ROLE');return v;}
  try{return await c.query(sql,args);}catch(error){const e=error as {code?:string;column?:string;table?:string;constraint?:string;routine?:string;position?:string};console.log('R14_SQL_FAILURE '+JSON.stringify({operation:sql.split(' ').slice(0,3).join(' '),code:e.code,column:e.column,table:e.table,constraint:e.constraint,routine:e.routine,position:e.position}));throw error;}
 },release(){}} as InboxConnection;}};
}
const source=async(c:InboxConnection,ref:ProjectionReference)=>(await c.query<{source:ProjectionSource}>('SELECT payment_projection.lock_source($1) AS source',[ref.jobId])).rows[0]?.source??null;
const projector=(pool:InboxPool)=>new TransactionalPaymentProjection(new PgPaymentProjection(pool,source));
export async function seed(p:Pool,merchantId='fixture-merchant',providerId:string|null='fixture-payment'){
 if((await p.query('SELECT 1 FROM rental_bookings WHERE id=$1',[id(1)])).rowCount)return;
 const c=await p.connect(),s=stateFixture(),period=normalizePeriod(s.booking.conditions.period);try{await c.query('BEGIN');
 await c.query("SELECT set_config('zao.actor','synthetic-actor',true),set_config('zao.reason','R14 SYNTHETIC 100 JPY test fixture',true)");
 await c.query(`INSERT INTO auth_user(id,name,email,"createdAt","updatedAt") VALUES('synthetic-actor','SYNTHETIC R14','synthetic-r14@example.invalid',now(),now())`);
 await c.query("INSERT INTO staff_members(id,active,role,scope) VALUES('synthetic-actor',false,'VIEWER','ASSIGNED')");
 for(const [n,family] of [[6,'SKI'],[7,'WEAR_JACKET'],[8,'WEAR_PANTS']] as const){
  await c.query(`INSERT INTO ledger_models(id,code,name,brand,family,notes,source_kind,source_document,source_locator,catalog_season) VALUES($1,$2,$2,'SYNTHETIC',$3,'SYNTHETIC only','SYNTHETIC','tests/readiness/r14-postgres.ts',$2,'2034/35')`,[id(n+30),'R14-'+family,family]);
  await c.query(`INSERT INTO ledger_variants(id,model_id,family,age,tier,size,notes,source_kind,source_document,source_locator,compatible_sports) VALUES($1,$2,$3,'ADULT',$4,$5,'','SYNTHETIC','tests/readiness/r14-postgres.ts',$3,$6)`,[id(n),id(n+30),family,n===6?'REGULAR':'STANDARD',n===6?'150 cm':'M',n===6?null:['SKI','SNOWBOARD']]);
  if(n===6)await c.query(`INSERT INTO ledger_assets(id,variant_id,family,initial_store_id,store_id,status,bsl_status,bsl_evidence,notes,source_kind,source_document,source_locator) VALUES($1,$2,'SKI','MOUNTAIN_BASE','MOUNTAIN_BASE','AVAILABLE','NOT_APPLICABLE','','','SYNTHETIC','tests/readiness/r14-postgres.ts','one pair')`,[id(50),id(n)]);
  else await c.query("INSERT INTO wear_pools(id,variant_id,store_id,ready) VALUES($1,$2,'MOUNTAIN_BASE',2)",[id(n+50),id(n)]);
 }
 await c.query("INSERT INTO inventory_reservations VALUES($1,'synthetic-actor')",[id(1)]);
 await c.query(`INSERT INTO inventory_holds(id,reservation_id,owner_id,pickup_store,return_store,conditions,starts_at,due_at,occupancy_start,occupancy_end,expires_at,state,payment_state) VALUES($1,$2,'synthetic-actor','MOUNTAIN_BASE','ONSEN_BASE',$3,$4,$5,'2035-01-01','2035-01-01',$6,'ACTIVE','PENDING')`,[id(2),id(1),s.booking.conditions,period.startsAt,period.dueAt,s.hold!.expiresAt]);
 await c.query("INSERT INTO inventory_claims(hold_id,requirement_key,asset_id,day) VALUES($1,'one:SKI',$2,'2035-01-01')",[id(2),id(50)]);
 for(const [n,f]of [[7,'WEAR_JACKET'],[8,'WEAR_PANTS']] as const)await c.query('INSERT INTO wear_claims(hold_id,requirement_key,pool_id,day,quantity) VALUES($1,$2,$3,$4,1)',[id(2),'one:'+f,id(n+50),'2035-01-01']);
 await c.query("INSERT INTO price_books(id,created_by,source_sha256,table_jpy,state,rental_from,rental_until) VALUES($1,'synthetic-actor',$2,'{}','PRIVATE_AVAILABLE','2035-01-01','2035-12-31')",[id(60),flowHash('R14 SYNTHETIC 100 JPY')]);
 await c.query("INSERT INTO price_activations(id,book_id,effective_at) VALUES($1,$2,'2025-01-01')",[id(61),id(60)]);
 await c.query(`INSERT INTO price_quotes(id,actor,request_key,request_fingerprint,book_id,activation_id,hold_id,hold_version,conditions,snapshot,snapshot_sha256,expires_at) VALUES($1,'synthetic-actor',$2,$3,$4,$5,$6,1,$7,$8,$9,$10)`,[id(3),id(62),flowHash('R14 quote'),id(60),id(61),id(2),s.booking.conditions,s.booking.priceSnapshot,s.booking.priceHash,s.hold!.expiresAt]);
 await c.query(`INSERT INTO rental_bookings(id,owner_id,request_key,fingerprint,hold_id,quote_id,conditions,price_snapshot,price_sha256,contact,mode,state,version) VALUES($1,'synthetic-actor',$2,$3,$4,$5,$6,$7,$8,$9,'SQUARE_SANDBOX','PAYMENT_PENDING',2)`,[id(1),id(63),flowHash('R14 booking'),id(2),id(3),s.booking.conditions,s.booking.priceSnapshot,s.booking.priceHash,{displayName:'SYNTHETIC R14',email:'synthetic-r14@example.invalid',termsAccepted:true}]);
 await c.query(`INSERT INTO rental_payment_attempts(id,booking_id,actor,idempotency_key,merchant_id,location_id,amount_jpy,currency,state,provider_id) VALUES($1,$2,'synthetic-actor',$3,$4,'fixture-location',100,'JPY',$5,$6)`,[id(4),id(1),id(5),merchantId,providerId===null?'SUBMITTING':'PENDING',providerId]);
 await c.query('COMMIT');}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}
}
export async function run(db:DB,out:string){
 if(db.r14?.completed.has('e2e')){
  if(db.r14.completed.has('fresh-verified'))return captureDbEvidence(db,out);
  // This development test session already owns all random credentials. IPC only to one finite
  // child avoids stale ESM modules; no secret files, environment variables, argv or external DB.
  const child=fork(fileURLToPath(new URL('./r14-fresh-child.ts',import.meta.url)),[],{execArgv:['--import','tsx'],env:{PATH:process.env.PATH,HOME:process.env.HOME,NODE_ENV:'test',NEXT_TELEMETRY_DISABLED:'1'},stdio:['ignore','pipe','pipe','ipc']});
  child.stdout?.on('data',x=>process.stdout.write(x));child.stderr?.on('data',()=>{});
  const options=(pool:Pool)=>({host:pool.options.host,port:pool.options.port,database:pool.options.database,user:pool.options.user,password:pool.options.password,max:2});
  const complete=new Promise<number|null>(resolve=>child.once('exit',resolve));
  child.send({owner:options(db.pool),roles:Object.fromEntries(Object.entries(db.r14.roles.pools).map(([k,p])=>[k,options(p)])),names:db.r14.roles.names,identity:db.identity,out});
  const timer=setTimeout(()=>child.kill('SIGTERM'),60000);let code;try{code=await complete;}finally{clearTimeout(timer);}if(code!==0)throw new Error('R14_FRESH_CHILD_FAILED');db.r14.completed.add('fresh-verified');return;
 }
 const results:{name:string;result:string;kind:string}[]=[];const save=()=>writeFileSync(out+'/real-db-tests.json',JSON.stringify({results,passed:results.filter(r=>r.result==='PASS').length,failed:results.filter(r=>r.result==='FAIL').length,actualProviderRequests:0},null,2));
 async function check(name:string,fn:()=>Promise<void>){try{await fn();results.push({name,result:'PASS',kind:'REAL_POSTGRESQL'});console.log('PASS '+name);}catch(e){results.push({name,result:'FAIL',kind:'REAL_POSTGRESQL'});save();throw e;}save();}
 await seed(db.pool);
 if(!db.r14)db.r14={roles:await provisionPaymentActivationRoles(db.pool,db.identity),completed:new Set()};
 const {roles}=db.r14,n=roles.names,p=roles.pools;
 // Business-only test clock. R12 lease/deadline uses actual PostgreSQL clock_timestamp.
 const original=(await db.pool.query("SELECT pg_get_functiondef('inventory_clock()'::regprocedure) AS definition")).rows[0].definition;
 await db.pool.query(`CREATE OR REPLACE FUNCTION inventory_clock() RETURNS timestamptz LANGUAGE sql VOLATILE AS $$SELECT coalesce(nullif(current_setting('zao.r14_clock',true),''),'2035-01-01T00:00:00Z')::timestamptz$$`);
 async function trial(fn:(c:PoolClient)=>Promise<void>){const c=await db.pool.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('zao.actor','synthetic-actor',true),set_config('zao.reason','R14 negative fixture transaction',true)");await fn(c);}finally{await c.query('ROLLBACK');c.release();}}
 async function truth(c:PoolClient,status:'PENDING'|'COMPLETED'|'FAILED'|'CANCELED'='COMPLETED',offset=0){
  const s={...event(),paymentId:offset?'fixture-payment-'+offset:'fixture-payment'},inbox=new PgSquareWebhookInbox(scoped(c,n.receiver)),d=new PgPaymentReconciliation(scoped(c,n.dispatcher)),w=new PgPaymentReconciliation(scoped(c,n.worker));
  await inbox.receive(s);await d.dispatch('SANDBOX',1);const claim=(await w.claimBatch('SANDBOX','r14-test',1))[0]!;assert.ok(claim);
  const context=(await w.load(claim))!,actual=(await c.query('SELECT clock_timestamp() AS now')).rows[0].now as Date;
  const o={...observation(status),providerId:s.paymentId,referenceId:id(1+offset),idempotencyKey:id(5+offset),updatedAt:actual.toISOString(),completedAt:status==='COMPLETED'?actual.toISOString():null};const accepted=decidePaymentTruth(context,s.paymentId,o,actual);
  assert.equal(accepted.decision,'ACCEPT_'+status);const outcome:JobOutcome={state:status==='PENDING'?'RETRY_WAIT':'RECONCILED',code:status==='PENDING'?'PENDING_OBSERVATION':null,retrySeconds:status==='PENDING'?10:null,truth:accepted};assert.equal(await w.finalize(claim,outcome),true);
  return {bookingId:id(1+offset),attemptId:id(4+offset),jobId:claim.id,truthRevision:claim.truthRevision+1,truthFingerprint:accepted.fingerprint,observationFingerprint:flowHash(o),expectedRevision:0};
 }
 try{
 await check('all migrations 0001-0032 recorded with hashes',async()=>{assert.equal((await db.pool.query('SELECT count(*)::int n FROM foundation_migrations')).rows[0].n,32);});
 await check('role boundaries: receiver/dispatcher/worker/diagnostic/public forbidden operations',async()=>{
  const denied:([keyof typeof p,string])[]=[['receiver',"UPDATE rental_bookings SET state='PAYMENT_REVIEW'"],['receiver','UPDATE inventory_holds SET version=version+1'],['receiver',`SELECT payment_projection.lock_source('${id(9)}')`],['receiver','SELECT * FROM square_webhook.inbox'],['dispatcher',"UPDATE rental_bookings SET state='PAYMENT_REVIEW'"],['worker',"UPDATE rental_bookings SET state='PAYMENT_REVIEW'"],['diagnostic',"SELECT payment_reconciliation.dispatch('SANDBOX',1)"],['publicProbe','SELECT * FROM payment_projection.events'],['publicProbe',"SELECT square_webhook.receive('SANDBOX','x','payment.updated','m','p','a')"],['publicProbe','SELECT * FROM payment_reconciliation.jobs'],['projector','UPDATE payment_reconciliation.jobs SET state=state'],['projector',"UPDATE rental_bookings SET contact='{}'"],['projector','UPDATE inventory_holds SET expires_at=now()'],['projector','UPDATE wear_claims SET active=false'],['projector','UPDATE inventory_claims SET active=false'],['projector','SELECT contact FROM rental_bookings'],['projector','INSERT INTO rental_notifications DEFAULT VALUES']];
  for(const [key,sql]of denied)await assert.rejects(p[key].query(sql),{code:'42501'});
  for(const pool of Object.values(p)){const a=(await pool.query('SELECT current_user AS name,usesuper FROM pg_user WHERE usename=current_user')).rows[0];assert.equal(a.usesuper,false);assert.notEqual(a.name,db.identity.namespace);await assert.rejects(pool.query('CREATE SCHEMA forbidden_r14'),{code:'42501'});}
 });
 await check('receiver duplicate/hash conflict and dispatcher link commit barrier',()=>trial(async c=>{const inbox=new PgSquareWebhookInbox(scoped(c,n.receiver)),d=new PgPaymentReconciliation(scoped(c,n.dispatcher)),s=event();assert.equal(await inbox.receive(s),'INSERTED');assert.equal(await inbox.receive(s),'DUPLICATE');await d.dispatch('SANDBOX',1);assert.equal((await c.query('SELECT count(*)::int n FROM payment_reconciliation.events WHERE event_id=$1',[s.eventId])).rows[0].n,1);assert.equal(await inbox.receive({...s,bodySha256:flowHash('conflict')}),'HASH_CONFLICT');assert.equal((await c.query('SELECT state,security_blocked FROM payment_reconciliation.jobs WHERE source_event_id=$1',[s.eventId])).rows[0].security_blocked,true);}));
 await check('signed receiver ACK awaits real commit; DB role failure gives 503 and no receipt',()=>trial(async c=>{
  const s=event(),url='https://r14.invalid/api/webhooks/square',key=randomBytes(32).toString('hex');const raw=JSON.stringify({event_id:s.eventId,type:s.type,merchant_id:s.merchantId,data:{object:{payment:{id:s.paymentId}}}}),signature=createHmac('sha256',key).update(url).update(raw).digest('base64');
  const req=()=>new Request(url,{method:'POST',headers:{'x-square-hmacsha256-signature':signature},body:raw});
  const config={environment:'SANDBOX' as const,merchantId:s.merchantId,notificationUrl:url,signatureKey:key};
  const bad=squareWebhookReceiver(config,()=>new PgSquareWebhookInbox(scoped(c,n.publicProbe)));assert.equal((await bad(req())).status,503);assert.equal((await c.query('SELECT count(*)::int n FROM square_webhook.inbox WHERE event_id=$1',[s.eventId])).rows[0].n,0);
  const good=squareWebhookReceiver(config,()=>new PgSquareWebhookInbox(scoped(c,n.receiver)));assert.equal((await good(req())).status,200);assert.equal((await good(req())).status,200);assert.equal((await c.query('SELECT count(*)::int n FROM square_webhook.inbox WHERE event_id=$1',[s.eventId])).rows[0].n,1);
 }));
 await check('lease expiry, interruption and stale finalize fenced by real DB',()=>trial(async c=>{const inbox=new PgSquareWebhookInbox(scoped(c,n.receiver)),d=new PgPaymentReconciliation(scoped(c,n.dispatcher)),w=new PgPaymentReconciliation(scoped(c,n.worker));await inbox.receive(event());await d.dispatch('SANDBOX',1);const first=(await w.claimBatch('SANDBOX','one',1))[0]!;assert.equal((await w.claimBatch('SANDBOX','two',1)).length,0);await c.query("UPDATE payment_reconciliation.jobs SET lease_expires_at=clock_timestamp()-interval '1 second',claim_after=clock_timestamp()-interval '1 second' WHERE id=$1",[first.id]);const second=(await w.claimBatch('SANDBOX','two',1))[0]!;assert.notEqual(first.leaseToken,second.leaseToken);const result:JobOutcome={state:'RETRY_WAIT',code:'NETWORK_RETRYABLE',retrySeconds:1,truth:null};assert.equal(await w.finalize(first,result),false);assert.equal(await w.finalize(second,result),true);assert.equal((await c.query('SELECT state FROM payment_reconciliation.jobs WHERE id=$1',[first.id])).rows[0].state,'RETRY_WAIT');}));
 for(const limit of ['attempt','deadline'] as const)await check('real DB '+limit+' cutoff stays DEAD',()=>trial(async c=>{const inbox=new PgSquareWebhookInbox(scoped(c,n.receiver)),d=new PgPaymentReconciliation(scoped(c,n.dispatcher)),w=new PgPaymentReconciliation(scoped(c,n.worker));await inbox.receive(event());await d.dispatch('SANDBOX',1);if(limit==='attempt')await c.query('UPDATE payment_reconciliation.jobs SET attempt=5');else await c.query("UPDATE payment_reconciliation.jobs SET deadline_at=clock_timestamp()-interval '1 second'");assert.equal((await w.claimBatch('SANDBOX','one',1)).length,0);const j=(await c.query('SELECT state,last_error FROM payment_reconciliation.jobs')).rows[0];assert.equal(j.state,'DEAD');assert.equal(j.last_error,limit==='attempt'?'ATTEMPTS_EXHAUSTED':'DEADLINE_EXCEEDED');}));
 for(const code of ['AUTH_BLOCKED','RATE_LIMITED'] as const)await check('real DB sticky '+code+' prevents new-event worker restart',()=>trial(async c=>{const inbox=new PgSquareWebhookInbox(scoped(c,n.receiver)),d=new PgPaymentReconciliation(scoped(c,n.dispatcher)),w=new PgPaymentReconciliation(scoped(c,n.worker));await inbox.receive(event());await d.dispatch('SANDBOX',1);const claim=(await w.claimBatch('SANDBOX','one',1))[0]!;assert.equal(await w.finalize(claim,{state:'BLOCKED',code,retrySeconds:null,truth:null}),true);await inbox.receive(event());await d.dispatch('SANDBOX',1);assert.equal((await w.claimBatch('SANDBOX','two',1)).length,0);assert.equal((await new PgPaymentReconciliation(scoped(c,n.diagnostic)).diagnostics('SANDBOX',10))[0]!.code,code);}));
 await check('new event while active preserves signal and terminal creates next generation',()=>trial(async c=>{const inbox=new PgSquareWebhookInbox(scoped(c,n.receiver)),d=new PgPaymentReconciliation(scoped(c,n.dispatcher)),w=new PgPaymentReconciliation(scoped(c,n.worker));await inbox.receive(event());await d.dispatch('SANDBOX',1);const claim=(await w.claimBatch('SANDBOX','one',1))[0]!;await inbox.receive(event());await d.dispatch('SANDBOX',1);const context=(await w.load(claim))!,t=new Date(),o={...observation(),updatedAt:t.toISOString(),completedAt:t.toISOString()},accepted=decidePaymentTruth(context,claim.paymentId,o,t);await w.finalize(claim,{state:'RECONCILED',code:null,retrySeconds:null,truth:accepted});assert.equal((await c.query('SELECT state FROM payment_reconciliation.jobs WHERE id=$1',[claim.id])).rows[0].state,'READY');const next=(await w.claimBatch('SANDBOX','two',1))[0]!;const duplicate=decidePaymentTruth({...context,latest:next.latest},claim.paymentId,o,t);await w.finalize(next,{state:'RECONCILED',code:null,retrySeconds:null,truth:duplicate});await inbox.receive(event());await d.dispatch('SANDBOX',1);assert.deepEqual((await c.query('SELECT generation FROM payment_reconciliation.jobs ORDER BY generation')).rows.map(x=>x.generation),[1,2]);}));
 for(const [name,mutation,expected]of [
  ['expired HOLD',"UPDATE inventory_holds SET expires_at=inventory_clock(),version=version+1",'BLOCK_EXPIRED_HOLD'],
  ['due boundary',"SELECT set_config('zao.r14_clock','2035-01-01T08:00:00Z',true)",'BLOCK_EXPIRED_HOLD'],
  ['missing gear',"UPDATE inventory_claims SET active=false",'BLOCK_INVENTORY_DRIFT'],
  ['missing wear',"UPDATE wear_claims SET active=false",'BLOCK_INVENTORY_DRIFT'],
  ['transfer attention',"UPDATE inventory_holds SET transfer_attention='NEEDS_REVIEW',version=version+1",'BLOCK_TRANSFER_ATTENTION'],
 ] as const)await check('real projection rejects '+name+' and retains original stock/contract',()=>trial(async c=>{const ref=await truth(c);await c.query(mutation);const before=(await c.query('SELECT expires_at,confirmed_at FROM inventory_holds WHERE id=$1',[id(2)])).rows[0];const result=await projector(scoped(c,n.projector)).project(ref);assert.equal(result.decision,expected);assert.notEqual(result.bookingState,'CONFIRMED_DEV');assert.equal(result.operatorActionRequired,true);assert.deepEqual((await c.query('SELECT expires_at,confirmed_at FROM inventory_holds WHERE id=$1',[id(2)])).rows[0],before);assert.equal((await c.query('SELECT count(*)::int n FROM rental_notifications')).rows[0].n,0);}));
 await check('existing immutable amount and snapshot reject direct edits',()=>trial(async c=>{for(const sql of ['UPDATE rental_payment_attempts SET amount_jpy=101',"UPDATE rental_bookings SET price_snapshot='{}'"]){await c.query('SAVEPOINT immutable_check');await assert.rejects(c.query(sql),{code:'23514'});await c.query('ROLLBACK TO SAVEPOINT immutable_check');}}));
 await check('real projection rejects synthetic price snapshot mismatch',()=>trial(async c=>{
  const conditions={...stateFixture().booking.conditions,reservationId:id(101)};
  await c.query("INSERT INTO inventory_reservations VALUES($1,'synthetic-actor')",[id(101)]);
  const clones=[['inventory_holds',id(2),{id:id(102),reservation_id:id(101),conditions}],['price_quotes',id(3),{id:id(103),request_key:id(162),hold_id:id(102),conditions}],['rental_bookings',id(1),{id:id(101),request_key:id(163),hold_id:id(102),quote_id:id(103),conditions,price_sha256:flowHash('SYNTHETIC wrong price hash')}],['rental_payment_attempts',id(4),{id:id(104),booking_id:id(101),idempotency_key:id(105),provider_id:'fixture-payment-100'}]] as const;
  for(const [table,from,overrides] of clones)await c.query(`INSERT INTO ${table} SELECT (jsonb_populate_record(NULL::${table},to_jsonb(t)||$2::jsonb)).* FROM ${table} t WHERE id=$1`,[from,JSON.stringify(overrides)]);
  const ref=await truth(c,'COMPLETED',100),result=await projector(scoped(c,n.projector)).project(ref);assert.equal(result.decision,'BLOCK_PRICE_INTEGRITY');assert.equal(result.bookingState,'PAYMENT_REVIEW');assert.equal((await c.query('SELECT confirmed_at FROM inventory_holds WHERE id=$1',[id(102)])).rows[0].confirmed_at,null);
 }));
 await check('stale revision rejected without business writes',()=>trial(async c=>{const ref=await truth(c);await assert.rejects(projector(scoped(c,n.projector)).project({...ref,expectedRevision:1}),{code:'STALE_PROJECTION_REVISION'});assert.equal((await c.query('SELECT count(*)::int n FROM payment_projection.events')).rows[0].n,0);}));
 await check('projection SQL failure after writes rolls back business/history/journal',()=>trial(async c=>{const ref=await truth(c),before=(await c.query('SELECT count(*)::int n FROM rental_history')).rows[0].n,base=scoped(c,n.projector);const broken:InboxPool={async connect(){const x=await base.connect();return {release:x.release,query:async(sql:string,args?:unknown[])=>{if(sql.startsWith('INSERT INTO payment_projection.events'))throw new Error('R14_INJECTED_CONNECTION_INTERRUPTION');return x.query(sql,args);}} as InboxConnection;}};await assert.rejects(projector(broken).project(ref),{code:'PROJECTION_STORAGE_UNAVAILABLE'});assert.equal((await c.query('SELECT state FROM rental_bookings WHERE id=$1',[id(1)])).rows[0].state,'PAYMENT_PENDING');assert.equal((await c.query('SELECT count(*)::int n FROM rental_history')).rows[0].n,before);assert.equal((await c.query('SELECT count(*)::int n FROM payment_projection.heads')).rows[0].n,0);}));
 // The one persistent synthetic chain is last. No destructive reset is used on a completed booking.
 if(!db.r14.completed.has('e2e'))await check('two dispatchers/workers then R12 truth and two R13 projectors; COMMIT response loss exactly once',async()=>{
  const inbox=new PgSquareWebhookInbox(p.receiver),d=new PgPaymentReconciliation(p.dispatcher),w=new PgPaymentReconciliation(p.worker),s=event();await inbox.receive(s);
  const dispatched=await Promise.all([d.dispatch('SANDBOX',1),d.dispatch('SANDBOX',1)]);assert.equal(dispatched.reduce((a,b)=>a+b,0),1);
  const claimed=await Promise.all([w.claimBatch('SANDBOX','one',1),w.claimBatch('SANDBOX','two',1)]);assert.equal(claimed.flat().length,1);const claim=claimed.flat()[0]!,context=(await w.load(claim))!,t=new Date(),o={...observation(),updatedAt:t.toISOString(),completedAt:t.toISOString()},accepted=decidePaymentTruth(context,claim.paymentId,o,t);assert.equal(await w.finalize(claim,{state:'RECONCILED',code:null,retrySeconds:null,truth:accepted}),true);
  const ref={bookingId:id(1),attemptId:id(4),jobId:claim.id,truthRevision:claim.truthRevision+1,truthFingerprint:accepted.fingerprint,observationFingerprint:flowHash(o),expectedRevision:0};
  const before=(await db.pool.query('SELECT count(*)::int n FROM rental_history')).rows[0].n;let lost=false;
  const lose:InboxPool={async connect(){const c=await p.projector.connect();return {release:(bad?:boolean)=>c.release(bad),query:async(sql:string,args?:unknown[])=>{const value=await c.query(sql,args);if(sql==='COMMIT'&&!lost){lost=true;throw new Error('R14_COMMIT_RESPONSE_LOST');}return value;}} as InboxConnection;}};
  const projected=await Promise.allSettled([projector(lose).project(ref),projector(p.projector).project(ref)]);assert.equal(projected.filter(x=>x.status==='fulfilled').length,1);assert.equal(projected.filter(x=>x.status==='rejected').length,1);assert.equal((await projector(p.projector).project(ref)).duplicate,true);
  assert.equal((await db.pool.query('SELECT state FROM rental_bookings WHERE id=$1',[id(1)])).rows[0].state,'CONFIRMED_DEV');assert.equal((await db.pool.query('SELECT count(*)::int n FROM rental_history')).rows[0].n,before+2);
  assert.equal((await db.pool.query('SELECT count(*)::int n FROM payment_projection.events')).rows[0].n,1);assert.equal((await db.pool.query('SELECT count(*)::int n FROM payment_projection.job_receipts')).rows[0].n,1);
  writeFileSync(out+'/synthetic-chain.json',JSON.stringify({kind:'REAL_POSTGRESQL_SYNTHETIC_PROVIDER_NOT_LIVE',eventId:s.eventId,jobId:claim.id,bookingId:id(1),attemptId:id(4),providerId:o.providerId,truthFingerprint:accepted.fingerprint,observationFingerprint:ref.observationFingerprint,decision:'APPLY_COMPLETED',booking:'CONFIRMED_DEV',journalCount:1,historyDelta:2,actualProviderRequests:0},null,2));db.r14!.completed.add('e2e');
 });
 await check('security metadata: function search paths and runtime attributes',async()=>{const functions=(await db.pool.query("SELECT n.nspname AS schema,p.proname AS name,r.rolname AS owner,p.prosecdef AS security_definer,p.proconfig AS settings FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace JOIN pg_roles r ON r.oid=p.proowner WHERE n.nspname IN ('square_webhook','payment_reconciliation','payment_projection') ORDER BY 1,2")).rows;for(const f of functions)assert.ok(f.settings?.includes('search_path=pg_catalog, pg_temp'));const attributes=(await db.pool.query('SELECT rolname,rolsuper,rolcreatedb,rolcreaterole,rolreplication,rolbypassrls FROM pg_roles WHERE rolname=ANY($1::text[])',[Object.values(n)])).rows;assert.ok(attributes.every(x=>!x.rolsuper&&!x.rolcreatedb&&!x.rolcreaterole&&!x.rolreplication&&!x.rolbypassrls));writeFileSync(out+'/db-role-metadata.json',JSON.stringify({functions,attributes,grants:(await db.pool.query('SELECT grantee,table_schema,table_name,privilege_type FROM information_schema.role_table_grants WHERE grantee=ANY($1::text[]) ORDER BY 1,2,3,4',[Object.values(n)])).rows},null,2));});
 await additional(db,out);
 }finally{await db.pool.query(original);save();}
}
