import {spawn} from 'node:child_process';
import {skiSet} from '../inventory/fixture';
import assert from 'node:assert/strict';
import {randomBytes,randomUUID,createHmac} from 'node:crypto';
import {flowFixture,simulation} from '../flow/fixture';
import {BookingService} from '../../packages/core/src/payment/booking-service';
import {initializeSandboxActivation,SANDBOX_ACTIVATION_ID,SandboxActivationJournal,ActivatedSandboxGateway} from '../../packages/core/src/payment/sandbox-activation';
import {SandboxRefundTrial} from '../../packages/core/src/payment/sandbox-refund';
import {SquareSandboxGateway} from '../../packages/core/src/payment/square-sandbox';
import {FetchSquareSandboxTransport} from '../../packages/core/src/payment/square-transport';
import {provisionSandboxJournal} from '../../scripts/sandbox-roles';
import {FlowError,type PaymentRequest} from '../../packages/contracts/src/rental-flow';
let failed=false,stage='setup',count=0;
async function check(name:string,fn:()=>Promise<void>){stage=name;await fn();count++;console.log('PASS '+name);}
async function fixture(){
 const x=await flowFixture();try{
 await provisionSandboxJournal(x.db.pool,x.db.identity.namespace);const config:import('../../packages/core/src/payment/sandbox-activation').SandboxActivation={id:SANDBOX_ACTIVATION_ID,evidence:'FIXTURE' as const,merchantId:simulation.merchantId,locationIds:Object.values(simulation.locations)};await initializeSandboxActivation(x.db.pool,config);
 const payments=new Map<string,Record<string,unknown>>(),refunds=new Map<string,Record<string,unknown>>();let posts=0,refundPosts=0,gets=0,lose=false,status=200,refundLose=false;
 const credential={environment:'SANDBOX' as const,merchantId:simulation.merchantId,locationId:simulation.locations.MOUNTAIN_BASE,accessToken:randomBytes(32).toString('base64url'),expiresAt:new Date('2036-01-01'),revoked:false};
 const transport=new FetchSquareSandboxTransport(credential.merchantId,credential.locationId,async()=>credential,async(url,init)=>{
  assert.ok(url.startsWith('https://connect.squareupsandbox.com/v2/'));assert.equal(init.redirect,'error');const body=init.body?JSON.parse(String(init.body)):null;
  if(init.method==='POST'&&url.endsWith('/payments')){posts++;if(status!==200)return Response.json({}, {status});const p=payments.get(body.idempotency_key)??{id:'fixture_'+body.reference_id,reference_id:body.reference_id,location_id:body.location_id,amount_money:body.amount_money,status:'COMPLETED',updated_at:x.now().toISOString(),card_details:{card_payment_timeline:{captured_at:x.now().toISOString()}}};payments.set(body.idempotency_key,p);if(lose){lose=false;throw new Error('SYNTHETIC_RESPONSE_LOST');}return Response.json({payment:p});}
  if(init.method==='POST'&&url.endsWith('/refunds')){refundPosts++;const r={id:'refund_'+body.idempotency_key,payment_id:body.payment_id,location_id:credential.locationId,amount_money:body.amount_money,status:'COMPLETED'};refunds.set(body.idempotency_key,r);if(refundLose){refundLose=false;throw new Error('SYNTHETIC_REFUND_RESPONSE_LOST');}return Response.json({refund:r});}
  gets++;const p=[...payments.values()].find(p=>url.endsWith('/'+p.id));return Response.json({payment:p});
 },x.now);
 const journal=new SandboxActivationJournal(x.flow.flowPool),gateway=new ActivatedSandboxGateway(new SquareSandboxGateway(transport,async()=> 'SYNTHETIC_SOURCE'),journal),service=new BookingService(x.flow.flowPool,x.roles.authPool,x.signed.identity,gateway,{...simulation,sandboxActivationId:SANDBOX_ACTIVATION_ID});
 let day=1;
 // LOWER-LEVEL MECHANICS (Square Sandbox payment-adapter/state-machine plumbing): the HOLD here
 // is incidental setup, not what's under test; x.principal (staff ADMIN) already has
 // INVENTORY_BUFFER_OVERRIDE from flowFixture.
 async function draft(){const conditions=skiSet('2035-03-'+String(day++).padStart(2,'0'));
  const h=await x.holds.command('create',randomUUID(),conditions,undefined,undefined,{reason:'SYNTHETIC sandbox-booking mechanics test'});assert.equal(h.result,'CREATED');const q=(await x.quotes.create(randomUUID(),{conditions,holdId:h.holdId,couponCode:null,wantAdvance:false})).quote;return {booking:await service.create(randomUUID(),q.id,{displayName:'SYNTHETIC Sandbox',email:'synthetic-sandbox@example.invalid',termsAccepted:true}),holdId:h.holdId!};}
 return {x,config,transport,journal,gateway,service,draft,payments,refunds,get posts(){return posts;},get refundPosts(){return refundPosts;},get gets(){return gets;},lose:()=>{lose=true;},status:(n:number)=>{status=n;},loseRefund:()=>{refundLose=true;}};
 }catch(e){await x.close();throw e;}}
let f:Awaited<ReturnType<typeof fixture>>|undefined;
try{
 f=await fixture();let bookingId='',paymentId='';
 await check('Square fixture transport -> payment state machine -> real DB confirmation has distinct Sandbox mode',async()=>{const d=await f!.draft();bookingId=d.booking.id;const b=await f!.service.startPayment(bookingId,randomUUID());assert.equal(b.mode,'SQUARE_SANDBOX');assert.equal(b.state,'CONFIRMED_DEV');await assert.rejects(f!.x.db.pool.query("UPDATE rental_bookings SET state='CONFIRMED',version=version+1 WHERE id=$1",[bookingId]),{code:'23514',constraint:'rental_bookings_mode_state_check'});assert.equal(b.chargeReady,false);paymentId=b.payments[0].provider_id;assert.equal(f!.posts,1);await f!.service.startPayment(bookingId,randomUUID());assert.equal(f!.posts,1);assert.equal((await f!.x.db.pool.query('SELECT confirmed_at FROM inventory_holds WHERE id=$1',[d.holdId])).rows[0].confirmed_at!==null,true);});
 await check('response lost before provider ID: same attempt/no new POST; verified webhook lookup recovers exact booking',async()=>{
  const d=await f!.draft();f!.lose();const before=f!.posts,b=await f!.service.startPayment(d.booking.id,randomUUID());assert.equal(b.payments[0].state,'UNKNOWN');assert.equal(b.payments[0].provider_id,null);await f!.service.startPayment(d.booking.id,randomUUID());assert.equal(f!.posts,before+1);
  const url='https://fixture.invalid/sandbox-webhook',key=randomBytes(32).toString('hex'),pid='fixture_'+d.booking.id;
  for(const event of ['new','old','new']){const raw=Buffer.from(JSON.stringify({event_id:event,merchant_id:simulation.merchantId,type:'payment.updated',data:{object:{payment:{id:pid,status:'FAILED'}}}})),signature=createHmac('sha256',key).update(url).update(raw).digest('base64');const result=await f!.service.reconcileVerifiedWebhook(d.booking.id,raw,signature,url,key);assert.equal(result.state,'CONFIRMED_DEV');}
  assert.equal(f!.posts,before+1);assert.equal((await f!.x.db.pool.query("SELECT count(*)::int n FROM rental_provider_events WHERE event_id LIKE 'webhook/%'")).rows[0].n,2);
 });
 await check('Sandbox refund fixture is bounded to recorded payment and cannot change commercial snapshot',async()=>{const trial=new SandboxRefundTrial(f!.transport,f!.journal),before=(await f!.x.db.pool.query('SELECT price_snapshot,conditions FROM rental_bookings WHERE id=$1',[bookingId])).rows[0],key=randomUUID();await assert.rejects(trial.create(randomUUID(),'unowned_provider',1),{code:'SANDBOX_REFUND_PAYMENT_UNVERIFIED'});const r=await trial.create(key,paymentId,100);assert.equal(r.status,'COMPLETED');assert.deepEqual(await trial.create(key,paymentId,100),r);assert.equal(f!.refundPosts,1);await assert.rejects(trial.create(key,paymentId,101),{code:'SQUARE_ACTIVATION_REPLAY_MISMATCH'});await assert.rejects(trial.create(randomUUID(),paymentId,7500),{code:'SANDBOX_REFUND_EXCEEDS_PAYMENT'});assert.deepEqual((await f!.x.db.pool.query('SELECT price_snapshot,conditions FROM rental_bookings WHERE id=$1',[bookingId])).rows[0],before);});
 await check('five-refund ceiling is shared by concurrent database transactions; replay does not consume again',async()=>{const a=new SandboxRefundTrial(f!.transport,new SandboxActivationJournal(f!.x.flow.flowPool)),b=new SandboxRefundTrial(f!.transport,new SandboxActivationJournal(f!.x.flow.flowPool));const results=await Promise.allSettled(Array.from({length:7},(_,i)=>(i%2?a:b).create(randomUUID(),paymentId,100))); // in-flight refunds serialize per payment and can require explicit reconciliation
  assert.ok(results.filter(r=>r.status==='fulfilled').length>=1);while(f!.refundPosts<5)await a.create(randomUUID(),paymentId,100);await assert.rejects(b.create(randomUUID(),paymentId,100),{code:'SQUARE_BUDGET_EXHAUSTED'});assert.equal(f!.refundPosts,5);
 });
 await check('20-payment ceiling persists across reconstructed adapters; UNKNOWN counts; new key for booking rejected',async()=>{const make=():PaymentRequest=>({attemptId:randomUUID(),bookingId:randomUUID(),idempotencyKey:randomUUID(),merchantId:simulation.merchantId,locationId:simulation.locations.MOUNTAIN_BASE,amountJpy:100,currency:'JPY'});const r=make(),g2=new ActivatedSandboxGateway(new SquareSandboxGateway(f!.transport,async()=> 'SYNTHETIC_SOURCE'),new SandboxActivationJournal(f!.x.flow.flowPool));f!.lose();await assert.rejects(g2.create(r));const prior=f!.posts;await assert.rejects(g2.create(r),{code:'PAYMENT_RESULT_UNKNOWN'});await assert.rejects(g2.create({...r,idempotencyKey:randomUUID()}),{code:'SQUARE_ACTIVATION_REPLAY_MISMATCH'});assert.equal(f!.posts,prior);const results=await Promise.allSettled(Array.from({length:24},()=>g2.create(make())));assert.ok(results.some(r=>r.status==='rejected'&&r.reason instanceof FlowError&&r.reason.code==='SQUARE_BUDGET_EXHAUSTED'));assert.equal(f!.posts,20);await initializeSandboxActivation(f!.x.db.pool,f!.config);await assert.rejects(g2.create(make()),{code:'SQUARE_BUDGET_EXHAUSTED'});assert.equal(f!.posts,20);});
 await check('20/5 ceilings survive two distinct operating-system processes with zero provider calls',async()=>{const before=[f!.posts,f!.refundPosts],pids:number[]=[];for(let i=0;i<2;i++){const p=spawn(process.execPath,['--import','tsx','tests/readiness/sandbox-journal-worker.ts'],{env:{PATH:process.env.PATH,NODE_ENV:'test'},stdio:['ignore','ignore','ignore','ipc']});pids.push(p.pid!);let timer:ReturnType<typeof setTimeout>|undefined;const exited=new Promise<number|null>(resolve=>p.once('exit',resolve));try{const message=new Promise<{codes:string[];counts:{operation:string;n:number}[]}>((resolve,reject)=>{p.once('message',m=>resolve(m as never));p.once('error',()=>reject(new Error('JOURNAL_CHILD_ERROR')));p.once('exit',()=>reject(new Error('JOURNAL_CHILD_EARLY_EXIT')));});p.send({db:f!.x.flow.flowDb,request:{attemptId:randomUUID(),bookingId:randomUUID(),idempotencyKey:randomUUID(),merchantId:simulation.merchantId,locationId:simulation.locations.MOUNTAIN_BASE,amountJpy:100,currency:'JPY'},paymentId});const result=await Promise.race([message,new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(new Error('JOURNAL_CHILD_TIMEOUT')),10000);})]);assert.deepEqual(result.codes,['SQUARE_BUDGET_EXHAUSTED','SQUARE_BUDGET_EXHAUSTED']);assert.deepEqual(result.counts,[{operation:'PAYMENT',n:20},{operation:'REFUND',n:5}]);assert.equal(await exited,0);}finally{clearTimeout(timer);p.kill('SIGTERM');await exited;}}assert.notEqual(pids[0],pids[1]);assert.deepEqual([f!.posts,f!.refundPosts],before);});
 await check('production composition and mismatched activation binding remain rejected',async()=>{assert.throws(()=>new BookingService(f!.x.flow.flowPool,f!.x.roles.authPool,f!.x.signed.identity,f!.gateway,{...simulation,nodeEnv:'production',sandboxActivationId:SANDBOX_ACTIVATION_ID}),{code:'SIMULATION_FORBIDDEN'});await assert.rejects(initializeSandboxActivation(f!.x.db.pool,{...f!.config,evidence:'REAL_SANDBOX'}),{code:'SQUARE_ACTIVATION_MISMATCH'});});
 await f.x.close();f=undefined;
 for(const status of [401,429]){f=await fixture();await check('auth/quota '+status+' stops future process calls without credential fallback',async()=>{f!.status(status);const d=await f!.draft();await assert.rejects(f!.service.startPayment(d.booking.id,randomUUID()),{code:status===401?'SQUARE_AUTH_STOP':'SQUARE_QUOTA_STOP'});assert.equal(f!.posts,1);await assert.rejects(f!.gateway.create({attemptId:randomUUID(),bookingId:randomUUID(),idempotencyKey:randomUUID(),merchantId:simulation.merchantId,locationId:simulation.locations.MOUNTAIN_BASE,amountJpy:100,currency:'JPY'}));assert.equal(f!.posts,1);await assert.rejects(f!.x.flow.flowPool.query('UPDATE sandbox_activation_runs SET stopped_reason=NULL'),(e:{code?:string})=>e.code==='23514');});await f.x.close();f=undefined;}
 f=await fixture();await check('lost refund response cannot be retried by same or alternate key',async()=>{const d=await f!.draft(),b=await f!.service.startPayment(d.booking.id,randomUUID()),trial=new SandboxRefundTrial(f!.transport,f!.journal),key=randomUUID(),paymentId=b.payments[0].provider_id;f!.loseRefund();await assert.rejects(trial.create(key,paymentId,100),{code:'SANDBOX_REFUND_RESULT_UNKNOWN'});await assert.rejects(trial.create(key,paymentId,100),{code:'SANDBOX_REFUND_RESULT_UNKNOWN'});await assert.rejects(trial.create(randomUUID(),paymentId,100),{code:'SANDBOX_REFUND_RECONCILIATION_REQUIRED'});assert.equal(f!.refundPosts,1);});await f.x.close();f=undefined;
 console.log('P4 Sandbox fixture + real PostgreSQL: '+count+' passed; real Sandbox payments/refunds=0/0; no real credentials.');
}catch(e){failed=true;console.error('P4_SANDBOX_FAILED '+stage+' '+String((e as {code?:string}).code??(e as Error).name));console.error((e as Error).stack?.split('\n').filter(s=>s.includes('/tests/readiness/')).join('\n'));}finally{await f?.x.close();console.log('Owned P4 Sandbox PostgreSQL stopped.');}if(failed)process.exit(1);
