-- Owner explicitly approved PUBLIC_GUEST_BOUNDARY_PROPOSAL.md. Synthetic development only.
DO $$BEGIN IF current_database() !~ '^zr_[a-f0-9]{12}$' THEN RAISE EXCEPTION 'Dedicated development DB required';END IF;END$$;
CREATE TABLE booking_actors(id text PRIMARY KEY,kind text NOT NULL CHECK(kind IN ('STAFF','GUEST')));
INSERT INTO booking_actors SELECT id,'STAFF' FROM staff_members;
CREATE TABLE guest_contexts(id uuid PRIMARY KEY,actor_id text UNIQUE NOT NULL REFERENCES booking_actors(id),token_sha256 text UNIQUE NOT NULL CHECK(token_sha256 ~ '^[a-f0-9]{64}$'),created_at timestamptz NOT NULL,expires_at timestamptz NOT NULL,revoked_at timestamptz,CHECK(expires_at>created_at));
CREATE FUNCTION booking_register_staff_actor() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$BEGIN INSERT INTO booking_actors VALUES(NEW.id,'STAFF');RETURN NEW;END$$;
REVOKE ALL ON FUNCTION booking_register_staff_actor() FROM PUBLIC;
CREATE TRIGGER booking_register_staff_actor AFTER INSERT ON staff_members FOR EACH ROW EXECUTE FUNCTION booking_register_staff_actor();
CREATE TABLE guest_drafts(id uuid PRIMARY KEY,context_id uuid NOT NULL UNIQUE REFERENCES guest_contexts(id),revision integer NOT NULL DEFAULT 1 CHECK(revision>0),input jsonb,preview_key uuid,preview_id uuid REFERENCES recommendation_previews(id),selection jsonb,selection_key uuid,booking_key uuid NOT NULL,booking_id uuid REFERENCES rental_bookings(id),created_at timestamptz NOT NULL DEFAULT clock_timestamp(),updated_at timestamptz NOT NULL DEFAULT clock_timestamp());
ALTER TABLE inventory_reservations DROP CONSTRAINT inventory_reservations_owner_id_fkey;
ALTER TABLE inventory_reservations ADD CONSTRAINT inventory_reservations_owner_id_fkey FOREIGN KEY(owner_id) REFERENCES booking_actors(id);
ALTER TABLE inventory_holds DROP CONSTRAINT inventory_holds_owner_id_fkey;
ALTER TABLE inventory_holds ADD CONSTRAINT inventory_holds_owner_id_fkey FOREIGN KEY(owner_id) REFERENCES booking_actors(id);
ALTER TABLE inventory_requests DROP CONSTRAINT inventory_requests_owner_id_fkey;
ALTER TABLE inventory_requests ADD CONSTRAINT inventory_requests_owner_id_fkey FOREIGN KEY(owner_id) REFERENCES booking_actors(id);
ALTER TABLE inventory_history DROP CONSTRAINT inventory_history_actor_fkey;
ALTER TABLE inventory_history ADD CONSTRAINT inventory_history_actor_fkey FOREIGN KEY(actor) REFERENCES booking_actors(id);
ALTER TABLE inventory_replans DROP CONSTRAINT inventory_replans_actor_fkey;
ALTER TABLE inventory_replans ADD CONSTRAINT inventory_replans_actor_fkey FOREIGN KEY(actor) REFERENCES booking_actors(id);
ALTER TABLE price_quotes DROP CONSTRAINT price_quotes_actor_fkey;
ALTER TABLE price_quotes ADD CONSTRAINT price_quotes_actor_fkey FOREIGN KEY(actor) REFERENCES booking_actors(id);
ALTER TABLE coupon_reservations DROP CONSTRAINT coupon_reservations_actor_fkey;
ALTER TABLE coupon_reservations ADD CONSTRAINT coupon_reservations_actor_fkey FOREIGN KEY(actor) REFERENCES booking_actors(id);
ALTER TABLE pricing_history DROP CONSTRAINT pricing_history_actor_fkey;
ALTER TABLE pricing_history ADD CONSTRAINT pricing_history_actor_fkey FOREIGN KEY(actor) REFERENCES booking_actors(id);
ALTER TABLE recommendation_previews DROP CONSTRAINT recommendation_previews_owner_id_fkey;
ALTER TABLE recommendation_previews ADD CONSTRAINT recommendation_previews_owner_id_fkey FOREIGN KEY(owner_id) REFERENCES booking_actors(id);
ALTER TABLE recommendation_selections DROP CONSTRAINT recommendation_selections_owner_id_fkey;
ALTER TABLE recommendation_selections ADD CONSTRAINT recommendation_selections_owner_id_fkey FOREIGN KEY(owner_id) REFERENCES booking_actors(id);
ALTER TABLE rental_bookings DROP CONSTRAINT rental_bookings_owner_id_fkey;
ALTER TABLE rental_bookings ADD CONSTRAINT rental_bookings_owner_id_fkey FOREIGN KEY(owner_id) REFERENCES booking_actors(id);
ALTER TABLE rental_payment_attempts DROP CONSTRAINT rental_payment_attempts_actor_fkey;
ALTER TABLE rental_payment_attempts ADD CONSTRAINT rental_payment_attempts_actor_fkey FOREIGN KEY(actor) REFERENCES booking_actors(id);
ALTER TABLE rental_requests DROP CONSTRAINT rental_requests_actor_fkey;
ALTER TABLE rental_requests ADD CONSTRAINT rental_requests_actor_fkey FOREIGN KEY(actor) REFERENCES booking_actors(id);
ALTER TABLE rental_history DROP CONSTRAINT rental_history_actor_fkey;
ALTER TABLE rental_history ADD CONSTRAINT rental_history_actor_fkey FOREIGN KEY(actor) REFERENCES booking_actors(id);
REVOKE ALL ON booking_actors,guest_contexts,guest_drafts FROM PUBLIC;
