import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {flowFixture} from '../flow/fixture';
import {CustodyService} from '../../packages/core/src/rental/custody-service';
import {provisionCustodyRole} from '../../scripts/custody-roles';
import {requestFor,variants,fid} from '../inventory/fixture';
import {WearService} from '../../packages/core/src/wear/service';
import {LedgerService} from '../../packages/core/src/catalog/ledger-service';
import {ledgerPrincipal,loadStaff} from '../../packages/auth/src/staff-auth';
import {verifyLedgerWrite} from '../../packages/auth/src/ledger-write-authority';
import {reconcileLedgerProtection} from '../../packages/core/src/catalog/reconcile-protection';
import {writeAccount,listAccounts} from '../../packages/auth/src/accounts';
import {registerWear} from '../wear/fixture';
import type {HoldConditions} from '../../packages/contracts/src/hold';
const x=await flowFixture();let role:Awaited<ReturnType<typeof provisionCustodyRole>>|undefined,failed=false,stage='start',count=0;
// LOWER-LEVEL MECHANICS (late-pickup/preparation-fixed protection scenarios): x.draft()'s HOLD is
// incidental setup, not what's under test.
const bufferOverride={reason:'SYNTHETIC late-pickup mechanics test'};
async function check(name:string,fn:()=>Promise<void>){stage=name;await fn();count++;console.log('PASS '+name);}
try{
 role=await provisionCustodyRole(x.db.pool,x.db.identity);const svc=new CustodyService(role.custodyPool,x.roles.authPool,x.signed.identity);
 async function confirmed(start:string,end:string,variant=variants.ski){await x.clock(start+'T10:00:00+09:00');const c=requestFor(start,[variant]);c.period={startDate:start,endDate:end,slot:'MULTIDAY'};const d=await x.draft(undefined,c,bufferOverride);await x.service.startPayment(d.booking.id,randomUUID());const view=await svc.checkoutView(d.booking.id);await svc.prepare(randomUUID(),{bookingId:d.booking.id,expectedBookingVersion:view.bookingVersion,expectedHoldVersion:view.holdVersion,selections:view.items.map(i=>({requirementKey:i.requirement_key,assetId:i.asset_id,poleId:i.pole_id})),fitEvidence:'SYNTHETIC late pickup preparation'});return d;}
 async function contract(id:string){return (await x.db.pool.query(`SELECT b.conditions,b.price_snapshot,b.price_sha256,h.expires_at,h.starts_at,h.due_at,h.occupancy_start,h.occupancy_end FROM rental_bookings b JOIN inventory_holds h ON h.id=b.hold_id WHERE b.id=$1`,[id])).rows[0];}
 const d=await confirmed('2035-04-01','2035-04-02'),before=await contract(d.booking.id);
 await check('first closing and original 600s TTL retain confirmed fixed protection, no release or sale to another customer',async()=>{await x.clock('2035-04-01T17:01:00+09:00');const h=(await x.db.pool.query('SELECT * FROM inventory_holds WHERE id=$1',[d.holdId])).rows[0];assert.equal(h.state,'ACTIVE');assert.equal(h.payment_state,'SUCCESS');assert.equal(h.allocation_stage,'PREPARATION_FIXED');assert.ok(h.expires_at<x.now());assert.equal((await x.db.pool.query('SELECT count(*)::int n FROM inventory_claims WHERE hold_id=$1 AND active',[d.holdId])).rows[0].n,2);const c:HoldConditions=structuredClone(d.conditions);c.reservationId=randomUUID();c.period.startDate=c.period.endDate='2035-04-02';c.period.slot='DAY';assert.equal((await x.holds.availability(c)).result,'INSUFFICIENT');});
 await check('MULTIDAY day2 10:00 checkout succeeds; commercial contract/snapshot/end/due/TTL stay unchanged',async()=>{await x.clock('2035-04-02T10:00:00+09:00');const key=randomUUID(),input={bookingId:d.booking.id,expectedPreparationVersion:1};const out=await svc.checkout(key,input);assert.equal(out.loans.length,1);assert.equal(out.loans[0].checked_out_at.toISOString(),x.now().toISOString());assert.equal(out.loans[0].due_at.toISOString(),new Date('2035-04-02T17:00:00+09:00').toISOString());assert.deepEqual(await contract(d.booking.id),before);await svc.checkout(key,input);await assert.rejects(svc.checkout(randomUUID(),input));assert.equal((await x.db.pool.query('SELECT count(*)::int n FROM rental_loan_items WHERE booking_id=$1',[d.booking.id])).rows[0].n,1);assert.equal(x.fake.calls.length,1);});
 const three=await confirmed('2035-04-05','2035-04-07',variants.skiAlt);
 await check('MULTIDAY day3 before opening/at closing rejected; day3 opening allowed without extension/refund',async()=>{const input={bookingId:three.booking.id,expectedPreparationVersion:1};await x.clock('2035-04-07T08:29:59+09:00');await assert.rejects(svc.checkout(randomUUID(),input));await x.clock('2035-04-07T17:00:00+09:00');await assert.rejects(svc.checkout(randomUUID(),input));await x.clock('2035-04-07T08:30:00+09:00');const old=await contract(three.booking.id);assert.equal((await svc.checkout(randomUUID(),input)).loans.length,1);assert.deepEqual(await contract(three.booking.id),old);assert.equal(x.fake.calls.length,2);});
 const untouched=await confirmed('2035-05-01','2035-05-03',fid(7101)),original=await contract(untouched.booking.id);
 await check('never collected booking completes only after original due; exact promise release with no return/refund/extension; replay once',async()=>{
  await x.clock('2035-05-03T16:59:59+09:00');await assert.rejects(svc.completeNoPickup(randomUUID(),{bookingId:untouched.booking.id}));
  await x.clock('2035-05-03T17:00:00+09:00');const keys=[randomUUID(),randomUUID()];await Promise.all(keys.map(k=>svc.completeNoPickup(k,{bookingId:untouched.booking.id})));await svc.completeNoPickup(keys[0]!,{bookingId:untouched.booking.id});
  assert.equal((await svc.checkoutView(untouched.booking.id)).noPickup.outcome,'NO_PICKUP_COMPLETED');assert.equal((await x.db.pool.query('SELECT count(*)::int n FROM rental_no_pickup_events WHERE booking_id=$1',[untouched.booking.id])).rows[0].n,1);
  assert.equal((await x.db.pool.query('SELECT count(*)::int n FROM inventory_claims WHERE hold_id=$1 AND active',[untouched.holdId])).rows[0].n,0);assert.equal((await x.db.pool.query('SELECT state FROM rental_bookings WHERE id=$1',[untouched.booking.id])).rows[0].state,'COMPLETED_DEV');assert.equal((await x.db.pool.query('SELECT allocation_stage FROM inventory_holds WHERE id=$1',[untouched.holdId])).rows[0].allocation_stage,'PREPARATION_FIXED');
  assert.deepEqual(await contract(untouched.booking.id),original);assert.equal((await x.db.pool.query('SELECT count(*)::int n FROM rental_receipts')).rows[0].n,0);await assert.rejects(svc.checkout(randomUUID(),{bookingId:untouched.booking.id,expectedPreparationVersion:1}));assert.equal(x.fake.calls.length,3);
 });
 await check('any previous physical equipment loan prevents no-pickup completion and keeps protection',async()=>{await assert.rejects(svc.completeNoPickup(randomUUID(),{bookingId:d.booking.id}));assert.equal((await x.db.pool.query('SELECT state FROM inventory_holds WHERE id=$1',[d.holdId])).rows[0].state,'ACTIVE');});
 await check('new function is UUID only, private by default, no direct application booking/claim writes; unchanged checkout ACL',async()=>{
  const fn=(await x.db.pool.query("SELECT proowner::regrole::text owner,proconfig FROM pg_proc WHERE oid='rental_complete_no_pickup(uuid)'::regprocedure")).rows[0];assert.equal(fn.owner,x.db.identity.namespace+'_custody_executor');assert.ok(fn.proconfig.includes('search_path=pg_catalog, public, pg_temp'));
  assert.equal((await x.db.pool.query("SELECT count(*)::int n FROM pg_proc p CROSS JOIN LATERAL aclexplode(p.proacl) a WHERE p.oid IN('rental_complete_no_pickup(uuid)'::regprocedure,'rental_validate_loan()'::regprocedure) AND a.grantee=0")).rows[0].n,0);
  for(const query of ['UPDATE inventory_claims SET active=false',"UPDATE rental_bookings SET state='COMPLETED_DEV'",'DELETE FROM rental_no_pickup_events'])await assert.rejects(role!.custodyPool.query(query),{code:'42501'});
 });
 const wear=new WearService(x.flow.flowPool,x.roles.authPool,x.signed.identity),ledger=new LedgerService(x.roles.ledgerPool,ledgerPrincipal(x.principal),(c,stores,global)=>verifyLedgerWrite(c,x.roles.authPool,x.signed.identity,stores,global),(resource,id,version)=>reconcileLedgerProtection(x.roles.transferPool,x.roles.authPool,x.signed.identity,resource,id,version));
 const f=await registerWear(ledger,wear);await x.clock('2035-06-01T10:00:00+09:00');
 const c=requestFor('2035-06-01',[f.variants['SKI-150 cm']!]);c.period={startDate:'2035-06-01',endDate:'2035-06-03',slot:'MULTIDAY'};c.contractVersion='INTEGRATED_V1_2';c.members[0]!.tier='PREMIUM';c.members[0]!.wear=true;c.members[0]!.items[0]!.modelPromise={modelId:f.models.SKI!,variantId:f.variants['SKI-150 cm']!,season:'2026/27'};c.members[0]!.items.push({family:'WEAR_JACKET',variantIds:[f.selection.jacketVariantId]},{family:'WEAR_PANTS',variantIds:[f.selection.pantsVariantId]});
 const mixed=await x.draft(undefined,c,bufferOverride);await x.service.startPayment(mixed.booking.id,randomUUID());const mixedBefore=await contract(mixed.booking.id);const view=await svc.checkoutView(mixed.booking.id);await svc.prepare(randomUUID(),{bookingId:mixed.booking.id,expectedBookingVersion:view.bookingVersion,expectedHoldVersion:view.holdVersion,selections:view.items.map(i=>({requirementKey:i.requirement_key,assetId:i.asset_id,poleId:i.pole_id})),fitEvidence:'SYNTHETIC exact premium preparation'});
 await check('Premium exact promise and quantity wear remain protected after first-day no-show; later-day requires planned pickup store and opening hours',async()=>{
  await x.clock('2035-06-02T08:29:59+09:00');const booking=await x.service.get(mixed.booking.id),input={bookingId:booking.id,expectedBookingVersion:booking.version,store:'MOUNTAIN_BASE',reason:'SYNTHETIC late pickup'};
  await assert.rejects(wear.checkout(randomUUID(),input));await x.clock('2035-06-02T10:00:00+09:00');await assert.rejects(wear.checkout(randomUUID(),{...input,store:'ONSEN_BASE'}),{code:'FORBIDDEN'});
  assert.equal((await x.db.pool.query('SELECT count(*)::int n FROM wear_claims WHERE hold_id=$1 AND active',[mixed.holdId])).rows[0].n,6);
  const competitor=structuredClone(c);competitor.reservationId=randomUUID();competitor.period.startDate='2035-06-02';competitor.members=Array.from({length:2},(_,n)=>({...structuredClone(c.members[0]!),key:'other-'+n}));assert.equal((await x.holds.availability(competitor)).result,'INSUFFICIENT');
  const out=await svc.checkout(randomUUID(),{bookingId:mixed.booking.id,expectedPreparationVersion:1});assert.equal(out.loans[0].variant_id,f.variants['SKI-150 cm']);assert.equal(out.loans[0].checked_out_at.toISOString(),x.now().toISOString());const key=randomUUID();const w=await wear.checkout(key,input);assert.equal(w.loans.length,2);await wear.checkout(key,input);assert.equal((await x.db.pool.query('SELECT count(*)::int n FROM wear_loans WHERE booking_id=$1',[mixed.booking.id])).rows[0].n,2);assert.deepEqual(await contract(mixed.booking.id),mixedBefore);assert.equal(x.fake.calls.length,4);
 });
 await x.clock('2035-07-01T10:00:00+09:00');const wc:HoldConditions={...c,reservationId:randomUUID(),period:{startDate:'2035-07-01',endDate:'2035-07-02',slot:'MULTIDAY'},members:[{key:'wear-only',product:'WEAR_SET',age:'ADULT',tier:'STANDARD',wearSport:'SKI',items:c.members[0]!.items.filter(i=>i.family.startsWith('WEAR_'))}]};
 const never=await x.draft(undefined,wc,bufferOverride);await x.service.startPayment(never.booking.id,randomUUID());const neverBefore=await contract(never.booking.id);
 await check('never collected wear releases quantity claims only at due, no garment assets/receipts/refund; issued wear cannot be completed as uncollected',async()=>{
  await x.clock('2035-07-02T17:00:00+09:00');await svc.completeNoPickup(randomUUID(),{bookingId:never.booking.id});assert.equal((await x.db.pool.query('SELECT count(*)::int n FROM wear_claims WHERE hold_id=$1 AND active',[never.holdId])).rows[0].n,0);assert.equal((await x.db.pool.query('SELECT count(*)::int n FROM wear_receipts')).rows[0].n,0);assert.deepEqual(await contract(never.booking.id),neverBefore);await assert.rejects(svc.completeNoPickup(randomUUID(),{bookingId:mixed.booking.id}));assert.equal(x.fake.calls.length,5);
 });
 const scoped=(await writeAccount(x.roles.authPool,x.bp,undefined,{email:'late-scoped@example.invalid',password:x.password,displayName:'SYNTHETIC scoped',active:true,role:'STAFF',scope:'ASSIGNED',storeIds:['ONSEN_BASE'],permissions:{BOOKING_VIEW:true,RENTAL_CHECKOUT:true}})).id!,signed=await x.login('late-scoped@example.invalid'),other=new CustodyService(role.custodyPool,x.roles.authPool,signed.identity);
 await check('planned pickup scope and fresh permission required even for old QR/replayed completion',async()=>{
  await assert.rejects(other.checkoutView(untouched.booking.id),{code:'FORBIDDEN'});const u=(await listAccounts(x.roles.authPool,x.bp)).find(u=>u.id===scoped)!;await writeAccount(x.roles.authPool,x.bp,scoped,{displayName:u.displayName,active:true,role:u.role,scope:'ASSIGNED',storeIds:['MOUNTAIN_BASE'],permissions:{BOOKING_VIEW:true,RENTAL_CHECKOUT:false},expectedRevision:u.revision});assert.ok(await loadStaff(x.db.pool,scoped));await assert.rejects(other.completeNoPickup(randomUUID(),{bookingId:untouched.booking.id}),{code:'FORBIDDEN'});
 });
 console.log(`Late pickup real PostgreSQL: ${count} passed; normal password/session, synthetic adapter/data.`);
}catch(e){failed=true;console.error('LATE_PICKUP_FAILED '+stage+' '+String((e as {code?:string}).code??(e as Error).name));if(e instanceof assert.AssertionError)console.error(JSON.stringify({actual:e.actual,expected:e.expected}));}finally{await role?.close();await x.close();console.log('Owned late-pickup PostgreSQL stopped.');}if(failed)process.exit(1);
