import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
import QRCode from 'qrcode';
import {requestFor} from '../inventory/fixture';
import {mkdir} from 'node:fs/promises';
import {chromium,expect,type Page} from '@playwright/test';
import {startFlowApp} from '../flow/launcher';
import {bootstrapDevelopmentAdmin} from '../../scripts/bootstrap-staff';
import {seedRecommendation} from '../recommendation/fixture';
import {LedgerService} from '../../packages/core/src/catalog/ledger-service';
import {loadStaff,ledgerPrincipal} from '../../packages/auth/src/staff-auth';
import {verifyLedgerWrite} from '../../packages/auth/src/ledger-write-authority';
import {reconcileLedgerProtection} from '../../packages/core/src/catalog/reconcile-protection';
import {WearService} from '../../packages/core/src/wear/service';
import {registerWear} from '../wear/fixture';
let stage='startup',count=0,failed=false;const browser=await chromium.launch(),password=randomBytes(24).toString('base64url');let app:Awaited<ReturnType<typeof startFlowApp>>|undefined,page:Page|undefined;
async function check(name:string,fn:()=>Promise<void>){stage=name;await fn();count++;console.log('PASS '+name);}
try{
 app=await startFlowApp();await seedRecommendation(app.db.pool);await bootstrapDevelopmentAdmin(app.db.pool,{email:'custody-ui-root@example.invalid',displayName:'SYNTHETIC Root',password});const {origin}=app;
 async function clock(time:string){await app!.db.pool.query(`CREATE OR REPLACE FUNCTION inventory_clock() RETURNS timestamptz LANGUAGE sql VOLATILE AS $$SELECT '${time}'::timestamptz$$`);}await clock('2035-01-01T01:00:00Z');
 for(let n=0;n<100;n++){try{if((await fetch(origin+'/api/health')).ok)break;}catch{}if(n===99)throw new Error('APP_START_TIMEOUT');await new Promise(r=>setTimeout(r,100));}
 const context=await browser.newContext({baseURL:origin,viewport:{width:1280,height:960}});context.setDefaultTimeout(15000);await context.addInitScript('window.__name = (fn) => fn');page=await context.newPage();const p=page;
 async function login(email:string){await p.goto('/staff/login');await p.getByLabel('メールアドレス',{exact:true}).fill(email);await p.getByLabel('パスワード',{exact:true}).fill(password);await p.getByRole('button',{name:'ログイン',exact:true}).click();await p.waitForURL(origin+'/staff/ledger');}
 await login('custody-ui-root@example.invalid');const perms={BOOKING_VIEW:true,BOOKING_CREATE:true,RENTAL_CHECKOUT:true,RENTAL_RETURN:true,INVENTORY_VIEW:true,INVENTORY_EDIT:true,HOLD_VIEW:true,HOLD_EDIT:true,QUOTE_VIEW:true,QUOTE_CREATE:true,PRICE_EDIT:true,TRANSFER_VIEW:true,TRANSFER_PLAN:true,TRANSFER_DISPATCH:true,TRANSFER_RECEIVE:true};
 const created=await context.request.post('/api/staff-users',{headers:{origin},data:{email:'custody-ui-actor@example.invalid',password,displayName:'SYNTHETIC Custody Staff',active:true,role:'ADMIN',scope:'ALL',storeIds:[],permissions:perms}});assert.equal(created.status(),201);
 const root=await browser.newContext({baseURL:origin});const rootLogin=await root.request.post('/api/auth/sign-in/email',{headers:{origin},data:{email:'custody-ui-root@example.invalid',password}});assert.equal(rootLogin.status(),200);
 await p.goto('/staff/logout');await p.getByRole('button',{name:'ログアウトする',exact:true}).click();await p.waitForURL(origin+'/staff/login');await login('custody-ui-actor@example.invalid');
 const subject=(await app.db.pool.query("SELECT id FROM staff_users WHERE email='custody-ui-actor@example.invalid'")).rows[0].id,sessionId=(await app.db.pool.query('SELECT id FROM auth_session WHERE "userId"=$1 ORDER BY "createdAt" DESC LIMIT 1',[subject])).rows[0].id,identity={subject,sessionId},principal=(await loadStaff(app.db.pool,subject))!;
 const ledger=new LedgerService(app.roles.ledgerPool,ledgerPrincipal(principal),(c,stores,global)=>verifyLedgerWrite(c,app!.roles.authPool,identity,stores,global),(resource,id,version)=>reconcileLedgerProtection(app!.roles.transferPool,app!.roles.authPool,identity,resource,id,version));const fixtures=await registerWear(ledger,new WearService(app.flow.flowPool,app.roles.authPool,identity));
 await p.goto('/staff/quotes');await p.getByLabel('料金の対象開始日').fill('2035-01-01');await p.getByLabel('料金の対象終了日').fill('2035-12-31');await p.getByRole('button',{name:'開発用の初期料金を設定'}).click();await expect(p.getByRole('region',{name:'料金版',exact:true})).toContainText('PRIVATE_AVAILABLE');
 let bookingId='',assetId='',poleId='',bootId='',holdId='',ttl='',snapshot='';
 await check('normal UI Premium model+selected size+quantity wear -> full HOLD/quote -> isolated payment confirmation',async()=>{
  await p.goto('/preview/integrated');await p.getByLabel('利用開始日',{exact:true}).fill('2035-01-05');await p.getByLabel('利用終了日',{exact:true}).fill('2035-01-05');await p.getByLabel('競技 1',{exact:true}).selectOption('SKI');await p.getByLabel('利用開始時の年齢区分 1',{exact:true}).selectOption('ADULT');await p.getByLabel('身長cm 1',{exact:true}).fill('170');await p.getByLabel('足サイズcm 1',{exact:true}).fill('25.5');await p.getByLabel('体重kg 1',{exact:true}).fill('60');await p.getByLabel('利用開始時の年齢 1',{exact:true}).fill('30');await p.getByLabel('レベル 1',{exact:true}).selectOption('BEGINNER');
  await p.getByLabel('クラス 1',{exact:true}).selectOption('PREMIUM');await p.getByLabel('ポールのサイズ 1',{exact:true}).selectOption(fixtures.variants['POLE-110 cm']!);
  await p.getByLabel('指定モデル・シーズン 1',{exact:true}).selectOption(fixtures.models.SKI!+'|2026/27');
  await p.getByLabel('ウェア上下セットを追加 1',{exact:true}).check();await p.getByLabel('上サイズ 1',{exact:true}).selectOption(fixtures.selection.jacketVariantId);await p.getByLabel('下サイズ 1',{exact:true}).selectOption(fixtures.selection.pantsVariantId);
  await p.getByRole('button',{name:'推薦候補を確認',exact:true}).click();await p.getByRole('button',{name:'おすすめを選ぶ 1',exact:true}).click();await p.getByRole('checkbox',{name:'表示したモデル契約・サイズ・ウェア構成を選択条件とすることを確認'}).check();await p.getByRole('button',{name:'全員分をHOLDして見積を保存',exact:true}).click();await expect(p.getByRole('region',{name:'見積詳細',exact:true})).toBeVisible();await p.getByRole('link',{name:'非公開の合成予約プレビューへ'}).click();await p.getByLabel('合成氏名').fill('SYNTHETIC Custody Mixed');await p.getByLabel('架空メール宛先').fill('synthetic-custody@example.invalid');await p.getByLabel('開発用の合成予約であり、営業規約・請求の確定ではないことを確認').check();await p.getByRole('button',{name:'合成予約情報を保存',exact:true}).click();await expect(p.getByRole('region',{name:'開発予約詳細'})).toContainText('DRAFT');await p.getByRole('button',{name:'テストアダプタへ照合要求'}).click();await expect(p.getByRole('region',{name:'開発予約詳細'})).toContainText('CONFIRMED_DEV');
  const b=(await app!.db.pool.query('SELECT b.*,h.expires_at FROM rental_bookings b JOIN inventory_holds h ON h.id=b.hold_id')).rows[0];bookingId=b.id;holdId=b.hold_id;ttl=b.expires_at.toISOString();snapshot=b.price_sha256;assert.equal(b.price_snapshot.chargeReady,false);assert.equal(b.price_snapshot.totalJpy,13000);
 });
 await check('wrong Premium model or length rejected; normal screen prepares exact witness and records all serialized equipment',async()=>{
  await clock('2035-01-05T01:00:00Z');const before=await context.request.get('/api/custody/booking/'+bookingId);assert.equal(before.status(),200);const data=await before.json(),selections=data.items.map((i:{requirement_key:string;asset_id:string|null;pole_id:string|null})=>({requirementKey:i.requirement_key,assetId:i.asset_id,poleId:i.pole_id}));
  for(const replacement of [fixtures.assets[fixtures.variants['SKI-155 CM']!]![0]!, '00000000-0000-4000-8000-000000001201']){const wrong=structuredClone(selections);wrong.find((i:{requirementKey:string})=>i.requirementKey.endsWith(':SKI')).assetId=replacement;const r=await context.request.post('/api/custody/prepare',{headers:{origin},data:{requestKey:randomUUID(),input:{bookingId,expectedBookingVersion:data.bookingVersion,expectedHoldVersion:data.holdVersion,selections:wrong,fitEvidence:'SYNTHETIC wrong equipment'}}});assert.equal(r.status(),409);}
  await p.goto('/staff/rental');await p.getByLabel('開発予約IDまたは予約QR').fill('zao-rental:reservation:'+bookingId);await p.getByRole('button',{name:'予約と仮割当を照合'}).click();await expect(p.getByRole('region',{name:'貸出用品'})).toContainText(bookingId);await p.getByLabel('準備・最終適合の作業記録').fill('SYNTHETIC staff recorded fit; no automatic DIN');await p.getByLabel('表示された個体と数量を照合した（合成検証）').check();await p.getByRole('button',{name:'照合した用品を準備固定'}).click();await p.getByRole('button',{name:'道具の貸出を記録'}).click();await expect(p.getByRole('region',{name:'貸出用品'})).toContainText('OUT');
  const loans=(await app!.db.pool.query('SELECT * FROM rental_loan_items WHERE booking_id=$1',[bookingId])).rows;assert.equal(loans.length,3);assert.ok(loans.every(l=>l.cycle_id===bookingId));assetId=loans.find(l=>l.family==='SKI').asset_id;poleId=loans.find(l=>l.family==='POLE').id;bootId=loans.find(l=>l.family==='SKI_BOOT').asset_id;
 });
 await check('quantity wear joins the same reservation/member/cycle without garment assets',async()=>{
  await p.goto('/staff/wear');await p.getByLabel('予約番号',{exact:true}).fill(bookingId);await p.getByRole('button',{name:'貸出を読込',exact:true}).click();await p.getByRole('button',{name:'ウェア数量を貸出記録',exact:true}).click();await expect(p.getByRole('button',{name:'1着を受領：person-1:WEAR_JACKET',exact:true})).toBeVisible();assert.equal((await app!.db.pool.query('SELECT count(*)::int n FROM wear_loans WHERE booking_id=$1 AND cycle_id=$1',[bookingId])).rows[0].n,2);assert.equal((await app!.db.pool.query("SELECT count(*)::int n FROM ledger_assets WHERE family LIKE 'WEAR_%'")).rows[0].n,0);
  await p.getByLabel('実際の受領・表示店舗').selectOption('ONSEN_BASE');await p.getByRole('button',{name:'貸出を読込',exact:true}).click();await p.getByRole('button',{name:'1着を受領：person-1:WEAR_JACKET',exact:true}).click();await expect(p.getByRole('article',{name:'ウェア貸出 person-1:WEAR_JACKET',exact:true})).toContainText('返却済み 1');await expect(p.getByRole('article',{name:'ウェア貸出 person-1:WEAR_PANTS',exact:true})).toContainText('未返却 1');
 });
 await check('continuous return candidates persist exact cycles; duplicate label and response loss/reload do not duplicate receipt',async()=>{
  await p.goto('/staff/rental');await p.getByLabel('受領店舗',{exact:true}).selectOption('ONSEN_BASE');await p.getByRole('button',{name:'この店舗で返却バッチを開始'}).click();await expect(p.getByRole('region',{name:'連続返却バッチ'})).toBeVisible();const bid=await p.getByLabel('保存済み返却バッチID').inputValue();
  async function scan(id:string){await p.getByLabel('用品の個体ID',{exact:true}).fill(id);const response=p.waitForResponse(r=>new URL(r.url()).pathname==='/api/custody/scan'&&r.request().method()==='POST');await p.getByRole('button',{name:'入力したIDを照合へ送る'}).click();assert.equal((await response).status(),200);await expect(p.getByRole('status').filter({hasText:'返却候補をサーバーに保存'})).toBeVisible();}
  await p.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=360;canvas.height=360;canvas.getContext('2d')!.fillRect(0,0,360,360);const media=canvas.captureStream(0),state={canvas,media,requests:0};(window as unknown as {syntheticCamera:typeof state}).syntheticCamera=state;Object.defineProperty(navigator.mediaDevices,'getUserMedia',{configurable:true,value:async()=>{state.requests++;return media;}});});
  async function draw(id:string){const data=await QRCode.toDataURL(id,{width:360,margin:4});await p.evaluate(async data=>{const w=window as unknown as {syntheticCamera:{canvas:HTMLCanvasElement;media:MediaStream}};const img=new Image();img.src=data;await img.decode();w.syntheticCamera.canvas.getContext('2d')!.drawImage(img,0,0,360,360);(w.syntheticCamera.media.getVideoTracks()[0] as CanvasCaptureMediaStreamTrack).requestFrame();},data);}
  await p.getByRole('button',{name:'カメラを開く'}).click();await draw(assetId);await expect(p.getByRole('region',{name:'連続返却バッチ'})).toContainText('person-1:SKI');await draw(randomUUID());await expect(p.getByRole('region',{name:'連続返却バッチ'})).toContainText('UNKNOWN_OR_ALREADY_RECEIVED');assert.equal(await p.evaluate(()=>(window as unknown as {syntheticCamera:{requests:number}}).syntheticCamera.requests),1);await p.getByRole('button',{name:'カメラを止める'}).click();assert.deepEqual(await p.evaluate(()=>(window as unknown as {syntheticCamera:{media:MediaStream}}).syntheticCamera.media.getTracks().map(t=>t.readyState)),['ended']);
  await scan(assetId);await scan(assetId);assert.equal((await app!.db.pool.query('SELECT count(*)::int n FROM rental_return_candidates WHERE batch_id=$1',[bid])).rows[0].n,2);await p.reload();await p.getByLabel('保存済み返却バッチID').fill(bid);await p.getByRole('button',{name:'返却バッチを再開'}).click();await expect(p.getByRole('region',{name:'連続返却バッチ'})).toContainText('CANDIDATE');
  await p.getByLabel('ポールの貸出明細ID').fill(poleId);await p.getByRole('button',{name:'この貸出のポール1ペアを候補に追加'}).click();await expect(p.getByRole('region',{name:'連続返却バッチ'})).toContainText('person-1:POLE');
  await p.route('**/api/custody/confirm',async route=>{const r=await route.fetch();assert.equal(r.status(),200);await route.abort('failed');});await p.getByRole('button',{name:'正常な候補をまとめて受領確定'}).click();await expect(p.getByRole('button',{name:'同じ保存済み要求を照合'})).toBeVisible();await p.unroute('**/api/custody/confirm');await p.reload();await p.getByRole('button',{name:'同じ保存済み要求を照合'}).click();await expect(p.getByRole('region',{name:'連続返却バッチ'})).toContainText('RECEIVED');
  assert.equal((await app!.db.pool.query('SELECT count(*)::int n FROM rental_receipts')).rows[0].n,2);assert.equal((await app!.db.pool.query('SELECT store_id FROM ledger_assets WHERE id=$1',[assetId])).rows[0].store_id,'ONSEN_BASE');assert.equal((await app!.db.pool.query("SELECT state FROM rental_loan_items WHERE asset_id=$1",[bootId])).rows[0].state,'OUT');assert.equal((await app!.db.pool.query('SELECT expires_at FROM inventory_holds WHERE id=$1',[holdId])).rows[0].expires_at.toISOString(),ttl);assert.equal((await app!.db.pool.query('SELECT price_sha256 FROM rental_bookings WHERE id=$1',[bookingId])).rows[0].price_sha256,snapshot);
  await expect(p.getByLabel('受領店舗',{exact:true})).toHaveValue('ONSEN_BASE');await p.getByRole('button',{name:'保存済み返却作業を読込'}).click();await expect(p.getByText('person-1:SKI / 受領済み・検品待ち',{exact:true})).toBeVisible();await p.getByLabel('実際に行った検品記録').fill('SYNTHETIC actual ready inspection');const skiLoan=(await app!.db.pool.query('SELECT id FROM rental_loan_items WHERE asset_id=$1',[assetId])).rows[0].id;await p.getByRole('button',{name:'検品完了 '+skiLoan,exact:true}).click();await expect(p.getByText('person-1:SKI / 検品済み（契約日・当日ブロックは維持）',{exact:true})).toBeVisible();
  const sameDay=requestFor('2035-01-05',[fixtures.variants['SKI-150 cm']!]);sameDay.contractVersion='INTEGRATED_V1_2';sameDay.pickupStore=sameDay.returnStore='ONSEN_BASE';sameDay.members[0]!.tier='PREMIUM';sameDay.members[0]!.items[0]!.modelPromise={modelId:fixtures.models.SKI!,variantId:fixtures.variants['SKI-150 cm']!,season:'2026/27'};const sameDayResponse=await context.request.post('/api/holds/availability',{headers:{origin},data:sameDay});assert.equal(sameDayResponse.status(),200);assert.notEqual((await sameDayResponse.json()).result,'FEASIBLE');
  await mkdir('.local/screenshots',{recursive:true});await p.screenshot({path:'.local/screenshots/custody-desktop.png',fullPage:true});await p.setViewportSize({width:390,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:'.local/screenshots/custody-mobile-width.png',fullPage:true});
 });
 await check('normal API refuses unauthenticated/CSRF/actor flags; revocation closes the current screen and blocks saved session',async()=>{
  const anon=await browser.newContext({baseURL:origin});try{assert.equal((await anon.request.get('/api/custody/booking/'+bookingId)).status(),401);}finally{await anon.close();}
  assert.equal((await context.request.post('/api/custody/batch',{data:{requestKey:randomUUID(),input:{store:'ONSEN_BASE'}}})).status(),403);assert.equal((await context.request.post('/api/custody/batch',{headers:{origin},data:{requestKey:randomUUID(),input:{store:'ONSEN_BASE'},actor:subject}})).status(),422);
  const users=await (await root.request.get('/api/staff-users')).json();const u=(Array.isArray(users)?users:users.items).find((u:{id:string})=>u.id===subject);const updated=await root.request.patch('/api/staff-users/'+subject,{headers:{origin},data:{displayName:u.displayName,active:false,role:u.role,scope:u.scope,storeIds:u.storeIds,permissions:u.permissions,expectedRevision:u.revision}});assert.equal(updated.status(),200);
  await p.getByRole('button',{name:'保存済み返却作業を読込'}).click();await expect(p.getByRole('heading',{name:'セッションを確認してください'})).toBeVisible();assert.equal((await context.request.get('/api/custody/booking/'+bookingId)).status(),401);
 });
 console.log(`CUSTODY ordinary UI/API/real PostgreSQL: ${count} passed, no skipped. Synthetic payment and data; synthetic camera frames and manual QR input, viewport only, no real phone/Square.`);
}catch(e){failed=true;console.error('CUSTODY_UI_FAILED '+stage+' '+(e as Error).name);if(e instanceof assert.AssertionError)console.error(JSON.stringify({actual:e.actual,expected:e.expected}));console.error((e as Error).stack?.split('\n').filter(l=>l.includes('/tests/custody/')).join('\n'));if(page){console.error('LAST_PAGE '+new URL(page.url()).pathname);console.error('UI_ALERT '+(await page.getByRole('alert').allTextContents()).join(' ').slice(0,400));}}finally{await browser.close();await app?.stop();console.log('Owned custody Web/browser/PostgreSQL stopped.');}if(failed)process.exit(1);
