import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import type {PoolClient} from 'pg';
import {flowFixture} from '../flow/fixture';
import {CustodyService} from '../../packages/core/src/rental/custody-service';
import {provisionCustodyRole} from '../../scripts/custody-roles';
import {writeAccount,listAccounts} from '../../packages/auth/src/accounts';
import {skiSet,requestFor,variants,fid} from '../inventory/fixture';
import {TransferService} from '../../packages/core/src/transfer/transfer-service';
import type {HoldConditions} from '../../packages/contracts/src/hold';
const x=await flowFixture();let role:Awaited<ReturnType<typeof provisionCustodyRole>>|undefined,failed=false,stage='start',count=0;
async function check(name:string,fn:()=>Promise<void>){stage=name;await fn();count++;console.log('PASS '+name);}
try{
 role=await provisionCustodyRole(x.db.pool,x.db.identity);const svc=new CustodyService(role.custodyPool,x.roles.authPool,x.signed.identity);
 async function context(c:PoolClient){await c.query("SELECT set_config('zao.actor',$1,true),set_config('zao.session',$2,true),set_config('zao.reason','Synthetic custody scenarios',true)",[x.actor,x.signed.identity.sessionId]);}
 async function start(conditions:HoldConditions){const d=await x.draft(undefined,conditions);await x.service.startPayment(d.booking.id,randomUUID());return d;}
 async function out(id:string,as=svc){const v=await as.checkoutView(id);await as.prepare(randomUUID(),{bookingId:id,expectedBookingVersion:v.bookingVersion,expectedHoldVersion:v.holdVersion,selections:v.items.map(i=>({requirementKey:i.requirement_key,assetId:i.asset_id,poleId:i.pole_id})),fitEvidence:'SYNTHETIC staff fit record'});return as.checkout(randomUUID(),{bookingId:id,expectedPreparationVersion:1});}
 async function scanned(assetId:string|null,poleLoanId:string|null,store='ONSEN_BASE'){let b=await svc.createBatch(randomUUID(),store);b=await svc.scan(randomUUID(),{batchId:b.id,expectedVersion:b.version,assetId,poleLoanId});return b;}
 const group=skiSet('2035-02-01');group.members.push({...structuredClone(group.members[0]!),key:'person-b'});group.members[1]!.items[0]!.variantIds=[variants.skiAlt];
 const d=await start(group);const board=requestFor('2035-03-01');board.members[0]!.product='SNOWBOARD_SET';board.members[0]!.items=[{family:'SNOWBOARD',variantIds:[variants.board]},{family:'SNOWBOARD_BOOT',variantIds:[variants.boardBoot]}];const bd=await start(board);
 await x.clock('2035-02-01T10:00:00+09:00');const receiver=(await writeAccount(x.roles.authPool,x.bp,undefined,{email:'custody-pickup@example.invalid',password:x.password,displayName:'SYNTHETIC scoped pickup',active:true,role:'STAFF',scope:'ASSIGNED',storeIds:['MOUNTAIN_BASE'],permissions:{BOOKING_VIEW:true,RENTAL_CHECKOUT:true}})).id!;const signed=await x.login('custody-pickup@example.invalid');const groupOut=await out(d.booking.id,new CustodyService(role.custodyPool,x.roles.authPool,signed.identity)),poles=groupOut.loans.filter(l=>l.family==='POLE');
 await check('booking creator hands off to distinct scoped pickup staff; returned items may be received by another authorized staff',async()=>{assert.notEqual(receiver,x.actor);assert.ok(groupOut.loans.every(l=>l.checked_out_by===receiver));await assert.rejects(new CustodyService(role!.custodyPool,x.roles.authPool,signed.identity).createBatch(randomUUID(),'ONSEN_BASE'),{code:'FORBIDDEN'});});
 await check('two-member pole partial return, concurrent terminals, replay and inspection conserve every PAIR',async()=>{
  assert.equal(poles.length,2);const total=(await x.db.pool.query('SELECT sum(quantity)::int n FROM ledger_poles')).rows[0].n;
  const aa=await scanned(null,poles[0].id),bb=await scanned(null,poles[0].id),key=randomUUID(),v={batchId:aa.id,expectedVersion:aa.version};await Promise.all([svc.confirm(key,v),svc.confirm(randomUUID(),{batchId:bb.id,expectedVersion:bb.version})]);await svc.confirm(key,v);
  assert.equal((await x.db.pool.query("SELECT count(*)::int n FROM rental_loan_items WHERE booking_id=$1 AND family='POLE' AND state='OUT'",[d.booking.id])).rows[0].n,1);assert.equal((await x.db.pool.query('SELECT sum(quantity)::int n FROM ledger_poles')).rows[0].n,total);
  const q=(await x.db.pool.query('SELECT * FROM rental_pole_custody WHERE id=$1',[poles[0].pole_id])).rows[0];assert.equal(q.accounted_pairs,2);assert.equal(q.out_pairs,1);assert.equal(q.at_store_pairs,1);
  assert.equal((await x.db.pool.query('SELECT count(*)::int n FROM inventory_claims WHERE hold_id=$1 AND requirement_key=$2 AND active',[d.holdId,poles[1].requirement_key])).rows[0].n,1);
  await svc.inspection(randomUUID(),{loanItemId:poles[0].id,expectedVersion:2,store:'ONSEN_BASE',evidence:'SYNTHETIC pair inspected'});assert.equal((await x.db.pool.query('SELECT sum(quantity)::int n FROM ledger_poles')).rows[0].n,total);
 });
 await check('existing transfer cannot dispatch a checked-out individual or consume OUT pole quantity',async()=>{
  const transfer=new TransferService(x.roles.transferPool,x.principal,x.now);const plan={sourceStore:'MOUNTAIN_BASE',destinationStore:'ONSEN_BASE',scheduledDate:'2035-02-01',plannedReadyAt:'2035-02-01T19:00:00+09:00',neededBy:'2035-02-02T08:30:00+09:00',basis:'SYNTHETIC dispatch test; no assumed receipt'};
  await assert.rejects(transfer.command('create',randomUUID(),{...plan,lines:[{assetId:groupOut.loans.find(l=>l.family==='SKI').asset_id}]}));
  await assert.rejects(transfer.command('create',randomUUID(),{...plan,lines:[{poleId:poles[1].pole_id,quantity:2}]}));
  assert.equal((await x.db.pool.query("SELECT count(*)::int n FROM rental_loan_items WHERE booking_id=$1 AND state='OUT'",[d.booking.id])).rows[0].n,5);
 });
 await x.clock('2035-03-01T10:00:00+09:00');const bo=await out(bd.booking.id);const boardLoan=bo.loans.find(l=>l.family==='SNOWBOARD'),boot=bo.loans.find(l=>l.family==='SNOWBOARD_BOOT');
 const oldBatch=await scanned(boardLoan.asset_id,null);
 await check('snowboard and snowboard-boot use one immutable Asset each, receive cross-store and retain same-day block',async()=>{
  assert.equal(bo.loans.length,2);assert.equal(boardLoan.unit,'BOARD');assert.equal(boot.unit,'PAIR');let batch=await scanned(boardLoan.asset_id,null);batch=await svc.scan(randomUUID(),{batchId:batch.id,expectedVersion:batch.version,assetId:boot.asset_id,poleLoanId:null});await svc.confirm(randomUUID(),{batchId:batch.id,expectedVersion:batch.version});
  for(const l of bo.loans){await svc.inspection(randomUUID(),{loanItemId:l.id,expectedVersion:2,store:'ONSEN_BASE',evidence:'SYNTHETIC inspected board or boot pair'});assert.equal((await x.db.pool.query('SELECT store_id FROM ledger_assets WHERE id=$1',[l.asset_id])).rows[0].store_id,'ONSEN_BASE');}
  const q=structuredClone(board);q.reservationId=randomUUID();q.pickupStore=q.returnStore='ONSEN_BASE';assert.notEqual((await x.holds.availability(q)).result,'FEASIBLE');
 });
 await x.clock('2035-03-02T10:00:00+09:00');const next=structuredClone(board);next.reservationId=randomUUID();next.period.startDate=next.period.endDate='2035-03-02';next.pickupStore=next.returnStore='ONSEN_BASE';const nd=await start(next),no=await out(nd.booking.id);
 await check('saved old scan never retargets a new cycle; new scan resolves new exact loan and receipt',async()=>{
  const again=no.loans.find(l=>l.family==='SNOWBOARD');assert.equal(again.asset_id,boardLoan.asset_id);assert.notEqual(again.cycle_id,boardLoan.cycle_id);
  const stale=await svc.confirm(randomUUID(),{batchId:oldBatch.id,expectedVersion:oldBatch.version});assert.equal(stale.candidates[0].outcome,'STALE_LOAN_CYCLE');assert.equal((await x.db.pool.query('SELECT state FROM rental_loan_items WHERE id=$1',[again.id])).rows[0].state,'OUT');
  const fresh=await scanned(again.asset_id,null);assert.equal(fresh.candidates[0].cycle_id,nd.booking.id);await svc.confirm(randomUUID(),{batchId:fresh.id,expectedVersion:fresh.version});assert.equal((await x.db.pool.query('SELECT count(*)::int n FROM rental_custody_events e JOIN rental_loan_items l ON l.id=e.loan_item_id WHERE l.asset_id=$1',[again.asset_id])).rows[0].n,2);
 });
 await check('MULTIDAY continuation is not permission for after-hours physical checkout',async()=>{
  const c=requestFor('2035-03-05',[fid(7106)]);c.members[0]!.items[0]!.family='SNOWBOARD';c.period={startDate:'2035-03-05',endDate:'2035-03-06',slot:'MULTIDAY'};const day=await start(c),v=await svc.checkoutView(day.booking.id);await svc.prepare(randomUUID(),{bookingId:v.bookingId,expectedBookingVersion:v.bookingVersion,expectedHoldVersion:v.holdVersion,selections:v.items.map(i=>({requirementKey:i.requirement_key,assetId:i.asset_id,poleId:i.pole_id})),fitEvidence:'SYNTHETIC preparation; not after-hours permission'});
  await x.clock('2035-03-05T17:01:00+09:00');await assert.rejects(svc.checkout(randomUUID(),{bookingId:v.bookingId,expectedPreparationVersion:1}),{code:'FLOW_CONFLICT'});assert.equal((await x.db.pool.query('SELECT count(*)::int n FROM rental_loan_items WHERE booking_id=$1',[v.bookingId])).rows[0].n,0);await x.clock('2035-03-02T10:00:00+09:00');
 });
 // Commit only a candidate/receipt, then call UUID function separately. This deliberately tests
 // the database boundary without relying on the service's earlier authorization check.
 const target=no.loans.find(l=>l.family==='SNOWBOARD_BOOT'),pending=await scanned(target.asset_id,null);const rid=randomUUID();const insert=await role.custodyPool.connect();try{await insert.query('BEGIN');await context(insert);await insert.query('INSERT INTO rental_receipts VALUES($1,$2,$3,$4,$5,$6,$6,$6)',[rid,target.id,pending.candidates[0].id,'ONSEN_BASE',x.actor,x.now()]);await insert.query('COMMIT');}finally{insert.release();}
 async function directWait(change:()=>Promise<void>){const blocker=await x.db.pool.connect(),caller=await role!.custodyPool.connect();let operation:Promise<unknown>|undefined;try{await blocker.query('BEGIN');await blocker.query('SELECT pg_advisory_xact_lock(71820600)');await caller.query('BEGIN');await context(caller);operation=caller.query('SELECT public.rental_apply_receipt($1)',[rid]).catch(e=>e);let observed=false;for(let n=0;n<200;n++){if((await x.db.pool.query("SELECT 1 FROM pg_stat_activity WHERE usename=$1 AND wait_event_type='Lock'",[role!.custodyDb.user])).rowCount){observed=true;break;}await new Promise(r=>setTimeout(r,3));}assert.ok(observed);await change();await blocker.query('COMMIT');assert.equal((await operation as {code:string}).code,'42501');await caller.query('ROLLBACK');}finally{await blocker.query('ROLLBACK');await caller.query('ROLLBACK');blocker.release();caller.release();}assert.equal((await x.db.pool.query('SELECT count(*)::int n FROM rental_custody_events WHERE receipt_id=$1',[rid])).rows[0].n,0);assert.equal((await x.db.pool.query('SELECT state FROM rental_loan_items WHERE id=$1',[target.id])).rows[0].state,'OUT');}
 await check('UUID function itself rechecks permission removal after inventory-lock wait',async()=>{await directWait(async()=>{const p=(await listAccounts(x.roles.authPool,x.bp)).find(u=>u.id===x.actor)!;await writeAccount(x.roles.authPool,x.bp,x.actor,{displayName:p.displayName,active:true,role:p.role,scope:p.scope,storeIds:p.storeIds,permissions:{...p.permissions,RENTAL_RETURN:false},expectedRevision:p.revision});});});
 const restore=(await listAccounts(x.roles.authPool,x.bp)).find(u=>u.id===x.actor)!;await writeAccount(x.roles.authPool,x.bp,x.actor,{displayName:restore.displayName,active:true,role:restore.role,scope:restore.scope,storeIds:restore.storeIds,permissions:{...restore.permissions,RENTAL_RETURN:true},expectedRevision:restore.revision});
 await check('UUID function itself rejects staff disable/session invalidation after inventory-lock wait',async()=>{await directWait(async()=>{const p=(await listAccounts(x.roles.authPool,x.bp)).find(u=>u.id===x.actor)!;await writeAccount(x.roles.authPool,x.bp,x.actor,{displayName:p.displayName,active:false,role:p.role,scope:p.scope,storeIds:p.storeIds,permissions:p.permissions,expectedRevision:p.revision});});});
 console.log(`CUSTODY scenarios ${count} passed; real PostgreSQL, synthetic stock and normal password/session.`);
}catch(e){failed=true;console.error('CUSTODY_SCENARIOS_FAILED '+stage+' '+((e as {code?:string}).code??(e as Error).name));if(e instanceof assert.AssertionError)console.error(JSON.stringify({actual:e.actual,expected:e.expected}));console.error((e as Error).stack?.split('\n').filter(l=>l.includes('/tests/custody/')).join('\n'));}finally{await role?.close();await x.close();console.log('Owned scenario PostgreSQL stopped.');}if(failed)process.exit(1);
