import type {PoolClient} from 'pg';
import {normalizePeriod,type HoldConditions} from '../../../contracts/src/hold';
export type CapacitySummary={kind:'PHYSICAL'|'PROVISIONAL';supply:string;day:string;operationalCapacity:number;publicCapacity:number;publicClaimed:number;staffOverrideClaimed:number;publicRemaining:number;operationalRemaining:number};
export function capacityFigures(operationalCapacity:number,publicClaimed:number,staffOverrideClaimed:number){const publicCapacity=Math.floor(operationalCapacity*0.95),operationalRemaining=Math.max(0,operationalCapacity-publicClaimed-staffOverrideClaimed);return {operationalCapacity,publicCapacity,publicClaimed,staffOverrideClaimed,publicRemaining:Math.max(0,Math.min(publicCapacity-publicClaimed,operationalRemaining)),operationalRemaining};}
/** Management-only derived counts. Fulfillment still requires the date/custody/transfer allocator. */
export async function capacitySummary(c:Pick<PoolClient,'query'>,conditions:HoldConditions,now:Date):Promise<CapacitySummary[]>{
 const ids=[...new Set(conditions.members.flatMap(m=>m.items.flatMap(i=>i.variantIds)))],days=normalizePeriod(conditions.period).dates;
 const physical=(await c.query<{variant_id:string;quantity:number}>(`SELECT variant_id,sum(quantity)::int AS quantity FROM (SELECT variant_id,1 quantity FROM ledger_assets WHERE status='AVAILABLE' UNION ALL SELECT variant_id,quantity FROM ledger_poles WHERE status='AVAILABLE') u WHERE variant_id=ANY($1::uuid[]) GROUP BY variant_id`,[ids])).rows;
 const usage=(await c.query<{variant_id:string;day:string;public:number;staff:number}>(`SELECT coalesce(a.variant_id,p.variant_id) variant_id,c.day::text,count(*) FILTER(WHERE NOT h.buffer_override)::int public,count(*) FILTER(WHERE h.buffer_override)::int staff FROM inventory_claims c JOIN inventory_holds h ON h.id=c.hold_id LEFT JOIN ledger_assets a ON a.id=c.asset_id LEFT JOIN ledger_poles p ON p.id=c.pole_id WHERE c.active AND coalesce(a.variant_id,p.variant_id)=ANY($1::uuid[]) AND c.day=ANY($2::date[]) AND h.state='ACTIVE' AND (h.expires_at>$3 OR h.payment_state IN ('PENDING','UNKNOWN','SUCCESS') OR h.allocation_stage<>'PROVISIONAL') GROUP BY coalesce(a.variant_id,p.variant_id),c.day`,[ids,days,now])).rows;
 const physicalIds=[...new Set(conditions.members.flatMap(m=>m.items.filter(i=>!i.family.startsWith('WEAR_')).flatMap(i=>i.variantIds)))];
 const rows:CapacitySummary[]=physicalIds.flatMap(id=>days.map(day=>{const u=usage.find(x=>x.variant_id===id&&x.day===day);return {kind:'PHYSICAL',supply:id,day,...capacityFigures(physical.find(x=>x.variant_id===id)?.quantity??0,u?.public??0,u?.staff??0)};}));
 const buckets=(await c.query<{id:string;supply:string;quantity:number}>(`SELECT b.id,b.family||' / '||b.age||' / '||b.booking_size supply,provisional_capacity_effective_quantity(b.id) quantity FROM provisional_capacity_buckets b WHERE b.active AND b.size_mapping_status='MAPPED' AND EXISTS(SELECT 1 FROM ledger_variants v WHERE v.id=ANY($1::uuid[]) AND v.family=b.family AND v.age=b.age AND v.size=b.booking_size)`,[ids])).rows;
 if(buckets.length){
  const claims=(await c.query<{bucket_id:string;day:string;public:number;staff:number}>(`SELECT c.bucket_id,c.day::text,coalesce(sum(c.quantity) FILTER(WHERE NOT h.buffer_override),0)::int public,coalesce(sum(c.quantity) FILTER(WHERE h.buffer_override),0)::int staff FROM provisional_capacity_claims c JOIN inventory_holds h ON h.id=c.hold_id WHERE c.state='ACTIVE' AND c.bucket_id=ANY($1::uuid[]) AND c.day=ANY($2::date[]) AND h.state='ACTIVE' AND (h.expires_at>$3 OR h.payment_state IN ('PENDING','UNKNOWN','SUCCESS') OR h.allocation_stage<>'PROVISIONAL') GROUP BY c.bucket_id,c.day`,[buckets.map(b=>b.id),days,now])).rows;
  for(const supply of new Set(buckets.map(b=>b.supply)))for(const day of days){const group=buckets.filter(b=>b.supply===supply),used=claims.filter(c=>c.day===day&&group.some(b=>b.id===c.bucket_id));rows.push({kind:'PROVISIONAL',supply,day,...capacityFigures(group.reduce((n,b)=>n+b.quantity,0),used.reduce((n,c)=>n+c.public,0),used.reduce((n,c)=>n+c.staff,0))});}
 }
 return rows;
}
