import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
import {chromium,expect} from '@playwright/test';
import {startDevelopmentApp} from '../../scripts/development-app';
import {bootstrapDevelopmentAdmin} from '../../scripts/bootstrap-staff';
import {loadStaff} from '../../packages/auth/src/staff-auth';
import {writeAccount} from '../../packages/auth/src/accounts';
import {seedRecommendation} from '../recommendation/fixture';
import {skiSet} from '../inventory/fixture';
import {provisionFlowRole} from '../../scripts/flow-roles';
import {provisionNotificationRole} from '../../scripts/notification-roles';
import {provisionBookingAccessRole} from '../../scripts/booking-access-role';
import {HoldService} from '../../packages/core/src/inventory/hold-service';
import {QuoteService} from '../../packages/core/src/pricing/quote-service';
import {BookingService} from '../../packages/core/src/payment/booking-service';
import {BookingRecovery} from '../../packages/core/src/guest/booking-recovery';
import {BookingNotificationWorker} from '../../packages/core/src/notification/worker';
import {FakeGateway,simulation} from '../flow/fixture';
import {LoopbackDeliveryAdapter} from './loopback';
const browser=await chromium.launch();let app:Awaited<ReturnType<typeof startDevelopmentApp>>|undefined,flow:Awaited<ReturnType<typeof provisionFlowRole>>|undefined,deliveryRole:Awaited<ReturnType<typeof provisionNotificationRole>>|undefined,accessRole:Awaited<ReturnType<typeof provisionBookingAccessRole>>|undefined,failed=false,stage='setup',count=0,external=0;
async function check(name:string,fn:()=>Promise<void>){stage=name;await fn();count++;console.log('PASS '+name);}
try{
 app=await startDevelopmentApp({built:true,operations:true});const {origin,db,roles}=app;await seedRecommendation(db.pool);const now=new Date('2035-01-01T10:00:00+09:00');await db.pool.query(`CREATE OR REPLACE FUNCTION inventory_clock() RETURNS timestamptz LANGUAGE sql VOLATILE AS $$SELECT '${now.toISOString()}'::timestamptz$$`);
 const password=randomBytes(24).toString('base64url'),root=await bootstrapDevelopmentAdmin(db.pool,{email:'notification-root@example.invalid',displayName:'SYNTHETIC Admin',password}),admin=(await loadStaff(db.pool,root))!;
 const actor=(await writeAccount(roles.authPool,admin,undefined,{email:'notification-operator@example.invalid',password,displayName:'SYNTHETIC Operator',active:true,role:'ADMIN',scope:'ALL',storeIds:[],permissions:{INVENTORY_VIEW:true,HOLD_VIEW:true,HOLD_EDIT:true,QUOTE_VIEW:true,QUOTE_CREATE:true,PRICE_EDIT:true,BOOKING_VIEW:true,BOOKING_CREATE:true,NOTIFICATION_RESEND:true}})).id!;
 await writeAccount(roles.authPool,admin,undefined,{email:'notification-viewer@example.invalid',password,displayName:'SYNTHETIC Viewer',active:true,role:'VIEWER',scope:'ASSIGNED',storeIds:['ONSEN_BASE'],permissions:{INVENTORY_VIEW:true,BOOKING_VIEW:true}});
 for(let i=0;i<150;i++){try{if((await fetch(origin+'/api/health')).ok)break;}catch{}if(i===149)throw Error('LOCAL_START_TIMEOUT');await new Promise(r=>setTimeout(r,100));}
 async function context(){const c=await browser.newContext({baseURL:origin,viewport:{width:390,height:900}});c.setDefaultTimeout(15000);await c.route('**/*',r=>{if(r.request().url().startsWith(origin+'/')||r.request().url().startsWith('data:'))return r.continue();external++;return r.abort();});return c;}
 const c=await context(),page=await c.newPage();await page.goto('/staff/login');await page.getByLabel('メールアドレス',{exact:true}).fill('notification-operator@example.invalid');await page.getByLabel('パスワード',{exact:true}).fill(password);await page.getByRole('button',{name:'ログイン',exact:true}).click();await page.waitForURL(origin+'/staff/ledger');
 flow=await provisionFlowRole(db.pool,db.identity);deliveryRole=await provisionNotificationRole(db.pool,db.identity);accessRole=await provisionBookingAccessRole(db.pool,db.identity);
 const principal=(await loadStaff(db.pool,actor))!,sessionId=(await db.pool.query('SELECT id FROM auth_session WHERE "userId"=$1',[actor])).rows[0].id,holds=new HoldService(roles.holdPool,principal,()=>now),quotes=new QuoteService(roles.pricingPool,principal,()=>now);await quotes.initializePrivate(randomUUID(),'2035-01-01','2035-12-31');
 const conditions=skiSet('2035-02-05'),h=await holds.command('create',randomUUID(),conditions),q=(await quotes.create(randomUUID(),{conditions,holdId:h.holdId,couponCode:null,wantAdvance:false})).quote,bookings=new BookingService(flow.flowPool,roles.authPool,{subject:actor,sessionId},new FakeGateway(()=>now),simulation),b=await bookings.create(randomUUID(),q.id,{displayName:'SYNTHETIC Guest',email:'synthetic-ui@example.invalid',termsAccepted:true});await bookings.startPayment(b.id,randomUUID());
 const delivery=(await db.pool.query('SELECT id FROM booking_notification_outbox WHERE booking_id=$1',[b.id])).rows[0].id,worker=new BookingNotificationWorker(deliveryRole.notificationPool,origin,new BookingRecovery(accessRole.accessPool,randomBytes(32),'ui-v1'),new LoopbackDeliveryAdapter());await worker.dispatch(delivery);
 await check('normal staff UI lists safe status and saves one audited manual resend after lost HTTP response',async()=>{await page.goto('/admin/notifications');await page.getByRole('button',{name:'通知状態を読み込む'}).click();await expect(page.getByRole('region',{name:'通知一覧'})).toContainText('SENT');assert.ok(!(await page.content()).includes('synthetic-ui@example.invalid'));
  let observed!:()=>void;const lost=new Promise<void>(r=>observed=r);await page.route('**/api/operations/notification-resend',async r=>{const response=await r.fetch();assert.equal(response.status(),200);await r.abort('failed');observed();});await page.getByRole('button',{name:'再送を依頼',exact:true}).click();await lost;await expect(page.getByRole('status')).toContainText('未確認');await page.unroute('**/api/operations/notification-resend');await page.getByRole('button',{name:'再送を依頼',exact:true}).click();await expect(page.getByRole('status')).toContainText('保存しました');assert.equal((await db.pool.query('SELECT count(*)::int n FROM booking_notification_outbox WHERE parent_delivery_id=$1',[delivery])).rows[0].n,1);
 });
 await check('notification page fits 390/768/1440; anonymous, store, permission and CSRF are denied',async()=>{for(const width of [390,768,1440]){await page.setViewportSize({width,height:900});await page.goto('/admin/notifications');await page.getByRole('button',{name:'通知状態を読み込む'}).click();await expect(page.getByRole('region',{name:'通知一覧'})).toContainText('PENDING');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}const anon=await context();assert.equal((await anon.request.get('/api/operations/notifications?store=MOUNTAIN_BASE')).status(),401);await anon.close();assert.equal((await c.request.post('/api/operations/notification-resend',{data:{requestKey:randomUUID(),input:{deliveryId:delivery,store:'MOUNTAIN_BASE',reason:'CUSTOMER_REQUEST'}}})).status(),403);
  const v=await context(),vp=await v.newPage();await vp.goto('/staff/login');await vp.getByLabel('メールアドレス',{exact:true}).fill('notification-viewer@example.invalid');await vp.getByLabel('パスワード',{exact:true}).fill(password);await vp.getByRole('button',{name:'ログイン',exact:true}).click();await vp.waitForURL(origin+'/staff/ledger');await vp.goto('/admin/notifications');await expect(vp.getByRole('button',{name:'再送を依頼',exact:true})).toHaveCount(0);assert.equal((await v.request.get('/api/operations/notifications?store=MOUNTAIN_BASE')).status(),403);assert.equal((await v.request.post('/api/operations/notification-resend',{headers:{origin},data:{requestKey:randomUUID(),input:{deliveryId:delivery,store:'ONSEN_BASE',reason:'CUSTOMER_REQUEST'}}})).status(),403);await v.close();
 });
 await check('booking survives notification failure and logout blocks former staff session',async()=>{const saved=(await db.pool.query('SELECT state FROM rental_bookings WHERE id=$1',[b.id])).rows[0];assert.equal(saved.state,'CONFIRMED_DEV');await page.goto('/staff/ledger');await page.getByRole('button',{name:'ログアウト',exact:true}).click();await expect.poll(async()=>(await c.request.get('/api/operations/notifications?store=MOUNTAIN_BASE')).status()).toBe(401);assert.equal(external,0);});
 console.log(JSON.stringify({status:'PASS',cases:count,externalRequests:external,actualMailSmsProviderRequests:0,normalApp:'apps/web'}));
}catch(e){failed=true;console.error(JSON.stringify({status:'FAIL',stage,code:(e as {code?:string}).code??'UI_ASSERTION',location:(e as Error).stack?.split('\n').filter(s=>s.includes('/tests/notification/')).join('\n')}));}finally{await browser.close();await accessRole?.close();await deliveryRole?.close();await flow?.close();await app?.stop();}if(failed)process.exit(1);
