import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
import {mkdir} from 'node:fs/promises';
import {chromium,expect} from '@playwright/test';
import {startFlowApp} from '../flow/launcher';
import {bootstrapDevelopmentAdmin} from '../../scripts/bootstrap-staff';
import {loadStaff,ledgerPrincipal} from '../../packages/auth/src/staff-auth';
import {verifyLedgerWrite} from '../../packages/auth/src/ledger-write-authority';
import {reconcileLedgerProtection} from '../../packages/core/src/catalog/reconcile-protection';
import {LedgerService} from '../../packages/core/src/catalog/ledger-service';
import {WearService} from '../../packages/core/src/wear/service';
import {registerWear} from '../wear/fixture';
import {seedPublicContent} from './content-seed';
const browser=await chromium.launch(),password=randomBytes(24).toString('base64url');let app:Awaited<ReturnType<typeof startFlowApp>>|undefined,stage='setup',count=0,failed=false;
const check=async(n:string,f:()=>Promise<void>)=>{stage=n;await f();count++;console.log('PASS '+n);};
try{
 app=await startFlowApp({publicP0:true});const {origin,db,roles,flow}=app,subject=await bootstrapDevelopmentAdmin(db.pool,{email:'content-pg-root@example.invalid',displayName:'SYNTHETIC Content Root',password});for(const permission of ['BOOKING_VIEW','INVENTORY_VIEW','INVENTORY_EDIT'])await db.pool.query('INSERT INTO staff_permission_overrides(staff_id,permission,allowed) VALUES($1,$2,true)',[subject,permission]);
 for(let n=0;n<100;n++){try{if((await fetch(origin+'/api/health')).ok)break;}catch{}if(n===99)throw new Error('APP_START_TIMEOUT');await new Promise(r=>setTimeout(r,100));}
 const c=await browser.newContext({baseURL:origin,viewport:{width:390,height:844}});c.setDefaultTimeout(15000);const page=await c.newPage();await page.goto('/staff/login');await page.getByLabel('メールアドレス',{exact:true}).fill('content-pg-root@example.invalid');await page.getByLabel('パスワード',{exact:true}).fill(password);await page.getByRole('button',{name:'ログイン',exact:true}).click();await page.waitForURL(origin+'/staff/ledger');
 const identity={subject,sessionId:(await db.pool.query('SELECT id FROM auth_session WHERE "userId"=$1',[subject])).rows[0].id},principal=(await loadStaff(db.pool,subject))!,ledger=new LedgerService(roles.ledgerPool,ledgerPrincipal(principal),(conn,s,all)=>verifyLedgerWrite(conn,roles.authPool,identity,s,all),(r,id,v)=>reconcileLedgerProtection(roles.transferPool,roles.authPool,identity,r,id,v)),wear=new WearService(flow.flowPool,roles.authPool,identity),stock=await registerWear(ledger,wear),seed=await seedPublicContent(db.pool,subject,{id:stock.models.SKI!,variantIds:[stock.variants['SKI-150 cm']!],season:'2026/27'}),anon=await browser.newContext({baseURL:origin});
 await check('normal staff password + explicit content rights; anonymous reads reject and unpublished physical model is not exposed',async()=>{assert.equal((await anon.request.get('/api/content')).status(),401);assert.equal((await c.request.get('/ja/rental/premium/synthetic-ski')).status(),404);await page.goto('/staff/content');await expect(page.getByRole('region',{name:'現在の下書き'})).toContainText('合成スキー');});
 await check('ordinary CMS CSV dry run -> partial commit -> PostgreSQL revisions/audit, then reviewed bilingual release',async()=>{const csv='schema_version,offer_code,locale,expected_revision,field,operation,value\n1,synthetic-ski,en,1,summary,SET,Synthetic English description updated\n1,synthetic-ski,ja,1,price,SET,1';await page.getByLabel('CSVファイル').setInputFiles({name:'synthetic.csv',mimeType:'text/csv',buffer:Buffer.from(csv)});await page.getByRole('button',{name:'差分を検証して保存'}).click();await page.getByRole('button',{name:/^有効な下書きを反映/}).click();await expect(page.getByRole('status',{name:'説明処理状態'})).toContainText('一部の下書きを保存済み');assert.equal((await db.pool.query('SELECT count(*)::int n FROM content_audit_records')).rows[0].n,1);await page.getByRole('button',{name:'下書き全体のreleaseを検証'}).click();await page.getByRole('button',{name:/^非公開releaseへ反映/}).click();await expect(page.getByRole('status',{name:'説明処理状態'})).toContainText('保存済み');assert.equal((await db.pool.query('SELECT count(*)::int n FROM content_outbox')).rows[0].n,1);});
 await check('released model SSR contains only verified length, semantic metadata and image srcset; JPEG/WebP derivatives are served, originals denied',async()=>{const response=await anon.request.get('/en/rental/premium/synthetic-ski'),html=await response.text();assert.equal(response.status(),200);assert.match(html,/Synthetic English description updated/);assert.match(html,/150 cm/);assert.doesNotMatch(html,/155 CM/);assert.match(html,/srcSet=/i);assert.match(html,/width="800"/);assert.match(html,/hrefLang="ja"/i);const image=await anon.request.get(seed.media.variants[0]!.src);assert.equal(image.status(),200);assert.equal(image.headers()['content-type'],seed.media.variants[0]!.type);assert.equal((await anon.request.get('/media/'+seed.sourceHash+'/800.webp')).status(),404);await page.goto('/en/rental/premium/synthetic-ski');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mkdir('.local/screenshots',{recursive:true});await page.screenshot({path:'.local/screenshots/public-model-en-mobile.png',fullPage:true});assert.doesNotMatch(await (await anon.request.get('/sitemap.xml')).text(),/<loc>/);});
 await check('normal staff photo upload persists manifest/derivatives in PG and same job reloads after response loss',async()=>{await page.goto('/staff/content');await page.getByLabel('写真ファイル').setInputFiles({name:'synthetic-ski__DETAIL__01.png',mimeType:'image/png',buffer:seed.source});let done!:()=>void,fail!:(e:unknown)=>void;const lost=new Promise<void>((r,j)=>{done=r;fail=j;});await page.route('**/api/content-photos/upload',async route=>{try{const r=await route.fetch();assert.equal(r.status(),200);await route.abort('failed');done();}catch(e){fail(e);}});await page.getByRole('button',{name:'選択した写真を送信・再開'}).click();await lost;await expect(page.getByRole('status',{name:'写真処理状態'})).toContainText('未確認');await page.unroute('**/api/content-photos/upload');await page.reload();await page.getByRole('button',{name:'保存済み写真jobを照合'}).click();await expect(page.getByRole('region',{name:'写真一括fixture'})).toContainText('変換済み 1');const state=(await db.pool.query('SELECT value FROM content_workspace')).rows[0].value;assert.equal(Object.keys(state.photoJobs).length,1);assert.equal(Object.values<{revision:number}>(state.photoJobs)[0]!.revision,2);await page.screenshot({path:'.local/screenshots/content-pg-mobile.png',fullPage:true});});
 await check('rights withdrawal removes index/model/media; explicit retired model yields410, legacy route redirects once; current staff revocation denies CMS',async()=>{await db.pool.query("UPDATE content_model_previews SET rights_verified=false WHERE slug='synthetic-ski'");assert.equal((await anon.request.get('/en/rental/premium/synthetic-ski')).status(),404);assert.equal((await anon.request.get(seed.media.variants[0]!.src)).status(),404);assert.doesNotMatch(await (await anon.request.get('/sitemap.xml')).text(),/synthetic-ski/);await db.pool.query("UPDATE content_model_previews SET state='WITHDRAWN' WHERE slug='synthetic-ski'");assert.equal((await anon.request.get('/en/rental/premium/synthetic-ski')).status(),410);const redirect=await anon.request.get('/ja/ski-rental',{maxRedirects:0});assert.equal(redirect.status(),308);assert.equal(new URL(redirect.headers().location!,origin).pathname,'/ja/rental/ski');await db.pool.query('DELETE FROM content_staff_access WHERE staff_id=$1',[subject]);const stamp=(await (await c.request.get('/api/session')).json()).stamp;assert.equal((await c.request.get('/api/content',{headers:{'x-zao-session':stamp}})).status(),403);assert.equal((await c.request.post('/api/content/bulk-prepare',{headers:{origin,'x-zao-session':stamp},data:{requestKey:randomUUID(),input:{csv:''}}})).status(),403);});
 console.log('Content/public model ordinary UI '+count+' passed; synthetic metadata/media, no live storage provider.');
}catch(e){failed=true;console.error('CONTENT_UI_FAILED '+stage+' '+String((e as {code?:string}).code??(e as Error).message.split('\n')[0]));if(e instanceof assert.AssertionError)console.error(JSON.stringify({actual:e.actual,expected:e.expected}));console.error((e as Error).stack?.split('\n').filter(s=>s.includes('/tests/public/')).join('\n'));}finally{await browser.close();await app?.stop();console.log('Owned content browser/Web/PostgreSQL stopped.');}if(failed)process.exit(1);
