import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
import {mkdir} from 'node:fs/promises';
import {chromium,expect,type Page} from '@playwright/test';
import {startFlowApp} from '../flow/launcher';
import {seedRecommendation,variants} from '../recommendation/fixture';
import {bootstrapDevelopmentAdmin} from '../../scripts/bootstrap-staff';
import {QuoteService} from '../../packages/core/src/pricing/quote-service';
import {loadStaff} from '../../packages/auth/src/staff-auth';
let app:Awaited<ReturnType<typeof startFlowApp>>|undefined,stage='setup',count=0,failed=false,last:Page|undefined;
const browser=await chromium.launch(),password=randomBytes(24).toString('base64url');
async function check(name:string,f:()=>Promise<void>){stage=name;await f();count++;console.log('PASS '+name);}
async function staffLogin(page:Page,email:string){
 await page.goto('/staff/login');await page.getByLabel('メールアドレス',{exact:true}).fill(email);await page.getByLabel('パスワード',{exact:true}).fill(password);
 const [signed]=await Promise.all([page.waitForResponse(r=>r.url()===app!.origin+'/api/auth/sign-in/email'&&r.request().method()==='POST',{timeout:60000}),page.getByRole('button',{name:'ログイン',exact:true}).click()]);
 assert.equal(signed.status(),200);await page.waitForURL(app!.origin+'/staff/ledger',{timeout:60000});
}
try{
 app=await startFlowApp({publicP0:true});await seedRecommendation(app.db.pool,true);await app.db.pool.query("CREATE OR REPLACE FUNCTION inventory_clock() RETURNS timestamptz LANGUAGE sql VOLATILE AS $$SELECT '2035-01-01T01:00:00Z'::timestamptz$$");
 const root=await bootstrapDevelopmentAdmin(app.db.pool,{email:'public-root@example.invalid',displayName:'SYNTHETIC Root',password});for(const permission of ['PRICE_EDIT','QUOTE_VIEW'])await app.db.pool.query('INSERT INTO staff_permission_overrides(staff_id,permission,allowed) VALUES($1,$2,true)',[root,permission]);

 await new QuoteService(app.roles.pricingPool,(await loadStaff(app.db.pool,root))!).initializePrivate(randomUUID(),'2035-01-01','2035-12-31');
 for(let n=0;n<100;n++){try{if((await fetch(app.origin+'/api/health')).ok)break;}catch{}if(n===99)throw new Error('APP_START_TIMEOUT');await new Promise(r=>setTimeout(r,100));}
 const context=await browser.newContext({baseURL:app.origin,viewport:{width:390,height:844}});context.setDefaultTimeout(15000);const page=await context.newPage();last=page;
 // Finish dev-only cold compilation before any staff form is filled. Anonymous
 // reads must retain their normal status; no staff/session fixture is injected.
 for(const path of ['/staff/login','/staff/ledger','/staff/users'])assert.equal((await context.request.get(path)).status(),200);
 assert.equal((await context.request.get('/api/auth/sign-in/email')).status(),405);
 for(const path of ['/api/session','/api/staff-users','/api/ledger/assets'])assert.equal((await context.request.get(path)).status(),401);
 await check('JA/EN primary content, unique metadata, canonical/hreflang/JSON-LD are in initial HTML; private/query URLs noindex',async()=>{
  const titles=new Set();for(const locale of ['ja','en'])for(const path of ['','rental','rental/ski','rental/snowboard','rental/premium','rental/wear','rental/kids-family','prices','stores/mountain-base','stores/onsen-base','pickup-return','faq']){const response=await context.request.get('/'+locale+(path?'/'+path:''));assert.equal(response.status(),200);const html=await response.text();assert.match(html,/<h1>/);assert.match(html,/rel="canonical"/);assert.match(html,/hrefLang="x-default"/i);assert.match(html,/application\/ld\+json/);assert.match(html,/BreadcrumbList/);const title=/<title>(.*?)<\/title>/.exec(html)?.[1];assert.ok(title&&!titles.has(title));titles.add(title);assert.ok(!response.headers()['x-robots-tag']?.includes('noindex'));}
  assert.match(await (await context.request.get('/sitemap.xml')).text(),/\/en\/rental\/ski/);assert.doesNotMatch(await (await context.request.get('/sitemap.xml')).text(),/<loc>[^<]*(?:\/book|\/staff|\?)/);assert.match(await (await context.request.get('/robots.txt')).text(),/Disallow:.*book/);
  for(const path of ['/ja/book','/api/guest/draft','/staff/login','/ja/rental?date=2035-01-05&people=20'])assert.match((await context.request.get(path)).headers()['x-robots-tag']??'',/noindex/);
  assert.equal((await context.request.get('/en/not-a-page')).status(),404);
  await page.goto('/ja/rental');await expect(page.getByRole('heading',{level:1})).toBeVisible();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mkdir('.local/screenshots',{recursive:true});await page.screenshot({path:'.local/screenshots/public-ja-mobile.png',fullPage:true});
 });
 await check('guest ordinary mobile UI -> explicit size -> server group total, without early HOLD',async()=>{
  await page.goto('/ja/book');await expect(page.getByLabel('利用開始日',{exact:true})).toBeEnabled();await page.getByLabel('利用開始日',{exact:true}).fill('2035-01-05');await page.getByLabel('利用終了日',{exact:true}).fill('2035-01-06');await page.getByLabel('利用枠',{exact:true}).selectOption('MULTIDAY');await page.getByRole('button',{name:'用品を選ぶ',exact:true}).click();await page.getByLabel('ポールのサイズ 1',{exact:true}).selectOption('pole-'+variants.pole); // option keys come from the server below if catalog prefix differs
  await page.getByRole('button',{name:'候補と参考料金を確認',exact:true}).click();await page.getByRole('radio',{name:/おすすめ/}).check();await page.getByLabel('全員のサイズ・モデル条件・ウェア構成を確認した').check();await page.getByRole('button',{name:'全員分の最終確認へ'}).click();await expect(page.getByRole('region',{name:'全員分の確認'})).toContainText('全員分の参考総額');assert.equal((await app!.db.pool.query('SELECT count(*)::int n FROM inventory_holds')).rows[0].n,0);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'.local/screenshots/guest-review-mobile.png',fullPage:true});
 });
 await check('final test payment response loss and reload restore the same booking/QR from real DB without duplicate hold or payment',async()=>{
  await page.getByLabel('合成データによる開発確認であることを確認').check();let done!:()=>void,fail!:(e:unknown)=>void;const lost=new Promise<void>((r,j)=>{done=r;fail=j;});await page.route('**/api/guest/checkout',async route=>{try{const response=await route.fetch();assert.equal(response.status(),200);await route.abort('failed');done();}catch(e){fail(e);}});await page.getByRole('button',{name:'在庫をHOLDして開発用決済を照合'}).click();await lost;await expect(page.getByRole('button',{name:'保存済みの結果を再読込'})).toBeEnabled();await expect(page.getByRole('main').getByRole('alert')).toContainText('Failed to fetch');await page.unroute('**/api/guest/checkout');await page.reload();await expect(page.getByRole('heading',{name:'CONFIRMED_DEV',exact:true})).toBeVisible();await expect(page.getByRole('img',{name:'開発予約QR',exact:true})).toBeVisible();const before=(await app!.db.pool.query('SELECT expires_at FROM inventory_holds')).rows[0].expires_at.toISOString();await page.getByRole('button',{name:'保存済みの結果を再読込'}).click();assert.equal((await app!.db.pool.query('SELECT count(*)::int n FROM rental_payment_attempts')).rows[0].n,1);assert.equal((await app!.db.pool.query('SELECT count(*)::int n FROM inventory_holds')).rows[0].n,1);assert.equal((await app!.db.pool.query('SELECT expires_at FROM inventory_holds')).rows[0].expires_at.toISOString(),before);await page.screenshot({path:'.local/screenshots/guest-confirmed-mobile.png',fullPage:true});
 });
 await check('cross-guest/CSRF and role/amount tampering rejected; logout drops the former context',async()=>{
  const old=await (await context.request.get('/api/guest/draft')).json();const other=await browser.newContext({baseURL:app!.origin});assert.equal((await other.request.get('/api/guest/draft')).status(),401);assert.equal((await other.request.post('/api/guest/context',{data:{}})).status(),403);await other.request.post('/api/guest/context',{headers:{origin:app!.origin},data:{}});assert.equal((await other.request.post('/api/guest/draft',{headers:{origin:app!.origin},data:{draftId:old.id,expectedRevision:old.revision,input:old.input}})).status(),403);assert.equal((await context.request.post('/api/guest/checkout',{headers:{origin:app!.origin},data:{paid:true,amount:1,role:'ADMIN'}})).status(),422);await page.getByRole('button',{name:'この予約画面を閉じる'}).click();await page.waitForURL(app!.origin+'/ja');assert.equal((await context.request.get('/api/guest/draft')).status(),401);await other.close();
 });
 await check('guest-confirmed MULTIDAY first-day no-show -> normal staff login/UI -> day2 actual checkout, original contract/price unchanged',async()=>{
  const booking=(await app!.db.pool.query('SELECT * FROM rental_bookings ORDER BY created_at LIMIT 1')).rows[0];const before={conditions:booking.conditions,price:booking.price_snapshot,hash:booking.price_sha256};
  await app!.db.pool.query("CREATE OR REPLACE FUNCTION inventory_clock() RETURNS timestamptz LANGUAGE sql VOLATILE AS $$SELECT '2035-01-05T17:01:00+09:00'::timestamptz$$");assert.equal((await app!.db.pool.query('SELECT count(*)::int n FROM inventory_claims WHERE hold_id=$1 AND active',[booking.hold_id])).rows[0].n,6);
  const adminContext=await browser.newContext({baseURL:app!.origin}),adminPage=await adminContext.newPage();last=adminPage;adminContext.setDefaultTimeout(15000);await staffLogin(adminPage,'public-root@example.invalid');
  // URL navigation alone is not a completed authenticated UI. Create the handoff
  // operator through the existing management form after its session boundary opens.
  // One submission only: neither a 500 nor a lost response is retried here.
  await adminPage.goto('/staff/users');await adminPage.getByRole('button',{name:'スタッフを作成',exact:true}).click();
  const form=adminPage.getByRole('form',{name:'スタッフ作成'});await form.getByLabel('表示名',{exact:true}).fill('SYNTHETIC Handoff');await form.getByLabel('メールアドレス',{exact:true}).fill('public-custody@example.invalid');await form.getByLabel('初期パスワード（15〜128文字）').fill(password);await form.getByLabel('MOUNTAIN_BASE',{exact:true}).check();
  for(const label of ['台帳の閲覧','開発予約の閲覧','開発用受付・貸出'])await form.getByLabel(label,{exact:true}).selectOption('allow');
  const [created]=await Promise.all([adminPage.waitForResponse(r=>r.url()===app!.origin+'/api/staff-users'&&r.request().method()==='POST',{timeout:60000}),form.getByRole('button',{name:'スタッフ設定を保存'}).click()]);console.log('STAFF_CREATION '+JSON.stringify({status:created.status(),json:created.headers()['content-type']?.includes('application/json')===true}));assert.equal(created.status(),201);await expect(adminPage.getByRole('heading',{name:'SYNTHETIC Handoff',exact:true})).toBeVisible();await adminContext.close();
  const staff=await browser.newContext({baseURL:app!.origin,viewport:{width:390,height:844}});staff.setDefaultTimeout(15000);const p=await staff.newPage();last=p;await staffLogin(p,'public-custody@example.invalid');
  await app!.db.pool.query("CREATE OR REPLACE FUNCTION inventory_clock() RETURNS timestamptz LANGUAGE sql VOLATILE AS $$SELECT '2035-01-06T10:00:00+09:00'::timestamptz$$");await p.goto('/staff/rental');await expect.poll(()=>p.getByRole('button',{name:'予約と仮割当を照合'}).evaluate(b=>typeof (b as HTMLButtonElement).onclick)).toBe('function');await p.getByLabel('開発予約IDまたは予約QR').fill('zao-rental:reservation:'+booking.id);await p.evaluate(async()=>{window.dispatchEvent(new PageTransitionEvent('pageshow',{persisted:false}));await new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r())));});await expect(p.getByLabel('開発予約IDまたは予約QR')).toHaveValue('zao-rental:reservation:'+booking.id);const assignmentResponse=p.waitForResponse(r=>r.url().includes('/api/custody/booking/')&&r.request().method()==='GET');await expect(p.getByLabel('開発予約IDまたは予約QR')).toHaveValue('zao-rental:reservation:'+booking.id);await p.getByRole('button',{name:'予約と仮割当を照合'}).click();const ar=await assignmentResponse;const av=await ar.json();console.log('HANDOFF_RESPONSE '+JSON.stringify({status:ar.status(),error:av.error,pickupTiming:av.pickupTiming}));await expect(p.getByRole('region',{name:'貸出用品'})).toContainText('LATE_PICKUP_ELIGIBLE');await p.getByLabel('準備・最終適合の作業記録').fill('SYNTHETIC staff handoff, no DIN inference');await p.getByLabel('表示された個体と数量を照合した（合成検証）').check();await p.getByRole('button',{name:'照合した用品を準備固定'}).click();await p.getByRole('button',{name:'道具の貸出を記録'}).click();await expect(p.getByRole('region',{name:'貸出用品'})).toContainText('OUT');const after=(await app!.db.pool.query('SELECT * FROM rental_bookings WHERE id=$1',[booking.id])).rows[0];assert.deepEqual({conditions:after.conditions,price:after.price_snapshot,hash:after.price_sha256},before);const loans=(await app!.db.pool.query('SELECT checked_out_at,due_at FROM rental_loan_items WHERE booking_id=$1',[booking.id])).rows;assert.equal(loans.length,3);assert.ok(loans.every(l=>l.checked_out_at.toISOString()==='2035-01-06T01:00:00.000Z'&&l.due_at.toISOString()==='2035-01-06T08:00:00.000Z'));await p.screenshot({path:'.local/screenshots/late-pickup-staff-mobile.png',fullPage:true});await staff.close();
 });
 console.log(`Public/guest UI ${count} cases passed; synthetic adapter and mobile viewport, not real device/Square.`);
}catch(e){failed=true;console.error('PUBLIC_UI_FAILED '+stage+' '+(e instanceof assert.AssertionError?JSON.stringify({actual:e.actual,expected:e.expected}):(e as Error).message));if(last){await mkdir('.local/screenshots',{recursive:true});await last.screenshot({path:'.local/screenshots/public-failure.png',fullPage:true});console.error('LAYOUT '+JSON.stringify(await last.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,wide:[...document.querySelectorAll('*')].filter(e=>e.getBoundingClientRect().right>innerWidth+1).map(e=>({tag:e.tagName,cls:e.className,width:e.getBoundingClientRect().width})).slice(0,10)}))));}if(last)console.error('PAGE_ALERT '+(await last.locator('[role=alert],[role=status]').allTextContents()).join(' '));console.error((e as Error).stack?.split('\n').filter(s=>s.includes('/tests/public/')).join('\n'));}finally{await browser.close();await app?.stop();console.log('Owned Public browser/Web/PostgreSQL stopped.');}if(failed)process.exit(1);
