import {notFound,permanentRedirect} from 'next/navigation';
import Link from 'next/link';
import {publicModels,modelState} from '../../../../../lib/public-content';
import {publicMetadata} from '../../../../../lib/public-seo';
import {safeJsonLd,publicOrigin,canonicalPath,type Locale} from '../../../../../../../../packages/core/src/content/public-pages';
import '../../../../../components/public.css';
type Props={params:Promise<{locale:string;slug:string}>;searchParams:Promise<Record<string,string>>};
async function find(p:Props){const {locale,slug}=await p.params;if(!['ja','en'].includes(locale))notFound();return {locale:locale as Locale,slug,model:(await publicModels()).find(m=>m.slug===slug)};}
export async function generateMetadata(p:Props){const {locale,slug,model}=await find(p);return model?publicMetadata(locale,'rental/premium/'+slug,model.content[locale].title,model.content[locale].summary,Object.keys(await p.searchParams).length>0):{robots:{index:false,follow:false}};}
export default async function Page(p:Props){const {locale,slug,model:m}=await find(p);if(!m){if(await modelState(slug)==='WITHDRAWN')permanentRedirect('/'+locale+'/retired/'+slug);notFound();}const media=m.media,webp=media.variants.filter(v=>v.type==='image/webp'),jpeg=media.variants.filter(v=>v.type==='image/jpeg'),src=(jpeg[0]??webp[0])!,ja=locale==='ja',origin=publicOrigin(process.env.ZAO_PUBLIC_ORIGIN);return <main className="public-main"><Link href={'/'+locale+'/rental/premium'}>Premium</Link><h1>{m.content[locale].title}</h1><p>{m.content[locale].summary}</p><picture>{webp.length>0&&<source type="image/webp" srcSet={webp.map(v=>v.src+' '+v.width+'w').join(', ')} sizes="(max-width: 720px) 90vw, 640px"/>}<img src={src.src} srcSet={jpeg.map(v=>v.src+' '+v.width+'w').join(', ')||undefined} sizes="(max-width: 720px) 90vw, 640px" width={media.width} height={media.height} alt={media.alt} style={{maxWidth:'100%',height:'auto'}}/></picture><dl><dt>{ja?'シーズン':'Season'}</dt><dd>{m.season}</dd><dt>{ja?'当店取扱確認済みの長さ':'Verified shop lengths'}</dt><dd>{m.lengths.join(' / ')}</dd></dl><p>{ja?'モデル・版・選択した長さを予約条件として維持します。期間別在庫は候補選択時に確認します。':'The chosen model, edition and length remain the booking promise. Period stock is checked during selection.'}</p><Link href={'/'+locale+'/book'}>{ja?'日程から選ぶ':'Start with dates'}</Link><p>{ja?'非公開開発プレビュー。実料金・税・公開承認は別途確認中。':'Private development preview. Price, tax and public approval remain pending.'}</p><script type="application/ld+json" dangerouslySetInnerHTML={{__html:safeJsonLd({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Premium',item:origin+canonicalPath(locale,'rental/premium')},{'@type':'ListItem',position:2,name:m.content[locale].title,item:origin+canonicalPath(locale,'rental/premium/'+slug)}]})}}/></main>;}
