import {HoldError} from '../../../contracts/src/hold';
import {parseVerifiedSquareWebhook} from './square-boundary';
import {randomUUID} from 'node:crypto';
import type {Pool,PoolClient} from 'pg';
import {loadStaff,type Permission} from '../../../auth/src/staff-auth';
import {authorizeBookingActor,isGuest,type GuestActor} from '../../../auth/src/booking-actor';
import {type HoldConditions} from '../../../contracts/src/hold';
import {advanceQualification} from '../../../contracts/src/pricing';
import {FlowError,flowId,flowHash,syntheticContact,expectedClaimKeys,reservationQr,matchPayment,type PaymentGateway,type PaymentRequest,type PaymentObservation,type FlowPermission} from '../../../contracts/src/rental-flow';
export type FlowIdentity={subject:string;sessionId:string}|(GuestActor&{sessionId?:never});
export type BookingRow={id:string;owner_id:string;request_key:string;fingerprint:string;hold_id:string;quote_id:string;conditions:HoldConditions;price_snapshot:Record<string,unknown>;price_sha256:string;contact:ReturnType<typeof syntheticContact>;mode:'SIMULATED_DEV'|'SQUARE_SANDBOX';state:string;confirmed_at:Date|null;version:number;notification_locale:'ja'|'en'};
type HoldRow={id:string;owner_id:string;state:string;conditions:HoldConditions;payment_state:string;expires_at:Date;due_at:Date;allocation_stage:string;transfer_attention:string|null;version:number};
type AttemptRow={id:string;booking_id:string;actor:string;idempotency_key:string;merchant_id:string;location_id:string;amount_jpy:string;currency:'JPY';state:string;provider_id:string|null;provider_state:string|null;provider_updated_at:Date|null;completed_at:Date|null};
type Connection=Pick<PoolClient,'query'>;
export class BookingService{
 constructor(protected pool:Pool,protected authPool:Pool,protected identity:FlowIdentity,private gateway:PaymentGateway|null=null,private simulation:{merchantId:string;locations:Record<string,string>;nodeEnv:string;sandboxActivationId?:string}|null=null){if(gateway&&(process.env.NODE_ENV==='production'||!simulation||!['test','development'].includes(simulation.nodeEnv)))throw new FlowError('SIMULATION_FORBIDDEN',503);}
 protected async time(c:Connection){return (await c.query<{now:Date}>('SELECT inventory_clock() AS now')).rows[0]!.now;}
 protected async authorize(permission:FlowPermission,stores:string[]=[]):Promise<{subject:string;storeIds:string[]}>{
 if(isGuest(this.identity))return authorizeBookingActor(this.authPool,this.identity,['BOOKING_VIEW',permission],stores);
 const a=await this.authPool.connect();try{const session=(await a.query('SELECT 1 FROM auth_session WHERE id=$1 AND "userId"=$2 AND "expiresAt">clock_timestamp()',[this.identity.sessionId,this.identity.subject])).rowCount;const p=session?await loadStaff(a,this.identity.subject):null;if(!p)throw new FlowError('UNAUTHENTICATED',401);if(!p.permissions.includes('BOOKING_VIEW')||!p.permissions.includes(permission as Permission)||stores.some(s=>!p.storeIds.includes(s as never)))throw new FlowError('FORBIDDEN',403);return p;}finally{a.release();}}
 protected async transaction<T>(permission:FlowPermission,stores:string[],preflight:(c:Connection)=>Promise<void>,fn:(c:PoolClient,now:Date)=>Promise<T>):Promise<T>{
 await this.authorize(permission,stores);await preflight(this.pool);const c=await this.pool.connect();try{await c.query('BEGIN');await c.query("SET LOCAL lock_timeout='1500ms';SET LOCAL statement_timeout='5000ms';SET LOCAL idle_in_transaction_session_timeout='10000ms'");await c.query('SELECT pg_advisory_xact_lock(71820600)');await c.query('SELECT pg_advisory_xact_lock_shared(71820901,hashtext($1))',[this.identity.subject]);await this.authorize(permission,stores);await preflight(c);await c.query("SELECT set_config('zao.actor',$1,true),set_config('zao.reason','DEVELOPMENT_FLOW',true)",[this.identity.subject]);const r=await fn(c,await this.time(c));await c.query('COMMIT');return r;}catch(e){await c.query('ROLLBACK');if(e instanceof FlowError||e instanceof HoldError)throw e;const code=(e as {code?:string}).code;if(code==='42501')throw new FlowError('FORBIDDEN',403);if(['23505','23503','23514'].includes(code??''))throw new FlowError('FLOW_CONFLICT');if(['55P03','57014','40P01','40001'].includes(code??''))throw new FlowError('INDETERMINATE',503);throw new FlowError('FLOW_OPERATION_FAILED',500);}finally{c.release();}}
 protected async booking(c:Connection,id:string,ownerOnly=false){flowId(id);const b=(await c.query<BookingRow>('SELECT * FROM rental_bookings WHERE id=$1',[id])).rows[0];if(!b||(ownerOnly||isGuest(this.identity))&&b.owner_id!==this.identity.subject)throw new FlowError('FORBIDDEN',403);return b;}
 private requireSimulation(){if(process.env.NODE_ENV==='production'||!this.gateway||!['SIMULATED_DEV','SQUARE_SANDBOX'].includes(this.gateway.kind)||!this.simulation||!['test','development'].includes(this.simulation.nodeEnv)||this.gateway.kind==='SQUARE_SANDBOX'&&this.simulation.sandboxActivationId!=='P4-SANDBOX-OWNER-R1')throw new FlowError('PAYMENT_NOT_CONNECTED_CHARGE_DISABLED',503);}
 private async source(c:Connection,quoteId:string,now:Date){flowId(quoteId);const q=(await c.query<{id:string;actor:string;hold_id:string|null;hold_version:number;conditions:HoldConditions;snapshot:Record<string,unknown>;snapshot_sha256:string;expires_at:Date;coupon_id:string|null}>('SELECT * FROM price_quotes WHERE id=$1',[quoteId])).rows[0];if(!q||q.actor!==this.identity.subject||!q.hold_id)throw new FlowError('FORBIDDEN',403);await this.authorize('BOOKING_CREATE',[q.conditions.pickupStore,q.conditions.returnStore]);const h=(await c.query<HoldRow>('SELECT * FROM inventory_holds WHERE id=$1',[q.hold_id])).rows[0];if(!h||h.owner_id!==this.identity.subject||flowHash(q.conditions)!==flowHash(h.conditions)||flowHash(q.snapshot)!==q.snapshot_sha256||q.hold_version!==h.version)throw new FlowError('QUOTE_HOLD_MISMATCH');if(q.expires_at<=now||h.expires_at<=now||h.due_at<=now||h.state!=='ACTIVE'||h.allocation_stage!=='PROVISIONAL'||!['NONE','FAILURE'].includes(h.payment_state))throw new FlowError('HOLD_OR_QUOTE_NOT_USABLE');await this.verifyClaims(c,h,now);const readyAt=await this.time(c);if(q.expires_at<=readyAt||h.expires_at<=readyAt||h.due_at<=readyAt)throw new FlowError('HOLD_OR_QUOTE_NOT_USABLE');if(q.coupon_id)throw new FlowError('COUPON_REDEMPTION_NOT_CONNECTED');if(!Number.isSafeInteger(q.snapshot.totalJpy)||Number(q.snapshot.totalJpy)<1||q.snapshot.currency!=='JPY'||q.snapshot.chargeReady!==false)throw new FlowError('PRICE_POLICY_REQUIRES_REVIEW');return {q,h};}
 // V2 (provisional-capacity correction): an active provisional_capacity_claims row satisfies
 // expectedClaimKeys here exactly like a real inventory_claims/wear_claims row — a reservation
 // backed by Owner-approved provisional capacity is a genuine hold, not incomplete protection.
 // This is deliberately booking/payment-scoped only: physical handoff has its own, stricter
 // verifyPhysicalHandoff below, which this method never calls.
 protected async verifyClaims(c:Connection,h:HoldRow,now:Date){if(h.transfer_attention)throw new FlowError('TRANSFER_RECONCILIATION_REQUIRED');const claims=(await c.query<{requirement_key:string;day:string}>("SELECT requirement_key,day::text FROM inventory_claims WHERE hold_id=$1 AND active UNION SELECT requirement_key,day::text FROM wear_claims WHERE hold_id=$1 AND active UNION SELECT requirement_key,day::text FROM provisional_capacity_claims WHERE hold_id=$1 AND state='ACTIVE'",[h.id])).rows;if(claims.map(x=>x.requirement_key+'/'+x.day).sort().join()!==expectedClaimKeys(h.conditions).join())throw new FlowError('INVENTORY_PROTECTION_INCOMPLETE');if((await c.query(`SELECT 1 FROM inventory_claims cl JOIN transfer_pieces p ON p.id=cl.transfer_piece_id JOIN transfer_batches b ON b.id=p.batch_id WHERE cl.hold_id=$1 AND cl.active AND (b.issue IS NOT NULL OR p.state='CANCELLED' OR (b.planned_ready_at<$2 AND p.state NOT IN ('READY','CLOSED'))) LIMIT 1`,[h.id,now])).rowCount)throw new FlowError('TRANSFER_RECONCILIATION_REQUIRED');}
 /** Handoff-only gate (prepare()/checkout() in custody-service.ts, never booking creation or
  * payment confirmation): "Reservation allowed. Physical handoff not allowed." Any still-ACTIVE
  * provisional claim on this hold means at least one requirement has no real physical/wear
  * custody to actually hand over yet — fails closed rather than letting staff release equipment
  * that was never confirmed as real stock. */
 protected async verifyPhysicalHandoff(c:Connection,holdId:string){if((await c.query("SELECT 1 FROM provisional_capacity_claims WHERE hold_id=$1 AND state='ACTIVE' LIMIT 1",[holdId])).rowCount)throw new FlowError('PROVISIONAL_PHYSICAL_ASSIGNMENT_REQUIRED');}
 async create(key:string,quoteId:string,contact:unknown,locale:'ja'|'en'='ja'){if(!['ja','en'].includes(locale))throw new FlowError('INVALID_LOCALE',422);flowId(key);flowId(quoteId);const normalized=syntheticContact(contact);this.requireSimulation();const fingerprint=flowHash({quoteId,contact:normalized});return this.transaction('BOOKING_CREATE',[],async c=>{const q=(await c.query('SELECT actor,conditions FROM price_quotes WHERE id=$1',[quoteId])).rows[0];if(!q||q.actor!==this.identity.subject)throw new FlowError('FORBIDDEN',403);await this.authorize('BOOKING_CREATE',[q.conditions.pickupStore,q.conditions.returnStore]);},async(c,now)=>{const old=(await c.query<BookingRow>('SELECT * FROM rental_bookings WHERE owner_id=$1 AND request_key=$2',[this.identity.subject,key])).rows[0];if(old){if(old.mode!==this.gateway!.kind)throw new FlowError('PAYMENT_MODE_MISMATCH',409);if(old.fingerprint!==fingerprint||old.notification_locale!==locale)throw new FlowError('IDEMPOTENCY_MISMATCH');await this.authorize('BOOKING_CREATE',[old.conditions.pickupStore,old.conditions.returnStore]);return this.view(c,old);}
 const {q,h}=await this.source(c,quoteId,now);const id=q.conditions.reservationId;await c.query(`INSERT INTO rental_bookings(id,owner_id,request_key,fingerprint,hold_id,quote_id,conditions,price_snapshot,price_sha256,contact,mode,state,notification_locale) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,'DRAFT',$12)`,[id,this.identity.subject,key,fingerprint,h.id,q.id,JSON.stringify(q.conditions),JSON.stringify(q.snapshot),q.snapshot_sha256,JSON.stringify(normalized),this.gateway!.kind,locale]);return this.view(c,await this.booking(c,id));});}
 protected async view(c:Connection,b:BookingRow){if(flowHash(b.price_snapshot)!==b.price_sha256)throw new FlowError('SNAPSHOT_INTEGRITY_ERROR');const payments=(await c.query('SELECT id,state,provider_state,provider_id,completed_at FROM rental_payment_attempts WHERE booking_id=$1',[b.id])).rows;const history=(await c.query('SELECT actor,event,occurred_at FROM rental_history WHERE entity_id=$1 ORDER BY id',[b.id])).rows;return {id:b.id,state:b.state,version:b.version,conditions:b.conditions,priceSnapshot:b.price_snapshot,priceSha256:b.price_sha256,contact:b.owner_id===this.identity.subject?b.contact:{displayName:b.contact.displayName},qr:b.confirmed_at?reservationQr(b.id):null,payments,history,mode:b.mode,chargeReady:false,meaning:b.mode==='SQUARE_SANDBOX'?'SANDBOX_NOT_COMMERCIAL_BOOKING':'DEVELOPMENT_SIMULATION_NOT_REAL_BOOKING_OR_PAYMENT'};}
 async get(id:string){const p=await this.authorize('BOOKING_VIEW');const c=await this.pool.connect();try{await c.query('BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY');const b=await this.booking(c,id);if(b.owner_id===p.subject){if(!p.storeIds.includes(b.conditions.pickupStore)||!p.storeIds.includes(b.conditions.returnStore))throw new FlowError('FORBIDDEN',403);}else if(!p.storeIds.includes(b.conditions.pickupStore)&&!p.storeIds.includes(b.conditions.returnStore))throw new FlowError('FORBIDDEN',403);const r=await this.view(c,b);await c.query('COMMIT');return r;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 async list(){const p=await this.authorize('BOOKING_VIEW');return (await this.pool.query(`SELECT id,state,version,conditions->'period' AS period,conditions->>'pickupStore' AS pickup_store,conditions->>'returnStore' AS return_store,contact->>'displayName' AS display_name,price_snapshot->>'totalJpy' AS total_jpy,mode FROM rental_bookings WHERE (conditions->>'pickupStore'=ANY($1::text[]) OR conditions->>'returnStore'=ANY($1::text[])) AND ($2::text IS NULL OR owner_id=$2) ORDER BY created_at DESC,id LIMIT 100`,[p.storeIds,isGuest(this.identity)?this.identity.subject:null])).rows;}
 private request(a:AttemptRow):PaymentRequest{return {attemptId:a.id,bookingId:a.booking_id,idempotencyKey:a.idempotency_key,merchantId:a.merchant_id,locationId:a.location_id,amountJpy:Number(a.amount_jpy),currency:a.currency};}
 async startPayment(id:string,key:string){flowId(id);flowId(key);this.requireSimulation();let call:AttemptRow|null=null;await this.transaction('BOOKING_CREATE',[],async c=>{const b=await this.booking(c,id,true);await this.authorize('BOOKING_CREATE',[b.conditions.pickupStore,b.conditions.returnStore]);},async(c,now)=>{const b=await this.booking(c,id,true);if(b.mode!==this.gateway!.kind)throw new FlowError('PAYMENT_MODE_MISMATCH',409);const old=(await c.query<AttemptRow>('SELECT * FROM rental_payment_attempts WHERE booking_id=$1',[id])).rows[0];if(old)return;if(b.state!=='DRAFT')throw new FlowError('PAYMENT_RECONCILIATION_REQUIRED');const {h}=await this.source(c,b.quote_id,now);const attemptId=randomUUID();await c.query(`INSERT INTO rental_payment_attempts(id,booking_id,actor,idempotency_key,merchant_id,location_id,amount_jpy,currency,state) VALUES($1,$2,$3,$4,$5,$6,$7,'JPY','SUBMITTING')`,[attemptId,id,this.identity.subject,key,this.simulation!.merchantId,this.simulation!.locations[b.conditions.pickupStore],b.price_snapshot.totalJpy]);await c.query("UPDATE rental_bookings SET state='PAYMENT_PENDING',version=version+1 WHERE id=$1",[id]);await c.query("UPDATE inventory_holds SET payment_state='PENDING',version=version+1 WHERE id=$1",[h.id]);call=(await c.query<AttemptRow>('SELECT * FROM rental_payment_attempts WHERE id=$1',[attemptId])).rows[0]!;});
 if(call){const a=call as AttemptRow;let observed:PaymentObservation;try{observed=await this.gateway!.create(this.request(a));}catch(e){await this.markUnknown(id,a.id);if(e instanceof FlowError&&['SQUARE_AUTH_STOP','SQUARE_QUOTA_STOP','SQUARE_BUDGET_EXHAUSTED','SQUARE_ACTIVATION_MISMATCH','SQUARE_ACTIVATION_UNCONFIGURED','SQUARE_ACTIVATION_REPLAY_MISMATCH'].includes(e.code))throw e;return this.get(id);}await this.recordObservation(id,a.id,'create/'+a.id,observed);}return this.get(id);}
 private async markUnknown(id:string,attemptId:string){await this.transaction('BOOKING_CREATE',[],async c=>{const b=await this.booking(c,id,true);await this.authorize('BOOKING_CREATE',[b.conditions.pickupStore,b.conditions.returnStore]);},async(c,now)=>{await c.query("UPDATE rental_payment_attempts SET state='UNKNOWN',updated_at=$2 WHERE id=$1 AND state='SUBMITTING'",[attemptId,now]);await c.query("UPDATE inventory_holds SET payment_state='UNKNOWN',version=version+1 WHERE id=(SELECT hold_id FROM rental_bookings WHERE id=$1) AND payment_state='PENDING'",[id]);});}
 async reconcile(id:string){flowId(id);this.requireSimulation();const b=await this.booking(this.pool,id,true);if(b.mode!==this.gateway!.kind)throw new FlowError('PAYMENT_MODE_MISMATCH',409);await this.authorize('BOOKING_CREATE',[b.conditions.pickupStore,b.conditions.returnStore]);const a=(await this.pool.query<AttemptRow>('SELECT * FROM rental_payment_attempts WHERE booking_id=$1',[id])).rows[0];if(!a)throw new FlowError('NO_PAYMENT_ATTEMPT');let o:PaymentObservation|null;try{o=await this.gateway!.lookup(this.request(a),a.provider_id);}catch{throw new FlowError('PAYMENT_LOOKUP_UNAVAILABLE',503);}if(o)await this.recordObservation(id,a.id,'lookup/'+flowHash(o),o);return this.get(id);}
 // Offline/synthetic replay boundary, not an externally published webhook endpoint.
 // A verified notification triggers lookup; its embedded amount/status never confirms a booking.
 async reconcileVerifiedWebhook(id:string,raw:Uint8Array,signature:string|undefined,notificationUrl:string,verificationKey:string){
 this.requireSimulation();const e=parseVerifiedSquareWebhook(raw,signature,notificationUrl,verificationKey);const b=await this.booking(this.pool,id,true);if(b.mode!==this.gateway!.kind)throw new FlowError('PAYMENT_MODE_MISMATCH',409);await this.authorize('BOOKING_CREATE',[b.conditions.pickupStore,b.conditions.returnStore]);const a=(await this.pool.query<AttemptRow>('SELECT * FROM rental_payment_attempts WHERE booking_id=$1',[id])).rows[0];if(!a||a.merchant_id!==e.merchantId||a.provider_id!==null&&a.provider_id!==e.paymentId)throw new FlowError('WEBHOOK_TARGET_MISMATCH');let o:PaymentObservation|null;try{o=await this.gateway!.lookup(this.request(a),e.paymentId);}catch{throw new FlowError('PAYMENT_LOOKUP_UNAVAILABLE',503);}if(!o)throw new FlowError('PAYMENT_LOOKUP_INCOMPLETE',503);if(o.providerId!==e.paymentId)throw new FlowError('WEBHOOK_TARGET_MISMATCH');await this.recordObservation(id,a.id,'webhook/'+e.eventId,o,flowHash(Array.from(raw)));return this.get(id);
 }
 // Only the trusted server adapter / verified webhook reconciliation calls this method.
 // HTTP never accepts a PaymentObservation or a paid/status flag from a browser.
 async recordObservation(id:string,attemptId:string,eventId:string,o:PaymentObservation,evidenceDigest=flowHash(o)){await this.transaction('BOOKING_CREATE',[],async c=>{const b=await this.booking(c,id,true);await this.authorize('BOOKING_CREATE',[b.conditions.pickupStore,b.conditions.returnStore]);},async(c,now)=>{
 const b=await this.booking(c,id,true),a=(await c.query<AttemptRow>('SELECT * FROM rental_payment_attempts WHERE id=$1 AND booking_id=$2',[attemptId,id])).rows[0];if(!a)throw new FlowError('NO_PAYMENT_ATTEMPT');const digest=evidenceDigest,prior=(await c.query('SELECT * FROM rental_provider_events WHERE event_id=$1',[eventId])).rows[0];if(prior){if(prior.attempt_id!==attemptId||prior.payload_sha256!==digest)throw new FlowError('EVENT_ID_CONFLICT');return;}
 let outcome='OBSERVED';try{matchPayment(this.request(a),o);if(a.provider_id&&a.provider_id!==o.providerId||Date.parse(o.updatedAt)>now.getTime()||o.completedAt&&Date.parse(o.completedAt)>now.getTime())throw new FlowError('PAYMENT_EVIDENCE_MISMATCH');}catch{outcome='MISMATCH';await c.query("UPDATE rental_payment_attempts SET state='REVIEW',updated_at=$2 WHERE id=$1 AND state<>'COMPLETED'",[a.id,now]);if(!b.confirmed_at)await c.query("UPDATE rental_bookings SET state='PAYMENT_REVIEW',version=version+1 WHERE id=$1",[id]);}
 if(outcome!=='MISMATCH'){
  if(a.state==='COMPLETED'||['FAILED','CANCELED'].includes(a.provider_state??'')&&o.status!=='COMPLETED'||a.provider_updated_at&&a.provider_updated_at>new Date(o.updatedAt)){outcome='STALE_OR_TERMINAL_IGNORED';}
  else if(['FAILED','CANCELED'].includes(a.provider_state??'')){outcome='CONTRADICTORY_TERMINAL_PAYMENT';await c.query("UPDATE rental_payment_attempts SET state='REVIEW',updated_at=$2 WHERE id=$1",[a.id,now]);await c.query("UPDATE rental_bookings SET state='PAYMENT_REVIEW',version=version+1 WHERE id=$1",[id]);await c.query("UPDATE inventory_holds SET payment_state='UNKNOWN',version=version+1 WHERE id=$1 AND state='ACTIVE'",[b.hold_id]);}
  else{const h=(await c.query<HoldRow>('SELECT * FROM inventory_holds WHERE id=$1',[b.hold_id])).rows[0]!;let state=o.status==='COMPLETED'?'COMPLETED':o.status==='PENDING'?'PENDING':'FAILED';
   if(o.status==='COMPLETED'){
    let ok=h.state==='ACTIVE'&&h.expires_at>now&&h.due_at>now&&h.allocation_stage==='PROVISIONAL'&&flowHash(h.conditions)===flowHash(b.conditions);
    try{await this.verifyClaims(c,h,now);}catch{ok=false;}
    now=await this.time(c);if(h.expires_at<=now||h.due_at<=now)ok=false;
    if(Number(b.price_snapshot.advanceDiscountJpy)>0&&advanceQualification(b.conditions.period.startDate,o.completedAt?new Date(o.completedAt):null)!=='QUALIFIED')ok=false;
    if(!ok){state='REVIEW';outcome='PAYMENT_SUCCESS_REQUIRES_INVENTORY_OR_PRICE_REVIEW';await c.query("UPDATE rental_bookings SET state='PAYMENT_REVIEW',version=version+1 WHERE id=$1",[id]);}
    else{await c.query("UPDATE rental_bookings SET state='CONFIRMED_DEV',confirmed_at=$2,version=version+1 WHERE id=$1",[id,now]);await c.query("UPDATE inventory_holds SET payment_state='SUCCESS',confirmed_at=$2,version=version+1 WHERE id=$1",[h.id,now]);await c.query("INSERT INTO rental_notifications(id,booking_id,destination,state) VALUES($1,$2,$3,'CAPTURED_TEST_ONLY')",[randomUUID(),id,b.contact.email]);outcome='CONFIRMED_DEV';}
   }
   await c.query('UPDATE rental_payment_attempts SET state=$2,provider_id=$3,provider_state=$4,provider_updated_at=$5,completed_at=$6,updated_at=$7 WHERE id=$1',[a.id,state,o.providerId,o.status,o.updatedAt,o.completedAt,now]);
   if(state==='FAILED')await c.query("UPDATE rental_bookings SET state='PAYMENT_REVIEW',version=version+1 WHERE id=$1",[id]);
   if(o.status!=='COMPLETED')await c.query('UPDATE inventory_holds SET payment_state=$2,version=version+1 WHERE id=$1',[h.id,state==='FAILED'?'FAILURE':'PENDING']);
  }
 }
 await c.query('INSERT INTO rental_provider_events(event_id,attempt_id,payload_sha256,outcome) VALUES($1,$2,$3,$4)',[eventId,a.id,digest,outcome]);});
 // Notification failure cannot roll back a committed booking. The immutable
 // confirmation capture is reconciled into the outbox by the worker after an outage.
 try{await this.pool.query('SELECT notification_enqueue_confirmed($1)',[id]);}catch{/* No raw recipient/provider/DB diagnostics. */}
 }
}
