import {createHash,randomUUID} from 'node:crypto';
import QRCode from 'qrcode';
import {GuestContexts,type GuestDraft} from './context';
import type {GuestActor} from '../../../auth/src/booking-actor';
import {canonical,HoldError,type Period} from '../../../contracts/src/hold';
import {exact} from '../../../contracts/src/pricing';
import {parseRecommendation,type Profile,type Direction,type Variant} from '../../../contracts/src/recommendation';
import {syntheticContact} from '../../../contracts/src/rental-flow';
import type {RecommendationService} from '../recommendation/recommendation-service';
import type {BookingService} from '../payment/booking-service';
export type GuestCatalog={revision:string;models:{key:string;name:string;modelId:string;season:string;sport:'SKI'|'SNOWBOARD';lengths:string[];variantIds:string[]}[];sizes:{key:string;label:string;variant:Variant}[]};
type GuestInput={pickupStore:'MOUNTAIN_BASE'|'ONSEN_BASE';returnStore:'MOUNTAIN_BASE'|'ONSEN_BASE';period:Period;members:unknown[]};
type SavedSelection={directions:Record<string,Direction>;wantAdvance:boolean;couponCode:string|null;acceptedModelPolicy:true;estimate?:Record<string,unknown>;contact?:ReturnType<typeof syntheticContact>;notificationLocale?:'ja'|'en'};
const hash=(v:unknown)=>createHash('sha256').update(canonical(v)).digest('hex');
const comparable=(v:Record<string,unknown>)=>Object.fromEntries(Object.entries(v).filter(([k])=>!['advisory','conditions','expiresAt','fingerprint','couponVersionId','productionGates','zeroTotalPath'].includes(k)));
const same=(a:unknown,b:unknown)=>canonical(a)===canonical(b);
export class GuestBookingService{
 constructor(private contexts:GuestContexts,private actor:GuestActor,private recommendations:RecommendationService,private bookings:BookingService|null,private catalog:()=>Promise<GuestCatalog>){}
 private expected(d:GuestDraft,id:unknown,revision:unknown){if(d.id!==id)throw new HoldError('FORBIDDEN',403);if(d.revision!==revision)throw new HoldError('STALE_DRAFT',409);}
 private async input(value:unknown){const x=exact(value,['pickupStore','returnStore','period','members']) as GuestInput;if(!Array.isArray(x.members)||!x.members.length||x.members.length>20)throw new HoldError('INVALID_GROUP');const cat=await this.catalog();
 const members=x.members.map(v=>{const m=exact(v,['key','sport','heightCm','footCm','adultAtStart','tier','ski','poleSize','premiumModel','jacketSize','pantsSize','wearSport']);const bySize=(key:unknown,family:string)=>{const size=cat.sizes.find(s=>s.key===key&&s.variant.family===family);if(!size)throw new HoldError('CATALOG_SELECTION_INVALID');return size.variant.id;};
 const premium=m.premiumModel===null?null:cat.models.find(p=>p.key===m.premiumModel&&p.sport===m.sport);if(m.premiumModel!==null&&!premium)throw new HoldError('MODEL_NOT_RELEASED');
 const wear=m.jacketSize!==null||m.pantsSize!==null?{jacketVariantId:bySize(m.jacketSize,'WEAR_JACKET'),pantsVariantId:bySize(m.pantsSize,'WEAR_PANTS')}:undefined;
 return {key:m.key,sport:m.sport,heightCm:m.heightCm,footCm:m.footCm,adultAtStart:m.adultAtStart,tier:m.tier,ski:m.ski,poleVariantId:m.poleSize===null?null:bySize(m.poleSize,'POLE'),...(premium?{modelSelection:{modelId:premium.modelId,season:premium.season}}:{}),...(wear?{wearSelection:wear}:{}),...(m.wearSport!==null?{wearSport:m.wearSport}:{})} as Profile;});
 return parseRecommendation({contractVersion:'INTEGRATED_V1_2',pickupStore:x.pickupStore,returnStore:x.returnStore,period:x.period,members});}
 async options(){const c=await this.catalog();return {revision:c.revision,models:c.models.map(({key,name,season,sport,lengths})=>({key,name,season,sport,lengths})),sizes:c.sizes.map(({key,label,variant:v})=>({key,label,family:v.family,age:v.age,tier:v.tier,compatibleSports:v.compatible_sports??[]}))};}
 private async releasedSelection(d:GuestDraft){const cat=await this.catalog(),p=await this.recommendations.get(d.preview_id!),s=d.selection as SavedSelection;
 for(const m of p.preview.input.members){if(!m.modelSelection)continue;const model=cat.models.find(v=>v.modelId===m.modelSelection!.modelId&&v.season===m.modelSelection!.season&&v.sport===m.sport);const choice=p.preview.offered.find(o=>o.key===m.key)?.candidates[s.directions[m.key]!];const board=choice?.member.items.find(i=>i.family===m.sport);if(!model||!board||board.variantIds.some(id=>!model.variantIds.includes(id)))throw new HoldError('MODEL_RELEASE_CHANGED',409);}}
 private async view(d:GuestDraft){if(d.booking_id&&!this.bookings)throw new HoldError('PAYMENT_READ_UNCONNECTED',503);const v=d.preview_id?await this.recommendations.get(d.preview_id):null;const result=d.booking_id?await this.bookings!.get(d.booking_id):null;
 return {id:d.id,revision:d.revision,input:d.input,selection:d.selection as SavedSelection|null,locked:Boolean((d.selection as SavedSelection|null)?.contact),priceReviewRequired:Boolean(v?.quote&&!d.booking_id&&!same((d.selection as SavedSelection|null)?.estimate,comparable(v.quote.snapshot))),
  estimate:(d.selection as SavedSelection|null)?.estimate??null,reviewHash:(d.selection as SavedSelection|null)?.estimate?hash((d.selection as SavedSelection).estimate):null,
  preview:v?{members:v.preview.offered.map(o=>({key:o.key,reason:o.reason,price:o.price,priceError:o.priceError,candidates:Object.fromEntries(Object.entries(o.candidates).map(([direction,c])=>[direction,c?{lengthCm:c.lengthCm}:null]))}))}:null,
  hold:v?.hold?{state:v.hold.state,expiresAt:v.hold.expiresAt,version:v.hold.version}:null,quote:v?.quote?{snapshot:v.quote.snapshot,validity:v.quote.validity,snapshotSha256:v.quote.snapshotSha256,chargeReady:false}:null,
  booking:result?{id:result.id,state:result.state,qr:result.qr,qrImage:result.qr?await QRCode.toDataURL(result.qr,{width:240,margin:2}):null,priceSnapshot:result.priceSnapshot,priceSha256:result.priceSha256,payments:result.payments.map(p=>({state:p.state})),chargeReady:result.chargeReady,mode:result.mode}:null};}
 async get(){return this.view(await this.contexts.read(this.actor));}
 async save(value:unknown){const v=exact(value,['draftId','expectedRevision','input']);await this.input(v.input);await this.contexts.change(this.actor,async(c,d)=>{this.expected(d,v.draftId,v.expectedRevision);if(d.booking_id||(d.selection as SavedSelection|null)?.contact)throw new HoldError('DRAFT_ALREADY_SELECTED',409);await c.query('UPDATE guest_drafts SET input=$2,preview_key=$3,preview_id=NULL,selection=NULL,selection_key=NULL,revision=revision+1,updated_at=clock_timestamp() WHERE id=$1',[d.id,JSON.stringify(v.input),randomUUID()]);});return this.get();}
 async preview(value:unknown){const v=exact(value,['draftId','expectedRevision']),d=await this.contexts.read(this.actor);this.expected(d,v.draftId,v.expectedRevision);if(!d.input||!d.preview_key)throw new HoldError('INPUT_REQUIRED');if(d.preview_id)return this.get();const input=await this.input(d.input),p=await this.recommendations.preview(d.preview_key,input,null);
 await this.contexts.change(this.actor,async(c,current)=>{this.expected(current,v.draftId,v.expectedRevision);if(current.preview_key!==d.preview_key)throw new HoldError('STALE_DRAFT',409);await c.query('UPDATE guest_drafts SET preview_id=$2 WHERE id=$1',[d.id,p.preview.id]);});return this.get();}
 async choose(value:unknown){const v=exact(value,['draftId','expectedRevision','directions','wantAdvance','couponCode','acceptedModelPolicy']);const d=await this.contexts.read(this.actor);this.expected(d,v.draftId,v.expectedRevision);if(!d.preview_id||v.acceptedModelPolicy!==true||typeof v.wantAdvance!=='boolean'||v.couponCode!==null)throw new HoldError('SELECTION_INVALID');const p=await this.recommendations.get(d.preview_id);
 const directions=v.directions as Record<string,Direction>;if(!directions||Array.isArray(directions)||typeof directions!=='object'||Object.keys(directions).sort().join()!==p.preview.input.members.map(m=>m.key).sort().join()||Object.entries(directions).some(([key,direction])=>!['RECOMMENDED','SHORTER','LONGER'].includes(direction)||!p.preview.offered.find(m=>m.key===key)?.candidates[direction]))throw new HoldError('SELECTION_INVALID');
 const selected={directions,wantAdvance:v.wantAdvance,couponCode:null,acceptedModelPolicy:true as const};const estimate=comparable(await this.recommendations.advisory(d.preview_id,selected));const s:SavedSelection={...selected,estimate};await this.contexts.change(this.actor,async(c,current)=>{this.expected(current,v.draftId,v.expectedRevision);if(current.selection_key){if(!same(current.selection,s))throw new HoldError('DRAFT_ALREADY_SELECTED',409);return;}await c.query('UPDATE guest_drafts SET selection=$2,selection_key=$3 WHERE id=$1',[d.id,JSON.stringify(s),randomUUID()]);});return this.get();}
 commercialEnabled(){return this.bookings?.commercialEnabled()??false;}
 async checkout(value:unknown){if(!this.bookings)throw new HoldError('PAYMENT_NOT_CONNECTED_CHARGE_DISABLED',503);const v=exact(value,['draftId','expectedRevision','contact','reviewHash',...(value&&typeof value==='object'&&'locale' in value?['locale']:[])]);const locale=v.locale===undefined?'ja':v.locale;if(locale!=='ja'&&locale!=='en')throw new HoldError('INVALID_LOCALE',422);const contact=this.bookings.normalizeContact(v.contact);
 const d=await this.contexts.change(this.actor,async(c,d)=>{this.expected(d,v.draftId,v.expectedRevision);if(!d.preview_id||!d.selection_key||!d.selection)throw new HoldError('SELECTION_REQUIRED');const s=d.selection as SavedSelection;if(!s.estimate||v.reviewHash!==hash(s.estimate))throw new HoldError('PRICE_REVIEW_REQUIRED',409);if(s.contact&&(!same(s.contact,contact)||(s.notificationLocale??'ja')!==locale))throw new HoldError('IDEMPOTENCY_MISMATCH',409);await c.query('UPDATE guest_drafts SET selection=$2 WHERE id=$1',[d.id,JSON.stringify({...s,contact,notificationLocale:locale as 'ja'|'en'})]);return {...d,selection:{...s,contact,notificationLocale:locale as 'ja'|'en'}};});
 // Catalog approval is rechecked before the first stock commitment, not trusted from a browser.
 if(!d.booking_id){await this.input(d.input);await this.releasedSelection(d);const {contact:_,estimate,notificationLocale,...selection}=d.selection;void _;const picked=await this.recommendations.select(d.preview_id!,d.selection_key!,selection);if(!picked.quote)throw new HoldError('HOLD_OR_QUOTE_RECONCILIATION_REQUIRED',409);if(!same(estimate,comparable(picked.quote.snapshot)))throw new HoldError('PRICE_CHANGED_REVIEW_REQUIRED',409);const b=await this.bookings.create(d.booking_key,picked.quote.id,{displayName:contact.displayName,email:contact.email,termsAccepted:true},notificationLocale);
  await this.contexts.change(this.actor,async(c,current)=>{this.expected(current,v.draftId,v.expectedRevision);await c.query('UPDATE guest_drafts SET booking_id=$2 WHERE id=$1',[d.id,b.id]);});}
 const saved=await this.contexts.read(this.actor);await this.bookings.startPayment(saved.booking_id!,saved.booking_key);return this.get();}
 async acceptPrice(value:unknown){const v=exact(value,['draftId','expectedRevision','snapshotSha256']),d=await this.contexts.read(this.actor);this.expected(d,v.draftId,v.expectedRevision);if(d.booking_id||!d.selection||!d.preview_id)throw new HoldError('PRICE_REVIEW_UNAVAILABLE',409);const p=await this.recommendations.get(d.preview_id);if(!p.quote||p.quote.validity!=='VALID_PRIVATE_ESTIMATE'||p.quote.snapshotSha256!==v.snapshotSha256)throw new HoldError('STALE_PRICE_REVIEW',409);
 await this.contexts.change(this.actor,async(c,current)=>{this.expected(current,v.draftId,v.expectedRevision);if(current.booking_id)throw new HoldError('PRICE_REVIEW_UNAVAILABLE',409);await c.query('UPDATE guest_drafts SET selection=$2 WHERE id=$1',[d.id,JSON.stringify({...current.selection as SavedSelection,estimate:comparable(p.quote!.snapshot)})]);});return this.get();}
 async reconcile(){if(!this.bookings)throw new HoldError('PAYMENT_NOT_CONNECTED_CHARGE_DISABLED',503);const d=await this.contexts.read(this.actor);if(!d.booking_id)throw new HoldError('NO_PAYMENT_ATTEMPT',409);await this.bookings.reconcile(d.booking_id);return this.get();}
}
