import {randomUUID,createHash} from 'node:crypto';
import type {Pool,PoolClient} from 'pg';
import {loadStaff} from '../../../auth/src/staff-auth';
import {HoldError,canonical,isWear,normalizePeriod,type HoldConditions} from '../../../contracts/src/hold';
import {exact,id} from '../../../contracts/src/pricing';
type Conn=Pick<PoolClient,'query'>;
type PoolRow={id:string;variant_id:string;store_id:string;ready:number;on_loan:number;returned_pending:number;cleaning:number;today_blocked:number;in_transit:number;unavailable:number;total:number;revision:number};
type Loan={id:string;cycle_id:string;booking_id:string;member_key:string;requirement_key:string;pool_id:string;variant_id:string;quantity:number;returned:number;planned_pickup_store:string;actual_pickup_store:string;planned_return_store:string;checked_out_at:Date;revision:number};
type Receipt={id:string;loan_id:string;pool_id:string;quantity:number;actual_store:string;received_at:Date;confirmed_at:Date;ready_at:Date|null;eligible_on:string;state:string;revision:number};
export class WearError extends HoldError{}
const sha=(x:unknown)=>createHash('sha256').update(canonical(x)).digest('hex');
const day=(d:Date)=>new Date(d.getTime()+9*3600000).toISOString().slice(0,10);
const nextDay=(d:Date)=>new Date(Date.parse(day(d)+'T00:00:00Z')+86400000).toISOString().slice(0,10);
function quantity(n:unknown){if(!Number.isInteger(n)||Number(n)<1||Number(n)>1000)throw new WearError('INVALID_QUANTITY');return Number(n);}
function revision(n:unknown){if(!Number.isInteger(n)||Number(n)<1)throw new WearError('INVALID_REVISION');return Number(n);}
function store(s:unknown){if(s!=='MOUNTAIN_BASE'&&s!=='ONSEN_BASE')throw new WearError('INVALID_STORE');return s;}
function reason(s:unknown){if(typeof s!=='string'||!s.trim()||s.length>160)throw new WearError('REASON_REQUIRED');return s;}
export class WearService{
 constructor(private pool:Pool,private auth:Pool,private identity:{subject:string;sessionId:string}){}
 private async authorize(permission:string,stores:string[]=[]){const c=await this.auth.connect();try{await c.query('BEGIN READ ONLY');const live=(await c.query('SELECT 1 FROM auth_session WHERE id=$1 AND "userId"=$2 AND "expiresAt">clock_timestamp()',[this.identity.sessionId,this.identity.subject])).rowCount;const p=live?await loadStaff(c,this.identity.subject):null;if(!p||!p.permissions.includes(permission as never)||stores.some(s=>!p.storeIds.includes(s as never)))throw new WearError('FORBIDDEN',403);await c.query('COMMIT');return p;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 private async tx<T>(permission:string,stores:string[],key:string,payload:unknown,note:string,fn:(c:PoolClient,now:Date)=>Promise<T>):Promise<T>{id(key);await this.authorize(permission,stores);const c=await this.pool.connect();try{await c.query('BEGIN');await c.query("SET LOCAL lock_timeout='1500ms';SET LOCAL statement_timeout='5000ms'");await c.query('SELECT pg_advisory_xact_lock(71820600)');await c.query('SELECT pg_advisory_xact_lock_shared(71820901,hashtext($1))',[this.identity.subject]);await this.authorize(permission,stores);const prior=(await c.query('SELECT fingerprint,result FROM wear_requests WHERE actor=$1 AND request_id=$2',[this.identity.subject,key])).rows[0],fingerprint=sha({permission,stores,payload});if(prior){if(prior.fingerprint!==fingerprint)throw new WearError('IDEMPOTENCY_MISMATCH',409);await c.query('COMMIT');return prior.result as T;}await c.query("SELECT set_config('zao.actor',$1,true),set_config('zao.reason',$2,true)",[this.identity.subject,note]);const now=(await c.query<{now:Date}>('SELECT inventory_clock() now')).rows[0]!.now;const result=await fn(c,now);await c.query('INSERT INTO wear_requests VALUES($1,$2,$3,$4)',[this.identity.subject,key,fingerprint,JSON.stringify(result)]);await c.query('COMMIT');return result;}catch(e){await c.query('ROLLBACK');if(e instanceof HoldError)throw e;const code=(e as {code?:string}).code;if(['23514','23505','23503'].includes(code??''))throw new WearError('WEAR_CONFLICT',409);if(['55P03','57014','40001','40P01'].includes(code??''))throw new WearError('INDETERMINATE',503);throw new WearError('WEAR_OPERATION_FAILED',500);}finally{c.release();}}
 private async getPool(c:Conn,poolId:string){id(poolId);const p=(await c.query<PoolRow>('SELECT * FROM wear_pools WHERE id=$1',[poolId])).rows[0];if(!p)throw new WearError('POOL_NOT_FOUND',404);return p;}
 private async ensurePool(c:Conn,variantId:string,storeId:string){const prior=(await c.query<PoolRow>('SELECT * FROM wear_pools WHERE variant_id=$1 AND store_id=$2',[variantId,storeId])).rows[0];if(prior)return prior;const poolId=randomUUID();await c.query('INSERT INTO wear_pools(id,variant_id,store_id) VALUES($1,$2,$3)',[poolId,variantId,storeId]);return this.getPool(c,poolId);}
 async overview(storeId:string){store(storeId);await this.authorize('INVENTORY_VIEW',[storeId]);const pools=(await this.pool.query(`SELECT p.*,v.family,v.age,v.size,v.compatible_sports,
 coalesce((SELECT max(n)::int FROM (SELECT sum(cl.quantity) n FROM wear_claims cl JOIN inventory_holds h ON h.id=cl.hold_id WHERE cl.pool_id=p.id AND cl.active AND h.state='ACTIVE' AND (h.expires_at>inventory_clock() OR h.payment_state IN ('PENDING','UNKNOWN','SUCCESS') OR h.allocation_stage<>'PROVISIONAL') AND NOT EXISTS(SELECT 1 FROM wear_loans l WHERE l.booking_id=h.reservation_id) GROUP BY cl.day) q),0) AS reserved_peak,
 coalesce((SELECT sum(quantity)::int FROM wear_transfers WHERE source_pool_id=p.id AND state='PLANNED'),0) AS transfer_reserved
 FROM wear_pools p JOIN ledger_variants v ON v.id=p.variant_id WHERE p.store_id=$1 ORDER BY v.family,v.age,v.size,p.id`,[storeId])).rows;return {pools,quantityMeaning:'PHYSICAL_BUCKETS_EXCLUDE_LOGICAL_HOLD',productionReady:false};}
 async register(key:string,value:unknown){const v=exact(value,['variantId','store','quantity','reason']);id(v.variantId);const s=store(v.store),q=quantity(v.quantity);return this.tx('INVENTORY_EDIT',[s],key,v,reason(v.reason),async c=>{const p=await this.ensurePool(c,v.variantId as string,s);if(p.total)throw new WearError('POOL_ALREADY_REGISTERED',409);await c.query('UPDATE wear_pools SET ready=$2 WHERE id=$1',[p.id,q]);return this.getPool(c,p.id);});}
 async adjust(key:string,value:unknown){const v=exact(value,['poolId','expectedRevision','ready','reason']);id(v.poolId);revision(v.expectedRevision);if(!Number.isInteger(v.ready)||Number(v.ready)<0||Number(v.ready)>1000)throw new WearError('INVALID_QUANTITY');await this.authorize('INVENTORY_EDIT');const p=await this.getPool(this.pool,v.poolId);return this.tx('INVENTORY_EDIT',[p.store_id],key,v,reason(v.reason),async c=>{const row=await this.getPool(c,p.id);if(row.revision!==v.expectedRevision)throw new WearError('STALE_REVISION',409);await c.query('UPDATE wear_pools SET ready=$2 WHERE id=$1',[p.id,v.ready]);return this.getPool(c,p.id);});}
 async loans(bookingId:string,receivingStore:string){id(bookingId);store(receivingStore);await this.authorize('BOOKING_VIEW');await this.authorize('RENTAL_RETURN',[receivingStore]);return (await this.pool.query<Loan>('SELECT * FROM wear_loans WHERE booking_id=$1 ORDER BY member_key,requirement_key',[bookingId])).rows;}
 async checkout(key:string,value:unknown){const v=exact(value,['bookingId','expectedBookingVersion','store','reason']);id(v.bookingId);revision(v.expectedBookingVersion);const s=store(v.store);return this.tx('RENTAL_CHECKOUT',[s],key,v,reason(v.reason),async(c,now)=>{
  const b=(await c.query<{id:string;state:string;version:number;conditions:HoldConditions;hold_id:string}>('SELECT id,state,version,conditions,hold_id FROM rental_bookings WHERE id=$1',[v.bookingId])).rows[0];if(!b||b.state!=='CONFIRMED_DEV')throw new WearError('CONFIRMED_DEVELOPMENT_BOOKING_REQUIRED',409);if(b.version!==v.expectedBookingVersion)throw new WearError('STALE_REVISION',409);if(b.conditions.pickupStore!==s)throw new WearError('FORBIDDEN',403);const period=normalizePeriod(b.conditions.period);if(day(now)!==b.conditions.period.startDate||now>=new Date(period.dueAt))throw new WearError('CHECKOUT_PERIOD_INVALID');
  if((await c.query('SELECT 1 FROM wear_loans WHERE booking_id=$1',[b.id])).rowCount)throw new WearError('ALREADY_CHECKED_OUT',409);
  const wanted=b.conditions.members.flatMap(m=>m.items.filter(i=>isWear(i.family)).map(i=>({key:m.key+':'+i.family,member:m.key,variant:i.variantIds[0]!})));if(!wanted.length)throw new WearError('NO_WEAR_LINES');
  const claims=(await c.query('SELECT requirement_key,pool_id,count(*)::int days FROM wear_claims WHERE hold_id=$1 AND active GROUP BY requirement_key,pool_id',[b.hold_id])).rows;if(claims.length!==wanted.length||wanted.some(w=>!claims.some(cl=>cl.requirement_key===w.key&&cl.days===period.days)))throw new WearError('WEAR_CLAIMS_MISMATCH');
  const cycle=randomUUID(),created:Loan[]=[];
  // All loan lines precede physical movement within the same transaction, so protected
  // claims become ON_LOAN without counting the same booking twice.
  for(const w of wanted){const p=await this.getPool(c,claims.find(cl=>cl.requirement_key===w.key)!.pool_id);if(p.store_id!==s||p.variant_id!==w.variant||p.ready<1)throw new WearError('WEAR_NOT_READY',409);const loanId=randomUUID();await c.query('INSERT INTO wear_loans(id,cycle_id,booking_id,member_key,requirement_key,pool_id,variant_id,quantity,planned_pickup_store,actual_pickup_store,planned_return_store,checked_out_at,actor) VALUES($1,$2,$3,$4,$5,$6,$7,1,$8,$8,$9,$10,$11)',[loanId,cycle,b.id,w.member,w.key,p.id,w.variant,s,b.conditions.returnStore,now,this.identity.subject]);created.push((await c.query<Loan>('SELECT * FROM wear_loans WHERE id=$1',[loanId])).rows[0]!);}
  for(const [poolId,n] of new Map(created.map(l=>[l.pool_id,created.filter(x=>x.pool_id===l.pool_id).length]))){const p=await this.getPool(c,poolId);if(p.ready<n)throw new WearError('WEAR_NOT_READY',409);await c.query('UPDATE wear_pools SET ready=ready-$2,on_loan=on_loan+$2 WHERE id=$1',[poolId,n]);}return {cycleId:cycle,loans:created};
 });}
 async receive(key:string,value:unknown){const v=exact(value,['loanId','expectedRevision','store','quantity','reason','unresolvedId']);id(v.loanId);revision(v.expectedRevision);const s=store(v.store),q=quantity(v.quantity);if(v.unresolvedId!==null)id(v.unresolvedId);return this.tx('RENTAL_RETURN',[s],key,v,reason(v.reason),async(c,now)=>{
  const l=(await c.query<Loan>('SELECT * FROM wear_loans WHERE id=$1',[v.loanId])).rows[0];if(!l)throw new WearError('LOAN_NOT_FOUND',404);if(l.revision!==v.expectedRevision)throw new WearError('STALE_REVISION',409);if(l.returned+q>l.quantity)throw new WearError('EXCESS_RETURN',409);let receivedAt=now;
  if(v.unresolvedId){const u=(await c.query('SELECT * FROM wear_unresolved_returns WHERE id=$1',[v.unresolvedId])).rows[0];if(!u||u.receipt_id||u.variant_id!==l.variant_id||u.store_id!==s||u.quantity!==q)throw new WearError('UNRESOLVED_RETURN_MISMATCH',409);receivedAt=u.received_at;}
  const destination=await this.ensurePool(c,l.variant_id,s),receiptId=randomUUID();await c.query('UPDATE wear_loans SET returned=returned+$2 WHERE id=$1',[l.id,q]);
  await c.query("INSERT INTO wear_receipts(id,loan_id,pool_id,quantity,actual_store,received_at,confirmed_at,eligible_on,state,actor) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'RETURNED_PENDING',$9)",[receiptId,l.id,destination.id,q,s,receivedAt,now,nextDay(receivedAt),this.identity.subject]);await c.query('UPDATE wear_pools SET on_loan=on_loan-$2 WHERE id=$1',[l.pool_id,q]);await c.query('UPDATE wear_pools SET returned_pending=returned_pending+$2 WHERE id=$1',[destination.id,q]);if(v.unresolvedId)await c.query('UPDATE wear_unresolved_returns SET receipt_id=$2 WHERE id=$1',[v.unresolvedId,receiptId]);return {receipt:(await c.query<Receipt>('SELECT *,eligible_on::text AS eligible_on FROM wear_receipts WHERE id=$1',[receiptId])).rows[0],remaining:l.quantity-l.returned-q,automaticRefund:false};
 });}
 async unresolved(key:string,value:unknown){const v=exact(value,['variantId','store','quantity','reason']);id(v.variantId);const s=store(v.store),q=quantity(v.quantity);return this.tx('RENTAL_RETURN',[s],key,v,reason(v.reason),async(c,now)=>{const variant=(await c.query('SELECT family FROM ledger_variants WHERE id=$1',[v.variantId])).rows[0];if(!variant||!isWear(variant.family))throw new WearError('INVALID_WEAR_VARIANT');const uid=randomUUID();await c.query('INSERT INTO wear_unresolved_returns(id,variant_id,store_id,quantity,received_at,actor,reason) VALUES($1,$2,$3,$4,$5,$6,$7)',[uid,v.variantId,s,q,now,this.identity.subject,v.reason]);return {id:uid,state:'UNRESOLVED_RETURN',addedToSellable:0};});}
 async cleaning(key:string,value:unknown){const v=exact(value,['receiptId','expectedRevision','operation','confirmedReady','reason']);id(v.receiptId);revision(v.expectedRevision);if(!['START','COMPLETE','RELEASE_NEXT_DAY'].includes(String(v.operation))||typeof v.confirmedReady!=='boolean')throw new WearError('INVALID_CLEANING_OPERATION');await this.authorize('RENTAL_RETURN');const before=(await this.pool.query<Receipt>('SELECT *,eligible_on::text AS eligible_on FROM wear_receipts WHERE id=$1',[v.receiptId])).rows[0];if(!before)throw new WearError('RECEIPT_NOT_FOUND',404);return this.tx('RENTAL_RETURN',[before.actual_store],key,v,reason(v.reason),async(c,now)=>{const receipt=(await c.query<Receipt>('SELECT *,eligible_on::text AS eligible_on FROM wear_receipts WHERE id=$1',[v.receiptId])).rows[0]!;if(receipt.revision!==v.expectedRevision)throw new WearError('STALE_REVISION',409);let target:string,from:string;
  if(v.operation==='START'){if(receipt.state!=='RETURNED_PENDING')throw new WearError('INVALID_CLEANING_STATE');from='returned_pending';target='CLEANING';}
  else if(v.operation==='COMPLETE'){if(!v.confirmedReady||receipt.state!=='CLEANING')throw new WearError('ACTUAL_READY_CONFIRMATION_REQUIRED');from='cleaning';target=day(now)<String(receipt.eligible_on)?'TODAY_BLOCKED':'READY';}
  else{if(receipt.state!=='TODAY_BLOCKED'||!receipt.ready_at||day(now)<String(receipt.eligible_on))throw new WearError('SAME_DAY_REHIRE_BLOCKED');from='today_blocked';target='READY';}
  const column=target==='CLEANING'?'cleaning':target==='TODAY_BLOCKED'?'today_blocked':'ready';await c.query('UPDATE wear_receipts SET state=$2,ready_at=CASE WHEN $3 THEN $4 ELSE ready_at END WHERE id=$1',[receipt.id,target,v.operation==='COMPLETE',now]);await c.query(`UPDATE wear_pools SET ${from}=${from}-$2,${column}=${column}+$2 WHERE id=$1`,[receipt.pool_id,receipt.quantity]);return (await c.query<Receipt>('SELECT *,eligible_on::text AS eligible_on FROM wear_receipts WHERE id=$1',[receipt.id])).rows[0]!;
 });}
 async transfers(storeId:string){store(storeId);await this.authorize('TRANSFER_VIEW',[storeId]);return (await this.pool.query(`SELECT t.*,p.store_id AS source_store,p.variant_id FROM wear_transfers t JOIN wear_pools p ON p.id=t.source_pool_id WHERE p.store_id=$1 OR t.destination_store=$1 ORDER BY t.scheduled_at,t.id`,[storeId])).rows;}
 async planTransfer(key:string,value:unknown){const v=exact(value,['poolId','expectedRevision','destinationStore','quantity','scheduledDate','reason']);id(v.poolId);revision(v.expectedRevision);const destination=store(v.destinationStore),q=quantity(v.quantity);if(typeof v.scheduledDate!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v.scheduledDate))throw new WearError('INVALID_TRANSFER_DATE');const scheduled=new Date(v.scheduledDate+'T17:00:00+09:00');if(!Number.isFinite(scheduled.getTime())||day(scheduled)!==v.scheduledDate)throw new WearError('INVALID_TRANSFER_DATE');await this.authorize('TRANSFER_PLAN');const before=await this.getPool(this.pool,v.poolId);if(before.store_id===destination)throw new WearError('SAME_STORE');return this.tx('TRANSFER_PLAN',[before.store_id,destination],key,v,reason(v.reason),async(c,now)=>{const p=await this.getPool(c,before.id);if(p.revision!==v.expectedRevision)throw new WearError('STALE_REVISION',409);if(scheduled<=now)throw new WearError('DEPARTURE_ALREADY_PASSED');const tid=randomUUID();await c.query("INSERT INTO wear_transfers(id,source_pool_id,destination_store,quantity,scheduled_at,state) VALUES($1,$2,$3,$4,$5,'PLANNED')",[tid,p.id,destination,q,scheduled]);
 // Revalidate ready capacity including this plan; planning never creates destination stock.
 await c.query('UPDATE wear_pools SET ready=ready WHERE id=$1',[p.id]);return (await c.query('SELECT * FROM wear_transfers WHERE id=$1',[tid])).rows[0];});}
 async transfer(key:string,value:unknown){const v=exact(value,['transferId','expectedRevision','operation','quantity','reason']);id(v.transferId);revision(v.expectedRevision);if(!['DISPATCH','CANCEL','RECEIVE'].includes(String(v.operation)))throw new WearError('INVALID_TRANSFER_OPERATION');const q=v.operation==='RECEIVE'?quantity(v.quantity):0;if(v.operation!=='RECEIVE'&&v.quantity!==null)throw new WearError('INVALID_INPUT');const permission=v.operation==='DISPATCH'?'TRANSFER_DISPATCH':v.operation==='CANCEL'?'TRANSFER_PLAN':'TRANSFER_RECEIVE';await this.authorize(permission);const before=(await this.pool.query('SELECT t.*,p.store_id AS source_store,p.variant_id FROM wear_transfers t JOIN wear_pools p ON p.id=t.source_pool_id WHERE t.id=$1',[v.transferId])).rows[0];if(!before)throw new WearError('TRANSFER_NOT_FOUND',404);const stores=v.operation==='RECEIVE'?[before.destination_store]:v.operation==='CANCEL'?[before.source_store,before.destination_store]:[before.source_store];return this.tx(permission,stores,key,v,reason(v.reason),async(c,now)=>{const t=(await c.query('SELECT * FROM wear_transfers WHERE id=$1',[before.id])).rows[0];if(t.revision!==v.expectedRevision)throw new WearError('STALE_REVISION',409);
 if(v.operation==='CANCEL'){if(t.state!=='PLANNED')throw new WearError('PHYSICAL_TRANSFER_CANNOT_CANCEL',409);await c.query("UPDATE wear_transfers SET state='CANCELLED' WHERE id=$1",[t.id]);}
 else if(v.operation==='DISPATCH'){if(t.state!=='PLANNED'||now<new Date(t.scheduled_at))throw new WearError('DEPARTURE_NOT_READY',409);await c.query("UPDATE wear_transfers SET state='IN_TRANSIT',departed_at=$2 WHERE id=$1",[t.id,now]);await c.query('UPDATE wear_pools SET ready=ready-$2,in_transit=in_transit+$2 WHERE id=$1',[t.source_pool_id,t.quantity]);}
 else {if(t.state!=='IN_TRANSIT'||q>t.quantity-t.received)throw new WearError('EXCESS_TRANSFER_RECEIPT',409);const dest=await this.ensurePool(c,before.variant_id,t.destination_store);await c.query("UPDATE wear_transfers SET received=received+$2,state=CASE WHEN received+$2=quantity THEN 'RECEIVED' ELSE state END WHERE id=$1",[t.id,q]);await c.query("INSERT INTO wear_transfer_receipts(id,transfer_id,pool_id,quantity,received_at,eligible_on,state) VALUES($1,$2,$3,$4,$5,$6,'RETURNED_PENDING')",[randomUUID(),t.id,dest.id,q,now,day(now)]);await c.query('UPDATE wear_pools SET in_transit=in_transit-$2 WHERE id=$1',[t.source_pool_id,q]);await c.query('UPDATE wear_pools SET returned_pending=returned_pending+$2 WHERE id=$1',[dest.id,q]);}
 return {transfer:(await c.query('SELECT * FROM wear_transfers WHERE id=$1',[t.id])).rows[0],receipts:(await c.query('SELECT *,eligible_on::text AS eligible_on FROM wear_transfer_receipts WHERE transfer_id=$1 ORDER BY id',[t.id])).rows};});}
 async transferReady(key:string,value:unknown){const v=exact(value,['receiptId','expectedRevision','confirmedReady','reason']);id(v.receiptId);revision(v.expectedRevision);if(v.confirmedReady!==true)throw new WearError('ACTUAL_READY_CONFIRMATION_REQUIRED');await this.authorize('TRANSFER_RECEIVE');const before=(await this.pool.query('SELECT r.*,p.store_id FROM wear_transfer_receipts r JOIN wear_pools p ON p.id=r.pool_id WHERE r.id=$1',[v.receiptId])).rows[0];if(!before)throw new WearError('RECEIPT_NOT_FOUND',404);return this.tx('TRANSFER_RECEIVE',[before.store_id],key,v,reason(v.reason),async(c,now)=>{const receipt=(await c.query('SELECT * FROM wear_transfer_receipts WHERE id=$1',[before.id])).rows[0];if(receipt.revision!==v.expectedRevision)throw new WearError('STALE_REVISION',409);if(receipt.state!=='RETURNED_PENDING')throw new WearError('ALREADY_READY',409);await c.query("UPDATE wear_transfer_receipts SET state='READY',ready_at=$2 WHERE id=$1",[receipt.id,now]);await c.query('UPDATE wear_pools SET returned_pending=returned_pending-$2,ready=ready+$2 WHERE id=$1',[receipt.pool_id,receipt.quantity]);return (await c.query('SELECT * FROM wear_transfer_receipts WHERE id=$1',[receipt.id])).rows[0];});}
 async receipts(bookingId:string,receivingStore:string){await this.loans(bookingId,receivingStore);return (await this.pool.query('SELECT r.*,r.eligible_on::text AS eligible_on FROM wear_receipts r JOIN wear_loans l ON l.id=r.loan_id WHERE l.booking_id=$1 ORDER BY r.received_at,r.id',[bookingId])).rows;}
}
