import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
import {chromium} from '@playwright/test';
import {startDevelopmentApp} from '../../scripts/development-app';
import {bootstrapDevelopmentAdmin} from '../../scripts/bootstrap-staff';
import {seedRecommendation,fid} from '../recommendation/fixture';
import {skiSet,requestFor} from '../inventory/fixture';
const browser=await chromium.launch(),password=randomBytes(24).toString('base64url');let app:Awaited<ReturnType<typeof startDevelopmentApp>>|undefined,passed=0,failed=0;
async function check(name:string,fn:()=>Promise<void>){try{await fn();passed++;console.log('PASS '+name);}catch(e){failed++;console.error('FAIL '+name+' '+((e as {code?:string}).code??(e as Error).name));if(e instanceof assert.AssertionError)console.error(JSON.stringify({actual:e.actual,expected:e.expected}));console.error((e as Error).stack?.split('\n').filter(l=>l.includes('/tests/stabilization/cd.ts:')).join('\n'));}}
try{
 app=await startDevelopmentApp({built:true});await seedRecommendation(app.db.pool);await bootstrapDevelopmentAdmin(app.db.pool,{email:'cd-root@example.invalid',displayName:'合成CD管理者',password});const {origin}=app,owner=app.db.pool;
 async function clock(t:string){const value=new Date(t).toISOString();await owner.query(`CREATE OR REPLACE FUNCTION inventory_clock() RETURNS timestamptz LANGUAGE sql VOLATILE AS $$SELECT '${value}'::timestamptz$$`);}
 await clock('2035-07-01T10:00:00+09:00');for(let i=0;i<100;i++){try{if((await fetch(origin+'/api/health')).ok)break;}catch{}if(i===99)throw new Error('APP_START_TIMEOUT');await new Promise(r=>setTimeout(r,100));}
 async function login(email:string){const c=await browser.newContext({baseURL:origin});c.setDefaultTimeout(10000);const p=await c.newPage();await p.goto('/staff/login');await p.getByLabel('メールアドレス',{exact:true}).fill(email);await p.getByLabel('パスワード',{exact:true}).fill(password);await p.getByRole('button',{name:'ログイン',exact:true}).click();await p.waitForURL(origin+'/staff/ledger');await p.close();return c;}
 const admin=await login('cd-root@example.invalid');const cr=await admin.request.post('/api/staff-users',{headers:{origin},data:{email:'cd-actor@example.invalid',password,displayName:'合成CD担当',active:true,role:'ADMIN',scope:'ALL',storeIds:[],permissions:{INVENTORY_VIEW:true,INVENTORY_EDIT:true,HOLD_VIEW:true,HOLD_EDIT:true,TRANSFER_VIEW:true,TRANSFER_PLAN:true,TRANSFER_DISPATCH:true,TRANSFER_RECEIVE:true}}});assert.equal(cr.status(),201);const actorId=(await cr.json()).id as string,c=await login('cd-actor@example.invalid');
 async function edit(resource:string,id:string,patch:Record<string,unknown>){const before=await (await c.request.get('/api/ledger/'+resource+'/'+id)).json();return c.request.patch('/api/ledger/'+resource+'/'+id,{headers:{origin},data:{version:before.version,reason:'SYNTHETIC A-G lifecycle reconciliation',...patch}});}
 const h=await (await c.request.post('/api/holds',{headers:{origin},data:{requestKey:randomUUID(),conditions:skiSet('2035-07-02')}})).json();assert.equal(h.result,'CREATED');await clock('2035-07-01T10:11:00+09:00');assert.equal((await (await c.request.get('/api/holds/'+h.holdId)).json()).state,'EXPIRED');
 await check('C expired unpaid group claim reconciles in ordinary Asset maintenance, audited once',async()=>{
  const result=await edit('assets',fid(1201),{status:'MAINTENANCE'});assert.equal(result.status(),200);assert.equal((await owner.query('SELECT count(*)::int AS n FROM inventory_claims WHERE hold_id=$1 AND active',[h.holdId])).rows[0].n,0);assert.equal((await owner.query('SELECT state FROM inventory_holds WHERE id=$1',[h.holdId])).rows[0].state,'EXPIRED');assert.ok((await owner.query('SELECT actor FROM inventory_history WHERE hold_id=$1',[h.holdId])).rows.every(r=>r.actor===actorId));assert.equal((await edit('assets',fid(1201),{status:'AVAILABLE'})).status(),200);
 });
 await check('C expired group no longer blocks pole reduction without unrelated HOLD command',async()=>{assert.equal((await edit('poles',fid(1301),{quantity:0})).status(),200);assert.equal((await edit('poles',fid(1301),{quantity:1})).status(),200);});
 async function transfer(path:string,input:unknown,key=randomUUID()){const r=await c.request.post('/api/transfers'+path,{headers:{origin},data:{requestKey:key,input}});assert.equal(r.status(),path?200:201);return r.json();}
 const t=await transfer('',{sourceStore:'MOUNTAIN_BASE',destinationStore:'ONSEN_BASE',scheduledDate:'2035-07-03',plannedReadyAt:'2035-07-03T19:00:00+09:00',neededBy:'2035-07-04T08:30:00+09:00',basis:'SYNTHETIC CD completed movement',lines:[{assetId:fid(1204)},{poleId:fid(1301),quantity:1}]});await clock('2035-07-03T17:00:00+09:00');await transfer('/'+t.batch.id+'/dispatch',{});await clock('2035-07-03T17:12:00+09:00');const pieceIds=t.batch.pieces.map((p:{id:string})=>p.id);await transfer('/'+t.batch.id+'/receive',{pieceIds});const readyKey=randomUUID();const ready=await transfer('/'+t.batch.id+'/ready',{pieceIds},readyKey),pole=ready.batch.pieces.find((p:{destination_pole_id:string|null})=>p.destination_pole_id).destination_pole_id;
 await check('D unreferenced actual receipt/readiness closes Asset and pair witnesses immediately',async()=>{
  assert.ok(ready.batch.pieces.every((p:{state:string})=>p.state==='CLOSED'));const before=(await owner.query('SELECT sum(quantity)::int AS n FROM ledger_poles WHERE variant_id=$1',[fid(1104)])).rows[0].n;const replay=await transfer('/'+t.batch.id+'/ready',{pieceIds},readyKey);assert.equal(replay.replayed,true);assert.equal((await owner.query('SELECT sum(quantity)::int AS n FROM ledger_poles WHERE variant_id=$1',[fid(1104)])).rows[0].n,before);assert.ok(replay.batch.pieces.every((p:{state:string;received_at:string;ready_at:string})=>p.state==='CLOSED'&&p.received_at&&p.ready_at));
 });
 await check('D closed movement permits ordinary maintenance/quantity without next transfer.add',async()=>{assert.equal((await edit('assets',fid(1204),{status:'MAINTENANCE'})).status(),200);assert.equal((await edit('poles',pole,{quantity:0})).status(),200);assert.equal((await owner.query('SELECT count(*)::int AS n FROM transfer_requests WHERE request_key=$1',[readyKey])).rows[0].n,1);assert.ok((await owner.query('SELECT count(*)::int AS n FROM transfer_history WHERE batch_id=$1',[t.batch.id])).rows[0].n>=8);});

 let source=0;
 async function stock(family:'SKI'|'POLE',quantity=1,storeId='MOUNTAIN_BASE',existingVariant?:string){const provenance={notes:'SYNTHETIC CD',sourceKind:'SYNTHETIC',sourceDocument:'tests/stabilization/cd.ts',sourceLocator:'case-'+(++source)};let variant=existingVariant;
  if(!variant){const r=await c.request.post('/api/ledger/variants',{headers:{origin},data:{...provenance,modelId:fid(family==='SKI'?1001:1003),family,age:'ADULT',tier:'REGULAR',size:(300+source)+' cm'}});assert.equal(r.status(),201);variant=(await r.json()).id;}
  const value=family==='SKI'?{...provenance,family,variantId:variant,storeId,status:'AVAILABLE',bslStatus:'NOT_APPLICABLE',bslMm:null,bslEvidence:''}:{...provenance,variantId:variant,storeId,status:'AVAILABLE',quantity};const r=await c.request.post('/api/ledger/'+(family==='SKI'?'assets':'poles'),{headers:{origin},data:value});assert.equal(r.status(),201);return {id:(await r.json()).id as string,variant:variant!};
 }
 const hold=async(input:unknown)=>{const r=await c.request.post('/api/holds',{headers:{origin},data:{requestKey:randomUUID(),conditions:input}});assert.equal(r.status(),201);return r.json();};
 async function flag(id:string,mode:string){const x=await owner.connect();try{await x.query('BEGIN');await x.query("SELECT set_config('zao.actor',$1,true)",[actorId]);await x.query(mode.endsWith('_FIXED')?'UPDATE inventory_holds SET allocation_stage=$2 WHERE id=$1':'UPDATE inventory_holds SET payment_state=$2 WHERE id=$1',[id,mode]);await x.query('COMMIT');}finally{x.release();}}
 for(const mode of ['ACTIVE','PENDING','UNKNOWN','SUCCESS','PREPARATION_FIXED','RENTAL_FIXED'])await check('C protects '+mode+' despite ledger status/quantity request',async()=>{
  await clock('2035-08-01T10:00:00+09:00');const a=await stock('SKI'),q=await stock('POLE',2),input=requestFor('2035-09-01',[a.variant]),pi=requestFor('2035-09-01');pi.members[0]!.items=[{family:'POLE',variantIds:[q.variant]}];const ah=await hold(input),ph=await hold(pi);assert.equal(ah.result,'CREATED');assert.equal(ph.result,'CREATED');if(mode!=='ACTIVE'){await flag(ah.holdId,mode);await flag(ph.holdId,mode);await clock('2035-08-01T10:11:00+09:00');}
  assert.equal((await edit('assets',a.id,{status:'MAINTENANCE'})).status(),422);assert.equal((await edit('poles',q.id,{quantity:0})).status(),422);assert.equal((await owner.query('SELECT count(*)::int AS n FROM inventory_claims WHERE hold_id=ANY($1::uuid[]) AND active',[[ah.holdId,ph.holdId]])).rows[0].n,2);assert.equal((await owner.query('SELECT status FROM ledger_assets WHERE id=$1',[a.id])).rows[0].status,'AVAILABLE');assert.equal((await owner.query('SELECT quantity FROM ledger_poles WHERE id=$1',[q.id])).rows[0].quantity,2);
 });
 await check('C failed-payment expired lease releases but unrelated protected groups stay intact',async()=>{await clock('2035-08-01T11:00:00+09:00');const a=await stock('SKI'),h=await hold(requestFor('2035-09-02',[a.variant]));await flag(h.holdId,'FAILURE');const protectedBefore=(await owner.query("SELECT count(*)::int AS n FROM inventory_claims cl JOIN inventory_holds h ON h.id=cl.hold_id WHERE cl.active AND (h.payment_state IN ('PENDING','UNKNOWN','SUCCESS') OR h.allocation_stage<>'PROVISIONAL')")).rows[0].n;await clock('2035-08-01T11:11:00+09:00');assert.equal((await edit('assets',a.id,{status:'MAINTENANCE'})).status(),200);assert.equal((await owner.query('SELECT state FROM inventory_holds WHERE id=$1',[h.holdId])).rows[0].state,'EXPIRED');assert.equal((await owner.query("SELECT count(*)::int AS n FROM inventory_claims cl JOIN inventory_holds h ON h.id=cl.hold_id WHERE cl.active AND (h.payment_state IN ('PENDING','UNKNOWN','SUCCESS') OR h.allocation_stage<>'PROVISIONAL')")).rows[0].n,protectedBefore);});
 const wait=async(user:string)=>{for(let i=0;i<100;i++){if((await owner.query("SELECT 1 FROM pg_stat_activity WHERE datname=current_database() AND usename=$1 AND wait_event='advisory'",[user])).rowCount)return true;await new Promise(r=>setTimeout(r,5));}return false;};
 for(const first of ['hold','ledger'])await check('C concurrent '+first+' first: new valid claim and maintenance cannot both win',async()=>{
  await clock('2035-08-01T12:00:00+09:00');const a=await stock('SKI'),old=await hold(requestFor('2035-09-03',[a.variant]));await clock('2035-08-01T12:11:00+09:00');const gate=await owner.connect();let hp:ReturnType<typeof hold>|undefined,lp:ReturnType<typeof edit>|undefined;
  try{await gate.query('BEGIN');await gate.query('SELECT pg_advisory_xact_lock(71820600)');if(first==='hold'){hp=hold(requestFor('2035-09-03',[a.variant]));assert.ok(await wait(app!.roles.holdDb.user));lp=edit('assets',a.id,{status:'MAINTENANCE'});assert.ok(await wait(app!.roles.transferDb.user));}else{lp=edit('assets',a.id,{status:'MAINTENANCE'});assert.ok(await wait(app!.roles.transferDb.user));hp=hold(requestFor('2035-09-03',[a.variant]));assert.ok(await wait(app!.roles.holdDb.user));}await gate.query('COMMIT');}finally{await gate.query('ROLLBACK');gate.release();}
  const [h,l]=await Promise.all([hp!,lp!]);assert.ok(['CREATED','INSUFFICIENT','TRANSFER_PLAN_REQUIRED'].includes(h.result));assert.ok([200,422].includes(l.status()));assert.equal(h.result==='CREATED'&&l.status()===200,false);assert.equal((await owner.query('SELECT count(*)::int AS n FROM inventory_claims WHERE hold_id=$1 AND active',[old.holdId])).rows[0].n,0);const counts=(await owner.query('SELECT a.status,count(cl.id)::int AS n FROM ledger_assets a LEFT JOIN inventory_claims cl ON cl.asset_id=a.id AND cl.active WHERE a.id=$1 GROUP BY a.id',[a.id])).rows[0];assert.ok(counts.status==='AVAILABLE'||counts.n===0);
 });
 function plan(day:string,lines:unknown[]){return {sourceStore:'MOUNTAIN_BASE',destinationStore:'ONSEN_BASE',scheduledDate:day,plannedReadyAt:day+'T17:03:00+09:00',neededBy:day+'T19:00:00+09:00',basis:'SYNTHETIC CD boundary',lines};}
 await check('D live referenced READY remains protected; partial transit, cancel, completion, replay and future stock stay consistent',async()=>{
  await clock('2035-08-02T16:55:00+09:00');const a=await stock('SKI'),q=await stock('POLE',3),t=await transfer('',plan('2035-08-02',[{assetId:a.id},{poleId:q.id,quantity:3}]));const ai=requestFor('2035-08-03',[a.variant]);ai.pickupStore=ai.returnStore='ONSEN_BASE';const pi=requestFor('2035-08-03');pi.pickupStore=pi.returnStore='ONSEN_BASE';pi.members[0]!.items=[{family:'POLE',variantIds:[q.variant]}];const ah=await hold(ai),ph=await hold(pi);assert.equal(ah.result,'CREATED');assert.equal(ph.result,'CREATED');const claim=(await owner.query('SELECT transfer_piece_id FROM inventory_claims WHERE hold_id=$1 AND active',[ph.holdId])).rows[0].transfer_piece_id;const selected=[t.batch.pieces.find((p:{asset_id:string})=>p.asset_id).id,claim];
  await clock('2035-08-02T17:00:00+09:00');await transfer('/'+t.batch.id+'/dispatch',{});await clock('2035-08-02T17:01:00+09:00');await transfer('/'+t.batch.id+'/receive',{pieceIds:selected});await clock('2035-08-02T17:02:00+09:00');let ready=await transfer('/'+t.batch.id+'/ready',{pieceIds:selected});assert.equal(ready.batch.pieces.filter((p:{state:string})=>p.state==='READY').length,2);assert.equal(ready.batch.pieces.filter((p:{state:string})=>p.state==='IN_TRANSIT').length,2);const dest=ready.batch.pieces.find((p:{destination_pole_id:string})=>p.destination_pole_id).destination_pole_id;assert.equal((await edit('assets',a.id,{status:'MAINTENANCE'})).status(),422);assert.equal((await edit('poles',dest,{quantity:0})).status(),422);
  for(const id of [ah.holdId,ph.holdId])assert.equal((await c.request.post('/api/holds/'+id+'/cancel',{headers:{origin},data:{requestKey:randomUUID()}})).status(),200);
  assert.equal((await edit('assets',a.id,{status:'MAINTENANCE'})).status(),200);assert.equal((await edit('poles',dest,{quantity:0})).status(),422);assert.equal((await owner.query('SELECT state FROM transfer_pieces WHERE id=$1',[claim])).rows[0].state,'CLOSED');const rest=t.batch.pieces.filter((p:{id:string})=>!selected.includes(p.id)).map((p:{id:string})=>p.id);await transfer('/'+t.batch.id+'/receive',{pieceIds:rest});const key=randomUUID();ready=await transfer('/'+t.batch.id+'/ready',{pieceIds:rest},key);assert.ok(ready.batch.pieces.every((p:{state:string})=>p.state==='CLOSED'));assert.equal((await transfer('/'+t.batch.id+'/ready',{pieceIds:rest},key)).replayed,true);assert.equal((await owner.query('SELECT quantity FROM ledger_poles WHERE id=$1',[dest])).rows[0].quantity,3);assert.equal((await owner.query('SELECT sum(quantity)::int AS n FROM ledger_poles WHERE variant_id=$1',[q.variant])).rows[0].n,3);assert.equal((await edit('poles',dest,{quantity:2})).status(),200);const next=await hold({...pi,reservationId:randomUUID()});assert.equal(next.result,'CREATED');assert.equal((await owner.query('SELECT transfer_piece_id FROM inventory_claims WHERE hold_id=$1 AND active',[next.holdId])).rows[0].transfer_piece_id,null);assert.equal((await edit('poles',dest,{quantity:0})).status(),422);
 });
 await check('D unresolved issue retains actual received/ready facts and blocks unsafe ledger cleanup',async()=>{
  await clock('2035-08-03T16:55:00+09:00');const a=await stock('SKI'),t=await transfer('',plan('2035-08-03',[{assetId:a.id}])),ids=t.batch.pieces.map((p:{id:string})=>p.id);await clock('2035-08-03T17:00:00+09:00');await transfer('/'+t.batch.id+'/dispatch',{});await transfer('/'+t.batch.id+'/issue',{reason:'SYNTHETIC unresolved handling'});await transfer('/'+t.batch.id+'/receive',{pieceIds:ids});const ready=await transfer('/'+t.batch.id+'/ready',{pieceIds:ids});assert.equal(ready.batch.pieces[0].state,'READY');assert.equal((await edit('assets',a.id,{status:'MAINTENANCE'})).status(),422);assert.equal((await owner.query('SELECT store_id FROM ledger_assets WHERE id=$1',[a.id])).rows[0].store_id,'ONSEN_BASE');assert.equal((await owner.query('SELECT state FROM transfer_pieces WHERE id=$1',[ids[0]])).rows[0].state,'READY');
 });
 await check('D closing receipt never enables same-day continuation reuse; next-day demand can use actual stock',async()=>{
  await clock('2035-08-04T16:55:00+09:00');const incoming=await stock('SKI'),local=await stock('SKI',1,'ONSEN_BASE',incoming.variant);const input=requestFor('2035-08-04',[incoming.variant]);input.pickupStore=input.returnStore='ONSEN_BASE';input.period.endDate='2035-08-05';input.period.slot='MULTIDAY';const h=await hold(input);assert.equal(h.result,'CREATED');const original=(await owner.query('SELECT DISTINCT asset_id FROM inventory_claims WHERE hold_id=$1 AND active',[h.holdId])).rows[0].asset_id;assert.equal(original,local.id);const t=await transfer('',plan('2035-08-04',[{assetId:incoming.id}])),pieceIds=t.batch.pieces.map((p:{id:string})=>p.id);await clock('2035-08-04T17:00:00+09:00');await transfer('/'+t.batch.id+'/dispatch',{});await clock('2035-08-04T17:02:00+09:00');await transfer('/'+t.batch.id+'/receive',{pieceIds});const ready=await transfer('/'+t.batch.id+'/ready',{pieceIds});assert.equal(ready.batch.pieces[0].state,'CLOSED');const reassign=await c.request.post('/api/holds/'+h.holdId+'/reassign',{headers:{origin},data:{requestKey:randomUUID(),requirementKey:'person-a:SKI',assetId:incoming.id}});assert.equal(reassign.status(),200);assert.notEqual((await reassign.json()).result,'AMENDED');assert.equal((await owner.query('SELECT DISTINCT asset_id FROM inventory_claims WHERE hold_id=$1 AND active',[h.holdId])).rows[0].asset_id,original);const next=requestFor('2035-08-05',[incoming.variant]);next.pickupStore=next.returnStore='ONSEN_BASE';assert.equal((await hold(next)).result,'CREATED');assert.equal((await owner.query('SELECT count(*)::int AS n FROM (SELECT asset_id,day FROM inventory_claims WHERE active GROUP BY asset_id,day HAVING count(*)>1 AND asset_id IS NOT NULL) x')).rows[0].n,0);
 });
 for(const first of ['ready','hold'])await check('D concurrent '+first+' first: completion and new group never double count physical/projection stock',async()=>{
  const day=first==='ready'?'2035-08-06':'2035-08-07';await clock(day+'T16:55:00+09:00');const a=await stock('SKI'),q=await stock('POLE',1),t=await transfer('',plan(day,[{assetId:a.id},{poleId:q.id,quantity:1}])),pieceIds=t.batch.pieces.map((p:{id:string})=>p.id);await clock(day+'T17:00:00+09:00');await transfer('/'+t.batch.id+'/dispatch',{});await clock(day+'T17:01:00+09:00');await transfer('/'+t.batch.id+'/receive',{pieceIds});
  const input=requestFor('2035-08-08',[a.variant]);input.pickupStore=input.returnStore='ONSEN_BASE';input.members.push({...structuredClone(input.members[0]!),key:'pole-b',items:[{family:'POLE',variantIds:[q.variant]}]});const gate=await owner.connect();let hp:ReturnType<typeof hold>|undefined,rp:ReturnType<typeof transfer>|undefined;const key=randomUUID();
  try{await gate.query('BEGIN');await gate.query('SELECT pg_advisory_xact_lock(71820600)');if(first==='ready'){rp=transfer('/'+t.batch.id+'/ready',{pieceIds},key);assert.ok(await wait(app!.roles.transferDb.user));hp=hold(input);assert.ok(await wait(app!.roles.holdDb.user));}else{hp=hold(input);assert.ok(await wait(app!.roles.holdDb.user));rp=transfer('/'+t.batch.id+'/ready',{pieceIds},key);assert.ok(await wait(app!.roles.transferDb.user));}await gate.query('COMMIT');}finally{await gate.query('ROLLBACK');gate.release();}
  const [created,ready]=await Promise.all([hp!,rp!]);assert.equal(created.result,'CREATED');assert.ok(ready.batch.pieces.every((p:{state:string})=>p.state===(first==='ready'?'CLOSED':'READY')));assert.equal((await transfer('/'+t.batch.id+'/ready',{pieceIds},key)).replayed,true);assert.equal((await owner.query('SELECT sum(quantity)::int AS n FROM ledger_poles WHERE variant_id=$1',[q.variant])).rows[0].n,1);assert.equal((await owner.query('SELECT count(*)::int AS n FROM inventory_claims WHERE hold_id=$1 AND active',[created.holdId])).rows[0].n,2);const shortage=await c.request.post('/api/holds',{headers:{origin},data:{requestKey:randomUUID(),conditions:{...input,reservationId:randomUUID()}}});assert.equal(shortage.status(),200);assert.equal((await shortage.json()).result,'INSUFFICIENT');
 });
 console.log(`C/D ordinary authentication/API/real PostgreSQL: ${passed} passed; ${failed} failed;0 skipped.`);
}catch(e){failed++;console.error('CD_SETUP_FAILED '+((e as {code?:string}).code??(e as Error).name));if(e instanceof assert.AssertionError)console.error(JSON.stringify({actual:e.actual,expected:e.expected}));}finally{await browser.close();await app?.stop();console.log('Owned C/D Web/browser/PostgreSQL stopped.');}if(failed)process.exit(1);
