import assert from 'node:assert/strict';
import {randomUUID,randomBytes} from 'node:crypto';
import type {Pool} from 'pg';
import {migrate} from '@rental/db';
import {startIsolatedPostgres} from '../../scripts/postgres';
import {provisionApplicationRoles} from '../../scripts/application-roles';
import {bootstrapDevelopmentAdmin} from '../../scripts/bootstrap-staff';
import {writeAccount} from '../../packages/auth/src/accounts';
import {loadStaff} from '../../packages/auth/src/staff-auth';
import {LedgerService} from '../../packages/core/src/catalog/ledger-service';
import {HoldService} from '../../packages/core/src/inventory/hold-service';
import {matchPeriods} from '../../packages/core/src/inventory/period-matching';
import {QuoteService} from '../../packages/core/src/pricing/quote-service';
import {seedInventory,requestFor,skiSet,variants,fid} from '../inventory/fixture';
let passed=0,failed=0;const db=await startIsolatedPostgres();let roles:Awaited<ReturnType<typeof provisionApplicationRoles>>|undefined;
async function check(name:string,f:()=>Promise<void>){try{await f();passed++;console.log('PASS '+name);}catch(e){failed++;console.error('FAIL '+name+' '+((e as {code?:string}).code??(e as Error).name));if(e instanceof assert.AssertionError)console.error(JSON.stringify({actual:e.actual,expected:e.expected}));}}
const day=(n:number)=>new Date(Date.UTC(2038,0,1+n)).toISOString().slice(0,10);let now=new Date('2037-01-01T00:00:00Z');
try{
 await migrate(db.pool);await seedInventory(db.pool,true);const actor=await bootstrapDevelopmentAdmin(db.pool,{email:'eg-synthetic@example.invalid',displayName:'合成EG管理者',password:randomBytes(24).toString('base64url')});roles=await provisionApplicationRoles(db.pool,db.identity);const bootstrap=(await loadStaff(roles.authPool,actor))!;const editor=(await writeAccount(roles.authPool,bootstrap,undefined,{email:'eg-editor@example.invalid',password:randomBytes(24).toString('base64url'),displayName:'合成EG担当',active:true,role:'ADMIN',scope:'ALL',storeIds:[],permissions:{HOLD_VIEW:true,HOLD_EDIT:true,QUOTE_VIEW:true,QUOTE_CREATE:true,PRICE_EDIT:true}})).id!;const principal=(await loadStaff(roles.authPool,editor))!;const h=new HoldService(roles.holdPool,principal,()=>now),q=new QuoteService(roles.pricingPool,principal,()=>now);await q.initializePrivate(randomUUID(),'2038-01-01','2040-12-31');
 const create=(input=requestFor(day(0)))=>h.command('create',randomUUID(),input);
 await check('E nine identical board units for ten same-day people is INSUFFICIENT, not search exhaustion',async()=>{const units=Array.from({length:9},(_,i)=>'u'+i);assert.equal(matchPeriods(Array.from({length:10},(_,i)=>({key:'p'+i,start:day(0),end:day(0),candidates:units})),new Map(units.map(u=>[u,1])),[]),null);});
 await check('E 81 independent live groups / 243 components do not cap a disjoint request',async()=>{for(let i=0;i<81;i++)assert.equal((await create(skiSet(day(i)))).result,'CREATED');assert.equal((await h.availability(skiSet(day(82)))).result,'FEASIBLE');assert.equal((await db.pool.query("SELECT count(*)::int AS n FROM inventory_holds WHERE state='ACTIVE'")).rows[0].n,81);assert.equal((await db.pool.query('SELECT count(*)::int AS n FROM inventory_claims WHERE active')).rows[0].n,243);});
 await check('E same candidate units on disjoint days preserve every original claim/TTL under concurrent new requests',async()=>{const before=(await db.pool.query('SELECT id,conditions,expires_at FROM inventory_holds ORDER BY id')).rows;const outcome=await Promise.all([create(skiSet(day(100))),create(skiSet(day(101)))]);assert.ok(outcome.every(r=>r.result==='CREATED'));const after=(await db.pool.query('SELECT id,conditions,expires_at FROM inventory_holds WHERE id=ANY($1::uuid[]) ORDER BY id',[before.map(h=>h.id)])).rows;assert.deepEqual(after,before);assert.equal((await db.pool.query('SELECT count(*)::int AS n FROM (SELECT asset_id,day FROM inventory_claims WHERE active AND asset_id IS NOT NULL GROUP BY asset_id,day HAVING count(*)>1) x')).rows[0].n,0);});
 await check('E connected 81 live single-component promises exceed old whole-repository cap safely',async()=>{
  now=new Date(now.getTime()+601000);for(let i=0;i<81;i++)assert.equal((await create(requestFor(day(150)))).result,'CREATED');assert.equal((await create(requestFor(day(150)))).result,'CREATED');const rows=(await db.pool.query("SELECT asset_id FROM inventory_claims WHERE active AND day=$1",[day(150)])).rows;assert.equal(rows.length,82);assert.equal(new Set(rows.map(r=>r.asset_id)).size,82);
 });
 await check('E transitive size/date chain rearranges all dependent witnesses but not unrelated/fixed groups',async()=>{
  now=new Date(now.getTime()+601000);const ledger=new LedgerService(roles!.ledgerPool,{subject:editor,role:'ADMIN',storeIds:['MOUNTAIN_BASE','ONSEN_BASE']},async()=>{/* Explicit synthetic fixture boundary; normal runtime uses verifyLedgerWrite. */});const vars:string[]=[],assets:string[]=[];
  for(let n=0;n<3;n++){const provenance={notes:'SYNTHETIC E dependency',sourceKind:'SYNTHETIC',sourceDocument:'tests/stabilization/eg.ts',sourceLocator:'chain-v'+n};const v=await ledger.create('variants',{...provenance,modelId:fid(1001),family:'SKI',age:'ADULT',tier:'REGULAR',size:(190+n)+' cm'});vars.push(v.id);const a=await ledger.create('assets',{...provenance,sourceLocator:'chain-a'+n,variantId:v.id,family:'SKI',storeId:'MOUNTAIN_BASE',status:'AVAILABLE',bslStatus:'NOT_APPLICABLE',bslMm:null,bslEvidence:''});assets.push(a.id);}
  const a=requestFor(day(160),vars.slice(0,2));a.period.endDate=day(161);a.period.slot='MULTIDAY';const b=requestFor(day(161),vars.slice(1));b.period.endDate=day(162);b.period.slot='MULTIDAY';const ah=await create(a),bh=await create(b);assert.equal(ah.result,'CREATED');assert.equal(bh.result,'CREATED');const before=(await db.pool.query('SELECT id,conditions,expires_at FROM inventory_holds WHERE id=ANY($1::uuid[]) ORDER BY id',[[ah.holdId,bh.holdId]])).rows;assert.equal((await create(requestFor(day(160),[vars[0]!]))).result,'CREATED');
  assert.equal((await db.pool.query('SELECT DISTINCT asset_id FROM inventory_claims WHERE hold_id=$1 AND active',[ah.holdId])).rows[0].asset_id,assets[1]);assert.equal((await db.pool.query('SELECT DISTINCT asset_id FROM inventory_claims WHERE hold_id=$1 AND active',[bh.holdId])).rows[0].asset_id,assets[2]);assert.deepEqual((await db.pool.query('SELECT id,conditions,expires_at FROM inventory_holds WHERE id=ANY($1::uuid[]) ORDER BY id',[[ah.holdId,bh.holdId]])).rows,before);
  now=new Date(now.getTime()+601000);const cross=requestFor(day(165),[vars[0]!]);cross.returnStore='ONSEN_BASE';const ch=await create(cross);assert.equal(ch.result,'CREATED');assert.equal((await create(requestFor(day(180),[vars[0]!]))).result,'TRANSFER_PLAN_REQUIRED');assert.equal((await h.get(ch.holdId!)).expiresAt,ch.hold!.expiresAt);
 });
 now=new Date(now.getTime()+601000);
 // Counter counts include auth, transaction and integrity work, not only target SELECTs.
 let queries:string[]=[];const measured=new Proxy(roles.pricingPool,{get(pool,key){if(key==='connect')return async()=>{const c=await pool.connect();return new Proxy(c,{get(client,k){if(k==='query')return (sql:string|{text:string},...args:unknown[])=>{queries.push(typeof sql==='string'?sql:sql.text);return Reflect.apply(client.query,client,[sql,...args]);};const v=Reflect.get(client,k);return typeof v==='function'?v.bind(client):v;}});};if(key==='query')return (sql:string|{text:string},...args:unknown[])=>{queries.push(typeof sql==='string'?sql:sql.text);return Reflect.apply(pool.query,pool,[sql,...args]);};const v=Reflect.get(pool,key);return typeof v==='function'?v.bind(pool):v;}}) as Pool;const measuredQuote=new QuoteService(measured,principal,()=>now);
 await check('G maximum group quote validates all 60 component selections with one variant query',async()=>{const input=skiSet(day(200));input.members=Array.from({length:20},(_,i)=>({...structuredClone(input.members[0]!),key:'p'+i}));queries=[];const preview=await measuredQuote.preview({conditions:input,holdId:null,wantAdvance:false,couponCode:null});assert.equal(preview.chargeReady,false);const count=queries.filter(x=>/SELECT id,family,age,tier FROM ledger_variants/.test(x)).length;console.log('MEASURE variant-validation '+JSON.stringify({people:20,components:60,allQueries:queries.length,variantQueries:count}));assert.equal(count,1);});
 await check('G 100 quote listing has bounded SQL with owner/store, immutable hash, HOLD validity',async()=>{now=new Date(now.getTime()+1);const held=await create(skiSet(day(201)));assert.equal(held.result,'CREATED');for(let i=0;i<100;i++)await q.create(randomUUID(),{conditions:held.hold!.conditions,holdId:held.holdId,wantAdvance:false,couponCode:null});queries=[];const rows=await measuredQuote.list();console.log('MEASURE quote-list '+JSON.stringify({quotes:rows.length,queries:queries.length}));assert.equal(rows.length,100);assert.ok(rows.every(x=>x.validity==='VALID_PRIVATE_ESTIMATE'&&x.chargeReady===false));assert.ok(queries.length<=15,`query count ${queries.length} exceeds constant bound15`);});
 // A malformed condition must remain rejected after batching (including one of many later members).
 await check('G batched selection preserves family, age/tier, missing variant and owner rejection',async()=>{for(const bad of [fid(999999),variants.board,variants.kids,variants.premium]){const input=skiSet(day(202));input.members.push({...structuredClone(input.members[0]!),key:'later'});input.members[1]!.items[0]!.variantIds=[bad];await assert.rejects(measuredQuote.preview({conditions:input,holdId:null,wantAdvance:false,couponCode:null}),{code:'VARIANT_CONDITIONS_MISMATCH'});}});
 console.log(`E/G real PostgreSQL: ${passed} passed; ${failed} failed; 0 skipped.`);
}catch(e){failed++;console.error('EG_SETUP_FAILED '+((e as {code?:string}).code??(e as Error).name));}finally{try{await roles?.close();}finally{await db.stop();}console.log('Owned E/G PostgreSQL stopped.');}if(failed)process.exit(1);
