import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
import {chromium,expect,type BrowserContext} from '@playwright/test';
import {startDevelopmentApp} from '../../scripts/development-app';
import {bootstrapDevelopmentAdmin} from '../../scripts/bootstrap-staff';
import {seedRecommendation,fid} from '../recommendation/fixture';
import {parseConditions} from '../../packages/contracts/src/hold';
import {readJson} from '../../apps/web/src/lib/ledger-http';
let app:Awaited<ReturnType<typeof startDevelopmentApp>>|undefined,passed=0,failed=0;
const browser=await chromium.launch(),password=randomBytes(24).toString('base64url');
async function check(name:string,fn:()=>Promise<void>){try{await fn();passed++;console.log('PASS '+name);}catch(e){failed++;console.error('FAIL '+name+' '+(e as Error).name);if(!(e instanceof assert.AssertionError))console.error((e as Error).message.slice(0,1200));if(e instanceof assert.AssertionError)console.error(JSON.stringify({actual:e.actual,expected:e.expected}));console.error((e as Error).stack?.split('\n').filter(l=>l.includes('/tests/stabilization/s01.ts:')).join('\n'));}}
try{
 app=await startDevelopmentApp({built:true});await seedRecommendation(app.db.pool);await bootstrapDevelopmentAdmin(app.db.pool,{email:'s01-root@example.invalid',displayName:'合成S01管理者1',password});const {origin}=app,owner=app.db.pool;
 await owner.query(`CREATE OR REPLACE FUNCTION inventory_clock() RETURNS timestamptz LANGUAGE sql VOLATILE AS $$SELECT '2035-01-01T00:00:00Z'::timestamptz$$`);
 for(let i=0;i<100;i++){try{if((await fetch(origin+'/api/health')).ok)break;}catch{}if(i===99)throw new Error('APP_START_TIMEOUT');await new Promise(r=>setTimeout(r,100));}
 async function login(email:string){const c=await browser.newContext({baseURL:origin});c.setDefaultTimeout(10000);const page=await c.newPage();await page.goto('/staff/login');await page.getByLabel('メールアドレス',{exact:true}).fill(email);await page.getByLabel('パスワード',{exact:true}).fill(password);await page.getByRole('button',{name:'ログイン',exact:true}).click();await page.waitForURL(origin+'/staff/ledger');await page.close();return c;}
 const admin=await login('s01-root@example.invalid');let serial=0;
 const settings={displayName:'合成S01対象',active:true,role:'STAFF',scope:'ASSIGNED',storeIds:['MOUNTAIN_BASE','ONSEN_BASE'],permissions:{INVENTORY_VIEW:true,INVENTORY_EDIT:true}};
 async function create(data:Record<string,unknown>={}){const email=`s01-${++serial}@example.invalid`;const r=await admin.request.post('/api/staff-users',{headers:{origin},data:{...settings,email,password,...data}});assert.equal(r.status(),201);return {id:(await r.json()).id as string,email};}
 const manager=await create({displayName:'合成S01管理者2',role:'ADMIN',scope:'ALL',permissions:{STAFF_MANAGE:true,INVENTORY_VIEW:true,INVENTORY_EDIT:true,HOLD_VIEW:true,HOLD_EDIT:true,QUOTE_VIEW:true,QUOTE_CREATE:true,PRICE_EDIT:true}});const second=await login(manager.email);
 async function edit(c:BrowserContext,name:string){const p=await c.newPage();await p.goto('/staff/users');await p.getByRole('button',{name:'スタッフを編集：'+name,exact:true}).click();return p;}
 const row=async(id:string)=>(await (await admin.request.get('/api/staff-users')).json()).items.find((x:{id:string})=>x.id===id);
 for(const order of ['root-first','second-first'])for(const mutation of ['disable','permission','store','role'])await check('A stale name-only form cannot restore '+mutation+' '+order,async()=>{
  const name='合成S01 '+mutation+' '+order,t=await create({displayName:name});const a=await edit(order==='root-first'?admin:second,name),b=await edit(order==='root-first'?second:admin,name);
  try{const form=b.getByRole('form',{name:'スタッフ更新'});if(mutation==='disable')await form.getByLabel('有効',{exact:true}).uncheck();if(mutation==='permission')await form.getByLabel('台帳の登録・更新',{exact:true}).selectOption('deny');if(mutation==='store')await form.getByLabel('MOUNTAIN_BASE',{exact:true}).uncheck();if(mutation==='role')await form.getByLabel('Role',{exact:true}).selectOption('VIEWER');
   const saved=b.waitForResponse(r=>r.url().endsWith('/api/staff-users/'+t.id)&&r.request().method()==='PATCH');await form.getByRole('button',{name:'スタッフ設定を保存'}).click();assert.equal((await saved).status(),200);const current=await row(t.id);
   const stale=a.getByRole('form',{name:'スタッフ更新'});await stale.getByLabel('表示名',{exact:true}).fill('合成 名前だけ変更');const response=a.waitForResponse(r=>r.url().endsWith('/api/staff-users/'+t.id)&&r.request().method()==='PATCH');await stale.getByRole('button',{name:'スタッフ設定を保存'}).click();const conflictResponse=await response;console.log('A_CONFLICT '+JSON.stringify(await conflictResponse.json()));assert.equal(conflictResponse.status(),409);assert.deepEqual(await row(t.id),current);
   await expect(a.getByRole('alert').filter({hasText:'別の管理者が更新'})).toContainText('別の管理者が更新');await expect(stale.getByRole('button',{name:'スタッフ設定を保存'})).toBeDisabled();await a.getByRole('button',{name:'最新設定を再読込',exact:true}).click();await expect(a.getByLabel('表示名',{exact:true})).toHaveValue(name);
   await a.getByLabel('表示名',{exact:true}).fill(name+' 再編集');const ok=a.waitForResponse(r=>r.url().endsWith('/api/staff-users/'+t.id)&&r.request().method()==='PATCH');await a.getByRole('button',{name:'スタッフ設定を保存'}).click();const result=await ok;assert.equal(result.status(),200);await expect(a.getByRole('form',{name:'スタッフ更新'})).toHaveCount(0);const committed=await row(t.id);assert.ok(committed.revision>current.revision);assert.equal(committed.displayName,name+' 再編集');
  }finally{await a.close();await b.close();}
 });
 await check('A missing revision is rejected atomically, not accepted as old-client overwrite',async()=>{const t=await create(),before=await row(t.id);const r=await admin.request.patch('/api/staff-users/'+t.id,{headers:{origin},data:{...settings,active:false}});assert.equal(r.status(),422);assert.deepEqual(await row(t.id),before);});
 async function waitLock(user:string,event='advisory'){for(let i=0;i<100;i++){if((await owner.query('SELECT 1 FROM pg_stat_activity WHERE usename=$1 AND wait_event=$2',[user,event])).rowCount)return true;await new Promise(r=>setTimeout(r,5));}return false;}
 for(const mutation of ['permission','store','disable'])await check('B inventory-lock wait observes committed '+mutation+' revocation before update',async()=>{
  const name='合成B '+mutation,t=await create({displayName:name}),actor=await login(t.email),detail=await (await actor.request.get('/api/ledger/assets/'+fid(1201))).json(),lock=await owner.connect();let pending:ReturnType<BrowserContext['request']['patch']>|undefined;
  try{await lock.query('BEGIN');await lock.query('SELECT pg_advisory_xact_lock(71820600)');pending=actor.request.patch('/api/ledger/assets/'+fid(1201),{headers:{origin},data:{version:detail.version,reason:'SYNTHETIC S01 revoked waiting operation',notes:'must not persist'}});assert.equal(await waitLock(app!.roles.ledgerDb.user),true);
   // A normal staff-management form is used so baseline/new API versions receive their own shape.
   const p=await edit(admin,name);try{const f=p.getByRole('form',{name:'スタッフ更新'});if(mutation==='permission')await f.getByLabel('台帳の登録・更新',{exact:true}).selectOption('deny');if(mutation==='store')await f.getByLabel('MOUNTAIN_BASE',{exact:true}).uncheck();if(mutation==='disable')await f.getByLabel('有効',{exact:true}).uncheck();const done=p.waitForResponse(r=>r.url().endsWith('/api/staff-users/'+t.id)&&r.request().method()==='PATCH');await f.getByRole('button',{name:'スタッフ設定を保存'}).click();assert.equal((await done).status(),200);}finally{await p.close();}
  }finally{await lock.query('ROLLBACK');lock.release();}
  assert.ok(pending);assert.equal((await pending).status(),403);assert.equal((await owner.query('SELECT notes FROM ledger_assets WHERE id=$1',[fid(1201)])).rows[0].notes,detail.notes);assert.equal((await owner.query('SELECT count(*)::int AS n FROM ledger_history WHERE actor=$1 AND reason=$2',[t.id,'SYNTHETIC S01 revoked waiting operation'])).rows[0].n,0);await actor.close();
 });

 await check('A invalid/stale versions preserve every field; name-only changes advance settings but login does not',async()=>{
  const t=await create({displayName:'合成A empty access',role:'ADMIN',scope:'ALL',storeIds:[],permissions:{}});const before=await row(t.id),body={displayName:before.displayName,active:before.active,role:before.role,scope:before.scope,storeIds:before.storeIds,permissions:before.permissions};
  for(const version of [null,'1',0,-1,1.2,2147483648]){assert.equal((await admin.request.patch('/api/staff-users/'+t.id,{headers:{origin},data:{...body,active:false,expectedRevision:version}})).status(),422);assert.deepEqual(await row(t.id),before);}
  const changed=await admin.request.patch('/api/staff-users/'+t.id,{headers:{origin},data:{...body,displayName:'合成 名前のみ',expectedRevision:before.revision}});assert.equal(changed.status(),200);const committed=await row(t.id);assert.ok(committed.revision>before.revision);assert.equal((await changed.json()).account.revision,committed.revision);
  assert.equal((await admin.request.patch('/api/staff-users/'+t.id,{headers:{origin},data:{...body,expectedRevision:before.revision}})).status(),409);assert.deepEqual(await row(t.id),committed);
  const c=await login(t.email);await c.close();assert.equal((await row(t.id)).revision,committed.revision);const self=await second.request.patch('/api/staff-users/'+manager.id,{headers:{origin},data:{...body,expectedRevision:(await row(manager.id)).revision}});assert.equal(self.status(),403);
 });
 await check('A actor revocation committed before settings boundary denies target update with no partial audit',async()=>{
  const a=await create({displayName:'合成A操作者',role:'ADMIN',scope:'ALL',storeIds:[],permissions:{STAFF_MANAGE:true}}),c=await login(a.email),target=await create({displayName:'合成A競合対象'}),before=await row(target.id);const lock=await owner.connect();let pending:ReturnType<BrowserContext['request']['patch']>|undefined;
  try{await lock.query('BEGIN');await lock.query('SELECT pg_advisory_xact_lock(71820901,hashtext($1))',[a.id]);await lock.query("UPDATE staff_permission_overrides SET allowed=false WHERE staff_id=$1 AND permission='STAFF_MANAGE'",[a.id]);pending=c.request.patch('/api/staff-users/'+target.id,{headers:{origin},data:{...settings,displayName:'must not persist',active:false,expectedRevision:before.revision}});assert.equal(await waitLock(app!.roles.authDb.user),true);await lock.query('COMMIT');}finally{await lock.query('ROLLBACK');lock.release();}
  assert.equal((await pending!).status(),403);assert.deepEqual(await row(target.id),before);assert.equal((await owner.query('SELECT count(*)::int AS n FROM staff_audit WHERE actor_staff_id=$1 AND target_staff_id=$2',[a.id,target.id])).rows[0].n,0);await c.close();
 });
 const assetInput=(locator:string,storeId='MOUNTAIN_BASE')=>({family:'SKI',variantId:fid(1101),storeId,status:'AVAILABLE',bslStatus:'NOT_APPLICABLE',bslMm:null,bslEvidence:'',notes:'SYNTHETIC',sourceKind:'SYNTHETIC',sourceDocument:'tests/stabilization/s01.ts',sourceLocator:locator});
 for(const mutation of ['permission','store','disable'])await check('B new Asset registration rechecks '+mutation+' after inventory wait',async()=>{
  const t=await create({displayName:'合成B登録 '+mutation}),c=await login(t.email),lock=await owner.connect();let pending:ReturnType<BrowserContext['request']['post']>|undefined;const locator='rejected-'+mutation;
  try{await lock.query('BEGIN');await lock.query('SELECT pg_advisory_xact_lock(71820600)');pending=c.request.post('/api/ledger/assets',{headers:{origin},data:assetInput(locator)});assert.equal(await waitLock(app!.roles.ledgerDb.user),true);const latest=await row(t.id);const value={...settings,...(mutation==='permission'?{permissions:{INVENTORY_VIEW:true,INVENTORY_EDIT:false}}:mutation==='store'?{storeIds:['ONSEN_BASE']}:{active:false}),expectedRevision:latest.revision};assert.equal((await admin.request.patch('/api/staff-users/'+t.id,{headers:{origin},data:value})).status(),200);}finally{await lock.query('ROLLBACK');lock.release();}
  assert.equal((await pending!).status(),403);assert.equal((await owner.query('SELECT count(*)::int AS n FROM ledger_assets WHERE source_document=$1 AND source_locator=$2',['tests/stabilization/s01.ts',locator])).rows[0].n,0);await c.close();
 });
 await check('B target-row wait also precedes final authorization; forbidden store never joins locks',async()=>{
  const t=await create({displayName:'合成B row wait',storeIds:['MOUNTAIN_BASE']}),c=await login(t.email),detail=await (await c.request.get('/api/ledger/assets/'+fid(1202))).json(),lock=await owner.connect();let pending:ReturnType<BrowserContext['request']['patch']>|undefined;
  try{await lock.query('BEGIN');await lock.query('SELECT id FROM ledger_assets WHERE id=$1 FOR UPDATE',[fid(1202)]);const start=Date.now();assert.equal((await c.request.post('/api/ledger/assets',{headers:{origin},data:assetInput('foreign-store','ONSEN_BASE')})).status(),403);assert.ok(Date.now()-start<1000);
   pending=c.request.patch('/api/ledger/assets/'+fid(1202),{headers:{origin},data:{version:detail.version,reason:'SYNTHETIC row wait',notes:'must not persist'}});assert.equal(await waitLock(app!.roles.ledgerDb.user,'transactionid'),true);const latest=await row(t.id);assert.equal((await admin.request.patch('/api/staff-users/'+t.id,{headers:{origin},data:{...settings,permissions:{INVENTORY_VIEW:true,INVENTORY_EDIT:false},expectedRevision:latest.revision}})).status(),200);
  }finally{await lock.query('ROLLBACK');lock.release();}assert.equal((await pending!).status(),403);assert.equal((await owner.query('SELECT notes FROM ledger_assets WHERE id=$1',[fid(1202)])).rows[0].notes,detail.notes);await c.close();
 });
 await check('B write wins first boundary; concurrent revocation waits through ledger commit then takes effect',async()=>{
  const t=await create({displayName:'合成B先行書込み'}),c=await login(t.email),d=await (await c.request.get('/api/ledger/assets/'+fid(1201))).json();
  await owner.query(`CREATE FUNCTION s01_test_commit_gate() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF NEW.reason='SYNTHETIC commit gate' THEN PERFORM pg_advisory_xact_lock(71820902); END IF;RETURN NEW;END$$;CREATE TRIGGER s01_test_commit_gate BEFORE INSERT ON ledger_history FOR EACH ROW EXECUTE FUNCTION s01_test_commit_gate()`);
  const gate=await owner.connect();let write:ReturnType<BrowserContext['request']['patch']>|undefined,revoke:ReturnType<BrowserContext['request']['patch']>|undefined;
  try{await gate.query('BEGIN');await gate.query('SELECT pg_advisory_xact_lock(71820902)');write=c.request.patch('/api/ledger/assets/'+fid(1201),{headers:{origin},data:{version:d.version,reason:'SYNTHETIC commit gate',notes:'SYNTHETIC committed before revoke'}});assert.equal(await waitLock(app!.roles.ledgerDb.user),true);const latest=await row(t.id);revoke=admin.request.patch('/api/staff-users/'+t.id,{headers:{origin},data:{...settings,active:false,expectedRevision:latest.revision}});assert.equal(await waitLock(app!.roles.authDb.user),true);await gate.query('COMMIT');assert.equal((await write).status(),200);assert.equal((await revoke).status(),200);
  }finally{await gate.query('ROLLBACK');gate.release();if(write)await write;if(revoke)await revoke;await owner.query('DROP TRIGGER s01_test_commit_gate ON ledger_history;DROP FUNCTION s01_test_commit_gate()');}
  assert.equal((await owner.query('SELECT notes FROM ledger_assets WHERE id=$1',[fid(1201)])).rows[0].notes,'SYNTHETIC committed before revoke');assert.equal((await c.request.get('/api/ledger/assets')).status(),401);assert.equal((await owner.query("SELECT count(*)::int AS n FROM pg_stat_activity WHERE datname=current_database() AND state='idle in transaction' AND usename<>current_user")).rows[0].n,0);await c.close();
 });
 await check('B normal permitted create/update succeeds; ledger role still cannot read staff or mutate audit',async()=>{
  const t=await create({displayName:'合成B正規'}),c=await login(t.email);const created=await c.request.post('/api/ledger/assets',{headers:{origin},data:assetInput('normal-create')});assert.equal(created.status(),201);const asset=await created.json();const updated=await c.request.patch('/api/ledger/assets/'+asset.id,{headers:{origin},data:{version:asset.version,reason:'SYNTHETIC normal authorized',notes:'saved normally'}});assert.equal(updated.status(),200);assert.equal((await updated.json()).history.at(-1).actor,t.id);await assert.rejects(app!.roles.ledgerPool.query('SELECT id FROM staff_members'),{code:'42501'});await assert.rejects(app!.roles.authPool.query('UPDATE ledger_assets SET notes=notes WHERE false'),{code:'42501'});await assert.rejects(app!.roles.ledgerPool.query('DELETE FROM ledger_history WHERE false'),{code:'42501'});await c.close();
 });
 // Real synthetic IDs:20 people,3 components,6 alternatives/component.
 // 22 units per strict variant allow all20 public members even when matching
 // chooses one variant; this exercises body limits, not alternative-pool scarcity.
 const families=['SKI','SKI_BOOT','POLE'];const alternatives:string[][]=[];
 const seed=await owner.connect();try{await seed.query('BEGIN');await seed.query("SELECT set_config('zao.actor','synthetic-s01-seed',true),set_config('zao.reason','S01 synthetic capacity',true)");for(let f=0;f<3;f++){alternatives[f]=[];for(let j=0;j<6;j++){const id=fid(9000+f*100+j);alternatives[f]!.push(id);await seed.query("INSERT INTO ledger_variants(id,model_id,family,age,tier,size,notes,source_kind,source_document,source_locator) VALUES($1,$2,$3,'ADULT','REGULAR',$4,'','SYNTHETIC','tests/stabilization/s01.ts',$4)",[id,fid(1001+f),families[f],`${f===0?180+j:f===1?30+j:120+j} cm`]);if(f===2)await seed.query("INSERT INTO ledger_poles(id,variant_id,store_id,quantity,status,notes,source_kind,source_document,source_locator) VALUES($1,$2,'MOUNTAIN_BASE',22,'AVAILABLE','','SYNTHETIC','tests/stabilization/s01.ts',$3)",[fid(9500+j),id,'pole-'+j]);else for(let k=0;k<22;k++)await seed.query("INSERT INTO ledger_assets(id,variant_id,family,initial_store_id,store_id,status,bsl_status,bsl_mm,bsl_evidence,notes,source_kind,source_document,source_locator) VALUES($1,$2,$3,'MOUNTAIN_BASE','MOUNTAIN_BASE','AVAILABLE',$4,NULL,'','','SYNTHETIC','tests/stabilization/s01.ts',$5)",[fid(10000+f*1000+j*30+k),id,families[f],f===1?'UNVERIFIED':'NOT_APPLICABLE','asset-'+f+'-'+j+'-'+k]);}}await seed.query('COMMIT');}finally{await seed.query('ROLLBACK');seed.release();}
 const conditions=parseConditions({reservationId:randomUUID(),pickupStore:'MOUNTAIN_BASE',returnStore:'MOUNTAIN_BASE',period:{startDate:'2035-09-20',endDate:'2035-09-20',slot:'DAY'},members:Array.from({length:20},(_,i)=>({key:('member-'+i).padEnd(24,'x'),product:'SKI_SET',age:'ADULT',tier:'REGULAR',items:families.map((family,f)=>({family,variantIds:alternatives[f]}))}))});
 await check('F max normal direct create/amend/availability/quote passes HTTP and actual database',async()=>{
  const data={requestKey:randomUUID(),conditions};console.log('F_BODY_BYTES '+Buffer.byteLength(JSON.stringify(data)));const post=(path:string,data:unknown)=>second.request.post(path,{headers:{origin},data});assert.equal((await post('/api/holds/availability',conditions)).status(),200);const r=await post('/api/holds',data);assert.equal(r.status(),201);const h=await r.json();assert.equal(h.result,'CREATED');const detail=await (await second.request.get('/api/holds/'+h.holdId)).json();assert.equal(detail.conditions.members.length,20);assert.equal((await post('/api/holds/'+h.holdId+'/availability',conditions)).status(),200);const amended=await post('/api/holds/'+h.holdId+'/amend',{requestKey:randomUUID(),conditions,expectedVersion:detail.version});assert.equal(amended.status(),200);assert.equal((await amended.json()).result,'AMENDED');
  assert.equal((await post('/api/quotes/private-initialize',{operation:'initializePrivate',input:{requestKey:randomUUID(),rentalFrom:'2035-01-01',rentalUntil:'2035-12-31'}})).status(),201);const quoteKey=randomUUID(),value={requestKey:quoteKey,input:{conditions,holdId:h.holdId,couponCode:null,wantAdvance:false}};const q=await post('/api/quotes',value);assert.equal(q.status(),201);const result=await q.json();assert.equal(result.quote.chargeReady,false);assert.equal((await post('/api/holds',data)).status(),201);assert.equal((await (await post('/api/quotes',value)).json()).quote.snapshotSha256,result.quote.snapshotSha256);assert.equal((await owner.query('SELECT count(*)::int AS n FROM inventory_claims WHERE hold_id=$1 AND active',[h.holdId])).rows[0].n,60);
 });
 await check('F stream UTF8 finite group cap accepts exact40960 and rejects one byte over',async()=>{const bytes=new TextEncoder().encode(JSON.stringify({note:'雪'}));function req(size:number){const body=new Uint8Array(size);body.fill(32);body.set(bytes);let n=0;return new Request('http://localhost/api/holds',{method:'POST',headers:{'content-type':'application/json'},duplex:'half',body:new ReadableStream({pull(c){if(n===body.length)c.close();else{c.enqueue(body.slice(n,n+137));n=Math.min(body.length,n+137);}}})} as RequestInit);}
  assert.deepEqual(await readJson(req(40960),40960),{note:'雪'});await assert.rejects(readJson(req(40961),40960),{status:413});await assert.rejects(readJson(req(16385)),{status:413});
 });

 await check('F excess body and small-route caps reject before mutation; auth/CSRF order retained',async()=>{
  const large=JSON.stringify({requestKey:randomUUID(),conditions})+' '.repeat(40960),before=(await owner.query('SELECT count(*)::int AS n FROM inventory_holds')).rows[0].n;
  assert.equal((await second.request.post('/api/holds',{headers:{origin,'content-type':'application/json'},data:large})).status(),413);assert.equal((await second.request.post('/api/holds',{headers:{origin:'https://untrusted.invalid','content-type':'application/json'},data:large})).status(),403);
  const anonymous=await browser.newContext({baseURL:origin});assert.equal((await anonymous.request.post('/api/holds',{headers:{origin,'content-type':'application/json'},data:large})).status(),401);await anonymous.close();
  assert.equal((await second.request.post('/api/ledger/assets',{headers:{origin,'content-type':'application/json'},data:' '.repeat(16385)})).status(),413);assert.equal((await second.request.post('/api/auth/sign-in/email',{headers:{origin,'content-type':'application/json'},data:' '.repeat(16385)})).status(),400);
  assert.equal((await second.request.post('/api/holds',{headers:{origin,'content-type':'application/json'},data:'{broken'})).status(),422);assert.equal((await owner.query('SELECT count(*)::int AS n FROM inventory_holds')).rows[0].n,before);
 });
 console.log(`S01 normal authentication/API/PostgreSQL: ${passed} passed; ${failed} failed; 0 skipped.`);
}catch(e){failed++;console.error('S01_SETUP_FAILED '+(e as Error).name+' '+(e as {code?:string}).code+' '+(e as {constraint?:string}).constraint);if(e instanceof assert.AssertionError)console.error(JSON.stringify({actual:e.actual,expected:e.expected}));console.error((e as Error).stack?.split('\n').filter(l=>l.includes('/tests/stabilization/s01.ts:')).join('\n'));}finally{await browser.close();if(app)await app.stop();console.log('Owned S01 Web/browser/PostgreSQL stopped.');}if(failed)process.exit(1);
