"""Deterministically derives PROVISIONAL_SOURCE_A_CAPACITY.csv from the already-committed,
already-reviewed docs/execution/launch-critical-m2b/PROVISIONAL_CATALOG_MAPPING.csv (Source A's
own real-catalog extraction, generated by provisional-inventory.py from the Owner-supplied
workbook, SHA256-verified there).

This is a normalization pass, not a new data source: it groups the existing per-model,
per-source-row candidate_size figures into per (family, age, booking_size) capacity buckets, in
the same shape PROVISIONAL_SOURCE_B_CAPACITY.csv already uses, so provisional_capacity_buckets
can be seeded with real per-size breakdown instead of one synthetic aggregate bucket per family.

Only the four Owner-approved asset-backed families (SKI, SNOWBOARD, SKI_BOOT, SNOWBOARD_BOOT) are
included — Source A has zero WEAR_JACKET/WEAR_PANTS rows (see PROVISIONAL_SOURCE_B_AUDIT.md's
cross-check table), and POLE/HELMET/SNOWBOARD_BINDING remain EXCLUDED_BY_OWNER_SCOPE, identically
to the real-import pipeline's own scope decision for this same source.

candidate_size for SKI/SNOWBOARD is the already cross-checked length (name vs. item-code suffix,
see provisional-inventory.py's ski_size()), for SKI_BOOT/SNOWBOARD_BOOT it is the source
workbook's own JP size column, read verbatim, never invented. Every row here is MAPPED: this data
was already reviewed as part of the real-inventory catalogue mapping, unlike Source B's aggregated
X-token boot buckets, which retain no per-model identity and are therefore left
BOOKING_SIZE_MAPPING_REQUIRED (see RESULT.md's disclosed finding on why that cannot be resolved
from the data this repository actually has).
"""
import csv, collections, sys

IN_SCOPE_FAMILIES = {'SKI': 'ASSET_PAIR', 'SNOWBOARD': 'ASSET_BOARD', 'SKI_BOOT': 'ASSET_PAIR', 'SNOWBOARD_BOOT': 'ASSET_PAIR'}


def main(mapping_path, out_path):
    totals = collections.Counter()
    buckets = collections.OrderedDict()  # (family, age, size) -> {quantity, rows}
    with open(mapping_path, newline='', encoding='utf8') as fh:
        for row in csv.DictReader(fh):
            family = row['mapped_family']
            if family not in IN_SCOPE_FAMILIES or row['owner_scope'] != 'IN_SCOPE':
                continue
            size = row['candidate_size'].strip()
            if not size:
                sys.exit(f"SOURCE_A_SIZE_MISSING row={row['source_row']} family={family}")
            quantity = int(row['quantity'])
            key = (family, row['age'], size)
            b = buckets.setdefault(key, {'quantity': 0, 'rows': []})
            b['quantity'] += quantity
            b['rows'].append(row['source_row'])
            totals[family] += quantity

    with open(out_path, 'w', newline='', encoding='utf8') as fh:
        w = csv.writer(fh, lineterminator='\n')
        w.writerow(['source', 'family', 'age', 'source_size', 'booking_size', 'size_mapping_status', 'quantity', 'unit_note', 'provenance'])
        for (family, age, size), b in buckets.items():
            provenance = f"PROVISIONAL_CATALOG_MAPPING.csv rows {','.join(b['rows'])}"
            w.writerow(['SOURCE_A', family, age, size, size, 'MAPPED', b['quantity'], IN_SCOPE_FAMILIES[family], provenance])

    for family in IN_SCOPE_FAMILIES:
        print(family, totals[family])
    print('SOURCE_A_TOTAL', sum(totals.values()))
    print('buckets', len(buckets))


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
