import assert from 'node:assert/strict';
import {chromium,expect,type Page} from '@playwright/test';
import QRCode from 'qrcode';
import jsQR from 'jsqr';
import {startFlowApp} from './launcher';
let stage='startup',passed=0,failed=false,last:Page|undefined;const browser=await chromium.launch();let app:Awaited<ReturnType<typeof startFlowApp>>|undefined;
const a='00000000-0000-4000-8000-000000001201',b='00000000-0000-4000-8000-000000001202';
async function check(name:string,fn:()=>Promise<void>){stage=name;await fn();passed++;console.log('PASS '+name);}
try{
 app=await startFlowApp();for(let i=0;i<100;i++){try{if((await fetch(app.origin+'/api/health')).ok)break;}catch{}if(i===99)throw new Error('APP_START_TIMEOUT');await new Promise(r=>setTimeout(r,100));}
 const context=await browser.newContext({baseURL:app.origin,viewport:{width:390,height:844},hasTouch:true});context.setDefaultTimeout(15000);
 // tsx names nested callbacks; helper belongs only to the browser test harness.
 await context.addInitScript('window.__name = (fn) => fn');
 async function page(){const p=await context.newPage();p.on('pageerror',e=>console.error('SYNTHETIC_PAGE_ERROR '+e.message));last=p;await p.goto('/test-asset-reader');await expect(p.getByRole('button',{name:'カメラを開く'})).toBeEnabled();return p;}
 await check('manual input rejects reservation QR and partial identities; one whole Asset callback only',async()=>{const p=await page();for(const invalid of ['zao-rental:reservation:'+a,a+'-left','unknown']){await p.getByLabel('用品の個体ID').fill(invalid);await p.getByRole('button',{name:'入力したIDを照合へ送る'}).click();await expect(p.getByRole('region',{name:'用品QR入力'}).getByRole('status')).toContainText('用品の個体ID');await expect(p.getByLabel('検出ID一覧')).toHaveText('');}await p.getByLabel('用品の個体ID').fill(a);await p.getByRole('button',{name:'入力したIDを照合へ送る'}).click();await expect(p.getByLabel('検出ID一覧')).toHaveText(a);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.close();});
 async function camera(p:Page,deferred=false){await p.evaluate(({deferred})=>{
  const canvas=document.createElement('canvas');canvas.width=360;canvas.height=360;canvas.getContext('2d')!.fillRect(0,0,360,360);const media=canvas.captureStream(0);
  const state={canvas,media,requests:0,release:()=>{}};(window as unknown as {syntheticCamera:typeof state}).syntheticCamera=state;
  Object.defineProperty(navigator.mediaDevices,'getUserMedia',{configurable:true,value:async()=>{state.requests++;if(deferred)await new Promise<void>(r=>{state.release=r;});return media;}});
 },{deferred});}
 async function draw(p:Page,id:string){const data=await QRCode.toDataURL(id,{width:360,margin:4});await p.evaluate(async data=>{const w=window as unknown as {syntheticCamera:{canvas:HTMLCanvasElement;media:MediaStream}};const i=new Image();i.src=data;await i.decode();w.syntheticCamera.canvas.getContext('2d')!.drawImage(i,0,0,360,360);(w.syntheticCamera.media.getVideoTracks()[0] as CanvasCaptureMediaStreamTrack).requestFrame();},data);}
 const tracks=(p:Page)=>p.evaluate(()=>(window as unknown as {syntheticCamera:{media:MediaStream}}).syntheticCamera.media.getTracks().map(t=>t.readyState));
 await check('synthetic camera frames continuously decode different Assets; duplicate same frame is suppressed; explicit stop releases tracks',async()=>{const p=await page();await camera(p);await p.getByRole('button',{name:'カメラを開く'}).click();await draw(p,a);await expect(p.getByLabel('検出ID一覧')).toHaveText(a);await draw(p,b);await expect(p.getByLabel('検出ID一覧')).toHaveText(a+','+b);assert.equal(await p.evaluate(()=>(window as unknown as {syntheticCamera:{requests:number}}).syntheticCamera.requests),1);await p.getByRole('button',{name:'カメラを止める'}).click();assert.deepEqual(await tracks(p),['ended']);await p.close();});
 await check('unmount while camera permission is pending stops the late stream without rendering or callbacks',async()=>{const p=await page();await camera(p,true);await p.getByRole('button',{name:'カメラを開く'}).click();await expect(p.getByRole('region',{name:'用品QR入力'}).getByRole('status')).toContainText('許可を待っています');await p.getByRole('button',{name:'入力部品を閉じる'}).click();await p.evaluate(()=>(window as unknown as {syntheticCamera:{release:()=>void}}).syntheticCamera.release());await expect.poll(()=>tracks(p)).toEqual(['ended']);await expect(p.getByLabel('検出ID一覧')).toHaveText('');await p.close();});
 await check('unmount of an active camera releases this component tracks',async()=>{const p=await page();await camera(p);await p.getByRole('button',{name:'カメラを開く'}).click();await draw(p,a);await expect(p.getByLabel('検出ID一覧')).toHaveText(a);await p.getByRole('button',{name:'入力部品を閉じる'}).click();await expect.poll(()=>tracks(p)).toEqual(['ended']);await p.close();});
 await check('permission denial and missing camera preserve manual fallback without fake acknowledgement',async()=>{for(const name of ['NotAllowedError','NotFoundError']){const p=await page();await p.evaluate(name=>Object.defineProperty(navigator.mediaDevices,'getUserMedia',{configurable:true,value:async()=>{throw new DOMException('synthetic',name);}}),name);await p.getByRole('button',{name:'カメラを開く'}).click();await expect(p.getByRole('region',{name:'用品QR入力'}).getByRole('status')).toContainText(name==='NotAllowedError'?'許可がありません':'見つかりません');await expect(p.getByLabel('検出ID一覧')).toHaveText('');await expect(p.getByLabel('用品の個体ID')).toBeEnabled();await p.close();}});
 await check('offline stops owned camera; reconnect never auto-acknowledges or restarts; touch width matrix',async()=>{const p=await page();await camera(p);await p.getByRole('button',{name:'カメラを開く'}).click();await draw(p,a);await expect(p.getByLabel('検出ID一覧')).toHaveText(a);await context.setOffline(true);await expect.poll(()=>tracks(p)).toEqual(['ended']);await expect(p.getByRole('button',{name:'カメラを開く'})).toBeDisabled();await context.setOffline(false);await expect(p.getByRole('button',{name:'カメラを開く'})).toBeEnabled();await expect(p.getByLabel('検出ID一覧')).toHaveText(a);for(const button of await p.getByRole('region',{name:'用品QR入力'}).getByRole('button').all())assert.ok((await button.boundingBox())!.height>=44);for(const width of [320,360,390,430,768,1024]){await p.setViewportSize({width,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}await p.close();});
 await check('slow camera lookup exposes pending state, suppresses repeat callbacks and does not claim saved before acknowledgement',async()=>{const p=await page();await p.getByLabel('合成照合応答を保留').check();await camera(p);await p.getByRole('button',{name:'カメラを開く'}).tap();await draw(p,a);await expect(p.getByLabel('合成照合開始数')).toHaveText('1');await expect(p.getByRole('region',{name:'用品QR入力'}).getByRole('status')).toContainText('まだ確認できません');await draw(p,b);await expect(p.getByLabel('検出ID一覧')).toHaveText('');await expect(p.getByRole('button',{name:'入力したIDを照合へ送る'})).toBeDisabled();await p.getByRole('button',{name:'合成応答を完了'}).click();await expect(p.getByLabel('検出ID一覧')).toContainText(a);await p.getByRole('button',{name:'カメラを止める'}).tap();assert.deepEqual(await tracks(p),['ended']);await p.close();});
 await check('reload clears unacknowledged input fixture without inventing a saved return or auto-starting camera',async()=>{const p=await page();await p.getByLabel('合成照合応答を保留').check();await p.getByLabel('用品の個体ID').fill(a);await p.getByRole('button',{name:'入力したIDを照合へ送る'}).tap();await expect(p.getByLabel('合成照合開始数')).toHaveText('1');await p.reload();await expect(p.getByLabel('検出ID一覧')).toHaveText('');await expect(p.getByLabel('合成照合開始数')).toHaveText('0');await expect(p.getByRole('button',{name:'カメラを止める'})).toBeDisabled();await p.close();});
 console.log(`Asset QR component: ${passed} passed, 0 skipped. Synthetic canvas MediaStream only; no physical phone/camera and no receipt mutation.`);
}catch(e){console.error('ASSET_READER_FAILED '+stage+' '+(e as Error).message);if(last)console.error('CAMERA_DIAGNOSTIC '+JSON.stringify(await last.evaluate(()=>({video:Array.from(document.querySelectorAll('video')).map(v=>({ready:v.readyState,width:v.videoWidth,height:v.videoHeight,paused:v.paused,hidden:v.hidden,stream:(v.srcObject as MediaStream|null)?.active})),status:document.querySelector('[role=status]')?.textContent})).catch(()=>null)));if(last){const pixels=await last.evaluate(()=>{const v=document.querySelector('video');if(!v)return null;const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;if(!c.width)return null;const x=c.getContext('2d')!;x.drawImage(v,0,0);return {w:c.width,h:c.height,data:Array.from(x.getImageData(0,0,c.width,c.height).data)};}).catch(()=>null);if(pixels)console.error('VIDEO_QR_DECODE '+jsQR(new Uint8ClampedArray(pixels.data),pixels.w,pixels.h)?.data);}if(e instanceof assert.AssertionError)console.error(JSON.stringify({actual:e.actual,expected:e.expected}));failed=true;}finally{await browser.close();await app?.stop();console.log('Owned QR test Web/browser/PostgreSQL stopped.');}

if(failed)process.exit(1);
