import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
import {mkdir} from 'node:fs/promises';
import {chromium,expect,type BrowserContext,type Page} from '@playwright/test';
import jsQR from 'jsqr';
import {startFlowApp} from './launcher';
import {bootstrapDevelopmentAdmin} from '../../scripts/bootstrap-staff';
import {seedRecommendation,variants} from '../recommendation/fixture';
let stage='startup',count=0,failed=false;const browser=await chromium.launch(),password=randomBytes(24).toString('base64url');let app:Awaited<ReturnType<typeof startFlowApp>>|undefined;let last:Page|undefined;
async function check(name:string,fn:()=>Promise<void>){stage=name;await fn();count++;console.log('PASS '+name);}
try{app=await startFlowApp();await seedRecommendation(app.db.pool);await bootstrapDevelopmentAdmin(app.db.pool,{email:'flow-ui-root@example.invalid',displayName:'SYNTHETIC Root',password});const {origin}=app;await app.db.pool.query("CREATE OR REPLACE FUNCTION inventory_clock() RETURNS timestamptz LANGUAGE sql VOLATILE AS $$SELECT '2035-01-01T01:00:00Z'::timestamptz$$");
 for(let i=0;i<100;i++){try{if((await fetch(origin+'/api/health')).ok)break;}catch{}if(i===99)throw new Error('APP_START_TIMEOUT');await new Promise(r=>setTimeout(r,100));}
 async function context(){const c=await browser.newContext({baseURL:origin,viewport:{width:1280,height:960}});c.setDefaultTimeout(15000);return c;}
 async function login(c:BrowserContext,email:string){const p=await c.newPage();await p.goto('/staff/login');await p.getByLabel('メールアドレス',{exact:true}).fill(email);await p.getByLabel('パスワード',{exact:true}).fill(password);await p.getByRole('button',{name:'ログイン',exact:true}).click();await p.waitForURL(origin+'/staff/ledger');return p;}
 const root=await context(),staff=await context(),anon=await context();const rootPage=await login(root,'flow-ui-root@example.invalid');
 await check('ordinary ADMIN grants synthetic creator minimum explicit permissions; anonymous/private boundaries stay closed',async()=>{assert.equal((await anon.request.get('/api/bookings')).status(),401);assert.equal((await root.request.get('/api/bookings/capabilities')).status(),403);const r=await root.request.post('/api/staff-users',{headers:{origin},data:{email:'flow-ui-creator@example.invalid',password,displayName:'SYNTHETIC Creator',active:true,role:'ADMIN',scope:'ALL',storeIds:[],permissions:{BOOKING_VIEW:true,BOOKING_CREATE:true,HOLD_VIEW:true,HOLD_EDIT:true,QUOTE_VIEW:true,QUOTE_CREATE:true,PRICE_EDIT:true}}});assert.equal(r.status(),201);});
 await check('administrator form preserves explicit booking permissions and grants/revokes rental choices without role defaults',async()=>{
  await rootPage.goto('/staff/users');await rootPage.getByRole('button',{name:'スタッフを編集：SYNTHETIC Creator'}).click();await expect(rootPage.getByLabel('開発予約の閲覧')).toHaveValue('allow');await expect(rootPage.getByLabel('開発用受付・貸出')).toHaveValue('default');
  await rootPage.getByLabel('開発用受付・貸出').selectOption('allow');await rootPage.getByLabel('開発用返却・検品').selectOption('allow');await rootPage.getByRole('button',{name:'スタッフ設定を保存'}).click();await expect(rootPage.getByRole('form',{name:'スタッフ更新'})).toHaveCount(0);
  await rootPage.getByRole('button',{name:'スタッフを編集：SYNTHETIC Creator'}).click();await expect(rootPage.getByLabel('開発予約の作成')).toHaveValue('allow');await expect(rootPage.getByLabel('開発用返却・検品')).toHaveValue('allow');await rootPage.getByLabel('開発用返却・検品').selectOption('deny');await rootPage.getByRole('button',{name:'スタッフ設定を保存'}).click();await expect(rootPage.getByRole('form',{name:'スタッフ更新'})).toHaveCount(0);
  const row={permissions:Object.fromEntries((await app!.db.pool.query("SELECT permission,allowed FROM staff_permission_overrides WHERE staff_id=(SELECT id FROM staff_users WHERE email='flow-ui-creator@example.invalid')")).rows.map(r=>[r.permission,r.allowed]))};assert.equal(row.permissions.BOOKING_VIEW,true);assert.equal(row.permissions.RENTAL_CHECKOUT,true);assert.equal(row.permissions.RENTAL_RETURN,false);assert.equal((await app!.db.pool.query("SELECT count(*)::int n FROM staff_role_permissions WHERE permission LIKE 'RENTAL_%' OR permission LIKE 'BOOKING_%'")).rows[0].n,0);
 });
 const page=await login(staff,'flow-ui-creator@example.invalid');last=page;page.on('response',r=>{if(r.status()>=400||new URL(r.url()).pathname.includes('sign-out'))console.log('HTTP_STATUS '+r.status()+' '+new URL(r.url()).pathname);});await page.goto('/staff/quotes');await page.getByLabel('料金の対象開始日').fill('2035-01-01');await page.getByLabel('料金の対象終了日').fill('2035-12-31');await page.getByRole('button',{name:'開発用の初期料金を設定'}).click();await expect(page.getByRole('region',{name:'料金版',exact:true})).toContainText('PRIVATE_AVAILABLE');
 const optionsResponse=await staff.request.get('/api/recommendations/options');console.log('OPTIONS_HTTP '+optionsResponse.status());const optionsData=await optionsResponse.json();assert.ok(optionsData.variants.some((v:{id:string})=>v.id===variants.pole));assert.equal(optionsResponse.status(),200);assert.equal((await staff.request.get('/staff/logout')).status(),200);
 async function profile(p:Page,i:number,sport:string){await p.getByLabel('競技 '+i,{exact:true}).selectOption(sport);await p.getByLabel('利用開始時の年齢区分 '+i,{exact:true}).selectOption('ADULT');await p.getByLabel('身長cm '+i,{exact:true}).fill('170');await p.getByLabel('足サイズcm '+i,{exact:true}).fill('25.5');if(sport==='SKI'){await p.getByLabel('体重kg '+i,{exact:true}).fill('60');await p.getByLabel('利用開始時の年齢 '+i,{exact:true}).fill('30');await p.getByLabel('レベル '+i,{exact:true}).selectOption('BEGINNER');await p.getByLabel('ポールのサイズ '+i,{exact:true}).selectOption(variants.pole);}}
 let bookingId='',quoteId='',holdId='',originalTTL='';
 await check('normal two-person UI -> recommendations -> explicit choice -> full HOLD/quote -> synthetic contact saved in real DB',async()=>{await page.goto('/staff/recommendations');await page.getByLabel('利用開始日',{exact:true}).fill('2035-01-05');await page.getByLabel('利用終了日',{exact:true}).fill('2035-01-05');await profile(page,1,'SKI');await page.getByRole('button',{name:'利用者を追加',exact:true}).click();await profile(page,2,'SNOWBOARD');await page.getByRole('button',{name:'推薦候補を確認',exact:true}).click();for(const i of [1,2])await page.getByRole('button',{name:'おすすめを選ぶ '+i,exact:true}).click();await page.getByLabel('モデル指定なし・表示したサイズとクラスを選択条件とすることを確認').check();await page.getByRole('button',{name:'全員分をHOLDして見積を保存',exact:true}).click();await expect(page.getByRole('region',{name:'見積詳細',exact:true})).toBeVisible();await page.getByRole('link',{name:'非公開の合成予約プレビューへ'}).click();await expect(page.getByRole('heading',{name:'予約情報と決済照合'})).toBeVisible();quoteId=await page.getByLabel('保存済み見積ID').inputValue();await page.getByLabel('合成氏名').fill('SYNTHETIC Mixed Group');await page.getByLabel('架空メール宛先').fill('synthetic-mixed@example.invalid');await page.getByLabel('開発用の合成予約であり、営業規約・請求の確定ではないことを確認').check();await page.getByRole('button',{name:'合成予約情報を保存',exact:true}).click();await expect(page.getByRole('region',{name:'開発予約詳細'})).toContainText('DRAFT');const row=(await app!.db.pool.query('SELECT b.id,b.hold_id,h.expires_at FROM rental_bookings b JOIN inventory_holds h ON h.id=b.hold_id WHERE quote_id=$1',[quoteId])).rows[0];bookingId=row.id;holdId=row.hold_id;originalTTL=row.expires_at.toISOString();assert.equal((await app!.db.pool.query('SELECT count(*)::int n FROM inventory_claims WHERE hold_id=$1 AND active',[holdId])).rows[0].n,5);});
 await check('simulated payment response loss -> reload -> same request -> one confirmation/notification and readable opaque QR',async()=>{await page.route('**/api/bookings/*/payment',async route=>{const r=await route.fetch();assert.equal(r.status(),200);assert.equal((await r.json()).state,'CONFIRMED_DEV');await route.abort('failed');});await page.getByRole('button',{name:'テストアダプタへ照合要求'}).click();await expect(page.getByRole('button',{name:'同じ保存済み要求を照合'})).toBeVisible();await page.unroute('**/api/bookings/*/payment');await page.reload();await page.getByRole('button',{name:'同じ保存済み要求を照合'}).click();await expect(page.getByRole('region',{name:'開発予約詳細'})).toContainText('CONFIRMED_DEV');await expect(page.getByLabel('開発予約QR')).toBeVisible();const pixels=await page.getByLabel('開発予約QR').evaluate((node)=>{const c=node as HTMLCanvasElement;return {width:c.width,height:c.height,data:Array.from(c.getContext('2d')!.getImageData(0,0,c.width,c.height).data)};});const result=jsQR(new Uint8ClampedArray(pixels.data),pixels.width,pixels.height);assert.equal(result?.data,'zao-rental:reservation:'+bookingId);assert.equal((await app!.db.pool.query('SELECT count(*)::int n FROM rental_payment_attempts WHERE booking_id=$1',[bookingId])).rows[0].n,1);assert.equal((await app!.db.pool.query('SELECT count(*)::int n FROM rental_notifications WHERE booking_id=$1',[bookingId])).rows[0].n,1);assert.equal((await app!.db.pool.query('SELECT expires_at FROM inventory_holds WHERE id=$1',[holdId])).rows[0].expires_at.toISOString(),originalTTL);await mkdir('.local/screenshots',{recursive:true});await page.screenshot({path:'.local/screenshots/flow-booking-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'.local/screenshots/flow-booking-mobile-width.png',fullPage:true});});
 await check('client paid/amount/actor flags, CSRF, foreign quote and real contact cannot create authority',async()=>{const body={requestKey:randomUUID(),quoteId,contact:{displayName:'SYNTHETIC Other',email:'synthetic-other@example.invalid',termsAccepted:true}};assert.equal((await staff.request.post('/api/bookings',{data:body})).status(),403);assert.equal((await staff.request.post('/api/bookings',{headers:{origin},data:{...body,paid:true}})).status(),422);for(const input of [{...body,contact:{...body.contact,email:'person@example.com'}},{...body,totalJpy:1},{...body,actor:'owner'}])assert.equal((await staff.request.post('/api/bookings',{headers:{origin},data:input})).status(),422);assert.equal((await staff.request.post('/api/bookings/'+bookingId+'/payment',{headers:{origin},data:{requestKey:randomUUID(),paid:true}})).status(),422);assert.equal((await anon.request.get('/api/bookings/'+bookingId)).status(),401);});
 await check('logout/relogin reloads same DB confirmation; different unprivileged account sees no previous cache',async()=>{await page.getByRole('link',{name:'ログアウト',exact:true}).click();await expect.poll(()=>page.getByRole('button',{name:'ログアウトする',exact:true}).evaluate((b)=>typeof (b as HTMLButtonElement).onclick)).toBe('function');await page.getByRole('button',{name:'ログアウトする',exact:true}).click();await page.waitForURL(origin+'/staff/login');assert.equal((await staff.request.get('/api/bookings')).status(),401);const back=await login(staff,'flow-ui-creator@example.invalid');await back.goto('/preview/rental');await back.getByRole('button',{name:/SYNTHETIC Mixed Group.*CONFIRMED_DEV/}).click();await expect(back.getByRole('region',{name:'開発予約詳細'})).toContainText(bookingId);await back.getByRole('link',{name:'ログアウト',exact:true}).click();await expect.poll(()=>back.getByRole('button',{name:'ログアウトする',exact:true}).evaluate((b)=>typeof (b as HTMLButtonElement).onclick)).toBe('function');await back.getByRole('button',{name:'ログアウトする',exact:true}).click();await back.waitForURL(origin+'/staff/login');const other=await login(staff,'flow-ui-root@example.invalid');await other.goto('/preview/rental');await expect(other.getByRole('heading',{name:'非公開の予約プレビュー'})).toBeVisible();await expect(other.getByText('SYNTHETIC Mixed Group',{exact:true})).toHaveCount(0);});
 console.log(`FLOW ordinary UI/API/PostgreSQL: ${count} passed, 0 skipped. Test-only payment composition. Canvas QR decoded, no real phone/camera. Rental/return writes blocked, not tested.`);
}catch(e){failed=true;console.error('FLOW_UI_FAILED '+stage+' '+(e as Error).name);if(e instanceof assert.AssertionError)console.error(JSON.stringify({actual:e.actual,expected:e.expected}));console.error((e as Error).stack?.split('\n').filter(l=>l.includes('/tests/flow/')).join('\n'));if(last){console.error('LAST_PAGE '+new URL(last.url()).pathname);console.error('ALERT '+await last.getByRole('alert').textContent().catch(()=>''));}if(last&&new URL(last.url()).pathname==='/staff/recommendations'){console.error('SELECT_OPTIONS '+JSON.stringify(await last.locator('select').evaluateAll(es=>es.map(e=>({label:e.getAttribute('aria-label'),options:Array.from((e as HTMLSelectElement).options).map(o=>({text:o.text,value:o.value}))})))));console.error('UI_STATUS '+await last.getByRole('status').textContent().catch(()=>''));}}finally{await browser.close();if(app)await app.stop();console.log('Owned FLOW Web, browser, PostgreSQL stopped.');}if(failed)process.exit(1);
