import assert from 'node:assert/strict';
import {randomUUID,createHmac} from 'node:crypto';
import {flowFixture,simulation} from './fixture';
import {requestFor,variants} from '../inventory/fixture';
import {writeAccount} from '../../packages/auth/src/accounts';
import {BookingService} from '../../packages/core/src/payment/booking-service';
import {flowHash,reservationQr,parseReservationQr} from '../../packages/contracts/src/rental-flow';
import {parseVerifiedSquareWebhook,squareObservation,verifySquareWebhook} from '../../packages/core/src/payment/square-boundary';
let stage='startup',passed=0;const x=await flowFixture();async function check(name:string,fn:()=>Promise<void>){stage=name;await fn();passed++;console.log('PASS '+name);}
try{
 await check('ordinary password login gives real expiring session; production composition has no payment adapter',async()=>{await assert.rejects(new BookingService(x.flow.flowPool,x.roles.authPool,x.signed.identity).create(randomUUID(),randomUUID(),{displayName:'SYNTHETIC Guest',email:'synthetic-g@example.invalid',termsAccepted:true}),{code:'PAYMENT_NOT_CONNECTED_CHARGE_DISABLED'});assert.throws(()=>new BookingService(x.flow.flowPool,x.roles.authPool,x.signed.identity,x.fake,{...simulation,nodeEnv:'production'}),{code:'SIMULATION_FORBIDDEN'});const testEnv:Record<string,string|undefined>=process.env;const priorEnv=testEnv.NODE_ENV;try{testEnv.NODE_ENV='production';assert.throws(()=>new BookingService(x.flow.flowPool,x.roles.authPool,x.signed.identity,x.fake,simulation),{code:'SIMULATION_FORBIDDEN'});}finally{if(priorEnv===undefined)delete testEnv.NODE_ENV;else testEnv.NODE_ENV=priorEnv;}await assert.rejects(new BookingService(x.flow.flowPool,x.roles.authPool,{...x.signed.identity,sessionId:randomUUID()},x.fake,simulation).list(),{code:'UNAUTHENTICATED'});});
 const a=await x.draft();const ttl=(await x.holds.get(a.holdId)).expiresAt;
 await check('quote/HOLD/contact -> immutable synthetic booking; replay and concurrent payment create exactly once',async()=>{assert.equal((await x.service.create(a.key,a.quote.id,a.contact)).id,a.booking.id);const before=x.fake.calls.length,key=randomUUID();const results=await Promise.all([x.service.startPayment(a.booking.id,key),x.service.startPayment(a.booking.id,key)]);assert.ok(results.some(r=>r.state==='CONFIRMED_DEV'));assert.equal(x.fake.calls.length-before,1);const saved=await x.service.get(a.booking.id);assert.equal(saved.state,'CONFIRMED_DEV');assert.equal(saved.chargeReady,false);assert.equal(saved.priceSha256,a.quote.snapshotSha256);assert.deepEqual(saved.priceSnapshot,a.quote.snapshot);assert.equal(parseReservationQr(saved.qr),a.booking.id);assert.ok(!reservationQr(a.booking.id).includes('Guest'));assert.equal((await x.db.pool.query('SELECT count(*)::int n FROM rental_notifications')).rows[0].n,1);});
 await check('confirmation protects claims after original 10 minute TTL without extending it or changing price snapshot',async()=>{await x.clock('2035-01-01T10:11:00+09:00');assert.equal((await x.holds.get(a.holdId)).state,'ACTIVE');assert.equal((await x.holds.get(a.holdId)).expiresAt,ttl);assert.equal((await x.service.get(a.booking.id)).priceSha256,flowHash(a.quote.snapshot));assert.equal((await x.db.pool.query('SELECT count(*)::int n FROM inventory_claims WHERE hold_id=$1 AND active',[a.holdId])).rows[0].n,3);});
 await check('UNKNOWN response loss persists same key and never creates again with another key; lookup recovers once',async()=>{const d=await x.draft();x.fake.failAfterSave=true;const before=x.fake.calls.length;const unknown=await x.service.startPayment(d.booking.id,randomUUID());assert.equal(unknown.payments[0].state,'UNKNOWN');assert.equal(unknown.state,'PAYMENT_PENDING');await x.service.startPayment(d.booking.id,randomUUID());assert.equal(x.fake.calls.length,before+1);const r=await x.service.reconcile(d.booking.id);assert.equal(r.state,'CONFIRMED_DEV');assert.equal((await x.service.reconcile(d.booking.id)).state,'CONFIRMED_DEV');assert.equal(x.fake.calls.length,before+1);x.fake.failAfterSave=false;});
 await check('late successful response after TTL is PAYMENT_REVIEW, never resurrects claims or confirms overbooking',async()=>{const d=await x.draft();x.fake.status='PENDING';await x.service.startPayment(d.booking.id,randomUUID());const req=x.fake.calls.at(-1)!;await x.clock('2035-01-01T10:22:00+09:00');const o={...x.fake.receipts.get(req.attemptId)!,status:'COMPLETED' as const,updatedAt:x.now().toISOString(),completedAt:x.now().toISOString()};x.fake.receipts.set(req.attemptId,o);const result=await x.service.reconcile(d.booking.id);assert.equal(result.state,'PAYMENT_REVIEW');assert.equal(result.qr,null);assert.equal((await x.holds.get(d.holdId)).expiresAt,new Date('2035-01-01T10:21:00+09:00').toISOString());assert.equal((await x.db.pool.query('SELECT confirmed_at FROM inventory_holds WHERE id=$1',[d.holdId])).rows[0].confirmed_at,null);x.fake.status='COMPLETED';});
 for(const [field,value]of Object.entries({referenceId:randomUUID(),merchantId:'foreign',locationId:'foreign',amountJpy:1,currency:'USD',idempotencyKey:randomUUID()}))await check('verified '+field+' mismatch cannot confirm',async()=>{x.fake.patch={[field]:value};const d=await x.draft();const result=await x.service.startPayment(d.booking.id,randomUUID());assert.equal(result.state,'PAYMENT_REVIEW');assert.equal(result.qr,null);x.fake.patch={};});
 await check('duplicate event payload is stable; terminal completion ignores delayed pending/failed notifications',async()=>{const req=x.fake.calls[0]!,o=x.fake.receipts.get(req.attemptId)!;await x.service.recordObservation(a.booking.id,req.attemptId,'test-same',o);await x.service.recordObservation(a.booking.id,req.attemptId,'test-same',o);await assert.rejects(x.service.recordObservation(a.booking.id,req.attemptId,'test-same',{...o,amountJpy:1}),{code:'EVENT_ID_CONFLICT'});for(const status of ['PENDING','FAILED'] as const)await x.service.recordObservation(a.booking.id,req.attemptId,'late-'+status,{...o,status,completedAt:null,updatedAt:x.now().toISOString()});assert.equal((await x.service.get(a.booking.id)).state,'CONFIRMED_DEV');assert.equal((await x.holds.get(a.holdId)).paymentState,'SUCCESS');assert.equal((await x.db.pool.query('SELECT count(*)::int n FROM rental_notifications WHERE booking_id=$1',[a.booking.id])).rows[0].n,1);});
 await check('real raw signature rejects modified body/URL, malformed events; capture time is not generic updated_at',async()=>{const raw=Buffer.from(JSON.stringify({event_id:'synthetic-event',merchant_id:'SYNTHETIC-MERCHANT',type:'payment.updated',data:{object:{payment:{id:'sim_payment'}}}})),url='https://example.invalid/test-webhook',key='SYNTHETIC-NONSECRET-TEST-KEY',sig=createHmac('sha256',key).update(url).update(raw).digest('base64');assert.equal(parseVerifiedSquareWebhook(raw,sig,url,key).paymentId,'sim_payment');assert.equal(verifySquareWebhook(Buffer.concat([raw,Buffer.from(' ')]),sig,url,key),false);assert.equal(verifySquareWebhook(raw,sig,url+'/changed',key),false);assert.equal(verifySquareWebhook(raw,undefined,url,key),false);const req=x.fake.calls[0]!;const data={id:'sim_payment',reference_id:req.bookingId,location_id:req.locationId,amount_money:{amount:req.amountJpy,currency:'JPY'},status:'COMPLETED',updated_at:'2035-01-01T02:00:00Z',card_details:{card_payment_timeline:{captured_at:'2035-01-01T01:00:00Z'}}};assert.equal(squareObservation(data,req,req.merchantId).completedAt,'2035-01-01T01:00:00Z');assert.equal(squareObservation({...data,card_details:undefined},req,req.merchantId).completedAt,null);});
 await check('signed webhook -> trusted provider lookup -> DB dedup; embedded paid flag and out-of-order body cannot confirm',async()=>{const d=await x.draft();x.fake.status='PENDING';await x.service.startPayment(d.booking.id,randomUUID());const req=x.fake.calls.at(-1)!,o=x.fake.receipts.get(req.attemptId)!;const url='https://example.invalid/offline-webhook',secret='SYNTHETIC-NONSECRET-KEY';const raw=Buffer.from(JSON.stringify({event_id:'event-flow-1',merchant_id:req.merchantId,type:'payment.updated',data:{object:{payment:{id:o.providerId,status:'COMPLETED',amount_money:{amount:1,currency:'USD'}}}}}));const sign=(b:Buffer)=>createHmac('sha256',secret).update(url).update(b).digest('base64');const pending=await x.service.reconcileVerifiedWebhook(d.booking.id,raw,sign(raw),url,secret);assert.equal(pending.state,'PAYMENT_PENDING');assert.equal(pending.qr,null);await x.service.reconcileVerifiedWebhook(d.booking.id,raw,sign(raw),url,secret);assert.equal((await x.db.pool.query("SELECT count(*)::int n FROM rental_provider_events WHERE event_id='webhook/event-flow-1'")).rows[0].n,1);await assert.rejects(x.service.reconcileVerifiedWebhook(d.booking.id,Buffer.concat([raw,Buffer.from(' ')]),sign(raw),url,secret),{code:'WEBHOOK_SIGNATURE_REJECTED'});const changed=Buffer.from(raw.toString().replace('event-flow-1','event-flow-2'));x.fake.receipts.set(req.attemptId,{...o,status:'COMPLETED',completedAt:x.now().toISOString()});assert.equal((await x.service.reconcileVerifiedWebhook(d.booking.id,changed,sign(changed),url,secret)).state,'CONFIRMED_DEV');x.fake.status='COMPLETED';});
 await check('terminal failed attempt is not silently restarted or promoted by a contradictory completion',async()=>{x.fake.status='FAILED';const d=await x.draft();const first=await x.service.startPayment(d.booking.id,randomUUID());assert.equal(first.payments[0].state,'FAILED');const n=x.fake.calls.length;await x.service.startPayment(d.booking.id,randomUUID());assert.equal(x.fake.calls.length,n);const req=x.fake.calls.at(-1)!,prior=x.fake.receipts.get(req.attemptId)!;x.fake.receipts.set(req.attemptId,{...prior,status:'COMPLETED',completedAt:x.now().toISOString()});const contradictory=await x.service.reconcile(d.booking.id);assert.equal(contradictory.state,'PAYMENT_REVIEW');assert.equal(contradictory.qr,null);assert.notEqual((await x.holds.get(d.holdId)).paymentState,'SUCCESS');await x.clock(new Date(x.now().getTime()+1).toISOString());x.fake.receipts.set(req.attemptId,{...prior,status:'COMPLETED',updatedAt:x.now().toISOString(),completedAt:x.now().toISOString()});assert.equal((await x.service.reconcile(d.booking.id)).state,'PAYMENT_REVIEW');x.fake.status='COMPLETED';});
 await check('confirmed provisional witness remains flexible within saved variants, preserving other promises and original TTL',async()=>{
  const d=await x.draft(undefined,requestFor('2035-02-25',[variants.ski,variants.skiAlt]));await x.service.startPayment(d.booking.id,randomUUID());
  const expiry=(await x.holds.get(d.holdId)).expiresAt;
  const before=(await x.db.pool.query('SELECT c.asset_id,a.variant_id FROM inventory_claims c JOIN ledger_assets a ON a.id=c.asset_id WHERE c.hold_id=$1 AND c.active',[d.holdId])).rows[0];
  const other=await x.holds.command('create',randomUUID(),requestFor('2035-02-25',[before.variant_id]));assert.equal(other.result,'CREATED');
  const after=(await x.db.pool.query('SELECT asset_id FROM inventory_claims WHERE hold_id=$1 AND active',[d.holdId])).rows[0];assert.notEqual(after.asset_id,before.asset_id);
  assert.equal((await x.db.pool.query('SELECT asset_id FROM inventory_claims WHERE hold_id=$1 AND active',[other.holdId])).rows[0].asset_id,before.asset_id);
  assert.equal((await x.holds.get(d.holdId)).expiresAt,expiry);assert.equal((await x.service.get(d.booking.id)).priceSha256,d.quote.snapshotSha256);
  assert.equal((await x.holds.availability(requestFor('2035-02-25',[variants.ski,variants.skiAlt]))).result,'INSUFFICIENT');
 });
 await check('new application role cannot DDL/read credentials/alter price, audit, or HOLD conditions/expiry',async()=>{for(const sql of ['CREATE TABLE forbidden_flow(id int)','SELECT password FROM auth_account','UPDATE price_quotes SET snapshot=snapshot','UPDATE rental_history SET event=event','UPDATE inventory_holds SET expires_at=expires_at','UPDATE inventory_holds SET conditions=conditions'])await assert.rejects(x.flow.flowPool.query(sql),{code:'42501'});assert.equal((await x.service.list()).length,12);});
 await check('handoff reader needs explicit booking permission/store; creator identity and live access removal are enforced',async()=>{
  const settings={displayName:'SYNTHETIC Reader',active:true,role:'VIEWER',scope:'ASSIGNED',storeIds:['MOUNTAIN_BASE'],permissions:{BOOKING_VIEW:true}};
  const account=await writeAccount(x.roles.authPool,x.bp,undefined,{...settings,email:'flow-reader@example.invalid',password:x.password});const signed=await x.login('flow-reader@example.invalid');
  const reader=new BookingService(x.flow.flowPool,x.roles.authPool,signed.identity,x.fake,simulation);const view=await reader.get(a.booking.id);assert.equal(view.id,a.booking.id);assert.equal('email' in view.contact,false);
  await assert.rejects(reader.startPayment(a.booking.id,randomUUID()),{code:'FORBIDDEN'});
  await assert.rejects(new BookingService(x.flow.flowPool,x.roles.authPool,{subject:x.actor,sessionId:signed.identity.sessionId},x.fake,simulation).get(a.booking.id),{code:'UNAUTHENTICATED'});
  const outside=await writeAccount(x.roles.authPool,x.bp,account.id,{...settings,storeIds:['ONSEN_BASE'],expectedRevision:account.account.revision});await assert.rejects(reader.get(a.booking.id),{code:'FORBIDDEN'});assert.equal((await reader.list()).length,0);
  const denied=await writeAccount(x.roles.authPool,x.bp,account.id,{...settings,permissions:{BOOKING_VIEW:false},expectedRevision:outside.account.revision});await assert.rejects(reader.get(a.booking.id),{code:'FORBIDDEN'});
  await writeAccount(x.roles.authPool,x.bp,account.id,{...settings,active:false,expectedRevision:denied.account.revision});await assert.rejects(reader.get(a.booking.id),{code:'UNAUTHENTICATED'});
 });
 console.log(`FLOW payment real PostgreSQL: ${passed} passed; no skipped; synthetic adapter, real password/session, no Square requests.`);
}catch(e){console.error('FLOW_PAYMENT_FAILED '+stage+' '+((e as {code?:string}).code??(e as Error).name));if(e instanceof assert.AssertionError)console.error(JSON.stringify({actual:e.actual,expected:e.expected}));console.error((e as Error).stack?.split('\n').filter(l=>l.includes('/tests/flow/')).join('\n'));process.exitCode=1;}finally{await x.close();console.log('Owned FLOW payment PostgreSQL stopped.');}
