import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
import {chromium,expect,type BrowserContext} from '@playwright/test';
import {startFlowApp} from './launcher';
import {bootstrapDevelopmentAdmin} from '../../scripts/bootstrap-staff';
import {seedRecommendation} from '../recommendation/fixture';
import {skiSet} from '../inventory/fixture';
let stage='startup',failed=false,app:Awaited<ReturnType<typeof startFlowApp>>|undefined;const browser=await chromium.launch(),password=randomBytes(24).toString('base64url');
try{
 app=await startFlowApp({paymentFault:'SAVE_THEN_LOSE'});await seedRecommendation(app.db.pool);await bootstrapDevelopmentAdmin(app.db.pool,{email:'restart-root@example.invalid',displayName:'SYNTHETIC Root',password});const {origin}=app;
 await app.db.pool.query("CREATE OR REPLACE FUNCTION inventory_clock() RETURNS timestamptz LANGUAGE sql VOLATILE AS $$SELECT '2035-01-01T01:00:00Z'::timestamptz$$");
 async function ready(){for(let i=0;i<100;i++){try{if((await fetch(origin+'/api/health')).ok)return;}catch{}await new Promise(r=>setTimeout(r,100));}throw new Error('APP_START_TIMEOUT');}await ready();
 stage='unhydrated login safety';const noJs=await browser.newContext({baseURL:origin,javaScriptEnabled:false});const noJsPage=await noJs.newPage();await noJsPage.goto('/staff/login');await expect(noJsPage.getByLabel('メールアドレス',{exact:true})).toBeDisabled();await expect(noJsPage.getByLabel('パスワード',{exact:true})).toBeDisabled();await expect(noJsPage.getByRole('button',{name:'ログイン',exact:true})).toBeDisabled();assert.equal(await noJsPage.locator('form').getAttribute('method'),'post');await noJs.close();console.log('PASS unhydrated login cannot submit credentials; native form transport is POST');
 async function context(){const c=await browser.newContext({baseURL:origin});c.setDefaultTimeout(15000);return c;}
 async function login(c:BrowserContext,email:string){const p=await c.newPage();await p.goto('/staff/login');await p.getByLabel('メールアドレス',{exact:true}).fill(email);await p.getByLabel('パスワード',{exact:true}).fill(password);await p.getByRole('button',{name:'ログイン',exact:true}).click();await p.waitForURL(origin+'/staff/ledger');return p;}
 const root=await context();await login(root,'restart-root@example.invalid');assert.equal((await root.request.post('/api/staff-users',{headers:{origin},data:{email:'restart-creator@example.invalid',password,displayName:'SYNTHETIC Restart',active:true,role:'ADMIN',scope:'ALL',storeIds:[],permissions:{BOOKING_VIEW:true,BOOKING_CREATE:true,HOLD_VIEW:true,HOLD_EDIT:true,QUOTE_VIEW:true,QUOTE_CREATE:true,PRICE_EDIT:true}}})).status(),201);
 const staff=await context(),p=await login(staff,'restart-creator@example.invalid');
 stage='UI price initial reads';const initialReads=Promise.all(['/catalog','/options',''].map(path=>p.waitForResponse(r=>new URL(r.url()).pathname==='/api/quotes'+path&&r.request().method()==='GET').then(async r=>{assert.equal(r.status(),200);await r.finished();})));await p.goto('/staff/quotes');await initialReads;stage='UI price input';await p.getByLabel('料金の対象開始日').fill('2035-01-01');await p.getByLabel('料金の対象終了日').fill('2035-12-31');stage='UI price save response';const savePrice=p.waitForResponse(r=>new URL(r.url()).pathname==='/api/quotes/private-initialize'&&r.request().method()==='POST'),priceReload=p.waitForResponse(r=>new URL(r.url()).pathname==='/api/quotes/catalog'&&r.request().method()==='GET');await p.getByRole('button',{name:'開発用の初期料金を設定'}).click();assert.equal((await savePrice).status(),201);assert.equal((await priceReload).status(),200);stage='UI price saved display';await expect(p.getByRole('region',{name:'料金版',exact:true})).toContainText('PRIVATE_AVAILABLE');
 stage='source HOLD API';const conditions=skiSet('2035-01-05');const hr=await staff.request.post('/api/holds',{headers:{origin},data:{requestKey:randomUUID(),conditions}});assert.equal(hr.status(),201);const h=(await hr.json()).hold;
 stage='source quote API';const qr=await staff.request.post('/api/quotes',{headers:{origin},data:{requestKey:randomUUID(),input:{conditions,holdId:h.id,couponCode:null,wantAdvance:false}}});assert.equal(qr.status(),201);const q=(await qr.json()).quote;
 stage='booking preview form';await p.goto('/preview/rental?quote='+q.id);await p.getByLabel('合成氏名').fill('SYNTHETIC Restart');await p.getByLabel('架空メール宛先').fill('synthetic-restart@example.invalid');await p.getByLabel('開発用の合成予約であり、営業規約・請求の確定ではないことを確認').check();stage='booking save response';const savedBooking=p.waitForResponse(r=>new URL(r.url()).pathname==='/api/bookings'&&r.request().method()==='POST');await p.getByRole('button',{name:'合成予約情報を保存',exact:true}).click();assert.equal((await savedBooking).status(),201);stage='booking saved display';await expect(p.getByRole('region',{name:'開発予約詳細'})).toContainText('DRAFT');
 stage='provider response loss';await p.getByRole('button',{name:'テストアダプタへ照合要求'}).click();await expect(p.getByRole('region',{name:'開発予約詳細'})).toContainText('UNKNOWN');const before=(await app.db.pool.query('SELECT * FROM rental_payment_attempts')).rows[0];assert.equal(before.state,'UNKNOWN');assert.equal((await app.db.pool.query('SELECT count(*)::int n FROM rental_notifications')).rows[0].n,0);console.log('PASS normal login/UI/protected APIs save UNKNOWN after test-provider response loss');
 stage='actual Next process restart';await p.close();const ids=await app.restartWeb();assert.ok(ids.oldPid&&ids.newPid&&ids.oldPid!==ids.newPid);await ready();const back=await staff.newPage();await back.goto('/preview/rental');await back.getByRole('button',{name:/SYNTHETIC Restart.*PAYMENT_PENDING/}).click();await back.getByRole('button',{name:'既存の決済結果を照合'}).click();await expect(back.getByRole('region',{name:'開発予約詳細'})).toContainText('UNKNOWN');await expect(back.getByLabel('開発予約QR')).toHaveCount(0);
 const again=await staff.request.post('/api/bookings/'+conditions.reservationId+'/payment',{headers:{origin},data:{requestKey:randomUUID()}});assert.equal(again.status(),200);assert.equal((await again.json()).state,'PAYMENT_PENDING');const after=(await app.db.pool.query('SELECT * FROM rental_payment_attempts')).rows;assert.equal(after.length,1);assert.equal(after[0].idempotency_key,before.idempotency_key);assert.equal(after[0].state,'UNKNOWN');assert.equal((await app.db.pool.query('SELECT expires_at FROM inventory_holds WHERE id=$1',[h.id])).rows[0].expires_at.toISOString(),h.expiresAt);assert.equal((await app.db.pool.query('SELECT count(*)::int n FROM rental_notifications')).rows[0].n,0);
 console.log('PASS distinct Next PIDs: saved session/booking/attempt/TTL survive; lost ephemeral provider evidence remains UNKNOWN, no replacement attempt or false QR');
}catch(e){console.error('WEB_RESTART_FAILED '+stage+' '+(e as Error).name+'; URL/query and credential diagnostics withheld');if(e instanceof assert.AssertionError)console.error(JSON.stringify({actual:e.actual,expected:e.expected}));console.error((e as Error).stack?.split('\n').filter(line=>line.includes('/tests/flow/web-restart.ts:')).join('\n'));failed=true;}finally{await browser.close();await app?.stop();console.log('Owned restart-test Web/browser/PostgreSQL stopped.');}

if(failed)process.exit(1);
