import assert from 'node:assert/strict';
import {randomUUID,randomBytes} from 'node:crypto';
import {chromium,expect,type BrowserContext} from '@playwright/test';
import {startDevelopmentApp} from '../../scripts/development-app';
import {bootstrapDevelopmentAdmin} from '../../scripts/bootstrap-staff';
import {loadStaff} from '../../packages/auth/src/staff-auth';
import {writeAccount} from '../../packages/auth/src/accounts';
import {seedRecommendation} from '../recommendation/fixture';
import {requestFor,fid} from '../inventory/fixture';
import {provisionFlowRole} from '../../scripts/flow-roles';
import {HoldService} from '../../packages/core/src/inventory/hold-service';
import {QuoteService} from '../../packages/core/src/pricing/quote-service';
import {BookingService} from '../../packages/core/src/payment/booking-service';
import {STOCK_IMPORT_HEADER_V2} from '../../packages/contracts/src/stock-import';
import {LedgerService} from '../../packages/core/src/catalog/ledger-service';
import {FakeGateway,simulation} from '../flow/fixture';
let app:Awaited<ReturnType<typeof startDevelopmentApp>>|undefined,flow:Awaited<ReturnType<typeof provisionFlowRole>>|undefined,failed=false,stage='startup',count=0,external=0;
const browser=await chromium.launch(),password=randomBytes(24).toString('base64url');
async function check(name:string,fn:()=>Promise<void>){stage=name;await fn();count++;console.log('PASS '+name);}
try{
 app=await startDevelopmentApp({built:true,operations:true});const {origin,db,roles}=app;await seedRecommendation(db.pool);
 const now=new Date('2035-01-01T10:00:00+09:00');await db.pool.query(`CREATE OR REPLACE FUNCTION inventory_clock() RETURNS timestamptz LANGUAGE sql VOLATILE AS $$SELECT '${now.toISOString()}'::timestamptz$$`);
 const root=await bootstrapDevelopmentAdmin(db.pool,{email:'m1-root@example.invalid',displayName:'SYNTHETIC Admin',password}),admin=(await loadStaff(db.pool,root))!;
 const actor=(await writeAccount(roles.authPool,admin,undefined,{email:'m1-operator@example.invalid',password,displayName:'SYNTHETIC Operator',active:true,role:'ADMIN',scope:'ALL',storeIds:[],permissions:{INVENTORY_VIEW:true,INVENTORY_EDIT:true,HOLD_VIEW:true,HOLD_EDIT:true,QUOTE_VIEW:true,QUOTE_CREATE:true,PRICE_EDIT:true,BOOKING_VIEW:true,BOOKING_CREATE:true,RENTAL_CHECKOUT:true,RENTAL_RETURN:true,RENTAL_AMEND:true,REFUND_OVERRIDE:true,INVENTORY_RECONCILE:true}})).id!;
 await writeAccount(roles.authPool,admin,undefined,{email:'m1-viewer@example.invalid',password,displayName:'SYNTHETIC Scoped viewer',active:true,role:'VIEWER',scope:'ASSIGNED',storeIds:['ONSEN_BASE'],permissions:{INVENTORY_VIEW:true,BOOKING_VIEW:true}});
 for(let i=0;i<150;i++){try{if((await fetch(origin+'/api/health')).ok)break;}catch{}if(i===149)throw Error('LOCAL_START_TIMEOUT');await new Promise(r=>setTimeout(r,100));}
 async function context(){const c=await browser.newContext({baseURL:origin,viewport:{width:1440,height:1000}});c.setDefaultTimeout(15000);await c.route('**/*',route=>{const url=route.request().url();if(url.startsWith(origin+'/')||url.startsWith('data:'))return route.continue();external++;return route.abort('blockedbyclient');});return c;}
 async function login(c:BrowserContext,email:string){const p=await c.newPage();await p.goto('/staff/login');await p.getByLabel('メールアドレス',{exact:true}).fill(email);await p.getByLabel('パスワード',{exact:true}).fill(password);await p.getByRole('button',{name:'ログイン',exact:true}).click();await p.waitForURL(origin+'/staff/ledger');return p;}
 const owner=await context(),viewer=await context(),anonymous=await context(),page=await login(owner,'m1-operator@example.invalid');await login(viewer,'m1-viewer@example.invalid');page.on('response',async r=>{if(r.url().startsWith(origin+'/api/operations/')&&r.status()>=400){const v=await r.json().catch(()=>({}));console.log(JSON.stringify({status:r.status(),code:/^[A-Z_]+$/.test(v.error)?v.error:'WITHHELD'}));}});
 flow=await provisionFlowRole(db.pool,db.identity);const principal=(await loadStaff(db.pool,actor))!,sessionId=(await db.pool.query('SELECT id FROM auth_session WHERE "userId"=$1',[actor])).rows[0].id as string;
 const holds=new HoldService(roles.holdPool,principal,()=>now),quotes=new QuoteService(roles.pricingPool,principal,()=>now);await quotes.initializePrivate(randomUUID(),'2035-01-01','2035-12-31');const conditions=requestFor('2035-02-05'),held=await holds.command('create',randomUUID(),conditions),q=(await quotes.create(randomUUID(),{conditions,holdId:held.holdId,couponCode:null,wantAdvance:false})).quote;
 const fake=new FakeGateway(()=>now),bookings=new BookingService(flow.flowPool,roles.authPool,{subject:actor,sessionId},fake,simulation),booking=await bookings.create(randomUUID(),q.id,{displayName:'SYNTHETIC Guest',email:'synthetic-m1-guest@example.invalid',termsAccepted:true});await bookings.startPayment(booking.id,randomUUID());
 await check('normal Next UI freezes and accepts extension; original paid snapshot stays immutable',async()=>{const before=(await db.pool.query('SELECT to_jsonb(b) value FROM rental_bookings b WHERE id=$1',[booking.id])).rows[0].value;await page.goto('/staff/amendments');await page.getByLabel('予約ID',{exact:true}).fill(booking.id);await page.getByRole('button',{name:'変更対象を読み込む'}).click();await expect(page.getByRole('heading',{name:'変更内容',exact:true})).toBeVisible();await page.getByLabel('返却日',{exact:true}).fill('2035-02-06');await page.getByLabel('操作理由（詳細な個人情報は記入しない）').fill('SYNTHETIC extension');await page.getByRole('button',{name:'変更見積を固定'}).click();await expect(page.getByRole('heading',{name:'変更見積',exact:true})).toBeVisible();await page.getByRole('button',{name:'この見積で変更を確定'}).click();await expect(page.getByRole('heading',{name:'変更見積',exact:true})).toHaveCount(0);assert.equal((await db.pool.query('SELECT count(*)::int n FROM ops_amendments WHERE booking_id=$1',[booking.id])).rows[0].n,1);assert.deepEqual((await db.pool.query('SELECT to_jsonb(b) value FROM rental_bookings b WHERE id=$1',[booking.id])).rows[0].value,before);});
 await check('staff exception refund uses the normal API and durable pending ledger without provider calls',async()=>{await page.getByRole('button',{name:'入金・返金残額を照合'}).click();await expect(page.getByRole('heading',{name:'入金と返金残額'})).toBeVisible();const payment=(await db.pool.query('SELECT id FROM rental_payment_attempts WHERE booking_id=$1',[booking.id])).rows[0].id;await page.getByLabel('元の入金').selectOption(payment);await page.getByLabel('返金依頼額（円）').fill('100');await page.getByRole('button',{name:'例外返金を依頼する'}).click();await expect.poll(async()=>Number((await db.pool.query('SELECT count(*) n FROM ops_refund_requests WHERE booking_id=$1',[booking.id])).rows[0].n)).toBe(1);assert.equal((await db.pool.query('SELECT dispatched_at FROM ops_refund_requests WHERE booking_id=$1',[booking.id])).rows[0].dispatched_at,null);assert.equal(fake.calls.length,1);});
 await check('normal inventory screen creates and records a stocktake without mutating stock',async()=>{await page.goto('/admin/inventory');await page.getByRole('button',{name:'棚卸を開始',exact:true}).click();await page.getByRole('button',{name:'棚卸を読み込む',exact:true}).click();await expect(page.getByRole('heading',{name:'棚卸の照合',exact:true})).toBeVisible();await page.getByLabel('用品の個体ID',{exact:true}).fill(fid(1201));await page.getByRole('button',{name:'入力したIDを照合へ送る'}).click();await expect(page.getByText('今回の読取: 1件', {exact:false})).toBeVisible();const before=(await db.pool.query('SELECT id,status,version FROM ledger_assets ORDER BY id')).rows;await page.getByRole('button',{name:'読取・数量を保存して差異確認へ'}).click();await expect.poll(async()=>Number((await db.pool.query("SELECT count(*) n FROM ops_stocktakes WHERE state='REVIEW_REQUIRED'")).rows[0].n)).toBe(1);assert.deepEqual((await db.pool.query('SELECT id,status,version FROM ledger_assets ORDER BY id')).rows,before);});
 await check('Asset ID search and identical ski QR labels work on normal admin route',async()=>{await page.goto('/admin/assets');await page.getByRole('button',{name:'個体台帳',exact:true}).click();await page.getByPlaceholder('モデル名・ID').fill(fid(1201));await page.getByRole('button',{name:/^詳細：/}).click();await expect(page.getByRole('heading',{name:'用品ラベル',exact:true})).toBeVisible();await expect(page.locator('.asset-label')).toHaveCount(2);const ids=await page.locator('.asset-label code').allTextContents();assert.deepEqual(ids,[fid(1201),fid(1201)]);});
 await check('normal CSV dry-run and explicit commit create one synthetic immutable Asset',async()=>{
  const ledger=new LedgerService(db.pool,{subject:actor,role:'ADMIN',storeIds:['MOUNTAIN_BASE','ONSEN_BASE']},async()=>{},async()=>{}),source={notes:'SYNTHETIC normal import',sourceKind:'SYNTHETIC',sourceDocument:'tests/operations/normal-ui.ts',sourceLocator:'csv'};
  const model=await ledger.create('models',{...source,code:'M1-BROWSER',name:'SYNTHETIC CSV ski',brand:'SYNTHETIC',family:'SKI',catalogSeason:'2026/27'}),variant=await ledger.create('variants',{...source,modelId:model.id,family:'SKI',age:'ADULT',tier:'REGULAR',size:'160 cm'}),asset=randomUUID();
  const csv=STOCK_IMPORT_HEADER_V2.join(',')+'\n'+['SHOP_RECEIPT','ADD',model.id,'2026/27',variant.id,'',1,'ASSET_PAIR',asset,'MOUNTAIN_BASE','SYNTHETIC browser receipt','1','SKI','160 cm','REGULAR','','AVAILABLE'].join(',')+'\n';
  await page.goto('/admin/inventory');await page.getByLabel('CSVファイル').setInputFiles({name:'synthetic-stock.csv',mimeType:'text/csv',buffer:Buffer.from(csv)});await page.getByRole('button',{name:'dry-runを保存',exact:true}).click();await expect(page.getByText('dry-run: 確定可能', {exact:false})).toBeVisible();assert.equal((await db.pool.query('SELECT count(*)::int n FROM ledger_assets WHERE id=$1',[asset])).rows[0].n,0);await page.getByLabel('投入理由').fill('SYNTHETIC verified receipt');await page.getByRole('button',{name:'検証済みの在庫を投入',exact:true}).click();await expect.poll(async()=>(await db.pool.query('SELECT count(*)::int n FROM ledger_assets WHERE id=$1',[asset])).rows[0].n).toBe(1);
 });
 await check('normal price draft/edit/preview/private publication preserves existing quote snapshot',async()=>{
  const before=(await db.pool.query('SELECT snapshot,snapshot_sha256 FROM price_quotes WHERE id=$1',[q.id])).rows[0],source=(await db.pool.query('SELECT id FROM price_books')).rows[0].id;
  await page.goto('/admin/prices');await page.getByRole('button',{name:'料金版を読み込む',exact:true}).click();await page.getByLabel('料金版',{exact:false}).selectOption(source);await page.getByLabel('理由',{exact:true}).fill('SYNTHETIC private price draft');await page.getByLabel('対象開始日').fill('2035-01-01');await page.getByLabel('対象終了日').fill('2035-12-31');await page.getByRole('button',{name:'選択した料金版からdraftを作る'}).click();await expect.poll(async()=>(await db.pool.query('SELECT count(*)::int n FROM price_books WHERE source_book_id=$1',[source])).rows[0].n).toBe(1);
  let draft=(await db.pool.query('SELECT * FROM price_books WHERE source_book_id=$1',[source])).rows[0];await page.getByRole('button',{name:'料金版を読み込む',exact:true}).click();await page.getByLabel('料金版',{exact:false}).selectOption(draft.id);await page.getByRole('button',{name:'料金表と差分を表示'}).click();await expect(page.getByRole('heading',{name:/DRAFT · revision/})).toBeVisible();const product=Object.keys(draft.table_jpy)[0]!,amount=draft.table_jpy[product].DAY_1+100;await page.getByLabel('商品',{exact:false}).selectOption(product);await page.getByLabel('金額（円）').fill(String(amount));await page.getByRole('button',{name:'draftを更新する'}).click();await expect.poll(async()=>(await db.pool.query('SELECT revision FROM price_books WHERE id=$1',[draft.id])).rows[0].revision).toBe(2);
  await page.getByRole('button',{name:'料金版を読み込む',exact:true}).click();await page.getByRole('button',{name:'料金表と差分を表示'}).click();await expect(page.getByRole('heading',{name:'複製元との差分'})).toBeVisible();await page.getByLabel('適用日時').fill('2035-01-02T10:00');await page.getByRole('button',{name:'表示した料金版を確定・適用する'}).click();await expect.poll(async()=>(await db.pool.query('SELECT state FROM price_books WHERE id=$1',[draft.id])).rows[0].state).toBe('PRIVATE_AVAILABLE');assert.deepEqual((await db.pool.query('SELECT snapshot,snapshot_sha256 FROM price_quotes WHERE id=$1',[q.id])).rows[0],before);
  const saved=(await db.pool.query('SELECT request_key FROM price_admin_requests WHERE actor=$1',[actor])).rows;assert.equal(saved.length,3);draft=(await db.pool.query('SELECT * FROM price_books WHERE id=$1',[draft.id])).rows[0];assert.equal(draft.table_jpy[product].DAY_1,amount);
 });
 await check('390/768/1440 responsive operations pages, authorization, scope and CSRF deny',async()=>{for(const width of [390,768,1440])for(const path of ['/admin/assets','/admin/inventory','/staff/amendments','/staff/rentals','/admin/prices']){await page.setViewportSize({width,height:960});await page.goto(path);await expect(page.locator('h1').first()).toBeVisible();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),path+' width '+width);}
  assert.equal((await anonymous.request.get('/api/operations/inventory?store=MOUNTAIN_BASE')).status(),401);assert.equal((await viewer.request.get('/api/operations/inventory?store=MOUNTAIN_BASE')).status(),403);
  assert.equal((await viewer.request.post('/api/operations/refund',{headers:{origin},data:{requestKey:randomUUID(),input:{bookingId:booking.id,paymentId:randomUUID(),actingStore:'ONSEN_BASE',category:'CUSTOMER_EXCEPTION',reason:'SYNTHETIC denied',amountJpy:100}}})).status(),403);
  assert.equal((await owner.request.post('/api/operations/stocktake-create',{data:{requestKey:randomUUID(),input:{store:'MOUNTAIN_BASE'}}})).status(),403);
  assert.equal((await owner.request.post('/api/bookings/'+booking.id+'/payment',{headers:{origin},data:{requestKey:randomUUID()}})).status(),503);assert.equal(external,0);
 });
 console.log(JSON.stringify({status:'PASS',cases:count,externalRequests:external,actualProviderCalls:0,normalApp:'apps/web'}));
}catch(e){failed=true;console.error(JSON.stringify({status:'FAIL',stage,code:(e as {code?:string}).code??'UI_ASSERTION',detail:stage==='startup'?'STARTUP_DETAILS_WITHHELD':(e as Error).message.split('Call log:')[0]!.slice(0,1200),location:(e as Error).stack?.split('\n').filter(l=>l.includes('/tests/operations/')).join('\n')}));}finally{await browser.close();await flow?.close();await app?.stop();}if(failed)process.exit(1);
