import {createHash,randomUUID} from 'node:crypto';
import type {Pool,PoolClient} from 'pg';
import {expireInventoryHolds} from '../inventory/expiry';
import {loadStaff,type StaffPrincipal,type Permission} from '../../../auth/src/staff-auth';
import {TransferError,parsePlan,uuid,object,lines,canonical,tokyoDate,type TransferOperation,type TransferLine} from '../../../contracts/src/transfer';
type Conn=Pick<PoolClient,'query'>;
type Batch={id:string;source_store:string;destination_store:string;scheduled_date:string;planned_ready_at:Date;needed_by:Date;basis:string;state:string;issue:string|null;version:number};
const permission:Record<TransferOperation,Permission>={create:'TRANSFER_PLAN',add:'TRANSFER_PLAN',cancel:'TRANSFER_PLAN',dispatch:'TRANSFER_DISPATCH',receive:'TRANSFER_RECEIVE',ready:'TRANSFER_RECEIVE',issue:'TRANSFER_VIEW'};
export class TransferService{
 constructor(private pool:Pool,private principal:StaffPrincipal,private clock?:()=>Date){}
 private async auth(c:Conn,op:Permission='TRANSFER_VIEW',stores:string[]=[]){const p=await loadStaff(c as Pick<Pool,'query'>,this.principal.subject);if(!p||p.revision!==this.principal.revision||!p.permissions.includes('TRANSFER_VIEW')||!p.permissions.includes(op)||stores.some(s=>!p.storeIds.includes(s as never)))throw new TransferError('FORBIDDEN',403);return p;}
 private async batch(c:Conn,id:string,op:TransferOperation|'view'){uuid(id);const b=(await c.query<Batch>('SELECT *,scheduled_date::text FROM transfer_batches WHERE id=$1',[id])).rows[0];if(!b)throw new TransferError('NOT_FOUND',404);const p=await this.auth(c,op==='view'?'TRANSFER_VIEW':permission[op]);const stores=op==='receive'||op==='ready'?[b.destination_store]:op==='create'||op==='add'||op==='cancel'?[b.source_store,b.destination_store]:op==='dispatch'?[b.source_store]:[];if(stores.some(s=>!p.storeIds.includes(s as never))||!p.storeIds.some(s=>s===b.source_store||s===b.destination_store))throw new TransferError('FORBIDDEN',403);if(op==='issue'&&!((p.storeIds.includes(b.source_store as never)&&p.permissions.includes('TRANSFER_DISPATCH'))||(p.storeIds.includes(b.destination_store as never)&&p.permissions.includes('TRANSFER_RECEIVE'))))throw new TransferError('FORBIDDEN',403);return b;}
 private async view(c:Conn,b:Batch,now:Date){const pieces=(await c.query(`SELECT p.*,a.family,coalesce(a.variant_id,lp.variant_id) AS variant_id FROM transfer_pieces p LEFT JOIN ledger_assets a ON a.id=p.asset_id LEFT JOIN ledger_poles lp ON lp.id=p.source_pole_id WHERE batch_id=$1 ORDER BY line_key,ordinal`,[b.id])).rows;
 const history=(await c.query('SELECT actor,event,entity_id,occurred_at FROM transfer_history WHERE batch_id=$1 ORDER BY id',[b.id])).rows;
 return {...b,pieces,history,late:!b.issue&&now>b.planned_ready_at&&pieces.some(p=>!['READY','CLOSED','CANCELLED'].includes(p.state)),affectedHolds:(await c.query(`SELECT DISTINCT h.id,h.state,h.transfer_attention FROM inventory_claims c JOIN inventory_holds h ON h.id=c.hold_id JOIN transfer_pieces p ON p.id=c.transfer_piece_id WHERE p.batch_id=$1 AND c.active AND h.state='ACTIVE' AND (h.expires_at>$2 OR h.allocation_stage<>'PROVISIONAL' OR h.payment_state NOT IN ('NONE','FAILURE'))`,[b.id,now])).rows,meaning:'TRANSFER_NOT_CUSTOMER_HANDOFF'};}
 private async read<T>(fn:(c:PoolClient,now:Date)=>Promise<T>){let c:PoolClient|undefined;try{c=await this.pool.connect();await c.query('BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY');await c.query("SET LOCAL statement_timeout='5000ms';SET LOCAL idle_in_transaction_session_timeout='10000ms'");await this.auth(c);const now=this.clock?.()??(await c.query<{now:Date}>('SELECT inventory_clock() AS now')).rows[0]!.now;const result=await fn(c,now);await c.query('COMMIT');return result;}catch(e){await c?.query('ROLLBACK').catch(()=>{});if(e instanceof TransferError)throw e;throw new TransferError('INDETERMINATE',503);}finally{c?.release();}}
 async list(){return this.read(async(c,now)=>{const p=await this.auth(c);return (await c.query(`SELECT b.*,scheduled_date::text,(b.planned_ready_at<$2 AND EXISTS(SELECT 1 FROM transfer_pieces WHERE batch_id=b.id AND state NOT IN ('READY','CLOSED','CANCELLED'))) AS late,(SELECT count(*)::int FROM transfer_pieces WHERE batch_id=b.id AND state='IN_TRANSIT') AS in_transit,(SELECT count(*)::int FROM transfer_pieces WHERE batch_id=b.id AND state='RECEIVED') AS inspection_pending FROM transfer_batches b WHERE source_store=ANY($1::text[]) OR destination_store=ANY($1::text[]) ORDER BY created_at DESC,id LIMIT 100`,[p.storeIds,now])).rows;});}
 async get(id:string){return this.read(async(c,now)=>this.view(c,await this.batch(c,id,'view'),now));}
 async options(){return this.read(async c=>{const p=await this.auth(c);return (await c.query(`SELECT a.id,a.family,a.store_id,a.variant_id,1 AS quantity,v.size,m.name FROM ledger_assets a JOIN ledger_variants v ON v.id=a.variant_id JOIN ledger_models m ON m.id=v.model_id WHERE a.status='AVAILABLE' AND a.store_id=ANY($1::text[]) UNION ALL SELECT a.id,a.family,a.store_id,a.variant_id,a.quantity,v.size,m.name FROM ledger_poles a JOIN ledger_variants v ON v.id=a.variant_id JOIN ledger_models m ON m.id=v.model_id WHERE a.status='AVAILABLE' AND a.store_id=ANY($1::text[]) ORDER BY family,id LIMIT 1000`,[p.storeIds])).rows;});}
 private async compactPoleClaims(c:Conn,b:Batch){
  const before=(await c.query(`SELECT cl.*,cl.day::text AS day FROM inventory_claims cl WHERE cl.active AND cl.transfer_piece_id IS NULL AND cl.pole_id IN (SELECT source_pole_id FROM transfer_pieces WHERE batch_id=$1) AND cl.day>$2 ORDER BY cl.id`,[b.id,b.scheduled_date])).rows;
  if(!before.length)return;await c.query('UPDATE inventory_claims SET active=false WHERE id=ANY($1::bigint[])',[before.map(x=>x.id)]);
  await c.query(`INSERT INTO inventory_claims(hold_id,requirement_key,pole_id,pole_slot,day) SELECT (v->>'hold_id')::uuid,v->>'requirement_key',(v->>'pole_id')::uuid,row_number() OVER(PARTITION BY v->>'pole_id',v->>'day' ORDER BY v->>'hold_id',v->>'requirement_key')::integer,(v->>'day')::date FROM jsonb_array_elements($1::jsonb) v`,[JSON.stringify(before)]);
  const after=(await c.query(`SELECT cl.*,cl.day::text AS day FROM inventory_claims cl WHERE cl.active AND cl.transfer_piece_id IS NULL AND cl.pole_id IN (SELECT source_pole_id FROM transfer_pieces WHERE batch_id=$1) AND cl.day>$2 ORDER BY cl.id`,[b.id,b.scheduled_date])).rows;
  await c.query('SELECT inventory_record_replan($1::jsonb,$2::jsonb)',[JSON.stringify(before),JSON.stringify(after)]);
 }
 private async add(c:Conn,b:Batch,input:TransferLine[],now:Date){
  if(b.state!=='PLANNED'||tokyoDate(now)>b.scheduled_date)throw new TransferError('BATCH_CLOSED',409);
  if(Number((await c.query('SELECT count(*) AS n FROM transfer_pieces WHERE batch_id=$1',[b.id])).rows[0].n)+input.reduce((n,x)=>n+('assetId'in x?1:x.quantity),0)>200)throw new TransferError('BATCH_LIMIT',422);
  // Archive a completed quantity witness only after every old claim is inactive. No IDs are relabelled.
  await c.query(`UPDATE transfer_pieces p SET state='CLOSED' WHERE state='READY' AND NOT EXISTS(SELECT 1 FROM transfer_batches b WHERE b.id=p.batch_id AND b.issue IS NOT NULL) AND NOT EXISTS(SELECT 1 FROM inventory_claims WHERE active AND (transfer_piece_id=p.id OR asset_id=p.asset_id))`);
  for(const line of input){const asset='assetId'in line,id=asset?line.assetId:line.poleId,quantity=asset?1:line.quantity;
   const stock=(await c.query(`SELECT * FROM ${asset?'ledger_assets':'ledger_poles'} WHERE id=$1 AND store_id=$2 AND status='AVAILABLE'`,[id,b.source_store])).rows[0];if(!stock)throw new TransferError('STOCK_NOT_READY',409);
   if((await c.query(`SELECT 1 FROM inventory_constraints WHERE ${asset?'asset_id':'pole_id'}=$1 AND starts_on<=$2 AND ends_on>=$2 LIMIT 1`,[id,b.scheduled_date])).rowCount)throw new TransferError('STOCK_CONSTRAINED',409);
   if(asset){if((await c.query(`SELECT 1 FROM transfer_pieces WHERE asset_id=$1 AND state NOT IN ('CANCELLED','CLOSED')`,[id])).rowCount)throw new TransferError('ALREADY_COMMITTED',409);
    if((await c.query(`SELECT 1 FROM inventory_claims c JOIN inventory_holds h ON h.id=c.hold_id WHERE c.active AND c.asset_id=$1 AND h.state='ACTIVE' AND (h.expires_at>$3 OR h.allocation_stage<>'PROVISIONAL' OR h.payment_state NOT IN ('NONE','FAILURE')) AND (c.day>$2 OR h.pickup_store<>h.return_store OR c.day=$2 AND h.allocation_stage<>'PROVISIONAL') LIMIT 1`,[id,b.scheduled_date,now])).rowCount)throw new TransferError('SOURCE_PROMISE_CONFLICT',409);
   }else{
    const reserved=Number((await c.query("SELECT count(*) AS n FROM transfer_pieces WHERE (source_pole_id=$1 AND (state='PLANNED' OR state='CANCELLED' AND EXISTS(SELECT 1 FROM inventory_claims cl WHERE cl.transfer_piece_id=transfer_pieces.id AND cl.active))) OR (destination_pole_id=$1 AND state='READY')",[id])).rows[0].n);
    const max=Number((await c.query(`SELECT coalesce(max(n),0) AS n FROM (SELECT count(*) AS n FROM inventory_claims c JOIN inventory_holds h ON h.id=c.hold_id WHERE c.active AND c.pole_id=$1 AND c.transfer_piece_id IS NULL AND (c.day>$2 OR h.pickup_store<>h.return_store OR c.day=$2 AND h.allocation_stage<>'PROVISIONAL') AND h.state='ACTIVE' AND (h.expires_at>$3 OR h.allocation_stage<>'PROVISIONAL' OR h.payment_state NOT IN ('NONE','FAILURE')) GROUP BY c.day) x`,[id,b.scheduled_date,now])).rows[0].n);
    if(stock.quantity-reserved-max<quantity)throw new TransferError('SOURCE_PROMISE_CONFLICT',409);
   }
   let destination:string|null=null,receipt:string|null=null;if(!asset){destination=(await c.query("SELECT transfer_pool($1,$2,'AVAILABLE') AS id",[stock.variant_id,b.destination_store])).rows[0].id;receipt=(await c.query("SELECT transfer_pool($1,$2,'MAINTENANCE') AS id",[stock.variant_id,b.destination_store])).rows[0].id;}
   const lineKey=randomUUID();for(let ordinal=1;ordinal<=quantity;ordinal++)await c.query('INSERT INTO transfer_pieces(id,batch_id,line_key,ordinal,asset_id,source_pole_id,destination_pole_id,receipt_pole_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[randomUUID(),b.id,lineKey,ordinal,asset?id:null,asset?null:id,destination,receipt]);
  }
 }
 private async stockScope(c:Conn,source:string,items:TransferLine[]){for(const family of ['asset','pole'] as const){const ids=items.flatMap(x=>family==='asset'&&'assetId'in x?[x.assetId]:family==='pole'&&'poleId'in x?[x.poleId]:[]);if(ids.length&&(await c.query(`SELECT id FROM ${family==='asset'?'ledger_assets':'ledger_poles'} WHERE id=ANY($1::uuid[]) AND store_id=$2`,[ids,source])).rowCount!==ids.length)throw new TransferError('FORBIDDEN',403);}}
 async command(op:TransferOperation,key:string,input:unknown,batchId?:string){uuid(key);if(op!=='create'){uuid(batchId);}const plan=op==='create'?parsePlan(input):null;
  const fp=createHash('sha256').update(canonical({op,batchId:batchId??null,input})).digest('hex');
  let added:TransferLine[]|undefined;let selected:string[]|undefined;
  if(op==='add')added=lines(object(input,['lines']).lines);
  if(op==='dispatch'||op==='cancel')object(input,[]);
  if(op==='receive'||op==='ready'){const v=object(input,['pieceIds']);if(!Array.isArray(v.pieceIds)||!v.pieceIds.length||v.pieceIds.length>200||new Set(v.pieceIds).size!==v.pieceIds.length)throw new TransferError('INVALID_SELECTION');for(const id of v.pieceIds)uuid(id);selected=v.pieceIds as string[];}
  if(op==='issue'){const v=object(input,['reason']);if(typeof v.reason!=='string'||!v.reason.trim()||v.reason.length>160)throw new TransferError('INVALID_REASON');}
  const preflight=async(c:Conn)=>{await this.auth(c,permission[op],plan?[plan.sourceStore,plan.destinationStore]:[]);const b=batchId?await this.batch(c,batchId,op):null;
   const receipt=(await c.query('SELECT fingerprint FROM transfer_requests WHERE actor=$1 AND request_key=$2',[this.principal.subject,key])).rows[0];if(receipt){if(receipt.fingerprint!==fp)throw new TransferError('IDEMPOTENCY_MISMATCH',409);return;}
   if(plan)await this.stockScope(c,plan.sourceStore,plan.lines);if(added&&b)await this.stockScope(c,b.source_store,added);
   if(selected&&b&&(await c.query('SELECT id FROM transfer_pieces WHERE batch_id=$1 AND id=ANY($2::uuid[])',[b.id,selected])).rowCount!==selected.length)throw new TransferError('STALE_SELECTION',409);
  };
  await preflight(this.pool);let c:PoolClient|undefined;
  try{c=await this.pool.connect();await c.query('BEGIN');await c.query("SET LOCAL lock_timeout='1500ms';SET LOCAL statement_timeout='5000ms';SET LOCAL idle_in_transaction_session_timeout='10000ms'");await preflight(c);await c.query('SELECT pg_advisory_xact_lock(71820600)');await preflight(c);
   const now=this.clock?.()??(await c.query<{now:Date}>('SELECT inventory_clock() AS now')).rows[0]!.now;
   await c.query("SELECT set_config('zao.actor',$1,true),set_config('zao.reason','Authorized E07 transfer',true)",[this.principal.subject]);
   await expireInventoryHolds(c,now);
   const prior=(await c.query('SELECT * FROM transfer_requests WHERE actor=$1 AND request_key=$2',[this.principal.subject,key])).rows[0];if(prior){if(prior.fingerprint!==fp)throw new TransferError('IDEMPOTENCY_MISMATCH',409);const current=await this.view(c,await this.batch(c,prior.batch_id,op==='create'?'view':op),now);await c.query('COMMIT');return {batch:current,replayed:true};}
   if(plan){batchId=randomUUID();await c.query('INSERT INTO transfer_batches(id,source_store,destination_store,scheduled_date,planned_ready_at,needed_by,basis) VALUES($1,$2,$3,$4,$5,$6,$7)',[batchId,plan.sourceStore,plan.destinationStore,plan.scheduledDate,plan.plannedReadyAt,plan.neededBy,plan.basis]);await this.add(c,await this.batch(c,batchId,'create'),plan.lines,now);}
   else{const b=await this.batch(c,batchId!,op);
    if(op==='add'){const v=object(input,['lines']);await this.add(c,b,lines(v.lines),now);}
    if(op==='dispatch'){
     object(input,[]);if(b.state!=='PLANNED'||b.issue||now<new Date(b.scheduled_date+'T17:00:00+09:00')||tokyoDate(now)!==b.scheduled_date)throw new TransferError('DISPATCH_NOT_ALLOWED',409);
     const pieces=(await c.query("SELECT p.*,coalesce(a.status,lp.status) AS status,coalesce(a.store_id,lp.store_id) AS store FROM transfer_pieces p LEFT JOIN ledger_assets a ON a.id=p.asset_id LEFT JOIN ledger_poles lp ON lp.id=p.source_pole_id WHERE batch_id=$1 AND p.state='PLANNED'",[b.id])).rows;
     if(!pieces.length||pieces.some(p=>p.status!=='AVAILABLE'||p.store!==b.source_store))throw new TransferError('STOCK_NOT_READY',409);
     if((await c.query(`SELECT 1 FROM inventory_constraints x JOIN transfer_pieces p ON (x.asset_id=p.asset_id OR x.pole_id=p.source_pole_id) WHERE p.batch_id=$1 AND x.starts_on<=$2 AND x.ends_on>=$2 LIMIT 1`,[b.id,b.scheduled_date])).rowCount)throw new TransferError('STOCK_CONSTRAINED',409);
     if((await c.query(`SELECT 1 FROM inventory_claims cl JOIN inventory_holds h ON h.id=cl.hold_id JOIN transfer_pieces p ON p.asset_id=cl.asset_id WHERE p.batch_id=$1 AND cl.active AND h.state='ACTIVE' AND h.allocation_stage<>'PROVISIONAL' AND cl.day>=$2 LIMIT 1`,[b.id,b.scheduled_date])).rowCount)throw new TransferError('SOURCE_NOT_RETURNED_OR_READY',409);
     for(const pole of [...new Set(pieces.map(p=>p.source_pole_id).filter(Boolean))]){const outgoing=pieces.filter(p=>p.source_pole_id===pole).length;const stock=(await c.query('SELECT quantity FROM ledger_poles WHERE id=$1',[pole])).rows[0];const occupied=Number((await c.query(`SELECT count(*) AS n FROM inventory_claims cl JOIN inventory_holds h ON h.id=cl.hold_id WHERE cl.pole_id=$1 AND cl.transfer_piece_id IS NULL AND cl.active AND h.state='ACTIVE' AND h.allocation_stage<>'PROVISIONAL' AND cl.day=$2`,[pole,b.scheduled_date])).rows[0].n);const projected=Number((await c.query("SELECT count(*) AS n FROM transfer_pieces WHERE destination_pole_id=$1 AND state='READY'",[pole])).rows[0].n);if(stock.quantity-projected-occupied<outgoing)throw new TransferError('SOURCE_NOT_RETURNED_OR_READY',409);}
     await c.query("UPDATE transfer_batches SET state='DEPARTED',departed_at=$2 WHERE id=$1",[b.id,now]);for(const p of pieces)await c.query("SELECT transfer_move_stock($1,'dispatch',$2)",[p.id,now]);await this.compactPoleClaims(c,b);
    }
    if(op==='receive'||op==='ready'){
     const v=object(input,['pieceIds']);if(!Array.isArray(v.pieceIds)||!v.pieceIds.length||v.pieceIds.length>200||new Set(v.pieceIds).size!==v.pieceIds.length)throw new TransferError('INVALID_SELECTION');for(const id of v.pieceIds)uuid(id);
     const rows=(await c.query('SELECT * FROM transfer_pieces WHERE batch_id=$1 AND id=ANY($2::uuid[])',[b.id,v.pieceIds])).rows;if(rows.length!==v.pieceIds.length||rows.some(p=>p.state!==(op==='receive'?'IN_TRANSIT':'RECEIVED')))throw new TransferError('STALE_SELECTION',409);
     for(const p of rows){if(op==='ready'&&p.asset_id&&(await c.query("SELECT 1 FROM ledger_assets WHERE id=$1 AND status='AVAILABLE'",[p.asset_id])).rowCount!==1)throw new TransferError('STOCK_NOT_READY',409);await c.query('SELECT transfer_move_stock($1,$2,$3)',[p.id,op,now]);}
    }
    if(op==='cancel'){object(input,[]);if(b.state!=='PLANNED')throw new TransferError('PHYSICAL_TRANSFER_CANNOT_CANCEL',409);await c.query("UPDATE transfer_pieces SET state='CANCELLED' WHERE batch_id=$1 AND state='PLANNED'",[b.id]);await c.query("UPDATE transfer_batches SET state='CANCELLED',issue='CANCELLED_TRANSFER' WHERE id=$1",[b.id]);}
    if(op==='issue'){const v=object(input,['reason']);if(typeof v.reason!=='string'||!v.reason.trim()||v.reason.length>160)throw new TransferError('INVALID_REASON');await c.query('UPDATE transfer_batches SET issue=$2 WHERE id=$1',[b.id,v.reason]);}
    await c.query('UPDATE transfer_batches SET version=version+1 WHERE id=$1',[b.id]);
   }
   // Preserve affected promises and claims; attention is not silent release/refund.
   await c.query(`UPDATE inventory_holds h SET transfer_attention='TRANSFER_RECONCILIATION_REQUIRED',version=version+1 WHERE h.state='ACTIVE' AND h.transfer_attention IS NULL AND EXISTS(SELECT 1 FROM inventory_claims cl JOIN transfer_pieces p ON p.id=cl.transfer_piece_id JOIN transfer_batches b ON b.id=p.batch_id WHERE cl.hold_id=h.id AND cl.active AND (b.issue IS NOT NULL OR (b.planned_ready_at<$1 AND p.state NOT IN ('READY','CLOSED'))))`,[now]);
   await c.query('INSERT INTO transfer_requests VALUES($1,$2,$3,$4)',[this.principal.subject,key,fp,batchId]);const result=await this.view(c,await this.batch(c,batchId!,'view'),now);await c.query('COMMIT');return {batch:result,replayed:false};
  }catch(e){await c?.query('ROLLBACK').catch(()=>{});if(e instanceof TransferError)throw e;const code=(e as {code?:string})?.code;if(['23505','23514','23503'].includes(code??''))throw new TransferError('TRANSFER_CONFLICT',409);if(['55P03','57014','40P01','40001'].includes(code??''))throw new TransferError('INDETERMINATE',503);throw new TransferError('TRANSFER_OPERATION_FAILED',500);}finally{c?.release();}
 }
}
