import test from 'node:test';import assert from 'node:assert/strict';
import {planPrivateRelease,applyPersistedPrivateRelease,type CatalogReleaseState,type ReleaseInput} from '../../packages/core/src/content/release-plan';
const now=new Date('2035-01-01');
const fixture=():CatalogReleaseState=>({current:null,draftIds:{'SKI/ja':'ja1','SKI/en':'en1'},commercialRevisions:{SKI:'terms1'},revisions:[{id:'ja1',offerCode:'SKI',locale:'ja',content:{title:'合成スキー',summary:'合成説明',fit_note:'店頭確認'},sourceRevision:null,translationApproved:true,mediaIds:['photo1'],commercialRevision:'terms1'},{id:'en1',offerCode:'SKI',locale:'en',content:{title:'Synthetic skis',summary:'Synthetic',fit_note:'Staff fitting required'},sourceRevision:'ja1',translationApproved:true,mediaIds:['photo1'],commercialRevision:'terms1'}],media:[{id:'photo1',processed:true,rightsConfirmed:true,rightsUntil:'2035-02-01T00:00:00Z',alt:'Synthetic test image',immutableSha256:'1'.repeat(64),internalOnly:false}],releases:[]});
const input:ReleaseInput={id:'release1',entries:['ja1','en1'],expectedCurrent:null,restoreOf:null};
test('private release plans exact revisions and applies complete manifest/current/audit/outbox result atomically in fixture',()=>{const s=fixture(),p=planPrivateRelease(s,input,now);assert.deepEqual(p.issues,[]);const result=applyPersistedPrivateRelease(s,JSON.parse(JSON.stringify(p)),now);assert.equal(result.state.current,'release1');assert.equal(result.outbox.releaseId,'release1');assert.equal(result.productionPublished,false);assert.equal(s.current,null);assert.equal(result.release.entries.length,2);});
test('stale draft, current pointer, media checksum or expired rights cannot reuse a prior validation',()=>{for(const mutate of [(s:CatalogReleaseState)=>s.draftIds['SKI/ja']='ja2',(s:CatalogReleaseState)=>s.media[0]!.immutableSha256='2'.repeat(64),(s:CatalogReleaseState)=>s.media[0]!.rightsConfirmed=false,(s:CatalogReleaseState)=>s.commercialRevisions.SKI='terms2']){const s=fixture(),p=planPrivateRelease(s,input,now);mutate(s);assert.throws(()=>applyPersistedPrivateRelease(s,p,now));assert.equal(s.releases.length,0);}const s=fixture(),p=planPrivateRelease(s,input,now);assert.throws(()=>applyPersistedPrivateRelease(s,p,new Date('2035-02-01')),{code:'RELEASE_INVALID'});s.current='other';assert.throws(()=>applyPersistedPrivateRelease(s,p,now),{code:'RELEASE_CURRENT_STALE'});});
test('no partial release or hidden language fallback; internal/unprocessed photos and stale translation reject',()=>{for(const mutate of [(s:CatalogReleaseState)=>s.media[0]!.internalOnly=true,(s:CatalogReleaseState)=>s.media[0]!.processed=false,(s:CatalogReleaseState)=>s.revisions[1]!.sourceRevision='missing',(s:CatalogReleaseState)=>s.revisions[1]!.translationApproved=false]){const s=fixture();mutate(s);const p=planPrivateRelease(s,input,now);assert.ok(p.issues.length);assert.throws(()=>applyPersistedPrivateRelease(s,p,now),{code:'RELEASE_INVALID'});}const s=fixture();assert.ok(planPrivateRelease(s,{...input,entries:['en1']},now).issues.some(i=>i.code==='TRANSLATION_UNVERIFIED_OR_STALE'));});
test('restore creates a new private release and rechecks current rights/commercial mapping; never rewrites history',()=>{let s=fixture();const first=applyPersistedPrivateRelease(s,planPrivateRelease(s,input,now),now);s=first.state;const previous=JSON.stringify(s.releases[0]);const restoration={...input,id:'release2',expectedCurrent:'release1',restoreOf:'release1'};const plan=planPrivateRelease(s,restoration,now);const restored=applyPersistedPrivateRelease(s,plan,now);assert.equal(restored.state.releases.length,2);assert.equal(JSON.stringify(restored.state.releases[0]),previous);s.media[0]!.rightsConfirmed=false;assert.throws(()=>applyPersistedPrivateRelease(s,plan,now),{code:'RELEASE_INVALID'});});
