import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {PrivateContentWorkflow,type ContentPermission,type ContentRepository,type ContentWorkflowState} from '../../packages/core/src/content/workflow';
// Explicit local fake adapter. This proves domain/CAS behavior, not PostgreSQL isolation
// or real CONTENT permissions. No fixture authority is imported by application routes.
class Fixture implements ContentRepository{
 state:ContentWorkflowState={catalog:{current:null,draftIds:{'SKI/ja':'j1','BOARD/ja':'b1'},commercialRevisions:{SKI:'c1',BOARD:'c1'},revisions:['SKI','BOARD'].map((offerCode,i)=>({id:i?'b1':'j1',offerCode,locale:'ja',content:{title:'Synthetic '+offerCode,summary:'old',fit_note:''},sourceRevision:null,translationApproved:true,mediaIds:['m1'],commercialRevision:'c1'})),media:[{id:'m1',processed:true,rightsConfirmed:true,rightsUntil:'2035-02-01T00:00:00Z',alt:'synthetic',immutableSha256:'1'.repeat(64),internalOnly:false}],releases:[]},plans:{},requests:{},audit:[],outbox:[]};
 grants=new Map([['synthetic-editor',new Set<ContentPermission>(['CONTENT_EDIT','CONTENT_BULK','CONTENT_PUBLISH'])]]);private tail=Promise.resolve();afterLock:(()=>Promise<void>)|undefined;
 async transaction<T>(fn:(state:ContentWorkflowState)=>Promise<T>){let done!:()=>void;const prior=this.tail;this.tail=new Promise<void>(r=>done=r);await prior;try{await this.afterLock?.();const draft=structuredClone(this.state),result=await fn(draft);this.state=draft;return result;}finally{done();}}
 async assert(subject:string,permission:ContentPermission){if(!this.grants.get(subject)?.has(permission))throw new Error('CONTENT_FORBIDDEN');}
 service(){return new PrivateContentWorkflow(this,this,()=>new Date('2035-01-01'));}
}
const subject='synthetic-editor',header='schema_version,offer_code,locale,expected_revision,field,operation,value\n';
test('server-stored bulk plan commits good targets and preserves invalid ones; idempotent response loss does not repeat revisions',async()=>{const f=new Fixture(),s=f.service(),p=await s.prepareBulk(subject,randomUUID(),header+'1,SKI,ja,1,summary,SET,new\n1,BOARD,ja,1,price,SET,5000');assert.equal(p.state,'PARTIAL_VALIDATION');const key=randomUUID(),a=await s.commitBulk(subject,key,p.planId,p.hash);assert.equal(a.state,'PARTIAL');assert.equal(f.state.catalog.revisions.length,3);assert.equal(f.state.catalog.draftIds['BOARD/ja'],'b1');assert.deepEqual(await s.commitBulk(subject,key,p.planId,p.hash),a);assert.equal(f.state.catalog.revisions.length,3);assert.equal(f.state.catalog.current,null);await assert.rejects(s.commitBulk(subject,randomUUID(),p.planId,'0'.repeat(64)),/STORED_PLAN_MISMATCH/);});
test('two editors of same revision: only one commits; old immutable content remains',async()=>{const f=new Fixture(),s=f.service(),ops=['one','two'].map(title=>s.saveDraft(subject,randomUUID(),'SKI','ja',1,{title,summary:'',fit_note:''}));const results=await Promise.allSettled(ops);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(f.state.catalog.revisions.length,3);assert.equal(f.state.catalog.revisions.find(r=>r.id==='j1')!.content.title,'Synthetic SKI');});
test('revocation after lock wait stops a previously authorized edit and replay',async()=>{const f=new Fixture(),s=f.service();let entered!:()=>void,release!:()=>void;const at=new Promise<void>(r=>entered=r),gate=new Promise<void>(r=>release=r);f.afterLock=async()=>{entered();await gate;};const op=s.saveDraft(subject,randomUUID(),'SKI','ja',1,{title:'new',summary:'',fit_note:''});await at;f.grants.get(subject)!.delete('CONTENT_EDIT');release();await assert.rejects(op,/CONTENT_FORBIDDEN/);assert.equal(f.state.catalog.revisions.length,2);assert.equal(f.state.audit.length,0);});
test('release current/audit/outbox commit once; another actor cannot steal a prepared plan',async()=>{const f=new Fixture(),s=f.service(),p=await s.prepareRelease(subject,randomUUID(),['j1','b1'],null);assert.deepEqual(p.issues,[]);f.grants.set('synthetic-other',new Set(['CONTENT_PUBLISH']));await assert.rejects(s.commitRelease('synthetic-other',randomUUID(),p.planId,p.hash),/STORED_PLAN_MISMATCH/);const key=randomUUID(),a=await s.commitRelease(subject,key,p.planId,p.hash);assert.equal(a.productionPublished,false);assert.deepEqual(await s.commitRelease(subject,key,p.planId,p.hash),a);assert.equal(f.state.catalog.releases.length,1);assert.equal(f.state.outbox.length,1);assert.equal(f.state.audit.length,1);});
test('rights or draft change after release preview fails without partial pointer/outbox update',async()=>{for(const cause of ['rights','draft']){const f=new Fixture(),s=f.service(),p=await s.prepareRelease(subject,randomUUID(),['j1','b1'],null);if(cause==='rights')f.state.catalog.media[0]!.rightsConfirmed=false;else await s.saveDraft(subject,randomUUID(),'SKI','ja',1,{title:'new',summary:'',fit_note:''});await assert.rejects(s.commitRelease(subject,randomUUID(),p.planId,p.hash),/RELEASE_INVALID/);assert.equal(f.state.catalog.current,null);assert.equal(f.state.outbox.length,0);}});
