import test from 'node:test';
import assert from 'node:assert/strict';
import {csvRows,planContentBulk,applyPersistedContentPlan,safeHumanCsv,type Draft} from '../../packages/core/src/content/bulk-plan';
const current:Draft[]=[{offerCode:'SKI_PREMIUM',locale:'ja',revision:3,content:{title:'合成モデル',summary:'旧文',fit_note:'要確認'}},{offerCode:'BOARD_PREMIUM',locale:'en',revision:2,content:{title:'Synthetic board',summary:'Old',fit_note:'Unknown'}}];
const header='schema_version,offer_code,locale,expected_revision,field,operation,value\r\n';
test('content CSV quotes/BOM/newlines, SET/KEEP/CLEAR and machine round-trip preserve literal values',()=>{const text='\uFEFF'+header+'1,SKI_PREMIUM,ja,3,summary,SET,"改行\nと,""引用"""\r\n1,SKI_PREMIUM,ja,3,fit_note,CLEAR,\r\n1,SKI_PREMIUM,ja,3,title,KEEP,\r\n';const p=planContentBulk(current,text);assert.equal(p.issues.length,0);const next=applyPersistedContentPlan(current,JSON.parse(JSON.stringify(p)));assert.equal(next[0]!.content.summary,'改行\nと,"引用"');assert.equal(next[0]!.content.fit_note,'');assert.equal(next[0]!.revision,4);assert.deepEqual(current[0]!.content.summary,'旧文');assert.equal(csvRows('"x"\n')[0]![0],'x');});
test('same target is atomic; valid other target survives forbidden price, HTML, duplicate and stale rows',()=>{for(const bad of ['1,SKI_PREMIUM,ja,3,price,SET,5000','1,SKI_PREMIUM,ja,3,fit_note,SET,<img>','1,SKI_PREMIUM,ja,2,title,SET,stale','1,SKI_PREMIUM,ja,3,summary,SET,duplicate']){const p=planContentBulk(current,header+'1,SKI_PREMIUM,ja,3,summary,SET,new\n'+bad+'\n1,BOARD_PREMIUM,en,2,summary,SET,valid');assert.equal(p.issues.length,1);assert.deepEqual(p.targets.map(t=>t.offerCode),['BOARD_PREMIUM']);}});
test('stored plan rejects stale revision and tampering; no stock or price fields can be changed',()=>{const p=planContentBulk(current,header+'1,SKI_PREMIUM,ja,3,title,SET,New');assert.throws(()=>applyPersistedContentPlan([{...current[0]!,revision:4},current[1]!],p),{code:'BULK_PLAN_STALE'});const altered=structuredClone(p);altered.targets[0]!.after.title='Tampered';assert.throws(()=>applyPersistedContentPlan(current,altered),{code:'PLAN_HASH_MISMATCH'});assert.throws(()=>applyPersistedContentPlan(applyPersistedContentPlan(current,p),p),{code:'BULK_PLAN_STALE'});assert.equal(planContentBulk(current,header+'1,UNKNOWN,ja,1,title,SET,No').targets.length,0);});
test('CSV bounds and human formula escaping remain separate from machine export',()=>{for(const text of ['a'.repeat(5*1024*1024+1),header+Array(1001).fill('1,SKI_PREMIUM,ja,3,title,KEEP,').join('\n'),'"unterminated','"closed"bad'])assert.throws(()=>csvRows(text));const exported=safeHumanCsv([['=HYPERLINK("x")',' @cmd','+1','-1','literal']]);assert.deepEqual(csvRows(exported)[0],["'=HYPERLINK(\"x\")","' @cmd","'+1","'-1",'literal']);});
