import test from 'node:test';
import assert from 'node:assert/strict';
import {intakeWindow,holdScope,type IntakeHold} from '../../packages/contracts/src/hold-intake';
import {normalizePeriod,canonical} from '../../packages/contracts/src/hold';
import {skiSet} from '../inventory/fixture';
function fixture(){const c=skiSet('2035-07-01');c.period={startDate:'2035-07-01',endDate:'2035-07-02',slot:'MULTIDAY'};c.members.push({...structuredClone(c.members[0]!),key:'person-b'});const h:IntakeHold={id:'synthetic',reservation_id:c.reservationId,owner_id:'synthetic',conditions:c,expires_at:new Date('2035-07-01T17:05:00+09:00'),due_at:new Date(normalizePeriod(c.period).dueAt),state:'ACTIVE',payment_state:'NONE',allocation_stage:'PROVISIONAL',version:1,transfer_attention:null};return {c,h,now:new Date('2035-07-01T17:01:00+09:00')};}
test('same scope continuation has future expiry and preserves all saved conditions/fingerprints',()=>{const {c,h,now}=fixture(),before=canonical(c),after=structuredClone(c);after.members[0]!.items[0]!.variantIds=['00000000-0000-4000-8000-000000001102'];const d=intakeWindow(after,now,h);assert.equal(d.mode,'HOLD_CONTINUATION');assert.equal(d.quoteBoundaryAt,h.expires_at.toISOString());assert.equal(canonical(c),before);assert.throws(()=>intakeWindow(after,now),{code:'INTAKE_CLOSED'});});
test('single-member candidate validates full group scope and exact member/version',()=>{const {c,h,now}=fixture(),single={...c,members:[c.members[1]!]};const context={scope:holdScope(c),memberKey:'person-b',expectedVersion:1};assert.equal(intakeWindow(single,now,h,context).mode,'HOLD_CONTINUATION');assert.throws(()=>intakeWindow(single,now,h,{...context,memberKey:'person-a'}),{code:'INVALID_CONTINUATION_CONTEXT'});assert.throws(()=>intakeWindow(single,now,h,{...context,expectedVersion:2}),{code:'STALE_HOLD_VERSION'});const scope=structuredClone(context.scope);scope.members.pop();assert.throws(()=>intakeWindow(single,now,h,{...context,scope}),{code:'INVALID_CONTINUATION_CONTEXT'});});
test('after-close changed non-size conditions fall back to new intake; future new conditions accepted',()=>{const {c,h,now}=fixture();for(const key of ['returnStore','period','members'] as const){const x=structuredClone(c);if(key==='returnStore')x.returnStore='ONSEN_BASE';if(key==='period')x.period.endDate='2035-07-03';if(key==='members')x.members.pop();assert.throws(()=>intakeWindow(x,now,h),{code:'INTAKE_CLOSED'});}const future=structuredClone(c);future.period={startDate:'2035-07-03',endDate:'2035-07-04',slot:'MULTIDAY'};assert.equal(intakeWindow(future,now,h).mode,'NEW_INTAKE');});
test('expiry, due, fixed/payment/attention and unproven acceptance are never exceptions',()=>{const {c,h,now}=fixture();assert.throws(()=>intakeWindow(c,h.expires_at,h),{code:'HOLD_EXPIRED_OR_RELEASED'});assert.throws(()=>intakeWindow(c,now,{...h,due_at:now}),{code:'PERIOD_ENDED'});for(const payment_state of ['PENDING','UNKNOWN','SUCCESS'] as const)assert.throws(()=>intakeWindow(c,now,{...h,payment_state}),{code:'PAYMENT_RECONCILIATION_REQUIRED'});for(const allocation_stage of ['PREPARATION_FIXED','RENTAL_FIXED'])assert.throws(()=>intakeWindow(c,now,{...h,allocation_stage}),{code:'ALLOCATION_FIXED'});assert.throws(()=>intakeWindow(c,now,{...h,transfer_attention:'issue'}),{code:'TRANSFER_ALLOCATION_FIXED'});assert.throws(()=>intakeWindow(c,new Date('2035-07-01T17:06:00+09:00'),{...h,expires_at:new Date('2035-07-01T17:15:00+09:00')}),{code:'HOLD_ACCEPTANCE_NOT_PROVEN'});});
