import test from 'node:test';import assert from 'node:assert/strict';import sharp from 'sharp';import {preparePhotoDrafts,photoMetadata} from '../../packages/core/src/content/media-plan';
const make=()=>sharp({create:{width:16,height:24,channels:3,background:'#abcdef'}}).withMetadata({orientation:6}).jpeg().toBuffer();
test('real decoder re-encodes and strips EXIF; identical bytes never inherit binding rights',async()=>{const bytes=await make();assert.ok((await sharp(bytes).metadata()).exif);const [a,b]=await preparePhotoDrafts([{filename:'synthetic-ski.jpg',bytes,binding:{modelId:'00000000-0000-0000-0000-000000000001',season:'2026/27',sport:'SKI',role:'COVER',rightsEvidence:'SYNTHETIC claim, unverified'}},{filename:'synthetic-board.jpg',bytes,binding:null}]);assert.equal(a!.sourceSha256,b!.sourceSha256);assert.equal(a!.rights,'UNVERIFIED');assert.equal(b!.binding,null);assert.equal(b!.publication,'DRAFT_ONLY');const clean=await sharp(a!.webp).metadata();assert.equal(clean.exif,undefined);assert.equal(clean.icc,undefined);assert.equal(clean.width,24);assert.equal(clean.height,16);assert.ok(!('webp' in photoMetadata(a!)));});
test('traversal, disguised SVG/HTML, extension mismatch, invalid decode and duplicate filename reject before any storage',async()=>{const bytes=await make();for(const f of [{filename:'../x.jpg',bytes},{filename:'x.svg',bytes},{filename:'x.png',bytes},{filename:'x.jpg',bytes:Buffer.from('<svg/>')},{filename:'x.jpg',bytes:Buffer.alloc(0)}])await assert.rejects(preparePhotoDrafts([{...f,binding:null}]));await assert.rejects(preparePhotoDrafts([{filename:'x.jpg',bytes,binding:null},{filename:'X.JPG',bytes,binding:null}]));await assert.rejects(preparePhotoDrafts(Array(201).fill({filename:'x.jpg',bytes,binding:null})),{code:'PHOTO_BATCH_LIMIT'});});

test('P0 bounded320/640/960/1440/1920 WebP and JPEG derivatives preserve aspect and strip metadata',async()=>{
 const bytes=await sharp({create:{width:2048,height:1024,channels:3,background:'#c1c2c3'}}).withMetadata().png().toBuffer();
 const [draft]=await preparePhotoDrafts([{filename:'synthetic-wide.png',bytes,binding:null}]);assert.equal(draft!.derivatives.length,10);
 for(const d of draft!.derivatives){assert.equal(d.width,d.requestedWidth);assert.equal(d.height,d.requestedWidth/2);const m=await sharp(d.bytes).metadata();assert.equal(m.format,d.format);assert.equal(m.exif,undefined);assert.equal(m.icc,undefined);}
 assert.ok(!JSON.stringify(photoMetadata(draft!)).includes('"type":"Buffer"'));assert.equal(draft!.publication,'DRAFT_ONLY');
});
