import test from 'node:test';
import assert from 'node:assert/strict';
import {TLSSocket} from 'node:tls';
import {proveNeonClientTls,phase6NeonHostname as host} from '../../packages/db/src/neon-tls';
const config={host,ssl:{rejectUnauthorized:true}};
// Fixtures exercise rejection branches only; actual encrypted/chain proof is hosted evidence.
function fixture(){const stream=Object.create(TLSSocket.prototype);Object.assign(stream,{encrypted:true,authorized:true,servername:host,_tlsOptions:{rejectUnauthorized:true},getProtocol:()=> 'TLSv1.3',getPeerCertificate:()=>({raw:Buffer.from('synthetic'),subjectaltname:'DNS:'+host})});return {connection:{stream}};}
test('safe proof contains only allowlisted fields, no certificate or hostname',()=>{const p=proveNeonClientTls(fixture(),config,{});assert.equal(p.protocol,'TLSv1.3');assert.equal(JSON.stringify(p).includes(host),false);assert.equal(JSON.stringify(p).includes('synthetic'),false);});
for(const kind of ['plain','unencrypted','unauthorized','insecure-socket','wrong-sni','old-protocol','missing-cert','wrong-san'])test('TLS rejection: '+kind,()=>{const c=fixture(),s=c.connection.stream;if(kind==='plain')c.connection.stream={};if(kind==='unencrypted')s.encrypted=false;if(kind==='unauthorized')s.authorized=false;if(kind==='insecure-socket')s._tlsOptions.rejectUnauthorized=false;if(kind==='wrong-sni')s.servername='other.neon.tech';if(kind==='old-protocol')s.getProtocol=()=> 'TLSv1.1';if(kind==='missing-cert')s.getPeerCertificate=()=>({});if(kind==='wrong-san')s.getPeerCertificate=()=>({raw:Buffer.from('synthetic'),subjectaltname:'DNS:other.neon.tech'});assert.throws(()=>proveNeonClientTls(c,config,{}),{message:'PHASE6_CLIENT_TLS_PROOF_FAILED'});});
test('TLS configuration cannot use query overrides, custom CA or insecure ambient settings',()=>{for(const c of [{host:'other.neon.tech',ssl:{rejectUnauthorized:true}},{host,ssl:{rejectUnauthorized:false}},{host,ssl:{rejectUnauthorized:true,ca:'synthetic'}}])assert.throws(()=>proveNeonClientTls(fixture(),c,{}));for(const key of ['NODE_TLS_REJECT_UNAUTHORIZED','NODE_EXTRA_CA_CERTS','SSL_CERT_FILE','SSL_CERT_DIR'])assert.throws(()=>proveNeonClientTls(fixture(),config,{[key]:'synthetic'}));});
