import {test} from 'node:test';
import assert from 'node:assert/strict';
import {flowHash} from '../../packages/contracts/src/rental-flow';
import {decidePaymentProjection as decide,verifyProjectionSource,validateProjectionReference,validateSavedProjection,projectionClaims,TransactionalPaymentProjection,type ProjectionState} from '../../packages/core/src/payment/payment-projection';
import {PgPaymentProjection} from '../../packages/db/src/payment-projection';
import {clock,id,stateFixture,observation,reference,sourceFixture,claimFixture,ProjectionSqlFixture} from '../fixtures/payment-projection';
const service=(f:ProjectionSqlFixture)=>new TransactionalPaymentProjection(new PgPaymentProjection(f));
for(const [status,decision,mutation] of [['PENDING','KEEP_PENDING','PENDING'],['COMPLETED','APPLY_COMPLETED','COMPLETED'],['FAILED','APPLY_FAILED','FAILED'],['CANCELED','APPLY_CANCELED','FAILED']] as const)test('projection '+status+' existing business semantics',()=>{const d=decide(stateFixture(),observation(status),clock);assert.equal(d.decision,decision);assert.equal(d.mutation,mutation);});
for(const [field,value] of Object.entries({providerId:'other',referenceId:id(90),idempotencyKey:id(91),merchantId:'other',locationId:'other',amountJpy:101,currency:'USD',status:'UNKNOWN',updatedAt:'bad',completedAt:null}))test('identity or provider contract mismatch '+field,()=>assert.equal(decide(stateFixture(),{...observation(),[field]:value} as never,clock).decision,'BLOCK_IDENTITY_MISMATCH'));
for(const value of [0,-1,1.1,100000001,Number.MAX_SAFE_INTEGER+1])test('bounded JPY amount '+value,()=>{const s=stateFixture();s.attempt.expected.amountJpy=value;assert.equal(decide(s,{...observation(),amountJpy:value},clock).decision,'BLOCK_IDENTITY_MISMATCH');});
for(const [name,change,reason] of [
 ['expired hold',(s:ProjectionState)=>{s.hold!.expiresAt=clock.toISOString();},'BLOCK_EXPIRED_HOLD'],
 ['missing gear',(s:ProjectionState)=>{s.gearClaimsIntact=false;},'BLOCK_INVENTORY_DRIFT'],
 ['missing wear',(s:ProjectionState)=>{s.wearClaimsIntact=false;},'BLOCK_INVENTORY_DRIFT'],
 ['transfer attention',(s:ProjectionState)=>{s.hold!.transferAttention='NEEDS_REVIEW';},'BLOCK_TRANSFER_ATTENTION'],
 ['canceled transfer',(s:ProjectionState)=>{s.forbiddenTransfer=true;},'BLOCK_TRANSFER_ATTENTION'],
 ['overdue unready transfer',(s:ProjectionState)=>{s.unreadyTransferAt=new Date(clock.getTime()-1).toISOString();},'BLOCK_TRANSFER_ATTENTION'],
 ['snapshot hash',(s:ProjectionState)=>{s.booking.priceHash='f'.repeat(64);},'BLOCK_PRICE_INTEGRITY'],
 ['quote relation',(s:ProjectionState)=>{s.quote!.holdId=id(90);},'BLOCK_PRICE_INTEGRITY'],
 ['quote hash',(s:ProjectionState)=>{s.quote!.snapshotHash='f'.repeat(64);},'BLOCK_PRICE_INTEGRITY'],
 ['coupon redemption',(s:ProjectionState)=>{s.quote!.couponId=id(90);},'BLOCK_PRICE_INTEGRITY'],
 ['missing quote',(s:ProjectionState)=>{s.quote=null;},'BLOCK_PRICE_INTEGRITY'],
 ['fixed allocation',(s:ProjectionState)=>{s.hold!.allocationStage='PREPARATION_FIXED';},'BLOCK_INVALID_TRANSITION'],
 ['released hold',(s:ProjectionState)=>{s.hold!.state='RELEASED';},'BLOCK_INVALID_TRANSITION'],
 ['successful hold',(s:ProjectionState)=>{s.hold!.paymentState='SUCCESS';},'BLOCK_INVALID_TRANSITION'],
 ['wrong reservation',(s:ProjectionState)=>{s.hold!.reservationId=id(90);},'BLOCK_INVALID_TRANSITION'],
 ['wrong actor',(s:ProjectionState)=>{s.attempt.actor='someone-else';},'BLOCK_IDENTITY_MISMATCH'],
 ['production mode',(s:ProjectionState)=>{s.booking.mode='PRODUCTION';},'BLOCK_IDENTITY_MISMATCH'],
] as const)test(name+' does not force confirmation/reacquire/refund',()=>{const s=stateFixture();change(s);const before=structuredClone(s);const d=decide(s,observation(),clock);assert.equal(d.decision,reason);assert.equal(d.operatorActionRequired,true);assert.notEqual(d.mutation,'COMPLETED');assert.deepEqual(s,before);});
test('return due exact boundary is closed even with remaining hold time',()=>{const s=stateFixture();s.hold!.expiresAt='2035-01-01T09:00:00.000Z';assert.equal(decide(s,observation(),new Date(s.hold!.dueAt)).decision,'BLOCK_EXPIRED_HOLD');assert.equal(decide(s,observation(),new Date(Date.parse(s.hold!.dueAt)-1)).decision,'APPLY_COMPLETED');});
test('early-discount qualification remains tied to provider completed time',()=>{const s=stateFixture();s.booking.priceSnapshot.advanceDiscountJpy=5;s.booking.priceHash=flowHash(s.booking.priceSnapshot);s.quote!.snapshot=s.booking.priceSnapshot;s.quote!.snapshotHash=s.booking.priceHash;assert.equal(decide(s,observation(),clock).decision,'BLOCK_PRICE_INTEGRITY');});
test('chargeReady and snapshot conditions cannot be tampered even with a recomputed hash',()=>{for(const change of [(s:ProjectionState)=>{s.booking.priceSnapshot.chargeReady=true;},(s:ProjectionState)=>{s.booking.priceSnapshot.conditions={};}]){const s=stateFixture();change(s);s.booking.priceHash=flowHash(s.booking.priceSnapshot);s.quote!.snapshotHash=s.booking.priceHash;assert.equal(decide(s,observation(),clock).decision,'BLOCK_PRICE_INTEGRITY');}});
test('same timestamp changed payload is BLOCK_CONFLICT, overriding only the new projection path',()=>{const s=stateFixture();s.previous=observation('PENDING');assert.equal(decide(s,observation(),clock).decision,'BLOCK_CONFLICT');assert.equal(decide(s,observation('PENDING'),clock).decision,'NOOP_DUPLICATE');});
test('terminal completed and duplicate/stale observations never downgrade',()=>{const s=stateFixture();s.previous=observation();s.attempt.state='COMPLETED';s.attempt.providerState='COMPLETED';s.attempt.providerUpdatedAt=clock.toISOString();s.attempt.completedAt=clock.toISOString();s.booking.state='CONFIRMED_DEV';s.booking.confirmedAt=clock.toISOString();assert.equal(decide(s,observation(),clock).decision,'NOOP_DUPLICATE');assert.equal(decide(s,{...observation('PENDING'),updatedAt:'2034-12-31T23:59:59.000Z'},clock).decision,'NOOP_STALE');assert.equal(decide(s,{...observation('FAILED'),updatedAt:'2035-01-01T00:00:01.000Z'},new Date(clock.getTime()+1000)).decision,'NOOP_TERMINAL');});
for(const status of ['FAILED','CANCELED'])test(status+' cannot be silently upgraded or retried',()=>{const s=stateFixture();s.attempt.state='FAILED';s.attempt.providerState=status;assert.equal(decide(s,observation(),clock).decision,'BLOCK_INVALID_TRANSITION');assert.equal(decide(s,observation('PENDING'),clock).decision,'NOOP_TERMINAL');});
test('completed truth in REVIEW requires an operator even if conditions later look repaired',()=>{const s=stateFixture();s.previous=observation();s.attempt.state='REVIEW';assert.equal(decide(s,observation(),clock).decision,'REQUIRES_OPERATOR_RECONCILIATION');});
for(const field of ['truthFingerprint','observationFingerprint','expectedRevision','truthRevision','bookingId','attemptId','jobId'])test('invalid projection reference '+field,()=>{const r=reference();Object.assign(r,{[field]:field.endsWith('Revision')?-1:'invalid'});assert.throws(()=>validateProjectionReference(r));});
for(const [field,value] of Object.entries({environment:'PRODUCTION',state:'CLAIMED',securityBlocked:true,truthRevision:2,decision:'ACCEPT_FAILED',decisionFingerprint:'b'.repeat(64),contextFingerprint:'c'.repeat(64),paymentId:'other',merchantId:'other',observation:null}))test('untrusted persisted source fails '+field,()=>{const src=sourceFixture();assert.throws(()=>verifyProjectionSource(reference(src),{...src,[field]:value},clock),{code:'PROJECTION_SOURCE_NOT_ACCEPTED'});});
test('only ten normalized provider fields cross the source boundary',()=>{const src=sourceFixture();src.observation={...src.observation!,card_data:'SYNTHETIC_PRIVATE'} as never;const clean=verifyProjectionSource(reference(sourceFixture()),src,clock);assert.equal(Object.keys(clean).length,10);assert.ok(!JSON.stringify(clean).includes('SYNTHETIC_PRIVATE'));});
test('claim contract checks gear, wear, exact quantity and variant/model promise without inferred substitution',()=>{const s=stateFixture(),claims=claimFixture(s);assert.deepEqual(projectionClaims(s.booking.conditions,claims as never),{gear:true,wear:true});assert.equal(projectionClaims(s.booking.conditions,claims.slice(1) as never).gear,false);assert.equal(projectionClaims(s.booking.conditions,claims.slice(0,1) as never).wear,false);claims[1]!.quantity=2;assert.equal(projectionClaims(s.booking.conditions,claims as never).wear,false);claims[0]!.id=id(92);assert.equal(projectionClaims(s.booking.conditions,claims as never).gear,false);});
test('Premium exact model/season/length stays in claim validation',()=>{const s=stateFixture(),m=s.booking.conditions.members[0]!;m.tier='PREMIUM';m.items[0]!.modelPromise={modelId:id(40),variantId:id(6),season:'2034/35'};const c=claimFixture(s);assert.equal(projectionClaims(s.booking.conditions,c as never).gear,true);c[0]!.catalog_season='2033/34';assert.equal(projectionClaims(s.booking.conditions,c as never).gear,false);});

test('actual repository + scripted SQL: completion is one transaction, frozen commercial contract, safe audit',async()=>{const f=new ProjectionSqlFixture(),before=structuredClone(f.world);const result=await service(f).project(reference());assert.equal(result.decision,'APPLY_COMPLETED');assert.equal(f.world.b.state,'CONFIRMED_DEV');assert.equal(f.world.a.state,'COMPLETED');assert.equal(f.world.h.payment_state,'SUCCESS');assert.equal(f.world.events.length,1);assert.equal(f.world.receipts.length,1);assert.deepEqual(f.world.history,['attempt','booking','hold']);assert.deepEqual(f.world.b.price_snapshot,before.b.price_snapshot);assert.deepEqual(f.world.b.conditions,before.b.conditions);assert.deepEqual(f.world.h.expires_at,before.h.expires_at);assert.equal(f.world.notifications.length,0);assert.ok(!JSON.stringify(f.world.events).includes('example.invalid'));});
test('two simultaneous projects commit once; replay checks precede old revision and changed source',async()=>{const f=new ProjectionSqlFixture(),p=service(f);const [a,b]=await Promise.all([p.project(reference()),p.project(reference())]);assert.deepEqual([a.duplicate,b.duplicate].sort(),[false,true]);assert.equal(f.world.events.length,1);assert.equal(f.world.history.length,3);f.world.src.securityBlocked=true;f.now=new Date('2036-01-01T00:00:00Z');assert.equal((await p.project(reference())).duplicate,true);assert.equal(f.world.history.length,3);});
test('COMMIT response loss replays stored result without second projection/notification/history',async()=>{const f=new ProjectionSqlFixture();f.loseCommitResponse=true;await assert.rejects(service(f).project(reference()),{code:'PROJECTION_STORAGE_UNAVAILABLE'});assert.equal(f.world.events.length,1);assert.equal((await service(f).project(reference())).duplicate,true);assert.equal(f.world.history.length,3);});
for(const stage of ['BEGIN','SET LOCAL','SELECT pg_advisory_xact_lock(71820600)','UPDATE rental_payment_attempts','UPDATE rental_bookings','UPDATE inventory_holds','INSERT INTO payment_projection.heads','INSERT INTO payment_projection.events','INSERT INTO payment_projection.job_receipts','COMMIT'])test('crash at '+stage+' rolls back all business/history/journal changes',async()=>{const f=new ProjectionSqlFixture(),before=structuredClone(f.world);f.failAt=stage;await assert.rejects(service(f).project(reference()),{code:'PROJECTION_STORAGE_UNAVAILABLE'});assert.deepEqual(f.world,before);assert.equal(f.released.at(-1),true);});
test('stale transaction revision rejects even after proposed writes and rolls back',async()=>{const f=new ProjectionSqlFixture(),before=structuredClone(f.world);f.staleHeadWrite=true;await assert.rejects(service(f).project(reference()),{code:'STALE_PROJECTION_REVISION'});assert.deepEqual(f.world,before);});
test('expired HOLD persists completed provider truth but not reservation or stock resurrection',async()=>{const f=new ProjectionSqlFixture();f.world.h.expires_at=new Date(clock);const claims=structuredClone(f.world.claims);const result=await service(f).project(reference());assert.equal(result.decision,'BLOCK_EXPIRED_HOLD');assert.equal(result.providerStatus,'COMPLETED');assert.equal(f.world.a.provider_state,'COMPLETED');assert.equal(f.world.a.state,'REVIEW');assert.equal(f.world.b.state,'PAYMENT_REVIEW');assert.equal(f.world.h.confirmed_at,null);assert.equal(f.world.h.payment_state,'PENDING');assert.deepEqual(f.world.claims,claims);assert.equal((await service(f).project(reference())).duplicate,true);});
for(const kind of ['GEAR','WEAR'])test('missing '+kind+' witness blocks completed projection in actual repository path',async()=>{const f=new ProjectionSqlFixture();f.world.claims=f.world.claims.filter(c=>c.kind!==kind);const res=await service(f).project(reference());assert.equal(res.decision,'BLOCK_INVENTORY_DRIFT');assert.equal(f.world.b.state,'PAYMENT_REVIEW');assert.equal(f.world.a.provider_state,'COMPLETED');});
test('DB time is sampled after locks and before first business write',async()=>{const f=new ProjectionSqlFixture();let clocks=0;f.onQuery=async sql=>{if(sql.includes('inventory_clock()')&&++clocks===2)f.now=new Date(f.world.h.expires_at);};const result=await service(f).project(reference());assert.equal(result.decision,'BLOCK_EXPIRED_HOLD');assert.equal(f.world.b.state,'PAYMENT_REVIEW');});
test('transfer deadline crossing during source lock wait blocks at final decision',async()=>{const f=new ProjectionSqlFixture();f.world.transfer.unready_at=new Date(clock.getTime()+1).toISOString();f.onQuery=async sql=>{if(sql.includes('payment_reconciliation.jobs WHERE id=$1 FOR UPDATE'))f.now=new Date(clock.getTime()+2);};assert.equal((await service(f).project(reference())).decision,'BLOCK_TRANSFER_ATTENTION');});
for(const status of ['PENDING','FAILED','CANCELED'] as const)test(status+' repository transition keeps hold witness and TTL',async()=>{const f=new ProjectionSqlFixture();f.world.src=sourceFixture(observation(status));const before=structuredClone(f.world.h);await service(f).project(reference(f.world.src));assert.equal(f.world.a.state,status==='PENDING'?'PENDING':'FAILED');assert.equal(f.world.h.payment_state,status==='PENDING'?'PENDING':'FAILURE');assert.equal(f.world.h.state,'ACTIVE');assert.deepEqual(f.world.h.expires_at,before.expires_at);assert.equal(f.world.claims.length,3);});
test('normal or production database name is blocked before business lock',async()=>{const f=new ProjectionSqlFixture();f.database='production';await assert.rejects(service(f).project(reference()),{code:'PROJECTION_DEVELOPMENT_DB_ONLY'});assert.ok(!f.calls.some(c=>c.sql.includes('pg_advisory_xact_lock')));});
test('source mutation blocks and performs no updates; attempt/version mismatch does not acquire source locks',async()=>{const f=new ProjectionSqlFixture();f.world.src.securityBlocked=true;await assert.rejects(service(f).project(reference()),{code:'PROJECTION_SOURCE_NOT_ACCEPTED'});assert.equal(f.world.history.length,0);const v=new ProjectionSqlFixture();await assert.rejects(service(v).project({...reference(),expectedRevision:1}),{code:'STALE_PROJECTION_REVISION'});assert.ok(!v.calls.some(c=>c.sql.includes('FROM payment_reconciliation')));});
test('production constructor/method gate and no ambient HTTP',async()=>{const old=process.env.NODE_ENV;Reflect.set(process.env,'NODE_ENV','production');try{assert.throws(()=>service(new ProjectionSqlFixture()),{code:'PROJECTION_NOT_ACTIVATED'});}finally{if(old===undefined)Reflect.deleteProperty(process.env,'NODE_ENV');else Reflect.set(process.env,'NODE_ENV',old);}const fetch=globalThis.fetch;globalThis.fetch=async()=>{throw new Error('FORBIDDEN_EXTERNAL_CALL');};try{const f=new ProjectionSqlFixture();assert.equal((await service(f).project(reference())).decision,'APPLY_COMPLETED');}finally{globalThis.fetch=fetch;}});

test('same observation proof does not cross from Square Sandbox to a simulation booking',async()=>{const f=new ProjectionSqlFixture();f.world.b.mode='SIMULATED_DEV';await assert.rejects(service(f).project(reference()),{code:'PROJECTION_MODE_MISMATCH'});assert.equal(f.world.history.length,0);});
test('expiry after first write is fenced by SQL and rolls back; same key later records blocked truth',async()=>{const f=new ProjectionSqlFixture(),before=structuredClone(f.world);f.onQuery=async sql=>{if(sql.startsWith('UPDATE inventory_holds'))f.now=new Date(f.world.h.expires_at);};await assert.rejects(service(f).project(reference()),{code:'PROJECTION_TIME_BOUNDARY_CHANGED'});assert.deepEqual(f.world,before);f.onQuery=null;assert.equal((await service(f).project(reference())).decision,'BLOCK_EXPIRED_HOLD');});

test('new R12 generation of an already projected observation links a new receipt without business/audit replay',async()=>{const f=new ProjectionSqlFixture(),p=service(f);await p.project(reference());const history=f.world.history.length;f.world.src.jobId=id(19);const r=reference(f.world.src);assert.equal((await p.project(r)).duplicate,true);assert.equal(f.world.history.length,history);assert.equal(f.world.events.length,1);assert.equal(f.world.receipts.length,2);await p.project(r);assert.equal(f.world.receipts.length,2);});
test('new job reference cannot borrow an old projection receipt without current source verification',async()=>{const f=new ProjectionSqlFixture(),p=service(f);await p.project(reference());f.world.src.jobId=id(19);f.world.src.securityBlocked=true;await assert.rejects(p.project(reference(f.world.src)),{code:'PROJECTION_SOURCE_NOT_ACCEPTED'});assert.equal(f.world.receipts.length,1);});

test('tampered saved result is rejected rather than returned as trusted internal data',async()=>{const f=new ProjectionSqlFixture(),p=service(f);await p.project(reference());(f.world.events[0]!.result as Record<string,unknown>).contact='SYNTHETIC_PRIVATE';await assert.rejects(p.project(reference()),{code:'INVALID_SAVED_PROJECTION'});assert.equal(f.world.history.length,3);});
test('provisional wear and gear require matching bucket size and exact one cross-kind witness',()=>{
 const s=stateFixture(),base=claimFixture(s),toProvisional=(c:typeof base[number])=>({kind:'PROVISIONAL' as const,requirement_key:c.requirement_key,day:c.day,quantity:1,family:c.family,age:c.age,booking_size:'M',requestedVariant:{...c,size:'M'}});
 const claims=base.map(toProvisional);assert.deepEqual(projectionClaims(s.booking.conditions,claims as never),{gear:true,wear:true});
 assert.equal(projectionClaims(s.booking.conditions,[...claims,base[1]!] as never).wear,false);
 assert.equal(projectionClaims(s.booking.conditions,claims.slice(1) as never).gear,false);
 claims[1]!.booking_size='L';assert.equal(projectionClaims(s.booking.conditions,claims as never).wear,false);claims[1]!.booking_size='M';
 s.booking.conditions.members[0]!.tier='PREMIUM';assert.equal(projectionClaims(s.booking.conditions,claims as never).gear,false);
});
test('POLE needs exactly one physical claim or durable matching exemption',()=>{
 const s=stateFixture(),m=s.booking.conditions.members[0]!;m.product='SKI_SET';m.items.push({family:'SKI_BOOT',variantIds:[id(20)]},{family:'POLE',variantIds:[id(21)]});
 const physical=claimFixture(s),claims=physical.filter(c=>c.family!=='POLE');
 assert.equal(projectionClaims(s.booking.conditions,claims as never).gear,false);
 const pole=physical.find(c=>c.family==='POLE')!,exemption={kind:'POLE_EXEMPT',requirement_key:pole.requirement_key,day:pole.day,quantity:1,store_id:s.booking.conditions.pickupStore,variant_ids:[id(21)]};
 assert.equal(projectionClaims(s.booking.conditions,[...claims,exemption] as never).gear,true);
 assert.equal(projectionClaims(s.booking.conditions,[...physical,exemption] as never).gear,false);
 assert.equal(projectionClaims(s.booking.conditions,[...claims,{...exemption,store_id:'ONSEN_BASE'}] as never).gear,false);
});

for(const status of ['COMPLETED','FAILED','CANCELED','PENDING'] as const)test('cancelled booking records late '+status+' without inventory resurrection',()=>{const s=stateFixture();s.booking.state='CANCELLED';s.hold!.state='RELEASED';s.gearClaimsIntact=false;s.wearClaimsIntact=false;const plan=decide(s,observation(status),clock);assert.equal(plan.mutation,'CANCELLED_PAYMENT');assert.equal(s.booking.state,'CANCELLED');assert.equal(s.hold!.state,'RELEASED');});
test('cancelled payment still rejects amount and immutable price drift',()=>{const s=stateFixture();s.booking.state='CANCELLED';assert.equal(decide(s,{...observation(),amountJpy:101},clock).mutation,'NONE');s.quote!.snapshotHash='f'.repeat(64);assert.equal(decide(s,observation(),clock).decision,'BLOCK_PRICE_INTEGRITY');});

test('saved payment projection rejects mode/state crossings before replay',async()=>{
 const f=new ProjectionSqlFixture(),ref=reference(),saved=await service(f).project(ref);
 validateSavedProjection(saved,ref,'SQUARE_SANDBOX');
 assert.throws(()=>validateSavedProjection({...saved,bookingState:'CONFIRMED'},ref,'SQUARE_SANDBOX'),{code:'INVALID_SAVED_PROJECTION'});
 assert.throws(()=>validateSavedProjection(saved,ref,'SQUARE_PRODUCTION'),{code:'INVALID_SAVED_PROJECTION'});
 validateSavedProjection({...saved,bookingState:'CONFIRMED'},ref,'SQUARE_PRODUCTION');
});
