import {test} from 'node:test';
import assert from 'node:assert/strict';
import type {Pool} from 'pg';
import {BookingService} from '../../packages/core/src/payment/booking-service';
import type {PaymentGateway} from '../../packages/contracts/src/rental-flow';
import {TransactionalPaymentProjection} from '../../packages/core/src/payment/payment-projection';
import {PgPaymentProjection} from '../../packages/db/src/payment-projection';
import {ProjectionSqlFixture,observation,reference,id} from '../fixtures/payment-projection';
// Only auth is synthetic; actual BookingService transaction, methods, claims and view are executed.
// This is not proof of PostgreSQL or real session/permission enforcement.
class LocalFlow extends BookingService{
 constructor(f:ProjectionSqlFixture,gateway:PaymentGateway){super(f as unknown as Pool,f as unknown as Pool,{subject:'synthetic-actor',sessionId:'fixture-session'},gateway,{merchantId:'fixture-merchant',locations:{MOUNTAIN_BASE:'fixture-location',ONSEN_BASE:'fixture-location'},nodeEnv:'test',sandboxActivationId:'P4-SANDBOX-OWNER-R1'});}
 protected override async authorize(){return {subject:'synthetic-actor',storeIds:['MOUNTAIN_BASE','ONSEN_BASE']};}
}
const gateway:PaymentGateway={kind:'SQUARE_SANDBOX',async create(r){return {...observation(),referenceId:r.bookingId,idempotencyKey:r.idempotencyKey};},async lookup(){return observation();}};
const projection=(f:ProjectionSqlFixture)=>new TransactionalPaymentProjection(new PgPaymentProjection(f));
test('legacy startPayment vs projection uses the same global lock and does not create a second payment',async()=>{const f=new ProjectionSqlFixture();let creates=0;const flow=new LocalFlow(f,{...gateway,async create(r){creates++;return gateway.create(r);}});await Promise.all([projection(f).project(reference()),flow.startPayment(id(1),id(81))]);assert.equal(creates,0);assert.equal(f.world.b.state,'CONFIRMED_DEV');assert.equal(f.world.events.length,1);assert.equal(f.world.history.filter(x=>x==='booking').length,1);});
test('legacy reconcile then projection of same observation is duplicate/noop, not second confirmation',async()=>{const f=new ProjectionSqlFixture(),flow=new LocalFlow(f,gateway);await flow.reconcile(id(1));const history=f.world.history.length;const result=await projection(f).project(reference());assert.equal(result.decision,'NOOP_DUPLICATE');assert.equal(f.world.history.length,history);assert.equal(f.world.notifications.length,1);assert.equal(f.world.events.length,1);});
test('concurrent legacy reconcile and projection preserve one confirmation and old event dedupe',async()=>{const f=new ProjectionSqlFixture(),flow=new LocalFlow(f,gateway);await Promise.all([projection(f).project(reference()),flow.reconcile(id(1))]);assert.equal(f.world.b.state,'CONFIRMED_DEV');assert.equal(f.world.history.filter(x=>x==='booking').length,1);assert.equal(f.world.events.length,1);assert.equal(f.world.providerEvents.length,1);});
test('legacy create/startPayment/get/list synthetic path retains HOLD/quote/hash/claim checks',async()=>{const f=new ProjectionSqlFixture();f.world.b=null as never;f.world.a=null as never;f.world.h.payment_state='NONE';const flow=new LocalFlow(f,gateway);const created=await flow.create(id(80),id(3),{displayName:'SYNTHETIC Fixture',email:'synthetic-fixture@example.invalid',termsAccepted:true});assert.equal(created.state,'DRAFT');const paid=await flow.startPayment(id(1),id(81));assert.equal(paid.state,'CONFIRMED_DEV');assert.equal((await flow.get(id(1))).priceSha256,f.world.b.price_sha256);assert.equal((await flow.list()).length,1);assert.equal(f.world.notifications.length,1);});
test('legacy UNKNOWN keeps its existing payment key and later lookup recovers without create retry',async()=>{const f=new ProjectionSqlFixture();f.world.b.state='DRAFT';f.world.a=null as never;f.world.h.payment_state='NONE';let calls=0;const flow=new LocalFlow(f,{...gateway,async create(){calls++;throw new Error('fixture-network-loss');},async lookup(r){return {...observation(),idempotencyKey:r.idempotencyKey};}});await flow.startPayment(id(1),id(81));assert.equal(f.world.a.state,'UNKNOWN');await flow.startPayment(id(1),id(82));assert.equal(calls,1);await flow.reconcile(id(1));assert.equal(f.world.a.state,'COMPLETED');assert.equal(calls,1);});
for(const mode of ['expired','claims','transfer','snapshot'] as const)test('legacy create still blocks '+mode,async()=>{const f=new ProjectionSqlFixture();f.world.b=null as never;f.world.a=null as never;f.world.h.payment_state='NONE';if(mode==='expired')f.world.h.expires_at=new Date(f.now);if(mode==='claims')f.world.claims=[];if(mode==='transfer')f.world.transfer.forbidden=true;if(mode==='snapshot')f.world.q.snapshot_sha256='a'.repeat(64);await assert.rejects(new LocalFlow(f,gateway).create(id(80),id(3),{displayName:'SYNTHETIC Fixture',email:'synthetic-fixture@example.invalid',termsAccepted:true}),{code:mode==='expired'?'HOLD_OR_QUOTE_NOT_USABLE':mode==='claims'?'INVENTORY_PROTECTION_INCOMPLETE':mode==='transfer'?'TRANSFER_RECONCILIATION_REQUIRED':'QUOTE_HOLD_MISMATCH'});assert.equal(f.world.b,null);});
