import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID,createHash} from 'node:crypto';import sharp from 'sharp';
import {preparePhotoDrafts} from '../../packages/core/src/content/media-plan';
import {PrivatePhotoJobs,photoCandidate,type PhotoJob,type PhotoJobStore} from '../../packages/core/src/content/photo-job';
class Memory implements PhotoJobStore{jobs:Record<string,PhotoJob>={};objects=new Map<string,Buffer>();allow=true;offers:string[]=['SKI'];private tail=Promise.resolve();async transaction<T>(fn:(s:Record<string,PhotoJob>,context:{offers:readonly string[]})=>Promise<T>){let done!:()=>void;const previous=this.tail;this.tail=new Promise<void>(r=>done=r);await previous;try{const copy=structuredClone(this.jobs),r=await fn(copy,{offers:[...this.offers]});this.jobs=copy;return r;}finally{done();}}async putPrivateObject(hash:string,b:Buffer){this.objects.set(hash,b);}async assert(s:string){if(!this.allow||s!=='synthetic')throw new Error('DENIED');}service(){return new PrivatePhotoJobs(this,this);}}
const sha=(b:Buffer)=>createHash('sha256').update(b).digest('hex');
test('photo candidates require exact existing offer, explicit role and bounded order; no fuzzy binding',()=>{assert.equal(photoCandidate('SKI__SERVICE__01.jpg',['SKI'])!.role,'SERVICE');assert.equal(photoCandidate('ski__COVER__01.jpg',['SKI']),null);assert.equal(photoCandidate('SKI__COVER__00.jpg',['SKI']),null);assert.equal(photoCandidate('SKI similar.jpg',['SKI']),null);});
test('duplicate upload/concurrent terminal replies commit each photo once, byte reuse never grants rights',async()=>{const f=new Memory();let decodes=0;const s=new PrivatePhotoJobs(f,f,async files=>{decodes++;return preparePhotoDrafts(files);}),b=await sharp({create:{width:12,height:12,channels:3,background:'red'}}).png().toBuffer(),selection={filename:'SKI__COVER__01.png',bytes:b.length,sha256:sha(b)},id=randomUUID();await s.prepare('synthetic',id,[selection]);const result=await Promise.all([s.upload('synthetic',id,0,b),s.upload('synthetic',id,0,b)]);assert.equal(result[0]!.metadata!.rights,'UNVERIFIED');assert.deepEqual(result[0],result[1]);assert.equal(f.jobs[id]!.revision,2);assert.equal(decodes,1);const another=randomUUID();await s.prepare('synthetic',another,[selection]);await s.upload('synthetic',another,0,b);assert.equal(f.jobs[another]!.items[0]!.metadata!.rights,'UNVERIFIED');await assert.rejects(s.upload('other',id,0,b),/DENIED/);f.allow=false;await assert.rejects(s.read('synthetic',id),/DENIED/);});
test('fixed manifest rejects replaced bytes/duplicate names; malformed image records failure without publishing',async()=>{const f=new Memory(),s=f.service(),b=Buffer.from('not png'),selection={filename:'unknown.png',bytes:b.length,sha256:sha(b)},id=randomUUID();await assert.rejects(s.prepare('synthetic',id,[selection,selection]),/PHOTO_SELECTION/);await s.prepare('synthetic',id,[selection]);await assert.rejects(s.upload('synthetic',id,0,Buffer.from('replaced')),/PHOTO_BYTES_MISMATCH/);const result=await s.upload('synthetic',id,0,b);assert.equal(result.state,'FAILED');assert.equal(f.jobs[id]!.state,'PARTIAL');assert.equal(f.jobs[id]!.productionPublished,false);assert.equal(f.objects.size,0);});

test('revocation while real decoder is running rejects commit and writes no private objects',async()=>{const f=new Memory();let reached!:()=>void,resume!:()=>void;const at=new Promise<void>(r=>reached=r),gate=new Promise<void>(r=>resume=r);const s=new PrivatePhotoJobs(f,f,async files=>{const result=await preparePhotoDrafts(files);reached();await gate;return result;}),b=await sharp({create:{width:12,height:12,channels:3,background:'blue'}}).png().toBuffer(),jobId=randomUUID();await s.prepare('synthetic',jobId,[{filename:'SKI__COVER__01.png',bytes:b.length,sha256:sha(b)}]);const op=s.upload('synthetic',jobId,0,b);await at;f.allow=false;resume();await assert.rejects(op,/DENIED/);assert.equal(f.jobs[jobId]!.items[0]!.state,'PENDING');assert.equal(f.objects.size,0);});

test('photo prepare matches the catalog from the acquired transaction, preserving replay candidates',async()=>{
 const f=new Memory();f.offers=[];const s=f.service(),jobId=randomUUID(),bytes=Buffer.from('candidate-only'),files=[{filename:'FRESH__COVER__01.png',bytes:bytes.length,sha256:sha(bytes)}];
 let entered!:()=>void,release!:()=>void;const at=new Promise<void>(r=>entered=r),gate=new Promise<void>(r=>release=r);
 const catalogChange=f.transaction(async()=>{entered();await gate;f.offers=['FRESH'];});await at;
 const request=s.prepare('synthetic',jobId,files);release();await catalogChange;
 const result=await request;assert.equal(result.items[0]!.candidate?.offerCode,'FRESH');
 f.offers=[];const replay=await s.prepare('synthetic',jobId,files);assert.deepEqual(replay,result);
});
