import {spawnSync} from 'node:child_process';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {productionPreflight,productionGateIds,type PreflightFacts} from '../../packages/contracts/src/production-preflight';
const f:PreflightFacts={head:'1'.repeat(40),tree:'2'.repeat(40),main:'3'.repeat(40),checkedAt:'2035-01-01T00:00:00Z',guestPolicyApproved:true,independentCouponDisabled:true,offline:true,worktreeClean:true};
test('P5 preflight never promotes documentation/fixtures/Owner targets to external PASS',()=>{const r=productionPreflight(f);assert.equal(r.gates.length,productionGateIds.length);assert.equal(r.ready,false);assert.equal(r.productionActivation,false);for(const id of ['SQUARE_SANDBOX','SQUARE_WEBHOOK','TRUSTED_INGRESS','BOOKING_RECOVERY','BACKUP_PITR','RPO_RTO','REAL_DEVICE'])assert.equal(r.gates.find(g=>g.id===id)!.state,'EXTERNAL_PENDING');assert.equal(r.gates.find(g=>g.id==='MAIN_PROTECTION')!.state,'NOT_RUN');});
test('P5 exact CI requires repository/workflow/event/head/base/integration tree/run attempt/job success',()=>{const proof:NonNullable<PreflightFacts['foundation']>={source:'GITHUB_READ_ONLY',repository:'ginisato-hash/zao-rental',workflow:'.github/workflows/ci.yml',event:'pull_request',head:f.head,base:f.main!,checkout:'4'.repeat(40),tree:f.tree,runId:123,attempt:1,conclusion:'success',jobsSucceeded:true};const state=(patch:Partial<typeof proof>)=>productionPreflight({...f,foundation:{...proof,...patch}}).gates.find(g=>g.id==='FOUNDATION_CI')!.state;assert.equal(state({}),'PASS');assert.equal(productionPreflight({...f,foundation:proof,worktreeClean:false}).gates.find(g=>g.id==='FOUNDATION_CI')!.state,'FAIL');for(const patch of [{repository:'other/repo'},{workflow:'other.yml'},{event:'push'},{head:'5'.repeat(40)},{base:'6'.repeat(40)},{tree:'7'.repeat(40)},{attempt:0},{conclusion:'failure'},{jobsSucceeded:false}])assert.equal(state(patch),'FAIL');});

test('P5 offline preflight command emits JSON/human summary and exits2 with pending gates',()=>{const r=spawnSync(process.execPath,['--import','tsx','scripts/production-preflight.ts','--offline'],{encoding:'utf8'});assert.equal(r.status,2);const body=JSON.parse(r.stdout);assert.equal(body.ready,false);assert.equal(body.productionActivation,false);assert.equal(body.gates.length,productionGateIds.length);assert.match(r.stderr,/NOT READY/);assert.equal(body.gates.find((g:{id:string})=>g.id==='FOUNDATION_CI').state,'NOT_RUN');});
