import test from 'node:test';
import assert from 'node:assert/strict';
import {randomBytes} from 'node:crypto';
import {productionConfiguration,productionServices,ProductionStartupError} from '../../packages/auth/src/production-config';
import {guestConfigurationHash,productionGuestConfiguration} from '../../packages/contracts/src/production-guest';
import {productionIngress,type VerifiedProductionPeer} from '../../packages/core/src/guest/production-ingress';
import {composeProductionRuntime,productionConfigurationDigest} from '../../packages/core/src/guest/production-runtime';
import {validateProductionCredential} from '../../packages/db/src/production-connection';
const guest=productionGuestConfiguration({schemaVersion:1,revision:'SYNTHETIC-M15',ingressAdapterId:'verified-fixture',policy:{version:'SYNTHETIC-M15',contextSeconds:60,absoluteSeconds:3600,recoverySeconds:1800,replaySeconds:30,retentionSeconds:60,windowSeconds:10,peerRequests:3,globalRequests:5}});
function input(){return {schemaVersion:1,capability:'ZAO_PRODUCTION_RUNTIME_V1',deployment:{provider:'VERCEL',environment:'production',projectId:'synthetic-project',releaseId:'synthetic-release',origin:'https://fixture.invalid'},database:{provider:'NEON',environment:'production',host:'ep-synthetic-production.neon.tech',name:'synthetic_db',roles:Object.fromEntries(productionServices.map(s=>[s,'synthetic_'+s]))},flags:{booking:true,guestRecovery:true,payment:false,media:false,staffOperations:true},guest,approvedGuestSha256:guestConfigurationHash(guest),payment:null,media:null};}
test('explicit validated Production configuration defaults Avatar OFF without removing booking or recovery',()=>{const c=productionConfiguration(input());assert.equal(c.flags.avatar,false);assert.equal(c.flags.booking,true);assert.equal(c.flags.guestRecovery,true);assert.ok(Object.isFrozen(c.flags));});
test('Production config rejects missing capability, Preview, localhost, unknown config and owner/admin role',()=>{const base=input();for(const patch of [{capability:undefined},{capability:'PREVIEW'},{deployment:{...base.deployment,environment:'preview'}},{deployment:{...base.deployment,origin:'http://127.0.0.1:3000'}},{database:{...base.database,environment:'development'}},{database:{...base.database,host:'127.0.0.1'}},{database:{...base.database,roles:{...base.database.roles,auth:'neondb_owner'}}},{database:{...base.database,roles:{...base.database.roles,auth:'db_admin'}}},{unknownSecret:'SYNTHETIC_ONLY'}])assert.throws(()=>productionConfiguration({...base,...patch}),ProductionStartupError);});
test('feature dependencies and unknown flags fail closed; media private configuration and expiry are required',()=>{const base=input(),media={provider:'CLOUDFLARE_R2',environment:'PRODUCTION',accountId:'a'.repeat(32),bucket:'synthetic-private',visibility:'PRIVATE',r2DevEnabled:false,publicDomains:[],credentialExpiresAt:'2099-01-01T00:00:00Z'};
 for(const patch of [{flags:{...base.flags,avatar:true}},{flags:{...base.flags,booking:false}},{flags:{...base.flags,debug:true}},{flags:{...base.flags,payment:true}},{flags:{...base.flags,media:true}},{media:{...media,visibility:'PUBLIC'}},{media:{...media,r2DevEnabled:true}},{media:{...media,publicDomains:['public.invalid']}},{media:{...media,credentialExpiresAt:'2000-01-01T00:00:00Z'}}])assert.throws(()=>productionConfiguration({...base,...patch}),ProductionStartupError);
 assert.equal(productionConfiguration({...base,media,flags:{...base.flags,media:true,avatar:true}}).flags.avatar,true);
});
test('Sandbox payment metadata is refused even when all other deployment fields are Production',()=>{const base=input(),payment={provider:'SQUARE',environment:'SANDBOX',merchantId:'synthetic-merchant',locations:{MOUNTAIN_BASE:'synthetic-mountain',ONSEN_BASE:'synthetic-onsen'}};assert.throws(()=>productionConfiguration({...base,payment,flags:{...base.flags,payment:true}}),{stage:'PAYMENT'});});
test('Production credential requires exact release DB/role, production provenance and no extra secret keys',()=>{const c=productionConfiguration(input()),credential={provider:'NEON' as const,environment:'PRODUCTION' as const,host:c.database.host,port:5432 as const,database:c.database.name,user:c.database.roles.auth,password:randomBytes(24).toString('hex'),revoked:false as const};validateProductionCredential(c,'auth',credential);
 for(const patch of [{environment:'PREVIEW'},{environment:'DEVELOPMENT'},{host:'localhost'},{database:'other_db'},{user:'neondb_owner'},{password:''},{adminUrl:'SYNTHETIC_ONLY'}])assert.throws(()=>validateProductionCredential(c,'auth',{...credential,...patch} as typeof credential),{stage:'DB_CONFIG'});
});
test('ingress ignores all spoofable headers and binds verified metadata to exact project/environment/release/origin',()=>{const c=productionConfiguration(input()),values=new WeakMap<Request,VerifiedProductionPeer>(),adapter=productionIngress(c,r=>values.get(r));const request=new Request(c.deployment.origin+'/api/guest/draft',{headers:{'x-forwarded-for':'192.0.2.8','x-real-ip':'192.0.2.9',host:'spoof.invalid','x-verified-peer':'192.0.2.10'}});assert.equal(adapter.peer(request),undefined);
 const proof={...c.deployment,address:'192.0.2.1'};values.set(request,proof);assert.equal(adapter.peer(request)?.address,'192.0.2.1');assert.equal(adapter.peer(request.clone()),undefined);
 for(const patch of [{projectId:'wrong'},{environment:'preview'},{releaseId:'wrong'},{origin:'https://other.invalid'}]){values.set(request,{...proof,...patch} as VerifiedProductionPeer);assert.equal(adapter.peer(request),undefined);}
});
test('normal composition rejects unapproved identity/unknown secrets before any connector or provider work',async()=>{const c=productionConfiguration(input());let connections=0;const secrets={database:{},guestKey:randomBytes(32).toString('hex'),staffKey:randomBytes(32).toString('hex'),accessKey:randomBytes(32).toString('hex'),recoveryKey:randomBytes(32).toString('hex'),accessKeyVersion:'prod-access-1',recoveryKeyVersion:'prod-recovery-1'};
 const base={configuration:c,approvedConfigurationSha256:productionConfigurationDigest(c),deployment:c.deployment,secrets,verifiedPeer:()=>undefined,connect:async()=>{connections++;throw Error('MUST_NOT_CONNECT');},audit:async()=>{}};
 for(const patch of [{approvedConfigurationSha256:''},{deployment:{...c.deployment,projectId:'wrong'}},{secrets:{...secrets,unknownCredential:'SYNTHETIC_ONLY'}},{secrets:{...secrets,recoveryKey:secrets.accessKey}}])await assert.rejects(composeProductionRuntime({...base,...patch}),ProductionStartupError);
 assert.equal(connections,0);
});
