import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash,createHmac,randomUUID} from 'node:crypto';
import {SquareSandboxGateway,SQUARE_SANDBOX_ORIGIN,type SquareSandboxTransport,type SquareCall} from '../../packages/core/src/payment/square-sandbox';
import {releasedDerivative} from '../../packages/core/src/content/storage-port';
import {planStockImport,type StockSource,type ImportVariant} from '../../packages/core/src/content/stock-import-plan';
import {launchReadiness,launchGateIds,safeOperationalEvent,webVital} from '../../packages/contracts/src/production-readiness';
import type {PaymentRequest} from '../../packages/contracts/src/rental-flow';
const request:PaymentRequest={attemptId:randomUUID(),bookingId:randomUUID(),idempotencyKey:randomUUID(),merchantId:'SYNTHETIC-MERCHANT',locationId:'SYNTHETIC-LOCATION',amountJpy:7500,currency:'JPY'};
const payment={id:'synthetic_payment',reference_id:request.bookingId,location_id:request.locationId,amount_money:{amount:7500,currency:'JPY'},status:'COMPLETED',updated_at:'2035-01-01T01:00:00Z',card_details:{card_payment_timeline:{captured_at:'2035-01-01T01:00:00Z'}}};
function fixture(reply:SquareSandboxTransport['send']=async()=>({status:200,body:{payment}})){const calls:SquareCall[]=[],gateway=new SquareSandboxGateway({environment:'SANDBOX',merchantId:request.merchantId,async send(c){calls.push(c);return reply(c);}},async()=> 'synthetic_source');return {gateway,calls};}

test('Square Sandbox adapter uses exact official request, stable key, bounded endpoint and no normal activation',async()=>{const x=fixture();const o=await x.gateway.create(request);assert.equal(x.gateway.kind,'SQUARE_UNCONNECTED');assert.equal(o.amountJpy,7500);assert.deepEqual(x.calls[0]!.body,{idempotency_key:request.idempotencyKey,source_id:'synthetic_source',reference_id:request.bookingId,location_id:request.locationId,amount_money:{amount:7500,currency:'JPY'},autocomplete:true});assert.equal(x.calls[0]!.url,SQUARE_SANDBOX_ORIGIN+'/v2/payments');assert.equal(x.calls[0]!.version,'2026-08-19');await x.gateway.lookup(request,payment.id);assert.equal(x.calls[1]!.method,'GET');});
test('UNKNOWN without verified provider ID never sends another POST or invents get-by-idempotency',async()=>{const x=fixture(async()=>{throw new Error('synthetic transport lost');});await assert.rejects(x.gateway.create(request),{code:'PAYMENT_RESULT_UNKNOWN'});await assert.rejects(x.gateway.lookup(request,null),{code:'PAYMENT_PROVIDER_ID_UNRESOLVED'});assert.equal(x.calls.length,1);await assert.rejects(x.gateway.lookup(request,'../payments'),{code:'INVALID_PROVIDER_ID'});assert.equal(x.calls.length,1);});
test('Square auth/quota/timeout stops without automatic retry and masks raw response',async()=>{for(const [status,code] of [[401,'SQUARE_AUTH_STOP'],[403,'SQUARE_AUTH_STOP'],[429,'SQUARE_QUOTA_STOP'],[500,'PAYMENT_RESULT_UNKNOWN']] as const){const x=fixture(async()=>({status,body:{untrusted:'never output'}}));await assert.rejects(x.gateway.create(request),{code});assert.equal(x.calls.length,1);}let aborted=false;const gateway=new SquareSandboxGateway({environment:'SANDBOX',merchantId:request.merchantId,send:c=>new Promise((_,reject)=>c.signal.addEventListener('abort',()=>{aborted=true;reject(new Error('synthetic abort'));}))},async()=> 'synthetic_source',1);await assert.rejects(gateway.create(request),{code:'PAYMENT_RESULT_UNKNOWN'});assert.equal(aborted,true);});
test('Square signed webhook uses fresh lookup rather than callback amount or status; rejects tamper, merchant and money mismatch',async()=>{const key='SYNTHETIC-WEBHOOK-KEY',url='https://fixture.invalid/webhook',raw=Buffer.from(JSON.stringify({event_id:'synthetic_event',merchant_id:request.merchantId,type:'payment.updated',data:{object:{payment:{id:payment.id,status:'FAILED',amount_money:{amount:1,currency:'USD'}}}}}));const sig=createHmac('sha256',key).update(url).update(raw).digest('base64'),x=fixture();assert.equal((await x.gateway.verifiedWebhook(request,raw,sig,url,key)).observation.status,'COMPLETED');assert.equal(x.calls.length,1);await assert.rejects(x.gateway.verifiedWebhook(request,Buffer.concat([raw,Buffer.from(' ')]),sig,url,key),{code:'WEBHOOK_SIGNATURE_REJECTED'});assert.equal(x.calls.length,1);await assert.rejects(x.gateway.verifiedWebhook({...request,merchantId:'wrong'},raw,sig,url,key),{code:'WEBHOOK_TARGET_MISMATCH'});const bad=fixture(async()=>({status:200,body:{payment:{...payment,amount_money:{amount:1,currency:'JPY'}}}}));await assert.rejects(bad.gateway.lookup(request,payment.id),{code:'PAYMENT_EVIDENCE_MISMATCH'});});

test('private storage releases only current derivative and rechecks withdrawal/revision after read',async()=>{const bytes=Buffer.from('synthetic-image'),sha=createHash('sha256').update(bytes).digest('hex'),path='/media/'+sha+'/320.webp';let allowed=true,reads=0;const grant=async()=>allowed?{path,sha256:sha,type:'image/webp' as const,revision:'r1'}:null;const store={async readPrivateObject(){reads++;return bytes;}};assert.equal((await releasedDerivative(path,store,grant))!.bytes,bytes);assert.equal(await releasedDerivative('/original/'+sha,store,grant),null);assert.equal(reads,1);assert.equal(await releasedDerivative(path,{async readPrivateObject(){allowed=false;return bytes;}},grant),null);allowed=true;await assert.rejects(releasedDerivative(path,{async readPrivateObject(){return Buffer.from('tampered');}},grant),{code:'MEDIA_DIGEST_MISMATCH'});});
const variant:ImportVariant={id:randomUUID(),modelId:randomUUID(),season:'2026/27',manufacturerSku:'SYNTHETIC-SKU',family:'SKI'};
const source:StockSource={documentSha256:'a'.repeat(64),locator:'Sheet1!A2',sourceKind:'SHOP_RECEIPT',intent:'ADD',modelId:variant.modelId,season:variant.season,variantId:variant.id,manufacturerSku:variant.manufacturerSku,quantity:1,unit:'ASSET_PAIR',assetIds:[randomUUID()],storeId:'MOUNTAIN_BASE'};
test('exact catalog/source plan preserves one ski pair as one Asset and duplicate receipt is idempotent',()=>{const p=planStockImport([source],[variant],{},'catalog-r1');assert.equal(p.entries[0]!.disposition,'VALIDATED_PLAN');assert.equal(p.createsInventory,false);assert.equal(p.requiresAuthorizedLedgerCommit,true);const old={[p.entries[0]!.sourceKey]:p.entries[0]!.sourceHash};assert.equal(planStockImport([source],[variant],old,'catalog-r1').entries[0]!.disposition,'ALREADY_IMPORTED');assert.ok(planStockImport([{...source,quantity:2}],[variant],old,'catalog-r1').entries[0]!.issues.includes('SOURCE_CHANGED_RECONCILE'));});
test('manufacturer range, unknown ADD/REPLACE/store/unit and wrong season never become stock',()=>{for(const patch of [{sourceKind:'MANUFACTURER'},{intent:'REPLACE'},{intent:'UNKNOWN'},{storeId:null},{unit:'UNKNOWN'},{season:'2025/26'},{manufacturerSku:'wrong'}])assert.ok(planStockImport([{...source,...patch} as StockSource],[variant],{},'r1').entries[0]!.issues.length);assert.throws(()=>planStockImport([{...source,price:1} as StockSource],[variant],{},'r1'));assert.throws(()=>planStockImport([source,source],[variant],{},'r1'));assert.ok(planStockImport([{...source,quantity:2,assetIds:[source.assetIds[0]!,source.assetIds[0]!]}],[variant],{},'r1').entries[0]!.issues.includes('ASSET_ID_DUPLICATE_OR_INVALID'));});
test('wear and poles require explicit quantity units with no generated individual IDs or invented200 total',()=>{for(const family of ['POLE','WEAR_JACKET','WEAR_PANTS'] as const){const v={...variant,family},s={...source,quantity:3,unit:family==='POLE'?'PAIR_QUANTITY' as const:'PIECE_QUANTITY' as const,assetIds:[]};assert.equal(planStockImport([s],[v],{},'r1').entries[0]!.disposition,'VALIDATED_PLAN');assert.ok(planStockImport([{...s,assetIds:[randomUUID()]}],[v],{},'r1').entries[0]!.issues.includes('QUANTITY_STOCK_HAS_NO_ASSET_IDS'));}});
test('launch checklist fails closed on missing/expired/old-head/old-policy evidence; pass grants no deploy permission',()=>{const head='a'.repeat(40),now=new Date('2035-01-01T01:00:00Z');assert.equal(launchReadiness([],head,'r1',now).ready,false);const gates=launchGateIds.map(id=>({id,state:'VERIFIED' as const,head,policyRevision:'r1',evidenceRef:'SYNTHETIC-EVIDENCE',verifiedAt:'2035-01-01T00:00:00Z',expiresAt:'2035-01-02T00:00:00Z'}));assert.deepEqual(launchReadiness(gates,head,'r1',now),{ready:true,blocked:[],deployPerformed:false,approvalGranted:false});assert.equal(launchReadiness(gates,'b'.repeat(40),'r1',now).ready,false);assert.equal(launchReadiness(gates,head,'r2',now).ready,false);assert.equal(launchReadiness(gates,head,'r1',new Date('2035-01-02')).ready,false);assert.throws(()=>launchReadiness([...gates,gates[0]!],head,'r1',now));});
test('operational events and CWV distinguish LAB/FIELD and exclude arbitrary PII/body/session fields',()=>{const event={operation:'guest_recovery',outcome:'denied',durationMs:20,requestId:randomUUID()};assert.equal(safeOperationalEvent(event).outcome,'denied');for(const k of ['email','cookie','token','ip','raw','url'])assert.throws(()=>safeOperationalEvent({...event,[k]:'not-allowed'}));assert.equal(webVital({name:'CLS',value:.1,page:'booking',device:'mobile',source:'LAB'}).unit,'score');assert.throws(()=>webVital({name:'LCP',value:1,page:'booking',device:'mobile',source:'LAB',email:'not-allowed'} as never));});

test('Square deadlines settle even when an injected dependency ignores cancellation; source failure never POSTs',async()=>{let calls=0;const transport:SquareSandboxTransport={environment:'SANDBOX',merchantId:request.merchantId,send:()=>{calls++;return new Promise(()=>{});}};await assert.rejects(new SquareSandboxGateway(transport,async()=> 'synthetic_source',1).create(request),{code:'PAYMENT_RESULT_UNKNOWN'});assert.equal(calls,1);calls=0;await assert.rejects(new SquareSandboxGateway(transport,()=>new Promise(()=>{}),1).create(request),{code:'PAYMENT_SOURCE_NOT_CONNECTED'});await assert.rejects(new SquareSandboxGateway(transport,async()=>{throw new Error('untrusted source diagnostic');}).create(request),{code:'PAYMENT_SOURCE_NOT_CONNECTED'});assert.equal(calls,0);});
