import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {r15Preview,r15RuntimeDatabase,r15Manifest} from '../../tools/acceptance/r15-preview';
import type {InboxPool} from '../../packages/db/src/square-webhook-inbox';
const id=(n:number)=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
const env={VERCEL_ENV:'preview',VERCEL_PROJECT_ID:'prj_ehUMOzM77em9DVnHJBJffncD5hg7',R15_ACTIVATION_AUTHORITY:'P6_R15',SQUARE_ENVIRONMENT:'SANDBOX',SQUARE_API_VERSION:'2026-08-19',SQUARE_SANDBOX_APPLICATION_ID:'sandbox-fixture',SQUARE_SANDBOX_LOCATION_ID:'fixture-location',SQUARE_SANDBOX_MERCHANT_ID:'MLKDVEDH1ME21',SQUARE_SANDBOX_ACCESS_TOKEN:'fixture-only'};
const m={authority:'P6_R15_COMPLETION',operationId:id(9),resourceId:'store_i5vh0ZEKo2ikcVo9',database:'zr_852b20c4d4b0',environment:'SANDBOX',merchantId:'MLKDVEDH1ME21',locationId:'fixture-location',amountJpy:100,currency:'JPY',bookingId:id(1),attemptId:id(4),idempotencyKey:id(5),branch:'codex/external-acceptance-p6',sourceHead:'a'.repeat(40),budgets:{createPayment:1,getPayment:1,retry:0}};
const body=(v:unknown=m)=>{const manifestSource=JSON.stringify(v);return {manifestSource,manifestSha256:createHash('sha256').update(manifestSource).digest('hex')};};
const req=(action:string,b:unknown=body(),headers:Record<string,string>={})=>new Request('https://preview.invalid/api/r15/'+action,{method:'POST',headers:{'X-ZAO-Acceptance':'P6_R15_COMPLETION','sec-fetch-site':'same-origin',origin:'https://preview.invalid',...headers},body:JSON.stringify(b)});
function db(log:string[],commitFails=false){let reserved=false;return {async connect(){return {async query(sql:string){log.push(sql);if(sql.startsWith('SELECT r15_activation.reserve')){const acquired=!reserved;reserved=true;return {rows:[{acquired}]};}if(sql==='COMMIT'&&commitFails)throw Error('fixture');return {rows:[]};},release(){}};}} as InboxPool;}
function fixture(commitFails=false){const log:string[]=[],p=db(log,commitFails),pools={worker:p,dispatcher:p,projector:p,diagnostic:p};let calls=0;const send:typeof fetch=async(url,init)=>{calls++;assert.equal(url,'https://connect.squareupsandbox.com/v2/payments');assert.equal(init?.redirect,'error');assert.ok(log.includes('COMMIT'));const b=JSON.parse(String(init?.body));assert.equal(b.source_id,'cnon:card-nonce-ok');assert.equal(b.amount_money.amount,100);throw Error('fixture network uncertainty');};return {log,get calls(){return calls;},handle:r15Preview(env,send,()=>pools)};}
test('R15 request tamper/identity mismatch cannot reach DB or provider',async()=>{const f=fixture();for(const b of [{...body(),manifestSource:body().manifestSource+' '},body({...m,amountJpy:101}),body({...m,merchantId:'wrong'}),body({...m,locationId:'wrong'}),body({...m,budgets:{createPayment:2,getPayment:1,retry:0}})])assert.equal((await f.handle(req('payment',b))).status,503);assert.equal(f.calls,0);assert.equal(f.log.length,0);});
test('R15 provider executes after durable COMMIT and never retries UNKNOWN',async()=>{const f=fixture(),r=await f.handle(req('payment'));assert.equal((await r.json()).classification,'UNKNOWN_DO_NOT_RETRY');assert.equal(f.calls,1);assert.equal((await f.handle(req('payment'))).status,409);assert.equal(f.calls,1);});
test('R15 failed COMMIT prohibits dispatch across a fresh handler',async()=>{const f=fixture(true);await f.handle(req('payment'));assert.equal(f.calls,0);const log:string[]=[],p=db(log),pools={worker:p,dispatcher:p,projector:p,diagnostic:p};let calls=0;const send:typeof fetch=async()=>{calls++;throw Error();};await r15Preview(env,send,()=>pools)(req('payment'));await r15Preview(env,send,()=>pools)(req('payment'));assert.equal(calls,1);});
test('R15 Production and cross-origin requests fail before callbacks',async()=>{let calls=0;const h=r15Preview({...env,VERCEL_ENV:'production'},async()=>{calls++;throw Error();},()=>{throw Error();});assert.equal((await h(req('payment'))).status,404);const f=fixture();assert.equal((await f.handle(req('payment',body(),{'sec-fetch-site':'cross-site'}))).status,400);assert.equal(calls+f.calls,0);});
test('R15 runtime URI binds exact fresh role/DB and verifying TLS',()=>{const uri='postgresql:'+'//zr_852b20c4d4b0_pay_truth:'+encodeURIComponent('fixture only')+'@ep-fixture.us-east-1.aws.neon.tech/zr_852b20c4d4b0?sslmode=verify-full';assert.deepEqual(r15RuntimeDatabase(uri,'truth').ssl,{rejectUnauthorized:true});for(const bad of [uri.replace('pay_truth','pay_receipt'),uri.replace('verify-full','require'),uri.replace('ep-fixture.us-east-1.aws.neon.tech','localhost'),uri+'&options=x'])assert.throws(()=>r15RuntimeDatabase(bad,'truth'));assert.equal(r15Manifest(body(),'fixture-location').request.amountJpy,100);});
