import assert from 'node:assert/strict';
import {test} from 'node:test';
import {Readable} from 'node:stream';
import {createHash,randomBytes,randomUUID} from 'node:crypto';
import {R2MediaProvider} from '../../packages/core/src/content/r2-media';
import {ProviderMediaStore} from '../../packages/core/src/content/provider-media';
function fixture(){const account='a'.repeat(32),bucket='synthetic-private',now=new Date('2035-01-01T00:00:00Z'),objects=new Map<string,{body:Uint8Array;hash:string}>();let revoked=false,puts=0,purgeDone=false;
 const r2=new R2MediaProvider(account,bucket,async()=>({accountId:account,bucket,accessKeyId:'SYNTHETIC',secretAccessKey:randomBytes(32).toString('hex'),expiresAt:new Date('2035-01-02'),revoked}),async(keys,requestId)=>({keys,requestId,completed:purgeDone}),()=>now,{handle:async (request:{hostname:string;protocol:string;path:string;headers:Record<string,string>;method:string;body?:unknown})=>{
  assert.equal(request.hostname,account+'.r2.cloudflarestorage.com');assert.equal(request.protocol,'https:');assert.ok(request.path.startsWith('/'+bucket+'/private/'));assert.equal(request.headers['x-amz-acl'],undefined);
  if(request.method==='PUT'){puts++;assert.equal(request.headers['if-none-match'],'*');if(objects.has(request.path))return {response:{statusCode:412,headers:{'content-type':'application/xml'},body:Readable.from(['<Error><Code>PreconditionFailed</Code></Error>'])}};objects.set(request.path,{body:new Uint8Array(request.body as Uint8Array),hash:request.headers['x-amz-meta-sha256']!});return {response:{statusCode:200,headers:{},body:Readable.from([])}};}
  const o=objects.get(request.path);return {response:{statusCode:o?200:404,headers:o?{'x-amz-meta-sha256':o.hash,'content-length':String(o.body.byteLength)}:{},body:Readable.from(o?[Buffer.from(o.body)]:[])}};
 }});return {r2,objects,now,revoke:()=>{revoked=true;},purge:()=>{purgeDone=true;},get puts(){return puts;}};}
test('R2 SDK transport fixture: private immutable object, conditional replay, no public ACL or default network',async()=>{const f=fixture();try{const bytes=Buffer.from('SYNTHETIC IMAGE'),sha256=createHash('sha256').update(bytes).digest('hex'),o={kind:'ORIGINAL' as const,sha256,bytes:bytes.length,mime:'image/png' as const},store=new ProviderMediaStore(f.r2);const a=await store.put(o,bytes);await store.put(o,bytes);assert.equal(f.objects.size,1);assert.equal(f.puts,2);assert.deepEqual(await f.r2.readPrivate(a.key),bytes);f.revoke();await assert.rejects(f.r2.readPrivate(a.key),{code:'R2_CREDENTIAL_UNAVAILABLE'});}finally{f.r2.close();}});
test('R2 presigning uses SDK and bounded original-only tickets; rights withdrawal requires matched purge receipt',async()=>{const f=fixture();try{const bytes=Buffer.from('SYNTHETIC IMAGE'),sha256=createHash('sha256').update(bytes).digest('hex'),object={kind:'ORIGINAL' as const,sha256,bytes:bytes.length,mime:'image/png' as const},store=new ProviderMediaStore(f.r2),access={object,revision:'r1',rightsRevision:'rights1',purpose:'PRIVATE_ORIGINAL' as const};await store.put(object,bytes);const ticket=await store.privateTicket(async()=>access,{now:f.now,expiresAt:new Date('2035-01-01T00:05:00Z'),maximumSeconds:300,approvedOrigin:f.r2.origin});const url=new URL(ticket.url);assert.equal(url.origin,f.r2.origin);assert.equal(url.searchParams.get('X-Amz-Expires'), '300');assert.ok(url.searchParams.has('X-Amz-Signature'));assert.equal(f.objects.size,1);await assert.rejects(f.r2.signPrivateRead('private/derivative/sha256/'+sha256,new Date('2035-01-01T00:05:00Z')),{code:'PRIVATE_MEDIA_DENIED'});const plan={id:randomUUID(),revision:'r2',keys:['private/original/sha256/'+sha256],lastTicketExpiresAt:ticket.expiresAt.toISOString(),legalRetentionUntil:null,cmsWithdrawn:true as const};await assert.rejects(store.revoke(plan),{code:'MEDIA_INVALIDATION_PENDING'});f.purge();assert.equal((await store.revoke(plan)).invalidationConfirmed,true);assert.equal(await store.read(async()=>null),null);assert.equal(f.objects.size,1);}finally{f.r2.close();}});
