import {createHash} from 'node:crypto';
import {PrivateContentWorkflow,type ContentPermission} from '../../../../packages/core/src/content/workflow';
import {planCatalogSources} from '../../../../packages/core/src/content/catalog-source';
import {id} from '../../../../packages/contracts/src/pricing';
import {canonical} from '../../../../packages/contracts/src/hold';
import {ContentInputError} from '../../../../packages/core/src/content/bulk-plan';
import {contentSession} from './content-session';
const responseHeaders={'Cache-Control':'private, no-store','Vary':'Cookie'};
export async function contentHandler(request:Request){try{
 const {runtime,subject,repo,authority}=await contentSession(request);
 const path=new URL(request.url);if(path.search)throw new Error('INVALID_QUERY');const action=path.pathname.slice('/api/content'.length),workflow=new PrivateContentWorkflow(repo,authority);
 if(request.method==='GET'&&action===''){await authority.assert(subject,'CONTENT_EDIT');const record=await repo.read();return Response.json({drafts:Object.entries(record.state.catalog.draftIds).map(([target,rid])=>({...record.state.catalog.revisions.find(r=>r.id===rid)!,target,revision:record.state.catalog.revisions.filter(r=>r.offerCode+'/'+r.locale===target).length})),plans:Object.entries(record.state.plans).filter(([,v])=>v.owner===subject).map(([planId,v])=>({planId,kind:v.kind,hash:v.plan.hash,issues:v.plan.issues,completed:!!v.completed})),current:record.state.catalog.current,releases:record.state.catalog.releases,catalogSources:Object.values(record.catalogSources??{}),privateFixture:false,storage:"DEVELOPMENT_POSTGRES"},{headers:responseHeaders});}
 if(request.method!=='POST'||request.headers.get('origin')!==runtime.config.origin)return Response.json({error:'ORIGIN_REJECTED'},{status:403,headers:responseHeaders});
 const required:Record<string,ContentPermission>={'/bulk-prepare':'CONTENT_BULK','/bulk-commit':'CONTENT_BULK','/release-prepare':'CONTENT_PUBLISH','/release-commit':'CONTENT_PUBLISH','/catalog-prepare':'CONTENT_BULK'};if(!required[action])throw new Error('NOT_FOUND');await authority.assert(subject,required[action]!);
 if(request.headers.get('content-type')?.split(';')[0]!=='application/json')throw new ContentInputError('JSON_REQUIRED');const reader=request.body?.getReader();if(!reader)throw new ContentInputError('BODY_REQUIRED');const chunks:Uint8Array[]=[];let size=0;try{for(;;){const part=await reader.read();if(part.done)break;size+=part.value.length;if(size>10*1024*1024+1024){await reader.cancel();return Response.json({error:'BODY_TOO_LARGE'},{status:413,headers:responseHeaders});}chunks.push(part.value);}}finally{reader.releaseLock();}const bytes=Buffer.concat(chunks),raw=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes));if(!raw||typeof raw!=='object'||Object.keys(raw).sort().join()!=='input,requestKey')throw new ContentInputError('INVALID_INPUT');
 const v=raw.input;let result:unknown;const shape=(keys:string[])=>{if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).sort().join()!==keys.sort().join())throw new ContentInputError('INVALID_INPUT');};
 if(action==='/catalog-prepare'){shape(['rows']);id(raw.requestKey);if(!Array.isArray(v.rows))throw new ContentInputError('CATALOG_SOURCE_SHAPE');result=await repo.edit(async record=>{await authority.assert(subject,'CONTENT_BULK');const key=subject+'/'+raw.requestKey,hash=createHash('sha256').update(canonical({action,rows:v.rows})).digest('hex'),old=record.state.requests[key];if(old){if(old.hash!==hash)throw new ContentInputError('REQUEST_KEY_MISMATCH');return old.result;}const planned=planCatalogSources(v.rows,record.catalogFacts??[]);record.catalogSources??={};let staged=0;for(const row of planned){if(record.catalogSources[row.sourceHash])continue;if(Object.values(record.catalogSources).some(r=>r.source.sourceDocument===row.source.sourceDocument&&r.source.sourceLocator===row.source.sourceLocator))row.issues.push('SOURCE_CHANGED_RECONFIRM');record.catalogSources[row.sourceHash]=row;staged++;}const saved={state:'DRAFT_RECONCILIATION',rows:planned.length,staged,unchanged:planned.length-staged,createsStock:false,productionPublished:false};record.state.requests[key]={hash,result:saved};record.state.audit.push({actor:subject,action:'CATALOG_SOURCE_STAGE',objectId:raw.requestKey,before:null,after:hash});return saved;});}
 else if(action==='/bulk-prepare'){shape(['csv']);if(typeof v.csv!=='string')throw new ContentInputError('INVALID_INPUT');result=await workflow.prepareBulk(subject,raw.requestKey,v.csv);}
 else if(action==='/bulk-commit'){shape(['planId','hash']);result=await workflow.commitBulk(subject,raw.requestKey,v.planId,v.hash);}
 else if(action==='/release-prepare'){shape(['entries','expectedCurrent','restoreOf']);if(!Array.isArray(v.entries)||v.entries.some((e:unknown)=>typeof e!=='string')||v.expectedCurrent!==null&&typeof v.expectedCurrent!=='string'||v.restoreOf!==null&&typeof v.restoreOf!=='string')throw new ContentInputError('INVALID_INPUT');result=await workflow.prepareRelease(subject,raw.requestKey,v.entries,v.expectedCurrent,v.restoreOf);}
 else if(action==='/release-commit'){shape(['planId','hash']);result=await workflow.commitRelease(subject,raw.requestKey,v.planId,v.hash);}
 else throw new Error('NOT_FOUND');return Response.json(result,{headers:responseHeaders});
 }catch(e){const code=e instanceof ContentInputError?e.code:(e as Error).message;const known=['CONTENT_UNCONNECTED','UNAUTHENTICATED','SESSION_CHANGED','CONTENT_FORBIDDEN','FIXTURE_LOCKED','FIXTURE_UNCONNECTED','INVALID_QUERY','NOT_FOUND'];return Response.json({error:e instanceof ContentInputError||known.includes(code)?code:'CONTENT_FIXTURE_FAILED'},{status:code==='UNAUTHENTICATED'?401:code==='CONTENT_UNCONNECTED'?503:code==='CONTENT_FORBIDDEN'?403:code==='FIXTURE_LOCKED'||code==='FIXTURE_UNCONNECTED'?503:e instanceof ContentInputError?409:500,headers:responseHeaders});}}
