import assert from 'node:assert/strict';
import {randomBytes,createHash} from 'node:crypto';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {chromium,expect} from '@playwright/test';
import {startFlowApp} from '../flow/launcher';
import {bootstrapDevelopmentAdmin} from '../../scripts/bootstrap-staff';
import {migrationPlan,migrationsDirectory} from '../../packages/db/src/index';
import {PostgresAvatarVisuals} from '../../packages/db/src/avatar-visuals';
import {avatarDerivative} from '../../packages/core/src/avatar/media';
import {seedAvatarPhase4} from './phase4-fixture';
import {id} from './fixture';
import type {ContentWorkflowState} from '../../packages/core/src/content/workflow';
const evidence='docs/execution/avatar-phase4',results:{kind:string;name:string;status:'PASS'}[]=[],measurements:unknown[]=[],screenshots:unknown[]=[];
let app:Awaited<ReturnType<typeof startFlowApp>>|undefined,browser:Awaited<ReturnType<typeof chromium.launch>>|undefined,stage='setup',failed=false,externalAttempts=0,businessPosts=0;
const check=async(kind:string,name:string,fn:()=>Promise<void>)=>{stage=name;await fn();results.push({kind,name,status:'PASS'});console.log('PASS '+kind+' '+name);};
try{
 app=await startFlowApp({publicP0:true});const {db,content,origin}=app,password=randomBytes(24).toString('base64url');
 const subject=await bootstrapDevelopmentAdmin(db.pool,{email:'avatar-staff@example.invalid',displayName:'SYNTHETIC Avatar Reviewer',password});
 for(const p of ['BOOKING_VIEW','HOLD_VIEW','QUOTE_VIEW'])await db.pool.query('INSERT INTO staff_permission_overrides VALUES($1,$2,true)',[subject,p]);
 // Existing local content_read role only. No production/runtime provisioning code changes.
 const role=content!.contentReadDb.user;assert.match(role,/^zr_[a-f0-9]{12}_content_read$/);
 await db.pool.query(`GRANT SELECT ON avatar_visuals,content_revision_records,content_outbox TO ${role}`);await db.pool.query(`GRANT EXECUTE ON FUNCTION avatar_visual_variant_matches(uuid,uuid,text,double precision) TO ${role}`);
 const seed=await seedAvatarPhase4(db.pool,subject),base=structuredClone(seed.state),body=seed.metadata[0]!,path='/avatar-media/'+body.id+'/'+body.derivativeSha256,preview='/preview/avatar?preview='+seed.previewId+'&member='+seed.memberKey;
 const save=async(state:ContentWorkflowState)=>db.pool.query('UPDATE content_workspace SET value=$1,revision=revision+1',[JSON.stringify(state)]);
 const business=async()=>{const out:Record<string,unknown>={};for(const table of ['recommendation_previews','recommendation_selections','inventory_holds','inventory_claims','price_quotes','rental_bookings','rental_payment_attempts','ledger_assets','ledger_poles','wear_pools'])out[table]=(await db.pool.query(`SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]') value FROM ${table} t`)).rows[0].value;return out;};
 const before=await business();browser=await chromium.launch();const c=await browser.newContext({baseURL:origin,viewport:{width:1440,height:1000}}),anon=await browser.newContext({baseURL:origin});
 for(const context of [c,anon])await context.route('**/*',async route=>{if(new URL(route.request().url()).origin!==origin){externalAttempts++;await route.abort();}else{if(route.request().method()==='POST'&&!route.request().url().includes('/api/auth/'))businessPosts++;await route.continue();}});
 const page=await c.newPage(),fatal:string[]=[];page.on('pageerror',()=>fatal.push('PAGE_ERROR'));page.on('console',m=>{if(m.type()==='error'&&/hydration|uncaught|maximum update/i.test(m.text()))fatal.push('CONSOLE_FATAL');});
 await check('BROWSER','anonymous preview and image cannot expose payload/bytes',async()=>{const html=await (await anon.request.get(preview)).text();assert.match(html,/Staff sign-in/);assert.ok(!html.includes(body.derivativeSha256));assert.equal((await anon.request.get(path)).status(),404);});
 await page.goto('/staff/login');await page.getByLabel('メールアドレス',{exact:true}).fill('avatar-staff@example.invalid');await page.getByLabel('パスワード',{exact:true}).fill(password);await page.getByRole('button',{name:'ログイン',exact:true}).click();await page.waitForURL(origin+'/staff/ledger');
 await check('PG','all31 migration hashes unchanged and no migration added',async()=>{const hashes=JSON.parse(await readFile('docs/execution/avatar-a2-a3/migration-hashes.json','utf8')) as {sha256:string}[];assert.equal(migrationPlan.length,31);for(const [i,m]of migrationPlan.entries())assert.equal(createHash('sha256').update(await readFile(migrationsDirectory+'/'+m.file)).digest('hex'),hashes[i]!.sha256);});
 await check('PG','current release returns only valid alpha WebP derivatives for all layers',async()=>{for(const v of seed.metadata){const r=await c.request.get('/avatar-media/'+v.id+'/'+v.derivativeSha256);assert.equal(r.status(),200);assert.equal(r.headers()['content-type'],'image/webp');assert.equal(r.headers()['cache-control'],'private, no-store');assert.equal(r.headers()['x-content-type-options'],'nosniff');assert.equal(createHash('sha256').update(await r.body()).digest('hex'),v.derivativeSha256);}});
 for(const [name,p]of [['unknown UUID','/avatar-media/'+id(999)+'/'+body.derivativeSha256],['wrong digest','/avatar-media/'+body.id+'/'+'e'.repeat(64)],['private original','/avatar-media/'+body.id+'/'+seed.originalHash],['malformed UUID','/avatar-media/not-a-uuid/'+body.derivativeSha256],['malformed digest','/avatar-media/'+body.id+'/BAD'],['client release claims',path+'?releaseId='+id(191)],['encoded traversal','/avatar-media/%2e%2e%2fsecret/'+body.derivativeSha256]] as const)await check('PG',name+' returns empty404',async()=>{const r=await c.request.get(p);assert.equal(r.status(),404);assert.ok(!(await r.text()).includes('catalog'));});
 await check('PG','POST rejected405 without business write',async()=>{assert.equal((await c.request.post(path,{data:{rightsConfirmed:true}})).status(),405);});
 for(const [name,change]of [
  ['rights revoked',(s:ContentWorkflowState)=>{s.catalog.media[0]!.rightsConfirmed=false;}],
  ['rights expired',(s:ContentWorkflowState)=>{s.catalog.media[0]!.rightsUntil='2000-01-01T00:00:00Z';}],
  ['internal-only',(s:ContentWorkflowState)=>{s.catalog.media[0]!.internalOnly=true;}],
  ['unprocessed',(s:ContentWorkflowState)=>{s.catalog.media[0]!.processed=false;}],
  ['stale release',(s:ContentWorkflowState)=>{s.catalog.current=id(999);}],
  ['purpose grant removed',(s:ContentWorkflowState)=>{delete s.catalog.revisions[0]!.avatarVisualUses;}],
  ['immutable revision differs',(s:ContentWorkflowState)=>{s.catalog.revisions[0]!.content.title='Changed draft';}],
  ['media digest retarget',(s:ContentWorkflowState)=>{s.catalog.media[0]!.immutableSha256=seed.originalHash;}],
  ['mediaId binding changed',(s:ContentWorkflowState)=>{s.catalog.media[0]!.id='unrelated';}],
  ['release entries removed',(s:ContentWorkflowState)=>{s.catalog.releases[0]!.entries=[];}],
 ] as const)await check('PG',name+' after metadata load denies next GET',async()=>{const s=structuredClone(base);change(s);await save(s);assert.equal((await c.request.get(path)).status(),404);await save(base);});
 await check('PG','inactive visual rejects404',async()=>{await db.pool.query("UPDATE avatar_visuals SET state='DISABLED' WHERE id=$1",[body.id]);assert.equal((await c.request.get(path)).status(),404);await db.pool.query("UPDATE avatar_visuals SET state='ACTIVE' WHERE id=$1",[body.id]);});
 await check('PG','visual digest retarget rejects404 even with existing private bytes',async()=>{await db.pool.query('UPDATE avatar_visuals SET derivative_sha256=$1 WHERE id=$2',[seed.originalHash,body.id]);assert.equal((await c.request.get('/avatar-media/'+body.id+'/'+seed.originalHash)).status(),404);await db.pool.query('UPDATE avatar_visuals SET derivative_sha256=$1 WHERE id=$2',[body.derivativeSha256,body.id]);});
 await check('PG','duplicate current workspace metadata fails closed',async()=>{const s=structuredClone(base);s.catalog.media.push(s.catalog.media[0]!);await save(s);assert.equal((await c.request.get(path)).status(),404);await save(base);});
 await check('PG','rights change during byte read is denied by second current DB check',async()=>{const repo=new PostgresAvatarVisuals(content!.contentReadPool);const bytes=await avatarDerivative({findForDelivery:(...args)=>repo.findForDelivery(...args),async readBytes(hash){const r=(await content!.contentReadPool.query('SELECT bytes FROM content_media_objects WHERE sha256=$1',[hash])).rows[0].bytes as Buffer;const s=structuredClone(base);s.catalog.media[0]!.rightsConfirmed=false;await save(s);return r;}},body.id,body.derivativeSha256);assert.equal(bytes,null);await save(base);});
 await check('PG','existing public media route does not accept Avatar grants',async()=>{assert.equal((await c.request.get('/media/'+body.derivativeSha256+'/400.webp')).status(),404);});
 await check('PG','content reader cannot write Avatar/business/workspace',async()=>{for(const sql of ["UPDATE avatar_visuals SET state='DISABLED'",'DELETE FROM recommendation_previews','UPDATE inventory_holds SET version=version+1','UPDATE content_workspace SET revision=revision+1'])await assert.rejects(content!.contentReadPool.query(sql),{code:'42501'});});
 await check('BROWSER','staff without required read permission is denied for preview and bytes',async()=>{await db.pool.query("UPDATE staff_permission_overrides SET allowed=false WHERE staff_id=$1 AND permission='BOOKING_VIEW'",[subject]);const r=await c.request.get(preview);assert.match(await r.text(),/Staff sign-in/);assert.equal((await c.request.get(path)).status(),404);await db.pool.query("UPDATE staff_permission_overrides SET allowed=true WHERE staff_id=$1 AND permission='BOOKING_VIEW'",[subject]);});
 await check('BROWSER','foreign/unowned preview id and invalid query are not exposed',async()=>{assert.equal((await c.request.get(preview.replace(seed.previewId,id(999)))).status(),404);assert.equal((await c.request.get(preview+'&rightsConfirmed=true')).status(),404);});
 await mkdir(evidence+'/screenshots',{recursive:true});
 const shot=async(name:string)=>{const file=evidence+'/screenshots/'+name+'.png';await page.screenshot({path:file,fullPage:true});screenshots.push({file,sha256:createHash('sha256').update(await readFile(file)).digest('hex'),syntheticOnly:true});};
 await page.goto(preview);await expect(page.getByRole('heading',{name:'長さのバランスを見る'})).toBeVisible();
 for(const width of [320,390,768,1440]){
  await page.setViewportSize({width,height:width<768?844:1000});
  for(const [name,length]of [['短め',150],['おすすめ',153],['長め',187]] as const)await check('BROWSER',width+'px '+name+' measured physical ratio and bounds',async()=>{
   await page.getByRole('button',{name:new RegExp('^'+name)}).click();await expect(page.locator('[data-layer="SKI"] img')).toBeVisible();await expect(page.locator('[data-layer="AVATAR"] img')).toBeVisible();
   await page.waitForFunction(()=>Array.from(document.querySelectorAll<HTMLImageElement>('[data-avatar-stage] img')).every(i=>i.complete&&i.naturalHeight>0));
   const m=await page.evaluate(()=>{const layers=Array.from(document.querySelectorAll('[data-layer]')).map(e=>{const b=e.getBoundingClientRect();return {layer:e.getAttribute('data-layer'),x:b.x,y:b.y,width:b.width,height:b.height,right:b.right,bottom:b.bottom};});const b=document.querySelector('[data-avatar-stage]')!.getBoundingClientRect();return {body:layers.find(e=>e.layer==='AVATAR')!,ski:layers.find(e=>e.layer==='SKI')!,stage:{x:b.x,y:b.y,width:b.width,height:b.height,right:b.right,bottom:b.bottom},overflow:document.documentElement.scrollWidth>innerWidth,layers};});
   assert.equal(m.overflow,false);assert.ok(Math.abs(m.ski.height-m.body.height*length/170)<=1);assert.ok(Math.abs(m.ski.bottom-m.body.bottom)<=1);for(const b of m.layers){assert.ok(b.x>=m.stage.x-1&&b.right<=m.stage.right+1&&b.y>=m.stage.y-1&&b.bottom<=m.stage.bottom+1);if(!['SKI','AVATAR'].includes(b.layer!)){assert.ok(Math.abs(b.x-m.body.x)<1&&Math.abs(b.y-m.body.y)<1&&Math.abs(b.height-m.body.height)<1);}}assert.ok(m.ski.x>m.body.right);measurements.push({viewport:width,direction:name,lengthCm:length,expectedRatio:length/170,...m});
   if(width===390||width===1440)await shot(width+'-'+length+'-full-layers');
  });
 }
 await check('BROWSER','appearance switch uses same component and preloaded payload without business POST',async()=>{const old=await page.locator('[data-layer="AVATAR"] img').getAttribute('src');await page.getByRole('button',{name:'見た目 2',exact:true}).click();await expect(page.locator('[data-layer="AVATAR"] img')).not.toHaveAttribute('src',old!);await page.waitForFunction(()=>document.querySelector<HTMLImageElement>('[data-layer="AVATAR"] img')?.naturalHeight===1000);assert.equal(businessPosts,0);await shot('desktop-appearance2');});
 await check('BROWSER','English measurements disclaimer and controls',async()=>{await page.goto(preview+'&locale=en');await expect(page.getByText('Your height',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Appearance 2',exact:true})).toBeVisible();await expect(page.locator('.avatar-disclaimer')).toContainText('completed payment');});
 await check('BROWSER','missing optional layers omit only the affected images',async()=>{await db.pool.query("UPDATE avatar_visuals SET state='DISABLED' WHERE layer IN ('BOOT','JACKET','PANTS')");await page.setViewportSize({width:390,height:844});await page.goto(preview);await expect(page.locator('[data-avatar-stage] img')).toHaveCount(2);await shot('mobile-missing-optional-layers');await db.pool.query("UPDATE avatar_visuals SET state='ACTIVE'");});
 await check('BROWSER','rights revoked after metadata: media404 and refresh removes artwork without fake fallback',async()=>{const state=structuredClone(base);for(const m of state.catalog.media)m.rightsConfirmed=false;await save(state);assert.equal((await c.request.get(path)).status(),404);await page.reload();await expect(page.locator('[data-avatar-stage]')).toHaveCount(0);await expect(page.getByRole('status')).toContainText('表示できる素材がありません');await save(base);});
 await check('BROWSER','displayed layer requests only; no hidden-direction image preload or optimizer cache',async()=>{const requests:string[]=[];page.on('request',r=>{if(new URL(r.url()).pathname.startsWith('/avatar-media/'))requests.push(r.url());});await page.goto(preview);await page.waitForFunction(()=>Array.from(document.querySelectorAll<HTMLImageElement>('[data-avatar-stage] img')).length===5&&Array.from(document.querySelectorAll<HTMLImageElement>('[data-avatar-stage] img')).every(i=>i.complete&&i.naturalHeight>0));assert.equal(requests.length,5);assert.equal(new Set(requests).size,5);assert.equal(await page.locator('img[src*="_next/image"]').count(),0);});
 await check('BROWSER','existing GuestBooking remains separate and no general navigation exposes Avatar',async()=>{const html=await (await anon.request.get('/ja')).text();assert.ok(!html.includes('/preview/avatar'));const source=await readFile('apps/web/src/components/GuestBooking.tsx','utf8');assert.ok(!source.includes('AvatarFitPreview'));});
 await check('PG','renderer/media interactions leave all saved business rows unchanged',async()=>assert.deepEqual(await business(),before));
 await check('BROWSER','no fatal console/hydration errors or external attempts/business POSTs',async()=>{assert.deepEqual(fatal,[]);assert.equal(externalAttempts,0);assert.equal(businessPosts,0);});
 await writeFile(evidence+'/browser-measurements.json',JSON.stringify({engine:'Desktop Chromium and iPhone-sized Chromium viewports; not Safari',tolerance:'1px',measurements},null,2)+'\n');await writeFile(evidence+'/screenshots.json',JSON.stringify(screenshots,null,2)+'\n');
}catch(e){failed=true;console.error('PHASE4_FAILED '+stage+' '+String((e as {code?:string}).code??(e as Error).name));if(e instanceof assert.AssertionError)console.error(JSON.stringify({actual:e.actual,expected:e.expected}));console.error((e as Error).stack?.split('\n').filter(s=>s.includes('/tests/avatar/')).join('\n'));}finally{await browser?.close();await app?.stop();console.log('Owned Avatar browser/Next/PostgreSQL closed.');}
if(failed)process.exit(1);
await writeFile(evidence+'/local-e2e.json',JSON.stringify({status:'PASS',results,pgChecks:results.filter(x=>x.kind==='PG').length,browserChecks:results.filter(x=>x.kind==='BROWSER').length,migrationChanges:0,businessWritesFromRenderer:0,externalProviderOperations:0,externalBrowserAttempts:externalAttempts,businessPosts,cleanup:'Owned browser/Next/PostgreSQL closed'},null,2)+'\n');console.log('PASS '+results.length+' Phase4 PG/browser checks');
