import assert from 'node:assert/strict';
import {randomBytes,randomUUID,createHash} from 'node:crypto';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {chromium,expect} from '@playwright/test';
import {startFlowApp} from '../flow/launcher';
import {seedRecommendation,variants,lengthVariants} from '../recommendation/fixture';
import {bootstrapDevelopmentAdmin} from '../../scripts/bootstrap-staff';
import {loadStaff} from '../../packages/auth/src/staff-auth';
import {QuoteService} from '../../packages/core/src/pricing/quote-service';
import {seedAvatarPhase4} from './phase4-fixture';
import {id} from './fixture';
import type {ContentWorkflowState} from '../../packages/core/src/content/workflow';
const evidence='docs/execution/avatar-phase5',results:{kind:string;name:string;status:'PASS'}[]=[],measurements:unknown[]=[],screenshots:unknown[]=[];
let app:Awaited<ReturnType<typeof startFlowApp>>|undefined,browser:Awaited<ReturnType<typeof chromium.launch>>|undefined,stage='setup',failed=false,externalAttempts=0,visualPosts=0,measuringVisuals=false;
const check=async(kind:string,name:string,fn:()=>Promise<void>)=>{stage=name;await fn();results.push({kind,name,status:'PASS'});console.log('PASS '+kind+' '+name);};
try{
 app=await startFlowApp({publicP0:true,avatarPhase5:true,warmRoutes:true});const {db,origin}=app;
 await seedRecommendation(db.pool,true);await db.pool.query("CREATE OR REPLACE FUNCTION inventory_clock() RETURNS timestamptz LANGUAGE sql VOLATILE AS $$SELECT '2035-01-01T01:00:00Z'::timestamptz$$");
 const stock=await db.pool.connect();try{await stock.query('BEGIN');await stock.query("SELECT set_config('zao.actor','synthetic-avatar-phase5',true),set_config('zao.reason','SYNTHETIC public alternate-length visual fixture',true)");
  await stock.query(`INSERT INTO ledger_assets(id,variant_id,family,initial_store_id,store_id,status,bsl_status,bsl_evidence,notes,source_kind,source_document,source_locator)
   SELECT gen_random_uuid(),id,family,'MOUNTAIN_BASE','MOUNTAIN_BASE','AVAILABLE','NOT_APPLICABLE','','','SYNTHETIC','tests/avatar/phase5-e2e.ts','public-direction-'||id FROM ledger_variants WHERE id=ANY($1::uuid[])`,[[lengthVariants.ski145,variants.skiAlt]]);await stock.query('COMMIT');
 }catch(e){await stock.query('ROLLBACK');throw e;}finally{stock.release();}
 const password=randomBytes(24).toString('base64url'),subject=await bootstrapDevelopmentAdmin(db.pool,{email:'avatar-phase5@example.invalid',displayName:'SYNTHETIC Phase5',password});
 for(const permission of ['PRICE_EDIT','BOOKING_VIEW','HOLD_VIEW','QUOTE_VIEW'])await db.pool.query('INSERT INTO staff_permission_overrides VALUES($1,$2,true)',[subject,permission]);
 await new QuoteService(app.roles.pricingPool,(await loadStaff(db.pool,subject))!).initializePrivate(randomUUID(),'2035-01-01','2035-12-31');
 await check('PG','fresh canonical0001–0032 with dedicated Avatar role',async()=>{assert.equal((await db.pool.query("SELECT count(*)::int n FROM foundation_migrations WHERE id<='0032'")).rows[0].n,32);assert.ok(app!.avatar);});
 browser=await chromium.launch();const c=await browser.newContext({baseURL:origin,viewport:{width:390,height:844}}),anon=await browser.newContext({baseURL:origin}),other=await browser.newContext({baseURL:origin}),staff=await browser.newContext({baseURL:origin});
 for(const context of [c,anon,other,staff]){context.setDefaultTimeout(20000);await context.route('**/*',async route=>{if(new URL(route.request().url()).origin!==origin){externalAttempts++;await route.abort();}else{if(measuringVisuals&&route.request().method()==='POST'&&new URL(route.request().url()).pathname!=='/api/guest/context')visualPosts++;await route.continue();}});}
 // Warm ordinary routes before interaction so Next dev compilation does not reload a submitted form.
 for(const path of ['/ja','/en/book','/staff/login','/staff/ledger','/api/auth/get-session'])await anon.request.get(path);
 const page=await c.newPage(),fatals:string[]=[];page.on('pageerror',()=>fatals.push('PAGE_ERROR'));page.on('console',m=>{if(m.type()==='error'&&/hydration|uncaught|maximum update/i.test(m.text()))fatals.push('CONSOLE_FATAL');});
 await check('BROWSER','ordinary GuestBooking without approved artwork still previews candidates',async()=>{
  await page.goto('/ja/book');await expect(page.getByLabel('利用開始日',{exact:true})).toBeEnabled();await page.getByLabel('利用開始日',{exact:true}).fill('2035-01-05');await page.getByLabel('利用終了日',{exact:true}).fill('2035-01-05');await page.getByRole('button',{name:'用品を選ぶ',exact:true}).click();await page.getByLabel('ポールのサイズ 1',{exact:true}).selectOption('pole-'+variants.pole);await page.getByRole('button',{name:'候補と参考料金を確認',exact:true}).click();await expect(page.getByRole('radio',{name:/おすすめ/})).toBeVisible();await expect(page.locator('[data-avatar-stage]')).toHaveCount(0);
 });
 const draft=await (await c.request.get('/api/guest/draft')).json(),scope=draft.id+'/'+draft.revision+'/person-1',metadataPath='/api/guest/avatar/'+scope;
 await check('PG','zero-art metadata is null and normal business candidate lengths remain present',async()=>{const r=await c.request.get(metadataPath);assert.equal(r.status(),200);assert.deepEqual(await r.json(),{APPEARANCE_1:null,APPEARANCE_2:null});assert.ok(draft.preview.members[0].candidates.RECOMMENDED.lengthCm>0);assert.equal(draft.hold,null);});
 const seed=await seedAvatarPhase4(db.pool,subject),base=structuredClone(seed.state),body=seed.metadata[0]!,imagePath='/guest-avatar-media/'+scope+'/'+body.id+'/'+body.derivativeSha256;
 const save=async(state:ContentWorkflowState)=>db.pool.query('UPDATE content_workspace SET value=$1,revision=revision+1',[JSON.stringify(state)]);
 await other.request.post('/api/guest/context',{headers:{origin},data:{}});
 const business=async()=>{const out:Record<string,unknown>={};for(const table of ['guest_drafts','recommendation_previews','recommendation_selections','inventory_holds','inventory_claims','price_quotes','rental_bookings','rental_payment_attempts','ledger_assets','ledger_poles','wear_pools'])out[table]=(await db.pool.query(`SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]') value FROM ${table} t`)).rows[0].value;return out;};
 // Existing GuestBooking initializes its context on each navigation; that pre-existing
 // idempotent POST is not a renderer action. All business rows are still fingerprinted.
 const before=await business();measuringVisuals=true;
 await check('PG','guest metadata uses own current saved recommendation and strips business/private data',async()=>{
  const r=await c.request.get(metadataPath);assert.equal(r.status(),200);assert.equal(r.headers()['cache-control'],'private, no-store');const value=await r.json();assert.deepEqual(Object.keys(value).sort(),['APPEARANCE_1','APPEARANCE_2']);for(const a of Object.values(value) as {candidates:Record<string,{skiLengthCm:number;skiToBodyRatio:number}|null>}[])for(const d of ['RECOMMENDED','SHORTER','LONGER']){const actual=draft.preview.members[0].candidates[d];if(actual){assert.equal(a.candidates[d]!.skiLengthCm,actual.lengthCm);assert.equal(a.candidates[d]!.skiToBodyRatio,actual.lengthCm/170);}}const text=JSON.stringify(value);assert.doesNotMatch(text,/owner_id|token_sha256|media_id|workspace|bytes|email|password/);
 });
 for(const [name,context]of [['anonymous',anon],['other guest',other]] as const)await check('PG',name+' cannot load victim metadata or bytes',async()=>{for(const p of [metadataPath,imagePath]){const r=await context.request.get(p);assert.equal(r.status(),404);assert.equal(await r.text(),'');}});
 await check('PG','own image GET returns private valid WebP only',async()=>{const r=await c.request.get(imagePath);assert.equal(r.status(),200);assert.equal(r.headers()['content-type'],'image/webp');assert.equal(r.headers()['cache-control'],'private, no-store');assert.ok(r.headers()['vary']?.split(',').map(x=>x.trim().toLowerCase()).includes('cookie')); assert.equal(createHash('sha256').update(await r.body()).digest('hex'),body.derivativeSha256);});
 for(const [name,path] of [
  ['unknown member',imagePath.replace('person-1','person-99')],['stale revision',imagePath.replace('/'+draft.revision+'/', '/'+(draft.revision+1)+'/')],['foreign draft',imagePath.replace(draft.id,id(999))],['private original',imagePath.replace(body.derivativeSha256,seed.originalHash)],['malformed UUID',imagePath.replace(body.id,'bad')],['wrong digest',imagePath.replace(body.derivativeSha256,'b'.repeat(64))],['claims in query',imagePath+'?rightsConfirmed=true'],['malformed metadata',metadataPath+'?avatar=admin'],['encoded traversal',imagePath.replace('person-1','%2e%2e%2fprivate')],
 ] as const)await check('PG',name+' denies404',async()=>{assert.equal((await c.request.get(path)).status(),404);});
 await check('PG','eligible garment outside this saved member offer is denied',async()=>{const v=seed.metadata.find(x=>x.layer==='PANTS')!;assert.equal((await c.request.get('/guest-avatar-media/'+scope+'/'+v.id+'/'+v.derivativeSha256)).status(),404);});
 await check('PG','guest route cannot use staff-only URL or broaden existing public media',async()=>{assert.equal((await c.request.get('/avatar-media/'+body.id+'/'+body.derivativeSha256)).status(),404);assert.equal((await c.request.get('/media/'+body.derivativeSha256+'/400.webp')).status(),404);});
 await check('PG','POST rejects405 and cross-site image read rejects404',async()=>{assert.equal((await c.request.post(imagePath,{data:{}})).status(),405);assert.equal((await c.request.post(metadataPath,{data:{}})).status(),405);assert.equal((await c.request.get(imagePath,{headers:{'sec-fetch-site':'cross-site'}})).status(),404);});
 for(const [name,change]of [
  ['rights revoked',(s:ContentWorkflowState)=>{s.catalog.media[0]!.rightsConfirmed=false;}],['rights expired',(s:ContentWorkflowState)=>{s.catalog.media[0]!.rightsUntil='2000-01-01';}],['internal-only',(s:ContentWorkflowState)=>{s.catalog.media[0]!.internalOnly=true;}],['unprocessed',(s:ContentWorkflowState)=>{s.catalog.media[0]!.processed=false;}],['current release changed',(s:ContentWorkflowState)=>{s.catalog.current=id(999);}],['purpose removed',(s:ContentWorkflowState)=>{delete s.catalog.revisions[0]!.avatarVisualUses;}],['immutable revision mismatch',(s:ContentWorkflowState)=>{s.catalog.revisions[0]!.content.title='changed';}],['digest retarget',(s:ContentWorkflowState)=>{s.catalog.media[0]!.immutableSha256=seed.originalHash;}],['release entry removed',(s:ContentWorkflowState)=>{s.catalog.releases[0]!.entries=[];}],['duplicate metadata',(s:ContentWorkflowState)=>{s.catalog.media.push(s.catalog.media[0]!);}],
 ] as const)await check('PG',name+' denies old guest image URL',async()=>{const state=structuredClone(base);change(state);await save(state);assert.equal((await c.request.get(imagePath)).status(),404);await save(base);});
 await check('PG','inactive visual denies old image URL',async()=>{await db.pool.query("UPDATE avatar_visuals SET state='DISABLED' WHERE id=$1",[body.id]);assert.equal((await c.request.get(imagePath)).status(),404);await db.pool.query("UPDATE avatar_visuals SET state='ACTIVE' WHERE id=$1",[body.id]);});
 await mkdir(evidence+'/screenshots',{recursive:true});
 const shot=async(name:string)=>{const file=evidence+'/screenshots/'+name+'.png';await page.screenshot({path:file,fullPage:true});screenshots.push({file,sha256:createHash('sha256').update(await readFile(file)).digest('hex'),syntheticOnly:true});};
 const metadataRequests:string[]=[];page.on('request',r=>{if(new URL(r.url()).pathname.startsWith('/api/guest/avatar/'))metadataRequests.push(r.url());});
 await page.reload();await expect(page.locator('[data-avatar-stage]')).toHaveCount(1);await page.waitForFunction(()=>Array.from(document.querySelectorAll<HTMLImageElement>('[data-avatar-stage] img')).every(i=>i.complete&&i.naturalHeight>0));
 const requestsBefore=metadataRequests.length;
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:width<768?844:1000});for(const [direction,label] of [['SHORTER','短め'],['RECOMMENDED','おすすめ'],['LONGER','長め']] as const)await check('BROWSER',width+'px '+direction+' actual guest DOM ratio and common floor',async()=>{
  const offered=draft.preview.members[0].candidates[direction];assert.ok(offered);await page.getByRole('radio',{name:new RegExp(label)}).check();
  await page.waitForFunction(()=>Array.from(document.querySelectorAll<HTMLImageElement>('[data-avatar-stage] img')).every(i=>i.complete&&i.naturalHeight>0));
  const m=await page.evaluate(()=>{const b=document.querySelector('[data-layer="AVATAR"]')!.getBoundingClientRect(),s=document.querySelector('[data-layer="SKI"]')!.getBoundingClientRect();return {bodyHeight:b.height,skiHeight:s.height,bodyBottom:b.bottom,skiBottom:s.bottom,overflow:document.documentElement.scrollWidth>innerWidth};});
  assert.equal(m.overflow,false);assert.ok(Math.abs(m.skiHeight-m.bodyHeight*offered.lengthCm/170)<=1);assert.ok(Math.abs(m.skiBottom-m.bodyBottom)<=1);measurements.push({width,direction,lengthCm:offered.lengthCm,expectedRatio:offered.lengthCm/170,...m});if(width===390||width===1440)await shot(width+'-'+direction);
 });}
 await check('BROWSER','appearance switch is local, updates body and causes no metadata reload or POST',async()=>{const old=await page.locator('[data-layer="AVATAR"] img').getAttribute('src');await page.getByRole('button',{name:'見た目 2',exact:true}).click();await expect(page.locator('[data-layer="AVATAR"] img')).not.toHaveAttribute('src',old!);await page.waitForFunction(()=>document.querySelector<HTMLImageElement>('[data-layer="AVATAR"] img')?.naturalHeight===1000);assert.equal(metadataRequests.length,requestsBefore);assert.equal(visualPosts,0);assert.equal(await page.locator('img[src*="_next/image"]').count(),0);await shot('desktop-appearance2');});
 await check('BROWSER','English candidate page keeps full disclaimer and appearance labels',async()=>{await page.goto('/en/book');await expect(page.getByRole('button',{name:'Appearance 1',exact:true})).toBeVisible();await expect(page.locator('.avatar-disclaimer')).toContainText('completed payment');});
 await check('BROWSER','revoked rights refresh omits renderer and keeps business candidates usable',async()=>{const state=structuredClone(base);for(const m of state.catalog.media)m.rightsConfirmed=false;await save(state);assert.equal((await c.request.get(imagePath)).status(),404);await page.reload();await expect(page.getByRole('radio',{name:/RECOMMENDED/i})).toBeVisible();await expect(page.locator('[data-avatar-stage]')).toHaveCount(0);await save(base);});
 await check('BROWSER','optional artwork HTTP failure does not fail candidate step or invent art',async()=>{await page.route('**/api/guest/avatar/**',route=>route.fulfill({status:503,body:''}));await page.reload();await expect(page.getByRole('radio',{name:/RECOMMENDED/i})).toBeVisible();await expect(page.locator('[data-avatar-stage]')).toHaveCount(0);await page.unroute('**/api/guest/avatar/**');});
 await check('PG','all visual reads and switches preserve guest/business rows exactly',async()=>{assert.deepEqual(await business(),before);assert.equal(visualPosts,0);});
 measuringVisuals=false;
 const staffPage=await staff.newPage();
 await check('BROWSER','normal local staff login for permission comparison',async()=>{
  await staff.request.get('/api/auth/get-session');
  await staffPage.goto('/staff/login');await staffPage.getByLabel('メールアドレス',{exact:true}).fill('avatar-phase5@example.invalid');await staffPage.getByLabel('パスワード',{exact:true}).fill(password);
  const signed=staffPage.waitForResponse(r=>new URL(r.url()).pathname==='/api/auth/sign-in/email');await staffPage.getByRole('button',{name:'ログイン',exact:true}).click();const response=await signed;console.log('LOCAL_STAFF_SIGNIN_HTTP '+response.status());assert.equal(response.status(),200);await staffPage.waitForURL(origin+'/staff/ledger');
 });
 const staffImage='/avatar-media/'+body.id+'/'+body.derivativeSha256,staffPreview='/preview/avatar?preview='+seed.previewId+'&member='+seed.memberKey;
 await check('PG','full staff permissions retain preview and derivative access',async()=>{assert.equal((await staff.request.get(staffImage)).status(),200);assert.ok((await (await staff.request.get(staffPreview)).text()).includes(body.derivativeSha256));});
 for(const missing of ['HOLD_VIEW','QUOTE_VIEW'])await check('PG','PHASE4-1: BOOKING_VIEW with '+missing+' denied blocks both staff surfaces',async()=>{await db.pool.query('UPDATE staff_permission_overrides SET allowed=false WHERE staff_id=$1 AND permission=$2',[subject,missing]);assert.equal((await staff.request.get(staffImage)).status(),404);assert.match(await (await staff.request.get(staffPreview)).text(),/Staff sign-in/);await db.pool.query('UPDATE staff_permission_overrides SET allowed=true WHERE staff_id=$1 AND permission=$2',[subject,missing]);});
 await check('PG','PHASE4-1 exact counterexample: BOOKING_VIEW only denies preview and bytes',async()=>{await db.pool.query("UPDATE staff_permission_overrides SET allowed=false WHERE staff_id=$1 AND permission IN ('HOLD_VIEW','QUOTE_VIEW')",[subject]);assert.equal((await staff.request.get(staffImage)).status(),404);assert.match(await (await staff.request.get(staffPreview)).text(),/Staff sign-in/);await db.pool.query("UPDATE staff_permission_overrides SET allowed=true WHERE staff_id=$1 AND permission IN ('HOLD_VIEW','QUOTE_VIEW')",[subject]);});
 await check('PG','guest context expiry/revocation invalidate old image capability',async()=>{const ctx=(await db.pool.query('SELECT context_id FROM guest_drafts WHERE id=$1',[draft.id])).rows[0].context_id;await db.pool.query('UPDATE guest_contexts SET revoked_at=inventory_clock() WHERE id=$1',[ctx]);assert.equal((await c.request.get(imagePath)).status(),404);assert.equal((await c.request.get(metadataPath)).status(),404);await db.pool.query('UPDATE guest_contexts SET revoked_at=NULL WHERE id=$1',[ctx]);await db.pool.query("CREATE OR REPLACE FUNCTION inventory_clock() RETURNS timestamptz LANGUAGE sql VOLATILE AS $$SELECT '2035-01-03T01:00:00Z'::timestamptz$$");assert.equal((await c.request.get(imagePath)).status(),404);await db.pool.query("CREATE OR REPLACE FUNCTION inventory_clock() RETURNS timestamptz LANGUAGE sql VOLATILE AS $$SELECT '2035-01-01T01:00:00Z'::timestamptz$$");});
 await check('PG','normal draft revision change immediately invalidates prior metadata/media URLs',async()=>{const r=await c.request.post('/api/guest/draft',{headers:{origin},data:{draftId:draft.id,expectedRevision:draft.revision,input:draft.input}});assert.equal(r.status(),200);const saved=await r.json();assert.equal(saved.revision,draft.revision+1);assert.equal((await c.request.get(imagePath)).status(),404);assert.equal((await c.request.get(metadataPath)).status(),404);const preview=await c.request.post('/api/guest/preview',{headers:{origin},data:{draftId:saved.id,expectedRevision:saved.revision}});assert.equal(preview.status(),200);});
 await check('BROWSER','existing explicit candidate selection and group estimate remain functional',async()=>{await page.goto('/ja/book');await page.getByRole('radio',{name:/おすすめ/}).check();await page.getByLabel('全員のサイズ・モデル条件・ウェア構成を確認した').check();await page.getByRole('button',{name:'全員分の最終確認へ'}).click();await expect(page.getByRole('region',{name:'全員分の確認'})).toContainText('全員分の参考総額');assert.equal((await db.pool.query('SELECT count(*)::int n FROM inventory_holds')).rows[0].n,0);assert.equal((await db.pool.query('SELECT count(*)::int n FROM rental_payment_attempts')).rows[0].n,0);});
 await check('BROWSER','logout invalidates saved avatar URLs without affecting another guest',async()=>{const logout=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/guest/logout');await page.getByRole('button',{name:'この予約画面を閉じる'}).click();assert.equal((await logout).status(),200);await page.waitForURL(origin+'/ja',{waitUntil:'domcontentloaded'});assert.equal((await c.request.get(imagePath)).status(),404);assert.equal((await other.request.get('/api/guest/draft')).status(),200);});
 await check('BROWSER','no fatal errors, hydration errors or external attempts',async()=>{assert.deepEqual(fatals,[]);assert.equal(externalAttempts,0);});
 await writeFile(evidence+'/browser-measurements.json',JSON.stringify({engine:'Chromium desktop/mobile viewports, not Safari',measurements},null,2)+'\n');await writeFile(evidence+'/screenshots.json',JSON.stringify(screenshots,null,2)+'\n');
}catch(e){failed=true;console.error('PHASE5_E2E_FAILED '+stage+' '+String((e as {code?:string}).code??(e as Error).name));if(e instanceof assert.AssertionError)console.error(JSON.stringify({actual:e.actual,expected:e.expected}));console.error((e as Error).stack?.split('\n').filter(s=>s.includes('/tests/avatar/')).join('\n'));}
finally{await browser?.close();await app?.stop();console.log('Owned Phase5 browser/Next/PostgreSQL closed.');}
if(failed)process.exit(1);
await writeFile(evidence+'/local-e2e.json',JSON.stringify({status:'PASS',results,pgChecks:results.filter(x=>x.kind==='PG').length,browserChecks:results.filter(x=>x.kind==='BROWSER').length,visualBusinessPosts:visualPosts,externalAttempts,approvedRealArtwork:false,syntheticFixturesOnly:true,cleanup:'Owned browser/Next/PostgreSQL closed'},null,2)+'\n');
