import assert from 'node:assert/strict';
import {createHash,randomBytes} from 'node:crypto';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {Pool} from 'pg';
import {migrate,migrationPlan,migrationsDirectory} from '../../packages/db/src/index';
import {startIsolatedPostgres} from '../../scripts/postgres';
import {seedInventory,fid,variants} from '../inventory/fixture';
import {PostgresAvatarVisuals} from '../../packages/db/src/avatar-visuals';
import {withAvatarVisualization} from '../../packages/core/src/avatar/visualization';
import {planPrivateRelease,applyPersistedPrivateRelease,type CatalogReleaseState,type ContentRevision} from '../../packages/core/src/content/release-plan';
import type {ContentWorkflowState} from '../../packages/core/src/content/workflow';
import type {VisualMetadata} from '../../packages/contracts/src/avatar-visualization';
import {id,now,recommendation,visual,visualGrant} from './fixture';
const results:{name:string;status:'PASS'}[]=[];
const check=async(name:string,fn:()=>Promise<void>)=>{await fn();results.push({name,status:'PASS'});console.log('PASS '+name);};
const expected=JSON.parse(await readFile('docs/execution/avatar-a2-a3/migration-hashes.json','utf8')) as {id:string;file:string;sha256:string;unchangedFromR15:boolean}[];
await check('all 30 historical migration hashes unchanged; new 0031 checksum tracked',async()=>{assert.equal(expected.length,31);assert.equal(expected.filter(x=>x.unchangedFromR15).length,30);for(const [i,m]of migrationPlan.entries()){assert.equal(m.id,expected[i]!.id);assert.equal(m.file,expected[i]!.file);assert.equal(createHash('sha256').update(await readFile(migrationsDirectory+'/'+m.file)).digest('hex'),expected[i]!.sha256);}});
const fresh=await startIsolatedPostgres();try{await check('fresh empty PostgreSQL -> canonical 0001–0031',async()=>{await migrate(fresh.pool);assert.deepEqual((await fresh.pool.query('SELECT id,checksum FROM foundation_migrations ORDER BY id')).rows,expected.map(x=>({id:x.id,checksum:x.sha256})));});}finally{await fresh.stop();}
const db=await startIsolatedPostgres();let reader:Pool|undefined;
try{
 for(const m of migrationPlan.slice(0,30)){const sql=await readFile(migrationsDirectory+'/'+m.file,'utf8');await db.pool.query(sql);await db.pool.query('CREATE TABLE IF NOT EXISTS foundation_migrations(id text PRIMARY KEY,checksum text NOT NULL)');await db.pool.query('INSERT INTO foundation_migrations VALUES($1,$2)',[m.id,createHash('sha256').update(sql).digest('hex')]);}
 await seedInventory(db.pool);
 const fingerprint=async()=>{
  const tables=['ledger_models','ledger_variants','ledger_assets','ledger_poles','wear_pools','inventory_holds','inventory_claims','booking_records','payment_attempts'];const out:Record<string,unknown>={};
  for(const table of tables){if((await db.pool.query('SELECT to_regclass($1) AS name',[table])).rows[0].name)out[table]=(await db.pool.query(`SELECT coalesce(jsonb_agg(to_jsonb(x) ORDER BY to_jsonb(x)::text),'[]') AS value FROM ${table} x`)).rows[0].value;}
  return out;
 };
 await check('populated R15 0030 -> additive 0031 preserves business rows exactly',async()=>{const before=await fingerprint();await migrate(db.pool);assert.equal((await db.pool.query('SELECT count(*)::int n FROM foundation_migrations')).rows[0].n,31);assert.deepEqual(await fingerprint(),before);});
 await check('zero visuals is a normal empty read and preserves business object',async()=>{const x=recommendation();const repo=new PostgresAvatarVisuals(db.pool);assert.deepEqual(await repo.read([],now),[]);assert.strictEqual(await withAvatarVisualization(async()=>x,repo,now),x.recommendation);});
 const derivative=Buffer.from('SYNTHETIC DERIVATIVE FIXTURE — NOT AN UPLOADED ASSET'),sha=createHash('sha256').update(derivative).digest('hex');
 await db.pool.query('INSERT INTO content_media_objects VALUES($1,$2)',[sha,derivative]);
 const metadata=[visual(1,{derivativeSha256:sha,sortOrder:4}),visual(2,{layer:'AVATAR',avatarType:'APPEARANCE_1',derivativeSha256:sha,sortOrder:1}),visual(3,{layer:'BOOT',derivativeSha256:sha,sortOrder:2}),visual(4,{layer:'JACKET',derivativeSha256:sha,sortOrder:2}),visual(8,{layer:'AVATAR',avatarType:'APPEARANCE_2',derivativeSha256:sha,sortOrder:1}),visual(9,{layer:'PANTS',derivativeSha256:sha,sortOrder:3})];
 const revision:ContentRevision={id:id(90),offerCode:'synthetic-rental-info',locale:'ja',content:{title:'Synthetic rental guidance',summary:'Only a local fixture',fit_note:'No product guarantee'},sourceRevision:null,translationApproved:false,mediaIds:['synthetic-media'],commercialRevision:'synthetic-v1',avatarVisualUses:metadata.map(visualGrant)};
 const catalog:CatalogReleaseState={current:null,draftIds:{'synthetic-rental-info/ja':revision.id},revisions:[revision],media:[{id:'synthetic-media',processed:true,rightsConfirmed:true,rightsUntil:null,alt:'Synthetic reference illustration',immutableSha256:sha,internalOnly:false}],commercialRevisions:{'synthetic-rental-info':'synthetic-v1'},releases:[]};
 const plan=planPrivateRelease(catalog,{id:id(91),entries:[revision.id],expectedCurrent:null,restoreOf:null},now);assert.deepEqual(plan.issues,[]);
 let state:ContentWorkflowState={catalog:applyPersistedPrivateRelease(catalog,plan,now).state,plans:{},requests:{},audit:[],outbox:[]};
 const save=async()=>{await db.pool.query('INSERT INTO content_workspace(id,value) VALUES(true,$1) ON CONFLICT(id) DO UPDATE SET value=excluded.value,revision=content_workspace.revision+1',[JSON.stringify(state)]);};
 await db.pool.query('INSERT INTO content_revision_records VALUES($1,$2)',[revision.id,JSON.stringify(revision)]);await db.pool.query("INSERT INTO content_outbox VALUES($1,'PRIVATE_PREVIEW_CHANGED')",[id(91)]);await save();
 const insert=async(v:VisualMetadata)=>{await db.pool.query(`INSERT INTO avatar_visuals(id,layer,avatar_type,match_kind,model_id,variant_id,season,ski_length_cm,media_id,derivative_sha256,revision_id,release_id,state,sort_order,anchor_x,anchor_y,position_x,position_y) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18)`,[v.id,v.layer,v.avatarType,v.match,v.modelId,v.variantId,v.season,v.skiLengthCm,v.mediaId,v.derivativeSha256,v.revisionId,v.releaseId,v.state,v.sortOrder,v.anchor.x,v.anchor.y,v.position.x,v.position.y]);};
 const repo=new PostgresAvatarVisuals(db.pool);
 await check('nullable model/variant and explicit existing content purpose grant resolve in stable order',async()=>{for(const v of metadata)await insert(v);const rows=await repo.read([],now);assert.deepEqual(rows.map(x=>x.id),[id(2),id(8),id(3),id(4),id(9),id(1)]);assert.ok(rows.every(x=>x.modelId===null&&x.variantId===null&&x.derivativeSha256===sha));});
 await check('ambiguous active generic/default rejected; disabled alternatives allowed',async()=>{await assert.rejects(insert(visual(5,{derivativeSha256:sha})),{code:'23505'});await insert(visual(5,{derivativeSha256:sha,state:'DISABLED'}));await assert.rejects(db.pool.query("UPDATE avatar_visuals SET state='ACTIVE' WHERE id=$1",[id(5)]),{code:'23505'});});
 await check('invalid media/revision/release foreign keys and appearance/position rejected',async()=>{for(const changes of [{derivativeSha256:'b'.repeat(64)},{revisionId:id(900)},{releaseId:id(901)}])await assert.rejects(insert(visual(6,{derivativeSha256:sha,state:'DISABLED',...changes})),{code:'23503'});for(const changes of [{layer:'AVATAR' as const},{anchor:{x:NaN,y:1}},{position:{x:2,y:1}}])await assert.rejects(insert(visual(6,{derivativeSha256:sha,state:'DISABLED',...changes})),{code:'23514'});});
 const original=structuredClone(state);
 const altered=async(change:(s:ContentWorkflowState)=>void)=>{state=structuredClone(original);change(state);await save();assert.deepEqual(await repo.read([],now),[]);state=structuredClone(original);await save();};
 await check('revoked/expired/internal-only/unprocessed/missing rights excluded including generic fallback',async()=>{for(const c of [{rightsConfirmed:false},{rightsUntil:'2034-12-31T00:00:00Z'},{rightsUntil:'2035-01-01T00:00:00Z'},{internalOnly:true},{processed:false}])await altered(s=>Object.assign(s.catalog.media[0]!,c));});
 await check('stale release, absent purpose grant and mutated immutable revision excluded',async()=>{await altered(s=>{s.catalog.current=null;});await altered(s=>{s.catalog.releases[0]!.entries=[];});await altered(s=>{delete s.catalog.revisions[0]!.avatarVisualUses;});await altered(s=>{s.catalog.revisions[0]!.content.title='Unreleased replacement';});});
 await check('general model photo rights do not authorize Avatar; digest retargeting denied',async()=>{await db.pool.query("UPDATE avatar_visuals SET media_id='ungranted-media' WHERE id=$1",[id(1)]);assert.ok(!(await repo.read([],now)).some(x=>x.id===id(1)));await db.pool.query("UPDATE avatar_visuals SET media_id='synthetic-media' WHERE id=$1",[id(1)]);await altered(s=>{s.catalog.media[0]!.immutableSha256='b'.repeat(64);});});
 await check('all inactive leaves recommendation unchanged; soft-disable timestamps and stable identity',async()=>{await db.pool.query("UPDATE avatar_visuals SET state='DISABLED'");const x=recommendation();assert.strictEqual(await withAvatarVisualization(async()=>x,repo,now),x.recommendation);await assert.rejects(db.pool.query('UPDATE avatar_visuals SET id=$1 WHERE id=$2',[id(999),id(1)]));assert.ok((await db.pool.query('SELECT bool_and(updated_at>=created_at) ok FROM avatar_visuals')).rows[0].ok);await db.pool.query("UPDATE avatar_visuals SET state='ACTIVE' WHERE id=ANY($1::uuid[])",[metadata.map(x=>x.id)]);});
 await db.pool.query("BEGIN;SELECT set_config('zao.actor','synthetic-avatar-seed',true),set_config('zao.reason','Synthetic model season fixture',true)");
 await db.pool.query("INSERT INTO ledger_models(id,code,name,brand,family,notes,source_kind,source_document,source_locator,catalog_season) VALUES($1,'AVATAR-SYNTHETIC','Synthetic exact ski','SYNTHETIC','SKI','','SYNTHETIC','tests/avatar/postgres.ts','model','2035/36')",[id(70)]);await db.pool.query("INSERT INTO ledger_variants(id,model_id,family,age,tier,size,notes,source_kind,source_document,source_locator) VALUES($1,$2,'SKI','ADULT','PREMIUM','150 cm','','SYNTHETIC','tests/avatar/postgres.ts','premium')",[id(71),id(70)]);await db.pool.query('COMMIT');
 const exact=visual(7,{derivativeSha256:sha,match:'EXACT_PROMISE',modelId:id(70),variantId:id(71),season:'2035/36',skiLengthCm:150});
 await check('exact PREMIUM model/variant/season/length relation rejects invalid references and mismatch',async()=>{for(const changes of [{modelId:fid(1002)},{variantId:variants.boot},{season:'2034/35'},{skiLengthCm:155},{variantId:variants.ski},{variantId:id(999)}])await assert.rejects(insert({...exact,...changes}),{code:'23514'});await insert(exact);assert.ok(!(await repo.read([id(71)],now)).some(v=>v.id===exact.id),'new row still lacks purpose-specific release grant');});
 // Explicit new immutable content revision + release, using existing release planner.
 await check('new immutable release grants exact promise; business schema rejects model season drift',async()=>{const r={...structuredClone(revision),id:id(92),avatarVisualUses:[...metadata.map(visualGrant),visualGrant(exact)]};state.catalog.revisions.push(r);state.catalog.draftIds['synthetic-rental-info/ja']=r.id;const p=planPrivateRelease(state.catalog,{id:id(93),entries:[r.id],expectedCurrent:state.catalog.current,restoreOf:null},now);assert.deepEqual(p.issues,[]);state.catalog=applyPersistedPrivateRelease(state.catalog,p,now).state;await db.pool.query('INSERT INTO content_revision_records VALUES($1,$2)',[r.id,JSON.stringify(r)]);await db.pool.query("INSERT INTO content_outbox VALUES($1,'PRIVATE_PREVIEW_CHANGED')",[id(93)]);await db.pool.query('UPDATE avatar_visuals SET revision_id=$1,release_id=$2',[id(92),id(93)]);await save();assert.ok((await repo.read([id(71)],now)).some(v=>v.id===exact.id));await db.pool.query("BEGIN;SELECT set_config('zao.actor','synthetic-avatar-seed',true),set_config('zao.reason','Synthetic model drift',true)");await assert.rejects(db.pool.query("UPDATE ledger_models SET catalog_season='2036/37' WHERE id=$1",[id(70)]),{code:'23514'});await db.pool.query('ROLLBACK');assert.ok((await repo.read([id(71)],now)).some(v=>v.id===exact.id));});
 const role=db.identity.namespace+'_visual_reader',password=randomBytes(24).toString('hex');await db.pool.query(`CREATE ROLE ${role} LOGIN PASSWORD '${password}'`);await db.pool.query(`GRANT CONNECT ON DATABASE ${db.identity.database} TO ${role}`);await db.pool.query(`GRANT USAGE ON SCHEMA public TO ${role}`);await db.pool.query(`GRANT SELECT ON avatar_visuals,content_workspace,content_revision_records,content_outbox,ledger_models,ledger_variants TO ${role}`);await db.pool.query(`GRANT EXECUTE ON FUNCTION avatar_visual_variant_matches(uuid,uuid,text,double precision) TO ${role}`);
 reader=new Pool({host:'127.0.0.1',port:db.identity.dbPort,database:db.identity.database,user:role,password});
 await check('read-only role resolves all directions/layers in one SELECT and cannot mutate business or visuals/read private bytes',async()=>{const before=await fingerprint();let queries=0;const q={query:async(text:string,values:unknown[])=>{queries++;assert.match(text.trim(),/^SELECT /);return reader!.query(text,values);}} as unknown as Pick<Pool,'query'>;const x=recommendation();const out=await withAvatarVisualization(async()=>x,new PostgresAvatarVisuals(q),now,'APPEARANCE_1');assert.ok(out.visualization);assert.equal(queries,1);for(const sql of ["UPDATE avatar_visuals SET state='DISABLED'",'DELETE FROM avatar_visuals',"UPDATE ledger_assets SET status='RETIRED'",'DELETE FROM inventory_holds','UPDATE content_workspace SET revision=revision+1','SELECT bytes FROM content_media_objects'])await assert.rejects(reader!.query(sql),{code:'42501'});assert.deepEqual(await fingerprint(),before);});
 await check('no PUBLIC grants, no image bytes/URL/credential columns, no security-definer escalation',async()=>{const privileges=(await db.pool.query("SELECT count(*)::int n FROM pg_class c CROSS JOIN LATERAL aclexplode(c.relacl) a WHERE c.relname='avatar_visuals' AND a.grantee=0")).rows[0].n;assert.equal(privileges,0);const columns=(await db.pool.query("SELECT column_name,data_type FROM information_schema.columns WHERE table_name='avatar_visuals'")).rows;assert.ok(columns.every(c=>c.data_type!=='bytea'&&!/url|credential|password|quantity/.test(c.column_name)));assert.ok((await db.pool.query("SELECT bool_and(NOT prosecdef) ok FROM pg_proc WHERE proname LIKE 'avatar_visual_%'")).rows[0].ok);});
}finally{await reader?.end();await db.stop();}
await mkdir('docs/execution/avatar-a2-a3',{recursive:true});await writeFile('docs/execution/avatar-a2-a3/local-db.json',JSON.stringify({status:'PASS',engine:'REAL_LOCAL_POSTGRESQL',freshAndUpgrade:true,checks:results.length,results,oldMigrationHashesUnchanged:30,newMigration:'0031',businessMutationsFromVisualPath:0,externalProviderRequests:0,queryCountPerRecommendation:1,cleanup:'Owned pools/clusters closed'},null,2)+'\n');
console.log(`PASS ${results.length} Avatar local PostgreSQL checks; external0; owned pools/clusters closed.`);
